### ISSUE TITLE
Failures in [sig-network] Network should set TCP CLOSE_WAIT timeout and Services should be rejected when no endpoints exist

### ISSUE THREAD

**Issue by hakman** [cilium/cilium#10002]
## Support

We are adding e2e tests to the [Kops](https://github.com/kubernetes/kops) project for most Kubernetes network plugins, Cilium included. Seems that some of the tests are failing and wanted to get some feedback here about them.
https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-aws-cni-cilium

The tests that fail are:
```
[sig-network] Network should set TCP CLOSE_WAIT timeout
[sig-network] Services should be rejected when no endpoints exist
```

Would like to know if there are any settings to make these pass or if there is any plan to fix them. Thanks!

**Comment by brb** [comment]
@hakman Thanks for reporting! What is a configuration of Cilium in the e2e tests?

**Comment by hakman** [comment]
@brb thanks for checking this. The configuration is the following:
* Debian Stretch
* Kubernetes 1.18-alpha.2
* Cilium v1.6.4

The template we use for Cilium is the following:
https://github.com/kubernetes/kops/blob/master/upup/models/cloudup/resources/addons/networking.cilium.io/k8s-1.12.yaml.template

We will try the same config, but with RHEL 8 (newer kernel) and see if anything changes.

**Comment by aanm** [comment]
@hakman thanks for opening the GH issue.

In the test matrix I can't find the `[sig-network] Network should set TCP CLOSE_WAIT timeout` error. 

For the `[sig-network] Services should be rejected when no endpoints exist` it seems the test wants the connection to be refused with the following syscall https://github.com/kubernetes/kubernetes/blob/4c3aa3f26b84929e8fb4b6a1c3faaea43e7586fa/test/images/agnhost/connect/connect.go#L74

**Comment by hakman** [comment]
@aanm thank you also for reviewing the Cilium PRs from the Kops repo lately.

We had a bit of trouble with our tests during the last week and results were a mess.
The `[sig-network] Network should set TCP CLOSE_WAIT timeout error` issue is gone after changing the base image to Ubuntu 18.04. I think it is just disabled, but you can check an older test run:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-cni-cilium/1223213134521569280

The `[sig-network] Services should be rejected when no endpoints exist` test expects that connections to services without endpoints should be rejected. Seems to be affecting also Calico and Weave and there is also a discussion in one of the Kubernetes issues:
https://github.com/kubernetes/kubernetes/issues/78994

**Comment by olemarkus** [comment]
FWIW I can confirm the e2e still fails on this issue with version 1.8

**Comment by aojea** [comment]
@aanm @brb @joestringer the expected behavior in Kubernetes, when a Service does not have endpoints, i.e. , there are no active backends, is to REJECT the connection, kube-proxy uses the iptables -j REJECT IIRC is an icmp unreachable by default ... these e2e tests fail because  Cilum drops the packet instead of rejecting 

Do you have any idea if is it possible to generate an ICMP packet or at least a TCP reset for a Service without backends?

I'm happy to try it if you give me some guidance

**Comment by joestringer** [comment]
@aojea How does the test detect the "rejection" condition? Depending on the protocol (TCP/UDP/SCTP), the rejection packet may look different. Also, if we do this rejection at the socket layer then there may not even be any packets to look at yet. It would be good to ensure that the test does not rely too much on specifics of a particular implementation.

Broadly I think there's a few possible solutions to this:
1. Implement directly in eBPF
    1. Socket-level: Return an error code to the application to prevent connection in the first place
    2. Packet-level: Ensure the "no services" error condition conditional exists, then from there, use packet pointers to rewrite the content of the packet + resize it, then redirect the packet back towards its source (similar to "hairpin").
1. Redirect such packets to an interface to generate the reject packet
   * Requires a bit more coordination to create such an interface, ensure that the Linux stack correctly rejects the packet, ensure the response is routed back to the source

I'll CC also @cilium/sig-datapath for perspectives.

**Comment by aojea** [comment]
> It would be good to ensure that the test does not rely too much on specifics of a particular implementation.

Yeah, the problem is that in kubernetes all the e2e are part from the same binary, but we should focus only on the e2e that describe behaviors, in this case one does but the other not

> sig-network] Network should set TCP CLOSE_WAIT timeout

This is an e2e but is just a regression test for a kube-proxy, we should not run these test outside of kubernetes

> [sig-network] Services should be rejected when no endpoints exist

This test is the one that defines that behavior expected by the users when a Services does not have endpoints.

This test creates a Service without endpoints and tries to connect from a client to the service, and then assert on the client error,

The test expects a "connection refused"  error in the client, but this is unspecified, it may be any other error that indicates to the user that the connection was rejected. What this test never should do is to assert on the packets generated.

I can see that you already had similar requests

https://github.com/cilium/cilium/issues/13451
https://github.com/cilium/cilium/issues/17944
