### ISSUE TITLE
Improve cilium policy trace usability

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1005]
When using `cilium policy trace`, the user is required to either enter the labels or the identity:
e.g.
```
cilium policy trace -s foo -d bar
cilium policy trace -s 260 -d 700
```

Add support to:
 - [x] `--src-identity / --dst-identity`
 - [x] podname + namespace (`--src-k8s-pod [namespace:]podname / --dst-k8s-pod [namespace:]podname`)
 - [x] endpoint id (`--src-endpoint / --dst-endpoint`)
 - [ ] pod yaml file (`--read-yaml FILE`) (if not provided, cilium queries the k8s API server)

**Comment by ianvernon** [comment]
Discussed in chat with @tgraf - currently `--src` and `--dst` can take a security identity as a parameter. Will remove that functionality from these flags and put it in the `--src-identity` and `--dst-identity` flags.

**Comment by ianvernon** [comment]
@tgraf - should only one source / destination type be providable by the user, or can we allow multiple source types (i.e., security identity, labels, etc.) in combination with multiple destination types?

**Comment by ianvernon** [comment]
#1046 affects my progress for grabbing the pod name + namespace information, so I'm holding off on that for now until it gets merged.

I've gotten `src-identity`, `dst-identity`, `src-endpoint`, `dst-endpoint` working fine - it's trivial to get the labels from these values. 

What's murky for me is "pod yaml file (--read-yaml FILE) (if not provided, cilium queries the k8s API server)"

@tgraf can you please clarify what you mean by "if not provided"? What would not be provided? Should this flag be used in tandem with other flags (e.g., pod name + namespace)? What if a YAML file has definitions for more than two pods ?

**Comment by ianvernon** [comment]
#1046 does not change which labels are stored, just where they are stored (endpoint structure vs. container structure). This means that the pod name will not be stored in the endpoint, as it is a label that we ignore (see `pkg/labels/filter.go:defaultLabelPrefixCfg()`). We need a way to obtain this information that is not coupled with the labels themselves, as we need to filter out certain labels in order to ensure that each endpoint of the same service has the same security ID, which is determined by labels of which Cilium is aware. 

I proposed that we create another set of labels in the Labels structure 'Unfiltered', which contains all labels, but @aanm was concerned that this would fall out of sync with k8s since k8s can add / remove labels. I then proposed that we could query the k8's API directly if we do a 'GET' of the labels for a specific endpoint, but @aanm and I both agreed that this is not very efficient, as the pod name shouldn't change. 

@aanm mentioned that we could store the pod name directly as a field in the endpoint structure itself, but I dislike mixing in Kubernetes-related configuration as part of the endpoint structure itself.

@aanm also proposed adding a field called 'extra' to the endpoint that would look something like the following:
```
type extra struct{
    podname string
}

type endpoint struct {
   ID string
    ...
   misc extra
}
```

This adds a pseudo 'junk-drawer' for stuff we need that is related to the endpoint, but I think it is basically the same as adding the pod-name as a field within the endpoint directly. Out of all of these, I think adding the field directly in the endpoint is the best bet.

**Comment by tgraf** [comment]
General remark: Would be great if the functionality that you are writing here is done in `pkg/` so we can also use it from `cilium monitor` afterwards to run `cilium monitor --related-to pod-x`

> @tgraf can you please clarify what you mean by "if not provided"? What would not be provided? Should this flag be used in tandem with other flags (e.g., pod name + namespace)? What if a YAML file has definitions for more than two pods ?

What I had in mind is the following: User queries `pod-name` and cilium will query the k8s API server to search for the pod and retrieve the spec including the labels. It's basically the same as reading from yaml except that the input is not from the file but the JSON that was returned by the API server which will contain the same information. The API server variant is for running pods. The file based variant is for jobs which have not been scheduled yet.

> I proposed that we create another set of labels in the Labels structure 'Unfiltered', which contains all labels, but @aanm was concerned that this would fall out of sync with k8s since k8s can add / remove labels. I then proposed that we could query the k8's API directly if we do a 'GET' of the labels for a specific endpoint, but @aanm and I both agreed that this is not very efficient, as the pod name shouldn't change.

As for the pod name, let's just keep it as part of the endpoint structure. This will never change for a running endpoint.

As for additional labels, we'll need them anyway long term to complement the proxy logs with labels to represent build information and so. I would call them "informational" though. Let's keep it outside of the scope of this PR though if we don't strictly need it.

> @aanm mentioned that we could store the pod name directly as a field in the endpoint structure itself, but I dislike mixing in Kubernetes-related configuration as part of the endpoint structure itself.

Agreed with the dislike to store it directly in the endpoint. We can have a `map [string]string` where we store these auxiliary information with well known key names. In this case, `"k8s:pod"`.

**Comment by ianvernon** [comment]
@tgraf  should endpoint ID lookup also be  across the cluster, and not just local to the node? 

EDIT: since endpoint IDs are not mutually exclusive across a cluster per [this Doc commit change ](https://github.com/cilium/cilium/pull/1244/files#diff-f25d2185d677408fd17b3de80a001eb5R236)(which is still pending as of this edit to the comment), it doesn't make sense to treat endpoint IDs to be searched for across the cluster; I will only search for local endpoints with these changes.

**Comment by ianvernon** [comment]
@tgraf I'm still unclear about what to do w.r.t. the YAML file. 

You mentioned that it should correspond with the `src-k8s-pod` and `dst-k8s-pod` options without having to query the API server. What would the YAML file be used in tandem with? Will the YAML file contain definitions for Pods, or NetworkPolicies, or both? In other words, what information am I supposed to be parsing / grabbing from the provided YAML? In tracing policy, everything comes down to which sets of labels can talk to another set of labels on specific ports. 
For instance, we have the following L3 / L4 policy in YAML in the repo at `examples/minikube/l3_l4_policy.yaml`:

``` 
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-backend
spec:
  podSelector:
    matchLabels:
      id: app1
  ingress:
  - from:
    - podSelector:
        matchLabels:
          id: app2
    ports:
    - port: 80
      protocol: TCP
```

If such a file is provided to the CLI as the `read-yaml` flag's value, am I supposed to check this YAML file against the set of labels / endpoint IDs / k8s pods provided for the other flags? 

Let's discuss this over Slack so I can nail down the requirements.

**Comment by tgraf** [comment]
> You mentioned that it should correspond with the src-k8s-pod and dst-k8s-pod options without having to query the API server. What would the YAML file be used in tandem with? Will the YAML file contain definitions for Pods, or NetworkPolicies, or both?

The use case I had in mind was that if a persona has the YAML of a deployment or a ReplicationSet locally, that persona wants to verify whether the policy is in place and allows for the communication before deploying the deployment:

```
cilium policy trace --src-k8s-yaml deployment1.yaml --dst-k8s-pod app1-234242
```

It should extract the labels of the YAML, filter them to get to the security relevant labels and evaluate the policy decision. The resources to support here are probably:
- Deployment
- ReplicationSet/ReplicationController
