### ISSUE TITLE
Validate guides for 1.7 release.

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#10125]
- Managed k8s
  - [x] EKS (@tklauser)
  - [x] GKE (@qmonnet)
  - [x] AKS (@tgraf)

- Self-managed
  - [x] Quick-install (@joestringer)
  - [x] w/ managed etcd (@joestringer)
  - [x] w/ external etcd (@nebril)

- Guides
  - [x] Kubernetes without kube-proxy (@gandro)
  - [x] Using Cilium with ~BIRD~ kube-router (@brb)
  - [x] Clustermesh on GKE (@raybejjani)
  - [x] Transparent encryption (@pchaigno)
  - [ ] Kata containers (Skipping, lack of current users)

**Comment by nebril** [comment]
I validated, `w/ external etcd`, but would be nice to merge https://github.com/cilium/cilium/pull/10147

**Comment by qmonnet** [comment]
I successfully validated the [GKE install](https://docs.cilium.io/en/v1.7/gettingstarted/k8s-install-gke/). I had to work around the following items, mostly because of my lack of experience with GKE:

- Creating a new project requires the user to have accepted Google Cloud terms and conditions beforehand, via the web platform.

- To enable the GKE API for the project, billing must be enabled for that project (so I ended up reusing an existing project instead of a new one).

- When deploying the connectivity test, 3 of the 10 pods (5 probes, 5 echo servers) failed to be scheduled because of insufficient CPU availability for that project. I could work around that by requesting lower CPU usage for the pods.

These bullet points are all related to Google Cloud, not Cilium itself, and are probably trivial to solve for people used to GKE. I do not consider that any change is required to Cilium install guide.

**Comment by gandro** [comment]
Validated "Kubernetes without kube-proxy" guide with `kubeadm v1.17.2` on `Linux 5.4`. Minor docs improvement for DSR suggested here https://github.com/cilium/cilium/pull/10149

**Comment by tklauser** [comment]
Succesfully validated [Installation on AWS EKS](https://docs.cilium.io/en/v1.7/gettingstarted/k8s-install-eks/). `examples/kubernetes/connectivity-check.yaml` wasn't available in `master` (which I used for testing). But it is in the `v1.7` branch and will also be re-added to `master` by #10141.

**Comment by joestringer** [comment]
Validated the quick-install and managed etcd guides using `K8S=1 NWORKERS=1 contrib/vagrant/start.sh`, disabling the systemd units, then applying the YAML / deploying via YAML. Used new connectivity-check YAML to confirm LB and policy works as expected.

**Comment by brb** [comment]
Validated the kube-router guide (proposed fixes: https://github.com/cilium/cilium/pull/10159) instead of BIRD, as the latter requires creating a new getting start guide (created an issue for it https://github.com/cilium/cilium/issues/10160), and the former project seems to be alive (last change to the master was made 15 days ago).

**Comment by pchaigno** [comment]
Validated the Transparent Encryption guide using `K8S=1 NWORKERS=1 contrib/vagrant/start.sh`. Found 1 nit (#10162): we keep using `--namespace cilium` in the guide when most installation guides have deploy Cilium in `kube-system`
