### ISSUE TITLE
Dead link in 1.5 upgrade section on latest docs

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10391]
In step 2 here: https://cilium.readthedocs.io/en/stable/install/upgrade/#upgrading-from-1-4-0-to-1-5-y

The link is broken.

**Comment by Ropes** [comment]
I decided to just go for it and submit a fix. Not perfect, as new backports to 1.5.x will not be immediately picked up in the static URL. However unsure how big of a concern that actually is. 

Also uncovered an issue I brought up in slack: rying to build the docs with `make test-docs`, got error, dove into container. make html error:
```
bash-5.0# make html
(sphinx-build -b spelling -d "_build/doctrees" "." "_build/spelling" -q -E  2>&1 && touch check-build.ok) > _build/warnings.txt
make: *** [Makefile:59: check-build] Error 2
bash-5.0# cat _build/warnings.txt 
Extension error:
Could not import extension sphinxcontrib.spelling (exception: The 'enchant' C library was not found and maybe needs to be installed.
See  https://pyenchant.github.io/pyenchant/install.html
for details
)
bash-5.0# apk info enchant
enchant-1.6.0-r14 description:
A wrapper library for generic spell checking
enchant-1.6.0-r14 webpage:
http://www.abisource.com/enchant/
enchant-1.6.0-r14 installed size:
212992
bash-5.0# pip install pyenchant
Requirement already satisfied: pyenchant in /usr/local/lib/python3.7/site-packages (3.0.1)
bash-5.0# pip install --upgrade pyenchant
Requirement already up-to-date: pyenchant in /usr/local/lib/python3.7/site-packages (3.0.1)
```
So the `enchant` lib was installed just fine, but something has changed in `pyenchant`. Turns out pyenchant just got an upgrade from 2.0.0 to 3.0.1 on March 1st.... https://pypi.org/project/pyenchant/#history
Downgrading pyenchant to 2.0.0 gets the docs built just fine... So we got burned by lastest version it seems not being backwards compatible with the installed c-lib it seems.

I could propose a fix to that and `Relate:` it to this issue if that seems good enough. Fix is via adding `pyenchant==2.0.0` works well.
