### ISSUE TITLE
Installation on AWS EKS doesn't work for Ubuntu1804 node-ami-family

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#10595]
Pods couldn't reach outside the cluster (e.g. google.com) after following instructions to install Cilium on EKS: https://docs.cilium.io/en/v1.7/gettingstarted/k8s-install-eks/#prepare-deploy-cilium

The issue is that egress masquerade interface gets renamed from `eth0` to `ens5` with `Ubuntu1804`. so I used this helm command:

```
helm install cilium cilium/cilium --version 1.7.1 \
  --namespace kube-system \
  --set global.eni=true \
  --set global.egressMasqueradeInterfaces=ens5 \
  --set global.tunnel=disabled \
  --set global.nodeinit.enabled=true
```
I don't know if it consistently gets renamed to `ens5` or not.

Also there is a rumor that the next version of Cilium supports listing multiple interfaces in `global.egressMasqueradeInterfaces`, so maybe we can just list both `eth0` and `ens5` once that's supported.

**Comment by michi-covalent** [comment]
forgot to mention that i added `--node-ami-family Ubuntu1804` option for creating a cluster:
```
eksctl create cluster --region us-east-2 -n my-cluster -N 0 --node-ami-family Ubuntu1804
```
so i'm using ubuntu instead of amazon linux.

**Comment by joestringer** [comment]
To be clear, the symptom of this issue is that outbound connections from pods fail; the underlying error is that the assumption is that the EKS image uses the name `eth0` for the first device that provides access to the outside world; the mitigation is to change your helm arguments to specify the right interface name; and the eventual solution will be abstracting the masquerade functionality to apply to more than one interface.
