### ISSUE TITLE
CI: Travis flake on arm64: StoreConsulSuite.TestStoreLocalKeyProtection: "timeout while waiting for expected value"

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#10615]
Seen this travis CI flake in unit tests on master during v1.8 dev cycle:

https://travis-ci.com/github/cilium/cilium/jobs/299021385#L1601

In this case it only failed on arm64 build, but passed on amd64 build.

```
=== RUN   Test

{"level":"warn","ts":"2020-03-17T17:21:24.079Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-56e7cff1-a5d3-47bc-a34a-5aec1a7c5203/127.0.0.1:4002","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}

{"level":"warn","ts":"2020-03-17T17:21:24.079Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-56e7cff1-a5d3-47bc-a34a-5aec1a7c5203/127.0.0.1:4002","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}

{"level":"warn","ts":"2020-03-17T17:21:24.138Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-93f385f7-95b1-44fc-b9bf-e12c7b889438/127.0.0.1:4002","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}

{"level":"warn","ts":"2020-03-17T17:21:24.138Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-93f385f7-95b1-44fc-b9bf-e12c7b889438/127.0.0.1:4002","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}

{"level":"warn","ts":"2020-03-17T17:21:24.195Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-1446e1c1-0230-4d19-a093-104fe90b75e8/127.0.0.1:4002","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}

{"level":"warn","ts":"2020-03-17T17:21:24.196Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-1446e1c1-0230-4d19-a093-104fe90b75e8/127.0.0.1:4002","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}

{"level":"warn","ts":"2020-03-17T17:22:24.251Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-4751680e-f781-4437-90e1-575a67b98de3/127.0.0.1:4002","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}

{"level":"warn","ts":"2020-03-17T17:22:24.251Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-4751680e-f781-4437-90e1-575a67b98de3/127.0.0.1:4002","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}

{"level":"warn","ts":"2020-03-17T17:22:24.296Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-3bcf90a0-34af-4494-80b2-f08e766925c7/127.0.0.1:4002","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}

{"level":"warn","ts":"2020-03-17T17:22:24.297Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-3bcf90a0-34af-4494-80b2-f08e766925c7/127.0.0.1:4002","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}

----------------------------------------------------------------------

FAIL: <autogenerated>:1: StoreConsulSuite.TestStoreLocalKeyProtection

store_test.go:270:

    c.Assert(expect(func() bool {

        v, err := kvstore.Client().Get(context.TODO(), store.keyPath(&localKey1))

        return err == nil && v == nil

    }), IsNil)

... value *errors.errorString = &errors.errorString{s:"timeout while waiting for expected value"} ("timeout while waiting for expected value")

OOPS: 9 passed, 1 FAILED

--- FAIL: Test (338.46s)

FAIL

coverage: 8.7% of statements in ./...

FAIL	github.com/cilium/cilium/pkg/kvstore/store	338.792s

FAIL

Makefile:146: recipe for target 'unit-tests' failed

make: *** [unit-tests] Error 1

The command "./.travis/build.sh" exited with 2.
```

**Comment by joestringer** [comment]
Sounds like this flaked on #10592 as well. 

@Jianlin-lv have you seen this before? I'm wondering whether this is identifying some issue on arm64 platform or if Consul arm64 support is poor and maybe we need to do something there like either bumping the Consul version or (worst case) conditionally disabling the test on arm64.

**Comment by pchaigno** [comment]
I've seen this a couple time as well, always only for the aarch64 build. In my experience, the Travis CI aarch64 runtime was fairly slower than the amd64 one, so this might simply be a matter of bumping a timeout somewhere.

**Comment by Jianlin-lv** [comment]
> Sounds like this flaked on #10592 as well.
> 
> @Jianlin-lv have you seen this before? I'm wondering whether this is identifying some issue on arm64 platform or if Consul arm64 support is poor and maybe we need to do something there like either bumping the Consul version or (worst case) conditionally disabling the test on arm64.

I haven’t encountered before, it looks like an occasional issue, I will do some investigation on this issue.

**Comment by Jianlin-lv** [comment]
> Sounds like this flaked on #10592 as well.
> 
> @Jianlin-lv have you seen this before? I'm wondering whether this is identifying some issue on 
arm64 platform or if Consul arm64 support is poor and maybe we need to do something there like either bumping the Consul version or (worst case) conditionally disabling the test on arm64.

I have checked infrastructure Travis-CI ran on for Arm job.
The host named  lxd-arm64 is an LXD container on Arm64-based infrastructure. I don't have information about the bare metal machine,
In a test case with 100 nodes, such as TestNodeManagerManyNodes, there may be resource constraints that cause slow response and may not be directly related to the current component.
whether or not extend the waiting time appropriately and continue to observe the operation results of CI:

--- a/pkg/aws/eni/node_manager_test.go
+++ b/pkg/aws/eni/node_manager_test.go
@@ -575,7 +575,7 @@ func (e *ENISuite) TestNodeManagerManyNodes(c *check.C) {
        }

        for _, s := range state {
-               c.Assert(testutils.WaitUntil(func() bool { return reachedAddressesNeeded(mngr, s.name, 0) }, 5*time.Second), check.IsNil)
+               c.Assert(testutils.WaitUntil(func() bool { return reachedAddressesNeeded(mngr, s.name, 0) }, 60*time.Second), check.IsNil)



--- a/pkg/kvstore/store/store_test.go
+++ b/pkg/kvstore/store/store_test.go
@@ -168,7 +168,7 @@ func expect(check func() bool) error {
                        return nil
                }

-               if time.Since(start) > defaults.NodeDeleteDelay+10*time.Second {
+               if time.Since(start) > defaults.NodeDeleteDelay+60*time.Second {
                        return fmt.Errorf("timeout while waiting for expected value")
                }

**Comment by Jianlin-lv** [comment]
Unfortunately, after my test, simply increasing the waiting time will not solve the problem, I will try other methods;

**Comment by joestringer** [comment]
@Jianlin-lv OK, thanks for looking into it. I look forward to hearing more. Let us know if we can provide any feedback or bounce ideas on how to fix this.

**Comment by Jianlin-lv** [comment]
When DeletePrefix function is executed to delete all key, the localKey stored in kvstore is not deleted. Due to the delay in the delivery of the event message, 
The program has a certain probability of receiving kvstore.EventTypeDelete and Re-creating the key;
If add the Sleep as shown in the following, this issue must occur
```
--- a/pkg/kvstore/store/store_test.go
+++ b/pkg/kvstore/store/store_test.go
@@ -267,6 +267,7 @@ func (s *StoreSuite) TestStoreLocalKeyProtection(c *C) {
        c.Assert(expect(func() bool { return localKey1.updated() >= 1 }), IsNil)
        // delete all keys
        kvstore.Client().DeletePrefix(context.TODO(), store.conf.Prefix)
+       time.Sleep(10 * time.Millisecond)
        c.Assert(expect(func() bool {

```
Is it possible to modify this test case as follows,
```
--- a/pkg/kvstore/store/store_test.go
+++ b/pkg/kvstore/store/store_test.go
@@ -267,9 +267,10 @@ func (s *StoreSuite) TestStoreLocalKeyProtection(c *C) {
        c.Assert(expect(func() bool { return localKey1.updated() >= 1 }), IsNil)
        // delete all keys
        kvstore.Client().DeletePrefix(context.TODO(), store.conf.Prefix)
+       time.Sleep(10 * time.Millisecond)
        c.Assert(expect(func() bool {
                v, err := kvstore.Client().Get(context.TODO(), store.keyPath(&localKey1))
-               return err == nil && v == nil
+               return err == nil && v != nil

```

What's your opinion? @joestringer
