### ISSUE TITLE
Create healthz HTTP endpoint for kube-proxy replacement

### ISSUE THREAD

**Issue by brb** [cilium/cilium#10621]
Implement healthz HTTP endpoint for kube-proxy replacement: https://github.com/kubernetes/kubernetes/blob/v1.17.4/pkg/proxy/healthcheck/. Listener addr and port should be configurable via cilium-agent params / Helm options.

The healthz endpoint will be used by external LBs.

**Comment by travisghansen** [comment]
Still valid..

**Comment by mrostecki** [comment]
@soumynathan will work on this (I can't assign him :/)

**Comment by brb** [comment]
@soumynathan Can you comment in this issue, so that we could assign you?

**Comment by soumynathan** [comment]
> @soumynathan Can you comment in this issue, so that we could assign you?

@brb please assign me.

**Comment by soumynathan** [comment]
@brb When trying to add a new HTTP service at port 10256. It errors out with bind: addr already in use.
It seems that 'kube-proxy' is already using it. 
root@k8s1:/home/vagrant/go/src/github.com/cilium/cilium# netstat -a -p | grep 10256
tcp6       0      0 [::]:10256              [::]:*                  LISTEN      11018/kube-proxy

Kubeproxy is also only creating a 'tcp6' listener.

Should we only create it when 'kubeproxy' is disabled. KubeProxyReplacement is in 'strict' or 'probe' mode.
Otherwise there will be a clash similar to the HealthCheckNodePort between cilium-agent and Kubeproxy.

**Comment by anfernee** [comment]
> Should we only create it when 'kubeproxy' is disabled. KubeProxyReplacement is in 'strict' or 'probe' mode.
> Otherwise there will be a clash similar to the HealthCheckNodePort between cilium-agent and Kubeproxy.

I think what you said makes sense. Are you still working on this issue. If not, I am okay to take it. It's kind of urgent for us.

**Comment by valas** [comment]
Same here, @soumynathan let me know how can we help (including taking over the PR).

**Comment by mrostecki** [comment]
@valas Swami is on PTO. Feel free to take over.

**Comment by valas** [comment]
Working on this issue. How do I change the assignment?

**Comment by mrostecki** [comment]
Only people with the commiter rights in the repository can assign people to issues (that's Github's limitation).

I assigned you.

**Comment by soumynathan** [comment]
> Same here, @soumynathan let me know how can we help (including taking over the PR).

It would be great if you can provide your review comments on this PR. I am back and I can work on this.

**Comment by valas** [comment]
I assume then you'll take over? Do you have a rough ETA?

Here is my draft, I believe it's working but missing a test:
https://github.com/cilium/cilium/compare/master...valas:node-level-healthz?expand=1
