### ISSUE TITLE
Cluster networking health

### ISSUE THREAD

**Issue by errordeveloper** [cilium/cilium#10975]
A user must be able to judge cluster networking health easily. 

There has to be a single status indicator for the user to look at, and they should
also be able to drill into what conditions that status indicator is based on. 

Cilium currently offer connectivity check manifest that users can deploy, but that
can be improve on and should be come part of automated installation experience,
albeit health indicator doesn't have to rely on continuous connectivity checks (as
those maybe expensive, or somehow inconvenient).

Prometheus metrics could be used, but there needs to be an overall state indicator.
Perhaps the model could be very similar to the Kubernetes node object - there is
a set of conditions and an overall readiness indicator is a sum of those conditions.

E.g. one possible approach would be to look at wether some percentage of nodes
(a user-defined threshold) in the cluster have positive network readiness conditions,
and that could be combines with Cilium pod status conditions.
Nodes also have `DiskPressure` condition, for example, that one is metic based,
similarly Cilium health could have `IPAMPressure` condition that would rely on
Prometheus metrics.

In a multi-cluster setting this becomes more important, as any form of sync logic
between clusters will need to be able to appropriately handle an unhealthy cluster,
or e.g. a cluster that is tainted for maintenance.

**Comment by errordeveloper** [comment]
From the documentation:

> Cilium allows to rule out network fabric related issues when troubleshooting
 connectivity issues by providing reliable health and latency probes between all
 cluster nodes and between a simulated workload running on each node.
>
> By default when Cilium is run, it launches instances of ``cilium-health`` in
the background to determine overall connectivity status of the cluster. This
tool periodically runs bidirectional traffic across multiple paths through the
cluster and through each node using different protocols to determine the health
status of each path and protocol. At any point in time, cilium-health may be
queried for the connectivity status of the last probe.

That is already very useful, however what this issues is prompting for is an
a central status object, that can be observed at any time. It may or may not
incorporate full connectivity as a key condition, as that maybe expensive to
assert very frequently in a large cluster.  One possible approach could be to
execute `cilium-health status` on different subset of nodes every time, with
a user-settable ratio...

However, aside from whether or not connectivity will be incorporated or not,
the primary object that I'd like to discuss is about to incorporating health
attributes that are already defined in Kubernetes APIs (i.e. node objects and
Cilium agent pods), as well as Prometheus metrics. Most crucial to point of
this proposal would be to define an API to begin with, the rest will evolve.

**Comment by joestringer** [comment]
Thanks for the great writeup. A few thoughts in no particular order:

The scale aspect is certainly a big deal with any kind of extension to the cluster connectivity assessment. Individual Cilium pods likely should not propagate these changes directly into the k8s apiserver, we've had similar health designs in the past with e.g. cilium endpoint status and it can easily become too expensive, especially if they end up making changes to the same resource. From that perspective, if we go down the path of representing these in K8s APIs, I'd expect the operator to be the primary component to manage any such state propagation. A common form is for us to propagate the info from cilium-agent to cilium-operator via the kvstore, then cilium-operator collates the reports and publishes them to a single k8s resource. This is not a hard-and-fast rule, but I think with folks like @aanm we have a bit of experience on the potential scale impacts of status APIs like this so we should draw on that knowledge if and when we address this problem.

Another aspect to the design is that in general, cluster connectivity health assessment often comes down to two different approaches:
* Quickly detecting problems and reporting them as they happen (and potentially reacting)
* Slower sweeps that assess health as a general sanity check that a user/operator may only notice minutes/hours/days later when they eventually observe another issue in the cluster.

I don't have a great writeup of the nuance of these use cases, but they have different goals and different design decisions that go into them (and different scale implications). The current `cilium-health` cluster connectivity checks fall into the latter category. They are best-effort probes run once per minute and hence are more interesting for noticing broader problems like "oh, this node has connectivity issues" in general and using that as a basis for guiding ongoing troubleshooting. I would urge caution if you find yourself mixing these two use cases, because the current design is not built for accurate and timely alerts.

Note as well, just because a node has cluster connectivity issues, that does not necessarily mean that the corresponding cilium pod should react to this in its status! If we note that there is a cluster connectivity issue and respond by restarting the cilium-agent pod, this is not guaranteed to make progress towards resolving the issue, and may instead exacerbate the issue by e.g. adding additional load to the apiserver; adding additional load to the node itself; or potentially causing other knock-on effects for other agents in the cluster. Additionally, there is an interesting aspect that a faulty node may report successful connectivity to all other nodes in the cluster, while all other nodes in the cluster only report connectivity issues to the one faulty node. We've seen examples of this with cilium-health pod connectivity checks recently (/cc @christarazi ).

Overall though I do wonder if a simple binary "all good" / "some connectivity issue" report in either `CiliumNode` or `Node` resources which could be printed out when someone runs `kubectl get ciliumnodes [-o wide]` might be useful as a first cut of this functionality. This is a bit less clear-cut when taking into account multi-cluster though, for the reasons you report in the issue description.

**Comment by errordeveloper** [comment]
@joestringer thanks for your input, there is certainly much to be discussed here!

Here is something that Bruno Miguel Custódio  mentioned on Slack just now:
>  8:50 AM
>
> Morning :wave: Does the Cilium agent expose metrics for the following items?
> ```
> root@ip-x-x-x-x:~# cilium status --all-clusters --all-nodes
> (...)
> ClusterMesh:            2/2 clusters ready, 0 global-services
>    xxxxxx: ready, 3 nodes, 0 identities, 0 services
>    └  etcd: 1/1 connected, lease-ID=51cc71740861ebd4, lock lease-ID=51cc71740861ebd6, has-quorum=true: http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxx.elb.eu-west-1.amazonaws.com:2379 - 3.4.7
>    xxxxxx: ready, 9 nodes, 0 identities, 0 services
>    └  etcd: 1/1 connected, lease-ID=12a87173b3db88d3, lock lease-ID=12a87173b3db88d5, has-quorum=true: http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxx.elb.eu-west-1.amazonaws.com:2379 - 3.4.7 (Leader)
> (...)
> Cluster health:   15/15 reachable   (2020-04-15T07:44:49Z)
> ```
> If it doesn’t, is there a way to understand whether the mesh is healthy using existing metrics? The end goal is to raise an alert whenever there are (in this particular case) less than 15 nodes reachable.

**Comment by aanm** [comment]
Isn't this covered by `kubectl get ds -n kube-system cilium` where the readiness checks verify if cilium is healthy and kubelet report it to kube-apiserver in case it's not?

**Comment by errordeveloper** [comment]
> Isn't this covered by `kubectl get ds -n kube-system cilium` where the readiness checks verify if cilium is healthy and kubelet report it to kube-apiserver in case it's not?

That's a good point, I think it does largely cover the use-case, but I think adding extra parameters, such as threshold, and metric-based conditions would be very helpful.

>  The current `cilium-health` cluster connectivity checks fall into the latter category. They are best-effort probes run once per minute...

I wasn't sure from the docs if these are user-initiated or periodic (maybe the page I was reading didn't cover that part, I've not read through everything), good to know these are periodic. So does the result of these probes gets reflected in cilium pod status or not?

> Note as well, just because a node has cluster connectivity issues, that does not necessarily mean that the corresponding cilium pod should react to this in its status!

That level of coupling would be definitely wrong to suggest. In fact, node status already incorporates status of cilium pod on that node, albeit indirectly. When CNI is non-functional, a node stops being ready (IIRC, as I forgot the exact mechanics).

>  If we note that there is a cluster connectivity issue and respond by restarting the cilium-agent pod, this is not guaranteed to make progress towards resolving the issue, and may instead exacerbate the issue...

Indeed, and I think that is why a dedicated health object would be more plausible in my view.

> Overall though I do wonder if a simple binary "all good" / "some connectivity issue" report in either `CiliumNode` or `Node` resources which could be printed out when someone runs `kubectl get ciliumnodes [-o wide]` might be useful as a first cut of this functionality. This is a bit less clear-cut when taking into account multi-cluster though, for the reasons you report in the issue description.

That is largely what I'm proposing, i.e. something lightweight, however what I had in mind a an aggregate cluster-wide object that represent a sum of all nodes (with a settable tolerance threshold).

Here's the kind of object I was thinking of:

```YAML
kind: ClusterNetworkHealth
apiVersion: cilium.io/v2
metadata:
   name: cilium
spec:
  maxUnhealthyNodesPerscent: 15%
  connectivityCheck:
    interval: 2m
    tolerance:
      maxFailuresDuration: 10m
    distribution:
      random:
        subset: 10%
  ipamPressure:
    minFreeAddresses: 100

status:
  conditions:
    - lastHeartbeatTime: "2020-04-15T09:24:23Z"
      lastTransitionTime: "2020-04-14T23:25:26Z"
      message: "98/100 nodes ready with healthy Cilium pods"
      status: "False"
      type: NodesNotReadyWithinThreshold
    - lastHeartbeatTime: "2020-04-15T09:24:23Z"
      lastTransitionTime: "2020-04-14T23:25:26Z"
      message: cilium has sufficient addresses available
      reason: CiliumHasSufficientAddresses
      status: "False"
      type: IPAMPressure
    - lastHeartbeatTime: "2020-04-15T09:24:23Z"
      lastTransitionTime: "2020-04-14T23:25:26Z"
      message: no significant connectivity failures in last 10m
      reason: NoConnectivityFailures
      status: "False"
      type: ConnectivityFailures
```

**Comment by mathpl** [comment]
We're taking a stab at this problem through https://github.com/cilium/cilium/pull/25994. We'll track the work over there.
