### ISSUE TITLE
Start DNS proxy before cilium-agent acquires IPs in CRD-backed IPAM mode

### ISSUE THREAD

**Issue by willdeuschle** [cilium/cilium#11004]
## Proposal / RFE
When running in CRD-backed IPAM mode, the agent does not start its DNS proxy until after it has acquired IP addresses. The DNS proxy should be able to start before this happens.

**Is your feature request related to a problem?**
The motivation here is primarily for situations in which the agent restarts. Existing endpoints relying on the DNS proxy will lose connectivity until the agent has acquired IPs and started the DNS proxy. Those existing endpoints already have IPs and just need the DNS proxy to be back online in order for them to egress normally.

**Describe the solution you'd like**
The DNS proxy is started without blocking on the agent acquiring IP addresses.

**Comment by jrajahalme** [comment]
#12698 starts the DNS proxy earlier, but this does not change the fact that while the DNS proxy policy (which is derived from the CNPs applicable to local endpoints) is not available, the DNS proxy will to deny passing requests until the applicable endpoints are regenerated after all CNPs have been received from the k8s API server. #12698 allows the new Proxy instance to receive the DNS requests based on the old datapath config, which may actually make the situation worse by causing DNS errors to be returned to the source POD.

**Comment by PinchasLev** [comment]
@jrajahalme Isn't this merely a question of honoring the TTL present in the old config/cache? Say a cycling the agent takes 10 seconds, wouldn't it be better to allow egress traffic for all those IP addresses present in the old cache, than to drop all egress until the cache is regenerated?  Granted any egress traffic whose destination IP is resolved to an address not present in the cache will be dropped.  But the newly started agent should at least start out using whatever cache is still valid, rather than with a blank cache.

**Comment by joestringer** [comment]
@PinchasLev my understanding of the issue is this is more about the handling of the DNS traffic itself rather than the allow of the regular connections to the destination IPs behind those DNS names. But broadly yes your suggestion around ensuring that the old cache sticks around when the agent is restarted makes sense, PR #12718 aims to do just this--right up until Cilium is able to resync with kubernetes & recalculate any "new" configurations that could have occurred while Cilium was down.

**Comment by PinchasLev** [comment]
@joestringer Thanks for your response and for the work done in the PR.  The point I'm getting at is that from a design perspective Cilium's move from poll to proxy for maintaining its DNS cache should not have had any effect on DNS handling.  The purpose of intercepting DNS traffic was for no other reason than to ensure that the toFQDN rules are being implemented with the same set of IPs as seen by the user, rather than via periodic polling that might be out of lockstep with user.  So that if DNS traffic is being dropped during restart by the eBPF module supporting polling, then polling has introduced a problem as a side-effect.
