### ISSUE TITLE
Wanted bpftool feature probes

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#11014]
We now rely on `bpftool feature probe macros` to tell us what the kernel supports BPF-wise. However, in some cases, bpftool doesn't provide the exact probe we need and we're forced to write our own or to probe another feature we know was introduced in the same commit (or worst-case scenario, the same release).

The list of probes that would be nice to have:
- [x] Supported BPF CPU versions.
- [ ] List of attach types (for the sockops programs and `verifier-test.sh`).
- [ ] Support for LPM map with GET_NEXT_KEY traversal.
- [ ] Support for LPM map with DELETE support.
- [x] Bounded loops (to remove `#pragma unroll` when possible/sensible)

No usage currently envisioned for Cilium, but listing for the record:
- [ ] Verifier complexity limit. There's already `HAVE_LARGE_INSN_LIMIT` for the 1M insns limit, but we don't have any indication for older kernels with e.g., 96k and 128k limits.
- [ ] prog/map names (`tc`/`ip` should have their own probe mechanism)
- [ ] global data, global functions
- [ ] batched map operations

There's some preliminary work on this at https://github.com/cilium/linux/commits/bpftool_newprobes.

**Comment by pchaigno** [comment]
@ti-mo also mentioned that this probing could be implemented in cilium/ebpf.

Although it may take a bit longer than extending bpftool, I agree this would be best in the long term as it avoids the need to shell out with bpftool. We also wouldn't need to package bpftool in the Cilium container image.

**Comment by qmonnet** [comment]
From https://github.com/cilium/cilium/issues/14314#issuecomment-763516378 we also want alternative probes for 

- [ ] `CONFIG_NET_SCH_INGRESS`
- [ ] `CONFIG_BPF_JIT`

for when the kernel config file is not available.

**Comment by pchaigno** [comment]
Taking a new look at this given the increased usage of OpenShift where our incorrect kernel probes are more likely to break (due to RedHat's backports). I've sent a first patchset for the bounded loops: https://lore.kernel.org/bpf/7dfdf3f93467c619c14c40e957c54b87bb734294.1639748569.git.paul@isovalent.com/T/. BPF ISA extensions will probably be next.

**Comment by pchaigno** [comment]
Probes for bounded loops and instruction set extensions were [merged in bpf-next](https://lore.kernel.org/bpf/164138641615.6231.4937030135518900608.git-patchwork-notify@kernel.org/T/). I'll update our images to start using those probes where appropriate.

**Comment by ti-mo** [comment]
@pchaigno Could we close this and/or spin this off into sub-items that we can ship in 1.14? For all kconfig-related stuff, I went ahead and created https://github.com/cilium/cilium/issues/22514. I think we should wind down our reliance on kconfig completely, since it's just not very reliable from within a container.

For attach types, that means finding a replacement for `pkg/bpf.TestDummyProg()`, but I'm not sure it's necessary as socket-lb is currently being ported to Go, where we can do proper error handling while loading/attaching.

- prog/map names: handled transparently by lib.
- global data: what does this mean specifically? Frozen maps, pseudomaps, or both? Could be interesting to opportunistically stop inlining static data accesses, but switching between proper use of .rodata and inlined ones will require some patches to the bytecode either way, not sure if this is realistic. :/
- global functions: are these regular bpf2bpf calls? Can't really tell from the patch set that introduces them upstream.
- batched map ops: cilium/ebpf should expose a map interface that does batch ops opportunistically at some point, but I haven't spent much time on this lately. We'll pick it up when we have a use case.
