### ISSUE TITLE
Restarting Cilium pods sometimes disconnects the network of CNI managed pods

### ISSUE THREAD

**Issue by Starblade42** [cilium/cilium#11147]
# Restarting Cilium pods sometimes disconnects the network of CNI managed pods:
## Characteristics of the failure
1. pod egress network traffic no longer makes it onto the VXLAN (cilium_vxlan) (like, say, to CoreDNS pods addressed directly from the pod within the same Pod network address space)
1. pod ingress network traffic no longer makes it to the pod.
  - For example, this problem can cause the Pod to **fail** `liveness` probes sent by the `kubelet` with the following message: `Readiness probe failed: Get http://172.16.229.155:9093/-/ready: dial tcp 172.16.229.155:9093: connect: no route to host`
1. The problem persists even if the `cilium-agent` container is restarted within the pod
1. The problem only seems to be resolved by deleting the pod and allowing a new one to be scheduled in its place

- The problem can be **caused** by deleting the pod and allowing a new Cilium to schedule on the node (like in `kubectl -n kube-system rollout restart daemonset/cilium`)
- The problem can be **resolved** by deleting the pod and allowing a new Cilium pod to be scheduled on the node. 🤪

## Characteristics of the pods
1. pods are colocated on the same node as the "bad" cilium pod
1. pods are using CNI and successfully receive a pod IP
1. pods *usually* have K8s Network Policy applied (L3/L4)
1. pods *sometimes* are CNI pods which have *no network policy applied* to their namespace
1. pod network address space is within `172.16.0.0/16` with a `/24` assigned to each node

## Cluster characteristics:
- ~115 worker nodes
- ~700 network policy objects
- ~137 namespaces
- ~2879 pods
- ~198 k8s service objects

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.6.7 d26878333 2020-03-03T22:55:12-08:00 go version go1.12.17 linux/amd64
Daemon: 1.6.7 d26878333 2020-03-03T22:55:12-08:00 go version go1.12.17 linux/amd64
```
- Kernel version (run `uname -a`)
```
Linux cpt-worker-ethos11prodor1-603.ethos.adobe.net 4.19.84-coreos #1 SMP Tue Nov 19 20:51:06 -00 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)

**How to reproduce the issue**

1. You may change the cilium config **or not** and issue a restart like so:
1. `kubectl -n kube-system rollout restart daemonset/cilium`
1. Some previously healthy pods will start failing health checks.
1. Some newly scheduled pods will crash and/or fail health checks
1. Restarting Cilium on the nodes where this is occurring **may** resolve the issue.

**Comment by danwent** [comment]
Our initial assessment on this is that there are potentially two issues happening here: 
- https://github.com/cilium/cilium/pull/10630  (it is highly likely that you hit this issue, and it was addressed in Cilium 1.6.8 release).   Restarting the Cilium pod will not fix the issue, and so upgrading to 1.6.8 to get this fix is key.    
- During the analysis we felt like there were certain scenarios on cilium restart + restoration of endpoints where Cilium may not properly retry.  We filed https://github.com/cilium/cilium/issues/11256 .    The workaround for this would be to restart the Cilium pod.   However, with further analysis, it seems like persistent connectivity lost due to this issue is quite unlikely, as the scenarios were this happen are less likely than we had originally thought, and such scenarios are not likely to persist.   We'll still do analysis on this issue as we believe things should be improved here, but this is a much less to cause problems than we originally thought.
