### ISSUE TITLE
Initial regeneration on restore is never retried

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#11256]
When an endpoint is restored from disk it must be regenrated. It will currently depend on another regeneration trigger for that endpoint to appear. This has become more serious as most triggers are not rebuilding the BPF layer.

```
        for _, ep := range state.restored {
                go func(ep *endpoint.Endpoint, epRegenerated chan<- bool) {
                        if err := ep.RegenerateAfterRestore(); err != nil {
                                epRegenerated <- false
                                return
                        }
                        epRegenerated <- true
                }(ep, epRegenerated)
        }
```

**Comment by joestringer** [comment]
A few lines up:

https://github.com/cilium/cilium/blob/3c25373901605acb9d8615ae2f0ba68e5a78ac18/daemon/cmd/state.go#L259-L263

...

`Expose()`:
https://github.com/cilium/cilium/blob/3c25373901605acb9d8615ae2f0ba68e5a78ac18/pkg/endpoint/manager.go#L56

...

https://github.com/cilium/cilium/blob/3c25373901605acb9d8615ae2f0ba68e5a78ac18/pkg/endpoint/policy.go#L586-L592

At least from this perspective we will retry regeneration at least until the endpoint is deleted.

**Comment by joestringer** [comment]
Why might the endpoint be deleted?

Well, as part of `NewDaemon()` we have:

https://github.com/cilium/cilium/blob/3c25373901605acb9d8615ae2f0ba68e5a78ac18/daemon/cmd/daemon.go#L444-L447

-> 

https://github.com/cilium/cilium/blob/3c25373901605acb9d8615ae2f0ba68e5a78ac18/daemon/cmd/state.go#L165-L178

So if `validateEndpoint()` believes that the endpoint no longer exists for whatever reason, it will quietly add it to a list of endpoints to clean up:

https://github.com/cilium/cilium/blob/3c25373901605acb9d8615ae2f0ba68e5a78ac18/daemon/cmd/state.go#L44-L50

---

Later, after `restoreOldEndpoints()` already ran, we call into `regenerateRestoredEndpoints()` (via `runDaemon()`) and that's how we end up around the point where the issue description starts, and more specifically at a point where we may actually delete the endpoint and stop the regeneration retries:

https://github.com/cilium/cilium/blob/3c25373901605acb9d8615ae2f0ba68e5a78ac18/daemon/cmd/daemon_main.go#L1280

->

https://github.com/cilium/cilium/blob/3c25373901605acb9d8615ae2f0ba68e5a78ac18/daemon/cmd/state.go#L344-L351

-> 

https://github.com/cilium/cilium/blob/3c25373901605acb9d8615ae2f0ba68e5a78ac18/daemon/cmd/state.go#L266-L292

In particular line 285 where the endpoint is deleted, which closes a context that we use to stop the regeneration retry controller.

So from this analysis, it seems to me that the only reason that we would not try regenerating again is if we think that the endpoint is invalid (whether because we can't find the endpoint in k8s, or the link disappears, or we can't allocate the same IP upon restart, or another reason). Specifically somewhere in this function:

https://github.com/cilium/cilium/blob/3c25373901605acb9d8615ae2f0ba68e5a78ac18/daemon/cmd/state.go#L50

**Comment by joestringer** [comment]
From Slack via @aanm :

> whether because we can't find the endpoint in k8s

The bug is here. Right now it seems that the endpoint is considered gone if we can't connect to k8s.
