### ISSUE TITLE
iptables: Chain already exists.

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#11276]
Agent fails to start repeatedly with the following error:
```
ERROR [2020-04-29T19:29:58.05957853Z] cilium.io/agent: "Command execution failed" cmd="[iptables -w 5 -t filter -N CILIUM_TRANSIENT_FORWARD]" error="exit status 1" subsys=iptables
WARN  [2020-04-29T19:29:58.059649147Z] cilium.io/agent: "iptables: Chain already exists." subsys=iptables
ERROR [2020-04-29T19:29:58.059671388Z] cilium.io/agent: "Error while initializing daemon" error="cannot add custom chain CILIUM_TRANSIENT_FORWARD: exit status 1" subsys=daemon
ERROR [2020-04-29T19:29:58.059689483Z] cilium.io/agent: "Error while creating daemon" error="cannot add custom chain CILIUM_TRANSIENT_FORWARD: exit status 1" subsys=daemon
```

**Comment by qmonnet** [comment]
From what I understand the issue happens multiple times consecutively, preventing the agent to restart.

I had a look at the code and I fail to understand what can be happening here. From what I understand, chain `CILIUM_TRANSIENT_FORWARD` is only added/removed with [`TransientRulesStart()`](https://github.com/cilium/cilium/blob/v1.7.3/pkg/datapath/iptables/iptables.go#L705) and `TransientRulesEnd()` (below the former). BUT `TransientRulesStart()` starts with calling `TransientRulesEnd()`, so the chain _should_ always be deleted when we try to create it again.

We could imagine that the agent crashed for whatever reason when those transient rules were up, and that we failed to delete the chain on the next restart attempt. Failing to delete the chain might happen for a number of reasons, I see:

1. We error and exit before trying to delete the chain
2. The chain is not empty
3. There are rules in other chains referring to this chain
4. The `/run/xtables.lock` is taken

For 1., `TransientRulesEnd()` is defined as such
``` go
// TransientRulesEnd removes Cilium related rules installed from TransientRulesStart.
func (m *IptablesManager) TransientRulesEnd(quiet bool) {
	if option.Config.EnableIPv4 {
		m.removeCiliumRules("filter", "iptables", ciliumTransientForwardChain)
		transientChain.remove(m.waitArgs, quiet)
	}
}
```

And we do not exit if `m.removeCiliumRules()` fails. Then `transientChain.remove()` attempts only two things: flush and delete, see next point.

For 2., we try to flush the chain before deleting it. Flushing might fail too, but as I understand from the case where we observed the issue, the chain was empty. So I don't understand why that would fail (any more than I understand why deleting it would fail). Note that trying to flush an empty chain does not make `iptables` return an error.

Point 3. is not supposed to happen, and as I understand from the current case, it didn't.

For 4. the lock might be held by some other application, but in that case we would see a different error message stating that the lock is held. This would happen before `iptables` realises that the chain we try to build is already existing (I checked that on my setup). Even if the lock was held just when we attempted to remove the chain, subsequent attempts (when trying to restart the Cilium agent again, and again) would be super-unlikely to hit the same contention.

So at this point I have no idea why this chain is still present in the table. Note that we silence the logs when trying to delete it when `TransientRulesEnd()` is called from `TransientRulesStart()`, so we have no indication. If possible, maybe trying to remove the chain by hand might provide some information.

Not sure how to debug further at this point, if we cannot find a reproducer. Talking with @joestringer, one of the best paths forwards might be to check the error message we get when creating the chain fails, and to avoid error-ing out if it fails because the chain is already here. I have no clue if the chain is in a “normal” state and could still receive the transient rules, if we failed to delete it; but transient rules are here to avoid packet loss during restart anyway, and no restart is probably worse than no transient rules in that regard?

**Comment by joestringer** [comment]
I say let's prepare the PR to add those logs, if it helps to gather more information next time then that's at least a step forward.

**Comment by joestringer** [comment]
I also note that while the issue description states:

```
ERROR [2020-04-29T19:29:58.059689483Z] cilium.io/agent: "Error while creating daemon" error="cannot add custom chain CILIUM_TRANSIENT_FORWARD: exit status 1" subsys=daemon
```

The corresponding code calls `Fatal()`:
https://github.com/cilium/cilium/blob/3c25373901605acb9d8615ae2f0ba68e5a78ac18/daemon/cmd/daemon_main.go#L1239

**Comment by joestringer** [comment]
We don't seem to have heard anything on this topic for almost a year, despite adding logging specifically to try to help investigate.

PR #16391 is actually looking to remove such logging along with the transient rules 'feature' so I doubt we'll take this issue any further.

If you see an issue like this in future, please file a brand new issue with the symptoms and details.
