### ISSUE TITLE
CI: Suite-k8s-1.18.K8sPolicyTest Basic Test Denies traffic with k8s default-deny egress policy

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#11325]
Seen the flake in master CI and various PRs:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19445/testReport/junit/Suite-k8s-1/18/K8sPolicyTest_Basic_Test_Denies_traffic_with_k8s_default_deny_egress_policy/

[be81e28f_K8sPolicyTest_Basic_Test_Denies_traffic_with_k8s_default-deny_egress_policy.zip](https://github.com/cilium/cilium/files/4577333/be81e28f_K8sPolicyTest_Basic_Test_Denies_traffic_with_k8s_default-deny_egress_policy.zip)

**Comment by qmonnet** [comment]
Looking for errors in `test-output.log`, I found:

```
time="2020-05-04T19:26:32Z" level=error msg="Error executing command 'kubectl exec -n kube-system cilium-6msj2 -- cilium policy wait 20 --max-wait-time 10.000000'" error="exit status 255"
cmd: "kubectl exec -n kube-system cilium-6msj2 -- cilium policy wait 20 --max-wait-time 10.000000" exitCode: 255 duration: 225.937201ms stdout:
Error: invalid argument "10.000000" for "--max-wait-time" flag: strconv.ParseInt: parsing "10.000000": invalid syntax
```

It looks like the `ShortCommandTimeout.Seconds()` returns a float that the CLI is not able to parse. This was introduced in a recent commit, 2a583b11750fd031542c61dbcd5e196717468661. My suspicion is that because of this failure, the `cilium policy wait` is actually not run. It seems that in most cases we're fine, as the change is fast enough that the test does not break, but it may occasionally not be finished when the test catches up and tries to check the policy.
