### ISSUE TITLE
Fix up ipcache access in datapath

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#11351]
Many of the ipcache accesses in the datapath use `ipcache_lookup4()` directly, which does not implement LPM via hash maps on older kernels. This can lead to unexpected behaviour such as what is fixed in PR #11333 .

We should review all existing uses of `ipcache_lookup[46]()` to ensure that if that code path is enabled on Linux 4.9/4.10, and it relies on identities with prefixes other than the longest and shortest (/0 for all protocols; /32 for IPv4; /128 for IPv6), it uses `lookup_ip[46]_remote_endpoint()` instead.

**Comment by soumynathan** [comment]
@joestringer  Do you think that we should probes to check if it is supported before swapping it. Assign it to me, I will work on it.

**Comment by pchaigno** [comment]
@soumynathan We already probe for it. However, there are cases where `ipcache_lookup[46]()` is called in code that would never get executed on older kernels (e.g., because it's behind a `ENABLE_*` for a feature only enabled in newer kernels). In those cases we don't need to call `lookup_ip[46]_remote_endpoint()`. Same if we rely only on shortest and longest prefixes.

**Comment by joestringer** [comment]
FYI it may be worth waiting until #11333 is merged to work on this, as it will fix up some of the cases.

**Comment by soumynathan** [comment]
> FYI it may be worth waiting until #11333 is merged to work on this, as it will fix up some of the cases.

Ok will do. Thanks.
