### ISSUE TITLE
Introduce a helm variable in order to make PolicyEnforcementMode configurable

### ISSUE THREAD

**Issue by brandshaide** [cilium/cilium#11393]
## Proposal / RFE

As described in the [docs for Policy Enforcement](https://docs.cilium.io/en/stable/policy/intro/), a user can set three policy enforcement modes (`default`, `always`, `never`) by either utilizing Cilium CLI or set the respective env value in the `DaemonSet`. 

It might be a good idea to have this behaviour configurable across a k8s-Cluster by employing a respective variable in the helm chart: 

`values.yaml` of `agent` : 

```
image: cilium

# possible values are defaut, always, never (default when omitted) 
PolicyEnforcementMode: ~

[...]
```

`daemonset.yaml` of `agent` :

```
[...]
{{- if .Values.PolicyEnforcementMode }}
        - name: CILIUM_ENABLE_POLICY
          value: {{ .Values.PolicyEnforcementMode | quote }}
{{- end}}
[...]
```

If this makes sense, I'd be happy to submit a PR.

**Comment by joestringer** [comment]
Do you think that this is useful to configure?

Most users rely on the default behaviour and standard k8s network policy enforcement mode handling, which is to say that if you have policies imported that select endpoints then those endpoints are in enforcing mode (as described in the docs link you shared). This can be applied across the entire cluster using things like CiliumClusterwideNetworkPolicy. The only feature that I think is not possible via those means is the PolicyEnforcementMode=disabled, which will cause all network policy to be ignored; though the user could just not import the policies to achieve the same effect.

Note that the downside of the `always` setting here is that the user *must* import policies to allow every bit of traffic they expect in the cluster, otherwise the traffic will be dropped. This might be a reasonable setting once the user has created a full set of policies for the cluster, but at that point they already have the policies so I'm not sure what extra help that configuring this option would provide.

That said it sounds like a harmless change so I'm not against making it configurable if there's a use case. If you do so, I would suggest including a link to the specific docs section (ie https://docs.cilium.io/en/stable/policy/intro/#policy-enforcement-modes) in the values.yaml so that the user can figure out what default/always/never means.

**Comment by brandshaide** [comment]
> [...] the only feature that I think is not possible via those means is the PolicyEnforcementMode=disabled [...] 

That's acutally the use-case which came into my mind: let's say there's a user who want's to [liberate](https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free/) his k8s cluster from `kube-proxy` as some kind of a first migration-step/try-out but e. g. wants (for now) to keep a already deployed solution for dealing with (applied) Network Policys when rolling out Cilium on the Cluster. 

But this might be an "esoteric" use-case; he just could add the value `CILIUM_ENABLE_POLICY: "never"` manually in the `DaemonSet` before rolling out an he'd be done. Feel free to close this RFE 😉

**Comment by joestringer** [comment]
For what it's worth, the recently introduced [Policy Audit Mode](https://github.com/cilium/cilium/pull/9970) likely supports this kind of case in a better way, as monitor messages will be generated for the policy allows/denies so it also provides a path for users to migrate onto policies and understand the impact they have without requiring full enforcement from the get-go. Disabling enforcement entirely like this would mean that the policies just aren't effective and there'd be no way to tell how they would affect the cluster traffic.

**Comment by joestringer** [comment]
@brandshaide if you think it'd be a useful exercise to learn about how Cilium plumbs these arguments together using Helm, then I'd say go ahead.

I believe that the changes you suggested in the issue description for the daemonset should not be necessary, we can just put it into the configmap. AFAIK Cilium will propagate all variables from the configmap through automatically without extending the daemonset. It'd be good to test this out to confirm though, and to include shell excerpts in the PR description to demonstrate that the new helm option successfully configures the different modes.

**Comment by brandshaide** [comment]
> [...] the recently introduced Policy Audit Mode for Cilium v1.8 likely supports this kind of case in a better way, as monitor messages will be generated for the policy allows/denies. [...] 

@joestringer cool, I wasn't aware of this feature. As this is a way more sophisticated tool for a migration path I don't see a relevant requirement for this RFE anymore 😉

**Comment by joestringer** [comment]
In that case I'll close out the issue but hopefully the discussion above proves useful. :-)
