### ISSUE TITLE
CI/GKE: Failed waiting for log-gatherer pods: timed out waiting for pods with filter -l k8s-app=cilium-test-logs to be ready: 4m0s timeout expired

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#11395]
https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline-GKE/1075/testReport/Suite-k8s-1/14/K8sHealthTest_checks_cilium_health_status_between_nodes/

```
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline-GKE/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:425
Failed waiting for log-gatherer pods: timed out waiting for pods with filter -l k8s-app=cilium-test-logs to be ready: 4m0s timeout expired
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline-GKE/src/github.com/cilium/cilium/test/test_suite_test.go:275
```

**Comment by nebril** [comment]
The original jenkins link expired, there has been a similar failure in non-GKE CI run recently: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/5271/testReport/junit/Suite-k8s-1/18/K8sHubbleTest_Hubble_Observe_Test_L3_L4_Flow/

it was caused by failing to pull images from dockerhub.

**Comment by tgraf** [comment]
This seems to no longer be an issue.
