### ISSUE TITLE
Is the ebpf ct table the same as netfilter‘s？

### ISSUE THREAD

**Issue by autumn0207** [cilium/cilium#11538]
## Support

I find that there are more connections in cilium's ct table than conntrack's. If they are not the same, how does different's devices share them?

**Comment by brb** [comment]
@autumn0207 No, they are different. You can see more connections in Cilium's CT due to:

- In some cases Cilium can bypass netfilter's conntrack because of `skb_redirect()`.
- Cilium creates an additional entry for a connection to k8s Services.

Cilium does not rely on netfilter's conntrack, so no sharing is needed.

**Comment by autumn0207** [comment]
@brb Got it thanks
