### ISSUE TITLE
Connection tracking issue in connections with a single RST.

### ISSUE THREAD

**Issue by aryantaheri** [cilium/cilium#11742]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.7.3 952090308 2020-04-29T15:29:53-07:00 go version go1.13.10 linux/amd64
Daemon: 1.7.3 952090308 2020-04-29T15:29:53-07:00 go version go1.13.10 linux/amd64
```

- Kernel version (run `uname -a`)
```
# uname -a
Linux xyz 4.9.0-0.bpo.12-amd64 #1 SMP Debian 4.9.210-1~deb8u1 (2020-02-21) x86_64 x86_64 x86_64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Kubernetes
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T15:58:45Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

```

- Configuration
Cilium integration with flannel through CNI chaining. Using managed etcd as the kvstore. NodeAffinity is used to control on which nodes Cilium agents are scheduled.

**How to reproduce the issue**
These three cases are tested between two pods in Kubernetes on different nodes, one node has Cilium agent running on it and the other one doesn't have. These tests can be done using `nc(1)` or by crafting packets using [Scapy](https://scapy.net/).

1) [This is a working example, so you may want to jump to (2) or (3)] A TCP Connection was established properly between two pods, then it was terminated with a FIN. In this case everything works as expected.

The conn-track entry immediately after the connection was established: 
```
(1) TCP IN 172.16.42.108:33284 -> 172.16.106.7:7777 expires=705338 RxPackets=12 RxBytes=822 RxFlagsSeen=0x1b LastRxReport=705328 TxPackets=6 TxBytes=408 TxFlagsSeen=0x1b LastTxReport=705328 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=3
```
This CT entry is removed after a few seconds (>20s, which is our `ct-gc-interval`). 

2) The sender tries to open a TCP connection to port `7777` on the receiver. The receiver (where we're observing) didn't have the port open and sends a RST.

These are captured traces for (2):
```
2)
-> endpoint 973 flow 0x274d2956 identity 3->279988 state new ifindex veth9866e6c1 orig-ip 172.16.42.108: 172.16.42.108:52456 -> 172.16.106.7:7777 tcp SYN
-> stack flow 0x274d2956 identity 279988->3 state reply ifindex 0 orig-ip 0.0.0.0: 172.16.106.7:7777 -> 172.16.42.108:52456 tcp ACK, RST
```

This CT entry is created for (2):
```
(2) TCP IN 172.16.42.108:52456 -> 172.16.106.7:7777 expires=727187 RxPackets=2 RxBytes=148 RxFlagsSeen=0x02 LastRxReport=705587 TxPackets=1 TxBytes=54 TxFlagsSeen=0x14 LastTxReport=705587 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=3
```
The record has `expires=727187` which is in about `21600s` from `now`. This is the maximum TCP connection lifetime in [here](https://github.com/cilium/cilium/blob/1.7.3/bpf/node_config.h#L56).

3) The sender (where we're observing) tries to establish a new TCP connection to port `7777` on the receiver. It sends a packet to the port that is closed and receives a RST.

These are captured traces for (3):
```
3)
-> stack flow 0x58208063 identity 279988->3 state new ifindex 0 orig-ip 0.0.0.0: 172.16.106.7:33462 -> 172.16.42.108:7777 tcp SYN
-> endpoint 973 flow 0xf8720d19 identity 3->279988 state reply ifindex veth9866e6c1 orig-ip 172.16.42.108: 172.16.42.108:7777 -> 172.16.106.7:33462 tcp ACK, RST
-> endpoint 973 flow 0xf8720d19 identity 3->279988 state reply ifindex 0 orig-ip 172.16.42.108: 172.16.42.108:7777 -> 172.16.106.7:33462 tcp ACK, RST
```

This CT entry is created for (3):
```
(3) TCP OUT 172.16.106.7:33462 -> 172.16.42.108:7777 expires=727434 RxPackets=2 RxBytes=108 RxFlagsSeen=0x14 LastRxReport=705834 TxPackets=1 TxBytes=74 TxFlagsSeen=0x02 LastTxReport=705834 Flags=0x0011 [ RxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=279988
```
This entry will also expire in about `21600s`. Same as case (2).

This results in connections accumulating in the Cilium CT map and expiring after a long time (6 hours). It should be noted that, reducing `conntrack-gc-interval` won't help because these entries are not eligible to be removed. Also, increasing `bpf-ct-global-tcp-max` significantly will just postpone the problem for a few hours depending on the volume and type of traffic in a cluster. Eventually this results in `CT: Map insertion failed` and dropped packets.

Apparently, a single RST doesn't trigger a shortened timeout and there is an issue in the detection of non-SYN state (Thanks to @tgraf for the hint).

**Comment by joestringer** [comment]
Thanks for the report!

I believe that when Cilium is run on newer kernels (4.10 or later) this issue is mitigated by the use of an LRU (Least-Recently-Used) map which would allow newer connections to bump out older stale entries like this.

That said, I think that https://github.com/cilium/cilium/pull/11684 improves this one step by making it more likely that the datapath will trigger userspace to wake up and perform GC.

One further step to improve this could potentially be to take into account "seen flags" for the connection when performing GC. Either on the datapath side by using presence of RST to update the lifetime of the CT entry, or on the userspace side to consider being more aggressive on deleting entries that have seen RST particularly if their age is beyond some threshold.

**Comment by kkourt** [comment]
Had a look at this issue using a simpler setup with two k8s nodes _both_ running cilium, and a pod trying to connect to another pod (valid IP) in a port that nothing listens to (`cli->srv: SYN`, `srv->cli: ACK,RST`) where the same (presumably) problem appears.

Logs from the client `cli` side:

```
cli->srv: SYN, from-endpoint:
CPU 00: MARK 0xfe6867bb FROM 2287 DEBUG: Conntrack lookup 1/2: src=10.11.0.34:55510 dst=10.11.1.136:6767
CPU 00: MARK 0xfe6867bb FROM 2287 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 00: MARK 0xfe6867bb FROM 2287 DEBUG: CT verdict: New, revnat=0
CPU 00: MARK 0xfe6867bb FROM 2287 DEBUG: Successfully mapped addr=10.11.1.136 to identity=12121
CPU 00: MARK 0xfe6867bb FROM 2287 DEBUG: Conntrack create: proxy-port=0 revnat=0 src-identity=12121 lb=0.0.0.0
```
srv->cli: ACK,RST
```
CPU 00: MARK 0x0 FROM 2287 DEBUG: No message, arg1=7272 (0x1c68) arg2=1 (0x1)
CPU 00: MARK 0x0 FROM 2287 DEBUG: Conntrack lookup 1/2: src=10.11.1.136:6767 dst=10.11.0.34:55510
CPU 00: MARK 0x0 FROM 2287 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 00: MARK 0x0 FROM 2287 DEBUG: CT entry found lifetime=313879, revnat=0
CPU 00: MARK 0x0 FROM 2287 DEBUG: CT verdict: Reply, revnat=0
```

On the return path, even though we get an `RST` flag, the CT verdict is a reply and the entry is updated with a lifetime of `21600s`:

```
TCP OUT 10.11.0.34:55510 -> 10.11.1.136:6767 expires=335419 (in 21591 sec(s) from now) RxPackets=1 RxBytes=54 RxFlagsSeen=0x04 LastRxReport=313819 TxPackets=1 TxBytes=74 TxFlagsSeen=0x02 LastTxReport=313819 Flags=0x0011 [ RxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=12121 IfIndex=0 
```

AFAICT, what happens is:

 * action is set to `ACTION_CLOSE` since there is an `RST` flag https://github.com/cilium/cilium/blob/400dfcb01161cdb9909c6c25da2a7d62e2711357/bpf/lib/conntrack.h#L617
* CT entry is updated with a `CT_CONNECTION_FILETIME_TCP` by: https://github.com/cilium/cilium/blob/400dfcb01161cdb9909c6c25da2a7d62e2711357/bpf/lib/conntrack.h#L214
* CT entry is still alive so the timeout is not updated to `CT_CLOSE_TIMEOUT`: https://github.com/cilium/cilium/blob/400dfcb01161cdb9909c6c25da2a7d62e2711357/bpf/lib/conntrack.h#L259

I've written a patch that distinguishes between `RST` and `FIN` flags as a solution. Not sure how much sense does it make or how it interacts with everything which is why I'm keeping it as a WiP PR  #13511  for now and hope that it can help to make the discussion more concrete.

At a higher level: there seem to be multiple places that we update the lifetime of a CT entry, which can lead to confusion. It might be a good idea to rewrite the logic so that the decision of what the new lifetime of an entry is happens in a single point.
