### ISSUE TITLE
CI: Test Denies traffic with cnp default-deny ingress policy

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#11741]
```
/home/jenkins/workspace/Cilium-PR-K8s-oldest-net-next/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:471
Egress ping connectivity should work
Expected command: kubectl exec -n 202005271537k8spolicytestbasictestchecksallkindofkubernetespoli app2-64975875bc-kcmxr -- ping -W 2 -c 5 8.8.8.8 
To succeed, but it failed:
Exitcode: 1 
Stdout:
 	 PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
	 
	 --- 8.8.8.8 ping statistics ---
	 5 packets transmitted, 0 received, 100% packet loss, time 4081ms
	 
	 
Stderr:
 	 command terminated with exit code 1
	 

/home/jenkins/workspace/Cilium-PR-K8s-oldest-net-next/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/Policies.go:619
```
[e2d53dbd_K8sPolicyTest_Basic_Test_Denies_traffic_with_cnp_default-deny_ingress_policy.zip](https://github.com/cilium/cilium/files/4694250/e2d53dbd_K8sPolicyTest_Basic_Test_Denies_traffic_with_cnp_default-deny_ingress_policy.zip)

**Comment by jrajahalme** [comment]
Seems the timeout increase has no effect:
```
Egress ping connectivity should work
Expected command: kubectl exec -n 202006021858k8spolicytestbasictestchecksallkindofkubernetespoli app2-64975875bc-9gxxv -- ping -W 5 -c 5 8.8.8.8 
To succeed, but it failed:
Exitcode: 1 
Stdout:
 	 PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
	 
	 --- 8.8.8.8 ping statistics ---
	 5 packets transmitted, 0 received, 100% packet loss, time 4081ms
	 
	 
Stderr:
 	 command terminated with exit code 1
```

time still reported as 4 seconds like before?

**Comment by jrajahalme** [comment]
Or, maybe waiting more does not help if the packets were lost? Should be retry after 5 secs instead?

**Comment by qmonnet** [comment]
@jrajahalme I think you are right. The `time 4081ms` seems to indicate the duration for sending the packets (5 ICMP requests, one per second). The `-W 5` increases the timeout for the answer, but if the packet was dropped because the setup was not ready it doesn't really matter whether we wait for longer. We could instead wait longer between the attempts with the `-i` option (or send more requests), I can send a PR to do that. I would probably create a new `SlowPing()` to avoid penalising the other tests when `ping` is supposed to fail.

**Comment by aanm** [comment]
hit in https://github.com/cilium/cilium/pull/12039

**Comment by nebril** [comment]
Closing, didn't see this happening since we added retries.
