### ISSUE TITLE
Metrics are reporting unreachable nodes when Cilium starts up

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#11874]
The connectivity health checking metrics are reporting unreachable nodes in the beginning of the bootstrapping process. This should be avoided to avoid spikes in the metric when new nodes are being added.

Core issue: We don’t have a difference between “unknown” / “unreachable”.

**Comment by mrostecki** [comment]
More details about the core issue: it happens, because HTTP status is usually `nil` before the new node gets bootstraped. Health client then considers the node as "unreachable", here:

https://github.com/cilium/cilium/blob/8c9539205edc25dc06aebe2d38e6f1dd6320b3cf/pkg/health/client/client.go#L152-L160

I think that the fix should be:
- considering PathStatus with `nil` members (`PathStatus.(Icmp|HTTP).Status`) as "unknown"
- considering PathStatus with empty (but not nil) members (`PathStatus.(Icmp|HTTP).Status`) as "healthy"
- considering PathStatus with non-empty members (`PathStatus.(Icmp|HTTP).Status`) as "unreachable
