### ISSUE TITLE
add TCP service  exposure for LB mode

### ISSUE THREAD

**Issue by jenningsloy318** [cilium/cilium#1193]
Hi All,

Hope we can also add TCP service exposure in LB mode agent. situations are when we running  some non-http servcice, such databases, we also need to expose these service to outside.  ingress-nginx-controller have TCP support, but it is not very easy to configure it.  wish we can have a better implementation in Cilium LB function.

**Comment by xjulio** [comment]
Hi folks, is this feature really implemented? Because the commit from the previous comment mentions "closes this issue", but there's nothing related. I did a search in Celium documentation and didn't find anything related to exposing TCP services similar to what Ingress Nginx has:

https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/

**Comment by wibed** [comment]
selfish bump
