### ISSUE TITLE
CI: Refactor curl / wget test helpers with retries

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#11994]
It'd be nice if we have a test helper wrapper for `curl` and `wget` which has retries built in. These retries should only be applied to commands that are expected to be used for connection with the outside / world.

For example:

```
testhelpers.CurlWithRetries(..., retries int, ...)
```

This would eliminate the need for one-off PRs like https://github.com/cilium/cilium/pull/11797 and https://github.com/cilium/cilium/pull/11993. These types of PRs are prone to accumulate tech debt as the number of retries could be incosistent across the code base, etc.. Also, issues like missing a place where retries would be needed, could be eliminated.

**Comment by JieJhih** [comment]
I can take this. Please assign it to me.

**Comment by JieJhih** [comment]
@christarazi I made a draft, for ``CurlWithRetries()`` function under the circumstances:
``CurlFail()`` ``CurlFailNoStats() `` ``CurlWithHTTPCode()`` may expect ``--retry`` flag, so it turns out something like this ``CurlWithRetries(CurlFail(...), retries)``, ``CurlWithRetries()`` function has to handle the string does it contain ``curl`` command, if true it means there have a command, the developer wants it to have retry feature, so just add ``--retry`` flag in the tail, otherwise developer just only wants ``--retry`` flag, so generate the command with ``--retry`` exclusive another flag at the end of the function.

Is this your expectation?
```
func CurlWithRetries(endpoint string, retries int, optionalValues ...interface{}) string {
	if len(optionalValues) > 0 {
		endpoint = fmt.Sprintf(endpoint, optionalValues...)
	}
	if strings.Contains(endpoint, "curl") {
		if strings.Contains(endpoint, "--retry") {
			return endpoint
		}
		return fmt.Sprintf(`%s --retry %d `, endpoint, retries)
	}
	return fmt.Sprintf(
		`curl --path-as-is -s  -D /dev/stderr --output /dev/stderr --retry %d %s`,
		retries, endpoint)
}
```

**Comment by christarazi** [comment]
@JieJhih That sounds like a great idea! Would you mind PRing your changes?

**Comment by JieJhih** [comment]
> @JieJhih That sounds like a great idea! Would you mind PRing your changes?

No problem. I already sent a pull request. Please take a look.
