### ISSUE TITLE
cilium monitor broken on AKS 1.15 (engine 0.47)

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#12070]
While testing the AKS guide, I discovered that `cilium monitor` does not work with Cilium 1.8@f3b474ad3. As soon as I start `cilium monitor` (or enable Hubble), the agent crashes with `failed to create perf ring for CPU 2: can't create perf event: can't create perf event: no such device`. The crash itself will be addressed in #12068, but  `cilium monitor` remains nonfunctional:

*cilium monitor does not display any trace or drop events*

```
$ cilium monitor
Listening for events on 128 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
>> Endpoint created: {"id":606,"pod-name":"pod-to-a-external-1111-7c5c99c6d9-ng8w7","namespace":"default"}
[ no trace/drop events ]
```

Cilium 1.7.5 works fine on the exact same cluster.
Note: The machine does not have 128 cpus, it has 2.

aksEngineVersion: v0.47.0-aks-gomod-55-aks
kubernetes: 1.15.11 
zone: westeurope
os image: Ubuntu 16.04.6 LTS
kernel: `Linux aks-ssh 4.15.0-1083-azure #93~16.04.1-Ubuntu SMP Thu May 7 18:39:44 UTC 2020 x86_64 GNU/Linux`

**Comment by gandro** [comment]
Seems like the node has 125 offline cpus:

```
cat /sys/devices/system/cpu/present
0-1
cat /sys/devices/system/cpu/possible
0-127
cat /sys/devices/system/cpu/offline
2-127
```

**Comment by brb** [comment]
cilium/ebpf is ussing `possible` to determine # of CPUs. However, according to https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/ABI/testing/sysfs-devices-system-cpu:

```
Description:	CPU topology files that describe kernel limits related to
		hotplug. Briefly:

		kernel_max: the maximum cpu index allowed by the kernel
		configuration.

		offline: cpus that are not online because they have been
		HOTPLUGGED off or exceed the limit of cpus allowed by the
		kernel configuration (kernel_max above).

		online: cpus that are online and being scheduled.

		possible: cpus that have been allocated resources and can be
		brought online if they are present.

		present: cpus that have been identified as being present in
		the system.

		See Documentation/admin-guide/cputopology.rst for more information.
```

**Comment by errordeveloper** [comment]
Am I understanding correctly that what's happening is that memory is being allocated per CPU core. While number of present CPU is less then possible, the intention is to allocate memory for all CPU cores, in even each core comes online eventually and memory had already been allocated.

Just trying to understand the subject a little more:
- Would it be possible to allocation on-demand, i.e. whenever CPU core actually come online?
- What happens if CPU goes online and there is no perf ring for it, i.e. in in hotplug situation?

**Comment by gandro** [comment]
@errordeveloper Please check out https://github.com/cilium/ebpf/pull/58#pullrequestreview-353738435 for the previous discussion.

However, the wonky CPU count might be a complete red herring. Cilium 1.7.5 and 1.8-rc both use the same version of `cilium/ebpf`, therefore it's not clear to me why one fails and the other one doesn't.

**Comment by errordeveloper** [comment]
@gandro has bisected this and confirmed that 1256a13bed02ada24ebf693bf2edd5af3bdba7fa is the culprit, I have tried reverted it on master (331aab47f35a4b7e329a2038658845134e362a75), and built an image.
I can confirm that the resulting image has functional `cilium monitor` and `hubble observe`. I've published it as `docker.io/errordeveloper/cilium:17aaff80d3d`.

**Comment by pchaigno** [comment]
As detailed in #12119, `pkg/maps` uses a different value for the `max_entries` of eventsmap and signalmap compared to the loader (`runtime.NumCPU()`) or to `init.sh` (`nproc`).

### Before 1256a13
Then, on startup, in the order (with 128 possible CPUs and 2 present CPUs):
1. `NewDaemon()` calls `initMaps()` which creates an eventsmap and a signalmap with `max_entries=128`: https://github.com/cilium/cilium/blob/f5b7027b488c877c771908944a5e1aeadc6a6c38/daemon/cmd/daemon.go#L361
2. `NewDaemon()` calls `d.init()` which executes `init.sh` and loads part of `bpf_host`: https://github.com/cilium/cilium/blob/f5b7027b488c877c771908944a5e1aeadc6a6c38/daemon/cmd/daemon.go#L570
While doing that, it removes and replaces the existing eventsmap and signalmap because they don't have the same `max_entries` value as defined by `init.sh` (128 vs. 2).
3. `NewDaemon()` calls `NewAgent()` which opens `cilium_events`: https://github.com/cilium/cilium/blob/f5b7027b488c877c771908944a5e1aeadc6a6c38/daemon/cmd/daemon.go#L579
4. After `NewDaemon()` has finished executing, the host endpoint is created and the remaining parts of `bpf_host` are loaded: https://github.com/cilium/cilium/blob/0fa8ac7f4310206e8ce7ecaf5276d785d5c0464b/daemon/cmd/daemon_main.go#L1297 

### After 1256a13
All of `bpf_host` is now loaded as part of the host endpoint in step 4 above. Therefore, step 2 doesn't happen anymore. So, when `NewAgent` is called, it opens the `cilium_events` map with `max_entries=128`.

When `bpf_host` is loaded in step 4, it creates new eventsmap and signalmap with `max_entries=2`, but it doesn't remove the old maps because the agent still has a reference (fd) to them.

Thus, we see 4 perf array maps in sysdump. `cilium monitor` pulls from incorrect `max_entries=128` map and BPF programs write into `max_entries=2` map. The `max_entries=2` map is also the one found at `sys/fs/bpf/tc/globals/cilium_events`.

**Comment by pchaigno** [comment]
There is a comment about this in `NewDaemon()`:
https://github.com/cilium/cilium/blob/f5b7027b488c877c771908944a5e1aeadc6a6c38/daemon/cmd/daemon.go#L577
This is still true because we set up the `cilium_events` map in `initMaps()`, we just need to use the same size everywhere.
