### ISSUE TITLE
Unable to upgrade from Cilium 1.8 to 1.9 without breaking compatibility

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#12288]
Currently a user upgrading from Cilium 1.7 to 1.8 will have to pass `--set config.upgradeCompatibility=1.7` to keep upgrade compatibility [1].

Unfortunately that same user won't be able to upgrade to 1.9 without facing upgrade compatibility issues since we won't be able to distinguish the first version of Cilium that the user installed was 1.7 or 1.8 nor we will be able to distinguish if the user didn't want to keep upgrade compatibility. In case the user wants to use a new option introduced in 1.8 it is a problem if we want to detect which options should be kept with the default values or with breaking values to avoid compatibility issues.

[1] https://docs.cilium.io/en/latest/install/upgrade/#step-2-option-a-regenerate-deployment-files-with-upgrade-compatibility-recommended

**Comment by borkmann** [comment]
Tracking collection of PRs w/ Helm related options only to be enabled for new deployments (need double checking before 1.9 release):

- #12868
- #11279

**Comment by joestringer** [comment]
Let's make sure to check that the CI also sets the upgrade compatibility option correctly.

**Comment by joestringer** [comment]
The above PRs were assuming that the user will specify the first version that they install via `--set upgradeCompatibility` (or add that setting into their values.yaml file). With that assumption, I believe this issue should be addressed.

Followups:
* [ ] Get a second look at whether the upgrade guide sufficiently describes to the user how to correctly configure upgradeCompatibility
* [ ] Use something like the https://github.com/cilium/chaos-monkeys scripts to run traffic through Cilium during such an upgrade and look for network disruption.

**Comment by kkourt** [comment]
For the second look followup, I did an upgrade from 1.8 to 1.9  following the guide and everything worked out well.

#13874 contains some improvements based on trying this.

**Comment by joestringer** [comment]
I updated the chaos-monkey scripts to run with recent helm, kubectl tools and deployed them in a GKE cluster.

First I tried:
* Deploy 1.8.5. Deploy chaos-monkeys. Restart Cilium.
  * I hit https://github.com/cilium/cilium/issues/13881
  * Only the FQDN monkeys crash/restart, which is expected since they rely on DNS resolution and the DNS proxy will become unavailable during upgrade due to the known L7 upgrade issue as documented.

I then waited for the cluster to stabilize again, then:
* Followed the upgrade docs to deploy the preflight checks. Once successfully deployed, deleted them
* Upgraded to 1.9.0-rc3.
  * Hit same issues as above in 1.8.5. No other chaos-monkeys reported issues. (no pod restarts; no slack notifications).

For good measure, after upgrading to 1.9.0-rc3, I tried restarting again and observed the same behaviour.
