### ISSUE TITLE
Cilium restarts if iptables lock is not held in 5s

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#12319]
The `Reinitialize` function runs some itpables commands. If any of these commands fails within 5 seconds, the `Reinitialize` returns an error causing this function to also return an error:
https://github.com/cilium/cilium/blob/ddd8fb1809e974ac7fa3a9f0b9f3dad26e0b2e73/daemon/daemon.go#L595-L599

However, the caller of the function fatals Cilium in case this happens:
https://github.com/cilium/cilium/blob/022349e1431ad67b5dc2f30d963b7f98ca38e017/pkg/datapath/ipcache/listener.go#L327-L335

IMO this should not happen since failing to acquire the iptables rules within 5 seconds might be sporadic and it can be successful if retried.

**Comment by joestringer** [comment]
> failing to acquire the iptables rules within 5 seconds might be sparodic

This is a fair statement if there's legitimate reason to believe there's a slow iptables interaction occurring in the environment. That said, 5s is a long time and if there is an application that's actually not releasing the xtables lock then Cilium could get stuck in this process. In that case per the comment in the second code snippet, the idea is to fail out to make the failure clear rather than silently continuing with an outdated ipcache map for an indeterminate time.
