### ISSUE TITLE
Fail to start if kvstore cannot be reached

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1234]
We currently startup successful and continue trying to establish a connection to the kvstore. This behavior can be subtle and hard to notice. Instead, fail hard if kvstore connectivity can't be established.

**Comment by aalemayhu** [comment]
I have a patch working for consul. Which was also testable because of the max
tries and cilium.sock, https://github.com/cilium/cilium/compare/master...scanf:kvstore-fail-missing

Had trouble with etcd for the failure case. There is no max tries in the code
and when running the daemon without a etcd container it gets stuck at
`concurrency.NewSession(...)`, [pkg/kvstore/etcd.go#L92](https://github.com/cilium/cilium/blob/master/pkg/kvstore/etcd.go#L92).
