### ISSUE TITLE
Conntrack table doesn't get cleared up promptly during load test.

### ISSUE THREAD

**Issue by lzang** [cilium/cilium#12518]
## Bug report

**General Information**

- Cilium version (run `cilium version`): 1.8.0 + loadbalancer cluster local fix. I expect the same issue can be reproduced on master HEAD.
- Kernel version (run `uname -a`) 4.19

**How to reproduce the issue**

1. Run a load test by creating a large number of http connections from multiple client pods to a server pod.  
    The tool I am using is https://github.com/rakyll/hey with the  -disable-keepalive option.
2. Stop and restart the load test for a couple of times.  
2. Observe that a large number of conntrack table entries were created in Cilium ebpf ct table. Stop the load test and found that the entries are not removed even long (> 30 minutes and I don't know when they were removed at the end) after the test is finished.

**Comment by brb** [comment]
Thanks for the report.

- What is your CT GC interval setting (`conntrack-gc-interval`)? It would be good to know your whole configuration.
- Did you hit a case when the CT maps became full?
- There are different lifetime values for different flow types. E.g. for `CT_SERVICE` the default is 21600s (6h; grep for `CTMapEntriesTimeoutSVCTCP`). Was the stress testing tool accessing the server pod via a service?

**Comment by Weil0ng** [comment]
seems like for both service and non-service, the defaults are same (6h)?
https://github.com/cilium/cilium/blob/master/daemon/cmd/daemon_main.go#L681

**Comment by Weil0ng** [comment]
I can reproduce this and it seems for my setup the problem is the following:

- Datapath updates timeout just fine, I see entries with lastTxReport=4400 and expires=4410, which is expected.
- It seems like GC never kicks in soon enough because GC has already been dynamically configured to run only after some 38min because previous low deletion ratio, hence **although datapath hints at deletion after 10s, but GC won't look at ct map until 38m later**

Feels like this is WAE (code-wide) but less ideal? Thoughts?

**Comment by nathanjsweet** [comment]
@Weil0ng can you confirm what your `conntrack-gc-interval` for your latest reproduction of this error is?

**Comment by Weil0ng** [comment]
> @Weil0ng can you confirm what your `conntrack-gc-interval` for your latest reproduction of this error is?

It is not explicitly set, so should be the default value 0.
Also double checked log, GC interval dynamically changing in the log (for the same cluster, it is >7h now that I left the cluster idle overnight).

**Comment by joestringer** [comment]
Feels like this is WAE (code-wise) but less ideal? Thoughts?

This is the impression I get. I understand the high-level concern iff large numbers of CT entries could cause some kind of forwarding issue, however on any recent kernel (ones with LRU map) even if the CT table is full, old CT entries will just be removed rather than getting a "conntrack table full, dropping packet" type behaviour.

There's one other nuanced aspect as it regards to services which is that service backend selection may remain sticky for longer than is ideal, which we also discussed during today's (2020-07-15) sig datapath meeting. [Notes](https://docs.google.com/document/d/1IZZ-FTM_U3zN06-M_mDOgep_DcDM0Oe3YOFVM1BTIt8/edit#heading=h.f8p6tjtu4tn7)

**Comment by Weil0ng** [comment]
Thanks Joe for the update! I agree that signaling control plane with a list of to-delete entries sounds like the most plausible way, but wouldn't it also need another map? also is the point that then GC can run more frequently given that it does not iterate the entire ct table every time?

**Comment by joestringer** [comment]
Most likely the way this would be implemented is by sending each 5tuple of an entry that will need to be deleted 'soon' into the existing 'signals' map (though we could alternatively use a special dedicated map for this purpose). Then yeah with the given set of 5tuples that are likely to need cleanup, we could come up with some more tailored heuristics in userspace for thresholds and scheduling check/cleanup of those specific entries.
