### ISSUE TITLE
BPF-masq unexpectedly SNATs replies to outside

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#12544]
Follow up from https://github.com/cilium/cilium/pull/12482.

See https://github.com/cilium/cilium/pull/12482#discussion_r454691162.

**Comment by brb** [comment]
The test which caught the bug is doing the following:

1. Add a route from outside to podCIDR via node.
2. Sends request to a podIP from outside.
3. A reply (SYN-ACK) gets masqueraded by BPF-masq.
4. The client @ outside drops the reply.

The problem is that the BPF-masq doesn't check whether a packet (podIP -> outside) is a reply, and does SNAT regardless. One possible fix is to consult CT to see whether a packet is a reply.

**Comment by christarazi** [comment]
@brb Any idea on why this only occurs on net-next kernels?

**Comment by brb** [comment]
@christarazi This is because we don't enable the BPF-masq feature on other CI builds (except for 4.19) due to the kernel version constraint.

**Comment by brb** [comment]
Had another thought that fixing this by adding the CT lookup would introduce the perf penalty for each packet from a local endpoint to outside. To make the test to work with BPF-based MASQ, we could add the outside IP addr to the [ip-masq-agent](https://docs.cilium.io/en/v1.8/concepts/networking/masquerading/#ebpf-based).

**Comment by liuyuan10** [comment]
Wondering with this issue, how can nodeport work? The first node snat to node ip and the pod on the 2nd node is returning traffic to node IP. Will the return traffic get masqueraded?

**Comment by brb** [comment]
> Wondering with this issue, how can nodeport work? The first node snat to node ip and the pod on the 2nd node is returning traffic to node IP. Will the return traffic get masqueraded?

@liuyuan10 No, it won't be masqueraded because of https://github.com/cilium/cilium/blob/master/bpf/lib/nodeport.h#L1193 (the 1st node IP addr is going to be in the IPCache of the 2nd node)
