### ISSUE TITLE
CI: K8sDatapathConfig MonitorAggregation Checks that monitor aggregation restricts notifications hits CI job timeout of 3 hours

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#12555]
https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-newest-kernel-4.9/1185/
[75bc68be_K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications.zip](https://github.com/cilium/cilium/files/4932364/75bc68be_K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications.zip)
https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-newest-kernel-4.9/1194/

The test output isn't reported by Jenkins because we dump too much info. (i.e., `cilium monitor -vv` output during several minutes). However, grepping through the logs in artifacts gives:
```
22:08:13 STEP: Checking that ICMP notifications in egress direction were observed
22:12:23 FAIL: Egress ICMPv4 flow ("ICMPv4.*DstIP=10.0.1.143") not found in monitor log
```

This flake seems to happen fairly frequently (about 1/5 locally).

[consoleFull output of the test](https://github.com/cilium/cilium/files/4934037/consoleFull.txt.xz.zip) (beware, it's 2.2GB once uncompressed, and you need to remove the .zip extension as GH would complain otherwise).

**Comment by pchaigno** [comment]
When reproducing locally, I'm able to see the ICMPv4 messages in the `cilium monitor` logs. Maybe the real issue is that `cilium monitor` wasn't fully started yet when we sent the ping and it's therefore missing in output? See https://github.com/cilium/cilium/issues/9330#issuecomment-576481804 in a previous flake on the same test.

**Comment by joestringer** [comment]
I'm not sure if this was observed before, but it seems to me that this behaviour coincides with hitting the 3h timeout in CI which implies that we're not detecting that the test takes a long time. (I'd do a trivial check of the log to confirm but it's 2.2GB and causes java heap space issues on jenkins + known to crash browsers so .... well even that by itself is probably a signal that our testing framework code isn't handling this case well :sweat_smile: )

**Comment by joestringer** [comment]
A few points:

* There's obviously the core issue itself of why we don't find the ICMPv4 message in the output. That may the same long-running issue in #9330.
* We output `cilium monitor -vv` and this causes a lot of output to be generated. Do we need `-vv` to inspect packet contents or would `-v` or even no verbosity be sufficient to validate that the ICMP flows are seen?
* The test itself should complete within a short period of time, but it is not. Seems like it's unbounded and we only stop running the test because of the overall job timeout of 3h.

**Comment by pchaigno** [comment]
I tried adding a small sleep after the call to start `cilium monitor` as follows, but that doesn't seem to have any effect. The bug still happens, and about as frequently.
```diff
--- a/test/k8sT/DatapathConfiguration.go
+++ b/test/k8sT/DatapathConfiguration.go
@@ -821,6 +821,7 @@ func monitorConnectivityAcrossNodes(kubectl *helpers.Kubectl) (monitorRes *helpe
 
        By(fmt.Sprintf("Launching cilium monitor on %q", ciliumPodK8s1))
        monitorRes, monitorCancel = kubectl.MonitorStart(helpers.CiliumNamespace, ciliumPodK8s1)
+       time.Sleep(10*time.Second)
        result, targetIP := testPodConnectivityAndReturnIP(kubectl, requireMultinode, 2)
        ExpectWithOffset(1, result).Should(BeTrue(), "Connectivity test between nodes failed")
```

**Comment by pchaigno** [comment]
I attached the complete logs to the issue (after a few fights with GitHub). Looking at them, the test that fails only takes 8min and 31s. So maybe the builds takes so long because of some issue during log collection afterwards, maybe caused by the huge `ciium monitor -vv` dump.

**Comment by joestringer** [comment]
Ah... many of the messages are `from-network`. I believe this is a regression due to #12245.

**Comment by joestringer** [comment]
I believe that we basically induced this behaviour by causing monitor notifications to be sent & processed & logged for every single packet coming into the node, which I would expect to significantly increase load on the system. Depending on what else is going on in the system, this could potentially cause too many `from-network` messages to be logged such that either (1) The ringbuffer overflows and we lose events or (2) We are unable to print the desired ICMPv4 flow to the file before the test times out because we print so many other flows. I wouldn't be surprised if there's a portion of the test which furthermore assumes that the output is small and attempts to load the entire file into memory, causing other CI issues due to memory usage. I noted that in the file I downloaded from the GH issue here from @pchaigno , the last line of the file is still monitor output, which presumably means that the rest of the jenkins page was truncated. This would be consistent with the UI presenting a java heap space error if we were to run out of memory on the jenkins node.

All of this points to two things: `monitorAggregationLevel=None` should be considered harmful, and #12559 should fix the issue.
