### ISSUE TITLE
CRD schema auto generation follow ups

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#12737]
- [x] Auto generate the CRD schema version - I've some ideas around that which would help https://github.com/cilium/cilium/pull/12493 as well.
  - [x] Automatic detection of CRD changes and increment the CRD schema validation version 
- [x] Resolve https://github.com/cilium/cilium/issues/13155 by creating a preflight check to ensure no policies have a top-level description
- [x] Generate CRDs for all other resources: https://github.com/cilium/cilium/pull/11476
- [x] GitHub Action to run `make manifests` to generate the CRDs and check for any drift (similar to `make generate-k8s-api`)
  - Generating CRDs is now part of the `make generate-k8s-api` target: https://github.com/cilium/cilium/pull/12805
- [x] Transition from v1beta1 to v1 CRDs: https://github.com/cilium/cilium/pull/11477
- [x] Move the CRD into the `quick-install.yaml` by putting in the CRD directory of helm. There is a special directory for CRDs in helm: https://github.com/cilium/cilium/pull/13310
  - See comment below on this item: https://github.com/cilium/cilium/issues/12737#issuecomment-701007713
  - Obsoleted by https://github.com/cilium/cilium/issues/12737#issuecomment-856713156
- [x] Promote https://github.com/christarazi/controller-tools to be under the Cilium org (from https://github.com/cilium/cilium/pull/13055#discussion_r482592330): https://github.com/cilium/cilium/pull/18185

### Higher priority
- [x] Add documentation to the K8s compatibility section about people upgrading from K8s < 1.16 to K8s >= 1.16 while running Cilium >= 1.9 should make sure to run the pre-flight checker from above: https://github.com/cilium/cilium/pull/13273
- [x] Remove "dead" code that CRDs (https://github.com/cilium/cilium/pull/11477#discussion_r487816729): https://github.com/cilium/cilium/pull/13272
- [x] Now that we depend on the operator to do cluster operation, the CRD update / check can be done by the operator instead of the cilium-agents: https://github.com/cilium/cilium/pull/13285
- [x] Replace go-bindata with `//go embed` https://github.com/cilium/cilium/pull/15834

**Comment by christarazi** [comment]
Re: 
> Move the CRD into the quick-install.yaml by putting in the CRD directory of helm. There is a special directory for CRDs in helm. 

As of Sep 2020, Helm 3.3.4 supports [two ways to manage CRDs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource), with only one of them considered ["best practice"](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you):

1) Official: Use special `crds/` directory inside the chart to put your CRDs in. Helm will install all CRDs prior to contacting the apiserver. [The caveat is they cannot be templated](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you).
2)  You can store your CRDs inside a regular `templates/` directory, which gives you the power to do anything with them just like any other template. 

The problem with approach (1) is that there's no way to support both v1 and v1beta1 versions of the CRD. This is problematic because we support versions of K8s that do not understand v1 CRDs, so we must support both. Because Helm [does not contact the apiserver before installing them](https://github.com/helm/helm/blob/e17500018edfede7a96bebd455d99fb26789ae91/pkg/action/install.go#L184), it cannot know which version of K8s the CRDs are being installed on. 

The problem with approach (2) is that if you `helm uninstall`, CRDs will also be removed, causing all CRs created under them to also be removed. This would be unfortunate for a user if they accidentally removed all their policies, or endpoints, etc.

The current state now is to wait on upstream Helm to better support CRDs (https://github.com/helm/helm/issues/5871).

**Comment by KlavsKlavsen** [comment]
https://github.com/helm/helm/issues/5871 was unfortunately abandoned - so Helm is not going to manage CRDs appearently, apart from initial install.. no upgrade handling or anytning :(

**Comment by christarazi** [comment]
@KlavsKlavsen Thanks for the update, good to know.

**Comment by christarazi** [comment]
Closed as all items have been completed :tada:.

**Comment by christarazi** [comment]
Closed as all items have been completed :tada: .
