### ISSUE TITLE
Allow IPSec and KubeProxyReplacement=strict (NodePort)

### ISSUE THREAD

**Issue by martin31821** [cilium/cilium#12978]
## Proposal

I'd like to be able to run a kube-proxy-less cilium installation on baremetal nodes with encryption enabled.
This is a tracking issue as suggested by @jrfastab and @joestringer. 

Related resources:
https://github.com/cilium/cilium/blob/fb0c3e592d7a9da854f9d38345fbb5720ea3b073/daemon/cmd/datapath.go#L481
https://linuxplumbersconf.org/event/7/contributions/683/
https://github.com/cilium/cilium/blob/fb0c3e592d7a9da854f9d38345fbb5720ea3b073/pkg/datapath/linux/ipsec/ipsec_linux.go#L433

I started working on a PR but it's not working yet.

**Comment by brb** [comment]
Unassigned @martin31821, as https://github.com/cilium/cilium/pull/12985 became abandoned.

**Comment by brb** [comment]
I took a stab at it (https://github.com/cilium/cilium/tree/pr/brb/lets-be-friends-with-ipsec; non-working). Due to the fact that we pass a packet to the stack to do encryption / decryption, adding NodePort BPF support would complicate the datapath code even more (esp the `from-netdev` entry point; also, we would need to add the lb lookup to `to-host`). That could be avoided if we introduce BPF helpers for IPSec.

Anyway, for now I switched my focus to adding the Wireguard encryption support which is much easier to integrate into our datapath (only L2-less <-> L2 dev handling is a bit painful).

**Comment by BurlyLuo** [comment]
Can we reopen this issue?

**Comment by sgargan** [comment]
Any movement on this? I'd be very interested in this feature

**Comment by fredwangwang** [comment]
any updates on this?

I am looking into use Cilium's Gateway API feature, in the docs it mentioned the KubeProxyReplacement has to be enable. However we also has IPSec configured. Which seems like there is no way for us to use the gateway feature.

**Comment by julianwiedmann** [comment]
thanks to @pchaigno support for this configuration actually landed in Cilium v1.16 :tada:.
