### ISSUE TITLE
Batch iterator for bpf.Map

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#13129]
Newer kernels (v5.6 or newer) provide batched lookup/delete APIs for maps. We should take advantage of these in cases like the conntrack map garbage collection to reduce the number of system calls / CPU consumed to perform GC.

**Comment by ti-mo** [comment]
This is feasible for 1.15 and has the potential to make the GC scanning phase ~an order of magnitude faster on supported kernels, though at the expense of more allocations in Go. ebpf-go has preliminary support for batching, but it isn't very well integrated with the rest of the map API yet.

**Comment by ti-mo** [comment]
Going to take this one off the tracker since a select few heavy-hitting maps have started using batch ops (ct/nat) for collecting metrics. Doing transparent batching across all maps is not something we're looking at due to its complexity and potential for regressions. The efforts we've made so far have resulted in an improved API (BatchCursor) on the ebpf-go side as well, so things are in better shape today. Subsystems that see a benefit from using batch ops can use them today.
