### ISSUE TITLE
Recompute security identity for endpoint running w/ K8s if labels are updated

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1314]
If labels are updated for a Kubernetes pod running with Cilium, update the security identity for the pods that have had their labels updated.

**Comment by ianvernon** [comment]
cc: @danwent

**Comment by danwent** [comment]
Yes, this would be very valuable for an integration that I'd like to demo :)

**Comment by danwent** [comment]
A basic test I performed seems to imply that this works.  I tested by deploying fission.io on top of cilium, since fission relabels the pods once it assigns a function to a particular pod.  I was able to see these new labels with "cilium endpoint list" and the re-labeled pod got a new distinct security id.   So at least in the common case, this already works.

**Comment by tgraf** [comment]
OK. I remember that @aanm added this functionality. I'll close this for now, we can reopen when we find missing functionality.
