### ISSUE TITLE
Cilium not cleaning cni configuration while uninstalling.

### ISSUE THREAD

**Issue by Buffer0x7cd** [cilium/cilium#13152]
While testing Cilium in Azure CNI mode ( without chaining ), It seems like cilium is not cleaning up the `05-cilium.conf` file from the `/etc/cni/net.d` directory, During uninstallation. This is causing Kubelet to generate lots of error like below

`kubelet[3524]: W0911 13:15:36.525325    3524 cni.go:202] Error validating CNI config &{cilium 0.3.1 false [0xc001103120] [123 34 99 110 105 86 101 114 115 105 111 110 34 58 34 48 46 51 46 49 34 44 34 110 97 109 101 34 58 34 99 105 108 105 117 109 34 44 34 112 108 117 103 105 110 115 34 58 91 123 34 99 110 105 86 101 114 115 105 111 110 34 58 34 48 46 51 46 49 34 44 34 101 110 97 98 108 101 45 100 101 98 117 103 34 58 102 97 108 115 101 44 34 110 97 109 101 34 58 34 99 105 108 105 117 109 34 44 34 116 121 112 101 34 58 34 99 105 108 105 117 109 45 99 110 105 34 125 93 125]}: [failed to find plugin "cilium-cni" in path [/opt/cni/bin]]`.

**General Information**

- Cilium version 1.8.3
- Kernel version 1.8.3
- Orchestration system version in use: Kubectl v1.18.0, Azure AKS
- Link to relevant artifacts (policies, deployments scripts, ...)

**How to reproduce the issue**

1.  Use the default instruction for installing cilium in azure cni mode
2. Check the directory containing the config file `/etc/cni/net.d/05-cilium.conf`
3. Remove cilium using helm delete and verify that files are `/etc/cni/net.d/05-cilium.conf` present
4. Furthur error logs can be seen from running `journalctl -fu kubelet`

**Comment by aanm** [comment]
@Buffer0x7cd having the file present is expected. Currently there's no way to tell kubelet that the user is removing or upgrading Cilium. In case of upgrading we can't remove the file as otherwise a pod could start being managed by another CNI plugin that is not Cilium.

**Comment by Buffer0x7cd** [comment]
Thanks for the info, I am assuming in the above scenario kubelet will pick up the next valid config (this was not clear from the docs) and ignore cilium.

**Comment by aanm** [comment]
@Buffer0x7cd yes. Which docs are not clear? Is there anything that we could have make it better in our docs?

**Comment by ti-mo** [comment]
Also hit this today. During `preStop` of the Cilium agent pod, the CNI plugin binary is removed from `/opt/cni`, but the CNI config in `/etc/cni/net.d` is kept there. After uninstalling Cilium, `kubelet` spams errors like:

```
Error validating CNI config list {.. full cni config here ...}: [failed to find plugin "cilium-cni" in path [/opt/cni/bin]]
```

This message is generated every 5s due to kubelet calling `VERSION` on the first CNI config in `/etc/cni/net.d`.

Still need to verify whether pod creation actually fails if the Cilium CNI binary is gone, otherwise there's not much use leaving the config there. It will also break pod scheduling on clusters where Cilium is installed and removed.

(Looking into this because there are multiple other fundamental issues with disabling azure-vnet when installing Cilium in Azure IPAM mode, will link everything together soon.)

**Comment by ti-mo** [comment]
> Still need to verify whether pod creation actually fails if the Cilium CNI binary is gone, otherwise there's not much use leaving the config there.

As expected, if the `cilium-cni` binary is deleted, `kubelet` will ignore Cilium's CNI configuration and just use the next-available working one. As a result, keeping a broken `05-cilium.conf` in place is not a solid strategy for keeping pods from being scheduled with another CNI plugin during a Cilium upgrade.
