### ISSUE TITLE
Health-check backend pods when LRP is active

### ISSUE THREAD

**Issue by Weil0ng** [cilium/cilium#13168]
Per offliine discussion with @aditighag, periodically health-checking backends picked by active LRP is desired to ensure cluster functionality.

A few concerns:
- If all backends become unhealthy, should we remove/circumvent LRP? What's the channel of notification to users that it is no longer in effect?
- Should we drop LRP entirely if all backends are unhealthy for a prolonged time?

**Comment by aditighag** [comment]
Thanks @Weil0ng for looking into this. 

> 
> * If all backends become unhealthy, should we remove/circumvent LRP? What's the channel of notification to users that it is no longer in effect?
We currently add a `local-redirect service entry` for an LRP only when there is at least 1 backend pod for the LRP. Once the entry is plumbed, when the last backend pod is removed, we delete the service entry as well. (The logic is in redirectpolicy/manager.go #12831 ). We can similarly monitor pod health status, and update the service entry accordingly. When there is no service entry for an LRP, there won't be any traffic redirection enabled for the LRP. 
I don't see any reason to remote the LRP entirely since pod's health status can change over time.

We could potentially use the CRD status field in order to notify the user about these updates. But there are some scale related issues due to which we disable updating such status fields. /cc @aanm @joestringer for any other insights.
Alternatively, we can expose an LRP status via CLI (#13156 ).


> * Should we drop LRP entirely if all backends are unhealthy for a prolonged time?
Please check reply above.

**Comment by joestringer** [comment]
I'm not sure I understand the motivation for any dedicated status fields in the LRP if we are trying to modify the implementation of LRP services based on the health of pods. I would think that the existing k8s health check infrastructure should be able to be used, and Cilium merely needs to respect the pod healthiness when considering backends to plumb for an LRP.

**Comment by aanm** [comment]
> I'm not sure I understand the motivation for any dedicated status fields in the LRP if we are trying to modify the implementation of LRP services based on the health of pods. I would think that the existing k8s health check infrastructure should be able to be used, and Cilium merely needs to respect the pod healthiness when considering backends to plumb for an LRP.

+1. If I may add as well, if we keep "stale" entries, those IPs might no longer exist locally and be redirected to elsewhere in the network.

**Comment by aditighag** [comment]
> I'm not sure I understand the motivation for any dedicated status fields in the LRP if we are trying to modify the implementation of LRP services based on the health of pods. I would think that the existing k8s health check infrastructure should be able to be used, and Cilium merely needs to respect the pod healthiness when considering backends to plumb for an LRP.

+1

As discussed [here](https://github.com/cilium/cilium/issues/13156#issuecomment-691359444), we would be dumping pod backend information for all the LRPs in the CLI output.

**Comment by aditighag** [comment]
> +1. If I may add as well, if we keep "stale" entries, those IPs might no longer exist locally and traffic be redirected to elsewhere in the network.

Not sure I understand your comment around stale entries. As I mentioned in my [previous comment](https://github.com/cilium/cilium/issues/13168#issuecomment-692213286), we currently delete entries with no backends, which should be done in case of unhealthy pods too.

**Comment by aanm** [comment]
> > +1. If I may add as well, if we keep "stale" entries, those IPs might no longer exist locally and traffic be redirected to elsewhere in the network.
> 
> Not sure I understand your comment around stale entries. As I mentioned in my [previous comment](https://github.com/cilium/cilium/issues/13168#issuecomment-692213286), we currently delete entries with no backends, which should be done in case of unhealthy pods too.

sorry, I was replying to this
>Should we drop LRP entirely if all backends are unhealthy for a prolonged time?

**Comment by Weil0ng** [comment]
>+1. If I may add as well, if we keep "stale" entries, those IPs might no longer exist locally and traffic be redirected to elsewhere in the network.

I agree that the map entry should be purged, but what about the CR itself? If we use status field as suggested by @aditighag and keep the CR, then when the backends are up again we can re-enable this redirection automatically, is that desired behavior? The alternative is that we remove the CR when no backend is alive and user then has to recreate it.

**Comment by joestringer** [comment]
The lifecycle of the LRP is managed entirely by the user, Cilium itself should not modify the resource in k8s apiserver.

Once the LRP is inserted into k8s, Cilium will learn about it and can cache the existence of this "desired state" so that when the backends change it can easily refer to the LRPs to figure out how to plumb the backend. Cilium will then also subscribe to these backend changes so that when backends arrive or leave, the effect on the LRP is calculated and applied to the datapath.
