### ISSUE TITLE
Move packages from `pkg/` to `internal/`

### ISSUE THREAD

**Issue by ti-mo** [cilium/cilium#13344]
Following a discussion in https://github.com/cilium/cilium/pull/13323#issuecomment-700773995, this is an exploratory issue to consider moving packages from `pkg/` to `internal/` if they do not contain any symbols intended for direct external consumption.
The main motivation being API compatibility guarantees, as well as the Go tooling not flagging unused symbols in `pkg/` by default, since they might be consumed from anywhere outside the package or repo.

Given the size of the directory, this might prove challenging, as it's a huge cross-cutting change that will impact most live branches. I couldn't immediately find an existing issue, but Hubble had a similar one here: https://github.com/cilium/hubble/issues/164.

This could be handled gradually by the maintainers/owners of each component over the course of multiple releases. Any opinions? Has this been discussed here before?

**Comment by joestringer** [comment]
I agree that Cilium doesn't follow the common etiquette in this regard, in practice we treat `pkg/` as `internal/`. 

> The main motivation being API compatibility guarantees

I think it would be useful to expand on this to be specific. On average, we have attempted to ensure high compatibility for the CRDs as we interact with k8s and I think that's about it.  I think Hubble is starting to motivate real API guarantees since during upgrade the `hubble-relay` version may differ from the `cilium` (hubble server) version for an extended period.

If existing software is using `pkg/` and we move it to `internal/`, what options does that software have? If they rebase, can they import `github.com/cilium/cilium/internal/foo/`? I realise this is counter to the idea of `internal/`, but I want to understand what kind of impact that moving this code would have, would we cause more trouble to current consumers of `pkg/` simply by moving the filepath than the average ongoing trouble from making arbitrary changes / rearranging under `pkg/` from release to release?

I think for the most part, there is still too much ongoing churn in most of the `pkg/` code to reasonably think about formalizing much of the "library" code we have under `pkg/`.

>  Go tooling not flagging unused symbols in 'pkg/' by default,

That's unfortunate, it would be nice to flag those unused symbols.

> This could be handled gradually by the maintainers/owners of each component over the course of multiple releases

I'm afraid of the impact this kind of churn would have on backports. It almost seems simpler to me to try to make the change all at once.

At a balance, I don't necessarily disagree that conforming to Go project norms would make API guarantees more obvious since it would be implicit in the filepaths. However I worry that this will be busy-work that introduces a lot of churn with not a lot of value.

**Comment by gandro** [comment]
> If existing software is using `pkg/` and we move it to `internal/`, what options does that software have? If they rebase, can they import `github.com/cilium/cilium/internal/foo/`?

This is a very important point: **External client will not be able to import any `github.com/cilium/cilium/internal` packages anymore.** `internal/` is a name with a special meaning in Go that permits imports from outside of the source tree: https://golang.org/doc/go1.4#internalpackages

Therefore I do share many of the concerns @joestringer laid out. There are projects that include Cilium packages as a library, e.g. Hubble being one example (albeit the number of imports has been reduced drastically since we embedded Hubble server in the Cilium tree). 

If we decide to move packages to `internal/`, we would have to ensure that any client code which is using Cilium as a library can keep importing its packages by making sure to keep these externally used packages outside of `internal/`. This is further complicated by the fact that there are likely non-public source trees as well which import parts of Cilium that we would inadvertently break with such a change.

**Comment by ti-mo** [comment]
Closing as it's not considered viable at this point in time. Maybe if new packages are added, those can go into `internal/`.
