### ISSUE TITLE
cilium-operator does not use IAM Role for ServiceAccounts to access AWS API

### ISSUE THREAD

**Issue by hikhvar** [cilium/cilium#13701]
## Bug report

We deploy our clusters with eksctl 0.30. Since ekstl 0.28 the nodes do not get the Policy `arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy ` attached. Therefore we want to use an [IAM Role for ServiceAccounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html). However, the cilium-operator seem to ignore this instance role since our logs of the cilium-operator says:
```
level=info msg="Retrieving own metadata from EC2 metadata server..." subsys=ipam-allocator-aws
level=info msg="Connected to EC2 metadata server" instance=i-08cb4b6758811177c region=eu-central-1 subsys=ipam-allocator-aws
level=info msg="Connected to EC2 service API" subsys=ipam-allocator-aws
level=warning msg="Unable to synchronize EC2 interface list" error="UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 23cb8daa-90bc-49e0-94eb-358a2e609770" subsys=eni
level=fatal msg="Unable to start eni allocator" error="Initial synchronization with instances API failed" subsys=cilium-operator-aws
```

**General Information**

- Cilium version: 1.8.4
- Kernel version: 4.14.198-152.320.amzn2.x86_64
- Orchestration system version in use: managed elastic kubernetes v1.18.8-eks-7c9bda

**How to reproduce the issue**

Deploy cluster with eksctl >= 0.28.0 . Enable `withOIDC`. 
Deploy cilium with the official helm chart in ENI mode:
```
  kubectl apply -f - <<EOF
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-cni-configuration
  namespace: kube-system
data:
  cni-config: |
    {
      "cniVersion": "0.3.1",
      "name": "cilium",
      "type": "cilium-cni",
      "enable-debug": false,
      "eni": {
        "first-interface-index": 0,
        "subnet-tags": {
           "kubernetes.io/cluster/cluster-name": "shared"
        }
      }
    }
EOF

helm upgrade --install --reset-values cilium cilium/cilium    --version 1.8.4 \
    --namespace kube-system \ 
    --set "global.eni=true" \
    --set "config.ipam=eni" \
    --set "global.cni.configMap=cilium-cni-configuration" \
    --set "global.egressMasqueradeInterfaces=eth0" \
    --set "global.tunnel=disabled" \
    --set "global.nodeinit.enabled=true" \
    --set "global.hubble.enabled=true" \
    --set "global.hubble.listenAddress=:4244" \
    --set "global.hubble.metrics.enabled={dns,drop,tcp,flow,port-distribution,icmp,http}" \
    --set "global.hubble.relay.enabled=true" \
    --set "global.hubble.ui.enabled=true" 
```

Overwrite the cilium-operator service account with eksctl:
```
eksctl create iamserviceaccount \             
    --name cilium-operator \
    --namespace kube-system \
    --cluster cluster-name \
    --attach-policy-arn arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy \
    --approve \
    --override-existing-serviceaccounts
```
Now delete the existing operator pods to trigger an injection of the IRSA token and env variables:
```
kubectl delete pods -n kube-system -l "io.cilium/app=operator"
```

The pods env looks like this:
```
kubectl describe pod -n kube-system cilium-operator-55cf8d97bb-xq447
Name:                 cilium-operator-55cf8d97bb-xq447
Namespace:            kube-system
[....]
Controlled By:  ReplicaSet/cilium-operator-55cf8d97bb
Containers:
  cilium-operator:
    Container ID:  docker://0dc151f58d699026bff79c2d3b3358f8bc7d979c58e5fef70af15dbaa6b7d4ca
    Image:         docker.io/cilium/operator-aws:v1.8.4
    Image ID:      docker-pullable://cilium/operator-aws@sha256:68d4a24fc5388063d8f4f679c276f838f069851a039e8e5678d4b7db0667d48f
    Port:          <none>
    Host Port:     <none>
    Command:
      cilium-operator-aws
    Args:
      --config-dir=/tmp/cilium/config-map
      --debug=$(CILIUM_DEBUG)
[...]
    Environment:
      K8S_NODE_NAME:                 (v1:spec.nodeName)
      CILIUM_K8S_NAMESPACE:         kube-system (v1:metadata.namespace)
      CILIUM_DEBUG:                 <set to the key 'debug' of config map 'cilium-config'>           Optional: true
      AWS_ACCESS_KEY_ID:            <set to the key 'AWS_ACCESS_KEY_ID' in secret 'cilium-aws'>      Optional: true
      AWS_SECRET_ACCESS_KEY:        <set to the key 'AWS_SECRET_ACCESS_KEY' in secret 'cilium-aws'>  Optional: true
      AWS_DEFAULT_REGION:           <set to the key 'AWS_DEFAULT_REGION' in secret 'cilium-aws'>     Optional: true
      AWS_ROLE_ARN:                 arn:aws:iam::xxxxxxxx:role/eksctl-cluster-name-addon-iamserviceaccou-Role1-1PFQQDTWNTIFT
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /tmp/cilium/config-map from cilium-config-path (ro)
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from cilium-operator-token-jzwbq (ro)

```

**Comment by errordeveloper** [comment]
hi @hikhvar, thanks for reporting this!

I think that using `arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy` maybe insufficient for Cilium as the implementation differs from AWS VPC CNI significantly.

Since Cilium relies on [EKS instance role](https://docs.aws.amazon.com/eks/latest/userguide/create-node-role.html), I'd recommend adding `arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy`. If you could test it, it would be very helpful.

**Comment by hikhvar** [comment]
I can cross check this. 
However, my current workaround is to manually add the policies `arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy` and `arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy`  to my worker nodes instance profile. This works so far. Furthermore I could not see any access to the cilium service account instance role in the IAM console. Thus I thought, cilium is not using the instance role at all. I tried to debug this in the go code myself but I did not see any odd settings. But I'm not that familar with the aws-go-sdk-v2.

**Comment by errordeveloper** [comment]
@hikhvar did you have a chance to try using both policies with the service account?

**Comment by hikhvar** [comment]
Ok, I removed the `arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy` policy from the worker nodes instance roles. Than I added `arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy` to the service account role of the cilium operator. 

Now I'm back to the start of this issue. The pods are unable to list the interfaces.

My next step was to upgrade to cilium 1.9.0 since the used aws-sdk was bumped to v0.23 from v0.18 

https://github.com/cilium/cilium/pull/12393

But now I still get:
```
level=info msg="Initializing IPAM" mode=eni subsys=cilium-operator-aws
level=info msg="Starting ENI allocator..." subsys=ipam-allocator-aws
level=info msg="Retrieving own metadata from EC2 metadata server..." subsys=ipam-allocator-aws
level=info msg="Connected to EC2 metadata server" instance=i-0e06c11adbbd82f9f region=eu-central-1 subsys=ipam-allocator-aws
level=info msg="Connected to EC2 service API" subsys=ipam-allocator-aws
level=warning msg="Unable to synchronize EC2 interface list" error="UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 2d16e8e1-394c-40c6-8225-91024e173cfe" subsys=eni
level=fatal msg="Unable to start eni allocator" error="Initial synchronization with instances API failed" subsys=cilium-operator-aws
```

**Comment by hikhvar** [comment]
So, fixed the service acoount mapping. Upgrading to cilium 1.9.0 fixed the issue for me :tada:

**Comment by errordeveloper** [comment]
@joestringer @aanm I am not sure if we should consider this as a 1.8 bug that needs addressing, I think this is just a missing feature - wdyt?

**Comment by aanm** [comment]
If it is fixed in 1.9.0 we can close this issue since it is fixed.

**Comment by errordeveloper** [comment]
@aanm I am just looking back at this, and looks like we are using AWS SDK v2, which is still beta. This feature was supposed to work automatically with classic SDK supported since [1.23.13](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html). I have looked at [v2's changelog](https://github.com/aws/aws-sdk-go-v2/blob/master/CHANGELOG.md), but couldn't see any reference to this... I am slightly concerned that v2 could be still too  experimental. I'll keep looking, it would be good to link to an upstream issue.

**Comment by errordeveloper** [comment]
Ok, looks like SDK v2 was just lagging behind v1 on this feature (see https://github.com/aws/aws-sdk-go-v2/issues/338 and https://github.com/aws/aws-sdk-go-v2/pull/507.

**Comment by JESWINKNINAN** [comment]
Getting the same error in newer version as well(1.9.6)

`level=info msg="Connected to EC2 service API" subsys=ipam-allocator-aws
level=warning msg="Unable to synchronize EC2 interface list" error="UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: xxxxx" subsys=eni`

Have verified Imdsv2 and Imdsv1 is working fine in my worker nodes.(Given this because of aws-sdk-v2 depedency)

Followed this for Cilium deployment: https://docs.cilium.io/en/v1.9/gettingstarted/k8s-install-eks/#deploy-cilium, Actually didn't spend much on troubleshooting this issue, Do I need to configure any additional thing to use the worker role. From the error it says that it was not able to authenticate.

**Comment by wreed4** [comment]
Having this same issue on all latest images and tools.

**Comment by vi2co** [comment]
Cilium helm chart is designed in the way that you have to set  `.Values.eni.iamRole: <iam-role-arn>` parameter. The chart will create cilium-operator service account annotations for you. Otherwise, cilium-operator will fail because the AWS default region environment variable is not set ([link]( https://github.com/cilium/cilium/blob/v1.14.5/install/kubernetes/cilium/templates/cilium-operator/deployment.yaml#L97)).

**Comment by skywalkr** [comment]
For anyone stumbling across this:

- the Cilium Operator requires ec2:DescribeVpcs which is not available in the AmazonEKS_CNI_Policy
- the newer AmazonEKSWorkerNodeMinimalPolicy also does not have this permission so you would need to add it manually or use the original AmazonEKSWorkerNodePolicy
