### ISSUE TITLE
CI, GKE: Connectivity Checks service.kubernetes.io/service-proxy-name label implementation

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#13752]
```
Stacktrace
/home/jenkins/workspace/Cilium-PR-K8s-GKE/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Timed out after 30.000s.
All Cilium pods should remove the service from its services list
Expected
    <int>: 0
to equal
    <int>: 2
/home/jenkins/workspace/Cilium-PR-K8s-GKE/src/github.com/cilium/cilium/test/k8sT/Services.go:403
```
https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/2940/testReport/junit/Suite-k8s-1/16/K8sServicesTest_Checks_ClusterIP_Connectivity_Checks_service_kubernetes_io_service_proxy_name_label_implementation/

**Comment by jibi** [comment]
I tried to reproduce this on GKE with a fresh image built from master:

```sh
$ CNI_INTEGRATION=gke K8S_VERSION=1.16 ginkgo -v --focus="K8sServicesTest.*Checks ClusterIP Connectivity.*label implementation" -noColor -- -cilium.provision=false -cilium.kubeconfig=`echo ~/.kube/config` -cilium.image="<build from master>" -cilium.operator-image="docker.io/cilium/operator" -cilium.hubble-relay-image="docker.io/cilium/hubble-relay" -cilium.passCLIEnvironment=true
```

but the test run just fine:

```sh
Ran 1 of 409 Specs in 213.283 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 408 Skipped
PASS

Ginkgo ran 1 suite in 3m36.433631227s
Test Suite Passed
```

Are we still seeing this in CI GKE tests?

**Comment by joestringer** [comment]
> Are we still seeing this in CI GKE tests?

Looks like it, yeah: https://datastudio.google.com/s/qAyX1z8XQe0

**Comment by pchaigno** [comment]
> > Are we still seeing this in CI GKE tests?
> 
> Looks like it, yeah: https://datastudio.google.com/s/qAyX1z8XQe0

All failures pointed by that link either happened in CI jobs with all tests failing (so unlikely related) or on v1.9 as linked above. Maybe this flake became a v1.9-only flake.

The v1.9 failure is at https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/5348/testReport/junit/Suite-k8s-1/17/K8sServicesTest_Checks_ClusterIP_Connectivity_Checks_service_kubernetes_io_service_proxy_name_label_implementation/.
[6b4d77ce_K8sServicesTest_Checks_ClusterIP_Connectivity_Checks_service.kubernetes.io-service-proxy-name_label_implementation.zip](https://github.com/cilium/cilium/files/6407822/6b4d77ce_K8sServicesTest_Checks_ClusterIP_Connectivity_Checks_service.kubernetes.io-service-proxy-name_label_implementation.zip)

**Comment by pchaigno** [comment]
Nice, another flake solved just before the weekend :-)

Looking at the code of the test, we can see that it checks that a given clusterIP VIP isn't in the list of services handled by cilium, that is `cilium service list`. We have one test artifact for a failed test, so let's check it.

`test-output.log` gives us the full logs of the test: what was executed, when, what failed, etc. Using that we can find the IP being searched for in `cilium service list`: it is looked up using command `kubectl -n default get service echo -o json` and is `10.87.241.25`:
```
cmd: "kubectl -n default get service echo -o json" exitCode: 0 duration: 199.16835ms stdout:
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"name\":\"echo\",\"namespace\":\"default\"},\"spec\":{\"ports\":[{\"name\":\"http\",\"port\":80,\"protocol\":\"TCP\"},{\"name\":\"tftp\",\"port\":69,\"protocol\":\"UDP\"}],\"selector\":{\"name\":\"echo\"},\"type\":\"NodePort\"}}\n"
        },
        "creationTimestamp": "2021-04-30T16:07:56Z",
        "name": "echo",
        "namespace": "default",
        "resourceVersion": "544792",
        "selfLink": "/api/v1/namespaces/default/services/echo",
        "uid": "5300538b-8fe0-4d09-b665-d9425bb0578b"
    },
    "spec": {
        "clusterIP": "10.87.241.25",
```

The same file has the successive outputs from `cilium service list`, so we can check that that IP is present in these outputs. And indeed, it kind of is:
```
cmd: "kubectl exec -n kube-system cilium-h82xz -- cilium service list" exitCode: 0 duration: 742.004037ms stdout:
ID   Frontend              Service Type   Backend                 
1    10.87.240.1:443       ClusterIP      1 => 35.247.116.7:443   
2    10.87.245.217:443     ClusterIP      1 => 10.84.1.94:443     
3    10.87.240.10:53       ClusterIP      1 => 10.84.1.175:53     
                                          2 => 10.84.1.28:53      
4    10.87.241.252:80      ClusterIP      1 => 10.84.1.104:8080   <-- The IP we're looking for (10.87.241.25), with a 2 at the end ;-)
5    10.128.15.215:30548   NodePort       1 => 10.84.1.104:8080   
6    0.0.0.0:30548         NodePort       1 => 10.84.1.104:8080   
7    10.87.243.65:3000     ClusterIP      1 => 10.84.2.111:3000   
8    10.87.242.110:9090    ClusterIP      1 => 10.84.2.128:9090   
9    10.87.255.175:80      ClusterIP      1 => 10.84.1.115:80     
                                          2 => 10.84.1.220:80     
10   10.87.255.175:69      ClusterIP      1 => 10.84.1.115:69     
                                          2 => 10.84.1.220:69 
```

So now, you've guessed it, the match against `cilium service list` is probably done using a grep of sorts and fails because the searched IP happens to be the prefix of another VIP. No wonder it only happens once in a blue moon.

Looking at the code for the test, we get the confirmation: https://github.com/cilium/cilium/blob/63c1e92366a90755aa4c9d68520940388e169a1f/test/k8sT/Services.go#L544-L558
Line 551 shows we just check the clusterIP is contained in the output, which is the case.

Several other tests have the same issue, so I'll send a fix in a few minutes.
