### ISSUE TITLE
bpf: allow for bounded loops

### ISSUE THREAD

**Issue by borkmann** [cilium/cilium#1376]
If upper loop boundary is an immediate constant or determined by a register's max deduced value when of dynamic nature, we should allow verifier for looping in these cases (aka jump backwards via BPF jmp insns). Compared to current pragma unroll, this would shrink # insns. Wrt dynamic # iterations, they are currently not possible. The loop itself needs to have limitations in terms of jumping in/out of the loop and tracking modifications to iterator as verifier needs to prove safe termination. Eval possibilities for a preferred native integration (and if deemed unrealistic find a slower way through helpers, for example).

**Comment by jrfastab** [comment]
One common case will be to iterate over data 'byte' by 'byte' so we would also need to track pkt access min/max in this case.

**Comment by borkmann** [comment]
Upper bound could be complexity limit for native backward jumps when not letting dfs bail out.

**Comment by jrfastab** [comment]
Started to mock this up, needs more work, but here is a high level sketch,

 - Build dominator tree using some method lengauer tarjan, or faster derivatives (nodes map to insn)
 - Build API to query for "natural loops"
 - In pusn_insn() instead of erroring on back-edges if back-edge is a natural loop mark insn for further analysis, (new insn state BPF_LOOP_NATURAL/BPF_LOOP_HEADER)
  - In do_check() when JMP class and BPF_LOOP_NATURAL need to go to BPF_LOOP_HEADER insn and trace register from JMP. Mark register (induction variable) as linear always increasing or linear always decreasing or undecided. Finally, do case analysis to determine if loop terminates.
  - Assuming loop terminates compute min/max range of register
  - Run verification again over loop with new min/max range
  - At this point we should "know" loop terminates and also doesn't violate any other bounds (e.g. packet access, etc.)

TBD: account for insn in loops
