### ISSUE TITLE
change PolicyAuditMode config option through CLI doesn't affect datapath

### ISSUE THREAD

**Issue by jaffcheng** [cilium/cilium#13902]
## Bug report

**General Information**

- Cilium version v1.8.4
- Kernel version 4.14.67
- Orchestration system version in use K8S v1.17.3

**How to reproduce the issue**

1. create some test pods on node1 and a deny-all CiliumNetworkPolicy enforcing on them, all traffic accessing test pods should be denied
https://docs.cilium.io/en/v1.8/policy/language/#ingress-egress-default-deny
2. execute the following command in cilium-agent on node1 to enable `PolicyAuditMode` on this node, all traffic accessing test pods are expected to be allowed
```
cilium config PolicyAuditMode=enable
```
3. `cilium config | grep PolicyAuditMode` displays the expected output, but traffic to test pods are denied
```
PolicyAuditMode          Enabled
```
cc @ArthurChiao

**Comment by jaffcheng** [comment]
It seems that this is due to CLI config change only triggers a `RegenerationWithoutDatapath` while `PolicyAuditMode` requires BPF recompilation:  
https://github.com/cilium/cilium/blob/73be2c15ced2d54aecdfa462b38d2aac2e6f631f/daemon/cmd/policy.go#L67-L76

**Comment by joestringer** [comment]
@jaffcheng good catch, you're right. Will you submit a patch to ensure that specifically when changing PolicyAuditMode it regenerates the datapath?

**Comment by ArthurChiao** [comment]
By the way, toggle on/off global PolicyVerdictNotification (`cilium config PolicyVerdictNotification=false`) is also broken due to the same reason as @jaffcheng described above.

AND, toggle off **endpoint-level** PolicyVerdictNotification is broken due to bpf compiling errors, a patch is submitted for review: https://github.com/cilium/cilium/pull/13921, @joestringer 

Thanks!

**Comment by jaffcheng** [comment]
Thanks for checking! I'll send a PR.
