### ISSUE TITLE
ConfigMap generated by Helm contains duplicates

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#13999]
Running `helm template` with the parameters used for GKE creates a configmap which contains duplicate keys. This is likely overall a bug in the Helm charts and might _not_ be GKE specific. @twpayne discovered this while generating YAML files for GKE.

How to reproduce:
```console
$ helm template cilium cilium/cilium --version 1.9.0 \
  --namespace cilium \
  --set nodeinit.enabled=true \
  --set nodeinit.reconfigureKubelet=true \
  --set nodeinit.removeCbrBridge=true \
  --set cni.binPath=/home/kubernetes/bin \
  --set gke.enabled=true \
  --set ipam.mode=kubernetes \
  --set nativeRoutingCIDR=$NATIVE_CIDR > cilium-gke.yaml
$ pip install --user yamllint
...
$ yamllint -d relaxed --no-warnings cilium-gke.yaml
cilium-gke.yaml
  151:3     error    duplication of key "tunnel" in mapping  (key-duplicates)
  185:3     error    duplication of key "ipam" in mapping  (key-duplicates)

```

The `tunnel` key also contains conflicting values, which makes this potentially more dangerous:

```console
$ egrep 'tunnel|ipam' cilium-gke.yaml
  tunnel: vxlan
  ipam: "kubernetes"
  tunnel: "disabled"
  ipam: "kubernetes"

```

This also happens on Cilium 1.8.5.

**Comment by sayboras** [comment]
I think there was exsiting issues or slack discussion before, saying that gke.enabled and ipam.mode should not be set together.

**Comment by PranaviRoy** [comment]
I identified the lines where the keys are getting duplicated, and so I would like to take a shot at creating the patch ✌🏼

The `tunnel` key gets duplicated because there's no condition around line 303 and when **_gke is enabled_** the control goes through lines 314 to 320, where `tunnel` key is set again at line 317
https://github.com/cilium/cilium/blob/ddb2423fae063ec050bd0332981c5d78f7a39396/install/kubernetes/cilium/templates/cilium-configmap.yaml#L303-L320

And here variable `$ipam` is compared against `"hostscope"`,
https://github.com/cilium/cilium/blob/ddb2423fae063ec050bd0332981c5d78f7a39396/install/kubernetes/cilium/templates/cilium-configmap.yaml#L615-L617

which was set here to `kubernetes`,  so that's getting duplicated as well.
https://github.com/cilium/cilium/blob/ddb2423fae063ec050bd0332981c5d78f7a39396/install/kubernetes/cilium/templates/cilium-configmap.yaml#L34

**Comment by PranaviRoy** [comment]
Although, I understand that we can put the `tunnel` key at line 303 around a condition which checks if _.Values.gke.enabled_ is true or not, I’m not sure what **“hostscope”** defines here. 
Should we put the `ipam` key at line 616 within a condition that checks for _.Values.gke.enabled_ as well or are there any other checks involved?

**Comment by gandro** [comment]
@PranaviRoy Thanks for digging into this. We discussed this in today's Cilium Community meeting, here is what I think we should do:

1. We want to add a check for `.Values.gke.enabled` for the `tunnel` key as you suggested.
    The old `hostscope` ipam mode has been removed in Cilium 1.9.0: https://github.com/cilium/cilium/issues/12974 and I believe what you found is a leftover which did not get removed by accident. Therefore you may safely remove that check for hostscope and replace it with a check for `.Values.gke.enabled` instead.

2. For the `ipam` duplicate, we actually want to remove the `ipam` key from the `gke.enabled` section here and require the user to set it explicitly. So all that is needed is to remove the `ipam` line here:
https://github.com/cilium/cilium/blob/f66515219c21041f17d424cb8f2ca2b1b81c4687/install/kubernetes/cilium/templates/cilium-configmap.yaml#L316

**Comment by PranaviRoy** [comment]
If we remove ipam from this block 
https://github.com/cilium/cilium/blob/f66515219c21041f17d424cb8f2ca2b1b81c4687/install/kubernetes/cilium/templates/cilium-configmap.yaml#L314-L320

and we replace this check with `gke.enabled` i.e. if its **true** then we won't be setting `ipam` anywhere if `gke.enabled: false`. Similarly if the check is for `gke.enabled: false` then we won't be setting `ipam` if `gke.enabled: true`
https://github.com/cilium/cilium/blob/ddb2423fae063ec050bd0332981c5d78f7a39396/install/kubernetes/cilium/templates/cilium-configmap.yaml#L615-L617

**Comment by PranaviRoy** [comment]
In my opinion we can either,
1. add the check for `gke.enabled: false` in here, so that `ipam` is set here if _gke is not enabled_
https://github.com/cilium/cilium/blob/ddb2423fae063ec050bd0332981c5d78f7a39396/install/kubernetes/cilium/templates/cilium-configmap.yaml#L615-L617
and let `ipam` be set here if _gke is enabled_
https://github.com/cilium/cilium/blob/f66515219c21041f17d424cb8f2ca2b1b81c4687/install/kubernetes/cilium/templates/cilium-configmap.yaml#L314-L320
**OR**
2. remove `ipam` from here 
https://github.com/cilium/cilium/blob/f66515219c21041f17d424cb8f2ca2b1b81c4687/install/kubernetes/cilium/templates/cilium-configmap.yaml#L314-L320
and remove the check from here altogether and let `ipam` be set explicitly, always
https://github.com/cilium/cilium/blob/ddb2423fae063ec050bd0332981c5d78f7a39396/install/kubernetes/cilium/templates/cilium-configmap.yaml#L615-L617

**Comment by gandro** [comment]
Ah, apologies, I think I mixed up `tunnel` and `ipam` above when talking about the `hostscope` check above.

> In my opinion we can either,
> 
>       [...]
>
>        **OR**
> 
>     2. remove `ipam` from here
>        https://github.com/cilium/cilium/blob/f66515219c21041f17d424cb8f2ca2b1b81c4687/install/kubernetes/cilium/templates/cilium-configmap.yaml#L314-L320
>        
>        and remove the check from here altogether and let `ipam` be set explicitly, always
>        https://github.com/cilium/cilium/blob/ddb2423fae063ec050bd0332981c5d78f7a39396/install/kubernetes/cilium/templates/cilium-configmap.yaml#L615-L617

Yes, I think we should go with option 2 here. From what I gathered during the Cilium Community meeting, it is intentional that we ask users to explicitly set the IPAM mode.

**Comment by PranaviRoy** [comment]
> Yes, I think we should go with option 2 here. From what I gathered during the Cilium Community meeting, it is intentional that we ask users to explicitly set the IPAM mode.

Okaay!!
