### ISSUE TITLE
what is the difference between hostport and localredirectpolicy?

### ISSUE THREAD

**Issue by liweilun1** [cilium/cilium#14003]
in hostport mode external traffic from any other not kubernetes node can connect to the hostport node，but in localredirectpolicy addressMatcher mode it seems only allow the node which has the addressMatcher‘s ip to connect ,maybe the other kubernetes node also can connect but i don't make a test .  so I have this question as I asked. Or this function is designd for the external workloads, make it convinent for no needs to change the application config

**Comment by aditighag** [comment]
LRPs enable users to specify configurations to redirect **application pod traffic** to a backend pod running on the same node as the application pod. For example, the `addressMatcher LRP` that you mentioned lets user specify <ip address/port/protocol> tuple as a frontend configuration and backend pod configuration where application pod traffic destined to this frontend is redirected to. On the other hand, the `serviceMatcher LRP` lets user specify a Kubernetes `clusterIP` service for which traffic from pods need to be redirected to only node-local backend pods. 
LRPs only apply to East-West traffic and not for North-South external workloads. 
 
You can also read about the use cases that LRPs enable in order to understand this better - https://docs.cilium.io/en/latest/gettingstarted/local-redirect-policy/#use-cases.

Let us know if you need additional clarification.
