### ISSUE TITLE
Policy Cache for Acceleration

### ISSUE THREAD

**Issue by hazelnutsgz** [cilium/cilium#14038]
I was wondering if cillium consider caching the historical network policy for the acceleration purpose. Or has it already been implemented in the current version?

Thanks.

**Comment by aanm** [comment]
> I was wondering if cillium consider caching the historical network policy for the acceleration purpose. Or has it already been implemented in the current version?
> 
> Thanks.

Hi @hazelnutsgz can you clarify what is the "historical network policy"? Thank you.

**Comment by hazelnutsgz** [comment]
It is just a very rough idea, what I want to say is that for the two messages(they are the same) that would go through a very COMPLEX cillium filter(ebpf programs). Can cillium memorize the decision of the first packet, then can fetch the decision from the cache for the second packet, which could accelerate the filtering procedure.

Thanks.

**Comment by aanm** [comment]
@hazelnutsgz That sounds a good idea but the policy can change in flight. In this case, Cilium needs to enforce the new policy for ongoing packets. This policy decision is done by performing a lookup in a eBPF map which is a simple operation.

**Comment by aanm** [comment]
the ebpf map contains the policy which is updated by the userspace. The code can be found here https://github.com/cilium/cilium/blob/75a2b474ead9a9b3373dc821054a9a8183087c0c/bpf/lib/policy.h#L90

**Comment by joestringer** [comment]
:+1: indeed, this is already implemented via hash tables in the eBPF implementation.

If you're interested in researching more in this area and coming up with a more concrete proposal, I'm sure we'd be open to hearing more ideas. You're welcome to post further on this issue, or you could join the Cilium slack #development channel to discuss further.

For now, I think without a clear idea of what could be implemented, this issue seems to be a general request to "make Cilium faster", which is always an ongoing development area so I'll be inclined to close out the issue in favour of tracking specific items that we can implement to achieve the goal.
