### ISSUE TITLE
Use GitHub Actions (as a CronJob or other trigger) to bump cilium-runtime image

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#14050]
This can be useful to detect newly reported vulnerabilities in the container image on DockerHub / Quay. 

Quay seems to have an API: https://docs.quay.io/api/swagger/#!/secscan

**Comment by sayboras** [comment]
seems like [dependabot](https://dependabot.com) can be useful here 🤔

**Comment by sharlns** [comment]
Thank you for opening an issue for this! 🚀

It would be awesome to scan our images during CI/CD. It doesn't have to be blocking but in this way we can get the CVEs immediately for all the built images, we can group them in a consistent manner and track the issues. Not just randomly scanning one or two.

I used Anchore from Sysdig before integrated with Jenkins - it was okay, it did the job. https://sysdig.com/opensource/anchore/ and https://github.com/anchore/anchore-engine

@jedsalazar used the community edition of AquaSec before: https://www.aquasec.com/products/container-security/ 

But I think everything would be useful from that group and almost every tool has an API/easy to integrate. And apparently some customers were already asking for it. There is a thread in Slack about it: https://isovalent.slack.com/archives/CHAA21WJU/p1606295500014300

**Comment by sayboras** [comment]
> But I think everything would be useful from that group and almost every tool has an API/easy to integrate. And apparently some customers were already asking for it. There is a thread in Slack about it: https://isovalent.slack.com/archives/CHAA21WJU/p1606295500014300

I think this slack discussion is no tpublic :thinking:.

+1 for aqua security, I have a good experience with their product. Local development with trivy is great as well.

**Comment by christarazi** [comment]
@sharlns Thanks for the additional context. If you think it's useful enough, let's copy-paste the Slack discussion from the link.

**Comment by sharlns** [comment]
@christarazi Sure! 

tgraf Nov 25th at 9:11 AM
@aanm @joe Vlad (Palantir) has reported that Aqua’s image scanner is reporting vulns in the 1.7 image. Quay is confirming this. We should be rebasing the 1.7 image with the next release. Can we track this somehow or what should I do as next step to ensure we don’t forget?

natalia  5 days ago
I can also create a github issue so we don't forget. Can we ask for the logs to see what is the specific vulnerability that the Aqua scanner picked up?

aanm  5 days ago
@natalia the quay logs are available here https://quay.io/repository/cilium/cilium/manifest/sha256:74e90ae8e891c2d2b01693b1830a6dbd6b25f70413ee702a42699fe977a5ed66?tab=vulnerabilities

natalia  5 days ago
hmm, for me it looks like:
- for the systemd there is a patch
- gcc vuln requires local access
the sqlite3 may be an Apple specific CVE 
I’d also propose to create a “cve-tracker” repo somewhere which would include the specific image + the CVEs found. @aanm do you use a repo something similar during development?

aanm  5 days ago
which would include the specific image + the CVEs found
can you clarify this? for what purpose?

natalia  5 days ago
to keep track what kind of vulnerabilities were found in what kind of image and to fix them in the next release (if there is a patch/fix already)

aanm  5 days ago
1 sec

aanm  5 days ago
@natalia do you have access to this page? https://github.com/cilium/cilium/security/advisories?state=draft

aanm  5 days ago
that's sort of where we keep track of the CVE that directly affect Cilium, not CVEs that affect dependencies

natalia  5 days ago
Yep, I think something similar would make sense for the images and the dependencies inside. @jed @robin?

aanm  5 days ago
just FYI at the moment we can't do much:
Could not pull base image: API error (500): You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


aanm  5 days ago
I'll keep retrying

natalia  5 days ago
thank you! 

aanm  5 days ago
the base image was rebuild [0]. unfortunately the vulnerabilities are still there because they are not fixed upstream and we have done a apt-get update && apt-get upgrade -y.
[0] https://quay.io/repository/cilium/cilium-runtime/manifest/sha256:506ad6f869330eb73b7a12c42843dad0dfe6c1d2d34de4ab72939ce7852a1875?tab=vulnerabilities

aanm  5 days ago
which to be fair, quay doesn't show a "FIXED IN VERSION" for any of them

robin  5 days ago
Food for thought: have we already tried to reduce the attack surface, ie strip down images/use small base images where possible/etc in the past? For instance, do we need to ship sqlite3 with the image? Have we ever considered something like "distroless" images? In the end, if our production images only contain the bare minimum we want, there'll be less CVEs to worry about.

tgraf  5 days ago
It’s a difficult question with multiple factors playing a role:
llvm/clang has been driving a lot of the distro dependencies
The troubleshooting use case can make the possibility of installing tcpdump and similar quite nice. If we strip down, we need to consider how we continue to allow troubleshooting without being in a position where we ask users to run entirely new DaemonSets all of a sudden.

robin  5 days ago
If we get a list of troubleshooting tools that must be available, that could help creating a base image that only contains what's needed for runtime+troubleshooting but not more.
At least, the operator/relay/clustermesh-apiserver images are doing well in that regard as the base image is scratch.
(and yes, ephemeral debug container is unfortunately only alpha as of k8s v1.18 :sad-parrot: )

natalia  5 days ago
also not quite related but @jed created a document listing the security issues we are having currently in the Cilium setup: https://docs.google.com/document/d/1sQibx5ZhhPbqtXYen7y8r2D7wmNtlM-E4Ur8RzhGh9I/edit#heading=h.x89x93mlfgvc

tgraf  5 days ago
I agree with everything said I just want to be careful that we all of a sudden break current troubleshooting flows

tgraf  5 days ago
I think the main reason for not having a scratch image in the first place is clang which requires glibc as far as I know

robin  5 days ago
I think it's pretty clear we can't use scratch as the base image for cilium-agent, even if just because we want to be able to kubectl exec into agent pods for troubleshooting. We could probably still try to reduce the number of installed packages to a bare minimum.

aanm  5 days ago
kind of related https://github.com/cilium/cilium/issues/9411

jed  5 days ago
+1 to hardening the Cilium base image and moving debugging tools to a dedicated daemonset (so long as it doesn't break our troubleshooting workflows). When an attacker lands in a pod with network debugging tools (tcpdump, nc, etc), it makes their job of reconn and lateral movement a lot easier, particularly if the deployment is locked down with Network Policy. Do we often encounter occurrences where customer's can't deploy a daemonset for debugging purposes?
I'm also curious if we're vuln scanning our images in CI. I've been manually poking at our enterprise images with trivy and inspecting deployments with DEEPCE but there's probably a better, more automated way of doing so

tgraf  5 days ago
We mainly use the quay scanner for now

jed  5 days ago
Would it be worth reaching out to Liz Rice to see if she can help with something like a community edition of Aqua Sec? :wink:
https://www.aquasec.com/products/container-security/

tgraf  5 days ago
What is the advantage over quay?

jed  5 days ago
@tgraf it has some interesting features like informing you whether a given CVE is actively being exploited in the wild, allows you to group images based on a product/application, and has a nifty risk assessment tool built in (based on whether the attack is exploitable over the network, has active exploits in the wild, etc) for easier triage. this might be too heavy-weight for us, but it's a great tool I've used in the past

natalia  5 days ago
@jed I agree with scanning our images during CI/CD - if we don't do it now. It doesn't have to be blocking but in this way we can get the CVEs immediately for all the built images, we can group them in a consistent manner and track the issues. Not just randomly scanning one or two.
I used Anchore from Sysdig before integrated with Jenkins - it was okay, it did the job. https://sysdig.com/opensource/anchore/ and https://github.com/anchore/anchore-engine
But I think almost everything is fine from that category (edited) 

danwent  5 days ago
Northwestern Mutual had also brought up some issues on the image scanning front.  I think the proposal at the time was to add something to the release documentation that prior to any release we would check the scan results and create a release blocking bug if there were key issues identified by the scanner.   But @joe probably remembers this discussion in more detail.

joe  5 days ago
There's an item on the release checklist today but it's basically "check if quay reports that there are vulnerabilities that have fixes released". As someone pointed out above, quay reports the vulnerabilities but the distro we used as the basis for v1.7 has not been updated to resolve those issues.

aanm  5 days ago
@joe where is that item....?

joe  5 days ago
That has been the case for months, some of the dependency vulnerabilities are very old. I don't think that Canonical has any intent to fix them

joe  5 days ago
@aanm step 5: https://github.com/cilium/cilium/issues/14158

tgraf  5 days ago
CI is not really enough, right? We typically get CVEs for older images that are already released

tgraf  5 days ago
We need regular scanning 

aanm  5 days ago
@joe I saw the GH issue but I totally miss that step maybe because it's checked 

aanm  5 days ago
We need regular scanning
we are considering it: https://github.com/cilium/cilium/issues/14050

christarazichristarazi
#14050 Use GitHub Actions (as a CronJob or other trigger) to bump cilium-runtime image
This can be useful to detect newly reported vulnerabilities in the container image on DockerHub / Quay.
Quay seems to have an API: https://docs.quay.io/api/swagger/#!/secscan
