### ISSUE TITLE
Prevent Kubelet from using a different CNI on Cilium upgrades

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#14128]
The initial implementation of CNI in Kubelet was made by checking for a valid configuration file, `*.conf`, in the configuration directory, which has the default of `/etc/cni/net.d`. This behavior allowed Cilium to be safely upgraded while other CNI configuration files were available as Kubelet would keep retrying Cilium’s configuration file until the Cilium CNI binary was available, where this binary is removed and re-added for each upgrade.

Unfortunately, this behavior has changed and Kubelet now picks the first valid CNI configuration file with a valid CNI binary. In a machine where multiple CNI configuration files are available, this might cause issues during a Cilium upgrade where Kubelet will use a different CNI plugin, for application pods, making those application pods to never be managed by Cilium.

To avoid this issue a proposed solution is to change the file extension of existing (edit: non-Cilium) CNI configuration files from `*.conf` and `*.conflist` to `*.conf.cilium_bak` and `*.conflist.cilium_bak` respectively. These files would only be reverted when the user would want to explicitly uninstall Cilium or when `cilium cleanup` command would be executed in this host. Since Kubelet only checks for the presence of `*.conf` and `*.conflist` it will not consider any other CNI configuration when setting up the application pods.

cc @ti-mo

**Comment by ti-mo** [comment]
Thanks, this could work! Edited the issue to specify `non-Cilium` CNI configs to be renamed, had to read that a couple of times for it to sink in. :wink:

**Comment by joestringer** [comment]
:scream: Was there a discussion of upgrade impact upstream?

**Comment by ti-mo** [comment]
> :scream: Was there a discussion of upgrade impact upstream?

Doesn't look like it: https://github.com/kubernetes/kubernetes/pull/80482. We were relying on an implementation detail rather than an explicit guarantee. A missing CNI binary causing scheduling errors was a reasonable assumption on our part, but this is not defined in the CNI spec, nor is it mentioned in the k8s docs anywhere.

This behaviour was changed in https://github.com/kubernetes/kubernetes/commit/9903cb3ad33bd0ce21256a6c5b6275b1ba557cc5 and saw its first release in `v1.16.0-beta.1`. CNI plugins are validated in lexical order w/ first-found principle.

CNI configs are checked for CNI binaries being present and those plugins supporting the configured CNI version.

@aanm Alternatively, we could point the CNI config to a wrapper script or binary that always passes `CHECK` commands even if the actual CNI binary is absent. but that feels like even more of a hack.

What about my (thus far ignored) suggestion of letting the user cordon all nodes before initiating an upgrade? This looks like the most robust and maintainable solution in the long term.

**Comment by ti-mo** [comment]
https://github.com/cilium/cilium/pull/14095 also contributes to solving this.

**Comment by tgraf** [comment]
Maybe we should just leave the `cilium-cni` binary on disk during restart?

The validation does this:
```
// ValidateNetworkList checks that a configuration is reasonably valid.
// - all the specified plugins exist on disk
// - every plugin supports the desired version.
//
// Returns a list of all capabilities supported by the configuration, or error
func (c *CNIConfig) ValidateNetworkList(ctx context.Context, list *NetworkConfigList) ([]string, error) {
```

Leaving the binary on disk will cause it to fail and thus retry without us having to modify the existing configuration on disk.

**Comment by aanm** [comment]
> Maybe we should just leave the `cilium-cni` binary on disk during restart?
> 
> The validation does this:
> 
> ```
> // ValidateNetworkList checks that a configuration is reasonably valid.
> // - all the specified plugins exist on disk
> // - every plugin supports the desired version.
> //
> // Returns a list of all capabilities supported by the configuration, or error
> func (c *CNIConfig) ValidateNetworkList(ctx context.Context, list *NetworkConfigList) ([]string, error) {
> ```
> 
> Leaving the binary on disk will cause it to fail and thus retry without us having to modify the existing configuration on disk.

I like that approach better. One issue I'm seeing is if Kubelet is in the middle of a "CNI ADD", our `cilium-cni` will keep retrying to connect the cilium-agent, until it gives up. If Cilium is being upgraded at that time, the agent will be available and will receive an API call from that out-of-date `cilium-cni` binary. If we decide to leave the binary behind we will need to add a client version ID to detect if the agent should process the API request or if it should refuse it, forcing the old `cilium-cni` binary to stop the retries. Kubelet will then re-run the "CNI ADD" call in the new `cilium-cni` binary for which the cilium-agent will process the API request as the client version ID matches with the ID the agent should accept.

**Comment by ti-mo** [comment]
> Leaving the binary on disk will cause it to fail and thus retry without us having to modify the existing configuration on disk.

Note: kubelet also skips a CNI plugin if it fails a CNI `CHECK` call. We currently specify a `nil` check handler, so checks always pass, and kubelet will always pick Cilium if the CNI config + binary exists.

https://github.com/cilium/cilium/blob/b3c840889332bf94d0c60fb4427fef1a9d6108dd/plugins/cilium-cni/cilium-cni.go#L81-L85

However, if we ever add a check handler that returns false, we will again regress on this behaviour. Instead, taking ownership of `/etc/cni/net.d` is waterproof, since no other CNIs would be eligible regardless of Cilium's `CHECK` behaviour or upstream behavioural changes to kubelet.

**Comment by ti-mo** [comment]
Implementation proposal: https://github.com/cilium/cilium/pull/14192
