### ISSUE TITLE
helm: partly- and un-implemented 'extra*' parameters

### ISSUE THREAD

**Issue by errordeveloper** [cilium/cilium#14133]
With #13210 new parameters were added in `values.yaml`:

https://github.com/cilium/cilium/blob/dcda3fd98d6cc748561c334ace996da8195c2218/install/kubernetes/cilium/values.yaml#L84-L107

These are declared for all components, but some are appear to be implemented in part, and some are not implemented:
```
$ git grep extraArgs install/kubernetes/cilium/templates
install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:{{- range $key, $value := .Values.extraArgs }}
$ git grep extraEnv install/kubernetes/cilium/templates           
install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:{{- with .Values.extraEnv }}
install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:{{- if .Values.extraEnv }}
install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:{{ toYaml .Values.extraEnv | indent 8 }}
install/kubernetes/cilium/templates/cilium-operator-deployment.yaml:{{- range $key, $value := .Values.operator.extraEnv }}
$ git grep extraInitContainers install/kubernetes/cilium/templates
$ git grep extraHostPathMounts install/kubernetes/cilium/templates 
install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:{{- range .Values.extraHostPathMounts }}
install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:{{- range .Values.extraHostPathMounts }}
install/kubernetes/cilium/templates/cilium-operator-deployment.yaml:{{- range .Values.operator.extraHostPathMounts }}
install/kubernetes/cilium/templates/cilium-operator-deployment.yaml:{{- range .Values.operator.extraHostPathMounts }}
$ git grep extraConfigmapMounts install/kubernetes/cilium/templates
$
```

**Comment by errordeveloper** [comment]
I think it maybe plausible to remove some some of the params from certain components, e.g. I'm not sure if there is use for any of these params in `nodeinit`.

**Comment by joestringer** [comment]
Maybe @seanmwinn can speak more to each instance of these, but the goal was to ensure they all have these extra args implemented so that it doesn't require a brand new Cilium release to fix up something in a user environment if necessary. That said I'm not sure if we actually sat down and had the conversation about which of these extra argument type helm sections make sense depending on the individual component being configured.

I see two possible fixes: One is just we go through with a comb and make sure they're all written correctly. The other is to sit down and reason about what kind of changes we think may be plausible by users and use that thinking to trim down on these extra options.
