### ISSUE TITLE
Kube-router and ipam: cluster-pool not working 

### ISSUE THREAD

**Issue by manuelbuil** [cilium/cilium#14152]
## Bug report

I followed the documentation: https://docs.cilium.io/en/v1.9/gettingstarted/kube-router/ and I see how kube-router is announcing the routes, but unfortunately they are based on `ipam: kubernetes` instead of `ipam: cluster-pool`. The latter is the option I have in my configmap. Consequently, my pods are getting IPs from an IP range different from the one in the node routing table, which breaks connectivity across nodes.

**General Information**

- Cilium version (run `cilium version`)
Client: 1.9.0 dcda3fd98 2020-11-10T13:24:55+01:00 go version go1.15.4 linux/amd64
Daemon: 1.9.0 dcda3fd98 2020-11-10T13:24:55+01:00 go version go1.15.4 linux/amd64

- Kernel version (run `uname -a`)
Linux master1 5.4.0-53-generic

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
kubernetes v1.18.12

- Link to relevant artifacts (policies, deployments scripts, ...)
https://docs.cilium.io/en/v1.9/gettingstarted/kube-router/

**How to reproduce the issue**

Follow https://docs.cilium.io/en/v1.9/gettingstarted/kube-router/ using `ipam: cluster-pool` (default)

**Comment by joestringer** [comment]
Thanks for the report. I think that this makes sense since in the `cluster-pool` mode, Cilium is responsible for delegating CIDRs to nodes and I don't think that these are made known to the standard k8s resources. Then presumably kube-router would pull the pod CIDRs directly from k8s.

As a workaround, it should still work if you configure `ipam: kubernetes`. Perhaps we should extend the kube-router guide to make this restriction more clear.

I'm also open to hearing ideas on how we might improve this interaction, I haven't yet considered whether there is something that Cilium could do differently when operating in cluster-pool mode that would allow this to work (could it push the podCIDRs into the k8s resources for instance?)

**Comment by manuelbuil** [comment]
> Thanks for the report. I think that this makes sense since in the `cluster-pool` mode, Cilium is responsible for delegating CIDRs to nodes and I don't think that these are made known to the standard k8s resources. Then presumably kube-router would pull the pod CIDRs directly from k8s.
> 
> As a workaround, it should still work if you configure `ipam: kubernetes`. Perhaps we should extend the kube-router guide to make this restriction more clear.
> 
> I'm also open to hearing ideas on how we might improve this interaction, I haven't yet considered whether there is something that Cilium could do differently when operating in cluster-pool mode that would allow this to work (could it push the podCIDRs into the k8s resources for instance?)

You are right, I don't think Cilium could do anything to improve this. Therefore, I'd say that the bug is just in the documentation where we should state this limitation. I'll prepare a small PR
