### ISSUE TITLE
Package Kubernetes / associated dependencies into VMs to reduce build times

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#1418]
A lot of time is spent in the Jenkins jobs just to install Kubernetes and its associated dependencies. Create a new base VM with these dependencies packaged in for use in the Jenkins jobs to reduce the build time.

**Comment by eloycoto** [comment]
I think that the problem is that the all k8s servers are going to install kubernetes, compile cilium etc.. I suggest to build an image with packer and after that, import it using vagrant and run only the test. 

In this case, you only build one time, so you save time and resources. 

Regards

Next week I can help you with this ;-)

**Comment by ianvernon** [comment]
@eloycoto yes, that is the intention of this ticket :D

**Comment by ianvernon** [comment]
This is being taken care of as part of #1733 for the build. Thus, I am closing this.
