### ISSUE TITLE
Evaluate cilium-agent map usage

### ISSUE THREAD

**Issue by fristonio** [cilium/cilium#14475]
The map implementation for Golang will grow the map to the size with maximum elements in the map and never reshrink it even if garbage collection is performed by the compiler. This can lead the map to grow and never get resized.
Evaluate if this can cause an issue in the Cilium agent. There are a bunch of places in Cilium where we keep local caches in maps(policy, ipcache, etc. for example).

Upstream issue: https://github.com/golang/go/issues/20135

**Comment by ti-mo** [comment]
Interesting, but this sort of makes sense. It's not clear what can be done about this without improving this in Go itself. Maps are such a fundamental data structure that this is a limitation we'll need to accept. If we identify problems with particular maps (through profiling), we could implement bespoke data structures for those, but I'm not sure whether this kind of wide investigation would turn up anything actionable.

I'll close this for now, we can revisit if this turns out to be a problem in the future.
