### ISSUE TITLE
EKS NodePort to local node with kube-proxy is broken 

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#14728]
When running in native ENI mode, NodePort on the local node is broken:

```
---------------------------------------------------------------------------------------------------------------------
🔌 [pod-to-service] Testing cilium-test/client-6c46bff775-9hw7v -> 192.168.58.215:32350 (NodePort)...
---------------------------------------------------------------------------------------------------------------------
❌ curl connectivity check command failed: error in stream: command terminated with exit code 28
❌ [pod-to-service] cilium-test/client-6c46bff775-9hw7v (192.168.132.242) -> 192.168.58.215:32350 (NodePort) (192.168.58.215:32350)
```

**Comment by aditighag** [comment]
@tgraf I presume this is on the master branch?

**Comment by tgraf** [comment]
I've reproduced the above with 1.9.2

Reproduction steps:
```
eksctl create cluster --name test-cluster-1 --without-nodegroup
cilium install --wait=false --cluster-name test-cluster-1
eksctl create nodegroup --cluster test-cluster-1 --nodes 2
cilium status --wait
cilium connectivity test --test pod-to-service
```

**Comment by aditighag** [comment]
I haven't been able to get an EKS cluster yet. :( 

3rd attempt - 
>[ℹ]  waiting for at least 2 node(s) to become ready in "ng-6941ff93"
Error: timed out (after 25m0s) waiting for at least 2 nodes to join the cluster and become ready in "ng-6941ff93"

**Comment by AnishShah** [comment]
Is this with or without kube-proxy?

**Comment by AnishShah** [comment]
I'm facing similar issue with NodePort on GKE with Cilium 1.8.2. #14765

**Comment by brb** [comment]
To verify whether it's the same issue, you need to check whether there exist ifaces with k8s ExternalIP and InternalIP.

**Comment by aditighag** [comment]
> Is this with or without kube-proxy?

Looks like without kube-proxy. I followed the [steps](https://github.com/cilium/cilium/issues/14728#issuecomment-767385335), but I wasn't able to reproduce the issue. The default kernel version on EKS cluster is 4.14, and since kube-proxy-replacement is set to probe mode by default, nodeport is disabled. 

@AnishShah If you are able to confirm if it's the same issue as #14765, I'll reassign the bug to you since you are already working on a fix. Let us know if you need any help. 

./cilium connectivity test --test pod-to-service
:

---------------------------------------------------------------------------------------------------------------------
🔌 [pod-to-service] Testing cilium-test/client-98ff44fc7-mplhk -> 192.168.35.237:31792 (NodePort)...
---------------------------------------------------------------------------------------------------------------------
✅ [pod-to-service] cilium-test/client-98ff44fc7-mplhk (192.168.40.204) -> 192.168.35.237:31792 (NodePort) (192.168.35.237:31792)

---------------------------------------------------------------------------------------------------------------------
🔌 [pod-to-service] Testing cilium-test/client-98ff44fc7-mplhk -> echo-other-node:8080 (ClusterIP)...
---------------------------------------------------------------------------------------------------------------------
✅ [pod-to-service] cilium-test/client-98ff44fc7-mplhk (192.168.40.204) -> echo-other-node:8080 (ClusterIP) (echo-other-node:8080)

---------------------------------------------------------------------------------------------------------------------
🔌 [pod-to-service] Testing cilium-test/client-98ff44fc7-mplhk -> 192.168.89.249:31792 (NodePort)...
---------------------------------------------------------------------------------------------------------------------
✅ [pod-to-service] cilium-test/client-98ff44fc7-mplhk (192.168.40.204) -> 192.168.89.249:31792 (NodePort) (192.168.89.249:31792)

---------------------------------------------------------------------------------------------------------------------
🔌 [pod-to-service] Testing cilium-test/client-98ff44fc7-mplhk -> 192.168.35.237:31924 (NodePort)...
---------------------------------------------------------------------------------------------------------------------
✅ [pod-to-service] cilium-test/client-98ff44fc7-mplhk (192.168.40.204) -> 192.168.35.237:31924 (NodePort) (192.168.35.237:31924)

---------------------------------------------------------------------------------------------------------------------
🔌 [pod-to-service] Testing cilium-test/client-98ff44fc7-mplhk -> 192.168.89.249:31924 (NodePort)...
---------------------------------------------------------------------------------------------------------------------
✅ [pod-to-service] cilium-test/client-98ff44fc7-mplhk (192.168.40.204) -> 192.168.89.249:31924 (NodePort) (192.168.89.249:31924)

---------------------------------------------------------------------------------------------------------------------
🔌 [pod-to-service] Testing cilium-test/client-98ff44fc7-mplhk -> echo-same-node:8080 (ClusterIP)...
---------------------------------------------------------------------------------------------------------------------
✅ [pod-to-service] cilium-test/client-98ff44fc7-mplhk (192.168.40.204) -> echo-same-node:8080 (ClusterIP) (echo-same-node:8080)

---------------------------------------------------------------------------------------------------------------------
📋 Test Report
---------------------------------------------------------------------------------------------------------------------
✅ 6/6 tests sucessful (0 warnings)

**Comment by aditighag** [comment]
Looks like @AnishShah already confirmed the issue on EKS - https://github.com/cilium/cilium/issues/14765#issuecomment-768843452.
I'll close this issue as we are already tracking the fix via #14765.

**Comment by aditighag** [comment]
I was able to reproduce the issue.

**Comment by kovalyukm** [comment]
Hello,

We faced with this big issue on our updated EKS clusters:
Kubernetes version 1.19
Amazon VPC CNI plug-in 1.7.9
KubeProxy 1.19.6
KERNEL-VERSION 5.4.91-41.139.amzn2.x86_64
and Cilium 1.9.4 (the same and similar issues for other 1.9 versions).

After updating components above, NodePorts of Services stopped working with connection timed out, so clients gets ERR_CONNECTION_TIMED_OUT when connecting via LoadBanancers (that use NodePort on INTERNAL-IP of nodes).

Kubernetes Services works inside cluster and NodePorts are accessible from other workers.

There are no suspicious errors in logs.
Cilium works in chainingMode, policyAuditMode does not help.
```yaml
    policyAuditMode: true
    cni:
      chainingMode: aws-cni
    masquerade: false
    tunnel: disabled
    nodeinit:
      enabled: true
```

Uninstalling Cilium does not fix the issue and NodePorts do not start work, additionally there is needed replacing of nodes.

Please, tell what is the state of the issue, are there some workarounds?
Thanks!

**Comment by kovalyukm** [comment]
Clients get responses like
"curl: (56) Recv failure: Operation timed out"
but we can see some traffic on the node with tcpdump port <NodePort> similar to legitimate traffic with Flags [S] [S.] [.] [P.] [F.] with client IP.

**Comment by dctrwatson** [comment]
Not sure if it's related, but with `kube-proxy-replacement=probe` seeing new connection issues with NLBs; they just hang for 90-120s periodically.

Kubernetes: `v1.17.11`
Kernel: `5.4.0-1035-aws`

If I set `kube-proxy-replacement=disabled`, I no longer have connection establishment issues from NLB->service for at least a few thousand new connections.

I changed it back to `probe` and then saw new connections start to hang after ~400 connections. Seems like the `cilium-agent` restart made it more reliable, but not 100% like `kube-proxy-replacement=disabled`.

Enabling DSR outright breaks NLBs though.

The `kube-proxy` daemonset is still running though...

**Comment by brb** [comment]
@dctrwatson Can you provide a sysdump?

**Comment by borkmann** [comment]
> Enabling DSR outright breaks NLBs though.

This is on AWS, right? Last time we checked, DSR was not supported there as we use custom IP options for the current DSR implementation in case of kube-proxy-replacement which the underlying network on AWS is dropping.

**Comment by dctrwatson** [comment]
> This is on AWS, right? Last time we checked, DSR was not supported there as we use custom IP options for the current DSR implementation in case of kube-proxy-replacement which the underlying network on AWS is dropping.

Ah, got it.

> @dctrwatson Can you provide a sysdump?

From a node running the pod? or the node the NLB routes the hung connection to?

**Comment by brb** [comment]
> From a node running the pod? or the node the NLB routes the hung connection to?

From both.

**Comment by dctrwatson** [comment]
I had to make other changes before I could get around to taking a sysdump...

Either upgrading to v1.9.6, disabling `masquerade`, and/or reducing number of nodes has made my issue go away... sorry.

**Comment by pchaigno** [comment]
> Last time we checked, DSR was not supported there as we use custom IP options for the current DSR implementation in case of kube-proxy-replacement which the underlying network on AWS is dropping.

@borkmann Should we fatal in that config. then?

**Comment by brb** [comment]
> Should we fatal in that config. then?

Hmm, I was able to run the DSR on AWS (e.g., https://github.com/brb/cilium-without-netfilter).
