### ISSUE TITLE
Policy deny during deployment

### ISSUE THREAD

**Issue by Joerg-Tech** [cilium/cilium#14748]
## Bug report

**General Information**

- Cilium version 1.9.1
- Kernel version 5.4.0-1036-azure
- AKS manged Kubernetes 1.18.10 

**Description of the issue**

We are running a django based web application, that uses pgbouncer as a connection pooler. 
Policies are configured, that django pod and pgbouncer pod can communicate with each other. There is also a CLUSTER_IP service for pgbouncer, that the django pods are using.
Normally this is working fine.

But often during a new deployment (with helm) a new migration pod is created, that needs to connect to the db via the pgbouncer pod.
As soon as the new pod is created, all django pods loose their connectivity to pgbouncer. Cilium even reports this as a "Policy denied". The created django-migration container is also blocked.
This issue then persists until the pgbouncer pod is restarted.
I experimented a lot with different policies (via service or pod or both), but it didn't change the issue.

I've created a cilium sysdump as the issue was present (before restarting the pgbouncer pod).
[cilium-sysdump-20210125-214535.zip](https://github.com/cilium/cilium/files/5879990/cilium-sysdump-20210125-214535.zip)

In this example the pod 
django-864b48d544-cwvqm                        1/1     Running             0          4d2h   10.240.0.22
was running fine and then after the new pod `django-migrations-f9wp6` spawned:
`xx drop (Policy denied) flow 0x2882ce37 to endpoint 0, identity 4930->2: 10.240.0.22:56564 -> 10.0.215.106:5432 tcp SYN`

Maybe someone can give more insight, what might be wrong here?

**Comment by pchaigno** [comment]
The packets are dropped because we enforce policies on the VIP (10.0.215.106) instead of the backend's IP. It indicates the DNAT at the socket level (kube-proxy replacement is enabled) didn't happen. It didn't happen because Cilium doesn't know of any backend to 10.0.215.106:
```
$ git grep -A1 10.0.215.106 bugtool-cilium-g7xhs-20210125-214545/cmd/cilium-bpf-lb-list.md
bugtool-cilium-g7xhs-20210125-214545/cmd/cilium-bpf-lb-list.md:10.0.215.106:5432    0.0.0.0:0 (29) [ClusterIP]                
bugtool-cilium-g7xhs-20210125-214545/cmd/cilium-bpf-lb-list.md-10.0.131.235:25227   0.0.0.0:0 (17) [ClusterIP]
```

@Joerg-Tech Could you try disabling the kube-proxy replacement (`kube-proxy-replacement: disabled`) to let kube-proxy handle the DNAT? iptables seems to have the proper DNAT rules, so I think that will workaround the issue.

/cc @brb

**Comment by Joerg-Tech** [comment]
Thanks a lot for your reply.
I'll try to disable `kube-proxy-replacemen` before the next deployment.

**Comment by joestringer** [comment]
Related: #13329

**Comment by Joerg-Tech** [comment]
I've tested it with `kube-proxy-replacement: disabled`, but this doesn't help. 

The only workaround seems to be to allow the service additionally to the pod.

**Comment by pchaigno** [comment]
> I've tested it with `kube-proxy-replacement: disabled`, but this doesn't help.

That's actually expected. I forgot that, with the kube-proxy replacement disabled, we will do the DNAT translation in the BPF program at lxc using the same map as before. The real issue here is that the service backends are missing the BPF map.

In the logs, I'm seeing some errors due to a transient connectivity issue. Could that be related or did it only happen this once?

Do you know at what time you started seeing the policy drops?

**Comment by Joerg-Tech** [comment]
> In the logs, I'm seeing some errors due to a transient connectivity issue. Could that be related or did it only happen this once?

I doubt it. I could reproduce this issue on our freshyl setup development cluster as well and I didnt find any errors there. 

> Do you know at what time you started seeing the policy drops?

It always starts , when the the migration pod is starting (after Phase 'ContainerCreating' is finished).

**Comment by pchaigno** [comment]
Do you still see this issue with latest v1.9 or with v1.10.1?

Also, is there anything special about the "migration pod"? What is it doing?

**Comment by Joerg-Tech** [comment]
The issue is still there with 1.9, but I havn't tested it with 1.10 yet.

The only unusual things of the "migration pod" might be, that it's started on demand (with a kubernetes job) and is running rather short (1 - 5mins).
