### ISSUE TITLE
 cni-uninstall.sh now removes the config even if it is managed externally

### ISSUE THREAD

**Issue by mvisonneau** [cilium/cilium#14838]
## Bug report

Following this change: https://github.com/cilium/cilium/commit/fa8554cc4d18a7c5fd3bfd61635ada51bbf97801#diff-c4bdadd87da9bff82b8355eb6656d5c750c10bb6e7b2956de2a3705ce3ba4d56R82-R94

We now remove unconditionally the config files present within the cni conf dir (/etc/cni/net.d). In my case I include this configuration as part of the cloud-init of my instances. It now leads on failure when the cilium pod restarts as the configuration gets deleted.

I assume that we should keep the possibility to let cilium manage the cni plugins without interfering with the config files? 🤔 

**General Information**

- Cilium version: `master` / `>= fa8554cc` 

**How to reproduce the issue**

1. Manage `/etc/cni/net.d/05-cilium.conf` outside of Cilium
2. Restart the Cilium pod

**Comment by mvisonneau** [comment]
As a workaround and maybe best practice, I renamed the file created with my cloudinit to `/etc/cni/net.d/05-cilium.conf.cloudinit` and reconfigured cilium with `--read-cni-conf='/host/etc/cni/net.d/05-cilium.conf.cloudinit'"`

**Comment by ti-mo** [comment]
Hi @mvisonneau, thanks for the report, that's an interesting workaround! This read/write feature is primarily used to read a CNI config from a file mounted from a configmap, but I guess it can be used to designate a single source of truth as well.

> let cilium manage the cni plugins without interfering with the config files

Heh, unfortunately, managing CNI plugins is done by installing config files on the host. Right now, CNI handling is strewn across a few shell scripts as well as the Go code that acts on `{read,write}-cni-conf...`, and we're trying to make this more coherent for 1.10. The config removal during agent shutdown is done because there is no clear difference between a stop and an uninstall. 

Could you elaborate on the environment you're running? (aside from there being cloud-init) Are you using Helm to deploy Cilium? As another workaround, you could remove the `postStart` and `preStop` hooks from the agent pod, which will disable CNI (un)installation altogether. We should probably expose this as a setting in the chart, because this is a use case we did have in mind. (see CNI-Genie)

**Comment by mvisonneau** [comment]
👋 hey @ti-mo, no worries! 🙇 

Indeed, I am using the helm chart (v1.9.3) with a specific image: `ciilum/cilium-dev:fafdb55c7e68665769c9907cb1eb486df7c31e57` as I was looking into this fix (unrelated to this issue) https://github.com/cilium/cilium/pull/14828

Main goal here was to be able to try out a multi-arch (amd64/arm64) implementation, which seems to works like a charm now !

If I remove the `postStart`, am I correct to assume that `cilium-cni` and `loopback` plugins won't be installed though? 🤔

**Comment by ti-mo** [comment]
> I am using the helm chart (v1.9.3) with a specific image

If I'm not mistaken, this CNI deletion behaviour was not backported to 1.9.x, you should only see it on master. Caveat: we had an incident a few weeks ago where a master build was accidentally pushed as 1.9.2. (see https://github.com/cilium/cilium/releases/tag/v1.9.3) Make sure you're running the correct image while troubleshooting this.

> If I remove the postStart, am I correct to assume that cilium-cni and loopback plugins won't be installed though?

Ah, that's correct. You don't manually install the CNI binary, that makes sense. Thanks for clarifying your use case!
I've included your use case in https://github.com/cilium/cilium/issues/14892 (`Unmanaged/manual/custom CNI mode`), please confirm if this accurately describes your deployment, and feel free to provide any suggestions.

I'll work on a short-term fix for what's currently in master. We have an undocumented env `CILIUM_CUSTOM_CNI_CONF` that is used for skipping the installation bits of `cni-install.sh`, but is not honored in the uninstall counterpart. Will change this to also skip all deletions. (this is causing the same impact to our microk8s integration, where the CNI config comes prepared on the host image)

Will update here when this has been addressed.

**Comment by mvisonneau** [comment]
Absolutely, I have since switched back on `v1.9.4` which is not impacted as it is not backported 👌 

I personally feel that the use of `--read-cni-conf` and `--write-cni-conf-when-ready` flags combo make lots of sense and I am very pleased about this implementation. Documenting the potential breaking change with its workaround would indeed seem to be the most appropriate solution 🤷 !
