### ISSUE TITLE
Pod IP range announcements via BGP

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#15015]
Assuming we implement #14395, the next obvious step would be to provide a mechanism to advertise the pod IPs/range from the node across the network.

**Comment by christarazi** [comment]
Is this simply advertising the node's PodCIDR from the K8s resource? Do we want more control of which nodes should advertise? I'm thinking an MVP would be to have all nodes announce their PodCIDRs and later we can add some annotation / mechanism to give control, if needed.

**Comment by brb** [comment]
> Is this simply advertising the node's PodCIDR from the K8s resource?

Yes, each node announces its own podCIDR.

**Comment by joestringer** [comment]
:+1: This won't make sense for all IPAM modes as it requires unique prefixes for each node, worth considering which IPAM modes it wouldn't make sense for:

https://docs.cilium.io/en/latest/concepts/networking/ipam/

(This may end up overlapping closely with whether the BGP use case makes sense in general, ie it's more useful in on-prem environments rather than cloud environments where the vendor provides an opinionated network for you).

**Comment by hongfeioo** [comment]
For self-built data centers, it is very useful for each node to declare its own CIDR, because NODE can establish EBGP neighbors with TOR at any time. Currently, when NODE is initialized, it can be declared CIDR by manually modifying the bird configuration. Hopefully in the future cilium can automatically complete this action in conjunction with bird
