### ISSUE TITLE
make hubble-relay available in GKE Dataplane V2

### ISSUE THREAD

**Issue by ShotaKitazawa** [cilium/cilium#15035]
## Proposal / RFE

I want to use hubble-relay & hubble-ui in GKE Dataplane V2.
Now, GKE Dataplane V2's default cilium config is specified `enable-hubble=true` option, but not specified `hubble-listen-address=":4244"` option. 
For this reason, hubble-relay outputs logs as below, because hubble-relay does not listen `tcp:0.0.0.0:4244`, but only listens  `unix://var/run/cilium/hubble.sock`.

```
level=warning msg="Failed to create gRPC client connection to peer gke-XXX; next attempt after 1h30m0s" address="${NODE_ADDR}:4244" error="connection error: desc = \"transport: error while dialing: dial tcp ${NODE_ADDR}:4244: connect: connection refused\"" subsys=hubble-relay
```

And, cannot get ServerStatus

```
$ kubectl port-forward hubble-relay-xxx 4245:4245 &

$ grpcurl -plaintext localhost:4245 observer.Observer.ServerStatus
{
  "numConnectedNodes": 0,
  "numUnavailableNodes": 3,
  "unavailableNodes": [
    "gke-XXX",
    "gke-XXX",
    "gke-XXX"
  ]
}
```

I understand that hubble-relay can connect to Peer service in UNIX-domain-socket and not connect to Observer service in TCP-socket.
(ref. https://docs.cilium.io/en/v1.9/hubble/)

**Describe the solution you'd like**

for example, implement new options in hubble-relay : `--disable-peering` and `--observer-service`

* `--disable-peering` : do not connect hubble-relay to Peer service
* `--observer-service` : specify Observer service to connect, specify `--disable-peering` option together

If this option has implemented, can use hubble-relay & hubble-ui in GKE Dataplane V2 in below ways.

* Deploy `hubble-relay-intermediate` (hubble-relay process) DaemonSet with `--disable-peering --observer-service=unix://var/run/cilium/hubble.sock` options and `hubble-relay-intermediate` Service listened `:4245`
* Deploy `hubble-relay` Deployment with `--peer-service=hubble-relay-intermediate` option
* Deploy `hubble-ui` Deployment

**Comment by ShotaKitazawa** [comment]
I have forgot below.

* Peer service is not implemented in hubble-relay, Thus `hubble-relay` Deployment cannot connect `hubble-relay-intermediate`
    * with this, I think that cannot available multi hubble-relay now. Is this correct?

**Comment by joestringer** [comment]
Hi @ShotaKitazawa , I don't fully understand the proposals but it seems like the base problem is that GKE dataplane v2 is not providing a fully functional Hubble Relay service. If that's the core issue then I think the best way to move forward is to report this through Google support channels and provide the feedback to the product managers there so that Cilium is configured correctly to allow Hubble to work as expected in that environment. While it's technically plausible to extend Cilium to facilitate working around Google's product implementation, I don't think it's really in the interests of the Cilium project itself to add additional code or alternative architectures just to work around such issues in that environment.

I've reached out to a contact at Google to point to this issue, but I suggest that you also follow up through your own support channels with Google to help register demand for this functionality.

**Comment by ShotaKitazawa** [comment]
Thank you for your reply.

> I suggest that you also follow up through your own support channels with Google to help register demand for this functionality.

I do so, thanks.

**Comment by dariush-a** [comment]
@joestringer Is this issue still open?
