### ISSUE TITLE
GKE Installation fails Connectivity Check

### ISSUE THREAD

**Issue by therealmitchconnors** [cilium/cilium#15098]
## Bug report

**General Information**

- attempting to follow https://docs.cilium.io/en/stable/gettingstarted/k8s-install-gke/
- GKE version 1.19.7-gke.1302

**How to reproduce the issue**

1. follow helm install instructions in linked doc
2. follow cilium test instructions
3. cilium test pods not ready
4. cilium test pods have no log output, but are in crashloop

```
NAME                                                    READY   STATUS             RESTARTS   AGE
echo-a-dc9bcfd8f-c5rx6                                  1/1     Running            0          14m
echo-b-5884b7dc69-ggn8g                                 1/1     Running            0          14m
echo-b-host-cfdd57978-g55m2                             0/1     CrashLoopBackOff   7          14m
host-to-b-multi-node-clusterip-c4ff7ff64-sxnbx          1/1     Running            0          14m
host-to-b-multi-node-headless-84d8f6f4c4-jwrzc          1/1     Running            0          14m
pod-to-a-5cdfd4754d-d74x8                               1/1     Running            0          14m
pod-to-a-allowed-cnp-7d7c8f9f9b-clbm2                   1/1     Running            0          14m
pod-to-a-denied-cnp-75cb89dfd-fdjzw                     1/1     Running            0          14m
pod-to-b-intra-node-nodeport-99b499f7d-g5d2w            0/1     CrashLoopBackOff   7          14m
pod-to-b-multi-node-clusterip-cd4d764b6-n5qpp           1/1     Running            0          14m
pod-to-b-multi-node-headless-6696c5f8cd-68nsc           1/1     Running            0          14m
pod-to-b-multi-node-nodeport-7ff5595558-h8bwr           0/1     CrashLoopBackOff   7          14m
pod-to-external-1111-d5c7bb4c4-rq8km                    1/1     Running            0          14m
pod-to-external-fqdn-allow-google-cnp-f48574954-n6nbj   1/1     Running            0          14m
```

**Comment by therealmitchconnors** [comment]
In hindsight, I ran these instructions against a pre-existing empty cluster.  When I use the exact cluster creation steps listed in the docs, the tests succeed.  I'm not sure what the difference between the clusters is, other than that the original is using routes-based networking, so maybe that causes problems?  

Either way, it seems like the tests should output some sort of error message when they fail...

**Comment by kkourt** [comment]
Hi,

Thanks for trying out Cilium and the bug report.

> other than that the original is using routes-based networking, so maybe that causes problems?

GKE mode for Cilium will always use the VPC routes, so the expectation is that this should not cause issues.

First, can you confirm that the `$NATIVE_CIDR` environment variable was properly set when you tried this?
If `$NATIVE_CIDR` is not the issue, can you provide a [sysdump](https://docs.cilium.io/en/v1.9/operations/troubleshooting/#automatic-log-state-collection)? This should help identify what the issue is.


You also mention:
> Either way, it seems like the tests should output some sort of error message when they fail...

Indeed. There is new CLI that will provide much better error messages for these issues: https://github.com/cilium/cilium-cli. GKE is already supported, so it should be able to provide more informative error messages.
