### ISSUE TITLE
packet drop by DROP_UNROUTABLE when use the enable-bpf-tproxy=true

### ISSUE THREAD

**Issue by liqd1** [cilium/cilium#15105]
Hello, we are testing the feature of BPF-based proxy redirection。when we created a l7-policy，and access the nodeport service from the outside of cluster，we found the SYN,ACK packet which returned by cilium-envoy was dropped by cilium_host in section 'from-host' 。
![image](https://user-images.githubusercontent.com/79635099/109138143-030dca80-7795-11eb-8214-bd5b704f07d9.png)

Cilium version:
![image](https://user-images.githubusercontent.com/79635099/109136757-6dbe0680-7793-11eb-9bbc-03f247d44a3b.png)

Kernel version:
![image](https://user-images.githubusercontent.com/79635099/109136922-99d98780-7793-11eb-8504-fcb0b64b61e3.png)

Kubernetes:
v1.20.2

My cilium's config with helm:
![image](https://user-images.githubusercontent.com/79635099/109137784-95619e80-7794-11eb-9014-fea90ef63638.png)

My deployment and svc:
![image](https://user-images.githubusercontent.com/79635099/109137190-e4f39a80-7793-11eb-91b7-29363d25c860.png)

My l7 policy:
![image](https://user-images.githubusercontent.com/79635099/109137310-048ac300-7794-11eb-8572-8bea35eee8ef.png)

Client info:
![image](https://user-images.githubusercontent.com/79635099/109138520-6e579c80-7795-11eb-847e-d3fec926e211.png)

Drop info:
![image](https://user-images.githubusercontent.com/79635099/109138604-83343000-7795-11eb-9b78-1061217b78c4.png)

In my optinion，the SYN,ACK packet returned by cilium-envoy should into cilium_host，and pass through the section “from-host”. Then back to the stack and enter cilium_net's section "to-host", back to the stack again and enter the outer eth's section "to-netdev"。can someone give some help？

Any help/pointers would be appreciated!

**Comment by joestringer** [comment]
Given that the traffic at this point is from the proxy (ie from an application running on the host), I'm a bit surprised that the traffic ends up getting routed to a device with the BPF host program attached but maybe we just haven't fully considered  the integration between the BPF tproxy feature and some other feature like host firewall.

My understanding of the reason for that drop is that the code assumes that traffic will only arrive to this point if (and only if) the traffic is destined to a Cilium-managed pod. Based on this assumption, any traffic not destined to a local pod (or pod CIDR on remote node) should be dropped because the traffic shouldn't hit this code in the first place. Suggests that the stack routing configuration is not forwarding responses in the way that the BPF code is expecting.

Where is traffic to 172.16.x.y being routed to and which programs are attached there?
