### ISSUE TITLE
How to migrate from Flanel? Is kubeadm --pod-network-cidr=10.217.0.0/16 still needed?

### ISSUE THREAD

**Issue by acim** [cilium/cilium#15170]
Sorry for the questions, it is maybe not supposed to ask here but I searched for these information and didn't fine anything useful.

1. Is some previous instructions (I think on kubernetes.io), it was advised to use flag _--pod-network-cidr=10.217.0.0/16_ with kubeadm in order to install Cilium later. Is this still the case? 
2. I would like to migrate from Flanel to Cilium. At the moment, my cluster is initialized with _--pod-network-cidr=10.244.0.0/16_. Can I still use Cilium with this CIDR? I saw that Helm chart for Cilium has value _ipam.operator.clusterPoolIPv4PodCIDR_ set to _10.0.0.0/8_. Is it related to this at all? Shall I keep the default or set it to 10.244.0.0/16? In the [quick-install](https://raw.githubusercontent.com/cilium/cilium/v1.9/install/kubernetes/quick-install.yaml) manifest there is also _cluster-pool-ipv4-cidr: "10.0.0.0/8"_.
3. What do I have to take care when migrating? I don't mind if my cluster has a short stop of services. My plan is to install the chart first:

```sh
helm install cilium cilium/cilium --namespace kube-system \
  --set global.kubeProxyReplacement=strict \
  --set global.k8sServiceHost=x.y.z.u \
  --set global.k8sServicePort=6443
```
And then delete flannel. Is there something else to consider?
I found [this tool](https://github.com/jetstack/cni-migration), but it looks too complicated for my case.

**Comment by aanm** [comment]
If you cluster is provisioned with a pod cidr then you can use `--set ipam.mode=kubernetes` in helm. Otherwise the default values set up in the helm chart are sufficient. More info [here](https://docs.cilium.io/en/v1.9/concepts/networking/ipam/kubernetes/#configuration)

just a FYI, starting in Cilium >= 1.9.0, the `global` are not required. More info [here](https://docs.cilium.io/en/v1.9/operations/upgrade/#helm-options)
