### ISSUE TITLE
BPF based masquerading picks wrong IP when using IP address aliases

### ISSUE THREAD

**Issue by gottwald** [cilium/cilium#15332]
## Proposal

**Is your feature request related to a problem?**

**Describe the solution you'd like**

We've run into a setup where cilium is running on a node that has multiple IP addresses (primary and secondary).
For example:
```
eth0 192.168.1.12
eth0:1 10.10.1.12
```
If used in iptables masquerading mode `192.168.1.12` is used as masquerading IP.
If used in bpf masquerading mode `10.10.1.12` is used as masquerading IP.

AFAICS in the code the bpf IP discovery does a sort of IPs in order to make sure to have a stable IP (#7637 is referenced in the code comments for this) but this also means it uses the "lowest" IP regardless of which "order" they are set which is usually not what you want.

Using `--devices` in this scenario doesn't help either because from a netlink perspective `eth0` and `eth0:1` are one device.

I have a working local patch that would alter the sort in IP discovery to prefer primary IPs over secondary IPs in the sort order.
This would work for all setup that use the `:n` suffix on the interface name, because netlink provides this as label. Users that use multiple IP addresses on `eth0` w/o any suffix would still stay on the current sorting mechanism.

WDYT?

Attached a PR as possible solution to this.

**Comment by rahulait** [comment]
We are seeing a similar issue where BPF based masquerading starts failing if there are multiple IP addresses on primary interface. In our case, we have multiple ip's configured on eth0 using alias (eth0, eth0:15). IP address on eth0 is externally routable, but the ip-address on eth0:15 is not.

```
root@198.11.11.71:~# ip addr show eth0
4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 7200
    link/ether a0:42:3f:37:91:e2 brd ff:ff:ff:ff:ff:ff
    inet 198.11.11.71/27 brd 198.11.11.95 scope global eth0
       valid_lft forever preferred_lft forever
    inet 192.168.10.153/23 brd 192.168.11.255 scope global eth0:15
       valid_lft forever preferred_lft forever
root@198.11.11.71:~#

root@198.11.11.71:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         198.11.11.65   0.0.0.0         UG    0      0        0 eth0
192.168.10.0    0.0.0.0         255.255.254.0   U     0      0        0 eth0
198.11.11.64   0.0.0.0         255.255.255.224 U     0      0        0 eth0
root@198.11.11.71:~#
```

When I am installing k8s with cilium on the host, cilium is picking up ip address on eth0:15 which is non-routable and my external traffic is failing.
From inside Pod:
```
/ # ping 198.11.11.73
PING 198.11.11.73 (198.11.11.73): 56 data bytes
^C
--- 198.11.11.73 ping statistics ---
36 packets transmitted, 0 packets received, 100% packet loss
/ # ^C
```
On the host:
```
root@198.11.11.71:~# tcpdump -i eth0 icmp
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
17:24:09.005708 IP 192.168.10.153 > 198.11.11.73: ICMP echo request, id 44221, seq 46, length 64
17:24:10.005835 IP 192.168.10.153 > 198.11.11.73: ICMP echo request, id 44221, seq 47, length 64
17:24:11.005966 IP 192.168.10.153 > 198.11.11.73: ICMP echo request, id 44221, seq 48, length 64
```
Since its picking the incorrect ip address (192.168.10.153 instead of 198.11.11.71 on eth0), no response for the requests is coming back.

I tried using ```--devices``` flag to specify interface, but that didn't helped. If kubeProxyReplacement is disabled, or egressMasqueradeInterfaces flag is specified which makes BPF fall back to iptables-based masquerading, only then the traffic starts routing correctly.
