### ISSUE TITLE
CI: Cannot retrieve enp0s8 enp0s3 link

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#15609]
All tests failed at https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/138/ and https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.19/112/ with the following fatal:
```
2021-04-08T09:50:53.984405149Z level=info msg="BPF host routing is currently not supported with devices without L2 addr. Falling back to legacy host routing (enable-host-legacy-routing=true)." subsys=daemon
2021-04-08T09:50:53.984408243Z level=fatal msg="Cannot retrieve enp0s8 enp0s3 link" error="Link not found" subsys=daemon
```

Sysdumps:
[b06d786b_K8sServicesTest_Testing_test_script_Validating_test_script_correctness.zip](https://github.com/cilium/cilium/files/6279521/b06d786b_K8sServicesTest_Testing_test_script_Validating_test_script_correctness.zip)
[c6459936_K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies.zip](https://github.com/cilium/cilium/files/6279523/c6459936_K8sPolicyTest_Basic_Test_checks_all_kind_of_Kubernetes_policies.zip)

/cc @brb (looks like it may be related to the patch for devices without L2 address)

**Comment by brb** [comment]
`BPF host routing is currently not supported with devices without L2 addr` is a false positive (because devices couldn't be retrieved through netlink).

Unfortunately, no bugtool is included in any of the artifacts. It's hard to say why all of sudden cilium-agent couldn't retrieve devices via netlink. Important to note is that the devices are determined during runtime (by using netlink). I doubt that their names could have changed. Have we recently built a new VM net-next image?

**Comment by pchaigno** [comment]
> Have we recently built a new VM net-next image?

No, net-next image builds have been blocked for a while. The failure also happened on a 4.19 image.

I think I saw this happen at least once before but maybe I'm mistaken. Could be that it's a bug in the PR which triggered tests (i.e., https://github.com/cilium/cilium/pull/15558). Let's maybe revisit next steps if it happens again.

**Comment by brb** [comment]
@pchaigno Why it was closed? Have we figured out why it was failing?

**Comment by pchaigno** [comment]
@brb It's specific to https://github.com/cilium/cilium/pull/15558.
