### ISSUE TITLE
Cilium deployment by Helm

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#1564]
Helm (https://github.com/kubernetes/helm) is the closest you can get in k8s when it comes to package management. It's also increasing in popularity among cluster operators.

This issue consists of two parts:
- determining whether cilium can be deployed easily enough for helm chart to actually make sense
- wrap existing daemon set examples into a "canonical" deployment in form of a Helm chart, along with configuration (mostly agent options) options exposed as chart variables.

**Comment by j14s** [comment]
Bump, just as a matter of interest. We have a "helm" only pathway to k8s at my company, and I have several people in security and compliance asking about Cilium. It would be great to see working examples of setting Cilium configs via Helm/Charts.

**Comment by nebril** [comment]
@j14s it would be easy to package cilium DaemonSet into Helm chart, but cilium DaemonSet requires mounting bpf filesystem on k8s worker nodes (http://cilium.readthedocs.io/en/stable/install/?highlight=mount%20bpf#quick-guide). It cannot be done as part of a chart spec, so there would be an extra step involved.

**Comment by The-Loeki** [comment]
I've been working on https://gitlab.com/ors-it/oss/helm-cilium

**Comment by ianvernon** [comment]
This was completed as part of the release of `v1.6`: https://github.com/cilium/cilium/pull/8637

**Comment by bmcstdio** [comment]
Could the chart be added to https://github.com/helm/charts or served from somewhere so that one can use plain `helm install` to install it (rather than downloading and extracting the tarball, and running `helm template` and `kubectl apply`)?

**Comment by ianvernon** [comment]
@bmcstdio what would that mean for custom configuration of a given deployment of Cilium? We have extensive templating with our Helm configuration - I'm not sure how that would fit in by adding it to the `charts` repo. I am not saying it wouldn't work, but I don't have enough expertise in the area to be helpful.

**Comment by bmcstdio** [comment]
@ianvernon adding it to `helm/charts` basically means moving/copying/mirroring the `install/kubernetes/cilium` directory there, with the added benefit of a packaged version of that being served from somewhere (and hence `helm install cilium` working out of the box). Custom configuration would still be possible—it's actually the goal of this to enable that in an easier way, as we'd be eliminating the step that requires people to download a tarball from this repo, extract it and use `helm template` against that. As an alternative, we can probably use GitHub pages to serve the packaged version of the chart.

**Comment by aanm** [comment]
@bmcstdio to sync with our release process, can you clarify the following?

- How long it would take to have `install/kubernetes/cilium` updated such as `helm install cilium` would be available once we release a new Cilium version?

- How feasible it is to specify a version with helm install?

Thanks!

**Comment by carrodher** [comment]
Hi, sorry for the delay I usually use an internal tool to manage GitHub notifications with some filters to only show those related to Bitnami repositories (or Helm charts), that is why I missed this one. Sorry.

As far as I know, the stable repository is not accepting new charts anymore, instead of that, the maintainers suggest you create your repository and it to the [Helm Hub](https://hub.helm.sh/charts), in fact, the following note appears when you try to create a PR in the [Helm Charts repository](https://github.com/helm/charts):

> NOTE: We're experiencing a high volume of PRs to this repo and reviews will be delayed. Please host your own chart repository and submit your repository to the Helm Hub instead of this repo to make them discoverable to the community. [Here](https://github.com/helm/hub/blob/master/Repositories.md) is how to submit new chart repositories to the Helm Hub.

That means that the users will need to add the repository and then install the chart:
```
helm repo add cilium-repository https://example.com
helm install cilium-repository/cilium [--version X.Y.Z]
```

As at this time there is not a centralized repository (well, `stable` is still alive right now, but the idea is to move everything to distributed repositories), the lifecycle is controlled by the developers end-to-end.
I mean, if a new version of Cilium is released, you should update the chart as part of this release process. Update the chart means:
- Change the `version` and `appVersion` in the _Chart.yaml_
- Modify the _values.yaml_ (or whatever you set the container image) to use the new tag for the images
- Pack and push the chart with those changes to your repository

Now the first two items are the same, but the third one is not on the developers' side. We sent a PR to the Helm chart repository and there are some owners/maintainers that review/accept the PR and there are some CI/CD integrations that execute some tests, pack and push the new chart.

**Comment by joestringer** [comment]
I think the only part we have left on this item is to automate the helm artifact generation to push the charts to https://github.com/cilium/charts when we push a github tag to this repository. That's almost done already.
