### ISSUE TITLE
Give better UX to log message "Disabling HostServicesPeer feature." error="invalid argument"

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#15727]
This is a warning message as seen in the sysdump from https://github.com/cilium/cilium/issues/15719. The error is not clear enough for the user and it is currently being printed as a warning.

Pinging @pchaigno and @christarazi as approvals of the PR that introduced the change https://github.com/cilium/cilium/pull/15460

**Comment by pchaigno** [comment]
Do we even need to log a message when disabling it given it's not a user-provided option?

**Comment by christarazi** [comment]
Initially https://github.com/cilium/cilium/issues/15448 was opened so that we print out the error. Since the error is coming directly from the kernel, it's going to be fairly generic like "invalid argument". What was the motivation behind https://github.com/cilium/cilium/issues/15448 anyway? What specifically do we care about when `TestDummyProg()` fails, i.e. what errno is relevant?
