### ISSUE TITLE
Support internalTrafficPolicy for services

### ISSUE THREAD

**Issue by aditighag** [cilium/cilium#16071]
[InternalTrafficPolicy](https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/) field was added an Alpha feature in Kubernetes v1.21. This overlaps with the [serviceMatcher Local Redirect Policy](https://docs.cilium.io/en/v1.9/gettingstarted/local-redirect-policy/#servicematcher) feature that Cilium offers. This issue is created to support the feature, and merge the control plane API for the functionality on kubernetes versions > v1.21.

**Comment by aditighag** [comment]
🤦‍♀️ lol, I lost track of the releases. @aanm Yes, we could plan this for 1.11.

**Comment by ghughes** [comment]
LRP fails open, so you can't use it to _guarantee_ traffic is directed to node-local endpoints; `internalTrafficPolicy: Local` provides that guarantee.

This is significant, because if you create an LRP and client pods at approximately the same time, there's a good chance the LRP will not be in force on every node before the pods come up and begin establishing outbound connections.

**Comment by maximumG** [comment]
We are also interested in the implementation that was done on 1.12 & 1.13. Is it plan to backport this on 1.10 & 1.11 cilium version as well ? :pray:

**Comment by pchaigno** [comment]
@maximumG There are no such plan at the moment. internalTrafficPolicy will only be supported in v1.13+.
