### ISSUE TITLE
ClusterMesh: no use etcd

### ISSUE THREAD

**Issue by sstoner** [cilium/cilium#16299]
## Summary

we should permit `--kvstore` to be empty when using ClusterMesh in multiple clusters and Cilium-CLI should not create etcd cluster again. 

## Motivation

It may be easier for users to generate kubeConfig than to provide a suite of ETCD certificates and maintain an extra ETCD cluster.

### Goals

- kvstore-free on clusterMesh

### NonGoals

- improve performance of Kubernetes' apiserver
- misconfiguration for remote clusters

### Design Overview

![ 'clustermesh-free-kvstore.png'](https://raw.githubusercontent.com/sstoner/cilium/pr/vncl/rename-informer/Documentation/clustermesh-free-kvstore.png)

#### Alpha workflow

1.  Cilium agent `Daemon` creates a `ClusterMesh` instance with `IPCache` and `CachingIdentityAllocator` that are initialized by `Daemon` itself.
2. ClusterMesh initializes `globalServiceCache` and gets `ServiceCache` from `Daemon`
2. ClusterMesh will add/remove cluster in `clusterLifecycle`.
3. Once a cluster is founded by ClusterMesh, `controllerManager` will start controllers to list/watch remote Cluster's apiserver for `CiliumNode` `CiliumEndpoint` and update `IPCache` locally.
4. `ControllerManager` will also start a controller to list/watch remoteCluster's apiserver for `ClusterService`, it will update `ClusterService` and merge `ServiceCache`
5. `ControllerManager` will start a controller to list/watch remote Cluster's apiserver for`CiliumIdentity` and update remote cluster's caches in `remoteCaches` of `Allocator`

##### Modified

```
// RemoteIdentityWatcher is any type which provides identities that have been
// allocated on a remote cluster.
type RemoteIdentityWatcher interface {
   // WatchRemoteIdentities starts watching for identities in another kvstore and
   // syncs all identities to the local identity cache.
-     WatchRemoteIdentities(backend kvstore.BackendOperations) (*allocator.RemoteCache, error)
+    WatchRemoteIdentities(remoteAlloc *allocator.Allocator) (*allocator.RemoteCache, error)
   // Close stops the watcher.
   Close()
}
```

##### Added

```
// compatible with KvStore
type RemoteShareStore interface {
    NumEntries() int
    Close(ctx context.Context)
    UpdateLocalKeySync(ctx context.Context, key store.LocalKey) error
}
// compatible with KvStore
type RemoteIPIdentityWatcher interface {
    Watch(ctx context.Context)
    Close()
}

// TODO 
//      more details
```

### TestPlan 

Following tests will be covered or considered: 

* **Unit Tests:** All core changes must be covered by unit tests.
* **Integration Tests:**
  * `--kvstore` can be an empty string as an option when using ClusterMesh and Cilium-CLI should not create etcd cluster again 
  * different clusters can establish connections with each other
  * local-balancing with global services 
  * security policies 
* **Benchmark Tests**

#### Alpha 

- [ ] Implementation of the new feature in the cilium agent
- [ ]  Test cases mentioned in the TestPlan

#### Alpha -> Beta Graduation

  - **New aggregation layer in the cilium operator, it keeps Kubernetes' controllers and provides API interfaces that will be used for merging IPCache or ServiceCache by local cilium-agent**

#### Beta -> GA Graduation

  - Conformance tests are agreed on and implemented

### Risks and Mitigations

TODO

## Implementation History

[WIP]()

## Reference

1. [Cilium Project](https://github.com/cilium/cilium)
2. [Results of measuring of API performance of Kubernetes](https://docs.openstack.org/developer/performance-docs/test_results/container_cluster_systems/kubernetes/API_testing/index.html)

**Is your feature request related to a problem?**

#15774 

**Describe the solution you'd like**

I wish to implement this proposal. Does anyone have any recommendations or advice to fulfill more details of this proposal?

**Comment by jrajahalme** [comment]
@sstoner New guides in Cilium 1.10 already set up ClusterMesh without kvstore via the new cilium-cli tool, please have a look: https://docs.cilium.io/en/v1.10/gettingstarted/clustermesh/clustermesh/

**Comment by sstoner** [comment]
> @sstoner New guides in Cilium 1.10 already set up ClusterMesh without kvstore via the new cilium-cli tool, please have a look: https://docs.cilium.io/en/v1.10/gettingstarted/clustermesh/clustermesh/

clustermesh-apiserver depends on etcd cluster so that cilium started with kvstore=“” is meaningless. And this proposal wants to remove etcd from cilium and clustermesh-apiserver in a true sense.

**Comment by aanm** [comment]
@sstoner can you present this proposal in the weekly development meeting? It will happen in exactly 12 hours from now. Feel free to ask how to access the meeting in the #development channel in Cilium slack.

**Comment by jrajahalme** [comment]
> clustermesh-apiserver depends on etcd cluster so that cilium started with kvstore=“” is meaningless. And this proposal wants to remove etcd from cilium and clustermesh-apiserver in a true sense.

As @joestringer [answered your question in the linked issue](https://github.com/cilium/cilium/issues/15774#issuecomment-837061657), there are architectural reasons for separating the control planes of different clusters from each other, one of which is k8s apiserver scalability, which can't be ignored. Other consideration is the fact that we already have most of the needed control-plane interfaces using etcd that we already need to maintain, so reusing them was a sound architectural choice.

The design diagram shown in this issue description leaves important detail to be filled in in order to consider this proposal. For example, what do the blue boxes labeled as "cluster1" and "cluster2" represent? Red boxes seem to represent modules internal to Cilium agents. For example for the "watch remote identities" function, what entity is initiating it in cluster 1, and what entity in cluster 2 is responding to it? Are you proposing that Cilium agents connect to remote cluster's apiservers directly?

**Comment by answer1991** [comment]
> Are you proposing that Cilium agents connect to remote cluster's apiservers directly?

Yes. 

In the design philosophy of Kubernetes, there is only one apiserver that is kube-apiserver in the "world" of Kubernetes. That's why all components connect to kube-apiserver to get the data which generated from aggr-apiserver, but not connect to aggr-apiserver directly. "Only one apiserver" keeps Kubernetes architecture simple and reliable, and ensure the data that component get is consistency. 

For now, We are worried that the current ClusterMesh architecture will cause data inconsistency and we need more effort to maintain the aggr-apiserver and etcd stability.

For nodes < 5k of all clusters, agent connect to remote cluster's apiservers directly are more reasonable.

For nodes > 5k of all clusters, ClusterMesh aggr-apiserver will be considered. But it should be stateless and data should NOT be saved in the etcd. ClusterMesh aggr-apiserver provide list/watch API for agent, and the merged multi-cluster data keeps in its memory which is get from the remote clusters' apiserver.

Above all, we recommend ClusterMesh module could be more common, which could be run in cilium-agent and aggr-apiserver. And cilium-agent hold an abstract Interface that could get merged multi-cluster data, which implement could be local ClusterMesh instance running in cilium-agent, or a list/watch client get data from ClusterMesh aggr-apiserver.

**Comment by sstoner** [comment]
> > clustermesh-apiserver depends on etcd cluster so that cilium started with kvstore=“” is meaningless. And this proposal wants to remove etcd from cilium and clustermesh-apiserver in a true sense.
> 
> As @joestringer [answered your question in the linked issue](https://github.com/cilium/cilium/issues/15774#issuecomment-837061657), there are architectural reasons for separating the control planes of different clusters from each other, one of which is k8s apiserver scalability, which is the principal reason why we support etcd configurations. Other consideration is the fact that we already have most of the needed control-plane interfaces using etcd that we already need to maintain, so reusing them was a sound architectural choice.

we can treat APIServer as a `SharedStore` and maybe just need to add an adapter to `ClusterMesh`.

> The design diagram shown in this issue description leaves important detail to be filled in in order to consider this proposal. For example, what do the blue boxes labeled as "cluster1" and "cluster2" represent? Red boxes seem to represent modules internal to Cilium agents. For example for the "watch remote identities" function, what entity is initiating it in cluster 1, and what entity in cluster 2 is responding to it? Are you proposing that Cilium agents connect to remote cluster's apiservers directly? If yes, then this seems like something we'd have to support and document in addition to the existing solution.
> 

I have updated the diagram and the design details description. Please take a look. 


> I'd also like to hear more about the AggregationApiserver mentioned at the bottom of the diagram.

[as this comment said ](https://github.com/cilium/cilium/issues/16299#issuecomment-848454100), it is the aggregationApiserver we want to propose.

**Comment by sstoner** [comment]
> @sstoner can you present this proposal in the weekly development meeting? It will happen in exactly 12 hours from now. Feel free to ask how to access the meeting in the #development channel in Cilium slack.

Ok, I have added the topic to meeting docs
