### ISSUE TITLE
Install hubble-ui via Helm chart without hubble-relay

### ISSUE THREAD

**Issue by d-m** [cilium/cilium#16628]
## Proposal / RFE

Attempting to install hubble-ui without hubble-relay via the Helm chart results in the following validation error:

```
Error: template: cilium/templates/validate.yaml:4:7: executing "cilium/templates/validate.yaml" at <fail "Hubble UI requires .Values.hubble.relay.enabled=true">: error calling fail: Hubble UI requires .Values.hubble.relay.enabled=true
```

However, some Cilium deployments, including [deployment via kOps](https://kops.sigs.k8s.io/networking/cilium/#hubble), already install hubble-relay.

It would be helpful if the Helm chart allowed installing hubble-ui without also needing to install hubble-relay via that method.

**Comment by joestringer** [comment]
This seems like a reasonable request, I think it would make sense to fix if someone proposed the PR. Finding the right code should be fairly straightforward using a `git grep` for `.Values.hubble.relay.enabled`, modifying the templates, and then testing it out using `helm template`.

**Comment by bradwhitfield** [comment]
I made an attempt at implementing this. Things look good when I run `helm template`, but I marked it as draft because I have an implementation question for this. In the current implementation, the hubble-relay service name and port are just the default. Should users have the ability to override these for non-standard installs?

To expand on that a bit, right now if `.Values.hubble.relay.tls.server.enabled` is true, then the hubble-ui deployment sets `FLOWS_API_ADDR` to `hubble-relay:443` and it uses port 80 if it's false. Would it make sense to allow people to specify the `FLOWS_API_ADDR` or something similar?

**Comment by rolinh** [comment]
> Would it make sense to allow people to specify the FLOWS_API_ADDR or something similar?

This makes sense to me, yes.

**Comment by bradwhitfield** [comment]
I realized when working on this that the `servicePort` for hubble-relay can already be defined, but when it's set, it's not used everywhere it should be. I was attempting to clean this up by adding a template in the `_helpers.tpl`, but I'm hitting errors with helm. It may be a few days before I can look at this more.

**Comment by bradwhitfield** [comment]
Sorry for the delay. The last few weeks have been crazy.

I've updated the PR, so if the status checks all pass, I'll remove the draft status from it and this will be ready.

**Comment by ti-mo** [comment]
Shipped in https://github.com/cilium/cilium/pull/17473.
