### ISSUE TITLE
Port ranges in network policies

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#16622]
The new `endPort` field for K8s' NetworkPolicies is in [alpha in v1.21](https://kubernetes.io/docs/concepts/services-networking/network-policies/#targeting-a-range-of-ports) and likely to become stable soon. It allows policies to target a range of ports instead of a single port.

Supporting this in Cilium will require changes in the datapath.

Tasks:
* [x] Add port range management mechanism
  * https://github.com/cilium/cilium/pull/20633
* [x] Add support for parsing/embedding port ranges from the API into the policy engine
* [x] Extend datapath for port range support
* [x] Implement policy engine -> datapath map generation logic

**Comment by jayunit100** [comment]
yay thanks !

**Comment by rikatz** [comment]
@aanm 👋 
This subject came into sig-network meeting, and we need one more CNI to graduate this. I've asked to move this to GA only in v1.24, wanted to know if this is going to be viable from Cilium side.

BTW sorry about not being helpful and opening a PR to this, but I have some lack of eBPF and C knowledge!

Thanks

**Comment by joestringer** [comment]
I think that the simplest implementation of this is "just" a matter of doing some processing in the policy internals to process the policy with a port range to generate multiple BPF map entries, one for each port. This shouldn't necessarily require BPF datapath changes. The only danger is that if the user configures many of these, they could run into BPF map size limits though. These are also configurable so they don't have to be a hard limit, but the user should be made aware of the limits so they can account for this. Ideally we'd either have a good way to limit the user against programming too many ports like this (eg pick an arbitrary port range size like 5 ports and ignore policies with more than that + warn), or alternatively we come up with a more nuanced datapath implementation that is aware of port ranges.

**Comment by rikatz** [comment]
@joestringer thanks for that. 

Yeah, so I was afraid of a bad user doing something like
```
- port: 1
   endPort: 65534
```

In this case, there would be some problem like adding 65533 items in a map for each port right?

I will reflect a bit about this, maybe try to learn something and check if and how can I help on this, even adding some safeguards and some user feedback when the user tries to add more than X ports per rule

**Comment by rikatz** [comment]
So per the suggested approach, here is what I'm going to do. In:

https://github.com/cilium/cilium/blob/a8e3fa283cf40b330035265bf83d63800b296bcf/pkg/k8s/network_policy.go#L280-L284

if endPort != nil, I'll iterate through port -> endPort and add all of those in `[]api.PortProtocol` array.

Will make some tests this week and check how it goes.

**Comment by rikatz** [comment]
@joestringer added: https://github.com/cilium/cilium/pull/17315

And btw, Cilium already limits for 40 ports per PortProtocol array in rules (discovered while writing the unit test) so I guess this works.

Now, putting my hat of "user", my only concern here is that I don't properly get feedback when I add more than 40 ports (other than errors in Cilium logs).

I'll start working on some KEP for Network Policy status and this way CNIs can provide feedback for users like "this rule was processed, or not, and why not" and I guess for Cilium and other CNIs would be good to say that "endPort is limited for 40 ports" , for example.

Thanks again for your help on this!

**Comment by joestringer** [comment]
@rikatz thanks for taking a first stab at it. I agree there's definitely still some concerns there to grapple with.

Do you have a link to the original KEP and use cases? I _feel_ like supporting huge port ranges in this kind of policies is counterproductive to the goals of nudging users towards the principle of least privilege.

**Comment by rikatz** [comment]
Sure, here is the KEP link: https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2079-network-policy-port-range

**Comment by joestringer** [comment]
I've looked through the use cases raised in https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2079-network-policy-port-range#user-stories . It seems to me like they have alternative implementations or workarounds that would work in Cilium without supporting endPort:

* Story 1 - Opening communication to NodePorts of other cluster
  * Rather than implementing cluster<->cluster services via NodePorts, the user could use [ClusterMesh](https://docs.cilium.io/en/v1.10/gettingstarted/clustermesh/clustermesh/#gs-clustermesh) to provide global services. Then the policy enforcement would be based on backend port numbers rather than NodePort service port numbers. Richer policy could also be used to match on backend pod labels rather than IPs.
* Story 2 - Blocking the egress for not allowed insecure ports
  * A combination of a permissive allow policy (at L3) plus [Deny Policies](https://docs.cilium.io/en/v1.10/policy/language/#deny-policies) would allow the user to block communication to specific well-known ports that should always be denied.
* Story 3 - Containerized Passive FTP Server
  * If the containerized FTP server is only hosting the server on port 21 as a regular (non-hostnetwork) pod, then there should be no functional difference between allowing inbound L3 access from authorized clients vs. allowing only ports 21 and 49152+ from authorized clients, since the containerization is providing isolation between this FTP server and the other services that would traditionally run adjacent to the FTP server in the same network namespace.

Based on the above, the question that comes to mind is basically whether it is worthwhile to integrate a partial solution like the initial proposal or not. Even if users wish to deploy these use cases using the endPort feature, the current proposal would restrict the ability to solve story 1 / 3 due to the port limitations. The "nice" effect would be to assist upstream k8s in the standardization of this new policy primitive. At the same time, I wonder if we would be in some sense undermining the standardization process if k8s netpol users cannot rely on all CNIs supporting all of these stories consistently.

**Comment by thockin** [comment]
I wasn't really tracking the implementation of this in Cilium, but it "came up" today.  Limiting this to small-N ports and creating N rules feels like a pretty severe limitation to me.  It sort of says "not implementable" to me. :(

My questions are:

a) Is my "not implementable" assessment too dramatic?
b) Is there anyone actually working on this?  (I really do not want to GA the feature without support in such a major impl)
c) Why did nobody jump up and down and scream that this design doesn't work for eBPF?  This has been on sig-net for a long time.

While Cilium is not part of Kubernetes, it's an important piece of the ecosystem.  We rely on the ecosystem, and that includes letting us know when we are making problems for you.

**Comment by jayunit100** [comment]
hiya folks, in general, the NetworkPolicy GA features, API  isn't fully supported by all providers. We have a tool https://github.com/mattfenwick/cyclonus that we've been using to evaluate this overall problem holistically (tabulates all evolved from the upstream e2es)

https://kubernetes.io/blog/2021/04/20/defining-networkpolicy-conformance-cni-providers/#results

There are other examples (pod CIDR policies) which *are* GA which also arent implemented in some cases.

We could do a new run of Cyclonus / netpol E2Es against 
- antrea 1.4
- calico 3.21
- cillium 1.11
- kube-router 
- ovn-kubernetes @astoyocos 

And evaluate this if its useful to have a more holistic picture of all the holes in the ecosystem .  Maybe we could just run them together on friday (we usually have a networking related hangout at 2pm EST/11 PST if folks want to join).

In general, Im pretty sure that we'll find a pretty broad range of results.

**Comment by thockin** [comment]
@rikatz FYI

**Comment by alex-berger** [comment]
FYI, as of Kubernetes v1.25, `endPort` is stable https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/#promoted-endport-in-network-policy-to-stable.

**Comment by joestringer** [comment]
Just as a brief update, I added a short breakdown of the tasks necessary to support this use case efficiently in eBPF in order to minimize per-packet latency while supporting this new feature.

**Comment by sathieu** [comment]
@joestringer What is the status of this issue?

**Comment by michalschott** [comment]
Hello 👋

**Comment by dalvarezquiroga** [comment]
Hi! thanks to open this issue,  same problem here , [cilium doesn't support port ranges](https://github.com/cilium/cilium/blob/v1.13.2/pkg/policy/api/l4.go#L27-L36),  any plan to launch the fix in future releases?

**Comment by paurosello** [comment]
Seems like https://github.com/cilium/cilium/pull/23016 is the implementation, not sure how far away from merging though

**Comment by nathanjsweet** [comment]
@paurosello Considering that the 1.14 feature freeze is this Friday, that seems unlikely.

**Comment by joestringer** [comment]
v1.14 feature freeze was _last_ friday, we're not accepting new features at this time. I can't make any promises on behalf of other contributors about the status or plans to support it in newer releases, but your feedback is welcome on the PR.

**Comment by angelbarrera92** [comment]
Any update?

**Comment by nathanjsweet** [comment]
The datapath portion of this work has already been completed. We now need to make use of it in the agent. It *should* be out with 1.15.

**Comment by nathanjsweet** [comment]
Bad news. This is not going to make 1.15 and will be delayed to 1.16. Much more userspace code had to be refactored than initially estimated. Keeping a data structure of port ranges that is searchable is something that we needed to implement to merge L4-L7 policies by port-protocol ranges (for example, checking if an allow-policy overlaps with a deny-policy and then automatically attenuating the allow-policy range because of it).

**Comment by kollender-noname** [comment]
Any update on this feature? 🙏

**Comment by nathanjsweet** [comment]
@kollender-noname it's making good progress, but it is contingent on https://github.com/cilium/cilium/pull/29717 and https://github.com/cilium/cilium/pull/30749.

**Comment by kollender-noname** [comment]
Thanks @nathanjsweet 
We hope to use this feature soon.
Are you still planning to release it in 1.16?
And if so - any estimation on when 1.16 is gonna be out?

**Comment by sethstuart** [comment]
@nathanjsweet There was mention in the past by @rikatz that cilium caps every PortProtocol array at 40 ports. Will that limit be greatly increased by this change? Is there a theoretical maximum that we know of at this time?

**Comment by jayunit100** [comment]
Hi cillium ! I'd also like to know if we can pin this to a specific release.... in the future ?

**Comment by nathanjsweet** [comment]
@sethstuart 
> There was mention in the past by @rikatz that cilium caps every PortProtocol array at 40 ports. Will that limit be greatly increased by this change? Is there a theoretical maximum that we know of at this time?

No. You'll be able to create any size range.

@jayunit100 
> Hi cillium ! I'd also like to know if we can pin this port range implementation to a specific release.... in the future ?

Very hopeful that we can make 1.16.

**Comment by jspaleta** [comment]
sorry, I've no idea what I did I was just looking at the project board and must have clicked something accidently. Completely unintentional

**Comment by Tyrael** [comment]
@nathanjsweet could you close it again as completed?

**Comment by nathanjsweet** [comment]
> So is this still not completed? I'm confused.

Not yet. That large PR you reference is all of the work, but it is being broken up into smaller PRs (per reviewer feedback). Part 2 of 3 was just approved. The final PR will be open tomorrow.

**Comment by nathanjsweet** [comment]
https://github.com/cilium/cilium/pull/32807 is the last PR that needs to be merged for this issue to close.

**Comment by squeed** [comment]
We got quite a lot of work done on this, but it didn't quite make the cut for v1.16. Moving to the v1.17 milestone.

**Comment by SixFive7** [comment]
> #32807 is the last PR that needs to be merged for this issue to close.

Isn't https://github.com/cilium/cilium/pull/32807 a good as done?


> We got quite a lot of work done on this, but it didn't quite make the cut for v1.16. Moving to the v1.17 milestone.

Would that not be in time for v1.16?

**Comment by joestringer** [comment]
Due to the active progress and community support for this feature we've made a feature freeze exception for this feature and merged the corresponding PRs into the `main` branch. This puts it on track for the upcoming v1.16 feature release ETA next month. We'll tag a release candidate v1.16.0-rc.1 with the feature likely early July, so it would be awesome to get some validation from users in their own staging / development environments about the experience with this feature in the release candidate.

**Comment by nvibert** [comment]
Tested and worked fine for me!
