### ISSUE TITLE
Jenkins CI should collect logs

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#1664]
When Jenkins CI fails a PR test, it puts together a tar. Currently this only appears to include the console output and some kind of test debug output. It should also include general cilium information.

At minimum:
- Cilium daemon logs
- Proxy logs (if relevant)

Also useful:
- Output of cilium commands, eg "cilium endpoint get"; "cilium policy get"; etc.
- Copy of /var/run/cilium/* (Perhaps minus the binaries)
- Dump of maps from /sys/fs/bpf/tc/globals/cilium*

**Comment by ianvernon** [comment]
Most of this currently exists - is it not appearing in a specific build ?

**Comment by joestringer** [comment]
The k8s guestbook test in this run is an example:
https://jenkins.cilium.io/job/cilium/job/cilium/job/PR-1599/15/

**Comment by ianvernon** [comment]
There is an issue with this test, in that if the cleanup steps fail during the test, the logs are not gathered appropriately. The proper fix would be to do something like:
```
function finish_test {
  log "finishing test: ${TEST_NAME}"
  cleanup || true
  gather_files ${TEST_NAME} k8s-tests
  gather_k8s_logs "2" ${LOGS_DIR}
  log "finished running test: $TEST_NAME"
}
```

as a quick fix. The drawback to doing this is that if the cleanup fails, then it might cause failures in the next test since the environment for the next test won't be clean. We could do something like the following to avoid that:
```
set +e
cleanup
CLEANUP_RETURN_CODE=$?
set -e
...
# End of finish_test function
if [[ "$CLEANUP_RETURN_CODE" != "0" ]]; 
  log "cleanup failed, exiting"
  exit 1
fi
```

**Comment by joestringer** [comment]
Issue no longer present.
