### ISSUE TITLE
CiliumEndpoint missing for a pod

### ISSUE THREAD

**Issue by liuyuan10** [cilium/cilium#17047]
cilium version: 1.9.4
kubelet: 1.20

After upgrade of a cluster, we notice ciliumendpoint is missing for a running pod. We dig into it and think it may be a bug in the way cilium manages cilium endpoint. Here is the timeline:

1. An existing statefulset pod alertmanager-0 running on a node
2. cluster is going with an upgrade. both cilium-agent and alertmanager-0 are getting upgraded
3. kubelet fails to remove the old container for alertmanager-0 because cilium-agent is being rebooted at the same time (so cni is missing)
```
Aug 03 04:08:11 bmut-dozrr9-0803-024754-871f3-acp2 kubelet[48398]: E0803 04:08:11.853703   48398 pod_workers.go:191] Error syncing pod 3f7c5201-edc9-4b83-a6a2-470289ae89ac ("alertmanager-0_kube-system(3f7c5201-edc9-4b83-a6a2-470289ae89ac)"), skipping: error killing pod: failed to "KillPodSandbox" for "3f7c5201-edc9-4b83-a6a2-470289ae89ac" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"a580c1ab31c3b1c66cbc5d542f9eb340bd0494449c2d832c1bda6e27636ed949\": failed to find plugin \"cilium-cni\" in path [/opt/cni/bin]"
```

4. cilium-agent is rebooted and starts to restore existing endpoints
```
2021-08-03T04:08:34.378283278Z level=info msg="New endpoint" containerID=a580c1ab31 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=277 identity=60609 ipv4=192.168.1.165 ipv6= k8sPodName=kube-system/alertmanager-0 subsys=endpoint
```
5. Almost at the same time, kubelet creates a new container for the pod:
```
2021-08-03T04:08:34.737428463Z level=info msg="Create endpoint request" addressing="&{192.168.1.85 78bda739-f410-11eb-92f1-42010a800063  }" containerID=f4a2e88f66aabf348196605c0b4d430bf6f3b4f660224f984bd16053b07b6b23 datapathConfiguration="<nil>" interface=lxc368fadda4150 k8sPodName=kube-system/alertmanager-0 labels="[]" subsys=daemon sync-build=true
```

Note that the container ID is not the same, so it's kubelet creating a new container for the same pod

6. after ~ 30seconds, kubelet tries to remove the old container of the pod
```
2021-08-03T04:09:00.533694827Z level=info msg="Delete endpoint request" id="container-id:a580c1ab31c3b1c66cbc5d542f9eb340bd0494449c2d832c1bda6e27636ed949" subsys=daemon
2021-08-03T04:09:00.534015683Z level=info msg="Releasing key" key="[k8s:app=alertmanager k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=alertmanager k8s:io.kubernetes.pod.namespace=kube-system k8s:statefulset.kubernetes.io/pod-name=alertmanager-0]" subsys=allocator
2021-08-03T04:09:00.539698529Z level=info msg="Removed endpoint" containerID=a580c1ab31 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=277 identity=60609 ipv4=192.168.1.165 ipv6= k8sPodName=kube-system/alertmanager-0 subsys=endpoint
```

Note the container id in the request is the old one.

7. cilium-agent removes the ciliumendpoint but still the pod is running.

After all of these steps, we end up with alertmanager-0 running fine but doesn't have a cilium endpoint. I guess the issue is that when we process delete endpoint rpc request, we didn't check the container id matches the one in the cilium_endpoint so if kubelet is removing an stale container, ciliumendpoint for a pod is removed. Shall we add this check?

**Comment by christarazi** [comment]
One thing I'm wondering about is why the IP changed. If pod IPs are unique, isn't that evidence that there were two "different" pods? At first thought, I don't think adding a check to look for container ID will fix this issue. To me, this issue sounds like a race between Cilium coming up and the pod being restarted. If Cilium was down while the pod was created, then Cilium will not know to manage this pod, hence why the pod resource exists, but not the corresponding CEP. The workaround for such cases is to restart the pod so that Cilium can manage it.

**Comment by liuyuan10** [comment]
Forget to mention the alertmanager is a statefulset and that's why the name of the pod doesn't change after recreation.

Not sure why you think it's strange that the IP changes. If you kubectl delete a pod in a statefulset, the IP will change while the name of the pod doesn't, which is what's happening in this case. 

The cause I see is that kubelet is managing containers individually but cilium-agent is managing a cilium endpoint per pod. So whenever there is a transient state where kubelet have two containers for the same pod, cilium-agent is confused. 

> If Cilium was down while the pod was created, then Cilium will not know that it needs to manage this pod,

I don't think so. kubelet can't create a new pod successfully without the cni so cilium will have all the information. just that cilium-agent doesn't link the ciliumendpoint to the container. Today there is already a container id in the ciliumendpoint so making sure the container id in the delete endpoint request matches that in the ciliumendpoint makes sense to me.

**Comment by christarazi** [comment]
I'm confused with your description of the problem because it seems to me that there ends up being two different pods because of the IP change. 

Step 4 has IP `192.168.1.165`.
Step 5 has IP `192.168.1.85`. 

My understand is that if it's the same pod, then the IP won't change. If only the containers within the pod are recreated, then pod doesn't obtain a new IP. Is that your understanding as well?

In the end, I see that the endpoint-delete happens on `endpointID=277`, which is the same endpointID that step 4 has. Step 5 should have ended up with a new CEP.

Do you have the full logs so that we can see which endpointID was allocated for step 5? That would get us closer to determining whether Cilium has a bug or not.

**Comment by liuyuan10** [comment]
This is a statefulset pod so when the pod is being restarted, pod IP will change while pod name won't. So whether it's a "new" pod depends on the definition.

I do see a different endpoint id (1169) allocated for the new container in step 5:
```
2021-08-03T04:08:34.737428463Z level=info msg="Create endpoint request" addressing="&{192.168.1.85 78bda739-f410-11eb-92f1-42010a800063  }" containerID=f4a2e88f66aabf348196605c0b4d430bf6f3b4f660224f984bd16053b07b6b23 datapathConfiguration="<nil>" interface=lxc368fadda4150 k8sPodName=kube-system/alertmanager-0 labels="[]" subsys=daemon sync-build=true
2021-08-03T04:08:34.737438952Z level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1169 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-08-03T04:08:34.737472469Z level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1169 identityLabels="k8s:app=alertmanager,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=alertmanager,k8s:io.kubernetes.pod.namespace=kube-system,k8s:statefulset.kubernetes.io/pod-name=alertmanager-0" ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-08-03T04:08:34.737535463Z level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1169 identity=60609 identityLabels="k8s:app=alertmanager,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=alertmanager,k8s:io.kubernetes.pod.namespace=kube-system,k8s:statefulset.kubernetes.io/pod-name=alertmanager-0" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
2021-08-03T04:08:34.737594359Z level=info msg="Waiting for endpoint to be generated" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1169 identity=60609 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```

I'm trying to see where the cilium-agent removes the ciiumendpoint object from [DeleteEndpoint](https://github.com/cilium/cilium/blob/master/daemon/cmd/endpoint.go#L685), but I only find resource cleanup but not the ciliumentpoint object. How agent is removing the ciliumendpoint upon receiving the DeleteEndpointRequset?

**Comment by christarazi** [comment]
The CEP object is only removed because it has the `ownerReference` set to the backing pod, so that their lifecycles are tied together. 

Basically, the timeline of events for an endpoint-delete is:

* `kubectl delete pod app1`
* kubelet sends CNI DEL to Cilium
* Cilium calls DeleteEndpoint(), which deletes the endpoint internally (removes from BPF maps, etc)
* app1 pod resource is deleted as the CNI DEL has completed
* Cilium's CEP watcher receives a CEP delete (because of `ownerReference` set to the now-deleted pod)
  * Deletes endpoint's IP from ipcache, etc

**Comment by liuyuan10** [comment]
Thanks for the explanation. So in this case, the CEP is removed because the pod is deleted during pod upgrade. But in this case, the pod is there while CEP is missing. Does it mean when k8s creates the pod (with the same name) again, cilium gets confused?

**Comment by Weil0ng** [comment]
> The CEP object is only removed because it has the `ownerReference` set to the backing pod, so that their lifecycles are tied together.
> 
> Basically, the timeline of events for an endpoint-delete is:
> 
> * `kubectl delete pod app1`
> * kubelet sends `CNI DEL` to Cilium
> * Cilium calls DeleteEndpoint(), which deletes the endpoint internally (removes from BPF maps, etc)
> * app1 pod resource is deleted as the `CNI DEL` has completed
> * Cilium's CEP watcher receives a CEP delete (because of `ownerReference` set to the now-deleted pod)
>   
>   * Deletes endpoint's IP from ipcache, etc

Curious in this issue, a bit confused by above chain of events, so when and who issues the DELETE for the CEP of "app1" to the apiserver because the watcher can get the delete event?

**Comment by liuyuan10** [comment]
>Curious in this issue, a bit confused by above chain of events, so when and who issues the DELETE for the CEP of "app1" to the apiserver before any watcher can get the delete event?

According to christarazi , I think it's when the k8s pod is removed, apiserver removes the CEP as well because threre is a owner ref to k8s pod.

**Comment by Weil0ng** [comment]
> According to christarazi , I think it's when the k8s pod is removed, apiserver removes the CEP as well because threre is a owner ref to k8s pod.

Ah I see, makes sense.

**Comment by liuyuan10** [comment]
@christarazi From you said, basically the issue is in CEP creation not deletion. In this case, cilium failed to create new CEP for the pod that gets removed and recreated with the same name. Do you have a flow about how CEP is created in cilium? is it done through CNI ADD or by pod watcher?

**Comment by christarazi** [comment]
@liuyuan10 It's done through CNI ADD. The CNI ADD will call Cilium's `(d *Daemon).createEndpoint` which in the process of creating the endpoint, also creates the CEP.

I think I'm starting to convince myself that we should have ended up with 2 CEPs. The reason is because at step 5, we received a CNI ADD for the "same" pod. This pod has the same name as the previous pod, but it's effectively a new pod because it has a new IP and a new container ID. However, like pods, CEPs are unique based on name, and the name used is the pod name. Since step 5 involves creating a pod with the same name, it causes issues. Cilium shares the assumption that pod names are unique with K8s (https://kubernetes.io/docs/concepts/overview/working-with-objects/names/). 

If we had 2 CEPs, then the correct one would've been deleted. I'm not yet sure what the correct approach is, but I'm considering two options (there might be others):
* Disambiguate the endpoint-delete (like you mentioned) by IP addr or by container ID, or even both
* Or disambiguate the endpoint-create

Another interesting aspect to this is what's happening at step 4. When Ciilum starts up, it attempts to restore endpoints it finds locally on the filesystem, without connecting to k8s first. But Cilium will validate that a pod exists with that name. If it doesn't, then it trashes the restored endpoint. If it does, then it keeps it. In this case, it look like the latter occurs because the `alertmanager-0` pod still exists, but as we mentioned above, it is effectively new pod because of container ID and IP addr, at least from Cilium's point of view.

I'll post on #development for further discussion.

**Comment by Weil0ng** [comment]
@christarazi Thanks for the detailed analysis! I have the impression that there are multiple places where we reply on just "namespace/name" of a CEP to lookup and do stuff, if we not introduce another part into the "key", then all these logic needs to take the new key "part" into consideration.

I'm actually still a bit confused as why we would have two pods of same name in this case...as you mentioned k8s is assuming uniqueness of resource names, no? This sounds like a general k8s issue?

**Comment by liuyuan10** [comment]
> When Ciilum starts up, it attempts to restore endpoints it finds locally on the filesystem, without connecting to k8s first. But Cilium will validate that a pod exists with that name. If it doesn't, then it trashes the restored endpoint.

How does it verify the pod exists without connecting to k8s? Do you mean it restores first and then later verify with k8s and trash the endpoint? Our log around (4) is indicating the endpoint is restored but no trashing is observed.

```
2021-08-03T04:08:34.378283278Z level=info msg="New endpoint" containerID=a580c1ab31 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=277 identity=60609 ipv4=192.168.1.165 ipv6= k8sPodName=kube-system/alertmanager-0 subsys=endpoint
2021-08-03T04:08:34.378411691Z level=info msg="New endpoint" containerID=a420b0e4d7 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2264 identity=24777 ipv4=192.168.1.39 ipv6= k8sPodName=kube-system/anthos-log-forwarder-5w4xs subsys=endpoint
2021-08-03T04:08:34.378447151Z level=info msg="Successfully restored endpoint. Scheduling regeneration" endpointID=2264 subsys=daemon
2021-08-03T04:08:34.378455709Z level=info msg="Successfully restored endpoint. Scheduling regeneration" endpointID=277 subsys=daemon
2021-08-03T04:08:34.378460584Z level=info msg="Successfully restored endpoint. Scheduling regeneration" endpointID=1227 subsys=daemon
2021-08-03T04:08:34.378859412Z level=info msg="Reserved new local key" key="k8s:app=alertmanager;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=alertmanager;k8s:io.kubernetes.pod.namespace=kube-system;k8s:statefulset.kubernetes.io/pod-name=alertmanager-0;" subsys=allocator
2021-08-03T04:08:34.379031768Z level=info msg="Reusing existing global key" key="k8s:app=alertmanager;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=alertmanager;k8s:io.kubernetes.pod.namespace=kube-system;k8s:statefulset.kubernetes.io/pod-name=alertmanager-0;" subsys=allocator
2021-08-03T04:08:34.379559918Z level=info msg="Reserved new local key" key="k8s:app=anthos-log-
```

Because the pod is quickly recreated by k8s while cilium is getting restarted, probably it won't trash it because there is a pod with the same name. What's in question to me is that why the CNI ADD in (5) didn't add a CEP assuming the it's already removed at that time. looks like agent is tricked to think there is already a CEP. maybe there is a race between k8s removes a POD vs agent observes the removal of CEP

**Comment by christarazi** [comment]
@Weil0ng 

> I'm actually still a bit confused as why we would have two pods of same name in this case...as you mentioned k8s is assuming uniqueness of resource names, no? This sounds like a general k8s issue?

I think that's at the core of my confusion. I think Cilium must follow whatever Kubernetes deems "uniqueness" is. If statefulsets are the exception, then Cilium must account for that.

@liuyuan10 The above is why I'm not saying to just go right ahead re: adding a check for containerID in the delete. I think the solution needs to dig one level deeper

> How does it verify the pod exists without connecting to k8s? Do you mean it restores first and then later verify with k8s and trash the endpoint?

Yes that's correct.

> Because the pod is quickly recreated by k8s while cilium is getting restarted, probably it won't trash it because there is a pod with the same name.

Correct yeah it seems to me that the pod is back up by the time Cilium goes to validate the restored endpoint.

> What's in question to me is that why the CNI ADD in (5) didn't add a CEP assuming the it's already removed at that time.

I think because the CEP already exists with the pod name, because CEPs are named after pod names.

**Comment by aanm** [comment]
@Weil0ng @liuyuan10 The agent is already watching for all CEP events. Ideally, we should re-write https://github.com/cilium/cilium/blob/ed37faf99d9bf9d9b8a02991c9e58a362c731f14/pkg/k8s/watchers/endpointsynchronizer.go#L44 in a way that avoids performing gets directly to kube-apiserver https://github.com/cilium/cilium/blob/ed37faf99d9bf9d9b8a02991c9e58a362c731f14/pkg/k8s/watchers/endpointsynchronizer.go#L138
If we replace the above Get with a Get from the watcher store that contains all CEPs `pkg/k8s/watchers/cilium_endpoint.go` we can check if the CEP is missing. This means that we will stop relying on the `lastMdl` and rely on the information stored in the watcher store. Let me know if this makes sense.

**Comment by Weil0ng** [comment]
> If we replace the above Get with a Get from the watcher store that contains all CEPs `pkg/k8s/watchers/cilium_endpoint.go` we can check if the CEP is missing. This means that we will stop relying on the `lastMdl` and rely on the information stored in the watcher store. Let me know if this makes sense.

(I feel like I may be totally missing your point here but) how would this help in this case?

**Comment by aanm** [comment]
@Weil0ng the `RunK8sCiliumEndpointSync` would noticed the CEP is gone and it would recreate it. Right now it doesn't detect it's gone because it's comparing it against `lastMdl`, which was grabbed before the endpoint was deleted.

**Comment by Weil0ng** [comment]
> @Weil0ng the `RunK8sCiliumEndpointSync` would noticed the CEP is gone and it would recreate it. Right now it doesn't detect it's gone because it's comparing it against `lastMdl`, which was grabbed before the endpoint was deleted.

Yea I get that `lastMdl` needs to come from watch store, but how is replacing the GET from apiserver with watch store in line 138 help achieve this? My understanding is that watch store is "one-step" behind on apiserver (until the event propagates), so if the CEP is gone, we should be able to tell from the apiserver too?

My understanding is that we should be populating `lastMdl` from watch store before https://github.com/cilium/cilium/blob/ed37faf99d9bf9d9b8a02991c9e58a362c731f14/pkg/k8s/watchers/endpointsynchronizer.go#L120.

**Comment by aanm** [comment]
>Yea I get that lastMdl needs to come from watch store, but how is replacing the GET from apiserver with watch store in line 138 help achieve this? My understanding is that watch store is "one-step" behind on apiserver (until the event propagates), so if the CEP is gone, we should be able to tell from the apiserver too?

Yes, however that means we will perform unnecessary GETs to the apiserver which doesn't scale. This is not an issue if we do it for the local store.

**Comment by Weil0ng** [comment]
> Yes, however that means we will perform unnecessary GETs to the apiserver which doesn't scale. This is not an issue if we do it for the local store.

I totally agree, but in my head this is a different issue...maybe I missed something?

**Comment by aanm** [comment]
> > Yes, however that means we will perform unnecessary GETs to the apiserver which doesn't scale. This is not an issue if we do it for the local store.
> 
> I totally agree, but in my head this is a different issue...maybe I missed something?

It is a different issue, but it will only be an issue if we decide to fix this bug this way. If we change it to fetch endpoints from the watcher store then it won't be an issue.

**Comment by Weil0ng** [comment]
> It is a different issue, but it will only be an issue if we decide to fix this bug this way. If we change it to fetch endpoints from the watcher store then it won't be an issue.

Right, so we don't do GET, we fetch `lastMdl` from watch store. Is that what you were suggesting?

**Comment by aanm** [comment]
> > It is a different issue, but it will only be an issue if we decide to fix this bug this way. If we change it to fetch endpoints from the watcher store then it won't be an issue.
> 
> Right, so we don't do GET, we fetch `lastMdl` from watch store. Is that what you were suggesting?

Correct, which is an "inexpensive" operation when compared when doing a GET to the kube-apiserver.

**Comment by rustrial** [comment]
+1 we observe the same behaviour with `StatefulSets`.

**Comment by Weil0ng** [comment]
Hi @christarazi @aanm, coming back to this, so IIRC, the root cause for this is:

- old pod deleted
- old CEP becomes orphaned
- new pod created with same name but different IP
- cilium tries to create new CEP but find the orphaned CEP and update its IP
- apiserver GC tries to delete orphaned CEP
- agent gets the old CEP delete event and deletes the CEP
- now we have a pod without a CEP

This does not violate the uniqueness of names as at any point of time, there is one and only one pod/CEP with that name.

I wonder if, as a more scoped fix to this, we can update `ownerReference` to the new pod when updating the `CEP`?

**Comment by christarazi** [comment]
@Weil0ng I'm not sure that's an accurate timeline for this, especially 

> cilium tries to create new CEP but find the orphaned CEP and update its IP

Have you seen evidence that it updated the CEP with the correct IP? 

> * apiserver GC tries to delete orphaned CEP
> * agent gets the old CEP delete event and deletes the CEP

I don't think the above is accurate either. I've not seen evidence that the above is the case.

Either way, I think the path forward for this bug is to reproduce the issue and trace the code that's happening here:
https://github.com/cilium/cilium/blob/b36c93b4c066bde0b43f6d8d4687ba32768038c4/pkg/k8s/watchers/endpointsynchronizer.go#L83

Once we understand why that code is not sufficient, then we can proceed with a fix. But until then, it's not clear what should be done.

**Comment by Weil0ng** [comment]
@christarazi I synced with @skmatti on our internal issue logs (in a different instance of this issue, same symptoms), seems like my previous understand was indeed inaccurate.

Here's an updated theory of the root cause timeline:
- old pod (on old node) gets deleted
- old CEP gets deleted
- new pod (on new node) created (with same name because of statefulSet)
- new CEP created ```2021-09-30 10:00:20.151 PDT
mgmt-cluster
k8s.io
…io.cilium.v2.ciliumendpoints.create
…ndpoints/argocd-application-controller-0
system:serviceaccount:kub…
audit_log, method: "io.cilium.v2.ciliumendpoints.create", principal_email: "system:serviceaccount:kube-system:cilium"```
- old cilium-agent (on old node) restarted for some reason and tries to restore all endpoints, when it hits the CEP for the deleted pod, it hits the following because it only looks for the pod in the local podStore https://github.com/cilium/cilium/blob/baa9e9a200a96eb4cf97a3e660af3f5f02ae3762/daemon/cmd/state.go#L71 
(```2021-09-30 10:00:27.294 PDT cilium-agent level=warning msg="Unable to restore endpoint, ignoring" endpointID=129 error="Kubernetes pod argocd/argocd-application-controller-0 does not exist" k8sPodName=argocd/argocd-application-controller-0 subsys=daemon```)
- then it deletes the CEP using the same name here https://github.com/cilium/cilium/blob/baa9e9a200a96eb4cf97a3e660af3f5f02ae3762/daemon/cmd/state.go#L191 ```2021-09-30 10:00:30.997 PDT
mgmt-cluster
k8s.io
…io.cilium.v2.ciliumendpoints.delete
…ndpoints/argocd-application-controller-0
system:serviceaccount:kub…
audit_log, method: "io.cilium.v2.ciliumendpoints.delete", principal_email: "system:serviceaccount:kube-system:cilium"```

We can provide more logs if there's any missing gaps in the theory.

**Comment by christarazi** [comment]
@Weil0ng Hm, I'm still confused how this is possible for the following step
> * old cilium-agent (on old node) restarted for some reason and tries to restore all endpoints, when it hits the CEP for the deleted pod, it hits the following because it only looks for the pod in the local podStore 

The reason I am confused is because

```
2021-09-30 10:00:27.294 PDT cilium-agent level=warning msg="Unable to restore endpoint, ignoring" endpointID=129 error="Kubernetes pod argocd/argocd-application-controller-0 does not exist" k8sPodName=argocd/argocd-application-controller-0 subsys=daemon
```

doesn't make sense to me, as the pod should exist at this point. I see that you mentioned that it only inside the local pod store, but we have a line to make sure that our K8s caches are synced before this point, see https://github.com/cilium/cilium/blob/baa9e9a200a96eb4cf97a3e660af3f5f02ae3762/daemon/cmd/state.go#L68.

It would be good to reproduce this and assert if truly the pod cache is not actually synced at this point. If that is the case, then the bug fix is to make sure we are synced first (& investigate why the above linked line is not enough). If that is not the case, then the theory still has a gap.

**Comment by Weil0ng** [comment]
> ...as the pod should exist at this point. I see that you mentioned that it only inside the local pod store, but we have a line to make sure that our K8s caches are synced before this point

Yes the cache is synced and I don't think there's an issue there. Problem is that the watcher itself only watches for local pods, so even if it is synced, it will only have local pods (unless I missed something?). The reason why we end up in this situation is that the pod WAS indeed deleted on the old node, and only then cilium-agent got restarted and tried to restore endpoints, so at that point, the pod exists on another node so it will not show up in the local pod store.

**Comment by christarazi** [comment]
@Weil0ng Ah I see now. That makes sense. It's not obvious to me what the solution could be here. 

Maybe we simply have to disambiguate the delete and check for the container ID, as we've just seen that a pod with the same name can be recreated onto another node, who is now managing the new CEP object containing a different container ID.

cc @aanm to double check me.

**Comment by aanm** [comment]
@christarazi @Weil0ng We should only delete the CEP with the pre condition that its UID is the same when the CEP was created. Something like this:


```patch
diff --git a/pkg/k8s/watchers/endpointsynchronizer.go b/pkg/k8s/watchers/endpointsynchronizer.go
index 9e716c85b4..b4fe16a44e 100644
--- a/pkg/k8s/watchers/endpointsynchronizer.go
+++ b/pkg/k8s/watchers/endpointsynchronizer.go
@@ -177,6 +177,9 @@ func (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync(e *endpoint.Endpoin
                                                        return err
                                                }
 
+                                               // Store CEP UID
+                                               e.CEPUID = localCEP.UID
+
                                                // continue the execution so we update the endpoint
                                                // status immediately upon endpoint creation
                                        case err != nil:
@@ -324,8 +327,15 @@ func deleteCEP(ctx context.Context, scopedLog *logrus.Entry, ciliumClient v2.Cil
                scopedLog.Debug("Skipping CiliumEndpoint deletion because it has no k8s namespace")
                return nil
        }
-       if err := ciliumClient.CiliumEndpoints(namespace).Delete(ctx, podName, meta_v1.DeleteOptions{}); err != nil {
-               if !k8serrors.IsNotFound(err) {
+
+       err := ciliumClient.CiliumEndpoints(namespace).Delete(ctx, podName, meta_v1.DeleteOptions{
+               Preconditions: &meta_v1.Preconditions{
+                       UID: func() *types.UID { a := types.UID(e.CEPUID); return &a }(),
+               },
+       })
+
+       if err != nil {
+               if !k8serrors.IsNotFound(err) || !k8serrors.PreConditionFailed() {
                        scopedLog.WithError(err).Warning("Unable to delete CEP")
                }
        }
```

**Comment by Weil0ng** [comment]
Coming back to this, is the `UID` the same as `ID` of an endpoint?

**Comment by christarazi** [comment]
@Weil0ng The UID is the K8s object UID, not a Cilium-specific field like the `ID` is. The diff that Andre posted above is not a full example, but rather pseudocode to get started. For instance, the `CEPUID` field would be need to created on the `Endpoint` object, etc.
