### ISSUE TITLE
DNSPolicy is ClusterFirst but should be ClusterFirstWithHostNet

### ISSUE THREAD

**Issue by enicholson125** [cilium/cilium#17170]
## Bug report

**General Information**

- Cilium version 1.9.9
- AWS EKS AMI 1.19.6-20210720
- Kubernetes 1.20 and 1.19 (haven't tried other versions)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

I was using a kubernetes 1.20 cluster provisioned with EKS, with cilium set up in aws-vpc-cni chaining mode when I came across this issue. I haven't tried with another setup.

1. Install cilium using the helm chart, with etcd.managed = true and etcd.k8sService = true. This installs the cilium agent with dnsPolicy = ClusterFirst.
2. Run `kubectl exec -ti -n cilium-system ds/cilium -- cilium kvstore get --recursive cilium/state/nodes/v1/`. This will fail with the error `Error while dialing dial tcp: lookup cilium-etcd-client.cilium-system.svc on 10.145.0.2:53: no such host`
3. Edit the cilium agent daemonset to have dnsPolicy = ClusterFirstWithHostNet
4. Run `kubectl exec -ti -n cilium-system ds/cilium -- cilium kvstore get --recursive cilium/state/nodes/v1/` again. This time it should succeed.

Looking at the [DNS section of the kubernetes docs](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy) also indicates that this should be ClusterFirstWithHostNet, as the cilium agent has HostNetwork = true

**Comment by bradwhitfield** [comment]
I started digging into this, because I thought it would be an easy fix, but now I'm second guessing.

It looks like this commit deliberately set the DNS to the kubelet default (`ClusterFirst` in this case) to avoid a dependency on CoreDNS being available for Cilium to run. In this case it means setting the `ClusterFirstWithHostNet` is not the desired fix.

https://github.com/cilium/cilium/commit/293fcd590474f7addfa6e080a82c0f430058a6cd#diff-f9c3b5155abfef2594685cb416c1bb4004e9d94870bb94abbd2014f5e8606044

I don't have immediate access to EKS, but assuming that the cluster is up and healthy and it's just the `kvstore` commands that don't work, I suspect the actual problem is that the CLI commands are not programmatically determining the etcd service IP like the daemon, operator, and preflight do.

https://github.com/cilium/cilium/search?q=initkvstore

Sorry, I'm beyond my ability at this point. Someone from the project (or least someone who knows the code better), will have to chime in from here, but I wanted to share my findings.

**Comment by enicholson125** [comment]
Thanks for looking! I'm also a bit out of my depth, as I'm not 100% sure what `ClusterFirstWithHostNet` changes in the networking - from the name it seems like it would make the same decisions as ClusterFirst, just routed differently. The [k8s documentation](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy) isn't super clear on this.

I wasn't aware that the daemon, operator and preflight programmatically determine the etcd service IP - that would explain why the cilium agent itself was healthy, despite the CLI command failures.

**Comment by joestringer** [comment]
I realize this is a bit late, but etcd-operator is no longer supported by the upstream team (see https://github.com/coreos/etcd-operator) and so we have deprecated the options to configure it in Cilium for a few releases now. I don't know if this is still relevant to you, but I would suggest following the latest Cilium documentation on deploying Cilium with dedicated etcd instances or even using CRD mode rather than using `etcd.managed=true`.

**Comment by aanm** [comment]
This issue has not seen any activity since it was marked stale. Closing. Feel free to re-open a new issue if it is still persisting. Thank you.
