### ISSUE TITLE
BPF masquerading issue on bond0 device

### ISSUE THREAD

**Issue by geNAZt** [cilium/cilium#17195]
## Bug report

**General Information**

- Cilium version (run `cilium version`): 
```
cilium-cli: v0.8.6 compiled with go1.16.6 on darwin/amd64
cilium image (default): v1.10.3
cilium image (stable): v1.10.3
```
- Kernel version (run `uname -a`): 4.18.0-305.10.2.el8_4.x86_64
- Orchestration system version in use (e.g. `kubectl version`, ...): 1.22.1
- Generate and upload a system zip:
[cilium-sysdump-20210820-152443.zip](https://github.com/cilium/cilium/files/7021752/cilium-sysdump-20210820-152443.zip)

**How to reproduce the issue**

I have a problem with duplicate TCP SYN packets after masq. Cilium status looks like this:

```
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.22 (v1.22.1) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [bond0 10.175.2.8 (Direct Routing)]
Cilium:                 Ok   1.10.3 (v1.10.3-4145278)
NodeMonitor:            Listening for events on 72 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok
IPAM:                   IPv4: 7/62 allocated from 172.16.18.128/26,
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           BPF   [bond0]   172.16.18.128/26 [IPv4: Enabled, IPv6: Disabled]
Controller Status:      40/40 healthy
Proxy Status:           OK, ip 172.16.18.179, 0 redirects active on ports 10000-20000
Hubble:                 Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 6.43   Metrics: Ok
Encryption:             Disabled
Cluster health:         3/3 reachable   (2021-08-20T10:56:16Z)
```

I try to `wget http://google.com` from a busybox on that node which leads to a connection reset (cilium monitor):

```
-> stack flow 0x327043ff identity 9324->world state new ifindex 0 orig-ip 0.0.0.0: 172.16.18.133:48302 -> 172.217.16.78:80 tcp SYN
-> endpoint 101 flow 0x0 identity world->9324 state reply ifindex lxcc9722b79a843 orig-ip 172.217.16.78: 172.217.16.78:80 -> 172.16.18.133:48302 tcp ACK, RST
```

From a small wireshark dump i created on the host i can see that the masq packet has been duplicated for whatever reason:
![Screenshot 2021-08-20 at 13 03 30](https://user-images.githubusercontent.com/3252854/130240380-c9989b9c-e78a-4c0a-9397-d9f4927712e6.png)

**Comment by joulaud** [comment]
Your problem is not in the packet duplication which is related to how you take the trace (you probably trace with `-i any` or equivalent) and thus you see the same packet transiting on several internal Linux network interface. It is just that wireshark does not know that and flags the packet as a retransmission.
You can see in your capture that all packet are duplicated (DNS UDP too, even if as it is UDP wireshark does not flag them as such).

**Comment by pchaigno** [comment]
Summarizing the Slack discussion:

There is actually only one packet, but Wireshark sees it on three different interfaces. The TCP RST seem likely to be caused by a lack of masquerading. BPF masquerading is enabled on the bond0 device:
```
Masquerading:           BPF   [bond0]   172.16.18.128/26 [IPv4: Enabled, IPv6: Disabled]
```
But maybe there's an issue because of the bond device. Next step would be to check with the ens2f3 device, which is part of the bond. Tracing the connection at the destination would also help confirm that masquerading is the issue. Finally, testing with iptables-based masquerading could confirm this is an issue with the BPF-based masquerading.
