### ISSUE TITLE
command terminated with exit code 28

### ISSUE THREAD

**Issue by clcc2019** [cilium/cilium#17436]
![image](https://user-images.githubusercontent.com/46099295/133882482-ef4ba63b-674a-4499-9d2d-1d6d86fee26a.png)

**Comment by aanm** [comment]
Hello, thanks for opening the GH issue, please provide steps to reproduce the issue and a cilium sysdump otherwise the issue can't be fixed. Thank you.

**Comment by joestringer** [comment]
Can you also try with the latest Cilium CLI v0.9.1 or later? There was one known bug that can trigger problems with this particular test. More broadly though this test relies on connectivity from this cluster to the outside world, so if there is any potential for problems with that connectivity then that could be the root cause of this behaviour you observe.

**Comment by aanm** [comment]
This issue has not seen any activity since it was marked stale. Closing. Feel free to re-open a new issue if it is still persisting. Thank you.
