### ISSUE TITLE
Use `github.com/cilium/workerpool` inside Maglev M permutation computation

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#17572]
The Maglev [`getPermutation()`](https://github.com/cilium/cilium/blob/946ec4f2393fe0b16df53c5aeed2521d0c984ec9/pkg/maglev/maglev.go#L64) function implements its own logic to compute the permutations based on `runtime.NumCPU()`. However, after seeing this [commit](https://github.com/cilium/cilium/pull/17546/commits/0c1929f3656e5630ac6bc0f61d9cb955701b7bef), we can replace this with `github.com/cilium/workerpool`.

**Comment by lauchokyip** [comment]
Thanks! will start working on it soon 😃

**Comment by lauchokyip** [comment]
@pchaigno  Didn't have luck running cilium on minikube or kind... will unassign myself to give chances to others

**Comment by christarazi** [comment]
@h3llix Are you still working on this? Please remove your assignment if not.

**Comment by h3llix** [comment]
Hi Chris. Sorry, I was caught up with something else. I'll look on this in next 2 3 days. If I still get stuck. I'll just unassign myself.

**Comment by h3llix** [comment]
@christarazi Sorry, I am unassigning this myself. Took a long to respond but caught up on some work.

**Comment by kaworu** [comment]
@christarazi I have a working patch fixing this issue [here](https://gist.github.com/kaworu/248922a805d668bcb5ec5aa52ec7a92c), but I don't think it's worth the change.

`cilium/workerpool` is most useful for context cancelling propagation to the worker goroutines, error propagation from the worker goroutines, and long-running job with dynamic tasks count over time (because the workerpool launches a goroutine on-demand rather than maintaining a pool of goroutines always running). None of theses properties are useful to `getPermutation()`, and so I feel like the patch only adds "noise" by ignoring the errors and context.

If you agree then let's close this issue, otherwise I'll be happy to open a PR with the patch linked above.

**Comment by christarazi** [comment]
@kaworu The way I see it is we've created `cilium/workerpool` to solve this general problem so that we don't have to re-solve it every time we want to limit workers in our code bases. If there's return values that we don't care about or extra knobs like context cancellation that the lib supports, then we simply don't have to use it and that's supported by the lib anyway.

I see this as a cleanup to consolidate our code on a single approach to a general problem. So might as well.
