### ISSUE TITLE
CEPs might be kept for unmanaged pods

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#17631]
Under certain conditions a CEP can be kept for unmanaged pods. This can happen, for example, in case Cilium stops running and the infra container of a pod is restarted on a node where another CNI besides Cilium starts managing it.

The GC of the CEP will not happen because a) the `ownerReference` of the CEP is the same since the pod is the same and b) Cilium Operator is only GC CEPs if the pod does not exist, which is also not the case. Both a) and b) are not sufficient as the only field that changed from the pod status was the pod IP.

There are two potential fixes for this

1. Watch for CEPs, which we already do under [1] and mark for deletion CEPs that are not running on the cilium agent. We can't delete them immediately since during the restore process the local agent will only start restoring the local endpoints after all state is synchronized with Kubernetes [2]. Thus, the CEPs can only be deleted after the endpoint restoration.

2. Verify if the IP addresses of the pod and the CEP are the same, if they are not, mark the CEP for deletion. This process can be executed from the cilium-operator. Similarly to case 1., we shouldn't delete the CEPs immediately at the risk of an endpoint having its IP address changed by a restart of the infra container where Cilium would be the CNI managing the pod. Cilium would likely re-create the CEP with the same name and the most up to date IP address but the IP address of the Pod Status might take a couple more seconds to be updated. If we delay the CEP deletion for maybe 1 minute we could guarantee the IP address of the Pod would be up to date and the CEP deletion would not happen unnecessarily.

[1] https://github.com/cilium/cilium/blob/63c0b29787e6743b2c7626782a7090272764e487/pkg/k8s/watchers/cilium_endpoint.go#L39-L47 

[2] https://github.com/cilium/cilium/blob/54fdf6ee745a3e8ad51b6d81034c7a628a517a4f/daemon/cmd/daemon_main.go#L1621-L1627

**Comment by tommyp1ckles** [comment]
Going to throw a summary some of my findings into this thread as there's a lot of potential ways that a CEP can get into a "stale" state.

From the customer-issue/Slack threads. It seems like there's a few different issues going on here.

1. Pods somehow un-managed, while retaining their CEP. One way that this can happen (i.e. I reproduced by) if the /etc/cni... Cilium config files get removed and the Node is restarted and loses its Cilium bpf state. In this case the same Pod might get re-sandboxed with another CNI (i.e. if the containers have to be restarted). At this point you'll have a Pod with a CEP but no endpoint in the endpoint manager. In this situation the CEP IP and actual Pod IP are likely to differ since the Pod has been restarted under a different CNI. As mentioned, Controller will not GC as the Pod.UUID and owner reference have not changed.

2. Pod becomes un-managed due to lost state. This can happen if the bpf state gets deleted for an endpoint. Once you restart the Cilium pod, upon restore the existing endpoint will not be restored. But, the Pod is still running with all the Cilium state still intact. 

3. *** Endpoint state is wrong and is synced to CEP. I'm not sure how this could happen organically. I was able to force this by decoding/modifying/recoding the `ep_headers.h` b64 data. If you restore from this you're going to get an Endpoint/CEP that are not consistent with the actual Pod. The CEP will become consistent with the Endpoint due to endpoint sync but PodIP will not.

_Other thoughts_, I spent a lot of time thinking up weird states that Endpoints/Pods/CEPs can get into. I don't think we can necessarily resolve all these situations. But I think in the future we could add better validation on the Agent side to report when things look like their in some unresolvable state. For example:
* Pod running Cilium endpoint programs etc but not being restored/managed by Cilium. In this case, the changes in my PR will cause the agent to delete the CEP but the Pod will continue to run on in a limbo state. We could probably check if this is the case and warn when this happens.
