### ISSUE TITLE
IPAM Chaining mode for ipvlan interface

### ISSUE THREAD

**Issue by yash97** [cilium/cilium#17955]
Description:
Right now cilium has chaining mode available for veth interface and for specific CNIs. There is no generalized mode available to chain Cilium with IPVLAN based IPAM.

**Comment by qmonnet** [comment]
Hi and thank you for the report. Note that IPVLAN is [getting deprecated](https://github.com/cilium/cilium/pull/17993/commits/1fb2dbb3293a962f7f7358eacb527e12afd86c31) in v1.11 (to be removed in v1.12), so this feature is unlikely to be implemented.

**Comment by joestringer** [comment]
I think that this is quite difficult to achieve, and has some security pitfalls if implementing this logic at the packet layer, because there is no dedicated network device outside the pod's namespace. This means that the pod can potentially have access to any sort of configurations that Cilium may apply at the device level to such IPVLAN interfaces (and worst case, remove that logic).

Which IPVLAN-based CNI are you interested in integrating Cilium with? Have you considered trying a Cilium-only approach rather than combining CNIs? Some of the recent performance improvements that the Cilium team have implemented for veth-based devices have now closed the performance gap with IPVLAN, see [this blog post](https://cilium.io/blog/2021/05/20/cilium-110#performance) for more details. Operationally it will be simpler to run & diagnose issues with your CNI if there is only one in place rather than two different CNIs that are each responsible for a subset of the networking behaviour.

**Comment by brb** [comment]
This is going to be resolved by https://github.com/cilium/cilium/pull/14436.
