### ISSUE TITLE
Maglev list no longer seems to work

### ISSUE THREAD

**Issue by joamaki** [cilium/cilium#18037]
With v1.11.0-rc3 version of Cilium the "lb maglev list" command no longer works:
```
root@demo-load-balancer:~# docker exec cilium-agent cilium bpf lb maglev list
Error: Cannot initialize maglev maps: cannot determine v6 outer maglev map's table size
```

Potential regression from https://github.com/cilium/cilium/commit/789eef0d148d0aa590d2a1b2da7fd69da6dafc47?

**Comment by oblazek** [comment]
Just run into the same issue. In my case I added only IPv4 service (as frontend) and that caused v6 outer map to be empty. Interested to know why we have these checks https://github.com/cilium/cilium/blob/789eef0d148d0aa590d2a1b2da7fd69da6dafc47/pkg/maps/lbmap/maglev.go#L79-L85
since if I remove them I can correctly get the desired output:
```
# cilium bpf lb maglev list
SVC ID   LOOKUP TABLE
1        [4 2 4 2 2 4 2 4 2 2 4 2 4 2 2 2 2 4]
```
