### ISSUE TITLE
Cilium upgrade with --reuse-values causes Helm to segfault

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#18115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In a kind environment, run:

```
$ helm install cilium cilium/cilium --version 1.10.5 --namespace kube-system
NAME: cilium
LAST DEPLOYED: Fri Dec  3 10:15:36 2021
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
You have successfully installed Cilium with Hubble.

Your release version is 1.10.5.

For any further help, visit https://docs.cilium.io/en/v1.10/gettinghelp
$ helm upgrade -n kube-system cilium cilium/cilium --version 1.11.0-rc3 --reuse-values --set upgradeCompatibility=1.10
Error: failed to download "cilium/cilium" at version "1.11.0-rc3"
$ helm upgrade -n kube-system cilium cilium/cilium --version 1.11.0-rc3 --reuse-values --set upgradeCompatibility=1.10
Error: UPGRADE FAILED: template: cilium/templates/hubble/tls-helm/server-secret.yaml:5:12: executing "cilium/templates/hubble/tls-helm/server-secret.yaml" at <prepend .Values.hubble.tls.server.extraDnsNames $cn>: error calling prepend: runtime error: invalid memory address or nil pointer dereference
```

The `--reuse-values` argument here means that the `.Values.hubble.tls.server.extraDnsNames` value does not have the default value from the v1.11.0-rc3 chart's values file, which then causes a runtime error in Helm.

Removing the `--reuse-values` argument resolves this problem, however it also requires the user to specify all of the options from `helm inspect values` or otherwise the resulting install may not carry over the correct settings.

### Cilium Version

v1.11.0-rc3

### Kernel Version

Any

### Kubernetes Version

Any

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

Reported-by: @seanmwinn

**Comment by joestringer** [comment]
This seems to be at least partially introduced by PR #17238 (cc @dungdm93).

**Comment by gandro** [comment]
Oh, I didn't see this issue until the community meeting today. I did some experimenting as well, and I don't think we ever supported `--reuse-values`, depending on the values used, `--reuse-values` also breaks in v1.9 to v1.10 upgrades.

The main problem is that `--reuse-values` does _not_ include any default values of the new release. This then causes various Helm expressions to fail (the ones introduced in #17238 are not the only ones, e.g. `hostFirewall` and `externalWorkload` related expressions also seem affected in v1.11)

Unfortunately, supporting `--reuse-values` seems pretty difficult in complex charts such as ours. Expressions like `.Values.foo.bar.baz` cannot be used directly, because we would have assume `foo` or `foo.bar` value don't exist in previous releases and thus any use would have to be surrounded with checks.
Additionally, all default values would need to be duplicated, i.e. once in the `values.yaml` (which we use to generate the values doc) and once in the template in case the new release values weren't loaded due to `--reuse-values`.

I opened a PR to document this caveat and a recommended workaround: https://github.com/cilium/cilium/pull/18259
