### ISSUE TITLE
Use UUID generation to allow correlating logs for same request

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#1812]
- [ ] Integrate with a UUID library such as https://github.com/satori/go.uuid. NodeID must be set correctly.
- [ ] Generate (timetamp based?) UUID for:
  - [ ] Endpoints

**Comment by ianvernon** [comment]
This is a great idea, and will help improve debugging significantly.

**Comment by raybejjani** [comment]
From what I've seen of the code so far, and a brief chat with aanm it seems like this change will require a bunch of refactoring to pass around some kind of context (the uuid itself or some other container object). The other schemes I can imagine are:
1- The sources of the uuids implement an interface that can present the UUID on demand, and then we pass the object onto all dependent calls down the stack.
2- We do some magic similar to Ruby's LSpace (https://github.com/ConradIrwin/lspace) which I've observed turn into a complicated mess in the past :/

Naively, I'm leaning towards (1) because it might be the most natural change. More importantly, as a longer term thing, it allows us to track the provenance of a UUID. This would be handy for transient things like an Endpoint Build, and would be similar in concept to spans used in tracing frameworks. This isn't too useful for this ticket but the scenarios I'd like to handle are something like:
Why did this Endpoint build trigger?
Build UUID connects to an event UUID connects to a policy change action by a user.
Build UUID connects to the 5-minutely regeneration of all Endpoints goroutine that has it's own UUID.

I'll report back here before I commit to something but if anyone has any thoughts let me know :)

**Comment by tgraf** [comment]
> Naively, I'm leaning towards (1) because it might be the most natural change. More importantly, as a longer term thing, it allows us to track the provenance of a UUID.

Agreed. This could be a `LoggableObject` interface which needs to provide a per object UUID

> This isn't too useful for this ticket but the scenarios I'd like to handle are something like:
> Why did this Endpoint build trigger?
> Build UUID connects to an event UUID connects to a policy change action by a user.
> Build UUID connects to the 5-minutely regeneration of all Endpoints goroutine that has it's own UUID.

Agreed. I thought about this too. Cilium is very much event triggered which then result in chain reactions in various subsystems. Being able to trace back a failure to the original event will be essential. Fortunately, the complexity is somewhat limited. We could do something relatively simple such as ensuring that as we pass over to another object, we log a standardized 'triggeredBy` field which contains the UUID of the original event, e.g.

```
=> containerd event, uuid=1111
=> "policy regeneration", uuid=2222, triggeredBy=1111
=> "endpoint regeneration", uuid=3333, triggeredBy=2222
```

We should probably considering adding "context" to all major functions so we can pass around the stack of uuids and dump it as required.
