### ISSUE TITLE
Configuration schema for automated tooling

### ISSUE THREAD

**Issue by briantopping** [cilium/cilium#18149]
## Proposal / RFE

Cilium configuration is currently based on an implicit schema of key-value pairs. The documentation is well-maintained and users can also look for keys in [`config.go`](https://github.com/cilium/cilium/blob/master/pkg/option/config.go). The keys are are also exposed to some degree in [`openapi.yaml`](https://github.com/cilium/cilium/blob/master/api/v1/openapi.yaml), generating a REST API for queries.

When Cilium is wrapped by a provider such as Gardener's [Cilium Network Provider](https://github.com/gardener/gardener-extension-networking-cilium), key mapping is fraught. There's no way for the provider to consume various versions of Cilium and accurately expose the Cilium options of the chosen version out to users. 

**Describe the solution you'd like**

Ideally, Cilium configuration option parsing code would be generated from a schema. That schema could be ingested by providers that wrap Cilium at build time and generate similar stubs in their own build. In turn, the provider could parse and map the full range of values for a Cilium version without manual transcription. ([This code](https://github.com/gardener/gardener-extension-networking-cilium/blob/master/pkg/apis/cilium/v1alpha1/types_network.go) shows that the options mapping is woefully inadequate for many needs at present.)

Issue in Gardener is tracked [here](https://github.com/gardener/gardener-extension-networking-cilium/issues/74). Thanks for your consideration and feedback!

**Comment by joestringer** [comment]
In principle I'm open to this idea if it helps providers to interface with Cilium more easily.

I think that one of the struggles here is that Cilium has many options; arguably too many - but this is because we put a fairly heavy emphasis on feature flags and partitioning logic behind those flags. This makes it possible to enable/disable some logic depending on the maturity of the functionality or even if it turns out that the feature causes some issue at runtime.

Ideally I would like for Cilium configuration on average to mainly involve a very small number of basic environment questions, such as what kind of connectivity you want (direct routing / vxlan / geneve), whether you will run kube-proxy alongside Cilium or not, perhaps the primary target kernel version so that we could automatically set a standard set of features. Then if you want something more complicated then you can start to get more involved in the configurations or figure out what base platform assumptions you can change in order to get the features you want. This is the way that the https://github.com/cilium/cilium-cli has gone, so we just autodetect the "best" configuration for your environment and just set those settings. If you need something special then you must take dedicated steps to enable the functionality that is not there by default. I guess the argument from this perspective is that Cilium could dynamically support the configuration or features you want through dedicated configurations (perhaps even new CRDs) instead of enabling/disabling feature flags. If the basics of Cilium configuration are fairly minimal, then a schema may not be necessary for configuration providers.

That said, I think that if there was a fairly lean way to consistently define the configuration schema and e.g. generate the `pkg/option`, `install/kubernetes/cilium/templates/cilium-configmap.yaml` and maybe even commandline flags, and that schema then provides a convenient integration point for providers, then that seems like a reasonable proposal. Hard to say what this would look like without a concrete example, but could be considered.

**Comment by briantopping** [comment]
Hi Joe, happy new year! Hope yours is off to a great start.

Thanks for the thoughtful response on this. I did not know about cilium-cli.  I think you captured most of what I'm writing below, would like to elaborate on it.

If we consider these "best configurations" as "strategies" that the Cilium team recognizes and captures in their intensive and intimate use, exposing those strategies for clients such as Gardener or GKE Dataplane v2 to select from could be far more powerful than the client binding every flag for every version. For instance, if a strategy was selected by identifier and a flag was removed or renamed in an upgrade, the client would continue to behave correctly if as long as the identified strategy still existed in the new version.

It might also be a good thing that strategies were agnostic to source (to your point about a new CRD), for instance if the Gardener team or local administrator wanted to specify an optimized strategy as default. The documentation of these strategies alone would be an exceptionally powerful means to convey usage of flags through compare and contrast of published strategies. This might cause cilium-cli to simply be a presenter of strategies as well.

Procedurally, if the strategy CRD had a version range for Cilium, Cilium could reject strategies that were outside the range. This is isn't intended to be secure, it's a feature that a user could simply widen the version range and resubmit. But such a user would be "on notice" that they are taking local responsibility for the potentially outdated strategy. An alternate implementation would have a map of configuration options within a strategy, keyed by version range. This would provide simpler strategy evolution as maintainers would not be required to thread the needle with configurations and users would not have to search far and wide for a strategy version that fit their deployment. 

One of the things that came to light in the linked issue above is that of security. Gardener can manage hundreds of clusters with no problem, but Cilium might present a means for a rogue child CNI configuration to allow MITM or other attack vectors in the parent deployment. Signed strategies would resolve this. Presumably Cilium would need to be launched with a flag that included acceptable signer certificates and reject strategies that were not appropriately signed. For instance in GKE Dataplane v2, a selection of signed strategies (possibly even generated by Google PSO and signed by network operations) could allow some customer flexibility without creating a security issue for other GKE customers on the same physical hosts.

If for this last feature alone, packaging configuration in a signed object could be incredibly useful.

**Comment by joestringer** [comment]
Happy new year to you as well, wishing you the best for 2022 :partying_face: 

> One of the things that came to light in the linked issue above is that of security. Gardener and GKE can manage hundreds of clusters with no problem, but Cilium might present a means for a rogue child CNI configuration to allow MITM or other attack vectors in the parent deployment. Signed strategies would resolve this. Presumably Cilium would need to be launched with a flag that included acceptable signer certificates and reject strategies that were not appropriately signed. For instance in GKE Dataplane v2, a selection of signed strategies (possibly even generated by Google PSO and signed by network operations via an internal workflow) could allow additional customer flexibility without creating a security issue for other GKE customers on the same physical hosts.

I'd like to unpack this a little bit more, just to uncover the assumptions here so that we can highlight and avoid any sort of adverse security implications here. Are we assuming first that there is a configuration CRD for Cilium that Gardener or other tooling could configure? Then the concern is whether unauthorized actors could manipulate these settings, thereby bypassing the higher level tooling and subverting the configurations? In this case, the most obvious solution to me is proper RBAC. Arbitrary users should not be able to manipulate the network plugin's configuration in any typical deployment, exactly because of this type of problem.

Depending on the security model of your organization, I could see that perhaps you may wish to be able to additionally validate the source of any sort of configuration, so that in the case that an adversary does gain RBAC access, there could be another layer of protection against unauthorized reconfiguration. Is that what you have in mind? Are there similar mechanisms elsewhere in the Kubernetes ecosystem for such configuration?

**Comment by briantopping** [comment]
I think the ideal solution is a bit more subtle than RBAC, although I agree that it could handle many of the cases. It's also possible for the UI to expose verifiably non-harmful switches workload cluster creators may tweak to enable various Cilium features, but the lag for those switches is often a year or more. 

How can workload cluster creators in a hyperscaler get ahold of advanced Cilium features in an organizationally safe manner that isn't beholden to UI development and testing lag? 

This is where the idea of signing comes in. RBAC can restrict who can apply a configuration to a cluster, but it can't stop someone with permissions who doesn't know what they are applying is harmful. Network security is qualified to make that decision, but usually not the one creating workload clusters.

The only alternative I can think of is using Gitops to apply configuration and putting repository rules on CNI configuration items to automatically add network security reviewers on change. Gitops on infrastructure is pretty rare with small orgs, but it might also be true that organizations that aren't big enough for it have bigger problems than someone applying rogue configuration.
