### ISSUE TITLE
ArgoCD Out-of-sync issues for hubble-generate-certs

### ISSUE THREAD

**Issue by henriknj** [cilium/cilium#18298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Deploying Cilium using the helm chart will generate a hubble-generate-certs cronjob and an also a job used for creating the initial certs. However, the job has **ttlSecondsAfterFinished** defined, so the job resource and associated pods will be purged after 30mins. The cilium chart will eventually (after 30mins) be "out of sync", as the job resource will be missing.

Could we maybe add/change something to make the helm chart work seamlessly with git-ops tools?

### Cilium Version

v1.10.5

### Kernel Version

5.4.156

### Kubernetes Version

1.21

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
Thanks for the report. I'm not sure I understand the bug report. The `hubble-generate-certs` simply creates a few certificates as Kubernetes secrets. These secrets will remain in the cluster even after the job has been purged.
In addition, there is also a CronJob with the same name which will re-generate the certificates regularly to ensure the secrets are not out of sync.

Could you clarify a bit more what problem you are experiencing with the certificates?

**Comment by henriknj** [comment]
@gandro They indeed stay and it is not the certificates that are the issue here, but the fact that the job resource that creates them is removed after 30mins - causing ArgoCD to become out of sync since it tries to ensure that the cluster and the output of e.g. this helm is in sync.

So as I might have alluded to this is not really a bug in the helm chart but rather a git-ops interoperability issue.

**Comment by gandro** [comment]
Thanks for the clarification. I'm not very familiar with ArgoCD. I am honestly a bit surprised by that behavior. A job is an ephemerial object after all. As the Kubernetes docs say, [keeping it around will in the system will put pressure on the API server](https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically), and especially pods created via `CronJob` ideally should be garbage collected, as otherwise you end up with an unbounded number of completed pods (unless ArgoCD garbage collects them somehow itself).

But again, I'm not familiar with ArgoCD. If there is no way to solve this on the ArgoCD side (i.e. by telling it to ignore jobs), I'm not opposed to a PR which removes the `ttlSecondsAfterFinished` field from the job spec if `certgen.ttlSecondsAfterFinished` is set to `nil`. As a consequence, pods created by the `Job` will stick around forever.

**Comment by gandro** [comment]
An alternative git-ops friendly solution might be to use `cert-manager` to generate the certificates in question: https://docs.cilium.io/en/v1.11/concepts/observability/hubble-configuration/#auto-generated-certificates-via-cert-manager (support in our charts was added in v1.11)

**Comment by steven166** [comment]
An empty string did the trick to make ArgoCD happy:
```yaml
certgen:
  ttlSecondsAfterFinished: ''
```

**Comment by henriknj** [comment]
@steven166 The empty string did the trick, but this will as @gandro said, leave pods around forever.. :\

**Comment by aanm** [comment]
@henriknj @steven166 please see if the solution on https://github.com/cilium/cilium/issues/17349 helps. Thank you
