### ISSUE TITLE
Consider refactoring IPCache to be a priority queue based on source

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#18301]
## Background

Today the IPCache is a pretty fundamental data structure for Cilium. The IPCache attempts to stitch together all of the identity information from different sources, i.e. which labels should be associated with an IP, however the callers must resolve conflicts between these different sources of information. This complicates the calling logic, because every calling case must consider all the other calling cases. 

Example: Pod IP is associated with a set of labels and the same IP is selected by a CIDR policy, then the IP can only map to one identity, whereas it can map to a priority queue of 2 identities, with the "active" identity being the highest priority. When the "active" identity is released, then the mapping will point to the next identity in the queue without having explicit code to perform this transition.

With the addition of the kube-apiserver policy matching feature, we've added another layer (metadata) which actually complicates ipcache handing even further.

## Proposal / RFE

* Convert the value of the map (`ipToIdentityCache`) from flat value of `ipcache.Identity` to priority queue of the same type (based on identity source). 
* Then convert the map key type to a stronger type, instead of string, because we resolve the Pod IP and CIDR range case.
  * We might have to reconsider the actual sources themselves, specifically whether we need a new source such as "Pod" for the above

Reported-by: Joe Stringer <joe@cilium.io>

**Comment by joestringer** [comment]
This may allow us to simplify some of the caller code from how it handles `ErrOverwrite` errors too, because the ipcache would resolve the conflicts.

**Comment by joestringer** [comment]
I think that with our latest design laid out in #21142, we will be able to merge multiple pieces of information into individual ipcache entries in the core types conflict resolution logic. It is likely that we will still have a conflict between Pod Identities and other information (eg labels associated with specific IPs), so then there will likely still be a two-tier identity selection logic built into the ipcache, but I don't think that we will need to form this as a priority queue of identities as was proposed in this issue.

So far I've primarily been using this issue as the way to track this work, but I think that it will be more accurate to use #21142 going forward. 

From the goals:

> Convert the value of the map (ipToIdentityCache) from flat value of ipcache.Identity to priority queue of the same type (based on identity source).

The current proposal is not a priorityqueue, but I think it solves the problems that this issue was planning to solve. No longer applicable.

> Then convert the map key type to a stronger type, instead of string, because we resolve the Pod IP and CIDR range case.

The initial form of this in the new ipcache API is already achieved in the current outstanding PRs, then to complete the process we just need to switch all callers over to the new API to use the new types. :+1: 

@christarazi So I think we should be good to close this out in favour of #21142 for tracking?

**Comment by christarazi** [comment]
Sounds good, closing in favor of https://github.com/cilium/cilium/issues/21142.
