### ISSUE TITLE
Can any one explain how would i use Project Cilium for CNI in my nomad cluster

### ISSUE THREAD

**Issue by codesiddhant** [cilium/cilium#18334]
Reference -> [https://www.hashicorp.com/blog/multi-interface-networking-and-cni-plugins-in-nomad-0-12](https://www.hashicorp.com/blog/multi-interface-networking-and-cni-plugins-in-nomad-0-12)

![image](https://user-images.githubusercontent.com/54833015/147346381-0d03d39b-7e7f-42b3-9efe-b96f24332332.png)

**My Problem** -> I want to connect all My containers across multiple clients(Nodes) in the nomad cluster. In my current Kubernetes cluster, all pods can communicate to each other based on IP address no matter they are deployed in different machines (worker) using CNI ( Cilium / Calico  / Funnel, etc).

The same thing I want to achieve in Nomad Cluster not only for docker containers but other plugins also including firecracker, qemu, etc.

**What I want** ->  All Resources (Container, MicroVm, Vms) should be able to communicate with each other based on IP Addresses under the same subnet across the entire cluster| Simply speaking I want SDN Solution in my cluster. 

**What I am trying to do** actually I trying to make my own private cloud that can support multiple types of technology including docker, microVM, LXC/LXD container, and KVM as like [Opennebula](https://opennebula.io/discover/). with the help of the Nomad cluster. 

**how will I be able to access instances (VMs)**  for accessing VMS through (SSH/VNC/RDP) with the help of open-source tool [Apache Guacamole](https://guacamole.apache.org/) but the condition is that every VM should be able to communicate with each other to make **Guacd proxy**  work possible.  

**What is my expectation** I am wondering how will one can use Cilium as CNI in the nomad cluster. I searched the entire internet but still didn't find any conclusive. 

There is mention of Cilium in nomad official documentation ([Blog](https://www.hashicorp.com/blog/multi-interface-networking-and-cni-plugins-in-nomad-0-12)) but I want a more detailed explanation about that. 

Please someone help me out with this including all alternative possibilities.
Billion thanks in advance :innocent:

**Comment by joestringer** [comment]
Interesting question, thanks for raising an issue on this. We've had a few people stop by in Slack asking about the same time in the past, so it's good to have a dedicated issue on GitHub to point to. I'll see if I can dig up and summarize my previous answers to other individuals. As far as I'm aware, no-one has put together a guide for this so far, but in principle it should be possible if you are particularly interested in attempting it. I will naturally warn you that the project has spent a lot more time on streamlining the experience with Kubernetes, so this will require some dedicated effort to get somewhere :-)

Broadly speaking, Cilium consists of a few components which are described in the documentation [here](https://docs.cilium.io/en/stable/concepts/overview/). For Nomad, the important parts will be Cilium-Agent, Cilium-Operator, Cilium-CNI and the datastore for sharing state in the cluster (etcd).

Typically Cilium provides docker container images for the cilium-agent and cilium-operator components. Kubernetes makes it easy to deploy these via YAML configurations, but I'm going to assume that Nomad doesn't provide compatible scheduling for these components. So at least one of the steps to achieve this would be to find a way to run the cilium-agent with the appropriate privileges on each node, plus run at least one cilium-operator somewhere in the cluster. If it's possible to run these as privileged docker containers, then this is likely the simplest possible option given that this is the primary distribution method that the Cilium project uses for providing binaries.

In addition to this, for each of those cilium-agent and cilium-operator components to coordinate with the others in the cluster, they will all need access to a shared datastore. Cilium supports etcd as a kvstore backend, so you would need to provision an etcd cluster and point these components towards etcd. Example configurations are described in the docs [here](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-external-etcd/#admin-install-daemonset), but again it's dependent on the k8s-style YAML configurations. In principle it ends up effectively passing a set of arguments to the agent and operator processes, but the exact parameters are subtly different from the format on that page. You can use the Command Reference to find the actual flags for each of the components.

Finally, there is the `cilium-cni` binary itself. In a standard Cilium install, the YAMLs will provision this binary onto each node and configure the CNI configuration so that kubelet will call this CNI binary, and then this CNI binary then relay requests to configure the networking from the node scheduler towards the Cilium agent API for the agent on that same node (via unix socket). So you would need to place that binary onto each node, and set up the configuration (per Nomad instructions) correctly as well. You should be able to pull the binary out of the `quay.io/cilium/cilium` docker image.

**Comment by monwolf** [comment]
Hi @codesiddhant, I'm interested in know if you have started with this setup.

**Comment by AlekseyMelikov** [comment]
@joestringer thanks for such a detailed answer. Tell me please, as far as I understand, the cilium supports work with the consul. In your post, you talk about running cilium with etcd. Is it possible to use consul instead of etcd? Or are there any restrictions when running cilium with the consul?

**Comment by jrandall** [comment]
I found old documentation for Cilium 1.9 that gives an example of how to run Cilium outside of Kubernetes, which is a helpful place to start when looking into running Cilium with Nomad: https://docs.cilium.io/en/v1.9/gettingstarted/docker/

Most of the detail of interest are in the (now removed) example for getting started using Vagrant and docker-compose (which actually spins up a consul cluster to serve as the kvstore):
 - https://github.com/cilium/cilium/blob/v1.9.12/examples/getting-started/Vagrantfile
 - https://github.com/cilium/cilium/blob/v1.9.12/examples/getting-started/docker-compose.yml

See also: https://github.com/cilium/cilium/issues/13072

**Comment by monwolf** [comment]
@jrandall @AlekseyMelikov @codesiddhant  I started putting all the pieces together for the v1.9.12. I got stuck in the nomad integration of the cni config plugin (https://github.com/hashicorp/nomad/issues/12120
). 

The problem I found in the config file provided for the cni-plugin is not what nomad expect, nomad wants the cni conf to have the key "plugins: []".

**Comment by zhujinhe** [comment]
Look forward to a detailed tutorial or best practices.

**Comment by xmulligan** [comment]
There is an OSS project for this now https://cosmonic.com/blog/engineering/netreap-a-practical-guide-to-running-cilium-in-nomad/

**Comment by aojea** [comment]
> There is an OSS project for this now https://cosmonic.com/blog/engineering/netreap-a-practical-guide-to-running-cilium-in-nomad/

@xmulligan how hashicorp license change to BLS impact this ?
 https://www.hashicorp.com/license-faq#What-products-will-be-covered-by-BSL-1.1-in-their-next-release

**Comment by xmulligan** [comment]
I would reach out to Cosmonic what they are thinking about this since it is their project and Cilium doesn't actually use Nomad

**Comment by aojea** [comment]
> I would reach out to Cosmonic what they are thinking about this since it is their project and Cilium doesn't actually use Nomad

thanks @xmulligan , FYI this is the umbrella issue on cncf to understand the implications on the hosted projects https://github.com/cncf/foundation/issues
