### ISSUE TITLE
DNS proxy swallows DNS response when a default-deny ingress NetworkPolicy is present

### ISSUE THREAD

**Issue by jamesharr** [cilium/cilium#18373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When a default-deny ingress policy is applied to a namespace and dns proxying is enabled for a workload, DNS responses don't make it back to a pod and hubble shows an ERROR in a DNS response.

### Kubernetes Environment
* K3s (latest) on AlmaLinux 8.5. It's mostly a stock install, apart from a dedicated control node.
  * *Update*: reproduced on Kernels 5.4 and 5.10 (see comment for details)
  * *Update*: reproduced on Ubuntu 20.04, cloud-image
* Cilium v1.11.0 and v1.10.6 (installed via downgrade) seem to both exhibit the behavior
* Cluster setup notes: [K3s-Cilium-Setup.md](https://github.com/cilium/cilium/files/7809923/K3s-Cilium-Setup.md)

### Description of environment to recreate issue
* A single POD to run DNS queries on, this is using a customized Ubuntu image with dig installed, but any image will do.
* A single default-deny ingress NetworkPolicy
* A CiliumNetworkPolicy with a DNS rule enabled

### Reproduction steps
```
kubectl create ns test-ns
kubectl -n test-ns apply -f dns-return-test.yml
kubectl -n test-ns exec dns-client -- dig example.com
hubble -n test-ns observe --since 5m

# teardown
kubectl -n test-ns delete -f dns-return-test.yml
kubectl delete ns test-ns 
```
Manifest(s) used: [dns-return-traffic.yml](https://github.com/cilium/cilium/files/7810064/dns-return-traffic.yml.txt)

### Current work-arounds:
* Enable A policy to allow return-traffic from kube-system (and therefor kube-dns). This is the `NetworkPolicy/dns-return-hack` object commented out at the end of the manifest.
* Disable rules.dns.matchPattern, which would prevent any FQDN-based policy from working

### Cilium Version

% cilium version
cilium-cli: v0.10.0 compiled with go1.17.4 on darwin/amd64
cilium image (default): v1.11.0
cilium image (stable): v1.11.0
cilium image (running): v1.10.6

### Kernel Version

% ssh k3s-worker1 uname -a
Linux k3s-worker1.local 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 15 09:17:08 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

% kubectl  version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5+k3s1", GitCommit:"405bf79da97831749733ad99842da638c8ee4802", GitTreeState:"clean", BuildDate:"2021-12-18T00:43:30Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20220104-134353.zip](https://github.com/cilium/cilium/files/7810033/cilium-sysdump-20220104-134353.zip)

### Relevant log output

```shell
% kubectl -n test-ns exec dns-client -- dig example.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> example.com
;; global options: +cmd
;; connection timed out; no servers could be reached
command terminated with exit code 9
Command failed 9

% hubble -n test-ns observe --since 5m

Jan  4 19:37:03.167: test-ns/dns-client:44004 -> kube-system/coredns-85cb69466-2ff7k:53 dns-request FORWARDED (DNS Query example.com. A)
Jan  4 19:37:03.167: test-ns/dns-client:44004 -> kube-system/coredns-85cb69466-2ff7k:53 L3-L4 REDIRECTED (UDP)
Jan  4 19:37:03.167: test-ns/dns-client:44004 -> kube-system/coredns-85cb69466-2ff7k:53 to-proxy FORWARDED (UDP)
Jan  4 19:37:03.183: test-ns/dns-client:44004 <- kube-system/coredns-85cb69466-2ff7k:53 dns-response FORWARDED (DNS Answer "93.184.216.34" TTL: 30 (Proxy example.com. A))
Jan  4 19:37:03.183: test-ns/dns-client:44004 <- kube-system/coredns-85cb69466-2ff7k:53 dns-response ERROR (DNS Answer "93.184.216.34" TTL: 30 (Proxy example.com. A))
Jan  4 19:37:08.166: test-ns/dns-client:44004 -> kube-system/coredns-85cb69466-2ff7k:53 to-proxy FORWARDED (UDP)
Jan  4 19:37:08.167: test-ns/dns-client:44004 -> kube-system/coredns-85cb69466-2ff7k:53 dns-request FORWARDED (DNS Query example.com. A)
Jan  4 19:37:08.167: test-ns/dns-client:44004 <- kube-system/coredns-85cb69466-2ff7k:53 dns-response FORWARDED (DNS Answer "93.184.216.34" TTL: 26 (Proxy example.com. A))
Jan  4 19:37:08.167: test-ns/dns-client:44004 <- kube-system/coredns-85cb69466-2ff7k:53 dns-response ERROR (DNS Answer "93.184.216.34" TTL: 26 (Proxy example.com. A))
Jan  4 19:37:13.166: test-ns/dns-client:44004 -> kube-system/coredns-85cb69466-2ff7k:53 to-proxy FORWARDED (UDP)
Jan  4 19:37:13.167: test-ns/dns-client:44004 -> kube-system/coredns-85cb69466-2ff7k:53 dns-request FORWARDED (DNS Query example.com. A)
Jan  4 19:37:13.167: test-ns/dns-client:44004 <- kube-system/coredns-85cb69466-2ff7k:53 dns-response FORWARDED (DNS Answer "93.184.216.34" TTL: 21 (Proxy example.com. A))
Jan  4 19:37:13.167: test-ns/dns-client:44004 <- kube-system/coredns-85cb69466-2ff7k:53 dns-response ERROR (DNS Answer "93.184.216.34" TTL: 21 (Proxy example.com. A))
```

### Anything else?

* [Slack conversation w/ @joestringer](https://cilium.slack.com/archives/C01JALNQAR1/p1640218007436000)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
One datapoint, I attempted to reproduce this locally using kind (v0.11.0) and Cilium v1.11.0 in an Ubuntu 20.04.3 (Linux 5.10) environment, and I did not observe the `dns response ERROR`, plus the DNS requests and the actual policy seemed to all work correctly. This suggests that there may be something specific to either k3s or AlmaLinux that is causing the issue.

**Comment by jamesharr** [comment]
A few data-points:
* reproduced regardless of whether kube-dns (provided by coredns) is on the same node or different node.
* reproduced on kernel 5.15.12-1.el8.elrepo.x86_64 (kernel-ml package in elrepo, [installation instructions](https://www.how2shout.com/linux/how-to-install-linux-kernel-5-x-on-almalinux-8-or-rocky/))
* reproduced on kernel 5.4.169-1.el8.elrepo.x86_64 (kernel-lt package in elrepo, [installation instructions](https://www.how2shout.com/linux/how-to-install-linux-kernel-5-x-on-almalinux-8-or-rocky/))

My `/etc/resolv.conf`:
```
% ssh k3s-worker1 cat /etc/resolv.conf
; Created by cloud-init on instance boot automatically, do not edit.
;
nameserver 192.168.42.2
nameserver 2602:61:7700:6f00::2
nameserver 1.1.1.1
search grickle.local
```

**Comment by jamesharr** [comment]
Another data-point -- Reproduced on Ubuntu 20.04 AMD64. Built from the Ubuntu cloud image (listed below). The only difference from the setup instructions above is that it's a single-node install, so the taint on the control node is skipped.

Image: [focal-server-cloudimg-amd64.img](https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img)

**uname**
```
Linux k3s-worker3 5.4.0-92-generic #103-Ubuntu SMP Fri Nov 26 16:13:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**kubectl version**
```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5+k3s1", GitCommit:"405bf79da97831749733ad99842da638c8ee4802", GitTreeState:"clean", BuildDate:"2021-12-18T00:43:30Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**sysdump**
[cilium-sysdump-20220104-164349.zip](https://github.com/cilium/cilium/files/7810820/cilium-sysdump-20220104-164349.zip)

**Comment by jamesharr** [comment]
Other data-points:
* Turning off `options edns0 trust-ad` does not seem to have an effect

**Comment by jamesharr** [comment]
I'm comparing `hubble log` output with and without the work-around applied and this seems very suspicious.

1. `L3-L4 REDIRECTED (UDP)` - same on both
2. `to-proxy FORWARDED (UDP)` - same on both
3. `dns-request FORWARDED (DNS Query example.com. A)` - same on both
4. ` dns-response FORWARDED (DNS Answer "93.184.216.34" TTL: 30 (Proxy example.com. A))` - same on both
5. This is where things differ
    a. `dns-response ERROR (DNS Answer "93.184.216.34" TTL: 30 (Proxy example.com. A))` shows up without the work-around, followed by some extra entries generated when `dig` retries the request
    b. `to-endpoint FORWARDED (UDP)` shows up when the work-around is applied.

Work-around applied (copied here for convenience) which permits kube-system to talk to the pod in the current namespace:
```
---
### Work-around NetworkPolicy to allow DNS return traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dns-return-hack
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
```

**Comment by jamesharr** [comment]
Looking at the cilium agent logs, I do see this (Ubuntu 20.04, K3s single-node, no work-around applied):

```
level=warning msg="WriteMsgIP failed" error="write ip 127.0.0.1->10.0.0.63: sendmsg: operation not permitted" subsys=fqdn/dnsproxy
level=error msg="Cannot forward proxied DNS response" DNSRequestID=43402 dnsName=example.com. endpointID=2244 error="write ip 127.0.0.1->10.0.0.63: sendmsg: operation not permitted" ipAddr="10.0.0.63:37074" subsys=fqdn/dnsproxy
level=warning msg="WriteMsgIP failed" error="write ip 127.0.0.1->10.0.0.63: sendmsg: operation not permitted" subsys=fqdn/dnsproxy
level=error msg="Cannot forward proxied DNS response" DNSRequestID=43402 dnsName=example.com. endpointID=2244 error="write ip 127.0.0.1->10.0.0.63: sendmsg: operation not permitted" ipAddr="10.0.0.63:37074" subsys=fqdn/dnsproxy
level=warning msg="WriteMsgIP failed" error="write ip 127.0.0.1->10.0.0.63: sendmsg: operation not permitted" subsys=fqdn/dnsproxy
level=error msg="Cannot forward proxied DNS response" DNSRequestID=43402 dnsName=example.com. endpointID=2244 error="write ip 127.0.0.1->10.0.0.63: sendmsg: operation not permitted" ipAddr="10.0.0.63:37074" subsys=fqdn/dnsproxy
```

With the work-around applied, no log message is displayed.

**Comment by jamesharr** [comment]
I think I made a break-through. I believe that with K3s, it turns out that flannel is still active and is interpreting NetworkPolicy, just not implementing an overlay of any sort. When I add `--disable-network-policy` to the K3s install, things seem to behave properly.

New K3s install instruction:
```
curl -sfL https://get.k3s.io | sh -s - server \
  --node-name="${HOSTNAME}" \
  --disable servicelb \
  --flannel-backend=none \
  --disable-network-policy
```

I also updated the K3s testing manifest to make positive/negative testing a bit easier:
* pod/dns-client
* networkpolicy.networking.k8s.io/ingress-default-deny
* networkpolicy.networking.k8s.io/egress-default-deny
* ciliumnetworkpolicy.cilium.io/egress-example-com-dns

Updated manifest: [dns-return-test.yml.txt](https://github.com/cilium/cilium/files/7815566/dns-return-test.yml.txt)

After applying the attached manifest (above), this executes as expected, indicating to me that disabling NetworkPolicy at K3s install is not negatively impacting Cilium's NetworkPolicy processing:
```
kubectl -n test-ns exec dns-client -- dig example.com # works as expected
kubectl -n test-ns exec dns-client -- dig google.com # works as expected
kubectl -n test-ns exec dns-client -- curl example.com # works as expected
kubectl -n test-ns exec dns-client -- curl google.com # fails as expected (times out)

kubectl delete -n test-ns cnp egress-example-com-dns
kubectl -n test-ns exec dns-client -- dig example.com # fails as expected
kubectl -n test-ns exec dns-client -- dig google.com # fails as expected
kubectl -n test-ns exec dns-client -- curl 93.184.216.34 # fails as expected (example.com)
kubectl -n test-ns exec dns-client -- curl 142.250.191.238 # fails as expected (google.com)
```

Brainstorming from an outside perspective, these might be some areas for improvement. I don't think all need to be implemented, these are just some ideas:
* Update the K3s install docs to include `--disable-network-policy`
* Update troubleshooting docs to 1) note that NP enforcement needs to be turned off in K3s 2) some way to observe if it is enabled. I detected it by observing `iptables -vnL` on the worker node.
* A self diagnostic to detect this situation? Possibly provide guidance and/or a link to the troubleshooting guide?

Other closing thoughts:
* I think the mixing of NetworkPolicy and CiliumNetworkPolicy objects may be complicating things a bit. The approach I've been taking so far is "use NetworkPolicy where possible, use CiliumNetworkPolicy when it's needed". Is this the right approach?
* This involves a default-deny egress policy, which I'm guessing is not the most common use-case.
* Huge thanks to @joestringer for helping me out over [slack](https://cilium.slack.com/archives/C01JALNQAR1/p1640200341429400).

**Comment by jamesharr** [comment]
Reviewing the docs, I found that some pages listed the `--disable-network-policy` flag and I think that may have been what tripped me up:
* [gettingstarted/k3s](https://docs.cilium.io/en/v1.11/gettingstarted/k3s/#getting-started-using-k3s) -- this shows the `--disable-network-policy` flag
* [gettingstarted/Quick Installation](https://docs.cilium.io/en/v1.11/gettingstarted/k8s-install-default/#install-cilium) does not list the flag

**Comment by joestringer** [comment]
Great work troubleshooting & getting to the bottom of it. 

> Brainstorming from an outside perspective, these might be some areas for improvement:
> * Update the K3s install docs to include --disable-network-policy

Yes please, looks like `Documentation/gettingstarted/requirements-k3s.rst` should be updated to include the same options as `Documentation/gettingstarted/k3s.rst`. In fact arguably we should maybe remove the latter, I'm not sure we need a dedicated page for k3s any more since the instructions for most platforms are now included in the "quick installation" page.

> * Update troubleshooting docs to 1) note that NP enforcement needs to be turned off in K3s 2) some way to observe if it is enabled. I detected it by observing iptables -vnL on the worker node.
> * A self diagnostic to detect this situation? Possibly provide guidance and/or a link to the troubleshooting guide?

One of the main observations I see here is that you believed that you had installed Cilium and therefore _only_ Cilium is responsible for the networking on the node. However, it turns out that flannel was also present and causing interference. In general it will always be more reliable for Cilium to provide all of the functionality rather than mixing Cilium with another component, just because we are more likely to test the "only Cilium" case rather than testing integration with every possible other CNI and understand which parts of the kernel configuration etc. that should be handled by each CNI.

From that direction, I wonder if there would be a way to easily detect when multiple CNIs are applying logic in an environment and highlight that so that if it's not intentional, at least it would be easier to detect / understand. I could imagine a few ways to detect this, but the simplest might be just to see whether there are other CNI configuration files under `/etc/cni/net.d`..?

Observing the `iptables` rules could be another way, but this can be a bit trickier. Even if we could detect that there are iptables rules which are not managed by Cilium, it will not always be obvious which component is introducing them (depending on how explicit they are with the `--comment` fields) or whether those particular rules are causing a conflict.

> That's a bunch of ideas, but not all probably need to be implemented. Where are areas that I can help out?

:heart: I appreciate the offer! I think the minimum we could do is to improve the docs; we can avoid needing to go through the debugging steps for future k3s deployments if the instructions are all set up right in the first place. If you can think of an easy way to implement the diagnostic suggestion above then I'd welcome that as well; I guess the question is probably more whether we can think of an appropriate place to perform that diagnostics. It could just be documentation under the "troubleshooting" section of the guide; or alternatively I could see it being somehow integrated into either Cilium itself, or potentially the [Cilium CLI](https://github.com/cilium/cilium-cli) `cilium status` output.

> Other closing thoughts:

> * I think the mixing of NetworkPolicy and CiliumNetworkPolicy objects may be complicating things a bit. The approach I've > been taking so far is "use NetworkPolicy where possible, use CiliumNetworkPolicy when it's needed". Is this the right approach?

I recognize that mixing policies can certainly be a pain point. It's hard to make a solid recommendation one way or another, but I can see benefits to avoiding multiple types of policy as much as possible. One of the simple notions is just that it can be easy to fall into the trap of only ever using `kubectl get ciliumnetworkpolicies` and then you forget that either k8s netpol or Cilium ClusterwideNetworkPolicies are also present. All of these policies will apply at the same time, so to have a full picture of policy, you will need to understand all of the policies. From this particular incident, we see that another component was implementing k8s netpol at the same time as Cilium, so in a sense this could be avoided by using only CNP, since flannel would not understand how to implement those policies. But that said, there can also be arguments to use standard k8s network policies as much as possible in order to reduce friction, for example if you wanted to migrate away from Cilium in future. And as much as we would like to make Cilium the no-brainer, best possible choice for CNI, it's your perogative as to whether you may want to switch to something else at any point :-) In summary, it comes down to your priorities.

> * This involves a default-deny egress policy, which I'm guessing is not the most common use-case.

I think that this is a fairly common use-case and we would recommend pursuing a least privilege / zero trust type approach like this. In this particular case I think it's more that the most common operations would be for Cilium to operate alone as the only CNI, but depending on the installer you use or your environment, it is possible to chain or combine Cilium with other plugins. Given how many other CNI plugins and how many different installers there are, it's difficult for the Cilium project to get good coverage over the install paths for all of them.

**Comment by jamesharr** [comment]
> I recognize that mixing policies can certainly be a pain point. It's hard to make a solid recommendation one way or another, but I can see benefits to avoiding multiple types of policy as much as possible. One of the simple notions is just that it can be easy to fall into the trap of only ever using kubectl get ciliumnetworkpolicies and then you forget that either k8s netpol or Cilium ClusterwideNetworkPolicies are also present.

This is a solid point. I think support for implementing NetworkPolicy objects is a good idea, but for any single given service, it's probably best to stick to one or the other. IE: If we adopt CNPs, we're already recognizing the fact that standard NP's won't serve our purpose and if we mix and match the two, the application is going to be broke anyway.

But... If a service only needs NP's, there's no point in graduating to CNPs if there's a possibility we'd share that helm chart with the world.

I think the desire here is so that if we do decide to open any of our services, we're not pushing the requirement to use Cilium onto anyone who wants to adopt that service. That's a bit of an assumption on my part as the person investigating CNIs, but it's something we'll need to answer as the team.

A somewhat tangential idea is that having a cilium-cli command to view the resultant set of policies. IE: If cilium boils things down to IPs, ports, allow/deny/proxy decisions, then having something to display that resultant policy set would be helpful (even if it's simulated), especially if that command displays where the policy came from. I'm throwing the idea in slack to see if there's any interest around it. This wouldn't be intended to solve the problem of having two CNI's implementing Network Policies, though.
