### ISSUE TITLE
pod visit host failed after systemctl restart network

### ISSUE THREAD

**Issue by llhhbc** [cilium/cilium#18377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. pod create success
2. `systemctl restart network`
3. exec in pod,  `curl -k -v https://<host_ip>:6443`  visit apiserver timeout 

### Cilium Version

cilium version
Client: 1.10.4 2a46fd6 2021-09-01T12:58:41-07:00 go version go1.16.7 linux/amd64
Daemon: 1.10.4 2a46fd6 2021-09-01T12:58:41-07:00 go version go1.16.7 linux/amd64

### Kernel Version

uname -a
Linux 10-10-150-154 4.19.113-300.el7.x86_64 #1 SMP Mon Mar 30 21:50:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

cilium sysdump
Error: unknown command "sysdump" for "cilium"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the report. Are you using Cilium's kube proxy replacement or are you using kube-proxy to provide services on the node? This could potentially impact whether it's at all possible for Cilium to mitigate an issue like this.

I'm not sure what `systemctl restart` does, but my guess is that it's invasive and is unaware that it is clobbering Cilium configurations on the node. I'm not sure whether there is something we can do in the Cilium project to mitigate this, or whether you need to follow up with the upstream systemd folks, or the maintainers of this `network` systemd module to ensure that this command will only impact configurations that the network module controls, rather than wiping Cilium configuration. 

If you are able to provide more specific details about what configuration changes on the nodes and propose something that you think Cilium could do to mitigate the connectivity issues when running `systemctl restart network`, then I think we would be interested to discuss proposals. In principle it is technically possible for Cilium to have some sort of a watch on configuration changes and then undo whatever steps that this is applying, but in general this will not prevent temporary disruption, because the core issue is that the `systemctl restart network` command is causing the disruptions.
