### ISSUE TITLE
service: Improve restoration of services from lbmap

### ISSUE THREAD

**Issue by brb** [cilium/cilium#18371]
Currently, the service restoration from lbmap (the entrypoint is `(pkg/service/service.go.*Service) RestoreServices(...)`) bails immediately upon hitting an error. Instead of bailing, we should log those errors and continue to restore next entries.

This could help to reduce a number of connections which would be interrupted due to svc/backend ID changes which happens when the restoration fails.

**Comment by chowmean** [comment]
I want to work on this. Can you please assign it to me? 

What I think has to be done here is find the loop where it is trying to recover the services and from there instead of returning the error. It can log the error and proceed to attempt to recover other services. 
in `pkg/service/service.go` `for _, svc := range svcs {` I think this should be the code location.
