### ISSUE TITLE
Improve BPF datapath unit testing

### ISSUE THREAD

**Issue by kkourt** [cilium/cilium#18480]
There are currently a number of different approaches for doing datapath unit testing in the tree, but they all have limitations which means that we end up having a lot of our testing happen in e2e tests using `ginkgo`. The problem with this is twofold:
* datapath development does not have a fast iteration cycle. It takes a long time to test features / etc.
* cathing datapath problems with the e2e tests is troublesome. There are many things that can go wrong and it's costly to identify issues.

Overall, I believe that having datapath unit testing (not to replace, but to complement datapath e2e tests) would save a lot of developer time.

### bpf unit testing using BPF_PROG_TEST_RUN

There are simple tests using this. The idea is to load the datapath code using go, create the initial state of maps, feed packets to it, and validate the output and the final state of maps. A first example can be found in:
https://github.com/cilium/cilium/blob/master/bpf/tests/prog_test/prog_test.go#L352. https://github.com/cilium/cilium/issues/14990 describes a way to address current limitations.

### ~bpf unit testing using cmock~

~Details about this approach can be found in the [bpf/mock](https://github.com/cilium/cilium/tree/master/bpf/mock) directory. A discussion about the limitations and a way of addressing them can be found in: https://github.com/cilium/cilium/pull/17227#discussion_r707086108.~ (prevalent approach seems to be using BPF_PROG_TEST_RUN.)

**Comment by dylandreimerink** [comment]
I have been playing with the idea of running tests for datapath in eBPF and created a [draft](https://github.com/cilium/cilium/compare/master...dylandreimerink:feature/bpf-unit-tests?expand=1) of what that might look like. Not set on any aspect of it,

With this method we can make test `SUITE`s which can contain multiple `TEST`s, in reality the suite is just a single eBPF program and all of the tests are executed one after the other, so they can share state and or setup. A single source file can contain multiple suites or they can be separated out. There are a few pre-defined actions a test can take which are modeled after the way Go unit tests work, a test passes by default and you can call `bpf_fail()` to mark a test as failed or `bpf_fail_now()` to exit the current test at that time. The `bpf_log(msg)`, `bpf_error(msg)` and `bpf_fatal(msg)` log a error message which is displayed in the results.

We record the test name, log and result in a buffer which we pass back to user space. The loader, a Go application is started as a testing.T unit test, each suite as a sub-test and each `TEST` as a sub-test of the suite. The Go application translates the log and result to the Go testing framework. The verbose output looks like this:
```
=== RUN   TestBPFUnits
=== RUN   TestBPFUnits/xdp/unittest/ipv6
=== RUN   TestBPFUnits/xdp/unittest/ipv6/test_ipv6_addr_clear_suffix
    bpf_unit_test.go:102: 
=== RUN   TestBPFUnits/xdp/unittest/ipv6/test_lpm_lookup
    bpf_unit_test.go:102: 
=== RUN   TestBPFUnits/xdp/unittest/jhash
=== RUN   TestBPFUnits/xdp/unittest/jhash/test_12
    bpf_unit_test.go:102: Produced hash != 0xAA
        
=== RUN   TestBPFUnits/xdp/unittest/jhash/test_1234
    bpf_unit_test.go:102: Produced hash != 0xABDD
        
=== RUN   TestBPFUnits/xdp/unittest/nat
=== RUN   TestBPFUnits/xdp/unittest/nat/return_-1_on_error_
    bpf_unit_test.go:102: 
=== RUN   TestBPFUnits/xdp/unittest/nat/return_0_on_track
    bpf_unit_test.go:102: 
=== RUN   TestBPFUnits/xdp/unittest/nat/return_-1_on_create_error
    bpf_unit_test.go:102: 
=== RUN   TestBPFUnits/xdp/unittest/nat/return_0_on_create_success_
    bpf_unit_test.go:102: 
--- FAIL: TestBPFUnits (0.01s)
    --- PASS: TestBPFUnits/xdp/unittest/ipv6 (0.00s)
        --- PASS: TestBPFUnits/xdp/unittest/ipv6/test_ipv6_addr_clear_suffix (0.00s)
        --- PASS: TestBPFUnits/xdp/unittest/ipv6/test_lpm_lookup (0.00s)
    --- FAIL: TestBPFUnits/xdp/unittest/jhash (0.00s)
        --- FAIL: TestBPFUnits/xdp/unittest/jhash/test_12 (0.00s)
        --- FAIL: TestBPFUnits/xdp/unittest/jhash/test_1234 (0.00s)
    --- PASS: TestBPFUnits/xdp/unittest/nat (0.00s)
        --- PASS: TestBPFUnits/xdp/unittest/nat/return_-1_on_error_ (0.00s)
        --- PASS: TestBPFUnits/xdp/unittest/nat/return_0_on_track (0.00s)
        --- PASS: TestBPFUnits/xdp/unittest/nat/return_-1_on_create_error (0.00s)
        --- PASS: TestBPFUnits/xdp/unittest/nat/return_0_on_create_success_ (0.00s)
FAIL
```

This approach differs from the suggestion in the issue in the sense that we do setup and pass/fail logic all in eBPF. That means that developers won't have to switch between C and Go when writing tests for their code which should make it easier to write. The loader will pickup any `.o` files in the directory and look for test suite programs and dynamically register sub-tests depending on the output of the suite so no loader modifications needed. 

Since we are running the code in the kernel, things like maps will just work. By writing the tests in C we can easily mock out parts of the code we are not interested in and/or set pre-processor variables to enable/disable parts of the code without having to get the agent to create a `node_config.h`

My final thought was to combine this with code coverage tooling Elasticsearch put out for viability into what parts are and aren't covered.
