### ISSUE TITLE
eBPF map "policy" fills up (resource leak)

### ISSUE THREAD

**Issue by alex-berger** [cilium/cilium#18581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Using Cilium version 1.11.0 (and 1.11.1) we run into problems with exceeding the eBPF map size for the *policy* map of the clusters CoreDNS Pods. We already increased bpf-map-dynamic-size-ratio from 0.0025 (the default setting) to 0.01 to increase all map sizes. However, after some hours (and several hundred very short-lived CronJob Pods later) we again hit the policy map size limit.

Once the eBPB map is full, traffic to CoreDNS will be dropped and (affected) workloads on the cluster start to fail as they no longer can resolve DNS names.

It looks like there is some garbage collection issues (bug) with Cilium not removing old (stale) map entries, kind-of-a resource leak. 

Below the `CiliumNetworkPolicy` which causes this problem. Removing that policy from our clusters resolves the problem.

```yaml
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: coredns
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      k8s-app: coredns
  ingress:
    # Allow DNS access from any namespace and pod inside this Kubernetes cluster.
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
        - ports:
            - port: "53"
              protocol: TCP 
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: grafana-agent
            app.kubernetes.io/instance: grafana-agent-metrics
            io.kubernetes.pod.namespace: grafana-agent-system
        - matchLabels:
            app.kubernetes.io/name: datadog
            app.kubernetes.io/component: cluster-agent
            io.kubernetes.pod.namespace: kube-system
        - matchLabels:
            app.kubernetes.io/name: datadog
            app.kubernetes.io/component: agent
            io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "9153"
  egress:
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
        - ports:
            - port: "53"
              protocol: TCP
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
```

### Cilium Version

We observe that behavior with the following Cilium version:
- 1.11.1
- 1.11.0

### Kernel Version

We observe this behavior with the following kernel version:
- 5.4.156
- 5.10.75

### Kubernetes Version

1.21 (EKS)

### Relevant log output

```shell
msg="Failed to add PolicyMap key" bpfMapKey="{31163 53 6 0}" containerID=94cb79724b datapathPolicyRevision=12 desiredPolicyRevision=12 endpointID=2200 error="Unable to update element for cilium_policy_02200 map with file descriptor 88: the map is full, please consider resizing it. argument list too long" identity=7935 ipv4=10.176.27.102 ipv6= k8sPodName=kube-system/coredns-6df967c45d-fcfnk port=0 subsys=endpoint
```

### Anything else?

Related [Slack thread](https://cilium.slack.com/archives/C01JALNQAR1/p1640211424433400)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the report. I think there's two things potentially interacting for the worse here:

(1) It seems like something about the way that CronJobs are deployed and removed does not trigger the cleanup logic. Does Kubernetes issue CNI DEL requests to Cilium for the cronjobs once they are completed? If you go into one of the Cilium pods, does `cilium endpoint list` show old stale CronJob entries?

(2) If every CronJob gets a unique identity for enforcing policy, eg based on some label with a UUID or timestamp, then this can cause the total number of identities to increase significantly, to a point where permissive policies attempt to explicitly allow each Identity, and that number takes many map entries to implement.

One mitigation is to look into what's happening with (1) to understand whether we can solve the lifecycling of the CronJobs properly. Another mitigation is to minimize the number of unique Identities in the system by [Limiting Identity-relevant Labels](https://docs.cilium.io/en/stable/operations/performance/scalability/identity-relevant-labels/#identity-relevant-labels) (more targeted at (2). Furthermore, if you have very permissive policies for some of your pods, then this can exacerbate issues with many Identities and lead to generating many PolicyMap entries because some of the pods are attempting to allow traffic from each and every CronJob pod's Identity. Making policies more restrictive can potentially help with this aspect of (2).

**Comment by alex-berger** [comment]
> (1) It seems like something about the way that CronJobs are deployed and removed does not trigger the cleanup logic. Does Kubernetes issue CNI DEL requests to Cilium for the cronjobs once they are completed? If you go into one of the Cilium pods, does cilium endpoint list show old stale CronJob entries?

@joestringer: No, it does not look like there are any stale old cilium endpoints for CronJobs. I checked this as you proposed using `cilium endpoint list` and I also checked the `cilium_endpoint` metric (see attached graphic).

<img width="1404" alt="grafik" src="https://user-images.githubusercontent.com/1087375/150604095-dfc420f6-4ce7-45cd-8739-59d67bcc3287.png">

**Comment by alex-berger** [comment]
> (2) If every CronJob gets a unique identity for enforcing policy, eg based on some label with a UUID or timestamp, then this can cause the total number of identities to increase significantly, to a point where permissive policies attempt to explicitly allow each Identity, and that number takes many map entries to implement.

@joestringer: Yes, it is true that each Pod created from a CronJob has some unique labels, namely the `controller-uid` and `job-name` labels, which are created by the Kubernetes Job controller (CronJob -> Job -> Pod).

```yaml
  labels:
    controller-uid: 83a9649f-e006-4576-b904-400f903f3e8a # The UUID of the Job (created for this CronJob run)
    job-name: test-27380030 # the name of the Job (created for this CronJob run)
```

However as mentioned [above](https://github.com/cilium/cilium/issues/18581#issuecomment-1018887064), it does not look like there are any stale endpoints (lying around) for all those entities. And therefore I assume there must be some kind of leak (not deleting old/stale eBPF map entries).

**Comment by joestringer** [comment]
:+1: Do you also have the `cilium_identity` metric?

Other things that may help (along with just a sysdump, since that will grab a lot of relevant information) would be a dump of the identities in the cluster - you could either probe this from the k8s level via `kubectl get ciliumidentities` and/or probe an individual Cilium pod using `cilium identity list` inside the pod. It may also be relevant to look at the `cilium policy selectors` to see which selectors are selecting many identities and which identities are being selected. Combining this information together, we may be able to track down some pattern in the identities that Cilium believes are still live and whether it's the policy subsystem keeping these alive, or some other piece of code.

**Comment by joestringer** [comment]
Another aspect if the identities are not reducing, is to look at the operator - As far as I understand, there is some periodic identity garbage collection handled by the operator (which also should have some corresponding metrics), so it would be useful to know how frequent that is and whether it's kicking in as expected (and whether that actually cleans up some of the identities that are no longer in use).

**Comment by alex-berger** [comment]
The `cilium_identity` metrics looks innocent (similar to the `cilium_endpoint` one):

<img width="1158" alt="grafik" src="https://user-images.githubusercontent.com/1087375/150607522-8075cf6a-a1db-4acb-9ae5-eb5149d7996d.png">

The result of `kubectl get ciliumidentities` also looks rather innocent:

```
❯ kubectl get ciliumidentities -o wide 
NAME    NAMESPACE              AGE
10158   linkerd-viz            46d
10349   loki-system            51d
10618   linkerd                51d
1086    default                17m
11102   default                23m
1116    kube-system            24m
1136    kube-system            51d
1140    loki-system            51d
1155    grafana-agent-system   39d
11557   kube-system            51d
1158    kube-system            51d
11930   kube-system            12m
11939   kube-system            31d
12234   default                21m
1241    flux-system            37d
12549   kube-system            26m
12833   gloo-system            39d
13381   kube-system            6m27s
13696   default                20m
14016   loki-system            51d
14246   default                11m
1477    default                15m
15153   grafana-system         51d
16707   kube-system            30m
16888   kube-system            10m
16973   loki-system            31d
17168   kube-system            35d
1782    cortex-system          31d
18057   grafana-agent-system   10h
18059   default                3m27s
1819    loki-system            51d
18256   cortex-system          30d
18398   loki-system            51d
18759   kube-system            16d
18857   default                30m
18976   grafana-agent-system   42d
19063   flux-system            37d
19078   cortex-system          31d
19242   cortex-system          51d
19316   kube-system            51d
19520   flux-system            37d
20051   cortex-system          51d
20369   loki-system            51d
21875   default                18m
22352   loki-system            51d
22451   loki-system            51d
23102   loki-system            31d
24021   default                4m27s
2482    linkerd-viz            46d
24989   loki-system            51d
25257   kube-system            28m
26038   default                6m27s
27298   cortex-system          31d
2891    default                16m
29514   flux-system            37d
30183   gloo-system            39d
30530   default                19m
3099    default                9m27s
31396   default                24m
3159    gloo-system            39d
32421   kube-system            51d
32508   grafana-agent-system   39d
32927   loki-system            49d
33231   gloo-system            39d
33255   gatekeeper-system      46d
3328    default                29m
3488    kube-system            18m
35304   cortex-system          51d
3592    kube-system            51d
3642    kube-system            51d
367     cortex-system          51d
37180   linkerd-viz            46d
382     kube-system            35d
38725   linkerd                51d
39105   kube-system            35d
3947    default                2m27s
40178   kube-system            51d
40464   default                22m
40521   kube-system            20m
40931   loki-system            31d
4202    loki-system            51d
43473   cortex-system          31d
44263   kube-system            51d
44878   kube-system            16m
45226   kube-system            51d
45353   grafana-system         46d
45623   loki-system            31d
45635   default                5m27s
47567   kube-system            4m27s
48152   default                10m
4895    cortex-system          51d
50200   kube-system            8m27s
5095    kube-system            51d
5150    default                13m
536     kube-system            14m
5494    kube-system            35d
54976   kube-system            51d
55200   default                27m
55264   kube-system            27s
57014   default                12m
57039   grafana-agent-system   39d
57176   loki-system            51d
57954   kube-system            22m
58838   default                25m
59276   default                27s
60632   default                7m27s
60790   default                26m
6108    kube-system            51d
6116    starboard-operator     51d
61951   default                14m
63338   cortex-system          51d
63933   default                87s
64419   kube-system            51d
6498    loki-system            51d
65102   default                28m
6838    kube-system            51d
7088    linkerd                51d
7935    kube-system            51d
8822    default                8m27s
9117    gatekeeper-system      46d
9203    linkerd-viz            46d
9342    kube-system            2m27s
9442    kyverno                46d
9635    kube-system            35d
```

**Comment by alex-berger** [comment]
Identity GC seems to work as expected, which corresponds to what we saw from the `cilium_identity` metric respectively the output from `kubectl get ciliumidentities`:

<img width="1242" alt="grafik" src="https://user-images.githubusercontent.com/1087375/150608375-b249162e-2258-4a3d-bd22-8e12e6367dd9.png">

**Comment by alex-berger** [comment]
Which brings us to your last point the `cilium policy selectors`. Our current observation is that the [above mentioned](https://github.com/cilium/cilium/issues/18581#issue-1110610193) `CiliumNetworkPolicy` for CoreDNS triggers this leak. If we remove that `CiliumNetworkPolicy` the problem disappears (or at least the leaks is growing much slower, such that we do not observe it).

**Comment by alex-berger** [comment]
Another observation is, that if I edit and save the above mentioned CiliumNetworkPolicy for CoreDNS (e.g. just adding a label, not changing any of its selectors) the leak is reset (the eBPF maps are drained). Of course after some hours, they are then filled up again and the problem is back.

**Comment by aanm** [comment]
@alex-berger please provide a Cilium sysdump when the issue occurs. Thank you.

**Comment by othmane399** [comment]
Hello, I have the same issue since I've upgrade to 1.11

**Comment by alex-berger** [comment]
@aanm Please find attached the requested `cilium sysdump`.

[cilium-sysdump-20220122-220038.zip](https://github.com/cilium/cilium/files/7919281/cilium-sysdump-20220122-220038.zip)

**Comment by aanm** [comment]
@alex-berger thank you but the sysdump is incomplete. There should be some cilium agents bugtool directories inside that .zip file. Specially for the cilium agents that are facing the issue.

**Comment by alex-berger** [comment]
@aanm I get warnings like the one below, but I have no clue why. 

```
⚠️ cilium-bugtool-cilium-452vd: failed to collect 'cilium-bugtool' output for "cilium-452vd" in namespace "kube-system": command terminated with exit code 137: 
```

**Comment by aanm** [comment]
@alex-berger are you following the steps described [here](https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection)? If yes, can you paste a full log output? Thanks

**Comment by joestringer** [comment]
> Which brings us to your last point the cilium policy selectors. Our current observation is that the above mentioned CiliumNetworkPolicy for CoreDNS triggers this leak. If we remove that CiliumNetworkPolicy the problem disappears (or at least the leaks is growing much slower, such that we do not observe it).

That's an interesting observation. I see the new `kube-apiserver` entity is used in one of the policies, so it's possible that this is related to the issue. Either way, I think that a proper bugtool dump from the node will help, and `cilium policy selectors` output will be one of the areas I would be most interested in.

**Comment by joestringer** [comment]
@alex-berger There's no defaults for memory limits on the cilium agent by default, as they tend to cause more problems than they solve. That said, if you are able to figure out useful limits that allow sysdump to successfully run, then that would be useful to know. It's hard to say what good values would be without understanding a lot about the deployment configuration, cluster details, etc.

**Comment by christarazi** [comment]
Hi @alex-berger, if you are able to reproduce the issue with v1.11.1, then please attach a sysdump for that. We [fixed](#18150) a very similar issue in .1.

**Comment by alex-berger** [comment]
Trying to reproduce this (after increasing memory limits for cilium agents), I now run into another problem. I get warnings like the one below and most of my CronJob Pods (that I use to reproduce the leak) do not start properly as they fail to get IP addresses.

```
level=warning msg="Stray endpoint found. You may be affected by upstream Kubernetes issue #86944."
containerID=c9f510374c endpointID=2656 k8sPodName=default/ytest-19-27386835-2bf6j 
subsys=endpoint-manager url="https://github.com/kubernetes/kubernetes/issues/86944"
```

Could this be related to our leak and if so, what is more likely, that the leak causes the problem with "Stray endpoints" or that the "Stray endpoints" cause the leak? I attached a sysdump (the download link will only work for the next few days).

[sysdump](https://drive.google.com/file/d/1-K3nUZajYXrb79U4_448fiRWOqXVFmcr/view?usp=sharing)

**Comment by joestringer** [comment]
@alex-berger I don't see the originally reported error message in this latest sysdump. Did the policymap resource leak issue occur this time that you tried? If you think the problem happened this time, can you share exactly which pods / which nodes / cilium pods you think were affected?

Regarding the "Stray Endpoints" issue, this occurs when the pod "disappears" during operation. Usually in a standard operation, when a pod is deleted, kubelet will call CNI DEL on cilium-cni and Cilium will clean everything up. What's happened here is that the pod was not explicitly deleted, but it went missing regardless. More specifically, the veth network device that provides networking connectivity to the pod disappeared without Cilium being informed that the pod should be deleted. You may be able to debug that independently using kubelet logs from the node where this occurred.

Right now I would treat the two issues entirely separately, since I'm not seeing the evidence of policy maps filling up in this latest sysdump.

**Comment by alex-berger** [comment]
@joestringer yes the last sysdump was for the `Stray Endpoints` problem only. Now, I was able to reproduce the original problem (after 24 hours of trying) and the below linked sysdump should contain the reported message `Failed to add PolicyMap key`.

[sysdump for `Failed to add PolicyMap key`](https://drive.google.com/file/d/1-MWkySp-V4ELJmgtRdki7wN87lvQFfN7/view?usp=sharing)

There were several Nodes and Pods affected just grep for `Failed to add PolicyMap key`. For example Pod `cilium-49wj9` running on Node `ip-10-176-23-135.eu-central-1.compute.internal` reported that error at `2022-01-27T07:56:23.695Z`.

**Comment by joestringer** [comment]
Thanks again for working through this with us, definitely looks like a bug, though admittedly the bug is made worse by the identity cardinality in the cluster. Reducing security identity churn would mitigate the issue without a need to change policies, however there is a real bug underneath that.

A few observations from the sysdump, looking at the `cilium-ws4rr` pod that @aanm mentioned above:

```
$ # Find out how many identities there are
$ grep "^[0-9]\+" cilium-identity-list.md  | wc -l                                                  │joe@carnotaurus [Jan 28 11:42:13 PST] cmd $ vim ../../k8s-pods-20220127-085813.*
927
```

Looking at the individual identities, I can see that many of them are unique because of UUIDs. However the policy doesn't differentiate these, so these are adding unnecessary load on the security identity allocation system. This is why I brought up [Limiting Identity-relevant Labels](https://docs.cilium.io/en/stable/operations/performance/scalability/identity-relevant-labels/#identity-relevant-labels) in an earlier post. That said, this is not yet deep enough to establish the bug, only establishing one possible explanation for high identity cardinality. This could still be unrelated to the actual issue you're reporting.

From the policy selectors detail, we see that there are two selectors that are picking a high number of these identities (looks like many):

```
$ # Filter all selectors that select more than 50 identities
$ jq -r '.[] | select ((.identities | length)>50) | .selector' cilium-policy-selectors--o-json.md
&LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{},}
&LabelSelector{MatchLabels:map[string]string{k8s.io.cilium.k8s.policy.cluster: default,},MatchExpressions:[]LabelSelectorRequirement{},}
```

Decoding these, the first one is a wildcard selector that selects everything (not sure if this ends up in a BPF map or not, will depend on the policies). The second one is a match on the "cluster" entity which I do see in the policy. This makes some sense, as it looks like you have a policy for CoreDNS that allows anything inside the cluster to make DNS requests to CoreDNS.

The number of identities in the selectors though doesn't seem so high:

```
$ # Count the number of identities in each policy selector
$ jq -r '.[] | .identities | length' cilium-policy-selectors--o-json.md
3
3
4
23
2
1
928
1
1
1
1
1
919
1
0
3
1
```

1K is certainly not ideal, but it's far from the limit currently configured for policymap sizes, 16K:

```
$ # Get the size of the policymap
$ grep PolicyMapEntries cilium-config--a.md 
PolicyMapEntries                  : 16384
```

All of the above looks pretty normal. Depending on your "identity-gc-*" settings and the pod deployment churn, it may be still possible to exceed the map sizes, but the above output does not point to such an issue.

However, as @aanm pointed out above, if we look at the actual BPF policymaps, there definitely looks like a bug that goes beyond high churn:

```
$ # check the raw number of policy entries across all policy maps on the node
$ wc -l cilium-bpf-policy-get---all---numeric.md 
16628 cilium-bpf-policy-get---all---numeric.md
```

Looking closer at the actual output, one of the individual endpoints has a map with ~16K entries, which is indeed the policy map max. Given that the identity list at the top of this post only highlighted ~900 legitimate identities, it appears that these remaining policy entries correspond to identities that no longer exist.

Given that you mentioned that you can mitigate the issue by removing the policy from the issue description, it suggests to me that something about the implementation of those policies is causing policymap entries to be injected into the BPF maps but *is not registering the cleanup logic for when the identities are removed*.

Looking over the exact numbers being used for identities in `cilium-identity-list.md`, I see that the label-based identities for individual pods are spread throughout the uint16 range, including getting up to 65504. This suggests to me that the full identity space available for pods is being iterated through as part of your test, and that the pod identities are what are triggering the bug - likely the `cluster` entity policy match. This also suggests that reducing the cardinality will mitigate the issue until we have got to the root of the problem with cleaning up old identities.

Related, I see that there are only two CIDR identities used for the kube-apiserver IPs, and these are using the identity numbers `16777217`, `16777218`. These are at the beginning of the CIDR identity space ([docs](https://docs.cilium.io/en/stable/internals/security-identities/#security-identities)), so this means that we do not appear to be allocating many CIDR identities and CIDR identities (or apiserver policy identity allocation logic) are not likely to be triggering the issue.

> Below the CiliumNetworkPolicy which causes this problem. Removing that policy from our clusters resolves the problem.

There is still a question of exactly which of these two policy statements are triggering the bug:

```
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
```

```
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
        - ports:
            - port: "53"
              protocol: TCP 
```

If you are able to try only applying one of these policies, and also try applying only the other of these two policies, and confirm whether one of these policies or the other policies or only both policies are required to trigger the bug, I think that this will help us track down the root cause.

**Comment by joestringer** [comment]
I believe that I've found a minimal reproduction of the issue, and in my testing it only affects v1.11.x releases. I cannot reproduce this with v1.10.7. Based on my testing, answering my own questions from above:

* Do you only need the cluster entity policy to trigger the bug?
  * Yes

**Comment by aditighag** [comment]
@jrajahalme  TL;DR : In some cases, identities are being leaked in the sense they are not removed from the policy selected endpoint's BPF maps. cluster entity and identity churn seem to be exposing some bug.

**Note that this bug is reproducible only in v1.11.**

There is something funky going on with this code path - http://github.com/aditighag/cilium/blob/v1.11/pkg/policy/mapstate.go#L778-L778. Joe and I were reading through the code, and we found that you had reworked this code path in v1.11 - https://github.com/cilium/cilium/commit/15a833ac4c397e5ce0fb8ff02af35d5b908a7e4b.

When an identity is deleted, identity deletion map changes were correctly accumulated.- 

```
2022-02-17T01:27:49.190404400Z level=debug msg=AccumulateMapChanges EndpointSelector="&LabelSelector{MatchLabels:map[string]string{[k8s.io](http://k8s.io/).cilium.k8s.policy.cluster: kind-kind,},MatchExpressions:[]LabelSelectorRequirement{},}" IsRedirect=false policyID.Added="[]" policyID.Deleted="[2024]" port=0 protocol=0 subsys=policy trafficDirection=Ingress

```

[consumeMapChanges](http://github.com/aditighag/cilium/blob/v1.11/pkg/policy/mapstate.go#L778-L778) correctly read the deletes (I added this debug message [before](http://github.com/aditighag/cilium/blob/v1.11/pkg/policy/mapstate.go#L784-L784) the mc.changes are iterated) -

`msg="debug-leak consume map changes mc before [{false Identity=2024,DestPort=0,Nexthdr=0,TrafficDirection=0 ProxyPort=0}]" subsys=policy`

But my debug log [inside](https://github.com/aditighag/cilium/blob/v1.11/pkg/policy/mapstate.go#L795) the deletion block wasn't hit, which means the `owners` struct wasn't populated with the policy selected endpoint



```
	log.Debugf("debug-leak consume map changes mc before %v", mc.changes) -----> Log message hit
	for i := range mc.changes {
		if mc.changes[i].Add {
			// insert but do not allow non-redirect entries to overwrite a redirect entry,
			// nor allow non-deny entries to overwrite deny entries.
			// Collect the incremental changes to the overall state in 'mc.adds' and 'mc.deletes'.
			policyMapState.denyPreferredInsertWithChanges(mc.changes[i].Key, mc.changes[i].Value, adds, deletes)
		} else {
			// Delete the contribution of this cs to the key and collect incremental changes
			for cs := range mc.changes[i].Value.owners { // get the sole selector
				policyMapState.deleteKeyWithChanges(mc.changes[i].Key, cs, adds, deletes)
			}
			log.Debugf("debug-leak consume map changes deletes after %v", deletes) ------> Not seen
		}
	}
```

Can you take a look to see what could be wrong?
