### ISSUE TITLE
Can't start cilium pod after installation on rancher-desktop v1.0.0

### ISSUE THREAD

**Issue by zbabac** [cilium/cilium#18675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Wanted to created a playground with k3s, cilium, prometheus/grafana and used rancher-desktop on Linux (ubuntu 20.04 based).
Used this guide: 
[https://docs.cilium.io/en/v1.11/gettingstarted/grafana/](url)
After installation via helm, cilium pod report an error:
`Error: failed to generate container "5ac671b188b972f82f131d21e54274b13d6aeaa46413ae8dd44db4e872fbe182" spec: failed to generate spec: path "/run/cilium/cgroupv2" is mounted on "/run/cilium/cgroupv2" but it is not a shared or slave mount`

```
kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS                      RESTARTS   AGE
kube-system   local-path-provisioner-84bb864455-nvpwg   1/1     Running                     0          23m
kube-system   helm-install-traefik-crd--1-fkzvz         0/1     Completed                   0          23m
kube-system   metrics-server-ff9dbcb6c-mzqcn            1/1     Running                     0          23m
kube-system   svclb-traefik-hf2q2                       2/2     Running                     0          22m
kube-system   helm-install-traefik--1-kkrzb             0/1     Completed                   2          23m
kube-system   traefik-55fdc6d984-lgqxk                  1/1     Running                     0          22m
kube-system   cilium-operator-5ffd7d9795-m8w2v          0/1     Pending                     0          6m7s
kube-system   cilium-operator-5ffd7d9795-z9ts6          1/1     Running                     0          6m7s
kube-system   coredns-96cc4f57d-2zl62                   1/1     Running                     0          23s
kube-system   cilium-rqzk4                              0/1     Init:CreateContainerError   0          6m7s
```

I got suggestion on forums to use workaround to mount manually:
`mount bpffs /sys/fs/bpf -t bpf`

but the question is where to mount? I am just a beginner in k8s, so a bit lost there. Rancher-desktop spins off a VM via qemu and entire K3S cluster runs inside that VM, so does the cilium as well. I can ssh to VM, but can't mount anything in it, It has no effect. Can this WA be applied somewhere else in k3s cluster? 

### Cilium Version

v1.11.1

### Kernel Version

Linux lima-rancher-desktop 5.10.88-0-virt #1-Alpine SMP Tue, 28 Dec 2021 12:51:14 +0000 x86_64 Linux

(This is kernel of the VM that runs k3s)

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-26T02:20:15Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

[cilium-sysdump-20220131-152742.zip](https://github.com/cilium/cilium/files/7971475/cilium-sysdump-20220131-152742.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincentmli** [comment]
> I got suggestion on forums to use workaround to mount manually: `mount bpffs /sys/fs/bpf -t bpf`
> 
> but the question is where to mount? I am just a beginner in k8s, so a bit lost there. Rancher-desktop spins off a VM via qemu and entire K3S cluster runs inside that VM, so does the cilium as well. I can ssh to VM, but can't mount anything in it, It has no effect. Can this WA be applied somewhere else in k3s cluster?

@zbabac maybe mount on the host, not the VM?

**Comment by zbabac** [comment]
After playing around, found out it has to be mounted on the host (where this vm runs). However, the BPF FS was already mounted, but not shared. It had to be unmounted then mounted again:

```
sudo mount bpffs -t bpf /sys/fs/bpf
sudo mount --make-shared /sys/fs/bpf
```

Altough issue doesn't exist any longer, I suggest update of the guides, to emphasize specifics of the installation into the rancher-desktop, or similar environments that run k3s inside VM.

**Comment by vincentmli** [comment]
@zbabac I vaguely recalled @borkmann made that suggestion for you from slack to mount bpffs on the host :-)

**Comment by aditighag** [comment]
>Altough issue doesn't exist any longer, I suggest update of the guides, to emphasize specifics of the installation into the rancher-desktop, or similar environments that run k3s inside VM.

Thanks for suggesting the installation step. Would you be interested in contributing a documentation PR so that it helps other users? We can document the additional step as a note in these guides - https://github.com/cilium/cilium/blob/master/Documentation/gettingstarted/k8s-install-rancher-existing-nodes.rst or https://github.com/cilium/cilium/blob/master/Documentation/gettingstarted/k3s.rst

**Comment by chancez** [comment]
I've been trying to make this work on rancher-desktop, and so far here's what I had to do:

- Start with a fresh setup, no cilium installed yet
- Run `sudo mount bpffs -t bpf /sys/fs/bpf && sudo mount --make-shared /sys/fs/bpf` inside the rancher-desktop guest.
- After this, I still saw the cgroup mount error, and ran `sudo mount --make-shared /run/cilium/cgroupv2/` , which allowed the cilium daemonset pod to run.

I'm iterating to see if I can fix it so that it works by applying some config on the VM creation, but the cgroup mount is a bit trickier.

**Comment by chancez** [comment]
Progress updates on trying to get this working:

So first, to disable flannel and the builtin network policy enforcement as instructed in https://docs.cilium.io/en/v1.11/gettingstarted/k8s-install-helm/ for k3s, you need to define an `overrides.yaml` for the rancher-desktop lima:

```
# override.yaml
env:
  # needed for cilium
  K3S_EXEC: '--flannel-backend=none --disable-network-policy'
provision:
  # needs root to mount
  - mode: system
    script: |
      #!/bin/sh
      set -e

      # needed for cilium
      mount bpffs -t bpf /sys/fs/bpf
      mount --make-shared /sys/fs/bpf

      mkdir -p /run/cilium/cgroupv2
      mount -t cgroup2 none /run/cilium/cgroupv2
      mount --make-shared /run/cilium/cgroupv2/
```

Then:
```
cp override.yaml "$HOME/Library/Application Support/rancher-desktop/lima/_config/override.yaml"
```

Unfortunately, passing multiple args to `K3S_EXEC` is broken until https://github.com/rancher-sandbox/rancher-desktop/pull/1565 is included in a new release.

That said, I ran rancher-desktop from master and despite having unrelated problems that I was able to work-around, this worked for disabling flannel. However, pods are still not coming up:

```
  Warning  FailedCreatePodSandBox  3m48s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "896a45964c9900e9a49052b1c6f7e0dedb87786f0a437852a261fe61fce0c6bd": failed to find plugin "cilium-cni" in path [/usr/libexec/cni]
  ```
  
The default helm install values uses `/opt/cni/bin` whereas k3s/rancher-desktop is using `/usr/libexec/cni`. 
  
After trying again with `--set cni.binPath=/usr/libexec/cni`, the pods correctly start up.

So the final (minimal) helm command I used was:
```
helm upgrade --install cilium cilium/cilium --version 1.11.2 --namespace kube-system --set operator.replicas=1 --set cni.binPath=/usr/libexec/cni
```

It isn't strictly necessary to delete the managed pods since they will just be in a `ContainerCreating` state waiting for CNI to be available. Also I set `operator.replicas=1`  since rancher-desktop only has a single node and the operator pods have pod anti-affinity.

This was sufficient to get it working.

**Comment by aditighag** [comment]
Nice job tracking all the installation steps! It'll be great if you could contribute a docs PR with these changes to help other users.

**Comment by chancez** [comment]
Yeah, I think we need there to be another release of rancher-desktop, but I will be trying to document this. I'm wondering if there should be a separate section on doing this for rancher-desktop separate from the existing `k3s` tab in the installation documentation WDYT?

**Comment by jandubois** [comment]
[Rancher Desktop 1.1.0](https://github.com/rancher-sandbox/rancher-desktop/releases/tag/v1.1.0) has been released and includes the required fix for `K3S_EXEC` with multiple arguments.

**Comment by imcom** [comment]
Hi @chancez chan, I noticed in your `override` yaml config, there is a comment saying

```
# needs root to mount
```

I wonder is there any extra steps to be taken in order to get root privilege or it happens by default when creating the lima vm ?

**Comment by aditighag** [comment]
> Yeah, I think we need there to be another release of rancher-desktop before this can be done smoothly, but I will be trying to document this. I'm wondering if there should be a separate section on doing this for rancher-desktop separate from the existing `k3s` tab in the installation documentation WDYT?

@chancez I would suggest adding a new section to the k3s guide - https://github.com/cilium/cilium/blob/master/Documentation/gettingstarted/k3s.rst. /cc@raphink

**Comment by raphink** [comment]
@aditighag should k3d and rancher-desktop be subsections of the k3s docs, or separate docs altogether?
