### ISSUE TITLE
datapath: to-netdev does not recirculate back after SNAT handling

### ISSUE THREAD

**Issue by brb** [cilium/cilium#18909]
In the bpf_host's egress section `to-netdev` we have the following code block https://github.com/cilium/cilium/blob/6c647ba7b06c93bf0350907255ab3c43154810b5/bpf/bpf_host.c#L1079-L1094

The problem with it is that `handle_nat_fwd()` does not recirculate back to `to-netdev` which makes the following trace notify ineffective https://github.com/cilium/cilium/blob/6c647ba7b06c93bf0350907255ab3c43154810b5/bpf/bpf_host.c#L1102

Discovered together with @gandro. cc @borkmann

**Comment by YutaroHayakawa** [comment]
I made some discussions regarding this issue with @brb and @borkmann. Below is a summary.

## The Problem

Currently, WG with KPR implementation is ongoing. In that implementation, we need to redirect the packet to the WG device in `to_netdev`. However, before that, we need to first SNAT the packet, then redirect. If we call into `handle_nat_fwd`, it does tail-call and sends the packet to the network device. So that we don't have any chance to redirect the packet to the WG device. Recirculation is one of the solutions to that problem. 

## Recirculation is not needed?
The users of this `handle_nat_fwd` (SNAT) is 1) BPF Masquerade 2) Some host applications that can reach the NodePort service endpoints (https://github.com/cilium/cilium/pull/8649/commits/b6de3922afa935b77af0cbb07693993cb44c394b).

However, in both cases, we WG shouldn't be involved. The remaining case that the WG should be involved in is NodePort SNAT (and reverse NAT), but NodePort SNAT is already performed in here, so no problem.

## Conclusion

In a conclusion, what we need to do is just add packet trace inside the `handle_nat_fwd` and that should be the scope of this issue.
