### ISSUE TITLE
datapath: Inconsistency between IPv4 and IPv6 iptables rules propagation

### ISSUE THREAD

**Issue by brb** [cilium/cilium#18904]
In the agent datapath package we try to detect and load iptables kernel modules: https://github.com/cilium/cilium/blob/3b9b098138d6197f2f7f9a8477bb33f0b698bb1e/pkg/datapath/iptables/iptables.go#L422-L436. If any v6 module cannot be loaded, we declare that the IPv6 cannot be used (i.e., we set `haveIp6tables=false`), while in the case of v4 we don't have such a declaration.

Later on in the code, we remove some chains, then re-add them and install rules. In the case of v6, not all operations are protected with `if m.haveIp6Tables {}` which can lead to the following error:
```
level=debug msg="Copying &{ip6tables cilium_node_set_v6 [-w 5]} TPROXY rule from OLD_CILIUM_PRE_mangle to CILIUM_PRE_mangle" obj="[-t mangle -A CILIUM_PRE_mangle -p udp -m mark --mark 0x27800200 -m comment --comment cilium: TPROXY to host cilium-dns-egress proxy -j TPROXY --on-port 32807 --on-ip :: --tproxy-mark 0x200/0xffffffff]" subsys=iptables
level=fatal msg="Error while creating daemon" error="error while initializing daemon: cannot add custom chain CILIUM_INPUT: exit status 1" subsys=daemon
```
The explanation for the error above is that the removal of the v6 chain `CILIUM_INPUT` is not performed due to the `haveIp6Tables` guard, while the insertion is not guarded.

Regarding the first inconsistency, I wonder why we have it. Maybe @vadorovsky or @joestringer has the answer? The code was introduced in https://github.com/cilium/cilium/commit/5b17c993e57963a86bfa4887b58018e055624086.

**Comment by vadorovsky** [comment]
> Regarding the first inconsistency, I wonder why we have it. Maybe @vadorovsky or @joestringer has the answer? The code was introduced in [5b17c99](https://github.com/cilium/cilium/commit/5b17c993e57963a86bfa4887b58018e055624086).

So my understanding is that:

* adding rules is (or should be) guarded by `option.Config.EnableIPv6`, which should be true only when:
  * IPv6 is enabled in config
  * ip6tables is available in the system
* removing rules is guarded only by `haveIp6tables`, because we want to remove IPv6 rules regardless of whether it's enabled now or not - for example, to clean up after previous Cilium run which might've IPv6 enabled and now we disable it; therefore the purpose of `haveIp6tables` is only to check whether ip6tables is available in the system

If rules are being **added** with the error you posted, I think that the real problem is that we are not checking `option.Config.EnableIPv6` at some place, or that `option.Config.EnableIPv6` is true even though ip6tables is not available.

I need to look at the code again, but for now I would say that everything should work correctly if we fallback `EnableIPv6` to false when there is no ip6tables?

**Comment by vadorovsky** [comment]
Eventually we could use something like `if option.Config.EnableIPv6 && haveIp6tables` when inserting, but in that case we would need to add some logs when `EnableIPv6` is true, but `haveIp6tables` is not, to let users know that they are doing a bad thing by enabling ipv6 when there is no ip6tables.

**Comment by joestringer** [comment]
Agree with @vadorovsky here. Goal is something like:

* If you enable IPv6 in the config, and IPv6 support is present in the kernel, then configure IPv6.
* If you disable IPv6 in the config, and IPv6 support is present in the kernel, then _unconfigure_ IPv6. (This means deleting potentially old/stale Cilium IPv6 configuration, so that when you disable IPv6 it actually disables IPv6.)
* If IPv6 support is not present in the kernel, then we shouldn't try to do any IPv6 configuration; it's gonna fail anyway. Maybe if the user configured IPv6, we should either error loudly or exit to complain that Cilium cannot achieve the requested configuration.

**Comment by vadorovsky** [comment]
@joestringer yes, actually explicit error when IPv6 is enabled, but not available, sounds better. Let me prepare a change.
