### ISSUE TITLE
Mismatch between helm chart value naming and the actual values file and docs

### ISSUE THREAD

**Issue by hacktron95** [cilium/cilium#19112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello and good day,

I've seen that there's a mismatches between helm chart values and the actual values file, 
in helm installation option, the documented way for changing `arping-refresh-period` time for the l2-neighbor-discovery feature is by setting `l2NeighDiscovery.arping-refresh-period` flag in the helm installation. [this is the helm reference page](https://docs.cilium.io/en/v1.11/helm-reference/ ) also in [the default helm values file](https://github.com/cilium/cilium/blob/v1.11.2/install/kubernetes/cilium/values.yaml#L1018)

however, for the actual helm chart, the value has a different name `l2NeighDiscovery.refreshPeriod`: https://github.com/cilium/cilium/blob/v1.11.2/install/kubernetes/cilium/templates/cilium-configmap.yaml#L600 

I would like to submit a PR for either way to fix this:
- change the docs and the default helm values to mention the right value from the helm chart `l2NeighDiscovery.refreshPeriod` which IMHO is not descriptive as `l2NeighDiscovery.arping-refresh-period`.

- change the Helm chart to use the right value mentioned in the docs `l2NeighDiscovery.arping-refresh-period`.

please lemme know if this is considered and which approach I should proceed with :))
thanks.

### Cilium Version

I checked 1.10.8 and 1.11.2

### Kernel Version

5.11

### Kubernetes Version

1.19

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ti-mo** [comment]
Hi @hacktron95, nice catch! Please do submit a PR for this, thank you.

I would opt for `l2NeighDiscovery.refreshPeriod` across the board for a few reasons:
- camelCase is preferred in yaml and would be consistent with the naming style of all other values
- users might already rely on `refreshPeriod` since the chart has already shipped this way; modifying this would constitute a breaking change
- the fact that `arping` is used for neigh disc is an implementation detail and is not relevant to the user; it can be omitted from the value name

**Comment by dongwangdw** [comment]
Hi, I found this `good-first-issue`, and just correct this issue. Please help review. My first commit here.
