### ISSUE TITLE
unable to run commands that were expected to fail without specifying set +e

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#1919]
When writing a runtime test I've noticed one of the functions, that were expected to fail, was causing the whole test to fail.

Later I've removed `set -e` from that script but our bash analyzer didn't allow me. As a workaround I had to `set +e` before executing the command that is expected to fail.

As an example: `tests/01-ct.sh` doesn't seem to be affected by this issue since the command that is expected to fail is executed inside a function, before a command that succeeds.
```
function 01_ct_function() {
    command_that_fails
    log "normal command"
}

# the function could hide a real error
01_ct_function
```
If the last `log` command is removed from the `01_ct_function`, the test will fail as the returned value of the function will be the return value of the command that failed (`command_that_fails`)

**Comment by ianvernon** [comment]
Here is what is happening. Per the bash man page (`man bash`):
```
-e      Exit immediately if a simple command (see SHELL GRAMMAR above) exits with a non-zero
status.  The shell does  not  exit if  the command that fails is part of the command list immediately
following a while or until keyword, part of the test in an if statement, part of a && or || list, or if the
command's return value is being inverted via !.  A trap on  ERR, if set, is executed before the shell exits.
```

The commands that are not failing that you are expecting to fail are in `connectivity test` in `01-ct.sh`:
```
log "trying to curl http://[$HTTPD1_IP]:80 from curl2 container (shouldn't work)"
  docker exec -i curl2 bash -c "curl --connect-timeout $DROP_TIMEOUT -XGET http://[$HTTPD1_IP]:80" && {
    abort "Error: Unexpected success reaching httpd1 on port 80"
  }
```

I edited the test and added a log message showing the return code of the curl command as well as a log message that shows all flags set in the shell:
```
log "trying to curl http://[$HTTPD1_IP]:80 from curl2 container (shouldn't work)"
  docker exec -i curl2 bash -c "curl --connect-timeout $DROP_TIMEOUT -XGET http://[$HTTPD1_IP]:80" && {
    abort "Error: Unexpected success reaching httpd1 on port 80"
  }
  echo $?
  log "return code ^^^"
  echo "$-"
  log "flags ^^^"
```

Output:
```
----- 01-ct.sh: main/connectivity_test: trying to curl http://[fd02::c0a8:210b:0:ecfe]:80 from curl2 container (shouldn't work)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (28) Connection timed out after 2002 milliseconds
28
----- 01-ct.sh: main/connectivity_test: return code ^^^
ehxB
----- 01-ct.sh: main/connectivity_test: flags ^^^
```

`e` is set and the return code is nonzero. Per the man page entry above, this is expected behavior. What I expect is happening on your end is that because in your function, if `&&` or `||` are used as the last command within a function, the shell won't exit if the command itself fails, but it will return the output of the last command as the return code of the function. For example:
```
... 
set -e
...
function foo {
  docker exec -i curl2 bash -c "curl --connect-timeout $DROP_TIMEOUT -XGET http://[$HTTPD1_IP]:80" && {
    abort "Error: Unexpected success reaching httpd1 on port 80"
  }
  # Return code of ^ is nonzero, but because it uses &&, the shell doesn't exit here per the man page
}
...
foo
# ^ fails because the last command in the execution of foo returned a nonzero return code.
# This is expected because set -e was ran above. The shell probably isn't intelligent enough to tell
the caller of the function "hey, this command was used with && or ||, so don't exit; it just sees that a
function returned with a nonzero return code
```

You can use `return 0` to get around this behavior. Since you are handling the error with `||` or `&&`, this will result in your function returning 0 and not causing the script you are writing to exit. I tested this locally.

foo.sh:
```
#!/bin/bash

set -ex

function foo {
  curl --connect-timeout 2 http://1.1.1.1 && exit 1
  echo "return code: $?"
  echo "flags: $-"
}

foo
echo "foo succeeded"
```

foo2.sh:
```
#!/bin/bash

set -ex

function foo {
  curl --connect-timeout 2 http://1.1.1.1 && exit 1
}

foo
echo "foo2 succeeded"
```

foo3.sh:
```
#!/bin/bash

set -ex

function foo {
  curl --connect-timeout 2 http://1.1.1.1 && exit 1
  return 0
}

foo
echo "foo3 succeeded"
```

output of foo:
```
$ ./foo.sh 
+ foo
+ curl --connect-timeout 2 http://1.1.1.1
curl: (28) Connection timed out after 2005 milliseconds
+ echo 'return code: 28'
return code: 28
+ echo 'flags: ehxB'
flags: ehxB
+ echo 'foo succeeded'
foo succeeded
```

The return code is nonzero, but does not exit due to `&&`. The function didn't return a nonzero return code due to `echo` commands.

Output of foo2.sh:
```
$ ./foo2.sh 
+ foo
+ curl --connect-timeout 2 http://1.1.1.1
curl: (28) Connection timed out after 2005 milliseconds
$ echo $?
28
```

This failed because `foo2.sh` runs the command in the function then returns, which results in the function returning a nonzero return code. The final `echo` statement is not ran.

Output of foo3.sh:
```
$ ./foo3.sh 
+ foo
+ curl --connect-timeout 2 http://1.1.1.1
curl: (28) Connection timed out after 2004 milliseconds
+ return 0
+ echo 'foo3 succeeded'
foo3 succeeded
```
The function returns with return code 0, and the script doesn't fail even though `curl `fails due to `&&` being used immediately following it on the same line. 

Thus, this is expected behavior of the shell; this isn't a bug in the existing test framework.
