### ISSUE TITLE
Better cluster mesh fault tolerance 

### ISSUE THREAD

**Issue by gary-RR** [cilium/cilium#19217]
## Proposal / RFE
Currently if one of the clusters in a mesh crashes, traffic still routes to the downed cluster which makes client apps keep waiting until they times out.   
**Is your feature request related to a problem?**
Yes, the scenario expressed above.
**Describe the solution you'd like**
Add some kind of heartbeat logic so that Cilium can automatically take a crashed cluster out of mesh until it is healthy again. Even if one tries to manually remove the crashed cluster through the "cilium clustermesh disconnect", since Cilium is unable to communicate with the cluster, the disconnect failed.  This task of removing and rejoining the cluster should be automatic in production.
Thanks!

**Comment by IceManGreen** [comment]
Reviving this issue because I have exactly the same problem.

I am using Cilium 1.15.2 on K3S v1.28.7+k3s1 clusters with cluster-mesh enabled.

I extended the rebel-base example to work with three clusters.
The rebel-base service is deployed in cluster-1 and cluster-2. 
The x-wing client pod is deployed only in cluster-3. 
Everything looks like a charm, requesting cluster-1 and cluster-2 from cluster-3, I sometimes get a response from the cluster-1 or cluster-2 as expected.

But if cluster-1 or cluster-2 fails entirely, not just the pods but all the nodes, the x-wing client pod on cluster-3 still tries to contact the failed cluster, resulting in useless and handling connections.
Moreover, if cluster-2 is down, I cannot disconnect cluster-2 from the clustermesh network since there is no way to join the API server or the cilium agents anymore (ex: `cilium clustermesh disconnect --context cluster-3 --destination-context cluster-2` won´t work).

I think it is kind of expected in the current Cilium version, since the agents and the clustermesh-api pods are configured to communicate with all the clusters of the cluster-mesh network. They cannot be aware of all the nodes failures of a cluster dynamically (or can they ?).

**Question**: Do you know if supporting dynamic cluster failures for cluster meshes is planned somewhere in the roadmap ? Do you know if there is a way to disconnect a cluster from an other unreachable cluster in the cluster mesh ?
