### ISSUE TITLE
docs: Add a caveat for the AF_PACKET specification around IPSec

### ISSUE THREAD

**Issue by YutaroHayakawa** [cilium/cilium#19274]
IPSec has a non-trivial specification around the tcpdump / Wireshark (technically AF_PACKET) behavior that on the ingress side, the ESP packet comes into the interface recirculated back to the interface after decryption. From the users' point of view, they will see the packets twice (encrypted and decrypted packets). This may make users misunderstand that the packets are not encrypted. It's good to have a caveat on the IPSec document.

**Comment by Kikiodazie** [comment]
Hey @slayer321, were you able to work on this issue, or are you working on it?

@pchaigno can I have this issue assigned to me? I'd love to work on it.

**Comment by slayer321** [comment]
No, you can work on this issue

**Comment by Kikiodazie** [comment]
Ok then. Thanks, @slayer321. 

@pchaigno can it be assigned to me?

**Comment by pchaigno** [comment]
Done :slightly_smiling_face:

**Comment by Kikiodazie** [comment]
> IPSec has a non-trivial specification around the tcpdump / Wireshark (technically AF_PACKET) behavior that on the ingress side, the ESP packet comes into the interface recirculated back to the interface after decryption. From the users' point of view, they will see the packets twice (encrypted and decrypted packets). This may make users misunderstand that the packets are not encrypted. It's good to have a caveat on the IPSec document.

From a conversation on the Slack #sigdocs channel, below Is more context on the issue by @YutaroHayakawa.

The problem here in short is
- We use a protocol called ESP for IPSec (IPSec is a name of the series of protocols and ESP is one of it). It encapsulates the IP packets coming from the Pods (src=PodIP) with another IP header (src=NodeIP). And encrypts “inner” IP packets.
- When users do tcpdump on receiver side, they will see two kind of the packets related to IPSec. The first one is enctypted ESP packet. Another one is decrypted IP packet. This happens because Linux first gets the encrypted packets and “reinsert” it to the receive path after decryption. This is a kind of weird kernel spec which is not always known.
- The problem here is when users are running a tcpdump with a filter like src <PodIP> , they only see decrypted IP packet. This makes a misunderstanding that packets are not encrypted.

What we should write in the document is some sentence to inform users about this spec. So that they won’t get confused

**Comment by ti-mo** [comment]
Ping, let's schedule this or close it if no longer relevant.
