### ISSUE TITLE
Cilium NetworkPolicy stops working intermittently after a few days

### ISSUE THREAD

**Issue by musabmasood** [cilium/cilium#19806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have three EKS clusters and all of them are running Cilium as the CNI. We have a `CiliumNetworkPolicy` which stops working on all clusters almost at the same time and the pods loose egress.

After recreating the `CiliumNetworkPolicy`, things start working right away. 

It feels like some kind of cache is expiring but I'm not sure where to look.

### Cilium Version

v1.11.4

### Kernel Version

5.4.156-83.273.amzn2.x86_64

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-eks-0d102a7", GitCommit:"eb09fc479c1b2bfcc35c47416efb36f1b9052d58", GitTreeState:"clean", BuildDate:"2022-02-17T16:36:28Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @musabmasood, thanks for reporting this issue. I have a few questions below that can help explore the cause:

Do I understand correctly that the problem is that traffic is flowing, then after some time, the traffic stops flowing?

Are you able to gather Hubble output for the affected connections when this problem occurs? Does Hubble report that Cilium is dropping the traffic, and if so, can you get both the regular hubble output and hubble output in json format to post here for analysis (+ specific pod IPs that are related to the breakage)

What kind of policies should be allowing the traffic?
