### ISSUE TITLE
Health port 9876 conflicts with Istio

### ISSUE THREAD

**Issue by bitva77** [cilium/cilium#19817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Yeah, we're running in EKS.  Istio installed with `hostNetwork: true` due to us using a 3rd party CNI (currently Weave) and there's an admission controller or something that the K8s API needs to call back to Istio for and can't do so via CNI because the K8s API is managed, etc....

We're looking to move to Cilium and upon installing Cilium via `helm install cilium cilium/cilium --version 1.11.4 -n kube-system`, we've run into an issue where Cilium can't start on the nodes that `istiod` is also running on as `istiod` apparently listens on port `9876` for some controlz thing (https://istio.io/latest/docs/ops/diagnostic-tools/controlz/).  Cilium also runs with `hostNetwork: true` and tries to bind `9876` as well and you see the problem :)

Are we the only people to ever run Cilium & Istio in an EKS cluster?

I think we can change the port in Istio `--ctrlz_port` but this might bite other people so FYI.

### Cilium Version

1.11.4

### Kernel Version

NA

### Kubernetes Version

1.21

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the heads up. We have Istio tests in the Cilium CI, and we've never hit this issue in the past, but these tests do not run on EKS by default. I don't know if they enable ControlZ.

The option for this health port is also configurable in Cilium via the `--agent-health-port` option (`healthPort` in Helm).

CC @tklauser I wonder if we can come up with a less predictable default health port number to reduce the likelihood of users hitting this sort of conflict? It looks like this has been set since around v1.8.x (2020), and I see that Istio Controlz has been using that port for longer than this.

**Comment by bitva77** [comment]
This would potentially be for any managed Kubernetes service as well, not just EKS.  But would need testing to verify.  I would imagine that other providers control plane wouldn't run on the overlay network either and so `hostNetwork` would be needed in those cases too and then port conflict on the node.

If Cilium's running in EKS with the aws-cni native mode (non-overlay) then this probably wouldn't be an issue (I wouldn't think at least).

**Comment by tklauser** [comment]
> CC @tklauser I wonder if we can come up with a less predictable default health port number to reduce the likelihood of users hitting this sort of conflict? It looks like this has been set since around v1.8.x (2020), and I see that Istio Controlz has been using that port for longer than this.

Given the port is only exposed on localhost for liveness and readiness probes, I think we can change the default value to something else without breaking existing users. I'll send a PR to change the default value.
