### ISSUE TITLE
CFP: make cilium-agent freak out if rp_filter config is wrong

### ISSUE THREAD

**Issue by samcday** [cilium/cilium#19909]
## Cilium Feature Proposal

When upgrading our Kubernetes workers from Ubuntu 20.04 -> 22.04 we encountered the issue described in #10645, since Ubuntu 22.04 ships with systemd 249.

The workaround is described in the [System Requirements](https://docs.cilium.io/en/stable/operations/system_requirements/#linux-distribution-compatibility-matrix) page, but I only managed to find it there because I was looking for it (I ran into this issue a few weeks ago trying to run Cilium on my local Arch workstation).

Given that the failure mode is really weird (host networking pods work fine, networked pods work fine when talking to same node), perhaps it would be worth checking the sysctl setting during cilium-agent startup, and fail to boot if it's not correctly set?

With Ubuntu 22.04.1 (the "real" LTS release, as everybody knows) around the corner, I suspect that many Cilium users are going to encounter this issue in the short term. Adding a check could save them (and folks responsible for Cilium issue triage!) a lot of time :)

**Comment by joestringer** [comment]
Thanks for the proposal.

My understanding of the issue is that Cilium attempts to configure the `rp_filter` settings, but systemd unfortunately overrides Cilium's configuration. Perhaps getting Cilium to instead detect & fail out is part of a better solution where we ensure that the `rp_filter` configuration is correct in the first place (ie the nodes are configured correctly).

I suspect that what we'll want to do is something like, provide an option for Cilium to configure the nodes if the administrator has not prepared the nodes for Cilium to successfully operate. If this setting is enabled, an init container of `cilium-agent` (or `node-init` DS) will attempt to create the systemd configuration to ensure that `rp_filter` is correctly configured on the node. Then separately, Cilium-agent could detect if this setting was configured or not and fail out if the configuration will cause problems later.

Another longer-term change would be to re-evaluate the datapath configuration that imposes the `rp_filter` requirements and see if we can rework those to avoid the dependency on `rp_filter`. But I think that this is a bigger effort than just ensuring that Systemd is configured in a way that it avoids clobbering Cilium's configuration.

**Comment by brb** [comment]
@joestringer One more solution would be to create a controller (in cilium-agent) which would be responsible for periodically monitoring `rp_filter` values of its managed devices, and reporting to user (e.g., via a log msg) if they change.

**Comment by aanm** [comment]
@dylandreimerink besides what we discussed offline, Martynas' proposal can also be done as an fallback as well.
