### ISSUE TITLE
CI: bpf-map-sync-cilium_lb4_backends_v2: map sync errors

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium#19993]
```
	 Controller Status:      30/31 healthy
	   Name                                          Last success   Last error   Count   Message
	   bpf-map-sync-cilium_lb4_backends_v2           never          4s ago       4       1 map sync errors 
```

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/1978/testReport/junit/Suite-k8s-1/21/K8sChaosTest_Connectivity_demo_application_Endpoint_can_still_connect_while_Cilium_is_not_running/
Sysdump: 
[e80c9b92_K8sChaosTest_Connectivity_demo_application_Endpoint_can_still_connect_while_Cilium_is_not_running.zip](https://github.com/cilium/cilium/files/8790853/e80c9b92_K8sChaosTest_Connectivity_demo_application_Endpoint_can_still_connect_while_Cilium_is_not_running.zip)

cc @brb

**Comment by brb** [comment]
Is https://github.com/cilium/cilium/pull/19352 striking us again? cc @borkmann

**Comment by eminaktas** [comment]
We are seeing this issue in our environment as well. Any idea what is causing this and is there a way to debug this error?

```bash
bpf-map-sync-cilium_lb4_backends_v2                               never          23s ago      31      1 map sync errors
```

```
level=debug msg="Starting periodic BPF map error resolver" file-path=/sys/fs/bpf/tc/globals/cilium_lb4_backends_v2 name=cilium_lb4_backends_v2 remaining=1 subsys=bpf
level=debug msg="BPF map error resolver completed" duration="37.753µs" file-path=/sys/fs/bpf/tc/globals/cilium_lb4_backends_v2 name=cilium_lb4_backends_v2 remaining=1 resolved=0 scanned=4 subsys=bpf
level=debug msg="Controller func execution time: 52.217µs" name=bpf-map-sync-cilium_lb4_backends_v2 subsys=controller uuid=79bbf788-b454-4fd6-ab32-39ea03d3a74c
level=debug msg="Controller run failed" consecutiveErrors=42 error="1 map sync errors" name=bpf-map-sync-cilium_lb4_backends_v2 subsys=controller uuid=79bbf788-b454-4fd6-ab32-39ea03d3a74c
`
``

**Comment by brb** [comment]
@eminaktas Can you post a sysdump for the node which has hit the sync errors?

**Comment by eminaktas** [comment]
I added the sysdump for the node here -> [cilium-sysdump-20220726-120708.zip](https://github.com/cilium/cilium/files/9188342/cilium-sysdump-20220726-120708.zip)

I have just upgraded the image version to 1.12.0, I didn't see the error message. However, the 1.11.7 version has the same error message.

**Comment by kks427** [comment]
This issue is coming in 1.11.9 also. 
`evel=warning msg="Failed to remove backend from maps" backendID=676176 error="Unable to delete backend 676176 (false): unable to delete element 676176 from map cilium_lb4_backends_v2: no such file or directory" subsys=service
level=warning msg="Failed to remove backend from maps" backendID=676022 error="Unable to delete backend 676022 (false): unable to delete element 676022 from map cilium_lb4_backends_v2: no such file or directory" subsys=service
level=warning msg="Failed to remove backend from maps" backendID=675582 error="Unable to delete backend 675582 (false): unable to delete element 675582 from map cilium_lb4_backends_v2: no such file or directory" subsys=service
level=warning msg="Failed to remove backend from maps" backendID=675585 error="Unable to delete backend 675585 (false): unable to delete element 675585 from map cilium_lb4_backends_v2: no such file or directory" subsys=service
level=error msg="Error while inserting service in LB map" error="Unable to add backend &{Key:676183 Value:ANY://192.168.99.246:27665}: Unable to update element for cilium_lb4_backends_v2 map with file descriptor 15: the map is full, please consider resizing it. argument list too long" k8sNamespace=ngcss-dev k8sSvcName=ntp-service-2 subsys=k8s-watcher`

**Comment by hemanthmalla** [comment]
We're seeing this in `1.11.10` as well.
```
Name                      Num entries   Num errors   Cache enabled
cilium_lb4_source_range   0             0            true
cilium_ipcache            11482         0            true
cilium_lb4_backends_v2    3070          2081         true
cilium_lb4_reverse_nat    4156          0            true
cilium_policy_02008       0             0            false
cilium_policy_02981       0             0            false
cilium_lxc                2             0            true
cilium_lb4_services_v2    4127          0            true
cilium_policy_03068       0             0            false
cilium_metrics            0             0            false
```

```
  Name                                  Last success   Last error   Count   Message
  bpf-map-sync-cilium_lb4_backends_v2   never          8s ago       190     2274 map sync errors
```
Max size for the map is the default value of `65536`

Why would we see `map is full` errors when the map isn't full ? 
Error msg also says `argument list too long`. Is the error msg wrong ?

**Comment by johannwagner** [comment]
We also ran into this at Cilium 1.11.14 with Kernel 5.15.89 on Flatcar. 

We mitigated the issue by rolling back to Cilium 1.11.6, but this may not be the root cause, since it only affected devices with newer kernels. After a roll back newer kernels seem to work fine.
