### ISSUE TITLE
Validate guides for 1.12 release 

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#20375]
Below is a set of platforms with a semi-randomly picked feature "getting started guide" links. The goal is to test each platform with at least one of the getting started guides. 
Secondary goal is to expose more people to the system.

Please test using https://docs.cilium.io/en/v1.12.0-rc3. For quick install guides, ensure to pass the version argument to the Cilium CLI to install the correct version.

Also take notes how much time it took you performing the Quick Install and how much time it took you testing the feature itself. Ideally the Quick Install should take < 15 minutes.

# Deadline: July 8th

### EKS (@NikAleksandrov)

- [x] [Quick Install](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/k8s-install-default/)
- [x] [IPSec](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/encryption-ipsec/#encryption-ipsec)

### GKE (@pippolo84) 

  - [x] [Quick Install](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/k8s-install-default/) 
  - [x] [Egress Gateway](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/egress-gateway/)

### K3s (@chancez)

  - [x] [Quick Install](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/k8s-install-default/)
  - [x] [L7-Aware Traffic Management](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/servicemesh/l7-traffic-management/)

### Kind (@raphink) 

  - [x] [Quick Install](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/k8s-install-default/)
  - [x] [HTTP policy](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/http/#apply-and-test-http-aware-l7-policy)

### RKE (@ti-mo)
   
  - [x] [Quick Install](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/k8s-install-default/)
  - [x] [Policy match on kube-apiserver](https://docs.cilium.io/en/v1.12.0-rc3/policy/language/#entities-based)
    * toEntities:
    * kube-apiserver

### AKS BYOCNI (@dylandreimerink)

  - [x] [Quick Install](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/k8s-install-default/)
  - [x] [Cluster Mesh](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/kind/#cluster-mesh)
  - [x] [Service affinity](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/clustermesh/affinity/) (Requires a cluestermesh setup)
     - [x] also enable hubble / relay / ui using cilium CLI and see what shows up.

### Openshift (@tommyp1ckles)

  - [x] [Quick Install](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/k8s-install-default/)
  - [x] [Kube Proxy Replacement](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/kubeproxy-free/#kubeproxy-free)

**Comment by raphink** [comment]
I've tested the two Kind guides. They both worked fine.

Just a note on the HTTP policy guide though.

We are instructed to install with the Quick Installation, which in the case of Kind creates a cluster with 4 nodes. Then we get:
```
kubectl -n kube-system get pods -l k8s-app=cilium
NAME           READY   STATUS    RESTARTS   AGE
cilium-5ngzd   1/1     Running   0          3m19s

kubectl -n kube-system exec cilium-1c2cz -- cilium endpoint list
```

From this:
1. It is not very clear that the goal of the first command is to find the name of the Cilium pod
2. In the case a Kind, there are 4 Cilium pods, and pods are running on any of the nodes, so it's not clear which one to pick

The easiest would be to provide a different Kind config with only a control plane (though this means cilium status will display an error iirc as it won't be able to deploy 2 operators).

**Comment by dylandreimerink** [comment]
I have tested the AKS BYOCNI guide, which works. Waiting for the clusters to come up takes the most time, even so ~15-20 min.

Currently working on the clustermesh guide, which is going less smoothly, will leave an additional comment as soon as I have figured out what is going wrong and how to improve the guide.

**Comment by chancez** [comment]
I tested the K3s install and the rancher-desktop install, everything went smoothly and quickly.

However, while testing the L7-Aware Traffic Management I ran into an issue which I wasn't clear on how to proceed:

so in our GSG we use cilium CLI, but in https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/servicemesh/l7-traffic-management/#installation, we’re upgrading via helm. Now I did expect this to work because CLI uses helm under the hood now, but it seems to only helm template, not helm install, so there’s no release for helm to upgrade, switching from the CLI to helm won't work.

I'm sure this issue is present in most of our docs. what are we expecting users to do in this situation?

`cilium upgrade` does not seem to support config updates, only image updates. so it’s not as a simple as turning `helm upgrade` into `cilium upgrade`, and running `cilium install` a 2nd time fails due to secrets already existing, so it is not idempotent either.

**Comment by chancez** [comment]
I've tested L7 docs and examples. I opened a PR here to resolve one issue: https://github.com/cilium/cilium/pull/20417

I also hit another issue, relating back to cilium cli, where port-forwarding to cilium's hubble port does not work, which is used in the  L7 LoadBalancing example. I worked around that by just running the hubble commands inside the cilium pod.

The other issue, also with the L7 LoadBalancing example is that `cilium connectivity test --test egress-l7` does not produce an `echo-other-node` K8s service. I’m using the `v0.11.10` CLI, so perhaps it’s just not in this CLI version? Not sure.

**Comment by sayboras** [comment]
> The other issue, also with the L7 LoadBalancing example is that cilium connectivity test --test egress-l7 does not produce an echo-other-node K8s service. I’m using the v0.11.10 CLI, so perhaps it’s just not in this CLI version? Not sure.

The echo-other-node is only applicable for multicluster or multi node cluster, can you try again with multi node cluster ?

**Comment by dylandreimerink** [comment]
So for the clustermesh guide I used AKS+BYOCNI clusters. But it turns out that if you follow the quick start guide for creating these clusters, you get clusters that use internal non-routable CIDR ranges for both the nodes and services (10.244.0.0/24). 

So if you then follow the clustermesh guide, all is well, until you run the connectivity test which fails to reach the other cluster.
All installation steps indicate success however and all statuses are green. Because the host CIDRs overlap, both clusters will loopback and connect to their own etcD and think that they are now connected to the other cluster. That was quite fun to debug.

So we should either change the AKS guide to suggest users to use non-default CIDR ranges or we include cluster creation steps in the clusermesh guide. While the guide does state the prerequisites https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/clustermesh/clustermesh/#prerequisites. We have no instructions on how to actually fix clusters which don't meet these requirements.

**Comment by dylandreimerink** [comment]
Another thing is that the v1.12-RC3 docs don't include the [Service affinity](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/clustermesh/affinity/) guide. The link returns 404 and the doesn't appear in the menu. This page only exist on the "latest" version of the docs https://docs.cilium.io/en/latest/gettingstarted/clustermesh/affinity/

**Comment by pippolo84** [comment]
I tested the Egress Gateway feature on GKE.
Unfortunately, the feature seems to be broken, so I opened an issue: https://github.com/cilium/cilium/issues/20432

Some other things that can be improved in the documentation:

- This guide suggests to use `helm upgrade` to deploy the new CIlium version. Just like @chancez reported, to do that, Cilium must have been first installed via helm, so it is worth mentioning.
- The `helm upgrade` command misses the option `--set rollOutCiliumPods=true`. Without this, Cilium pods won't be restarted and thus they won't read the updated ConfigMap for Egress Gateway.
- If possible, in [this section](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/egress-gateway/#compatibility-with-cloud-environments) it may be worth giving the user a way to test if `--set egressGateway.installRoutes=true` is really needed.
- (nit) In [this section](--set egressGateway.installRoutes=true) the final note `Regardless of which way the egress IP is configured ...` is valid for all the three possible ways in which the egress IP is configured. Then it should be moved after the last code section and outside of the numbered list.
- The [example policy](https://raw.githubusercontent.com/cilium/cilium/v1.12.0-rc3/examples/kubernetes-egress-gateway/egress-nat-policy-egress-gateway.yaml) cannot be applied as is. The documentation should report that the user has to change the `destinationCIDRs` with its designated external IP address. Same goes for the `egressIP` option, but I think it should be better to simply leave this empty, so to let the agent use the first IPv4 assigned to the interface for the default route.
- The documentation should specify that a node different from the one where the `mediabot` pod is running must be used as the egress gateway. Besides, it should also point out that such node should be labeled with `egress-node=true` so to be correctly selected by the policy.

**Comment by tommyp1ckles** [comment]
Mostly complete the kube-proxy getting started guide. Here are my findings:

1. Struggled to get a functioning cluster with kubeadm initially, was trying to create one with containerd as the cri but was getting hard to troubleshoot crashing issues. _Not really related to this guide_, but worth noting since I only resolved this by switching to using docker+cri-dockerd. We might want to consider making the guide a bit more opinionated to make things easier for someone not familiar with kubeadm.
2. Guide was overall good, making a PR for some small improvements to help clarify some sections but overall I had no problem. Should take less than 5 minutes once you actually have a functioning cluster.
3. Ultimately I ran into cross node connectivity issues after running through the steps, didn't have time to dig too far into those so I made an issue to resolve those #20434 (it's possible these are related to my particular setup, but it would be worth solving regardless to help readers avoid similar pitfalls).

Link to mentioned issue: #20434

**Comment by dylandreimerink** [comment]
I go AKS(BYOCNI) + Clustermesh working, but it involved some additional configuration work. I explained the process in a dedecated AKS-to-AKS clustermesh guide #20439

**Comment by dylandreimerink** [comment]
Tested service affinity using the docs on 'latest'. That all seems to work except for one small thing in the example commands which I updated in #20442. 

Also took a look at hubble UI. That looks as expected. When service affinity is local only the local flows show up, when service affinity is remote the flows to the remote endpoint show up, with no affinity set both show up.

**Comment by ti-mo** [comment]
I set up a single-node RKE deployment. No issues encountered during installation.
`toEntities: - kube-apiserver` works, but not in combination with e.g. a `toPorts` clause. I assume that is a known limitation.

However, it doesn't seem like L7 proxying works on RKE:

```
  [.] Action [client-egress-l7/pod-to-pod/curl-1: cilium-test/client2-686d5f784b-dkpx8 (10.0.0.243) -> cilium-test/echo-same-node-7c9dcd594-rnbtr (10.0.0.202:8080)]
  📄 Following flows...
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://10.0.0.202:8080" failed: command terminated with exit code 28
  ℹ️  curl output:
  curl: (28) Connection timeout after 5001 ms
:0 -> :0 = 000

...

  📄 Flow logs for peer cilium-test/client2-686d5f784b-dkpx8:
  ❓ [0] Jul 11 08:10:12.430: cilium-test/client2-686d5f784b-dkpx8:47736 -> cilium-test/echo-same-node-7c9dcd594-rnbtr:8080 L3-L4 REDIRECTED (TCP Flags: SYN)
  ❓ [1] Jul 11 08:10:12.430: cilium-test/client2-686d5f784b-dkpx8:47736 -> cilium-test/echo-same-node-7c9dcd594-rnbtr:8080 to-proxy FORWARDED (TCP Flags: SYN)
```

All connectivity tests involving L7 proxying (both DNS and HTTP) are failing consistently on RKE.

**Comment by sayboras** [comment]
seems like we missed @raphink in assignee before.
