### ISSUE TITLE
Kube Proxy Replacement GSG Guide connectivity issues on GCP: Cilium not recognized as CNI

### ISSUE THREAD

**Issue by tommyp1ckles** [cilium/cilium#20434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Running through the guide for creating a cluster with [Cilium kube-proxy](https://docs.cilium.io/en/v1.12.0-rc3/gettingstarted/kubeproxy-free/#kubeproxy-free) replacement using kubeadm, I was able to create a cluster with kube proxy replacement with all cilium status fields reporting that it was functioning correct.

However, when testing the specified nginx requests began to fail intermittently as they where load balanced over remote nodes in the cluster. It appears as though only connections proxied to the local node where succeeding. In my test cases it seemed like the configuration specified by the guide has connectivity issues.

To reproduce:

1. Create kubeadm cluster with at least one node via the guide using docker+cri-dockerd CRI.
2. Follow guide up until you test the node port by curling it, curl multiple times until the connection fails.

This issue is in reference to: #20375

### Cilium Version

v1.12.0-rc3

### Kernel Version

Linux version 5.10.0-15-cloud-amd64 

### Kubernetes Version

v1.24.2

### Sysdump
[cilium-sysdump-20220708-161540.zip](https://github.com/cilium/cilium/files/9073521/cilium-sysdump-20220708-161540.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
(@tommyp1ckles would need some more info that would be helpful for debugging, but we can also sync via slack.)

**Comment by aditighag** [comment]
@tommyp1ckles Please collect sysdump from the affected cluster, better yet leave the cluster as-is in the problematic state.

**Comment by borkmann** [comment]
> @tommyp1ckles Please collect sysdump from the affected cluster, better yet leave the cluster as-is in the problematic state.

Wasn't it posted here? [cilium-sysdump-20220708-161540.zip](https://github.com/cilium/cilium/files/9073521/cilium-sysdump-20220708-161540.zip)

Also Cc'ing @nathanjsweet for visibility given this happened on OpenShift (details also outlined in https://github.com/cilium/cilium/issues/20375).

**Comment by aditighag** [comment]
>However, when testing the specified nginx requests began to fail intermittently as they where load balanced over remote nodes in the cluster. It appears as though only connections proxied to the local node where succeeding.

Sounds like `rp_filter` could be the culprit.

**Comment by aditighag** [comment]
Looked into the cluster - the deployed nginx pods are not managed by cilium.  `kubectl get ciliumendpoints` returns empty, and `cilium endpoints list `doesn't show core-dns or the nginx pods. Looking at the IP addresses for these pods, they are on the docker network. @tommyp1ckles Is there a chance the nginx pods were deployed *before* cilium pods were in the ready state?

We have this step in the guide prior to deploying the nginx pods - 

`After deploying Cilium with above Quick-Start guide, we can first validate that the Cilium agent is running in the desired mode:`

In general, we need to restart unmanaged (non-host networked) pods once Cilium is up and running so that they are managed by Cilium. Looks like this step is missing in the kube-proxy free guide. We have a script to do that, but I can't seem to remember the name. Can you add this to your documentation improvement PR? Thanks!

**Comment by joestringer** [comment]
@tommyp1ckles @aditighag what's the latest on this issue? I see both `need-more-info` and `needs/triage`, but it doesn't make sense to have both labels. What's the next step?

I've removed the `release-blocker/1.12` label because I see no progress in the last 27 days. If the issue is not being prioritized, it doesn't make sense to block releases on it.
