### ISSUE TITLE
Cilium Operator leases have a default TTL of 60 seconds

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#20958]
Contrary to the cilium-agent, the cilium-operator does not have a kvstore TTL flag. We should add one because right now it is using the default value of etcd's library which is 60 seconds.

**Comment by NikhilSharmaWe** [comment]
@aanm Please inform me if this is reasonable

So we have to define a new flag in [operator/cmd/flags.go](https://github.com/cilium/cilium/blob/master/operator/cmd/flags.go) for specifying the value `Time-to-live for the KVstore lease` and use them instead of `defaults.LockLeaseTTL` in the places like https://github.com/cilium/cilium/blob/master/operator/cmd/kvstore_watchdog.go#L61

**Comment by aanm** [comment]
> @aanm Please inform me if this is reasonable
> 
> So, we have to define a new flag in [operator/cmd/flags.go](https://github.com/cilium/cilium/blob/master/operator/cmd/flags.go) for specifying the value `Time-to-live for the KVstore lease` and use them instead of `defaults.LockLeaseTTL` in the places like https://github.com/cilium/cilium/blob/master/operator/cmd/kvstore_watchdog.go#L61

@NikhilSharmaWe I think it just as simple as adding this code https://github.com/cilium/cilium/blob/d7af9ef37fa772ac8379d82460ff78cdfc12386e/daemon/cmd/daemon_main.go#L538-L540

in the operator's flags.go
