### ISSUE TITLE
`nodeinit.reconfigureKubelet` seems to break kubelets on Kubernetes v1.24.0 and newer

### ISSUE THREAD

**Issue by BradLugo** [cilium/cilium#21049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Helm installation documentation for GKE suggests to `--set nodeinit.reconfigureKubelet=true` and explains why a user will need that option. One result of using that option is `nodeinit` will add the `--network-plugin=cni` flag to the kubelet service, but this flag is removed as of Kubernetes v1.24.0. Enabling this flag on node pools that are on Kubernetes v1.24.0 or newer seems to cause the kubelets to run in an infinite cause loop.

Additionally, the `nodeinit.reconfigureKubelet` isn't documented in the Helm documentation, so it's difficult for a user to understand how and why it's used (and when it shouldn't be).

### Cilium Version

v1.12.1

### Kernel Version

5.10.123

### Kubernetes Version

v1.24.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bmcustodio** [comment]
( @michi-covalent I'm not sure I'll have cycles to work on this soon, so it might be better to assign someone else since it's `priority/high` 🤐 )

**Comment by squeed** [comment]
Probably the best way to fix this is, in `install/kubernetes/cilium/files/nodeinit/startup.bash`, we should autodetect if the kubelet is using dockershim or CRI, and just not set `--network-plugin` and `--cni-bin-dir` if that's the case.

Alternatively, we could get the kubelet's version.

**Comment by pippolo84** [comment]
After removing the two offending flags based on the k8s version another issue arose.
Starting from containerd 1.6, that is used on GKE with node version 1.24 and above, a CNI configuration must be specified, otherwise the following error is reported:

`error="cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config"`

and containerd stops responding to the kubelet:

`Error: failed to run Kubelet: unable to determine runtime API version: rpc error: code = Unknown desc = server is not initialized yet`

To avoid this, the proposed fix writes a dummy CNI config to enable containerd starting correctly and finally letting the `cni-install.sh` script run from the `cilium-agent` DaemonSet.
