### ISSUE TITLE
helm reference  missing helm option documents

### ISSUE THREAD

**Issue by vincentmli** [cilium/cilium#21107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

first noticed in https://github.com/cilium/cilium/pull/20639#issuecomment-1197895181 where when the helm option is commented out with `#`,  after `make -C install/kubernetes`, and `make -C Documentation`, the `install/kubernetes/cilium/README.md` and `Documentation/helm-values.rst` is not updated with commented out helm options.

noticed this same issue in slack with another user who tried  to find out how to use helm to set cilium agent option `ipv4-native-routing-cidr` which has helm option  `ipv4NativeRoutingCIDR`, but is commented out, so it is missing in https://docs.cilium.io/en/latest/helm-reference/.  according to @gandro this might be helm-docs bug, so file this issue to track the bug. the workaround is to uncomment these  helm options.  should we wait for the bug to be resolved or I could send PR to uncomment these helm options ?

### Cilium Version

1.12.1

### Kernel Version

irrelevant

### Kubernetes Version

irrelevant

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
> the workaround is to uncomment these helm options. should we wait for the bug to be resolved 

I don't think we know the root cause yet. We did some upstream patches before (https://github.com/norwoodj/helm-docs/pull/99), but seems they are incomplete (cc @bmcustodio @sayboras). See also https://github.com/cilium/cilium/issues/20530 for a similar report.

> I could send PR to uncomment these helm options ?

I'm would to accept a PR which does this (assuming un-commenting the option or setting it to nil does not affect the generated manifest).
