### ISSUE TITLE
Running CI locally no longer possible (due to image issues)

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#21241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I attempted to follow the documentation at https://docs.cilium.io/en/latest/contributing/development/dev_setup/#launch-ci-vms -- specifically, running

```
K8S_VERSION=1.18 K8S_NODES=1 ./vagrant-local-start.sh
```

However, it fails because it cannot pull all the desired images:

`ctr: failed to resolve reference "quay.io/isovalent/gke-test-cluster-requester:fe34abda190c31680968ba62634c788428d91706": pulling from host quay.io failed with status code [manifests fe34abda190c31680968ba62634c788428d91706]: 401 UNAUTHORIZED`

### Relevant log output

```shell
ctr: failed to resolve reference "quay.io/isovalent/gke-test-cluster-requester:fe34abda190c31680968ba62634c788428d91706": pulling from host quay.io failed with status code [manifests fe34abda190c31680968ba62634c788428d91706]: 401 UNAUTHORIZED
k8s1-1.16: ctr: failed to resolve reference "quay.io/cilium/cilium:latest": quay.io/cilium/cilium:latest: not found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
The first failure/log message should be fixed by #21362. For the second failure, I think it's worth digging into where this `cilium/cilium:latest` gets generated from because we deliberately avoid having such a tag. If it's looking for a development "tip of master" image, this should be `quay.io/cilium/cilium-ci:latest` instead.

**Comment by Shunpoco** [comment]
@squeed @joestringer 
I caught the same error and found the reason why the script tries to pull `cilium/cilium:latest`.
1. If we don't set the `PRELOAD_VM` option, [vagrant-local-create-box.sh](https://github.com/cilium/cilium/blob/master/test/vagrant-local-create-box.sh#L13) set `PRELOAD_VM=true` then run `vagrant up`.
2. The Vagrantfile calls `./provision/k8s_install.sh` and the shellscript calls `./test/provision/container-images.sh test_images .` [here](https://github.com/cilium/cilium/blob/master/test/provision/k8s_install.sh#L598).
3. In `provision/container-images.sh`, `test_images` function checks necessary images by [doing grep all files in the directory](https://github.com/cilium/cilium/blob/master/test/provision/container-images.sh#L36-L37) and pulls these images.

But in the step 3, because the process is in the repository root directory, `test_images` check all files including documents to get image names.

If we try the same command as test_images in the repository root directory, we get such result and it contains some `latest` packages:
```console
$ grep -rI --no-filename "quay.io" .     | sed -nEe   's#.*(quay.io/[-_a-zA-Z0-9]+/[-_a-zA-Z0-9]+:[-_.a-zA-Z0-9]+).*#\1#p' | sort | uniq
quay.io/cilium/alpine-curl:v1.3.0
quay.io/cilium/alpine-curl:v1.5.0
quay.io/cilium/cilium-bpftool:d3093f6aeefef8270306011109be623a7e80ad1b
quay.io/cilium/cilium-builder:1b8f97cf70e2a4e7b0609f259d9540523c50cc9f
quay.io/cilium/cilium-checkpatch:2f0f4f512e795d5668ea4e7ef0ba85abc75eb225
quay.io/cilium/cilium-cli-ci:latest
quay.io/cilium/cilium-dev:scale-test-2019-03-12
quay.io/cilium/cilium-dev:scale-test-2019-03-13
quay.io/cilium/cilium-dev:vetcd-v3.3.11-hf1-aanm
quay.io/cilium/cilium-envoy:bdb324791884636aea84b789466c3a538b1d4970
quay.io/cilium/cilium-iproute2:f882e3fd516184703eea5ee9b3b915748b5d4ee8
quay.io/cilium/cilium:latest
quay.io/cilium/cilium-llvm:3408daa17f6490a464dfc746961e28ae31964c66
quay.io/cilium/cilium-runtime:1a8102930aa1ec5d82312abc941edb4097db000a
quay.io/cilium/cilium:v1.10.1
quay.io/cilium/cilium:v1.10.17
quay.io/cilium/cilium:v1.11.11
quay.io/cilium/cilium:v1.12.1
quay.io/cilium/cilium:v1.12.4
quay.io/cilium/cilium:v1.13
quay.io/cilium/cilium:v1.9.5
quay.io/cilium/clustermesh-apiserver:v1.10.2
quay.io/cilium/hubble-relay:v1.9.5
quay.io/cilium/hubble:v0.10.0
quay.io/cilium/image-compilers:5569a29cea6b3ad50aeb03102aaf3dc03841197c
quay.io/cilium/image-maker:7de7f1c855ce063bdbe57fdfb28599a3ad5ec8f1
quay.io/cilium/image-tester:dd09c8d3ef349a909fbcdc99279516baef153f22
quay.io/cilium/istio_pilot:1.10.6
quay.io/cilium/istio_proxy:1.10.6
quay.io/cilium/json-mock:v1.3.0
quay.io/cilium/json-mock:v1.3.2
quay.io/cilium/log-gatherer:v1.1
quay.io/cilium/net-test:v1.0.0
quay.io/cilium/operator-dev:scale-test-2019-03-12
quay.io/cilium/operator-generic:latest
quay.io/cilium/operator-generic:v1.12.1
quay.io/cilium/operator-generic:v1.9.5
quay.io/cilium/scruffy:v0.0.2
quay.io/cilium/test-verifier:2ecf56b4ea57576e9d92d34407898e5d14e80aa3
quay.io/coreos/etcd-operator:v0.9.3
quay.io/coreos/etcd:v3.1.0
quay.io/coreos/etcd:v3.3.20
quay.io/coreos/etcd:v3.3.20-arm64
quay.io/coreos/etcd:v3.3.25
quay.io/coreos/etcd:v3.4.13
quay.io/coreos/etcd:v3.4.7
quay.io/pires/docker-elasticsearch-kubernetes:5.6.2
```

But as @joestringer said, because we don't have `latest` tags for our images, the script fails.

I guess that this issue has happened from [this commit](https://github.com/cilium/cilium/commit/9d4b1bb322e955a715b2a2b9ac610e0dfbd2284a#diff-554ccff80c857908a80602a41b8ac4ed1b1621afc0c256d4c93a135bb8ff2b2dL30).

So what we have to do is specifying `test/k8s` directory in [the part](https://github.com/cilium/cilium/blob/master/test/provision/k8s_install.sh#L598) like [the commit](https://github.com/cilium/cilium/commit/9d4b1bb322e955a715b2a2b9ac610e0dfbd2284a#diff-35d19c00b0c7e4a0020887617a0fa50a2a5c1fce46fee7665b37f097987c5b01R116).

**Comment by Shunpoco** [comment]
Could you reopen the issue? @squeed , @joestringer 
I'd like to fix this problem.

**Comment by pchaigno** [comment]
@Shunpoco Nice troubleshooting!
