### ISSUE TITLE
CFP: make cilium ingress work on bare metal without any extra components

### ISSUE THREAD

**Issue by farcaller** [cilium/cilium#21390]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**

Currently, the docs state: 

> The ingress controller creates a service of LoadBalancer type, so your environment will need to support this.

Other ingress controllers running on bare metal can make use of hostPort (e.g. ingress-nginx w/ cilium as CNI works like that). Cilium requires a load-balanced service which, in turn, requires extra components (e.g. metallb).

**Describe the feature you'd like**

For trivial setups it'd be great if cilium listened on the host network's tcp80 and tcp443 and served as an ingress without any extra component requirements.

**(Optional) Describe your proposed solution**

Given that envoy already runs in the host network, it should be only the matter of listening on the relevant ports.

**Comment by aanm** [comment]
cc @youngnick

**Comment by chancez** [comment]
I was just looking at how to run the ingress without a LoadBalancer service as well and found this issue. I agree that it would be nice if we could configure some hostPorts for envoy to listen on at all times, then a user could direct traffic to these hostPorts through whatever mechanisms they have available in their environment.

**Comment by youngnick** [comment]
I agree that this would be a great feature, but I think the problems we need to incorporate solutions for into a design are:
- How do you request the behavior, and target specific ports? For Ingress, this will need to be annotations, but we should really also be thinking about how to do a similar thing for Gateway API objects (which is harder because they include the port the _client_ should connect on in the listener definition, not any intermediate ports, which is what we have here).
- How do you keep track of what port is assigned to what Ingress/Gateway/whatever? If the port is being used by some external (possibly not k8s-aware) system, then it probably needs to be statically defined, rather than dynamically allocated. But dynamic allocation also seems like it would be useful (otherwise you're stuck keeping track of hostPorts on a spreadsheet somewhere or something).

However, doing this will mean that we can give people TCPRoute and UDPRoute Gateway API support of some sort on bare metal, which seems very useful.

**Comment by youngnick** [comment]
Hmm, I think this is still worth doing, but it may be a while before we get to it.
