### ISSUE TITLE
Cilium Policy Version Increments Frequently 

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#2141]
I'm seeing the Revision reported by "cilium policy get" update frequently, in scenarios where I would not have expected it. This seems related to the creation of containers when there is already a policy enforced.

I am creating an application that consists of 15 containers, and there is already an HTTP-aware cilium network policy enforced when I create those containers.  

0) New minikube with fresh cilium lastest installed. 

1) I first run a script that does 3 kubectl calls to delete cilium network policies, one in each of 3 namespaces. This increments the policy revision to 6. Note: deleting an already empty policy version probably shouldn't increment at all, but that's not really the main issue I'm reporting here. 

2) I then apply the L7-aware security policy.  This is a legit policy change, and increments the revision number to 7. 

3) I deploy 15 containers using kubectl . This takes quite some time to stabilize, as pods come in and out of ready state. I'm guessing in some cases we need to regenerate some/all BPF programs multiple times, as we learn about container IDs that we didn't know about before? Maybe that can be optimized, but the strange thing is that when things finally stabilize, the policy revision number of 37. So it seems like we bumped the policy revision number twice per new containers (i.e., 6 + 1 + 2 * (# containers) = 30).

Expected behavior. Policy revision number would be 1 (or maybe 7), as that is the number of actual policy changes that happened from a user perspective.

After about 45 minutes, the policy revision is still 37, so it does not seem to be any kind of a background thing. It seems to happen only when endpoints are being created (and perhaps destroyed?)

**Comment by raybejjani** [comment]
I think this is intended, although not user intuitive, behaviour. We increment the policy revision when we regenerate an endpoint (https://github.com/cilium/cilium/blob/master/pkg/endpoint/policy.go#L725) which happens for a variety of reasons, including the endpoint being created (we iterate over all endpoints and trigger a regenerate). We do have some short-circuits to avoid pointlessly regenerating (most obvious in that the revision doesn't increment every 5 minutes when we regenerate all endpoints) but that doesn't seem to apply here, meaning something is actually changing in the internal state to warrant the full rebuild.

I'll close this since there isn't much we can do unless we intend to stop exposing this value or change it's semantics (which is hard since it's an internal implementation).
