### ISSUE TITLE
Calculate estimated "TTL" for connection entries (zombies) in the FQDN cache

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#21540]
`connection` entries are zombie entries meaning their TTL have expired. These entries when shown with `cilium fqdn cache list` have a nil expiration time. Given that these entries are GC'd when the CT GC runs, unlike `lookup` entries, there isn't a straightforward expiry time because there's no concept of TTL for these entries. However, we can estimate when the next CT GC runs so theoretically we can provide an estimated expiry time to ease debuggability / visibility into when these entries are likely to be cleaned up.

```
3283       connection   google.com.       0      0001-01-01T00:00:00.000Z   52.218.1.32                                  
3283       connection   cilium.io.        0      0001-01-01T00:00:00.000Z   52.218.1.33
```                    

Idea by @joestringer

**Comment by joestringer** [comment]
:+1: Maybe even rather than "estimate", instead, when CT GC calculates its next run time and goes to sleep.. store that timestamp somewhere that can be easily read by the DNS cache. Then, DNS cache can just fetch & populate the field whenever it is expiring an entry.

Then if CT GC does *not* expire an entry, we would also need to refresh this timestamp for all connection/zombie entries.
