### ISSUE TITLE
Support DSR with IPIP in CNI mode

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#21876]
PR https://github.com/cilium/cilium/pull/18449 proposes to add support for DSR by encapsulating packets in IP. The motivation here is that the current DSR approach which uses IP options can lead to a situation where packets get dropped in the core of the network, because the routers don't support the IP options. In this case, the router sends this to the slow path which cannot handle the rate of traffic.

Tasks:
- [ ] Rebase
- [ ] Review changes to ipv4_policy handling with nodeport
  - https://github.com/cilium/cilium/pull/18449#discussion_r891577527
- [ ] See if we can avoid the DSR_ENCAP_MODE #ifdefs
  - https://github.com/cilium/cilium/pull/18449#discussion_r891587259
- TBD

**Comment by brb** [comment]
cc @julianwiedmann

**Comment by joestringer** [comment]
@ysksuzuki and I were discussing this today and took notes on some initial steps, he will reopen a fresh issue and update with the latest status from the PR and what remains to get this feature into the tree.

**Comment by ysksuzuki** [comment]
As far as I looked at the PR, the remaining tasks are as follows.

1. Rebase
2. Fix some unresolved comments
3. Add pure IPIP option which doesn't rely on IP options

As for 3, we need to mention the limitation in docs and ensure that a backend port matches a service port as well. In the pure IPIP mode, the backend port matches a service port, because with the IP-in-IP encapsulation without IP option, we cannot have L4 different ports.

@brb suggested it so that users can avoid the risk of SYN packets being dropped by routers that do not support IP options and can parse the inner IP header.

Please correct me if I'm wrong.

**Comment by ymmt2005** [comment]
> 3. Add pure IPIP mode which doesn't rely on IP options

I think Generic UDP Encapsulation (GUE) may be used to encapsulate
IPIP packets. GUE allows adding arbitrary security/private data
in the header so that we can avoid IP options.

GUE is also preferable to IPIP regarding network performance since
many network peripherals have optimizations for UDP packets.

https://datatracker.ietf.org/doc/html/draft-herbert-gue-01

**Comment by ysksuzuki** [comment]
@borkmann and I were talking about this. He said that we should avoid using IP option because of the GRO perspective as well as the risk that Syn packets with IP option are dropped.  However, the limitation that service port and backend port have to be the same is critical in our use case. So I will create a CFP that suggests using tunneling technologies such as GENEVE,  GUE for DSR to lift the limitation.
