### ISSUE TITLE
docs: search doesn't work in mobile

### ISSUE THREAD

**Issue by xmulligan** [cilium/cilium#21938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I’m unable to search at [docs.cilium.io](http://docs.cilium.io/) from my iPhone using safari, google or Firefox.
The link with the three lines to bring up the side menu with the search bar sits behind the cilium and GitHub stars window.

![image](https://user-images.githubusercontent.com/29048870/199027761-27e3ed8d-d817-4f13-8899-48aa20b5b728.png)
![image](https://user-images.githubusercontent.com/29048870/199027801-f8527d22-e00a-4c90-8497-41094aec305d.png)

### Cilium Version

1.12

### Kernel Version

n/a

### Kubernetes Version

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bolotskydev** [comment]
Hey guys, I did a little investigation and know precisely how to fix it. You just throw in along [this line](https://github.com/cilium/cilium/blob/10cf878cf875deb30e7b8451fe417c2424624752/Documentation/_themes/sphinx_rtd_theme/sass/_theme_layout.sass#L366) this sass snippet: 

```diff
background: $section-background-color
+.wy-github-stars
+  display:none;
```
So that it looks like this:
```
+media($tablet)
  .wy-body-for-nav
     background: $section-background-color
    .wy-github-stars
      display:none;
```

<details>
<summary>Before</summary>
The CTA buttons get wrapped and hide the burger icon.
<img width="611" alt="image" src="https://user-images.githubusercontent.com/32940211/202486832-e22e57fe-9d10-43d5-a73d-7aea59941cc8.png">


</details>

<details>
<summary>After</summary>

Notice the github and slack buttons are gone. No worries though as they a bit too much for the header to contain on mobiles 😓 

<img width="654" alt="image" src="https://user-images.githubusercontent.com/32940211/202484871-c928538d-3e5e-4827-a278-b4325d4b7639.png">

And here is that shy search box:

<img width="652" alt="image" src="https://user-images.githubusercontent.com/32940211/202485796-256af3b6-470c-4888-9ea5-44ec706ed518.png">

</details>

**Comment by bolotskydev** [comment]
@xmulligan honestly, I have no idea how to run this thing, so I wasn't able to verify it, but I bet the solution is going to work.

**Comment by kimstacy** [comment]
@bolotskydev Thank you for the helpful attempt. I believe you were referencing a file that doesn't exist anymore. You can find Cilium's custom Sphinx RTD theme [here](https://github.com/cilium/sphinx_rtd_theme/). Here's a [direct link](https://github.com/cilium/sphinx_rtd_theme/tree/v1.0) to the theme's **v1.0** branch.
