### ISSUE TITLE
NodePort BPF with L7 netpol is broken for N/S when request is sent to node running SVC backend 

### ISSUE THREAD

**Issue by brb** [cilium/cilium#21955]
First issue is https://github.com/cilium/cilium/issues/21954. The second issue is that the L7 proxy will do the TCP handshake on behalf of the pod meaning that all replies to an outside client won't be rev-DNAT-ed (bpf_lxc is doing rev-DNAT for NodePort BPF). To fix this we should move the rev-DNAT to `bpf_host @ eth0`, as it was suggested by https://github.com/cilium/cilium/pull/17504. 

The bonus issue is DSR when an intermediate LB node is hit first. In this case, the IP opt/ext is dropped by the proxy. The fix is to handle the opt / ext in bpf_host (same as rev-DNAT).

**Comment by brb** [comment]
> bpf_lxc is doing rev-DNAT for NodePort BPF

`bpf_lxc` is doing the rev-DNAT via the tailcall which you linked in your comment. The problem with the L7 proxy reply path is that it doesn't involve bpf_lxc, so nobody can do the rev-DNAT.

**Comment by pchaigno** [comment]
> To fix this we should move the rev-DNAT to `bpf_host @ eth0`, as it was suggested by #17504.

I think that would be a good thing in any case:
1. By doing this, we ensure the Linux stack sees consistent IPs & ports for forward and reply traffic. It's less likely to drop packets because the connection looks invalid (e.g., forward is DNATed but not reply).
2. By moving DSR to bpf_host, it will also make it easier to pipe the DSR information from e.g. a tunnel (IPIP or GENEVE) that we decapsulate at the native device to the DSR logic. Currently, with DSR logic at bpf_lxc, we need a special way to pass that information :( 

cc @julianwiedmann

**Comment by brb** [comment]
> I think that would be a good thing in any case:

One more:

3. Fixes N/S for service endpoints running in a host netns.
