### ISSUE TITLE
CFP: Per-Node configuration overrides

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#22036]
### Background

There is sometimes a need to update or override configuration on one or more nodes. Some possible use-cases include
- Rolling out disruptive changes
- Rolling out changes that need external coordination
- Deploying Cilium in to an existing cluster

#### 1: Rolling out kube-proxy-replacement
Consider a cluster with kube-proxy. The administrator would like to enable Cilium's kube-proxy-replacement feature (KPR). However, to do this, each node must "simultaneously" disable the kube-proxy daemonset as well as enable cilium KPR. Labels on a node naturally lend themselves to this situation

#### 2: Rolling out Cilium to an existing cluster
Imagine deploying Cilium node-by-node in an existing cluster. There are two sets of nodes: migrated and unmigrated. These two sets of nodes might need very different configuration.

#### 3: Platform-managed, administrator overridden
In a cluster where Cilium is maintained by a Platform team, individual cluster owners still may need the ability to tweak certain settings.

### CiliumConfigOverrides CRD
We create a new CRD, `CiliumConfigOverride`. This would allow for overriding arbitrary key-value pairs from the `cilium-config` ConfigMap.

CiliumConfigOverride would have a NodeSelector indicating to which nodes it applied. In the event of conflicting overrides, the lexicograpical ordering of CR names would be used.

Exampe:
```yaml
apiVersion: cilium.io/v2
kind: CiliumConfig
metadata:
  name: run-kube-proxy
spec:
  nodeSelector:
    - matchLabels:
        io.cilium.migration/kube-proxy-replacement: true
  rawConfig:
    kube-proxy-replacement: strict 
```

An empty NodeSelector would apply to all nodes.

### Node annotations
For quick, one-off changes, individual keys could be overridden with annotations on the Node. `io.cilium.config/<KEY>: <VALUE>`

### Configuration resolution

This CR would be read by an InitContainer, which would produce a folder with structure identical to the pre-existing `cilium-config` ConfigMap. Nothing would change for the configuration parsing code in the agent or operator (for now).

By default, the order of precedence would be ConfigMap, then Overrides, then Node annotations. To support case 3, however, the resolution order will be configurable.

There is a more detailed design document at https://docs.google.com/document/d/1_1AsgmY2W2apUUttt0WOoGqlyVEPTK1REokzON-RmR8

**Comment by squeed** [comment]
Hit enter too early. Hold please.

**Comment by squeed** [comment]
@varunmar Trying to split these by namespaces strikes me as a bit fragile.

Instead, one option would be to grand the cluster operator access to the cilium-config ConfigMap, while not allowing access to the CiliumConfigOverrides CRs. Then, the "frozen" settings can go in a CiliumConfigOverride. Since those take precedence, the operator is free to change cilium-config (maybe even with Helm) without fear of breaking anything.

**Comment by varunmar** [comment]
More thinking - 
We came to the same conclusion - It makes little sense to try to handle namespaces. In fact, it is possible to make the case that these overrides are cluster-scoped to begin with, and shouldn't be in a namespace at all. However, if they're in a namespace, they should just all be treated the same.

There are two aspects of the configuration options - setting overrides, and setting defaults. If a config option is not specified, we do want it to fall back to the "infra role" set option, which may or may not match the built-in defaults of the cilium agent/operator/clustermesh-apiserver.

Another use case we have is when the cluster operator doesn't even have access to the namespace that system pods are run in. This is the case for GKE autopilot, for example.

**Comment by squeed** [comment]
>  If a config option is not specified, we do want it to fall back to the "infra role" set option, which may or may not match the built-in defaults of the cilium agent/operator/clustermesh-apiserver.

I'm trying to think of a nice clean way to design the API to support existing installations, temporary administrator overrides, and "frozen" settings from a platform team. We've somewhat painted ourselves in a corner by declaring the `CiliumConfig` type in the OLM operator [see here](https://github.com/cilium/cilium-olm/blob/master/ciliumconfig.v1.12.yaml), so we can't create any other types with that name now.

My first idea: We add two new helm values that tweak the behavior of the config resolver:

* `configOverrides.namespaces` : a list of (additional) namespaces to search for CiliumConfigOverrides. Then you can give cluster owners the ability to tweak certain settings
* `configOverrides.sources`: a list of configuration sources, in order of precedence. The default would be `configmap, overrides, node`, but you could change this to `overrides, configmap` for your use case.

How does that sound?

**Comment by varunmar** [comment]
I'm starting to think that namespaces are not a good idea for this new CRD in the first place. I think we should just get rid of them - either we make the CRD cluster scoped, or we treat all the namespaces equally (maybe with the alphabetical tie breaking you had in the first place)

Changing the order of precedence fixes the namespace permissions problem but not the defaulting-vs-overriding problem.
Let me see if an example helps - 
The compiled-in default for the `debug-verbose` field is empty.
The infrastructure operator wants this to be `datapath` by default.
However, the cluster operator should be able to edit this for their own purposes, either adding something, changing to to empty, etc.

So the policy would be - if the cluster operator specifies something for `debug-verbose,` it should take effect. However, if the cluster operator did not specify anything the infra providers option should take effect. However, the `tunnel` mode option should remain fixed, and the cluster operator should not be able to change it.

A strict prioritization of configmap -> override, or override -> configmap will not be able to able to satisfy that requirement, I think.

In fact, I think my use case has the same prioritization the same as yours - `configmap, overrides, node`  is the correct priority order. What is missing is that some options are just not able to be overridden at all.

So instead of a `configOverrides.sources,` I am thinking of a `configOverride.optionsList` list. By default, this can simply be `"*"`, and the infrastructure provider is responsible for setting it to match their policies.

What do you think?

**Comment by youngnick** [comment]
Sooo, the idea of having defaults and overrides for specific settings is one we've been exploring extensively in Gateway API, and that's where we ended up with [Policy Attachment](https://gateway-api.sigs.k8s.io/references/policy-attachment/). That said, that document is a bit out of date, and I'm working on an update at https://docs.google.com/document/d/1p_kmAOmqebX8zyHnXW5I58cD8ZhNX4QNSa_gw8uAYxw/edit#.

Just some things for you to have a read of when thinking about how to solve this style of problem.

For this one, I think it's more complicated because the actual Cilium config is a YAML blob rather than a fully structured CRD. But I think some of the principles should apply.

**Comment by varunmar** [comment]
Thanks Nick! I think the policyAttachment API design pattern is super flexible, and may be exactly what we want. If the gateway API is going to use this same model, it may be a good thing to use those same abstractions/patterns.

Casey - what do you think?

**Comment by varunmar** [comment]
Yes, makes sense. We don't need to override any resource other than the config map blob, and there's no inherent cross-resource structure.
The overrides and defaults are very interesting though, and making the names of the fields similar might have some advantages to making the structure more obvious to users in a future where Gateway API is well known.

I'm not entirely sure how you want to do defaults without overrides, but I'll leave that up to you - I think the general approach in your linked PR makes sense. While we're here, might it make sense to be clear that dynamically changing the configuration on a running node (like in https://github.com/cilium/cilium/issues/21002) is not in scope?

Thanks!

**Comment by youngnick** [comment]
Awesome. I was pretty sure it wouldn't be directly applicable, but glad that it was at least a little useful.

**Comment by squeed** [comment]
This was reverted; reopening.
