### ISSUE TITLE
The benchmark script for service loadbalance

### ISSUE THREAD

**Issue by pengbinbin1** [cilium/cilium#22151]
I am doing the test about the service loadbalance performance，and I have got you use pktgen to push the packet，can you shell your test script？

**Comment by borkmann** [comment]
Are you referring to https://cilium.io/blog/2020/06/22/cilium-18/#kubeproxy-removal ? Really anything works, you could also use a dpdk-based packet generator. In the test we used a UDP service vip+port and the packet generator on the other node needs to make sure to vary source vip/port in order to RSS steer packets on the LB node to different CPUs. Traffic was pushed back out of the NIC (e.g. XDP_TX on XDP layer) to check for the case of remote backend.

**Comment by pengbinbin1** [comment]
> Are you referring to https://cilium.io/blog/2020/06/22/cilium-18/#kubeproxy-removal ? Really anything works, you could also use a dpdk-based packet generator. In the test we used a UDP service vip+port and the packet generator on the other node needs to make sure to vary source vip/port in order to RSS steer packets on the LB node to different CPUs. Traffic was pushed back out of the NIC (e.g. XDP_TX on XDP layer) to check for the case of remote backend


Yes， i referred to  https://cilium.io/blog/2020/06/22/cilium-18/#kubeproxy-removal  .Now I have compiled and installed the pktgen-dpdk on my host，but I am not sure how to test the service‘s performace based on cilium. Is that to create a service and then use pktgen to access this service? Can you share your detail test plan ? thank you.
