### ISSUE TITLE
Add timestamps to github CI runs

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#22436]
It would be helpful to have inline timestamps in github workflows to correlate test environment timestamps with pod logs inside the testing environment. This is a feature request to add this.

**Comment by tklauser** [comment]
FWIW, `cilium connectivity test` has a `-t`/`--timestamp` option since v0.12.1, so for the cilium-cli based CI runs it should only be a matter of adding this flag. The datapath conformance workflow already uses it:

https://github.com/cilium/cilium/blob/1182ca9b4742df4d05e60d0d89cecc9f080ff601/.github/workflows/conformance-datapath.yaml#L222

Marking as `good first issue` given the above.

**Comment by burnerlee** [comment]
@joestringer @tklauser can I take up this issue? I'm looking to contribute to the project

**Comment by joestringer** [comment]
@burnerlee sure, I've assigned you. Let us know if you have any questions, either here or in https://cilium.io/slack #development channel.

**Comment by pchaigno** [comment]
We already have timestamps as part of the workflows (top right corner to display them), why do we need to add more?

**Comment by joestringer** [comment]
I didn't realize that GitHub does this for us already. Paul shared this screenshot of how to find the screenshots through the GitHub UI:

![image](https://user-images.githubusercontent.com/1243336/205461698-a70ef431-1cdb-44e2-966a-24ba1ccdc9e6.png)

Based on this, we can get the information we need so there's no need for any workflow or code changes.
