### ISSUE TITLE
Hubble metrics: pod-short should only shorten managed pods

### ISSUE THREAD

**Issue by raphink** [cilium/cilium#22677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using the `pod-short` context in Hubble metrics, the pod name is shortened to the smallest initial segment, using `-` as a separator.

This leads to manually named pods  (or pods whose Deployment names contain a dash) being shortened to a wrong name.

Instead, it should probably look for the `ownerReferences` and try to determine the name of the parent `Deployment` if it exists.

### Cilium Version

1.13

### Kernel Version

N/A

### Kubernetes Version

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shunpoco** [comment]
I researched this issue a little because I'm interested in this topic!

**Background**
1. If we choose `pod-short`, a pod name is converted by [`shortenPodName`](https://github.com/cilium/cilium/blob/v1.13.0-rc4/pkg/hubble/metrics/api/context.go#L299-L301) function.
2. The function use [this regexp pattern](https://github.com/cilium/cilium/blob/v1.13.0-rc4/pkg/hubble/metrics/api/context.go#L59
)

**What I checked**
I investigated how pod names are converted by the regexp pattern (Please see this go playground: https://go.dev/play/p/9BnKPWs95fo)
In short, 
1. If Deployment controls the pod, the regexp pattern cuts unnecessary suffixes properly even if the Deployment name contains `-`
2. But if the pod is from Daemonset, Replicaset, Statefulset, other Kinds, or doesn't have a parent, the regexp pattern cuts suffixes too much. If a pod comes from a Daemonset and its name is `xxx-yyy-{random string}`, we expect the pod-short is `xxx-yyy` but the actual is `xxx`.

**Consideration**
I think @raphink 's proposal (using `ownerReferences`) is correct, but if the pod is from Deployment, we have to trace `ownerReferences` twice because I remember that a Deployment controls a Replicaset, and the Replicaset controls Pods.
I think that we can refer ownerReferences repeatedly until there is no owner and cut suffixes the same times as the references (If a pod has no owner, we don't cut anything, if a pod is managed by a Deployment, we cut twice).

**Comment by raphink** [comment]
That's write @Shunpoco , my suggestion was indeed to trace `ownerReferences` until we hit the top parent.

**Comment by Shunpoco** [comment]
@raphink Thanks!
I found that from v1.13, we can use `workload-name` and I think it returns shorten name if the pod is managed by Deployment or any other workload. (https://github.com/cilium/cilium/blob/v1.13.0-rc4/pkg/hubble/metrics/api/context.go#L427-L430)
So how about using `ep.GetWorkload()` first then use pod's name if the function returns empty string?
(Although we have to discuss whether we need to maintain `pod-short` because it is equal to using `workload-name | pod` )

**Comment by raphink** [comment]
Ah good point! 0139215e761bdf698366b79b5a59dee97a7f9841 also introduced `app` which is a good alternative as well.

**Comment by raphink** [comment]
So a safe option could be `app | workload-name | pod` to get:
- app name from labels if available
- workload-name from controller name if any
- pod name otherwise

**Comment by raphink** [comment]
Unfortunately, `app` and `workload-name` don't include the namespace, unlike `pod` and `pod-short`.

**Comment by raphink** [comment]
Following up on the NS issue in https://github.com/cilium/cilium/issues/23122

**Comment by Shunpoco** [comment]
Thanks, I forgot about the namespace.
Currently pod-short gets a namespace in [these lines](https://github.com/cilium/cilium/blob/v1.13.0-rc4/pkg/hubble/metrics/api/context.go#L409-L410), so we can reuse that way.

But I'm wondering whether we should use `app` first. In order to get pod-short (its parent name or the pod name), it is enough to use `workload-name` and `pod` and sometimes `app` has different name from its pod's name.

**Comment by raphink** [comment]
I personally switched to `app|workload-name|pod` because it honors the user-given name (the app label) then tries to get a short name from the parent controller, and eventually defaults to the pod name.

**Comment by lambdanis** [comment]
I created a PR recently to deprecate `pod-short`: https://github.com/cilium/cilium/pull/23025
Sorry I didn't search for an issue before that.

But yes, `workload-name|pod` would be a correct replacement, modulo the namespace thing.

**Comment by Shunpoco** [comment]
@lambdanis 
Thanks for your notification! I put a comment on your PR.

**Comment by lambdanis** [comment]
This issue is "mostly" fixed, as source/destination context options now support `workload-name`, a correct replacement for `pod-short`, and the namespace information can be added separately through labels context.

What still needs to be done is removing `pod-short` option, as promised in the [deprecation note](https://docs.cilium.io/en/v1.13/observability/metrics/#context-options). I'll do it before 1.14 release if nobody beats me to it :)
