### ISSUE TITLE
CI: RuntimeDatapathPrivilegedUnitTests: TestFutureWatcher failure in pkg/crypto/certloader

### ISSUE THREAD

**Issue by tklauser** [cilium/cilium#22750]
[11:40:02]     watcher_test.go:141: FutureWatcher should be ready once the TLS files exists
	 [11:40:02] --- FAIL: TestFutureWatcher (0.65s)

https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/4296/

Seen on https://github.com/cilium/cilium/pull/22721

**Comment by christarazi** [comment]
Seems like this test waits up to `testReloadDelay` (200ms), but if that's not enough for some reason, then this flake can occur. Maybe bumping the value is sufficient? Is there a better way to debug this test?

cc @kaworu

**Comment by kaworu** [comment]
At first glance this issue look similar to https://github.com/cilium/cilium/issues/21999 for which I'm working on a patch. Increasing the timeout is an idea, but I think we could have a retry loop instead so that in the best case (i.e fastest) we don't have to wait the whole timeout cc @ti-mo

**Comment by ti-mo** [comment]
Unfortunately, getting work scheduled within any particular timespan is just not a given when running in vbox. Any test that expects behaviour to happen after x amount of wall time is theoretically a flake.

**Comment by kaworu** [comment]
> Any test that expects behaviour to happen after x amount of wall time is theoretically a flake.

Isn't almost all tests theorical flakes by that definiton? There must be a "bail-out" timeout (not only in this case but generally) right?

**Comment by ti-mo** [comment]
Test timeouts are a different topic; as an extreme example, all `func Test*()` are limited to 10 minutes by default, at least that's what I think you mean by bailout timeout. My point is tests should avoid using `time.Sleep()` with arguments on the order of seconds as a synchronization mechanism, since those tend to cause flakes due to scheduling artifacts. (Go never `nanosleep()`s the given duration, it does some funky stuff to get the runtime woken up first, which seems to cause a bad interaction with the vbox hypervisor)

I've found that if a `time.Sleep()` is needed in a test, the solution is often to refactor the code to improve testability (e.g. by adding some sort of notification mechanism) instead, so a test can `select {}` over a channel and a `time.After()` (for setting a timeout).

**Comment by christarazi** [comment]
There are no `time.Sleep()`s in the `TestFutureWatcher*` code and it's already using a `time.After()`. I think as @kaworu mentioned, a retry seems like the best thing to do here.

**Comment by ti-mo** [comment]
Whether `time.Sleep()` or `time.After()` is used, the runtime will need to ask the OS for some sort of notification at some point in the future. In virtualbox, this signal won't be delivered in a timely manner. A retry just rolls the dice again.

**Comment by christarazi** [comment]
I'm not sure what else we can do. This test signals to a channel when files on disk appear. The timeout is how long to wait for that signal. A retry would try reading from the channel again.

**Comment by kaworu** [comment]
@christarazi sorry for the confusion about the retry I was mixing up the issues.

For this particular issue we could either remove the `time.After` case and rely on the default 10 minutes timeout or replace by a timer used through the test func (in order to have control over the timeout, e.g. 1 minute). It's basically increasing the timeout, but note that in the success case we'll finish the test as soon as the watcher is ready https://github.com/cilium/cilium/blob/d329654931a9a10db6d29e31663fd280be888ed7/pkg/crypto/certloader/watcher_test.go#L137-L142

This is needed in a couple of other places too where we use the same pattern ([here](https://github.com/cilium/cilium/blob/d329654931a9a10db6d29e31663fd280be888ed7/pkg/crypto/certloader/server_test.go#L93-L98) and [here](https://github.com/cilium/cilium/blob/d329654931a9a10db6d29e31663fd280be888ed7/pkg/crypto/certloader/watcher_test.go#L168-L174)).

The "retry loop" suggestion is to fix https://github.com/cilium/cilium/issues/21999 (which is the same underlying problem as this issue but in another test): https://github.com/cilium/cilium/blob/d329654931a9a10db6d29e31663fd280be888ed7/pkg/crypto/certloader/server_test.go#L156-L157
In this case we don't have a "Future" watcher with a channel, but instead an actual watcher which doesn't provide a way to signal when certs are reloaded. Here increasing the timeout would slow down the test in the success case, and I'm hesitant to add a reload notification mechanism (e.g. channel or callback) if it's only used in testing. Instead, I would suggest to add a simple "reload counter" and loop / sleep until the counter has been incremented. That way in the success case the test will succeed quickly, while still waiting as long as the "bail out" timeout (again, either the default 10mins or a custom timeout).

What do you think about theses suggestions? @ti-mo @christarazi

**Comment by christarazi** [comment]
Sounds reasonable to me.
