### ISSUE TITLE
Update XDP driver list in docs

### ISSUE THREAD

**Issue by joewilliams** [cilium/cilium#22867]
## Cilium Feature Proposal

I didn't see a way to submit a docs request so I am submitting this as a CFP. I hope that's okay.

**Is your feature request related to a problem?**

The drivers listed in https://github.com/cilium/cilium/blob/v1.12/Documentation/bpf.rst#xdp section `Drivers supporting native XDP` is from linux 4.17. 

**Describe the feature you'd like**

It's unclear how this list was generated and it would be nice if it was updated for a recent kernel.

**Comment by brb** [comment]
@joewilliams Thanks for the issue. There is another list of XDP drivers - https://docs.cilium.io/en/v1.12/gettingstarted/kubeproxy-free/#loadbalancer-nodeport-xdp-acceleration. cc @qmonnet @borkmann

**Comment by qmonnet** [comment]
Part of the list can be found with `git grep -l XDP_SETUP_PROG drivers/` (see also https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md#xdp).

Would be nice to have a single source of truth. Would be nice to have it in the BPF/XDP guide, but at the same time we want to keep it handy in the list of requirements for Cilium's features. As long as the BPF guide lives under Cilium docs, I suppose we could move the list to a dedicated RST fragment and include it from both locations, how would that sound?

**Comment by joewilliams** [comment]
>  I suppose we could move the list to a dedicated RST fragment and include it from both locations, how would that sound?

That sounds good to me, thank you!

**Comment by pchaigno** [comment]
@joewilliams Are you planning to send a PR to update (and move?) the list?

**Comment by joewilliams** [comment]
@pchaigno sorry, I don't have time right now to submit a PR.

**Comment by measutosh** [comment]
Hello @joewilliams  

I would like to pick this up
Could you please lead me to the file where the changes need to be implemented or any other resources to get me started

**Comment by joewilliams** [comment]
@measutosh It's in this file https://github.com/cilium/cilium/blob/v1.12/Documentation/bpf.rst#xdp

**Comment by janvi01** [comment]
Hey @qmonnet I would like to work on this. 

The finalized list we want to keep is https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md#xdp BPF/XDP guide, right?

**Comment by qmonnet** [comment]
> Hey @qmonnet I would like to work on this.

I'd say go for it, the issue seems to have been stale for over one year.

> The finalized list we want to keep is https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md#xdp under BPF/XDP guide, right?

Please see [this comment](https://github.com/cilium/cilium/issues/22867#issuecomment-1369545828). We'd like the list in a separate rST fragment so that we can include it from the two locations where we currently list some of the supported drivers.

**Comment by MeherRushi** [comment]
@qmonnet @janvi01 

I believe that this issue was sort of addressed while restructuring the docs in the main branch.
The commit ee7572b0fbd618fc88a168f485974793630084c3 does address the issue (where the list of drivers supporting xdp in both XDP documentation and kube-proxy-free guide was merged)

The list that is currently present in https://github.com/cilium/cilium/blob/main/Documentation/bpf/progtypes.rst seems up to date with the https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md#xdp except that it was mentioned in a separate format (In a much neater format in my opinion). 

Also the last update in both of the documentation was regarding the bond driver 5.15 (commit 8d28f16be2de8680f58c264778871ddc6c2ffa4d in the cilium/docs and commit 9e8572c43167520f75ea0c9147c791dd48f8146d in the bcc/docs). But what I find amusing is that cilium docs was updated before the bcc/docs.

Please do cross check once.

**Comment by MeherRushi** [comment]
@qmonnet 

Also, I personally feel that we could add a link to the bcc/docs GitHub repo towards the end of the current cilium's bpf docs as a note further reading incase people would want more information or some clarity regarding the source of information. I'd like to know your opinion on it and I could help if required.

**Comment by janvi01** [comment]
@MeherRushi This is a separate concern I think and can be addressed by creating a new issue imo.
 
> Also, I personally feel that we could add a link to the bcc/docs GitHub repo towards the end of the current cilium's bpf docs as a note further reading incase people would want more information or some clarity regarding the source of information. I'd like to know your opinion on it and I could help if required.

**Comment by qmonnet** [comment]
> I believe that this issue was sort of addressed while restructuring the docs in the main branch. The commit [ee7572b](https://github.com/cilium/cilium/commit/ee7572b0fbd618fc88a168f485974793630084c3) does address the issue (where the list of drivers supporting xdp in both XDP documentation and kube-proxy-free guide was merged)

Yes, looks correct, this addresses the issue where we had two versions of the list, so we no longer need to move it to a specific fragment. Apologies.

> The list that is currently present in https://github.com/cilium/cilium/blob/main/Documentation/bpf/progtypes.rst seems up to date with the https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md#xdp except that it was mentioned in a separate format

Yes, but we want to be up-to-date with regards to driver support in the Linux kernel, not with the BCC docs.

> (In a much neater format in my opinion).

Well [sorry about that](https://github.com/iovisor/bcc/commit/12a09dc8883bc043b4ae92a21c374f4f8053a0df), I guess
 
> Also the last update in both of the documentation was regarding the bond driver 5.15 (commit [8d28f16](https://github.com/cilium/cilium/commit/8d28f16be2de8680f58c264778871ddc6c2ffa4d) in the cilium/docs and commit 9e8572c43167520f75ea0c9147c791dd48f8146d in the bcc/docs). But what I find amusing is that cilium docs was updated before the bcc/docs.

I'm not sure I understand why this is amusing. The two lists are updated independently, we're very much capable to update our list ourselves and don't usually copy-paste from the BCC docs. I used to maintain the list on BCC's side, but I've stopped a long time ago and I'm not sure who does it these days.

> Also, I personally feel that we could add a link to the bcc/docs GitHub repo towards the end of the current cilium's bpf docs as a note further reading incase people would want more information or some clarity regarding the source of information. I'd like to know your opinion on it and I could help if required.

I'm not sure how this information would be helpful to Cilium users who don't particularly need to know what BPF helpers are available to them, knowing that we already have a list of requirements regarding kernel versions. Same for the source of information, it's not excluded that some people might have updated the list looking at the BCC docs in the past, but overall we're updating our list by ourselves and based on what we know from the kernel and the mailing list. 

The former two lists no longer need to be merged, but the current issue regarding the list update still stands, it seems to me that there is a bunch of drivers that have got XDP support since 2022.

**Comment by MeherRushi** [comment]
Hey @qmonnet 

Sorry for the inconvenience caused, I had mistaken BCC for being the reference for the list of drivers. Thanks a lot for taking the effort and time to explain. I understand how the document updating works now and why the format is chosen as well.

> The former two lists no longer need to be merged, but the current issue regarding the list update still stands, it seems to me that there is a bunch of drivers that have got XDP support since 2022.

I think @janvi01 is already working on it. I am willing to help if required.

Once again, thanks for the clarification.
