### ISSUE TITLE
cilium-dns-egress - port assignment, firewall, documentation

### ISSUE THREAD

**Issue by wiktorkisielewski** [cilium/cilium#22906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi!

I'm running a bare-metal Kubernetes cluster (based on ubuntu 20.04 machines) and I've found something called `cilium-dns-egress` exposed on a random TCP port on every cluster node, accessible on public IP.

- there is no info about this in the docs, so I have no idea if this is necessary and must be exposed 
- there is no way to add this to the TCP ports whitelist as it is assigned to a random port every time cilium agent on a node is restarted (example ports, `33689`, `40505`)

The only way to determine that this is in fact `cilium-dns-egress` is by looking into cilium pod logs:

![image](https://user-images.githubusercontent.com/45452378/210228975-dc1faf99-26d5-468c-8db5-39a434a2ea43.png)

This was happening on cilium version 1.08 and is on 1.12.1

### Cilium Version

1.12.1

### Kernel Version

5.4.0-135-generic

### Kubernetes Version

1.25.3

### Relevant log output

```shell
# kubectl logs -n kube-system cilium-hmg44 | grep cilium-dns-egress
level=info msg="Adding new proxy port rules for cilium-dns-egress:33689" proxy port name=cilium-dns-egress subsys=proxy
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pchaigno** [comment]
I believe this port corresponds to Cilium's DNS proxy, which is only actually used if you have DNS redirections for network policies (e.g., DNS or FQDN policies) or if you are using [L7 Protocol Visiblity](https://docs.cilium.io/en/stable/policy/visibility/#proxy-visibility).

This was reported before in https://github.com/cilium/cilium/issues/18286. See [Jarno's answer](https://github.com/cilium/cilium/issues/18286#issuecomment-1006720284) in particular:
- There's a `--tofqdns-proxy-port` flag you can use to set the DNS proxy port to a fixed value.
- One direct improvement would be to only allocate this port if the DNS proxy is actually being used. That would mean starting the DNS proxy only at runtime based on received Kubernetes CRs instead of starting it when the Cilium agent starts.
- Another avenue would be confirming that we do need to listen on 0.0.0.0 and can't limit this socket to e.g. 127.0.0.1.

**Comment by wiktorkisielewski** [comment]
Thanks! 
- Is there a way to disable this completely (if I don't need to use it)?
- Why does this component run on a  "random" port instead of a fixed one?

**Comment by pchaigno** [comment]
> Is there a way to disable this completely (if I don't need to use it)?

Yes, I believe you can disable all L7 proxies and redirections with `--enable-l7-proxy=false`.

> Why does this component run on a "random" port instead of a fixed one?

I don't know the historical reason for that. @jrajahalme might know.

**Comment by adjurk** [comment]
Hi @pchaigno, I've tried setting `--enable-l7-proxy` to `false`, but this also disables the health check `tcp/4240` port. I wasn't able to find the docs which would describe what does this flag is exactly responsible for.

Is there any way to disable the DNS proxy while keeping health checks ports open?

**Comment by adjurk** [comment]
Never mind, the health check actually took a little longer than I expected to become healthy 🤦 The flag's working fine 👍

**Comment by wiktorkisielewski** [comment]
Since there is a way to disable it I am closing this issue 👍
