### ISSUE TITLE
CI: Travis: Unit test panic in TestResource_WithFakeClient

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#23079]
## CI failure

https://app.travis-ci.com/github/cilium/cilium/jobs/593210550

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   PANIC  package: github.com/cilium/cilium/pkg/k8s/resource • TestResource_WithFakeClient   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
panic: runtime error: invalid memory address or nil pointer dereference [recovered]            
	panic: runtime error: invalid memory address or nil pointer dereference                        
[signal SIGSEGV: segmentation violation code=0x1 addr=0x188 pc=0x1a6f9cd]                      
                                                                                               
goroutine 17 [running]:                                                                        
testing.tRunner.func1.2({0x1c8ce40, 0x31c3350})                                                
	/home/travis/.gimme/versions/go1.19.4.linux.amd64/src/testing/testing.go:1396 +0x24e           
testing.tRunner.func1()                                                                        
	/home/travis/.gimme/versions/go1.19.4.linux.amd64/src/testing/testing.go:1399 +0x39f           
panic({0x1c8ce40, 0x31c3350})                                                                  
	/home/travis/.gimme/versions/go1.19.4.linux.amd64/src/runtime/panic.go:884 +0x212              
github.com/cilium/cilium/pkg/k8s/resource_test.TestResource_WithFakeClient(0xc0004504e0)       
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/resource/resource_test.go:158 +0xbed  
testing.tRunner(0xc0004504e0, 0x20393f0)                                                       
	/home/travis/.gimme/versions/go1.19.4.linux.amd64/src/testing/testing.go:1446 +0x10b           
created by testing.(*T).Run                                                                    
	/home/travis/.gimme/versions/go1.19.4.linux.amd64/src/testing/testing.go:1493 +0x35f           
FAIL	github.com/cilium/cilium/pkg/k8s/resource	0.162s           
```

**Comment by joestringer** [comment]
This failed on AMD64 but the same PR run did not fail on ARM64, which suggests that this is an intermittent issue.

**Comment by joestringer** [comment]
@joamaki does this look familiar to you? Based on the code on that line, it seems like potentially a test code issue with the fake client.

**Comment by pchaigno** [comment]
@joamaki Did you get a chance to look into this? It's still affecting CI.

**Comment by joamaki** [comment]
Ok yeah. Looks like assert.Equal won't immediately stop the test, which causes this panic as a later assert derefs a nil pointer. Annoyingly the actual failed asserts aren't visible in the logs.

The actual problem seems to be a race in emitting the initial set. Haven't been able to reproduce it locally though. I think an event is emitted twice for the same object with same revision. The sequence of events is probably:
```
Informer.Add(1/2): Informer adds A to store
Events(): queue all keys from store (A)
emit: Event{Upsert, A} and remove from queue
Informer.Add(2/2): Informer calls ResourceEventHandlerFuncs.AddFunc, queues A again
emit: Event{Upsert, A}
```

This happens because the store is updated before the event handler is called, so we don't have a good way of synchronizing this. I could do what's done in pkg/k8s/informer/informer.go and fork the informer code and handle the insert into the store and handler callbacks in our code and make sure we're synchronizing on the queue lock, but that feels excessive. I might want that later anyway as I'd like to set the WatchErrorHandler to mark Resource[T] as degraded if Watch() is failing as currently we'd just get cryptic log messages about it.

Since there isn't much harm in emitting the same upsert event twice (except potentially in tests that don't expect to see it), I'll do a quick fix to the tests to avoid this race and I'll follow up later with fixing this properly.
