### ISSUE TITLE
ginkgo: Reuse AnnotationNames from `pkg/`

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2308]
https://github.com/cilium/cilium/blob/9af5a5ee738664aaf67293599333e5160c0a4f43/test/helpers/kubectl.go#L32-L37

+@eloycoto any reason this didn't just reuse the copy it references?

**Comment by eloycoto** [comment]
@joestringer We had like that, but if we reused that we can't run the test on OSX. 

cc: @ianvernon

**Comment by ianvernon** [comment]
@joestringer this is because if we pull in the package, that package's dependencies are pulled in as well, which includes cgo code that requires BPF headers to be present. Since Ginkgo is written in go, when it tries to compile this on the Mac, it fails, as the required headers are not present. This would require a refactoring of the packages to have the constants separate from the package itself in Cilium. After doing that, we could import the package itself without issue.

**Comment by manalibhutiyani** [comment]
closing as per the comments by Ian and Eloy. Please reopen if you feel this is required.

**Comment by ianvernon** [comment]
I'm reopening this, as reducing duplication of code is important. There are two tasks here:

- [ ] Refactor annotation constants into separate package for importing by the Ginkgo tests.
- [ ] Import these constants into the Ginkgo tests.
