### ISSUE TITLE
Hubble metric contexts discrepancy

### ISSUE THREAD

**Issue by raphink** [cilium/cilium#23122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Looking at https://github.com/cilium/cilium/commit/0139215e761bdf698366b79b5a59dee97a7f9841, I see that there's now `app` and `workload-name` contexts, which is much better than `pod-short`.

However, `pod` and `pod-short` include the namespace in the format `<ns>/<pod>` but `app` and `workload-name` don't include the namespace.

There should be an option to get `pod` label context without the namespace prefix.

### Cilium Version

1.13

### Kernel Version

N/A

### Kubernetes Version

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chancez** [comment]
I think we're deprecating pod-short in favor of workload-name: https://github.com/cilium/cilium/pull/23025. 

However, there is still an inconsistency and with `source/destination` context options, if you used app or workload name, you won't know what namespace they originated from, but you could use the labels context option to get the `source_namespace` and `destination_namespace`, though it's not exactly the same.

Additionally, with `labels` context option, you could construct `source` or `destination` labels using relabeling rules, but the UX is not as good. 

If we want consistency, we can either update the `app` and `workload-name` to include the namespace name in the `source/destination` labels, like it is for pod and pod-short, or we could remove the namespace from `pod` and `pod-short`. For both situations, we need to consider backwards compatibility.

For handling compatibility, we could introduce new metrics configuration options for including the namespace in workload-name/app, or options for removing namespace from pod/pod-short. It's pretty unfortunate this wasn't caught earlier, since we now have a split in how things are being done.

If we supported some form of string interpolation/templating syntax, we could support any label formatting pretty easily, so that's also a consideration.

**Comment by raphink** [comment]
I'm fine with using `labelsContext` to add namespace info. I'm guessing (but not sure) that we still need `pod` for when there's no controller, right?

So: `app|workload-name|pod`

**Comment by chancez** [comment]
@raphink Right, but you will have the unfortunate issue that the namespace will be in the resulting value if it falls back to pod.

**Comment by raphink** [comment]
Exactly. So an option to get the pod name without namespace would be idea.

**Comment by lambdanis** [comment]
All of: `namespace`, `pod`, `workload`, `app` can be added as separate labels (prefixed with `source_`/`destination_`) through `labelsContext`. And `ip` too. If these labels are enabled, then setting source/destination context to a corresponding option is mostly duplicating information, right?

> If we want consistency, we can either update the app and workload-name to include the namespace name in the source/destination labels, like it is for pod and pod-short, or we could remove the namespace from pod and pod-short

Adding namespace to `workload-name` and `app` options makes them more meaningful identifiers in case additional labels are not enabled. And different than labels enabled by `labelsContext` at least, but I don't think there's much value in that. I don't really like the namespace/something format though.

I'm mildly leaning towards removing namespace from pod (as new option `pod-name`?). Then a simple useful config would be source/destination context: `workload-name|pod-name` and labels context: `source_namespace,destination_namespace`. As compared to source/destination with namespace, it shouldn't lose any information or increase cardinality. But it gives separate labels for namespace and identifier.

And `pod-short` should be removed IMO (https://github.com/cilium/cilium/pull/23025 promises removal in 1.14 release), it's simply incorrect.

**Comment by raphink** [comment]
Agreed, `pod-name` is probably the best option going forward

**Comment by chancez** [comment]
@lambdanis that seems pretty reasonable. I'll take a quick stab at implementing `pod-name`.
