### ISSUE TITLE
CFP: Improvements in hubble metrics cardinality

### ISSUE THREAD

**Issue by marqc** [cilium/cilium#23162]
## Cilium Feature Proposal/Improvement

Improvements in hubble metrics cardinality proposals:
1. introduce TTL on metrics
2. introduce limit on total number of metric series
3. clean up metrics on pod deletion
4. introduce label or annotation to exclude certain targets/pods from collecting metrics

**Is your feature request related to a problem?**

I'm currently examining potential hubble metrics cardinality issues, that may lead to OOM errors on either cilium-agent or metrics collector (in case of too many metrics are getting exposed by cilium agent).

Cilium-agent collects metrics in standard prometheus golang_client counters and depending on source & destination context labels metrics with pod-name (or cilium identity). Over time pods get deleted and new ones are created. Prometheus registry still keeps track of counters labeled with deleted pods. If cilium-agent doesn't get restarted, it can lead to OOM on cilium-agent or metrics collector. The problem is mostly visible when pods live for a very short time, eg. when heavy utilizing cronjobs or knative.

The other failing scenario is when a workload/pod behaves "strange". The port scanner may be an example.  Lets say we have a pod, that periodically scans open ports of other pods and clusters to report potential security vulnerabilities. Each scan attempt may generate thousands of dataseries with simple `nc -z -v <TARGET_IP> 1-32000`. It is related to the port-distribution metric https://github.com/cilium/cilium/blob/master/pkg/hubble/metrics/port-distribution/handler.go

**Describe the feature you'd like**

I can think of a few mitigations and improvements and would love to hear your feedback.

### 1. introduce TTL on metrics

Keep an additional map of the last write timestamp of each data series and remove metrics that haven't been updated in specified TTL. This will mitigate the problem of forever keeping dataseries of non-existing pods.
It can remove data series of existing posd when there is no frequent traffic.

### 2. introduce limit on total number of metric series

Introduce limit that will reject creating new metric series when the configured threshold is reached.  In combination with proposal (1) and (3) the number of data series may be later decreased which will allow creating new dataseries again.  The number of rejections should be tracked in a separate counter as a feedback to the maintainer.

This prevents OOM in any scenario, but may lead to some metrics not being collected.

### 3. clean up metrics on pod deletion

If metric is attributed to pod or CiliumIdentity we can track removals of these elements and remove related metrics. This solution is better than solution 1 in case of infrequent traffic.

On the other hand it can be quite challenging to determine which data series should be removed. eg. when source="pod-a" and destination="pod-b" should we remove such data series when "pod-a" is deleted? Should we wait for both pods to be deleted? 
If all pods talk to long-running pods like dns-server we may keep them forever (until dns pod is deleted).

### 4. introduce label or annotation to exclude certain targets/pods from collecting metrics

We can additionally label/annotate some pods with `cilium.io/no-metrics: true` label and in case of this annotation being present do not return any label in the context resolver. This will allow excluding certain workloads/pods from generating data series (pod scanner scenario).

**Comment by siwiutki** [comment]
Regarding feature from point 2, enabling it might lead to having no metrics at all on some quite meaningful traffic. If there were a port scanner that would generate enough data series to hit the limit, and then after that some pairs of pods started communicating, we could miss some useful info about flows between them.

A way to prevent that would be to have additional limit between any pair of pods and/or workloads.

**Comment by lambdanis** [comment]
Hey @marqc, thanks for the proposal. High cardinality caused by keeping metrics for deleted pods is definitely a known issue, and IMO the most important to address.

> 1. introduce TTL on metrics
> 3. clean up metrics on pod deletion

From these two, I would rather implement (3).

TTL on metrics has a problem you pointed out: it can remove data series of existing pods when there is no frequent traffic. Many clusters have wide distributions of workloads size, traffic and churn rate. Given that, it would be difficult to choose a TTL that fits both: workloads with large number of short-lived pods (causing high cardinality), and workloads with long-lived low-traffic pods (that still might be critical, so randomly losing metrics for them would be bad). This issue could be solved by more granular configuration (e.g. pod annotations), but that's a significant overhead.

Cleaning up metrics on pod deletion sounds much nicer to me. I think when a pod is deleted, then all metrics that had this pod (or corresponding Cilium identity?) as either source or destination can be stopped - after all there will be no traffic to or from this pod anymore. I guess the simplest implementation would be a pod watcher + [DeletePartialMatch](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#MetricVec.DeletePartialMatch) or similar.

> 2. introduce limit on total number of metric series

It would help with cardinality, but feels like a hack. If the previous issue (zombie metrics for deleted pods) is fixed and workloads are predictable, then it should be possible to estimate the resources needed to produce and collect all Hubble metrics. If workloads are not predictable, e.g. heavily autoscaled, then the problem persists and a hard limit might help OOMs at least. But personally in such case I would prefer to over-provision Cilium agent and metrics collector if possible - otherwise I can lose exactly the metrics that would be the most interesting. A limit can be a QoL improvement, just shouldn't replace fixing zombie metrics problem and proper configuration.

> 4. introduce label or annotation to exclude certain targets/pods from collecting metrics

Sounds legit to me, might be a QoL improvement too. A nit: I think the annotation should have `hubble` somewhere in it.

**Comment by chancez** [comment]
I agree with the points made by @lambdanis.  I’ve looked into expiring metrics when pods are deleted but it’s a pretty big task. It’s done in a few other projects like kube-state-metrics as well. 

> introduce label or annotation to exclude certain targets/pods from collecting metrics

You can also drop metrics for certain targets in Prometheus using the metrics labels, which would achieve similar results.

**Comment by lambdanis** [comment]
> It’s done in a few other projects like kube-state-metrics as well.

If I understand [this](https://github.com/kubernetes/kube-state-metrics/blob/f01ce58a30d4bb2710bf3fbe2178aa3972e76508/pkg/metrics_store/metrics_store.go#L28) correctly, kube-state-metrics implements Prometheus registry as `k8s.io/client-go/tools/cache.Store`, so deleting metrics is handled by `Delete()` method. Hubble would need a different approach.

> You can also drop metrics for certain targets in Prometheus using the metrics labels, which would achieve similar results.

Similar, with one important difference that it might not help with OOM kills in the collector, as it still needs to collect metrics before dropping. Unless handling drops is more memory-efficient these days, I'm not really sure.

**Comment by marqc** [comment]
Deleting the metric series on pod deletion has some additional challenges:

1. If we have data series between pod-A and pod-B should we delete this data series when only pod-A or pod-B is deleted or when both pods are deleted. I believe we should do this when any of the pods is deleted. Otherwise dataseries for flows to eg. dns server may hang forever.

2. What if the data series context is set to something different than "pod", eg. "pod-short", "namespace", "workload", "ip". I beliebe we should ignore all of this and naively assume to try `DeletePartialMatch({"source":"<ns>/<pod_name>"})` & `DeletePartialMatch({"destination":"<ns>/<pod_name>"})`.
Contexts like pod--short, workload, namespace already have much lower cardinality. Also IPs are reusable within a node. But I'm not sure if we should try to delete data series labeled by IP.

3. Right now metric handlers do not know and do not care whether the source & destination context is set and how is it configured. But they manage prometheus Counters/Histograms. I believe the way to go is to extend metrics Handler interface with method OnPodDeletion and call common implementation, eg.
 
```
type flowHandler struct {
	flows   *prometheus.CounterVec
	context *api.ContextOptions
}

func (h *flowHandler) ProcessPodDeleted(namespace, podName string) error {
	return h.context.RemovePodMetrics(h.flows.MetricVec, namespace, podName)
}
```

4. Should we delete the metrics series immediately when a pod is removed. Usually prometheus scapers are configured to fetch data once per 30-60s. I believe a queue should be added with delayed delivery that will remove data series only after preconfigured time has passed since pod deletion.

**Comment by chancez** [comment]
@lambdanis 

> If I understand [this](https://github.com/kubernetes/kube-state-metrics/blob/f01ce58a30d4bb2710bf3fbe2178aa3972e76508/pkg/metrics_store/metrics_store.go#L28) correctly, kube-state-metrics implements Prometheus registry as k8s.io/client-go/tools/cache.Store, so deleting metrics is handled by Delete() method. Hubble would need a different approach.

Yes, that was my assessment as well. I do believe we have the required hooks, but the challenge isn't the hooks to pod delete, but integrating the creation of new metrics series (some_metric.WithLabels(...)) with the hooks.

@marqc 

> I believe we should do this when any of the pods is deleted. 

That seems reasonable to me.

> What if the data series context is set to something different than "pod"

I think this is pretty nuanced. I don't believe that's going to work quite how you want. Similar to what I was saying to @lambdanis above, I think ideally, when we create a metrics vector we would be querying for the related resources, and tying their lifecycle to the metric itself, but this is probably quite a bit of effort.

> I believe the way to go is to extend metrics Handler interface with method OnPodDeletion and call common implementation

Yes, this is definitely necessary, but ideally we would actually tie it to the metrics registry/metrics rather than the handlers. Handlers "shouldn't" need to know about this ideally.

**Comment by vakalapa** [comment]
> ### 4. introduce label or annotation to exclude certain targets/pods from collecting metrics
> We can additionally label/annotate some pods with `cilium.io/no-metrics: true` label and in case of this annotation being present do not return any label in the context resolver. This will allow excluding certain workloads/pods from generating data series (pod scanner scenario).

@marqc  Was there a follow up for this item. This suggestion is very helpful in cloud providers where Prometheus servers cannot be configured on the fly.

**Comment by marqc** [comment]
@vakalapa 

> > ### 4. introduce label or annotation to exclude certain targets/pods from collecting metrics
> > We can additionally label/annotate some pods with `cilium.io/no-metrics: true` label and in case of this annotation being present do not return any label in the context resolver. This will allow excluding certain workloads/pods from generating data series (pod scanner scenario).
> 
> @marqc Was there a follow up for this item. This suggestion is very helpful in cloud providers where Prometheus servers cannot be configured on the fly.

No. There was no follow up, as removing metric series on pod deletion seemed to be a good enough solution so far. Implementation of point "4" should be quite easy. The flow object is already passed to the context resolver and labels set  should be propagated with CEP/CES so accessible when resolving it. https://github.com/cilium/cilium/blob/main/pkg/hubble/metrics/api/context.go#L291

The question is if you don't want these metrics available at prometheus endpoint in cilium-agent pod, or it's fine if they are present but with an empty source or destination label (to be dropped in scraper config/filters).

If you want to completely remove this metrics series from prometheus endpoint (where either source or destination is labeled with `no-metrics` , you should rather look into event filtering. Ie. something similar to https://github.com/cilium/cilium/blob/main/pkg/hubble/monitor/filter.go

Note that monitor filters will affect not only metrics but also other hubble features (UI, CLI). So maybe a better approach would be to allow setting flow filters on metrics. https://docs.cilium.io/en/stable/_api/v1/flow/README/#flowfilter

**Comment by neaggarwMS** [comment]
Agreed, we need some form of implementation for #4 where we can completely filter a pod/workload from metrics.

**Comment by neaggarwMS** [comment]
Thanks @marqc  for the pointers.
