### ISSUE TITLE
Moved documentation pages lead to 404s

### ISSUE THREAD

**Issue by tommyp1ckles** [cilium/cilium#23224]
Often when searching for Cilium documentation, you often find links for pages that have since been move, leading to hitting the 404 page with no clear indication on where to look.
When page moves occur, we should try to redirect to something relevant, if not an index page.

Example:
* First documentation link when searching "cilium service mesh" is: https://docs.cilium.io/en/v1.12/network/servicemesh/index/

**Comment by measutosh** [comment]
Hello @tommyp1ckles , I would like to pick this up
could you please suggest few resources to get me started with this or any other information

**Comment by joestringer** [comment]
@measutosh Cilium uses readthedocs to configure these. If it's possible to configure this in a readthedocs configuration file in the repository, then we would be open to accepting PRs to add that configuration. I don't know if that's the case. Otherwise this may require someone from the project with advanced privileges to go through and configure it.

**Comment by margamanterola** [comment]
I've encountered this as well. It's quite unfortunate, because Google tends to link to older versions for some reason.

A couple of cases I ran into: 
 - https://docs.cilium.io/en/v1.10/gettingstarted/egress-gateway/ should point to https://docs.cilium.io/en/v1.13/network/egress-gateway/
 - https://docs.cilium.io/en/v1.9/gettingstarted/kubeproxy-free/ should point to https://docs.cilium.io/en/v1.13/network/kubernetes/kubeproxy-free/

**Comment by margamanterola** [comment]
It's possible to do page redirects with ReadTheDocs: https://docs.readthedocs.io/en/stable/user-defined-redirects.html#id2

The tricky part here is that we would need to do the redirect starting from the first version where the page was moved onwards, but not for the versions before.

**Comment by margamanterola** [comment]
Oh, apparently readthedocs doesn't support setting redirects in config files and rather requires someone doing it manually through the web console, or alternatively using an API. See https://github.com/readthedocs/readthedocs.org/issues/2904 for more information.

**Comment by margamanterola** [comment]
The alternative mentioned in that issue I linked is to use GitHub Actions to sync the redirects. There's a template here: https://github.com/nextstrain/.github/blob/master/workflow-templates/sync-rtd-redirects.yaml, with instructions for creating the first redirects.yaml with the contents of the current redirects configured through the web console.
