### ISSUE TITLE
CI:  Travis: BPF unit tests, "'buildx' is not a docker command"

### ISSUE THREAD

**Issue by qmonnet** [cilium/cilium#23509]
## CI failure

- Travis, on `master` branch
- Go 1.19.5, amd64
- [URL](https://app.travis-ci.com/github/cilium/cilium/jobs/594698367)
- [Raw logs](https://github.com/cilium/cilium/files/10557731/log.txt)

```
[...]
1d0852833443: Pull complete
Digest: sha256:4592d81f9cecdc9fe1832bdcd22dfceafd36720011539679ae177f62cf169ce6
Status: Downloaded newer image for consul:1.7.2
f645980a4e3447ea43ac36d90e51bdb5d9149ac2e63d2cfd401f089bcd2fc1bb
  CC     test/bpf/elf-demo.o
  CC     test/bpf/unit-test
  CHECK  test/bpf
  CHECK  test/bpf unit-test
docker: 'buildx' is not a docker command.
See 'docker --help'
  CHECK   vetting all packages...


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```

I don't know whether `docker: 'buildx' is not a docker command.` is the cause of the error or a symptom.

Cc @dylandreimerink just in case, although given how little info we have, I have no idea how to reproduce.

**Comment by dylandreimerink** [comment]
The `buildx` message is unrelated, and also not the last message `vetting all packages...`. I have seen this failure mode before and it turns out to be the `go test ./...` stage which can go for >10m without making output which Travis doesn't like. 

Should be noted that I have only ever seen it when one of the tests breaks which causes a timeout in one of the tests. So there might be an underlying issue. But we should also fix the fact that those errors are obscured.

The simplest "fix" would be to pass `-v` to `go test` so it will output while it is running. But that might break our nice `tparse` formatting. And spam the Travis CI log.

**Comment by sayboras** [comment]
we are moving away from travis, the first step is to migrate amd64 job to GHA 

https://github.com/cilium/cilium/pull/22900

**Comment by lmb** [comment]
just ran into this again, would it be OK if I added something like `-timeout 9m30s` to `make integration-tests`? (Maybe it has to be conditional on running on travis?)
