### ISSUE TITLE
Cilium sets wrong MTU to veth-interfaces

### ISSUE THREAD

**Issue by kvaps** [cilium/cilium#23711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey, we're using cilium to run virtual machines using KubeVirt project.
The KubeVirt inherits MTU value from veth-interface created by CNI.

But the problem is that Cilium sets wrong MTU for veth-interfaces:

```console
29: lxcd014acdcb003@if28: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether ca:eb:0e:7e:e2:d7 brd ff:ff:ff:ff:ff:ff link-netns cni-bf21b517-613f-f985-4fda-9f5159bc587b
```

It seems this MTU 1500 is inherited from physical device:

```
level=info msg="  --mtu='0'" subsys=daemon
level=info msg="Inheriting MTU from external network interface" device=eno1 ipAddr=92.53.71.83 mtu=1500 subsys=mtu
```

But I have VXLAN tunnel mode enabled. Thus it should equal 1450, same like in routing table:

```
10.111.0.0/24 via 10.111.0.169 dev cilium_host src 10.111.0.169
10.111.0.169 dev cilium_host scope link
10.111.1.0/24 via 10.111.0.169 dev cilium_host src 10.111.0.169 mtu 1450
10.111.2.0/24 via 10.111.0.169 dev cilium_host src 10.111.0.169 mtu 1450
10.111.3.0/24 via 10.111.0.169 dev cilium_host src 10.111.0.169 mtu 1450
10.111.4.0/24 via 10.111.0.169 dev cilium_host src 10.111.0.169 mtu 1450
```

---

During investigation of this problem, I found that:
- Setting `--mtu` option manually, changes MTU in routes, but not for veth-devices.
- Setting  `--device-mtu` option makes no effect.

Any way, even if this would work, specifying MTU manually is not universal solution and will disable MTU autodetection.
So I am a supporter of using RouteMTU for created veth-intefaces.

AFAIK [flannel-cni](https://github.com/flannel-io/flannel) and other CNI plugins are setting correct MTU value for Veth interfaces.
In case of tunnel enabled it is always 1450 instead of 1500

### Cilium Version

Client: 1.11.12  go version go1.17.13 linux/amd64
Daemon: 1.11.12  go version go1.17.13 linux/amd64

### Kernel Version

5.15.0-60-generic

### Kubernetes Version

v1.23.15

### Relevant log output

```shell
enable-pmtu-discovery: "true"
```

### Anything else?

@tgraf as author of this change, cloud you comment this issue please?
https://github.com/cilium/cilium/commit/829fc5730dc1741a07f8781ce6fc74eaeba4edc9#diff-7361d3356cb8d25d09fee88f8dbba7f047387c04c417e21f7a234a78068c02a7R349

Thank you 🙂 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nbusseneau** [comment]
Thanks @kvaps, this looks like a legitimate bug, I think the line you're referring to should probably use `RouteMTU` instead of `DeviceMTU`. Would you be up for testing it out and submitting a PR?

**Comment by kvaps** [comment]
Yeah, works fine to me!

**Comment by joestringer** [comment]
I think that the solution to this problem is to configure routes in the VMs with the lower MTU. Lowering the MTU on the devices will break other paths.

**Comment by kvaps** [comment]
this still in a row

**Comment by joestringer** [comment]
Cilium configures a higher MTU on the devices in order to allow receiving larger frames, specifically because it is connected to multiple networks (tunnel and non-tunnel). By design Cilium configures routes inside Pods to use a lower MTU in order to limit the transmission on the tunnel network to fit within the MTU of that path. This ensures that regardless of whether the Pod attempts to connect to peers over the tunnel or over the internet, the connectivity works correctly. We can't just change the device MTU to route MTU since that will break connectivity between Pods and the Internet (or any other non-tunnel destinations).

One possible solution is to teach kubevirt about the route (+MTU) when configuring the devices. By the looks, the [CNI spec doesn't encode this today in its routes](https://github.com/containernetworking/cni/blob/main/pkg/types/types.go#L131), but maybe it should encode MTU in the routes there. I'm not exactly sure how kubevirt is involved in the device handling, but if Cilium handed back the MTU with the routes that it configures, this might help kubevirt to configure MTU correctly. On the other hand, maybe a simpler solution is just to have another out-of-band configuration for kubevirt to ensure that the routes are configured with the correct MTU.
