### ISSUE TITLE
/bin/sh removed from etcd image breaking etcd-init

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#23760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

/bin/sh is no longer included in quay.io/coreos/etcd as of v3.5.7 

Seems there was a licensing issue for using busybox: https://github.com/etcd-io/etcd/issues/15034

### Cilium Version

v1.12.7

### Kernel Version

n/a

### Kubernetes Version

n/a

### Relevant log output

```shell
Error: failed to start container "etcd-init": Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Thanks for the report, this has slipped through the CI due to a mismatch between the way that the Helm charts configure this feature vs. https://github.com/cilium/cilium-cli. I've filed https://github.com/cilium/cilium-cli/issues/1391 to follow up on the discrepancy and avoid this sort of breakage in future.

In the mean time, you can work around this issue on Cilium v1.12.7 by configuring the Helm value `clustermesh.apiserver.etcd.image.tag` to `v3.5.4@sha256:795d8660c48c439a7c3764c2330ed9222ab5db5bb524d8d0607cac76f7ba82a3`.

**Comment by michi-covalent** [comment]
affected versions: 

- [v1.12.7](https://github.com/cilium/cilium/releases/tag/v1.12.7)
- [v1.11.14](https://github.com/cilium/cilium/releases/tag/v1.11.14)
- [v1.10.20](https://github.com/cilium/cilium/releases/tag/v1.10.20)

**Comment by joestringer** [comment]
#23771 was merged before v1.13.0, so v1.13 is not affected. It looks like v1.10.x is also not affected. @michi-covalent I presume you will follow up for v1.11 and v1.12 above? Otherwise the tophat can take care of it if we just mark the revert PR for backport.

**Comment by michi-covalent** [comment]
🚀 

- v1.12: https://github.com/cilium/cilium/pull/23788
- v1.11: https://github.com/cilium/cilium/pull/23789

**Comment by dctrwatson** [comment]
Confirmed this was fixed by

> rocket
> 
> * v1.12: [Revert "Pick up etcd v3.5.7" #23788](https://github.com/cilium/cilium/pull/23788)
> * v1.11: [Revert "Pick up etcd v3.4.23" #23789](https://github.com/cilium/cilium/pull/23789)
