### ISSUE TITLE
Update clustermesh-apiserver initContainer to configure etcd for v3.5.7 or later

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#23770]
Etcd v3.5.7 or later no longer ships with a shell in the default image.

Currently in the following clustermesh-apiserver deployment, we rely on the availability of a shell:

https://github.com/cilium/cilium/blob/105331bd133131c6f724fc9121fef1fb57c22ca9/install/kubernetes/cilium/templates/clustermesh-apiserver/deployment.yaml#L40

In order to bump the etcd dependency to v3.5.7, we need to update this line to either:
1. Rely on another image that has a shell that we can use in order to configure etcd, OR
2. Rework these instructions such that they work directly in the etcd 3.5.7 container.

Related: https://github.com/cilium/cilium/issues/23760

**Comment by cyclinder** [comment]
Option 1 is better, Right?  `busybox` maybe a good choice.

**Comment by joestringer** [comment]
I'm not sure what the best option is yet, but if you have a proposal then we can review it. Ideally we could use an image that is already used in a Dockerfile under `images/` just in order to keep the diversity of image dependencies as minimal as possible. However, depending on the implementation details that may not be possible. Given that the script currently runs various `etcd` and `etcdctl` commands, pure busybox will not be sufficient.

**Comment by ferozsalam** [comment]
@learnitall and @mpl – @jameslaverack mentioned he would be interested in taking a look at this item. As it doesn't look like work has begun on this, I'm assuming that it's not an issue, shout if I've got it wrong! Obviously happy for whoever has time first to take a look at it.

**Comment by learnitall** [comment]
Go for it! I've thought about this a bit and discussed it with my working group, but haven't started any concrete work yet. Here's what we've thought about so far:

* Restraints:
  * From what we can tell, there isn't a viable way to go through this init process without a running instance of etcd. This means that the image used for the init container must have etcd available.
  * The init logic for etcd must be run within an init container with etcd bound to localhost before the main etcd container is served to the cluster, otherwise, there is a small window when the etcd server is exposed without restrictions on access.
* Option 1: Move init logic into the clustermesh-apiserver
  * clustermesh-apiserver gets a new subcommand that inits a local etcd server, which will be run in the init container.
  * This doesn't make too much sense because clustermesh-apiserver doesn't ship etcd in its container image, meaning, a new image would have to be created that contains both the clustermesh-apiserver and etcd. There are alternatives with less bloat.
* Option 2: Create a go program that starts an [embedded etcd](https://pkg.go.dev/go.etcd.io/etcd@v3.3.27+incompatible/embed) and runs init logic.
  * This would require creating a new image to build and maintain, but all other options require this as well.
  * More code to write, test, build and maintain, in comparison to the simple shell script.
  * Advantage is that there is potential for this to be more robust, but I'm not sure there is a need for robustness here.
* Option 3: Create a go program that imports and uses the code etcd uses for creating its database directory, ie [go.etcd.io/etcd/server/v3](https://pkg.go.dev/go.etcd.io/etcd/server/v3).
  * This could alleviate the "etcd must be running" requirement, which would trim the image size since we don't need to include etcd.
  * But, this might require lots of maintenance as, according to the [etcd docs](https://github.com/etcd-io/etcd/blob/004195bb6eac3ddf2646ff0ac2c56654bb3ceda5/Documentation/contributor-guide/modules.md?plain=1#L29), this code is not stable between minor versions: 
  * Might take some time to figure out.
* Option 4: Keep the shell script and create a new container image that uses etcd as a base, and just install shell inside of it.
  * Simplest option there is IMO and the one I recommend we move forward with.
  * But, @ferozsalam, is this possible from the perspective of CVE maintenance? Do we need to avoid shell altogether?

**Comment by ferozsalam** [comment]
From my perspective I'm fine with either 2. or 4. (the other options seem convoluted to me).

2. would be harder to compromise due to the absence of a shell, but if it's significantly more complex from a implementation/maintenance perspective I am happy to start with 4. and take an iterative approach.
 
The current image we're shipping contains 8 Critical and 48 High CVEs in its dependencies, so making any progress to the most recent image is preferable.

Would be interested if @joestringer or @jameslaverack have any thoughts on the approaches described.

**Comment by JamesLaverack** [comment]
👋 Hey! I'd love to help out on this one. Of those options I agree that 2 or 4 seem the most reasonable:

"Option 1: Move init logic into the clustermesh-apiserver" doesn't sound like it really helps that much. "Option 3: Create a go program that imports and uses the code etcd uses for creating its database directory" sounds like it's going to break constantly as etcd change their implementation. I suspect that those APIs could change behaviour without warning too, so it seems pretty risky.

> … from the perspective of CVE maintenance? Do we need to avoid shell altogether?

I don't **think** so. Most of the issues with these older images are everything else, and not the shell itself. Although a shellless container is better for security as there's less for an attacker to use.

I think I might take a brief timeboxed look at the complexity of option 2, but fall back onto option 4 pretty quickly.
Wouldn't we need to test both options anyway (and Go is usually easier to test than Bash).

**Comment by learnitall** [comment]
Sounds like a plan! Writing this in go would definitely be easier to test. @giorio94 do you know how/if we test the etcd initContainer for clustermesh today?

(Also, would someone with permissions mind assigning @JamesLaverack? Thank you!)

**Comment by giorio94** [comment]
Concerning the option 2 vs option 4 discussion above, it is worth mentioning that this custom image would need to be used only for the init container itself (which exposes etcd on localhost only), while the actual container could use any official image that we decide to pick.

**Comment by ferozsalam** [comment]
Thanks for looking at this @JamesLaverack. I can't speak for the low-level details, but the high level approach looks good to me. The replacement init container is minimal, which helps, and TIL about running etcd embedded!

**Comment by JamesLaverack** [comment]
After speaking with @giorio94 today, we're going to slightly change approach:

* Marco is working on some related changes in this area to merge the clustermesh-apiserver and kvstoremesh into a single binary.
* We're going to change approach, after some concerns about version skew when using an embedded etcd to setup etcd, and a container to actually run etcd.
* Instead we're going to embed the etcd binary inside the container image, and exec it from Cilium to perform the initialisation. This will remove the ability for a user to customise the etcd version, but that's likely a feature not a bug.
* We'll retain much of the initialisation Go code already on #26352, but rebase it ontop of Marco's changes. The script is still going away.

**Comment by giorio94** [comment]
The draft PR which merges the clustermesh-apiserver and kvstoremesh into a single binary is up: https://github.com/cilium/cilium/pull/27888
