### ISSUE TITLE
Modularization: Egress Gateway

### ISSUE THREAD

**Issue by lmb** [cilium/cilium#23782]
The Egress Gateway consumes a bunch of events from k8s, creates a desired current state from that and finally updates some BPF maps to effect changes in the datapath. It's a good example of the kind of work the various subsystems do (so I've been told!)

Based on discussion with @jibi we've settled on:

- [x] Move EGW specific bpf maps into `pkg/egressgateway` and provide a cell for them
- [x] Wrap egressgateway into a cell with minimal changes
- [ ] Write a simple test that feeds some fake events into egressgateway and ensures that the correct action is taken
- [ ] Split egressgateway into datapath (responsible for updating maps) and control plane part (which integrates events)

Splitting the EGW is delayed until [excludedCIDR](https://github.com/cilium/cilium/pull/23448) lands to avoid conflicts. Writing tests will be harder, since it's not trivial to get the correct BPF program to feed packets to.

Related: https://github.com/cilium/cilium/issues/23425

**Comment by joamaki** [comment]
Few additional thoughts:
- Move option.Config.*EgressGateway* into EgressGatewayConfig (cell.Config)
- Once feasible, consider moving the datapath parts (the egressgw map and the wrapper around it) to e.g. pkg/datapath/linux/egressgateway. Though this should probably wait until the datapath cell has been moved there from daemon/cmd so we have some scaffolding into which to hook it.
- For BPF tests take a look at bpf/tests/tc_egressgw.c. Default "test" build of bpf_host.o might actually work.
- For the event handler, we'll need `Resource[CiliumEndpoint]`, `Resource[CiliumNode]` and `Resource[CiliumEgressGatewayPolicy]` added to `pkg/k8s/shared_resources.go`. The last one is easy since the existing K8sWatcher is not tied with anything else, but the first two are more involved. CiliumEndpoint watcher for example gets stopped when kvstore connects (watchers/cilium_endpoint.go:102). BTW, does this mean egressgateway is not compatible with kvstore?

**Comment by joamaki** [comment]
@dylandreimerink did some initial modularization work for egress gateway: https://github.com/cilium/cilium/pull/23046.

**Comment by lmb** [comment]
Didn't end up moving maps to pkg/egressgateway for now.

**Comment by margamanterola** [comment]
With feature freeze being one week away, I assume we aren't going to finish the last remaining items for 1.14. Will we finish this for 1.15?

**Comment by lmb** [comment]
Sorry, I didn't see your comment. I wrote the last two bullet points before working on the egw code base. "Injecting events" will start happening when we start using `Resource[T]` and the dataplane / controlplane split is a bit fuzzy as a concept, I think. EGW already has the split between the maps used to communicate between DP and the manager, so in a way this already exists. We can revisit whether the interface should change once the dust has settled on porting to `Resource[T]`.

So my preference would be to close this ticket and track Resource[T] elsewhere.
