### ISSUE TITLE
CFP: cilium ingress should have an option to set the number of trusted loadbalancer hops (as per Envoy config `xff_num_trusted_hops`)

### ISSUE THREAD

**Issue by farcaller** [cilium/cilium#24292]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your feature request related to a problem?**

If cilium ingress is deployed behind an LB that does HTTPS termination, cilium won't pass the `x-forwarded-proto` (or `-for`) to the downstream. This makes it impossible to use cilium ingress in situations where the downstream verifies that the request came over HTTPS as it won't have any context on if that's true or not (as cilium itself did not terminate https).

**Describe the feature you'd like**

CIlium needs an option to allow trusting the x-forwarded-* headers in envoy.

**(Optional) Describe your proposed solution**

Envoy has support for [x-forwarded-for](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#config-http-conn-man-headers-x-forwarded-for) and the rest of the headers.

**Comment by youngnick** [comment]
This seems fair enough to me. I've added this to the service mesh backlog, and we'll see what we can do.

**Comment by youngnick** [comment]
I'll also add a note here that while doing this for Ingress, we should do it for Gateway API as well.

**Comment by O5ten** [comment]
I also stumbled on this today when trying to deploy an application that requires the x-forwarded-proto header because of an external load balancer terminating SSL outside of the cluster. 

In another cluster i have i just add this annotation to tell haproxy what to do: 
```yaml
annotations:
  haproxy.org/request-set-header: X-Forwarded-Proto https
```

Expected to find something like this when googling: 
```yaml
annotations:
  cilium.io/request-set-header: X-Forwarded-Proto https
```

**Comment by youngnick** [comment]
Okay, I've come back to this to have a more detailed look, sorry for the delay.

In general, Envoy handles these headers in a pretty automatic way - X-Forwarded-For is handled for you, as is X-Forwarded-Host (set automatically if you rewrite the host header or hostname in some other way).

For X-Forwarded-For or X-Forwarded-Proto, Envoy allows you to set `xff_num_trusted_hops`, which will mean that X-Forwarded-Proto and X-Forwarded-Port sent from a downstream (that is, external) load balancer will be trusted and used, without needing to configure the header manually.

@farcaller, @O5ten, would either of you be interested in a "Set number of trusted XFF hops" directive? Gateway API already has support for _explicit_ header setting (as in the HAProxy example), and I'd rather avoid adding annotations to Ingress that duplicate that functionality.

But a Cilium install config item that tells Cilium's ingress Envoys to trust X downstream (outside) hops seems like it would solve both your use cases.

**Comment by farcaller** [comment]
> would either of you be interested in a "Set number of trusted XFF hops" directive

yes, that solves my use case.

**Comment by youngnick** [comment]
Okay, I'm going to change the title to reflect the new scope.

The current TODO then is:
- Add a new global config item that sets the number of trusted hops for external load balancers for Ingress (or Gateway API) config. Default to 0, which produces the current behavior.
- Plumb that value to the relevant Envoy configs so that it takes effect for all ingress listeners. (As opposed to Layer 7 policy enforcement listeners)

This is not a huge change, and is ready to start. I'll mark it as `help-wanted` and if we can't get a community contributor, see if we can get the team to fit it into 1.15.

**Comment by chaunceyjiang** [comment]
Hi @youngnick, I'm a beginner and would like to resolve this issue. Could you assign this task to me?

**Comment by vhaudiquet** [comment]
Sorry to revive this closed issue, but what is the correct way to use the pull request that was merged ?

In helm values, I set `envoy.xffNumTrustedHopsL7PolicyIngress` to `1`  (and `gatewayAPI.xffNumTrustedHops` to 1), but it seems that "X-Forwarded-Proto" is still not forwarded to the pod (i'm running authentik, which relies on X-Forwarded-Proto for apiBase url, which is 'http://xxx' for now... even though i'm accessing it via https).
Is that enough ? My setup is nginx proxy manager -> ingress -> pod.

Also, is there any way to trust only a CIDR/IP instead of always trusting last hop ?

Sorry to bother :)
