### ISSUE TITLE
level=fatal msg="Envoy: Binary \"cilium-envoy\" cannot be executed" error="exit status 127" subsys=envoy-manager

### ISSUE THREAD

**Issue by 13567436138** [cilium/cilium#24404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

cilium pod got level=fatal msg="Envoy: Binary \"cilium-envoy\" cannot be executed" error="exit status 127" subsys=envoy-manager

### Cilium Version

1.13

### Kernel Version

root@cluster1-144:~# uname -a
Linux cluster1-144 5.19.0-35-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 3 18:36:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.26.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 13567436138** [comment]
@farcaller can you take a look

**Comment by farcaller** [comment]
Needs more context. How are you deploying cilium?

**Comment by 13567436138** [comment]
using helm

**Comment by youngnick** [comment]
Thanks for logging this @13567436138, could you please grab a sysdump for us, that will have a bunch of information that may help us figure out what's happening. (See https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection for instructions). You can upload to this issue, or make the sysdump available in some other way if it's too large.

Thanks again.

**Comment by 13567436138** [comment]
[cilium-sysdump-20230320-144719.zip](https://github.com/cilium/cilium/files/11014927/cilium-sysdump-20230320-144719.zip)

**Comment by 13567436138** [comment]
@youngnick

**Comment by youngnick** [comment]
Thanks for that @13567436138.

The error is because the Cilium agent expects the cilium-envoy binary to be available in the cilium container. I notice from the sysdump that the cilium daemonset is using a non-standard registry, is that a custom build of the container? If so, it may need to ensure that the cilium-envoy (https://github.com/cilium/proxy) binary is inside the container image.

The released cilium versions include this file at `/usr/bin/cilium-envoy`, and if it's not present, then the layer 7 proxy won't be able to be loaded, as you see here.

**Comment by 13567436138** [comment]
image has no problem，other pod，using the same image，it is running well
![image](https://user-images.githubusercontent.com/31508490/227861195-a70ac130-d7a1-4eb1-ae9d-4e24bc42b56b.png)

**Comment by youngnick** [comment]
Thanks for that @13567436138, I'd recommend execing into that pod and seeing if you can run `/usr/bin/cilium-envoy` from a terminal - there must be some reason why that binary is not running, but I can't see anything from the logs.

**Comment by 13567436138** [comment]
I can not run command kubectl exec -it  container is not exist

**Comment by youngnick** [comment]
To be honest, I'd try deleting that pod and seeing if the recreated pod has the same issue; it seems very weird.

**Comment by 13567436138** [comment]
I deleted the pod ，and the same error

**Comment by 13567436138** [comment]
fatal msg="Envoy: Binary \"cilium-envoy\" cannot be executed" error="exit status 127" subsys=envoy-manager

**Comment by 13567436138** [comment]
I think maybe，the binary execute has some error，but the msg is not sufficient

**Comment by 13567436138** [comment]
I decided to reinstall cilium to see if the problem exist

**Comment by 13567436138** [comment]
even reinstall the problem still exist.and the same node,is this because of the enviroment of the node

**Comment by 13567436138** [comment]
@youngnick

**Comment by 13567436138** [comment]
![image](https://user-images.githubusercontent.com/31508490/229338447-fba95488-a7b2-4cfe-a947-e87bd972fb80.png)
can not debug

**Comment by 13567436138** [comment]
I will add a new node

**Comment by roro-86** [comment]
I seem to have a similar issue, when i execute cilium-envoy from with in the container it throws the following error:

`external/com_github_google_tcmalloc/tcmalloc/system-alloc.cc:661] MmapAligned() failed - unable to allocate with tag (hint, size, alignment) - is something limiting address placement? 0x341380000000 1073741824 1073741824 @ 0x55762b1448 0x55762ad8bc 0x55762ad010 0x557628b850 0x55762aaca4
external/com_github_google_tcmalloc/tcmalloc/arena.cc:58] FATAL ERROR: Out of memory trying to allocate internal tcmalloc data (bytes, object-size); is something preventing mmap from succeeding (sandbox, VSS limitations)? 131072 640 @ 0x55762b17bc 0x557628b8e0 0x55762aaca4`

This issue seems related: https://github.com/envoyproxy/envoy/issues/23339#issuecomment-1290509732
