### ISSUE TITLE
Ensure mutual auth and Policy interact in safe ways

### ISSUE THREAD

**Issue by youngnick** [cilium/cilium#24552]
Spun out from https://github.com/cilium/design-cfps/pull/5#discussion_r1142674630

This issue covers ensuring that we ensure that Cilium can't be used to block its own mutual auth, or that mutual auth policy can't be used to block things that are required for mutual auth to work.

From @joestringer:
> For instance (different options):
> 
> * We have some structure internally that tracks "exceptions to auth", and those peers are _always_ excluded from the auth requirement, transparently
>   
>   * Given the requirement for `toEndpoints`, kube-apiserver might be transparently protected since it's _probably_ not running as a Pod in the cluster so can't be targeted with such policy statements. Does the same apply to SPIRE?
> * We expose some CLI config flag that excludes certain labels, IPs or tuples from auth, then set some sort of default there, and the user can configure it to exclude other things from auth if they have specific constraints in their environment.
> * We provide documentation to protect against footgunnery
> 
> A couple of other corner cases come to mind:
> 
> * Can these statements be used for host firewall?
> * Etcd configuration also comes to mind here for Cilium<->etcd in etcd configuration mode
> * Cilium <-> Cilium auth connections must be exempt

An issue for exceptions to host firewall for mutual auth authentication traffic: #24542.

**Comment by sayboras** [comment]
## Current traffic flow

The below flows are required for mutual authentication to work:

- spire agent <-> spire server
- cilium operator -> spire agent
- cilium agent -> spire agent (via unix socket)
- cilium agent <-> cilium agent on mTLS port

## Proposal approach

- Add reserved identities for spire components (e.g. spire agent and spire server)
- Add allowed L3/L4 rules for traffic between the below pairs:
   - spire agent <-> spire server
   - cilium operator -> spire agent
   - ~cilium agent -> spire agent~ (not required as it's via unix socket on the same node)
   - cilium agent <-> cilium agent on mTLS port
      - make sure the mTLS port is allowed regardless if the host firewall feature is enabled.
- Add a special check for not enforcing auth in authmap for the above cases.

**Comment by sayboras** [comment]
Working on this one currently, target to wrap it up this week.

**Comment by sayboras** [comment]
The above proposal is under the assumption that the spire agent and server are running on the non-host network. However, Spire Agent is actually running on **the host network**, otherwise, the node attestation process will fail. 

- spire agent (host) <-> spire server (pod)
- cilium operator (host) <-> spire agent (host)
- cilium agent (host) -> cilium agent (host) on mTLS port

For host network enforcement, there is no implicit rule injected at all. One existing case is about cilium-health check. This means that we rely on the user to not have any rules blocking related traffics as per the below docs. The PR https://github.com/cilium/cilium/pull/25589 helps to address for the same.

https://docs.cilium.io/en/latest/operations/system_requirements/#firewall-rules
