### ISSUE TITLE
LRP for node-local-dns clashes with FQDN network policies

### ISSUE THREAD

**Issue by Caomoji** [cilium/cilium#24654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

L7 network policies appear not to work with a Local Redirect Policy for `node-local-dns` that is set up following the [documentation](https://docs.cilium.io/en/v1.12/gettingstarted/local-redirect-policy/#node-local-dns-cache). 
Traffic to FQDNs that should be authorized is blocked. It seems that traffic in fact is not proxied by [Cilium DNS proxy ](https://docs.cilium.io/en/latest/security/policy/language/#dns-proxy)as if the LRP would bypass it. Once the DNS proxy cache is filled with an entry however, traffic to that FQDN works even if the LRP is recreated.

When observing the request with Hubble, we noticed that the request is not proxied and that Hubble/Cilium seems to have lost the information about the FQDN (only showing the IP address).
![hubble-with-lrp](https://user-images.githubusercontent.com/116181894/228909802-c3df292b-3761-45b1-a2c2-f8a2d7fd6abd.png)

Here is the expected behavior (without LRP) for comparison:
![hubble-without-lrp](https://user-images.githubusercontent.com/116181894/228909810-e47b5061-b0e7-4af7-9193-4bb1132a9b39.png)

This also impacts metrics collected by Hubble, with the LRP the `dns` label in the source/destination contexts is empty.

### Cilium Version

Experienced on `1.12.5` and  `1.13.0`

### Kernel Version

`5.10.167`,  `6.2.8`

### Kubernetes Version

`1.24`,  `1.25.3`

### Sysdump

[cilium-sysdump.zip](https://github.com/cilium/cilium/files/11113586/cilium-sysdump.zip)

### Anything else?

We reproduced this behavior on a clean Kind cluster only following procedures from the Cilium documentation ([Cilium installation](https://docs.cilium.io/en/v1.13/installation/kind/#gs-kind) & [node-local-dns](https://docs.cilium.io/en/v1.12/gettingstarted/local-redirect-policy/#node-local-dns-cache)):
```bash
# creating a cluster
cat <<-EOF | kind create cluster --config - 
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
EOF

# deploying Cilium
helm repo add cilium https://helm.cilium.io/
docker pull quay.io/cilium/cilium:v1.13.0
kind load docker-image quay.io/cilium/cilium:v1.13.0
helm upgrade --install cilium cilium/cilium --version 1.13.0 --wait \
   --namespace kube-system \
   --set nodeinit.enabled=true \
   --set kubeProxyReplacement=partial \
   --set hostServices.enabled=false \
   --set externalIPs.enabled=true \
   --set nodePort.enabled=true \
   --set hostPort.enabled=true \
   --set bpf.masquerade=false \
   --set image.pullPolicy=IfNotPresent \
   --set ipam.mode=kubernetes \
   --set l7Proxy=true \
   --set localRedirectPolicy=true \
   --set prometheus.enabled=true \
   --set operator.prometheus.enabled=true \
   --set hubble.enabled=true \
   --set hubble.relay.enabled=true \
   --set hubble.metrics.enableOpenMetrics=true \
   --set hubble.metrics.enabled="{drop:sourceContext=namespace\|dns\;destinationContext=namespace\|dns}" 

# installing node-local-dns and its LRP
wget https://raw.githubusercontent.com/cilium/cilium/v1.13/examples/kubernetes-local-redirect/node-local-dns.yaml
kubedns=$(kubectl get svc kube-dns -n kube-system -o jsonpath={.spec.clusterIP}) && sed -i "s/__PILLAR__DNS__SERVER__/$kubedns/g;" node-local-dns.yaml
kubectl apply -f node-local-dns.yaml
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.13/examples/kubernetes-local-redirect/node-local-dns-lrp.yaml

# creating a FQDN network policy
kubectl create ns service-a
cat <<-EOF | kubectl apply -f -
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: deny-world
  namespace: service-a
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - cluster
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toFQDNs:
        - matchName: cilium.io
EOF

# launching a Pod to send some requests
kubectl run -it --rm curl-client  --namespace service-a --image nicolaka/netshoot -- bash
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aditighag** [comment]
@Caomoji Thanks for the report. Did you observe similar behavior with kubeProxyReplacement=strict?

We should document the limitation in the [guide](https://docs.cilium.io/en/v1.12/gettingstarted/local-redirect-policy/#node-local-dns-cache). Are you interested in sending a PR?

**Comment by Caomoji** [comment]
Yes we initially experienced this issue with `kubeProxyReplacement=strict`, I forgot to set it when reproducing it with Kind and after changing it I still get the same behavior.

Do you mean this should be considered as a limitation rather than a bug? Or is it about mentioning it in the documentation until it's fixed? I can send a PR to update the doc either way.

**Comment by aditighag** [comment]
Hi! So the issue was that your CNP spec didn't select the node-local dns labels. With node-local dns, DNS responses are intercepted by the dns caches, and the FQDN rules need to specify the cache pod labels so that DNS responses are redirected to the DNS proxy. 

You'll need to change the `matchLabels` to - 

```
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: node-local-dns
```

I can confirm that connectivity from the test pod to FQDNs work as expected along with node-local dns once the spec is updated -

```
Policy verdict log: flow 0x0 local EP ID 262, remote ID 47992, proto 17, egress, action redirect, auth: disabled, match L3-L4, 10.244.1.149:37117 -> 10.244.1.23:53 udp
-> proxy port 39563 flow 0x0 , identity 2574->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.244.1.149:37117 -> 10.244.1.23:53 udp
-> Request dns from 262 ([k8s:io.kubernetes.pod.namespace=default k8s:run=curl-client k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default k8s:io.cilium.k8s.policy.cluster=kind-kind k8s:io.cilium.k8s.policy.serviceaccount=default]) to 2042 ([k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system k8s:io.cilium.k8s.policy.cluster=kind-kind k8s:io.cilium.k8s.policy.serviceaccount=node-local-dns k8s:io.kubernetes.pod.namespace=kube-system k8s:k8s-app=node-local-dns]), identity 2574->47992, verdict Forwarded DNS proxy: cilium.io.default.svc.cluster.local. A
-> Request dns from 262 ([k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=default k8s:run=curl-client k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default k8s:io.cilium.k8s.policy.cluster=kind-kind]) to 2042 ([k8s:io.cilium.k8s.policy.cluster=kind-kind k8s:io.cilium.k8s.policy.serviceaccount=node-local-dns k8s:io.kubernetes.pod.namespace=kube-system k8s:k8s-app=node-local-dns k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system]), identity 2574->47992, verdict Forwarded DNS proxy: cilium.io.default.svc.cluster.local. AAAA
-> Response dns to 262 ([k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default k8s:io.cilium.k8s.policy.cluster=kind-kind k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=default k8s:run=curl-client]) from 2042 ([k8s:io.cilium.k8s.policy.serviceaccount=node-local-dns k8s:io.kubernetes.pod.namespace=kube-system k8s:k8s-app=node-local-dns k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system k8s:io.cilium.k8s.policy.cluster=kind-kind]), identity 47992->2574, verdict Forwarded DNS proxy: cilium.io.default.svc.cluster.local. AAAA TTL: 4294967295 Answer: ''
-> endpoint 262 flow 0x0 , identity 47992->2574 state reply ifindex lxc3425676740c2 orig-ip 10.244.1.23: 10.244.1.23:53 -> 10.244.1.149:37117 udp
```

`node-local-dns-hqwf9                         1/1     Running            0               21m    10.244.1.23   kind-worker          <none>           <none>`

I'm closing the issue. But if you have any questions, feel free to post them, or reopen the issue.

**Comment by danielleef** [comment]
@aditighag I'm having issues with node-local-dns and Cilium's L7 DNS proxy for FQDN policies.

**Setup:**
- node-local-dns deployed per https://docs.cilium.io/en/stable/network/kubernetes/local-redirect-policy/#node-local-dns-cache
- `dnsproxy-enable-transparent-mode: "true"` is enabled
- CiliumLocalRedirectPolicy redirects coredns service → node-local-dns
- node-local-dns forwards external queries directly to upstream DNS (`__PILLAR__UPSTREAM__SERVERS__`), not through CoreDNS

**Policy:**
- toEndpoints with `k8s-app: node-local-dns` + toPorts 53 + dns rules
- toFQDNs allowing google.com

**Observed behavior:**
- DNS traffic to node-local-dns IS flowing through proxy (736 packets on proxy port 29053)
- FQDN cache remains empty (`cilium fqdn cache list` shows nothing)
- Egress to google.com's IP blocked because no FQDN cache entry exists

**Expected behavior:**
- DNS proxy should parse responses from node-local-dns and populate FQDN cache

**Flow:**
1. Pod queries google.com → node-local-dns (Cilium proxy intercepts)
2. node-local-dns forwards to upstream DNS directly (not CoreDNS)
3. node-local-dns returns response to pod
4. FQDN cache not populated
5. Pod connects to google.com IP → blocked (not in allowed identities)

Is the DNS proxy expected to parse responses from recursive resolvers like node-local-dns? Or does it only work when DNS goes directly to CoreDNS?
