### ISSUE TITLE
CFP: I would like to have rewrite-target for cilium-ingress

### ISSUE THREAD

**Issue by jhodysetiawansekardono** [cilium/cilium#24685]
## Cilium Feature Proposal

Currently, cilium-ingress does not have a rewrite-target feature like [ingress-nginx](https://github.com/kubernetes/ingress-nginx/blob/main/docs/examples/rewrite/README.md) which is very useful when users want to use Cilium's build-in ingress controller.

**Is your feature request related to a problem?**

It's very hard to use cilium-ingress when it doesn't have rewrite-target feature and in the end the user won't use it because it's not as complete as ingress-nginx

**Describe the feature you'd like**

I want cilium-ingress to be able to rewrite-target when a request goes to `/foo` it will be rewritten to `/`

**Comment by michi-covalent** [comment]
pinned the issue so that it gets triaged properly without automatically getting closed ✅

**Comment by gelato** [comment]
Any news on this?

**Comment by youngnick** [comment]
Right now, there is support for this in Gateway API, using the upstream spec. I'd kind of prefer this to be a reason to try out Gateway API and invest the engineering time in moving that along rather than building more annotations for Ingress.

That said, if people are very interested, I'd like to hear more about specific use cases you'd like to be able to do.
