### ISSUE TITLE
Install Cilium with kubernestes 1.25

### ISSUE THREAD

**Issue by Sundragon1993** [cilium/cilium#24781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Could you please give instructions to install Cilium with the latest version of Kubernetes? The quick installation of Cilium has been removed since version 1.10-rc0.

### Cilium Version

Latest

### Kernel Version

1.10.0-rc0

### Kubernetes Version

1.25.0 and 1.24.12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
What do you think is missing from the documentation? Do you have a link to a previous version of the docs that you think is missing now?

**Comment by gchhablani** [comment]
@squeed I have a similar question.
What would be an appropriate replacement for:
```
kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.9/install/kubernetes/quick-install.yaml
```

**Comment by squeed** [comment]
Cilium supports two installation methods, both well documented:

- installation with cilium-cli -> https://docs.cilium.io/en/v1.13/gettingstarted/k8s-install-default/#k8s-install-quick
- installation with helm -> https://docs.cilium.io/en/v1.13/installation/k8s-install-helm/

We no longer provide a static manifest, since we want to do pre-installation customization. When the new install operator is finished, we may transition back to a single installation manifest.
