### ISSUE TITLE
aks to self managed cluster mesh

### ISSUE THREAD

**Issue by TheCodeYoda** [cilium/cilium#24858]
I have 2 clusters.
* AKS cluster [Azure IPAM]
* self managed cluster [cilium v1.10.5]

Is it possible to spawn a cluster mesh with the above specs? AKS to self managed?

**Comment by dylandreimerink** [comment]
There is in theory no reason why this would not be possible as long as the [prerequisites](https://docs.cilium.io/en/stable/network/clustermesh/clustermesh/#prerequisites) are met. However, this might require some significant effort since AKS is very closed off by default and you need access to the node IPs from your self managed cluster. We currently do not have a guide for this.

Also, v1.10 is end of life, I recommend you upgrade your Cilium deployment. Later versions can receive more support and meshing clusters with similar version numbers is best tested.
