### ISSUE TITLE
Flux cannot reconcile services anymore due to duplicate lb-ipam-request-satisfied status

### ISSUE THREAD

**Issue by n0rad** [cilium/cilium#24945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Following #24502 on https://github.com/cilium/cilium/issues/24502#issuecomment-1511630042, when deleting the `CiliumLoadBalancerIPPool` to get around the bug, flux cannot reconcile anymore services, even after applying back the pool.

```
✗ Kustomization reconciliation failed: Service/network-cluster/nginx-ingress-controller dry-run failed, error: failed to create manager for existing fields: failed to convert new object (network-cluster/nginx-ingress-controller; /v1, Kind=Service) to smd typed: .status.conditions: duplicate entries for key [type="io.cilium/lb-ipam-request-satisfied"]
```

All services have to be deleted along the pool before being able to reconcile.

 
Actually I think I saw it once even without deleting the pool

### Cilium Version

```
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
Client: 1.13.1 a6be57eb 2023-03-15T19:39:01+01:00 go version go1.19.6 linux/amd64
Daemon: 1.13.1 a6be57eb 2023-03-15T19:39:01+01:00 go version go1.19.6 linux/amd64
```

### Kernel Version

```
Linux srv1 6.2.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 30 Mar 2023 14:51:14 +0000 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"archive", BuildDate:"2023-03-19T19:47:22Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.4", GitCommit:"f89670c3aa4059d6999cb42e23ccb4f0b9a03979", GitTreeState:"clean", BuildDate:"2023-04-12T12:05:35Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

[cilium-sysdump-20230418-235454.zip](https://github.com/cilium/cilium/files/11266734/cilium-sysdump-20230418-235454.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by n0rad** [comment]
For completeness, I did the sysdump yesterday after no restart of any cilium pod (since I'm running a stable bare metal cluster) and with working route advertisement, so I'm not 100% sure it's linked to #24502 (except if it's a weird state left by it).

Also looking at the service events example I past just above, since conditions are contradicted and published at the same exact time, it look more like a race condition in cilium than an expected feature incompatible with flux.

**Comment by munai-das** [comment]
What was the fix for this?

**Comment by addreas** [comment]
Also encountered this through Flux, though this issue would arise for anything that uses tries to do structured merges  using [kubernetes/apimachinery](https://github.com/kubernetes/apimachinery/blob/master/pkg/util/managedfields/internal/structuredmerge.go#L100) since that is where the error originates. 

From what I can  tell  this is unrelated to https://github.com/fluxcd/flux2/issues/1522. 

> I don't think that duplicate keys violate any k8s guideline, given that the API server does not reject it.

How structured merges should be made is [defined for the `Service` status](https://github.com/kubernetes/api/blob/v0.26.0/core/v1/types.go#LL4416C1-L4419C21), and with this definition multiple conditions with the same `type` shouldn't exist, even though the API server doesn't reject this. Perhaps it should.

(There are [guidelines](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/1623-standardize-conditions/README.md) for how `.status.conditions` should be structured, and the current implementation of the BGP Control Plane is not following the naming conventions for `reason` and `type`)

A half-workaround until this can be fixed is to `kubectl patch service [service-name] --subresource=status --type=merge --patch='{"status":{ "conditions": []}}'`, but it seems the conflicting conditions still pop up later when cilium runs its reconcile loop so this will probably only help for a single reconciliation.

**Comment by dylandreimerink** [comment]
@addreas I think you are right, given [KEP-1623](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/1623-standardize-conditions/README.md). I think we should rename our constants to match the same pattern, but more importantly, start using the standardized apimachinery to manage conditions: https://github.com/kubernetes/apimachinery/blob/master/pkg/api/meta/conditions.go this seems to merge them properly on `type`.

**Comment by dedene** [comment]
Has there been any progress towards this issue or is there a sort of non-manual workaround? This makes using CiliumLoadBalancerIPPools in combination with GitOps / FluxCD a bit cumbersome.

**Comment by dylandreimerink** [comment]
There has been no progress on the issue. It is still on my radar, but I simply have not yet had the time to fix it yet. I also welcome community contributions if anyone can get this done before I can get to it.

**Comment by addreas** [comment]
Had a look, and the changes are pretty minimal actually. Was tempted to also un-reverse the reverse-dns in the `io.cilium/lb-ipam-ips`, but that would have been a bit of a breaking change I guess.
