### ISSUE TITLE
Clustermesh-apiserver: CiliumEndpoint out of order deletions leads to dropping packets for valid network policies

### ISSUE THREAD

**Issue by dboslee** [cilium/cilium#25562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After cycling several thousand pods at once we observed cilium reporting dropped packets with the reason `Policy Denied` to pods running in other clusters joined together with clustermesh that should have been allowed.

We traced this down to the clustermesh-apiservers in the cluster where the destination pods were hosted. The destination pod IPs were correct, the ciliumendpoint CRs existed, however some IPs were missing from clustermesh-apiserver kvstore (etcd sidecar container). This was observed well after clustermesh-apiserver finished processing its queue of events.

We have concluded this happens due to a combination of ip reuse and deletion events being processed out of order by clustermesh-apiserver.

Under heavy load (many ciliumendpoint create/update/delete events)  the clustermesh-apiserver is unable to keep up with the queue which leads to backpressure on the watch connection. Eventually the watcher fails which leads to a re-list where create events get re-queued and processed before delete events.

When an IP is reused and the creation of the new ciliumendpoints is processed before the deletion of the old ciliumendpoints the clustermesh-apiserver blindly deletes the ip from the kvstore since the keys are identical (e.g. `cilium/state/ip/v1/default/100.10.10.10`). The only way to recover from this state was to restart the clustermesh-apiservers to resync the ciliumendpoints or restart the impacted pods to create new ciliumendpoints.

#### What I expect to happen

I would expect cilium to handle out of order deletions properly. This could be accomplished by doing a comparison of the `namespace/pod` stored in the value against that in the ciliumendpoint before doing the delete. And only deleting when the `namespace/pod` are the same.

I also noticed the clustermesh-apiserver is using an informer directly to process events while doing blocking operations which is a big contributor to the backpressure/failure we are observing. Using a [workqueue](https://pkg.go.dev/k8s.io/client-go/util/workqueue) or [controller](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.14.6/pkg/controller#Controller) would help process these events without blocking to help mitigate the issue and improve performance.

1. Initially observed on EKS and reproduced using KIND
2. Clustermesh-apiserver enabled using CRDs to propigate endpoints
3. I've included a bash script I used to reproduce the issue in a local kind cluster. It performs the following:

#### Steps to reproduce
1. Create a ciliumendpoint `endpoint1` with the ip 100.10.10.10.
2. Generate load by creating and deleting 5000 ciliumendpoints
3. Delete `endpoint1`
4. Generate load by creating and deleting 5000 ciliumendpoints
5. Create a ciliumendpoint `endpoint2` with the ip 100.10.10.10 (same ip).
6. Observe the output of watching the key
```bash
etcdctl --cert etcd.crt --cacert etcd-ca.crt --key etcd.key watch cilium/state/ip/v1/default/100.10.10.10
PUT
cilium/state/ip/v1/default/100.10.10.10
{"IP":"100.10.10.10","Mask":null,"HostIP":"","ID":0,"Key":0,"Metadata":"","K8sNamespace":"default","K8sPodName":"endpoint2"}
DELETE
```
<details>
<summary>Bash script to reproduce race condition</summary>

```bash
#!/bin/bash
set -e

total_ciliumendpoints=5000
batch_size=100

# Extract etcd client credentials
kubectl -n kube-system get secret clustermesh-apiserver-remote-cert -o json | jq -r '.data["tls.crt"]' | base64 -d > etcd.crt
kubectl -n kube-system get secret clustermesh-apiserver-remote-cert -o json | jq -r '.data["tls.key"]' | base64 -d > etcd.key
kubectl -n kube-system get secret clustermesh-apiserver-remote-cert -o json | jq -r '.data["ca.crt"]' | base64 -d > etcd-ca.crt

# Start the kubectl port-forward in the background
kubectl -n kube-system port-forward svc/clustermesh-apiserver 2379:2379 > /dev/null &

# Store the process ID of the background process
port_forward_pid=$!

# Function to clean up the background process when the script finishes
cleanup() {
  kill $port_forward_pid
}

check_etcd() {
    echo
    echo "Checking etcd:"
    sleep 1
    etcdctl --cert etcd.crt --cacert etcd-ca.crt --key etcd.key get cilium/state/ip/v1/default/100.10.10.10
    echo
}

# Register the cleanup function to be called on script exit
trap cleanup EXIT

ENDPOINT_YAML=""

generate_ciliumendpoint_yaml() {
  local index=$1
  cat <<EOF
apiVersion: cilium.io/v2
kind: CiliumEndpoint
metadata:
  name: endpoint-$index
status:
  networking:
    addressing:
    - ipv4: 10.10.10.$index
EOF
}

apply_ciliumendpoints_batch() {
  local start=$1
  local end=$2
  local batch_yaml=""
  for ((i = start; i < end; i++)); do
    yaml=$(generate_ciliumendpoint_yaml $i)
    batch_yaml+="$yaml"$'\n---'$'\n'  # Separate YAMLs with '---' and add newline
  done
  echo "$batch_yaml" | kubectl apply -f -
}

delete_ciliumendpoints_batch() {
  local start=$1
  local end=$2
  local batch_yaml=""
  for ((i = start; i < end; i++)); do
    yaml=$(generate_ciliumendpoint_yaml $i)
    batch_yaml+="$yaml"$'\n---'$'\n'  # Separate YAMLs with '---' and add newline
  done
  echo "$batch_yaml" | kubectl delete --wait=false -f -
}

generate_load() {
    for ((start = 0; start < total_ciliumendpoints; start += batch_size)); do
    end=$((start + batch_size))
    if ((end > total_ciliumendpoints)); then
        end=$total_ciliumendpoints
    fi

    echo "Applying CiliumEndpoints batch: $start - $((end - 1))"
    apply_ciliumendpoints_batch $start $end
    done

    for ((start = 0; start < total_ciliumendpoints; start += batch_size)); do
    end=$((start + batch_size))
    if ((end > total_ciliumendpoints)); then
        end=$total_ciliumendpoints
    fi

    echo "Applying CiliumEndpoints batch: $start - $((end - 1))"
    delete_ciliumendpoints_batch $start $end
    done
}

create_endpoint1(){
endpoint1='
apiVersion: cilium.io/v2
kind: CiliumEndpoint
metadata:
  name: endpoint1
status:
  networking:
    addressing:
    - ipv4: 100.10.10.10
'
echo "$endpoint1" | kubectl apply -f -
}

create_endpoint1
check_etcd
generate_load
kubectl delete ciliumendpoint/endpoint1
check_etcd
sleep 5
generate_load

# Create second endpoint with the same IP.
endpoint2='
apiVersion: cilium.io/v2
kind: CiliumEndpoint
metadata:
  name: endpoint2
status:
  networking:
    addressing:
    - ipv4: 100.10.10.10
'
echo "$endpoint2" | kubectl apply -f -

etcdctl --cert etcd.crt --cacert etcd-ca.crt --key etcd.key watch cilium/state/ip/v1/default/100.10.10.10

# Clean up endpoint2 before running again.
# kubectl delete ciliumendpoint/endpoint2
```

</details>

### Cilium Version

1.12.3

### Kernel Version

5.4.228-132.418.amzn2.x86_64

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.16-eks-48e63af", GitCommit:"e6332a8a3feb9e0fe3db851878f88cb73d49dd7a", GitTreeState:"clean", BuildDate:"2023-01-24T19:18:15Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output
We frequently see logs from the `DeltaFIFO Pop Process` saying `slow event handlers blocking the queue`.
```
level=info msg="Trace[966577027]: \"DeltaFIFO Pop Process\" ID:kube-system/endpoint-97,Depth:884,Reason:slow event handlers blocking the queue (19-May-2023 16:49:12.790) (total time: 200ms):" subsys=klog
level=info msg="Trace[966577027]: [200.65117ms] [200.65117ms] END" subsys=klog
level=info msg="Inserted endpoint into etcd: {10.10.10.98 <nil> <nil> unknown 0  kube-system endpoint-98 []}" subsys=clustermesh-apiserver
level=info msg="Trace[557003893]: \"DeltaFIFO Pop Process\" ID:kube-system/endpoint-98,Depth:883,Reason:slow event handlers blocking the queue (19-May-2023 16:49:12.990) (total time: 200ms):" subsys=klog
level=info msg="Trace[557003893]: [200.290023ms] [200.290023ms] END" subsys=klog
level=info msg="Inserted endpoint into etcd: {10.10.10.99 <nil> <nil> unknown 0  kube-system endpoint-99 []}" subsys=clustermesh-apiserver
level=info msg="Trace[1278055974]: \"DeltaFIFO Pop Process\" ID:kube-system/endpoint-99,Depth:882,Reason:slow event handlers blocking the queue (19-May-2023 16:49:13.191) (total time: 199ms):" subsys=klog
level=info msg="Trace[1278055974]: [199.076903ms] [199.076903ms] END" subsys=klog
level=info msg="Inserted endpoint into etcd: {10.10.10.100 <nil> <nil> unknown 0  kube-system endpoint-100 []}" subsys=clustermesh-apiserver
level=info msg="Trace[612181316]: \"DeltaFIFO Pop Process\" ID:kube-system/endpoint-100,Depth:881,Reason:slow event handlers blocking the queue (19-May-2023 16:49:13.390) (total time: 199ms):" subsys=klog
level=info msg="Trace[612181316]: [199.613696ms] [199.613696ms] END" subsys=klog
level=info msg="Inserted endpoint into etcd: {10.10.10.101 <nil> <nil> unknown 0  kube-system endpoint-101 []}" subsys=clustermesh-apiserver
level=info msg="Trace[47538077]: \"DeltaFIFO Pop Process\" ID:kube-system/endpoint-101,Depth:880,Reason:slow event handlers blocking the queue (19-May-2023 16:49:13.590) (total time: 200ms):" subsys=klog
level=info msg="Trace[47538077]: [200.600939ms] [200.600939ms] END" subsys=klog
level=info msg="Inserted endpoint into etcd: {10.10.10.102 <nil> <nil> unknown 0  kube-system endpoint-102 []}" subsys=clustermesh-apiserver
level=info msg="Trace[976094207]: \"DeltaFIFO Pop Process\" ID:kube-system/endpoint-102,Depth:879,Reason:slow event handlers blocking the queue (19-May-2023 16:49:13.790) (total time: 199ms):" subsys=klog
level=info msg="Trace[976094207]: [199.310668ms] [199.310668ms] END" subsys=klog
level=info msg="Inserted endpoint into etcd: {10.10.10.103 <nil> <nil> unknown 0  kube-system endpoint-103 []}" subsys=clustermesh-apiserver
level=info msg="Trace[1478378861]: \"DeltaFIFO Pop Process\" ID:kube-system/endpoint-103,Depth:878,Reason:slow event handlers blocking the queue (19-May-2023 16:49:13.990) (total time: 199ms):" subsys=klog
level=info msg="Trace[1478378861]: [199.976645ms] [199.976645ms] END" subsys=klog
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giorio94** [comment]
Thanks @dboslee for the detailed report. This issue should be fixed by https://github.com/cilium/cilium/pull/25049, which refactors the clustermesh-apiserver to use a workqueue to process the events for improved performance and resiliency. I'm going to run your repro script to double-check that it works as expected.

**Comment by rcanderson23** [comment]
@giorio94 Thanks for this. In my very rough testing, I used 10k artificial `CiliumEndpoints` and the current version took about 17min to get them all inserted into the local etcd, running with your change it was finished before I was able finish typing `kubectl logs -f`. I also did not observe the out of order deletion like we did prior.

**Comment by giorio94** [comment]
> @giorio94 Thanks for this. In my very rough testing, I used 10k artificial `CiliumEndpoints` and the current version took about 17min to get them all inserted into the local etcd, running with your change it was finished before I was able finish typing `kubectl logs -f`. I also did not observe the out of order deletion like we did prior.

I suspect that the reason for the huge performance difference in this case is that, being the `CiliumEndpoints` first created and then immediately deleted, they are never actually written into etcd (since the events are coalescenced through the workqueue). With the default rate-limiting settings (20QPS, which can be tuned through `--kvstore-opt=etcd.qps=QPS`) it is reasonable that it takes ~17min to first create and then delete 10K endpoints.

**Comment by giorio94** [comment]
I double-checked waiting for the endpoints to be propagated into etcd before deleting them, and it took as expected based on the rate-limiting configuration. I only had to change the ipv4 generation of the original script to ensure that it was valid:

```
 - ipv4: 10.10.$(( index / 256 )).$(( index % 256 ))
```

Logs no longer mention `slow event handlers blocking the queue`, since events are now quickly read from the informer and then enqueued.

**Comment by giorio94** [comment]
> Unfortunately the helm chart doesn't not expose anything to allow additional flags for clustermesh to be configured.

Mmm, that's true. There's env variable support, but AFAIK they have lower precedence that args...

> Would it be best to open a separate issue calling that out specifically? I'm willing to post a PR for it as well

Please, feel free to go ahead (and to ping me in case you need any help). A specific issue is not necessary if you plan to post the PR soon. Otherwise, it would be great if you could open it, so that we don't forget once this one gets closed.

**Comment by sclevine** [comment]
From @rcanderson23's testing, seems like the QPS limit is the main issue we experience with the slowness in reindexing.

For completeness, during the pod churn that @dboslee described, we also also found etcd struggling with the write load, with ~5 of these per second:
```
{"level":"warn","ts":"[redact]","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"700.254302ms","expected-duration":"100ms","prefix":"read-only range ","request":"key:\"cilium/state/services/v1/[redact]/[redact]/[redact]\" ","response":"range_response_count:1 size:602"}
```

We don't always see them during reindexing, even when it takes 20m. The EBS volume we have under etcd measures 4ms latency at 99th percentile (under the 10ms [recommended](https://etcd.io/docs/v3.4/op-guide/performance/)) but we don't have EBS optimization enabled. Not sure if the qps limit would result in those, or only disk latency / cpu load as etcd documents.

Shortly after the incident, we also noticed 100s of these over the course of a few minutes:
```
{"level":"warn","ts":"[redact]","caller":"etcdserver/util.go:123","msg":"failed to apply request","took":"19.544µs","request":"header:<ID:[redact] username:\"[redact]\" auth_revision:13 > lease_revoke:<id:[redact]>","response":"size:27","error":"lease not found"}
```
Seems like this happens due to load balancing between separate etcd instances? May not be relevant.

**Comment by giorio94** [comment]
> Not sure if the qps limit would result in those, or only disk latency / cpu load as etcd documents.

Rate limiting is directly performed on the clustermesh-apiserver side (requests to etcd are throttled at the specified rate). It should not have any influence on the warning messages that are reported by etcd.

> Shortly after the incident, we also noticed 100s of these over the course of a few minutes:
> ```
> {"level":"warn","ts":"[redact]","caller":"etcdserver/util.go:123","msg":"failed to apply request","took":"19.544µs","request":"header:<ID:[redact] username:\"[redact]\" auth_revision:13 > lease_revoke:<id:[redact]>","response":"size:27","error":"lease not found"}
> ```

This seems definitely strange, and I couldn't reproduce it (nor the other warning) on a first attempt.

Could you please elaborate a bit about your setup to better consider the possible sources of the issue? In particular:
* Are you running the clustermesh-apiserver as configured by helm (i.e., with etcd as sidecar backed by an `emptyDir` volume for storage) or is etcd managed externally? 
* Did you configure any resource limits on the clustermesh-apiserver/etcd containers?
* Were the tests performed with remote clusters configured to connect to the given etcd instance or not? If yes, what is the rough number of nodes across the entire cluster mesh (as that translates to the number of active watchers for a given kvstore prefix).

**Comment by sclevine** [comment]
> Rate limiting is directly performed on the clustermesh-apiserver side (requests to etcd are throttled at the specified rate). It should not have any influence on the warning messages that are reported by etcd.

Thanks for confirming. We'll switch to lower latency storage as well.

> This seems definitely strange, and I couldn't reproduce it (nor the other warning) on a first attempt.

Seems like this error can occur when multiple etcd instances are placed behind a load balancer? E.g., https://github.com/apache/apisix/issues/7476.

> Are you running the clustermesh-apiserver as configured by helm (i.e., with etcd as sidecar backed by an emptyDir volume for storage) or is etcd managed externally?

Helm chart, with two replicas of clustermesh-apiserver (each including the single-node etcd sidecar, backed by emptyDir on EBS).

> Did you configure any resource limits on the clustermesh-apiserver/etcd containers?

Only the apiserver container was constrained, with:
```
  resources:
      limits:
        cpu: "1"
        memory: 1024M
      requests:
        cpu: 200m
        memory: 512Mi
```

Combined memory usage for apiserver and etcd never exceeded 300MiB. apiserver CPU stayed under 0.02, etcd under 0.150. We did not observe CPU throttling. (We plan to [remove the CPU limit in the future](https://home.robusta.dev/blog/stop-using-cpu-limits).)

> Were the tests performed with remote clusters configured to connect to the given etcd instance or not? If yes, what is the rough number of nodes across the entire cluster mesh (as that translates to the number of active watchers for a given kvstore prefix).

Both log lines were from the production incident, with all remote clusters connected. Roughly 80 nodes running the cilium agent across 6 clusters, all in different geographic regions.

**Comment by giorio94** [comment]
> > Rate limiting is directly performed on the clustermesh-apiserver side (requests to etcd are throttled at the specified rate). It should not have any influence on the warning messages that are reported by etcd.
> 
> Thanks for confirming. We'll switch to lower latency storage as well.

Sounds reasonable. Two additional possibilities here might be:
* Enabling tracing in the etcd server, to better understand the cause of the latency spike: https://github.com/etcd-io/etcd/issues/11166
* Use a `tmpfs`-backed `emptyDir` volume, to confirm that the latency is storage related (https://kubernetes.io/docs/concepts/storage/volumes/#emptydir). That parameter is not currently configurable through the helm chart, hence you'll need to customize it manually. 

> 
> > This seems definitely strange, and I couldn't reproduce it (nor the other warning) on a first attempt.
> 
> Seems like this error can occur when multiple etcd instances are placed behind a load balancer? E.g., [apache/apisix#7476](https://github.com/apache/apisix/issues/7476).

That's indeed possible and most likely. The other explanation would be that the apiserver failed to renew its own lease. In that case, all keys would be deleted, because they are associated to that lease. This seems extremely unlikely to me, since that lease has by default a quite large expiration period (15 minutes). You should be able to confirm the originator of the request looking at the username (which is redacted in the log above): by default the agents use `remote`, while the apiserver uses either `root` or `admin-<cluster-name>` depending on the version.

> 
> > Are you running the clustermesh-apiserver as configured by helm (i.e., with etcd as sidecar backed by an emptyDir volume for storage) or is etcd managed externally?
> 
> Helm chart, with two replicas of clustermesh-apiserver (each including the single-node etcd sidecar, backed by emptyDir on EBS).

Heads up that running two replicas of clustermesh-apiserver is currently not officially supported, and might lead to subtle issues when one remote agent switches the connection from one replica to another (since they are two separated etcd clusters and their state is not aligned). 

> 
> > Did you configure any resource limits on the clustermesh-apiserver/etcd containers?
> 
> Only the apiserver container was constrained, with:
> 
> ```
>   resources:
>       limits:
>         cpu: "1"
>         memory: 1024M
>       requests:
>         cpu: 200m
>         memory: 512Mi
> ```
> 
> Combined memory usage for apiserver and etcd never exceeded 300MiB. apiserver CPU stayed under 0.02, etcd under 0.150. We did not observe CPU throttling. (We plan to [remove the CPU limit in the future](https://home.robusta.dev/blog/stop-using-cpu-limits).)

Yeah, resource consumption of the apiserver is not a concern. I've seen etcd consuming quite a lot of resources with a much higher number of watchers, but in your case it seems pretty under control and there's no limit configured to constrain it.

> 
> > Were the tests performed with remote clusters configured to connect to the given etcd instance or not? If yes, what is the rough number of nodes across the entire cluster mesh (as that translates to the number of active watchers for a given kvstore prefix).
> 
> Both log lines were from the production incident, with all remote clusters connected. Roughly 80 nodes running the cilium agent across 6 clusters, all in different geographic regions.

Thanks for the information, that number of agents should not pose any concerns on etcd from what I've seen in the past.

**Comment by marseel** [comment]
I was able to reproduce the issue with expiring leases and it seems it has to do with locking in etcd server and increasing the number of keys attached to a single lease (which is what clustermesh is doing currently): https://github.com/etcd-io/etcd/issues/15993

We plan to mitigate the issue with a high initial synchronization time and also expiring leases by introducing "inflight" requests rather than strict QPS for clustermesh: https://github.com/cilium/cilium/pull/25817 - so in case of initial synchronization, we should be doing much higher QPS, but once Etcd requests slow down, QPS will decrease, reducing the load on Etcd.

Long term plan is to either use multiple leases or get rid of leases.

**Comment by giorio94** [comment]
I'm closing this issue, given that all fixes/improvements herein discussed have been merged and are available in v1.14:

* https://github.com/cilium/cilium/pull/25049
* https://github.com/cilium/cilium/pull/25817
* https://github.com/cilium/cilium/pull/25966

**Comment by cmergenthaler** [comment]
@giorio94 I know this is an old issue but we ran into exactly the same issue with v1.18.4. We observed an out-of-order deletion for 2 pods during high pod churn (k8s upgrade and node rotations) where the upsert happened some seconds before the delete in clustermesh-apiserver. 

```
21/01/2026 11:17:45.808 msg="Updating resource in etcd" module=clustermesh.clustermesh-synchronization resource=CiliumEndpoint operation=upsert key=<pod-ip>
21/01/2026 11:18:30.032 msg="Updating resource in etcd" module=clustermesh.clustermesh-synchronization resource=CiliumEndpoint operation=delete key=<pod-ip>
```
Note that we run clustermesh-apiserver with 2 replicas in HAMode (using sessionaffinity) and the out-of-order delete happened on both instances simultaneously.

I can open a new issue if that is preferred.

**Comment by giorio94** [comment]
Hey @cmergenthaler, thanks for your report. 

Could you please open a new issue, and ping me there, given that the underlying cause is most likely unrelated to that discussed in this one? 

Given that you mentioned high pod churn, one guess is that this may have happened if a pod IP gets reused by a new pod (and included in a CiliumEndpoint) before an old CiliumEndpoint referencing the same IP is deleted. Do you have any ways of checking from the logs if the affected Pod IP got recycled in a very short period of time? Are you using CiliumEndpointSlices?

The current clustermesh synchronization logic is known to be prone to that (so far theoretical) problem (for CiliumEndpoints and CiliumEndpointSlices), but I hadn't manage to see it in the wild yet (other parts of Cilium may also get confused in the same situation).
