### ISSUE TITLE
Minor improvement: automatically cleanup stale AWS-CNI iptables rules in nodeinit

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#25804]
In the [install documentation for EKS](https://github.com/cilium/cilium/blob/v1.13/Documentation/installation/k8s-install-helm.rst?plain=1#L208), it has you manually remove some stale AWS iptables rules. *Not* removing these rules results in subtle and random connectivity issues, most notably around host-network processes accessing the pod network. This typically results in a failure to reach the health check.

So, when we're sure these aren't in use, we should remove these in the [nodeinit script](https://github.com/cilium/cilium/blob/v1.13/install/kubernetes/cilium/files/nodeinit/startup.bash).

The challenge is knowing these rules are not in use. From reading the install documentation, I don't see a reliable way to detect it, so we'll have to add another helm value. Probably something like `nodeinit.removeAWSCNI`.

**Comment by nebril** [comment]
@squeed AFAIU we are not recommending enabling nodeinit on EKS, and we actually remove these iptables via post-start Cilium hook defined here:
https://github.com/cilium/cilium/blob/v1.13/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L228
https://github.com/cilium/cilium/blob/v1.13/install/kubernetes/cilium/files/agent/poststart-eni.bash

I think the docs are actually out of sync.

**Comment by squeed** [comment]
Oh nice! Do you think we should backport that to v1.12, or are the docs sufficient?

**Comment by squeed** [comment]
@nebril that code is only enabled when using ENI mode. There are two other cases we need to consider:

1. We are on AWS, but not using ENI mode (encapsulation). Then we **do** need to remove the iptables rules.
2. We are on AWS, chaining with aws-cni. Then we **must not** remove the iptables rules.


I'm not sure if we can detect case 1 with the current Helm values.

**Comment by nebril** [comment]
At this point I am inclined to run this post-start hook always, unless `cni.chainingMode` is set to `aws-cni`, but that seems like not the most elegant solution :(.

**Comment by rabbagliettiandrea** [comment]
hello there,
this is a really crucial fix in my humble opinion. In EKS scenario often you don't have access to nodes and it would be great to fix the iptables stuff at cilium level.

As you already know unfortunately this is mandatory if you configure Cilium to do overlay mode :/

**Comment by rabbagliettiandrea** [comment]
Also, please note the following:

Scenario A [NOT WORKING]:

1. create new EKS cluster
2. delete VPC CNI related resources
3. install Cilium with overlay (tunnel: vxlan) and eni mode disabled
4. cilium status gives you unreachable to some nodes

Scenario B [WORKING]:

1. create new EKS cluster
2. delete VPC CNI related resources
3. install Cilium with eni mode enabled
4. cilium status says: OK
5. uninstall Cilium with eni mode enabled
6. install Cilium with overlay (tunnel: vxlan) and eni mode disabled
7. cilium status says: OK (and that's why it flushed the rules in the step 3. I guess)

Scenario C [WORKING]:

1. create new EKS cluster
2. delete VPC CNI related resources
3. install Cilium with overlay (tunnel: vxlan) and eni mode disabled but with nodeinit with iptables flush
4. cilium status says: OK

I really thing that this is something to be addressed

**Comment by rabbagliettiandrea** [comment]
The command that I use to flush the stale rules:

`iptables-save | grep -v 'AWS-SNAT-CHAIN\|AWS-CONNMARK-CHAIN' | iptables-restore`
