### ISSUE TITLE
update 'github.com/mdlayher/arp'

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#25814]
This dependency is being used by our [metallb](https://github.com/cilium/metallb) fork. We should update our fork to use a new version of 'github.com/mdlayher/arp' so that we revert the change made in https://github.com/cilium/cilium/pull/25807

**Comment by cyclinder** [comment]
hi @aanm, is updated  `github.com/mdlayher/arp` to the latest version?

**Comment by cyclinder** [comment]
@christarazi Can you confirm this? thanks

**Comment by dylandreimerink** [comment]
Metal LB uses the library, likely for their L2 feature, which we never supported (can't be enabled in the embedded version in Cilium) so we should be able to update without consequence as long as the API did not change. 

We also have a direct dependency since https://github.com/cilium/cilium/pull/25254, where we do actually use it, so we will need to watch out for that if we upgrade.

**Comment by christarazi** [comment]
I think what @dylandreimerink said covers everything.

**Comment by plant99** [comment]
Hey @aanm I'd love to work on this if you could please assign it to me?

**Comment by aanm** [comment]
@plant99 assigned

**Comment by SejalJain1710** [comment]
Hi folks, I was searching through the good first issues as a first time OS contributor and came across this issue which I believe is now closed. When you find the time could you please close the issue as well? Thankyou!

**Comment by tklauser** [comment]
The metallb dependecy was dropped in #36191, but we still exclude updates for `github.com/mdlayher/arp` in the renovate config. Should be fixed by #36542.
