### ISSUE TITLE
clustermesh sync'ing all services not just global

### ISSUE THREAD

**Issue by dctrwatson** [cilium/cilium#26049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

`cilium status` is reporting 1000s of global-services for clustermesh. However, there are only a couple hundred services with the global annotation.

### Cilium Version

1.13.3 36cb0eed 2023-05-17T12:31:14-04:00 go version go1.19.8 linux/amd64

### Kernel Version

Linux ip-10-195-65-53 5.15.0-1037-aws #41~20.04.1-Ubuntu SMP Mon May 22 18:18:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.24.13-eks-0a21954

### Anything else?

Looks like an inverted bool here: https://github.com/cilium/cilium/blob/8cb94c70f7105f29a69e754d2b8969117e681775/clustermesh-apiserver/main.go#L633

Per the comment of: https://github.com/cilium/cilium/blob/8cb94c70f7105f29a69e754d2b8969117e681775/operator/watchers/k8s_service_sync.go#L96-L99

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giorio94** [comment]
Hi @dctrwatson, this has been fixed in https://github.com/cilium/cilium/pull/25259. 

Essentially, the clustermesh-apiserver needs to synchronize all services to support the external workloads feature, but you can now disable it if not used and synchronize only the shared/global services. Please consider that the `enable-external-workloads=false` flag is added only when installing Cilium through helm (if `externalWorkloads.enabled=false`, which is the default), or the Helm-based cilium CLI. The legacy Cilium CLI instead never configures that flag (but it can be added manually). 

Given the above I'm closing this issue, but feel free to reopen it if anything is missing.

**Comment by dctrwatson** [comment]
> Hi @dctrwatson, this has been fixed in #25259.
> 
> Essentially, the clustermesh-apiserver needs to synchronize all services to support the external workloads feature, but you can now disable it if not used and synchronize only the shared/global services. Please consider that the `enable-external-workloads=false` flag is added only when installing Cilium through helm (if `externalWorkloads.enabled=false`, which is the default), or the Helm-based cilium CLI. The legacy Cilium CLI instead never configures that flag (but it can be added manually).

Ohhh! Sorry, didn't realize that was related. Thank you!

Will that be backported to v1.12 and v1.13 by any chance?

**Comment by giorio94** [comment]
Sorry, this slipped under my radar. Given that the original PR is pretty small in size and it brings potentially significant performance improvements in common environments, I think that it is reasonable for it to be backported to v1.13. I'd say instead that it does not match the [requirements](https://docs.cilium.io/en/stable/contributing/release/backports/#backport-criteria-for-x-y-1-z-and-x-y-2-z) for being backported to v1.12 (security/major bug fixes only). I've labeled the PR accordingly.
