### ISSUE TITLE
ICMP Fragmentation blocked when ingress policy present

### ISSUE THREAD

**Issue by dosmanak** [cilium/cilium#26193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

* AKS cluster with Azure CNI in chain with cilium 1.11 -> 1.13 
* kubernetes cluster CIDR is routed via VPN (IPsec) to on-prem network.
* pod with with ingress policy that allows only few endpoints access its http port and egress policy that allow just toCIDR etc.

The pod sends HTTP POST with large payload, but the server respondes with `408` request timeout. In the hubble observe I could see the ICMP packet is dropped. The fragmentation request comes from different IP address than the target of my request. Using tcpdump on worker node I see the packets.
```
IP 10.64.142.184.34552 > 10.250.2.2.http: Flags [.], seq 1:1399, ack 9714, win 501, options [nop,nop,TS val 302428356 ecr 1879216538], length 1398: HTTP: POST /pathpathpath?query HTTP/1.1
IP 10.64.0.4 > 10.64.142.4: ICMP 10.250.2.2 unreachable - need to frag (mtu 1427), length 1400
IP 10.64.0.4 > 10.64.142.4: icmp
```
```
$ kubectl --context xxx-dev --namespace kube-system exec ds/cilium -c cilium-agent -- cilium config -a| grep -i -e mtu -e frag
AllowICMPFragNeeded               : true
EnableIPv4FragmentsTracking       : true
EnablePMTUDiscovery               : true
FragmentsMapEntries               : 8192
MTU                               : 0
```

The flag AllowICMPFragNeeded should allow all fragmentation packets according to commit  [7435ff3](https://github.com/cilium/cilium/commit/7435ff38f7fa732798c56b5bf7ecf7569eb4e1d0)

I also tried to add icmp policy to ingress without success.
```
- icmps:
  - fields:
    - family:
      type: 3
```

In the docs, there is cryptical [sentence](https://docs.cilium.io/en/stable/security/policy/language/#ip-cidr-based):
> If any ICMP policy is specified, layer 4 and ICMP communication will be blocked unless it’s related to a connection that is otherwise allowed by the policy.

But to my understanding if there is flag `AllowICMPFragNeeded` set true, the ICMP fragmentation request should not be blocked at all.

### Cilium Version

Client: 1.13.2 8cb94c70 2023-04-17T23:19:21+02:00 go version go1.19.8 linux/amd64
Daemon: 1.13.2 8cb94c70 2023-04-17T23:19:21+02:00 go version go1.19.8 linux/amd64

### Kernel Version

Linux aks-etnpool-17322842-vmss000002 5.15.0-1035-azure #42-Ubuntu SMP Tue Feb 28 19:41:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"b278d3784e784ae3d8e986fe641beb572e08ecc0", GitTreeState:"clean", BuildDate:"2023-05-19T00:03:21Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi, thanks for the report.


> The flag AllowICMPFragNeeded should allow all fragmentation packets according to commit [7435ff3](https://github.com/cilium/cilium/commit/7435ff38f7fa732798c56b5bf7ecf7569eb4e1d0)

Yes indeed, it looks like this should allow such traffic. It's hard to say what the datapath is doing without hubble observe output or a sysdump.

> In the docs, there is cryptical [sentence](https://docs.cilium.io/en/stable/security/policy/language/#ip-cidr-based):
> 
> > If any ICMP policy is specified, layer 4 and ICMP communication will be blocked unless it’s related to a connection that is otherwise allowed by the policy.
> 
> But to my understanding if there is flag AllowICMPFragNeeded set true, the ICMP fragmentation request should not be blocked at all.

That is my understanding as well. I believe that this quoted section of the docs is just trying to explain that any ICMP policy puts the endpoint into "default deny".

In order to further investigate this issue, the following would help a lot for anyone looking closer at the issue:
- Hubble output that demonstrates the traffic drop
- Description of all IP addresses listed in the issue, for instance Pod A (IP X) is connecting to Service IP Y and that connection is load balnced to backend Z. The ICMP packet that is dropped has source N and destination M.
- Sysdump if possible
- Example pods + policies that someone could use to reproduce the issue.
- Description of MTU configuration along the entire path (all devices you control along the path between source and destination, and ideally a full description of the path itself, especially if it goes over the internet or a limited MTU link).

One plausible mitigation could be to manually configure the MTU setting to account for the IPSec VPN headers, which could help to prevent Cilium-managed endpoints from generating packets that are too large in the first place.
