### ISSUE TITLE
[Intermittent] Cannot establish connection to local cilium instance

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2627]
@aanm has been hitting this issue with the following developer commandline:

`sudo service nfs start && ETCD_CLEAN=1 RELOAD=1 NWORKERS=1 NFS=1 K8S=1 contrib/vagrant/start.sh`

```
==> cilium-k8s-node-2: Jan 23 15:34:54 cilium-k8s-node-2 cilium-agent[2744]: time="2018-01-23T15:34:54-08:00" level=debug msg="Cannot establish connection to local cilium instance" error="Get http://%2Fvar%2Frun%2Fcilium%2Fcilium.sock/v1beta/healthz: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
```

Sometimes it shows up when running like the above, sometimes not. The messages repeat for maybe up to 90 seconds, then it recovers.

The issue appears to be `cilium-health` complaining that it is unable to reach the `cilium` API via `/var/run/cilium/cilium.sock`. It's not clear why the cilium socket is sometimes unavailable on startup like this.

**Comment by aanm** [comment]
I was able to get hit the issue again, it seems like docker doesn't respond to the `docker ps -a` request immediately. Going throughout the stack trace it seems this happens the first time we can `ws.syncWithRuntime()`
```
goroutine 1 [select, 1 minutes]:
github.com/cilium/cilium/vendor/github.com/docker/engine-api/client/transport/cancellable.Do(0x2b8f420, 0xc42007a010, 0x7f6ae8df08c8, 0xc4203835c0, 0xc42011a600, 0xc4200491a0, 0x0, 0x0)
	./go/src/github.com/cilium/cilium/vendor/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:56 +0x1d2
github.com/cilium/cilium/vendor/github.com/docker/engine-api/client.(*Client).sendClientRequest(0xc42005bbc0, 0x2b8f420, 0xc42007a010, 0x1c63e4d, 0x3, 0x1c73857, 0x10, 0xc4200491a0, 0x0, 0x0, ...)
	./go/src/github.com/cilium/cilium/vendor/github.com/docker/engine-api/client/request.go:106 +0x250
github.com/cilium/cilium/vendor/github.com/docker/engine-api/client.(*Client).sendRequest(0xc42005bbc0, 0x2b8f420, 0xc42007a010, 0x1c63e4d, 0x3, 0x1c73857, 0x10, 0xc4200491a0, 0x0, 0x0, ...)
	./go/src/github.com/cilium/cilium/vendor/github.com/docker/engine-api/client/request.go:75 +0xe9
github.com/cilium/cilium/vendor/github.com/docker/engine-api/client.(*Client).get(0xc42005bbc0, 0x2b8f420, 0xc42007a010, 0x1c73857, 0x10, 0xc4200491a0, 0x0, 0x4b5d9e, 0xc4200800a0, 0xc420874000)
	./go/src/github.com/cilium/cilium/vendor/github.com/docker/engine-api/client/request.go:33 +0xa7
github.com/cilium/cilium/vendor/github.com/docker/engine-api/client.(*Client).ContainerList(0xc42005bbc0, 0x2b8f420, 0xc42007a010, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	./go/src/github.com/cilium/cilium/vendor/github.com/docker/engine-api/client/container_list.go:47 +0x136
github.com/cilium/cilium/pkg/workloads/containerd.(*watcherState).syncWithRuntime(0xc4202e2fa0)
	./go/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher_state.go:97 +0xa2
github.com/cilium/cilium/pkg/workloads/containerd.EnableEventListener(0x8, 0x1d173b0)
	./go/src/github.com/cilium/cilium/pkg/workloads/containerd/watcher.go:67 +0xe4
main.runDaemon()
	./go/src/github.com/cilium/cilium/daemon/main.go:709 +0x14a
main.glob..func1(0x2b5ad40, 0xc4204b7130, 0x0, 0xb)
	./go/src/github.com/cilium/cilium/daemon/main.go:133 +0x30
github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute(0x2b5ad40, 0xc420086010, 0xb, 0xb, 0x2b5ad40, 0xc420086010)
	./go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:648 +0x234
github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2b5ad40, 0xc420421b90, 0x192a360, 0xc42034b888)
	./go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:735 +0x2fe
github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).Execute(0x2b5ad40, 0x0, 0xc420421700)
	./go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	./go/src/github.com/cilium/cilium/daemon/main.go:147 +0x13a
```

I think we should have a context with timeout here:
```
	cList, err := dockerClient.ContainerList(ctx.Background(), dTypes.ContainerListOptions{All: false})
	if err != nil {
		log.WithError(err).Error("Failed to retrieve the container list")
		return
	}
```
@raybejjani thoughts?

**Comment by raybejjani** [comment]
What's odd here is that by the time we make this `ContainerList` call we've already made one from `IgnoreRunningContainers` (https://github.com/cilium/cilium/blob/master/pkg/workloads/containerd/watcher.go#L349), called during `NewDaemon`, which happens before the `syncWithRuntime` within `runDaemon`. All these calls are synchronous and have no explicit timeout.
I would like to add timeouts to all the docker calls here but I'm not sure how we should then handle timeouts. For example, if we timeouts during `ContainerList` in `IgnoreRunningContainers` we can't continue to initialise the containerd watcher because we'd try to manage containers we shouldn't or we'd return and error and fail to init the agent (we can retry, of course, but then what happens when we fail the retries?).
I'll try to look through the code a little more. I don't think any of what I said is blocking but might need some reshuffling of the calls to simplify the error management. In the meantime, I will make a PR to:
- Add a timeout to this `ContainerList` in `syncWithRuntime`
- Remove the initial synchronous `syncWithRuntime` call made during `EnableEventListener` and make the goroutine that calls `syncWithRuntime` async call it before it sleeps.

Separately, do we start health and other subprograms before we finish initialising containerd and co? Would it make sense to do it only once the basic agent stuff is ready?

**Comment by raybejjani** [comment]
Righto, here is my attempt: https://github.com/cilium/cilium/pull/2654

**Comment by joestringer** [comment]
> Separately, do we start health and other subprograms before we finish initialising containerd and co? Would it make sense to do it only once the basic agent stuff is ready?

Specifically for `cilium-health`, it needs access to the cilium API and doesn't really care about the container runtime (the endpoints it generates are handled separately with network namespaces). One may argue it's a bit misleading if the cilium-health status starts showing OK before the container runtime is ready, but `cilium status` reports the status of the container runtime separately so I don't think this is an issue.

I might think that for cilium monitor if the container runtime can't be reached, it might still be nice to be able to monitor what's going on in the endpoints - for example if cilium restarts and restores the existing endpoints, but doesn't yet have access to the container runtime?
