### ISSUE TITLE
CFP: CiliumBGPPeeringPolicy Status Support

### ISSUE THREAD

**Issue by danehans** [cilium/cilium#26280]
## Cilium Feature Proposal

**Is your feature request related to a problem?**
The CiliumBGPPeeringPolicy API type exposes a range of fields for configuring BGP. Additionally, node-level BGP configuration parameters are required. BGP is not trivial and is commonly misconfigured requiring an operator to perform troubleshooting. Currently, the Cilium client provides the `bgp` option to view some BGP configurations. However, additional tools are needed to effectively manage and troubleshoot BGP Control Plane.

**Describe the feature you'd like**
Add the Status Subresource to the CiliumBGPPeeringPolicy API type. The Status Subresource can surface conditions that indicate the current state of a CiliumBGPPeeringPolicy matches the desired state.

**Comment by YutaroHayakawa** [comment]
Putting some food for thought. CiliumBGPPeeringPolicy can be applied to multiple nodes, but on the other hand, the actual status is per node. In the past, we discussed this issue and came up with the idea that having per node status by the map on status in which the key is the node name and the value is status. However, the idea was rejected because it causes a lot of unnecessary notifications for all nodes watching CiliumBGPPeeringPolicy. So, it might be better to put a status on per-node resources like `CiliumNode`.
