### ISSUE TITLE
CFP: support overriding default liveness/readiness checks in helm chart

### ISSUE THREAD

**Issue by raphaeldeem-jsq** [cilium/cilium#26282]
## Cilium Feature Proposal

**Is your feature request related to a problem?**
Yes, cilium becomes unhealthy on our k8s cluster and the health checks in the cilium pods do not detect it.

**Describe the feature you'd like**
Ability to override liveness/readiness probes in cilium helm chart with custom checks.

**Comment by joestringer** [comment]
Hi @raphaeldeem-jsq , can you explain a bit more about the symptoms of unhealthiness in this scenario?

While allowing custom checks could be a potential solution here, I think it would be more interesting to understand exactly what the failure conditions are here and get those checks into the core of Cilium so that every Cilium user can benefit from better detection of those symptoms/conditions. That is unless there's something very special about your environment that causes these failures that would not be applicable to other Cilium users.

**Comment by ti-mo** [comment]
This reads like XY problem. Why does Cilium become unhealthy?
