### ISSUE TITLE
[Questions] Why not support IPV6 fragment?

### ISSUE THREAD

**Issue by nejisama** [cilium/cilium#26292]
I found function `bpf/lib/ipv6.h: ipv6_hdrlen_offset` returns DROP_FRAG_NOSUPPORT
Why cilium not support fragment in ipv6? 
I think we can support ipv6 fragment like ipv4 with fragment tracking?

**Comment by M4t7e** [comment]
I think IPv6 fragmentation is not recommended in general because it adds complexity, reduces efficiency, increases latency, and can cause packet loss. IPv6 routers are not allowed to fragment packets in transit, putting the burden on the source host. Fragmentation also poses security risks and is generally avoided in favor of Path MTU Discovery for optimal packet transmission. Also for IPv4 you normally want to avoid that, because it leads in practice to various problems.
