### ISSUE TITLE
Cannot import cilium package

### ISSUE THREAD

**Issue by yuedongze** [cilium/cilium#26334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I wanted to use a go package from Cilium, but it keeps complaining about a dependency on metallb.
```
go get github.com/cilium/cilium/pkg/bgp/config@v1.13.4
github.com/cilium/cilium/pkg/bgp/config imports
        go.universe.tf/metallb/pkg/config: cannot find module providing package go.universe.tf/metallb/pkg/config
```

### Cilium Version

1.13.4

### Kernel Version

Linux test 5.10.0-19-cloud-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

### Kubernetes Version

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Broadly speaking, Cilium's `pkg/` directory is considered unstable internal API and is only published due to historic code structuring. If you're able to figure out how to use it, then you are welcome to do so, but those packages and APIs are subject to change in any subsequent release for any reason. If you're able to figure out the solution to the import issue, then you might consider posting any such solution here on the issue.

**Comment by rolinh** [comment]
@yuedongze Unfortunately, Cilium has a number of [replace directives](https://github.com/cilium/cilium/blob/1.13.4/go.mod#L247-L256) that must be replicated to any project's `go.mod` that imports Cilium due to how Go tooling works.
