### ISSUE TITLE
CI: ClusterMesh (ci-multicluster) connectivity test failed: timeout reached waiting lookup for localhost from pod cilium-test/client2

### ISSUE THREAD

**Issue by gandro** [cilium/cilium#26513]
## CI failure

Error:
```
 ⌛ [kind-cluster1-5390656331] Waiting for pod cilium-test/client2-76f4d7c5bc-ssxp7 to reach DNS server on cilium-test/echo-other-node-545c9b778b-btrlh pod...
connectivity test failed: timeout reached waiting lookup for localhost from pod cilium-test/client2-76f4d7c5bc-ssxp7 to server on pod cilium-test/echo-other-node-545c9b778b-btrlh to succeed (last error: context deadline exceeded)
Error: Process completed with exit code 1.
```

Observed in two separate PRs [here](https://github.com/cilium/cilium/actions/runs/5391374377/jobs/9788172243) and [here](https://github.com/cilium/cilium/actions/runs/5390656331/jobs/9786352042)

Looking at the sysdump, I don't see any obvious errors with that pod and no hubble drops either.

**Comment by marseel** [comment]
I think we are missing hubble logs - I took a look at [this](https://github.com/cilium/cilium/actions/runs/5390656331/jobs/9786352042) 
and `hubble-flows-cilium-r6qnp-20230627-135702.json` has the first log with timestamp `2023-06-27T13:56:34.982006946Z` which is already after the test was run: `13:56:28 GMT`

**Comment by marseel** [comment]
I took a look at multiple runs, and it seems that the only thing in common is kvstoremesh. 
First failed run that I found with this error: https://github.com/cilium/cilium/actions/runs/5290437383/jobs/9574599699
@giorio94  could you take a look, please?

**Comment by giorio94** [comment]
I've checked a few runs, including the ones initially mentioned by @gandro and [another from a scheduled run](https://github.com/cilium/cilium/actions/runs/5360483511/jobs/9725417855), and all flakes seem to be caused by unlucky timing. 

The failure of the run mentioned by @marseel, instead, was fixed by https://github.com/cilium/cilium/pull/26363.

Taking the scheduled run as an example.

The check was performed between :24 and :44:
```
21:05:24 GMT ⌛ [kind-cluster1-5360483511] Waiting for pod cilium-test/client2-76f4d7c5bc-h4dxl to reach DNS server on cilium-test/echo-other-node-545c9b778b-4dxsv pod...
21:05:44 GMT connectivity test failed: timeout reached waiting lookup for localhost from pod cilium-test/client2-76f4d7c5bc-h4dxl to server on pod cilium-test/echo-other-node-545c9b778b-4dxsv to succeed (last error: context deadline exceeded)
```

The agent on the same node of the client pod detected the remote cluster configuration and connected to the remote cluster at :34 (the configuration is mounted from a configmap, hence it can take some time before the kubelet propagates it):
```
2023-06-23T21:05:34.871376407Z level=debug msg="Remote cluster configuration added"
2023-06-23T21:05:34.871391164Z level=info msg="New remote cluster configuration"
```

The nslookup client attempted one lookup at :39 (which failed), and one at :44 (which I guess succeeded, but the timeout kicked in at the same time):
```
Jun 23 21:05:39.721: cilium-test/client2-76f4d7c5bc-h4dxl:39752 (ID:84980) <> cilium-test/echo-other-node-545c9b778b-4dxsv:53 (ID:16747539) from-endpoint FORWARDED (UDP)
Jun 23 21:05:39.721: cilium-test/client2-76f4d7c5bc-h4dxl:39752 (ID:84980) -> cilium-test/echo-other-node-545c9b778b-4dxsv:53 (ID:16747539) to-stack FORWARDED (UDP)
Jun 23 21:05:44.718: cilium-test/client2-76f4d7c5bc-h4dxl:39752 (ID:84980) <> cilium-test/echo-other-node-545c9b778b-4dxsv:53 (ID:16747539) from-endpoint FORWARDED (UDP)
Jun 23 21:05:44.718: cilium-test/client2-76f4d7c5bc-h4dxl:39752 (ID:84980) -> cilium-test/echo-other-node-545c9b778b-4dxsv:53 (ID:16747539) to-stack FORWARDED (UDP)
Jun 23 21:05:44.719: cilium-test/echo-other-node-545c9b778b-4dxsv:53 (world) <> cilium-test/client2-76f4d7c5bc-h4dxl:39752 (ID:84980) from-host FORWARDED (UDP)
Jun 23 21:05:44.719: cilium-test/client2-76f4d7c5bc-h4dxl:39752 (ID:84980) <- cilium-test/echo-other-node-545c9b778b-4dxsv:53 (ID:16747539) to-endpoint FORWARDED (UDP)
Jun 23 21:05:44.720: cilium-test/client2-76f4d7c5bc-h4dxl:52667 (ID:84980) <> cilium-test/echo-other-node-545c9b778b-4dxsv:53 (ID:16747539) from-endpoint FORWARDED (UDP)
Jun 23 21:05:44.720: cilium-test/client2-76f4d7c5bc-h4dxl:52667 (ID:84980) -> cilium-test/echo-other-node-545c9b778b-4dxsv:53 (ID:16747539) to-stack FORWARDED (UDP)
Jun 23 21:05:44.720: cilium-test/echo-other-node-545c9b778b-4dxsv:53 (world) <> cilium-test/client2-76f4d7c5bc-h4dxl:52667 (ID:84980) from-host FORWARDED (UDP)
Jun 23 21:05:44.720: cilium-test/client2-76f4d7c5bc-h4dxl:52667 (ID:84980) <- cilium-test/echo-other-node-545c9b778b-4dxsv:53 (ID:16747539) to-endpoint FORWARDED (UDP)
```

Empirically, it seems that nslookup performs three attempts with a 5 seconds delay between each, and then gives up.

https://github.com/cilium/cilium-cli/pull/1758 raised the timeout of the above check to 30 seconds (although has not yet been released), which should help a bit in this situation. A separate possible improvement could be to make `cilium clustermesh status` wait until all agents have successfully connected to the expected clusters.
