### ISSUE TITLE
L2 announcements stop working after a time

### ISSUE THREAD

**Issue by maxpain** [cilium/cilium#26586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I created LoadBalancer service with the new L2 announcement feature and could access to it from my local network.
After a some time this service stopped working.

Cilium agent doesn't answer ARP requests for the IP of the service.
```
12:19:04.985743 eth0  B   ARP, Request who-has 10.0.0.225 tell 10.0.0.135, length 46
```

### Cilium Version

Client: 1.14.0-rc.0 08239f59 2023-06-28T15:18:32-07:00 go version go1.20.5 linux/amd64
Daemon: 1.14.0-rc.0 08239f59 2023-06-28T15:18:32-07:00 go version go1.20.5 linux/amd64

### Kernel Version

Linux talos-xa1-p9c 6.1.35-talos #1 SMP PREEMPT_DYNAMIC Wed Jun 28 13:58:51 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.27.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YutaroHayakawa** [comment]
Could you provide us a sysdump? Otherwise, it's hard to know how we can reproduce this issue.

**Comment by YutaroHayakawa** [comment]
cc: @dylandreimerink

**Comment by dylandreimerink** [comment]
That sounds quite serious. I am not aware of any known issue that would cause this. Very keen on a sysdump :pray:

**Comment by maxpain** [comment]
@dylandreimerink @YutaroHayakawa 
[cilium-sysdump-20230704-200609.zip](https://github.com/cilium/cilium/files/11951348/cilium-sysdump-20230704-200609.zip)

**Comment by maxpain** [comment]
@dylandreimerink @YutaroHayakawa can I send it privately?

**Comment by dylandreimerink** [comment]
I believe you uploaded it in a now deleted message, but I am still able to access it via the mail notification it sent out initially, so I hope it did not contain very sensitive info. :fearful: 

I did take a look. At the time of capturing the sysdump there were at least some IPs we are responding to:
```
{
  "l2-announce-entries": [
    {"IP":"10.0.0.240","NetworkInterface":"eth0","Origins":[{"Name":"{redacted}","Namespace":"media"}],"Deleted":false,"Revision":46},
    {"IP":"10.0.0.241","NetworkInterface":"eth0","Origins":[{"Name":"{redacted}","Namespace":"media"}],"Deleted":false,"Revision":41},
    {"IP":"10.0.0.247","NetworkInterface":"eth0","Origins":[{"Name":"{redacted}","Namespace":"{redacted}"}],"Deleted":false,"Revision":40},
    {"IP":"10.0.0.254","NetworkInterface":"eth0","Origins":[{"Name":"{redacted}","Namespace":"media"}],"Deleted":false,"Revision":32}
  ]
}
```

The revision numbers are very high, indicating a lot of churn in the list. 

The agent log is full of rate limit messages:
```
2023-07-04T14:59:51.959400310Z level=info msg="Waited for 1.395439596s due to client-side throttling, not priority and fairness, request: GET:https://127.0.0.1:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cilium-l2announce-kube-system-hubble-peer" subsys=klog
2023-07-04T15:00:12.159409007Z level=info msg="Waited for 1.398748976s due to client-side throttling, not priority and fairness, request: PUT:https://127.0.0.1:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cilium-l2announce-default-kubernetes" subsys=klog
2023-07-04T15:00:22.160304629Z level=info msg="Waited for 1.191052918s due to client-side throttling, not priority and fairness, request: GET:https://127.0.0.1:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cilium-l2announce-kube-system-hubble-ui" subsys=klog
2023-07-04T15:00:42.360058569Z level=info msg="Waited for 1.399530216s due to client-side throttling, not priority and fairness, request: PUT:https://127.0.0.1:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cilium-l2announce-kube-system-kube-dns" subsys=klog
```

So what is likely happening is that the increased API traffic for the leases is triggering the default QPS limit of 5 requests a second. The throttling causes the agent to not update the lease quick enough, so it stops announcing, assuming another node is taking over. The default burst limit is 10 QPS which could explain why its initially not an issue.

I did not account for the client rate limit during design and development of the feature :disappointed:.

For now I see two possible workarounds:
1. Increase the lease duration and renew deadline to decrease the amount of API calls needed to keep the lease. This can be done via the `l2announcements.leaseDuration` and `l2announcements.leaseRenewDeadline` helm values.
2. Increase the client rate limit. There currently is no Helm value for this, but it should be doable by setting the `k8s-client-qps` option in the ConfigMap and restarting the agent.

**Comment by dylandreimerink** [comment]
We unfortunately do not have time to come up with a permanent solution before the v1.14 release. So what I have done is open a PR to add helm values for the client rate limit so they can be configured via helm. The PR also adds warnings to the docs about setting the rate limits and a section on picking good values.

Since this is all we will be able to do before v1.14, I am removing the release-blocker label (the PR has one). But I would like this keep this issue open to track progress on the more permanent fix.

**Comment by marseel** [comment]
Adding to Dylan's https://github.com/cilium/cilium/issues/26586#issuecomment-1620641960 , increasing `l2announcements.leaseRetryPeriod` will help in your case. Increasing only `leaseDuration` and `leaseRenewDeadline` might not be sufficient -  https://pkg.go.dev/k8s.io/client-go/tools/leaderelection package does not describe different parameters well, but most significant in terms of the number of calls issued is actually `RetryPeriod` rather than `leaseDuration/leaseRenewDeadline`

**Comment by davehs30** [comment]
I am seeing this type of event behavior with 1.14.0 L2 load balancer..  Have the following settings:
l2announcements.leaseDuration=300s
l2announcements.leaseRenewDeadline=60s
l2announcements.leaseRetryPeriod=10s

two l2 announcement leases at this time.  both are showing the same.  a arp/mac address is learned on the local segment for awhile but then times out and is not re-learned.

**Comment by drawdy** [comment]
same problem. not work after a while.

**Comment by sbocahu** [comment]
So far, we did not experience missing leases after having configure high values for base qps/burst qps and leaseduration/renew.
however, the "Waited for 1s due to client-side throttling, not priority and fairness" log line is regularly found in one of nodes cilium agent. A few days ago the log volume grew a lot (15/20 per hour), which is very surprising as the number of services is low (35 on this node) and qps high (150; burst: 500).
lease config:  leaseRetryPeriod: 3s / leaseDuration: 30s / leaseRenewDeadline: 10s

This is confusing

**Comment by rouke-broersma** [comment]
> Same question, not work after a while.
> 
> Is it possible not to create lease for not LB services ? There are too many leases.

This is tracked here: https://github.com/cilium/cilium/issues/28752 and a patch has been submitted

**Comment by withinboredom** [comment]
I'm still seeing this. There is now a job running on the cluster that does an arping every few seconds and if it goes down, we restart a random cilium pod. The leases simply expire and never get recreated.

**Comment by rouke-broersma** [comment]
I still have this issue even though I've limited the announcement to only 2 LB services using the namespace filter and increased the qps significantly beyond the default.

**Comment by zimmertr** [comment]
I also am seeing this. I've been fixing it temporarily by deleting the impacted Kubernetes LoadBalancer service but that is becoming annoying for homelab use. Are people not experiencing this in prod?

**Comment by rouke-broersma** [comment]
> Are people not experiencing this in prod?
L2announce is experimental so I would expect almost no one uses this in prod. Most probably just use bgp in prod which is not experimental. I switched to bgp at home due to this issue as well.

**Comment by akarneliuk** [comment]
Same here, after about 30-40 mins after the cilium pod starts (or after I create a new service), it stops responding to ARP. If I restart cilium pod, it operates for some time and then stops again.

**Comment by gelato** [comment]
Also experiencing this behavior, Cilium 1.14.5

**Comment by marseel** [comment]
If you are able to try 1.15.0-pre.3 version, it contains this fix that limits amount of leases created (so also decreases qps used): https://github.com/cilium/cilium/pull/29446

Except for increasing qps/burst I would recommend increasing `l2announcements.leaseRetryPeriod` per this https://github.com/cilium/cilium/issues/26586#issuecomment-1628615612

> Do other pods watch these leases even though they aren't the "master"?

Unfortunately, that's not how leases work :cry: If they were just watching leases everything would be fine. Nodes that are not leaders are performing GET operation on lease every `leaseRetryPeriod`, which burns qps limit quite significantly on all nodes and this is the main root cause of the issues.

**Comment by akarneliuk** [comment]
Put QPS/BURST to 50/100 and it started working for me, thanks.

**Comment by withinboredom** [comment]
I've noticed this requires near weekly tuning. No matter what numbers I set, eventually, a lease would be lost. Usually, within a week or two. I've had to switch back to metallb.

**Comment by githubcdr** [comment]
Same for me, randomly having to restart Cilium pods to get it working again, even with the 50/100 setting. This is with 1.15rc1 release.

**Comment by dylandreimerink** [comment]
I think it its fairly clear that this problem is quite consistently effecting a number of users. Keeping an open mind the causes can be:
* Client rate limiting delaying lease related updates to the points leases are lost (my primary suspect)
* A bug in the `k8s.io/client-go/tools/leaderelection` library
* A bug in L2 announcements

It would be great if users with this issue could check the agent logs to see if the `Waited for ...s due to client-side throttling, not priority and fairness` messages appear when this happens. Or even better record and share a sysdump which should include that info as well.

With regards to this happening even after changing the QPS settings, I believe this requires very specific tuning. The rate is shared with all other agent features on that instance, so not only do the lease settings and the amount of leases play a role, any uptick in other API traffic might also variably take up part of the limit. Granted this is speculation, but I suspect situations like this can explain the delay in the failure.

In any case, the current situation isn't workable. But a fix doesn't seem straightforward, so I would like to get some discussion/feedback going around these possible solutions:

* Change some of the k8s client plumbing internally to remove the rate limit for the lease API calls specifically. The downside to this is that we might just shift the problem to the API server and overload it in some way (what the rate limit attempts to avoid).
* Ditch the k8s leases and do leader election via the KVStore instread. The downside being that this makes the Cilium deployment more complicated, which isn't desirable for the smaller setups this feature was intended for.
* Ditch the k8s leases and do leader election via some sort of agent-to-agent raft protocol. The downside being that this would take the longest to develop, would be major maintenance burden due to it being only used for this feature, and require additional ports to be opened in our firewall scheme.

No fix that I can come up with has zero downsides, I am open for ideas on alternative fixes and feedback on which direction sounds least bad.

**Comment by withinboredom** [comment]
It's not due to throttling, but due to just randomly losing the lease and nothing anywhere ever checking for the lease to exist. There's no self-healing; it assumes that if it is the leader, it will never fail to not be the leader.

At least that was my case; there was nothing in the logs to hint at what was going on. Maybe someone else has fresher logs that shows something different 🤞

**Comment by dylandreimerink** [comment]
@withinboredom I think you are completely right :facepalm:. The `RunOrDie` method exits when the context is canceled but also when it somehow loses its lease while the agent is still running. I have no clue how that made it so far without notice. I think https://github.com/cilium/cilium/pull/30340 should be the fix.

**Comment by jokajak** [comment]
I appreciate the team effort that went into resolving this ticket. Thank you to @withinboredom for providing the illuminating fact that enabled @dylandreimerink to find and fix #30340 .

I know this ticket had been opened for many months with lots of different ideas and workarounds proposed and used. It's the consistent review of the ticket and interest in the ticket that I really appreciate. It would have been too easy to get frustrated and upset leading to a lack of cooperation so I am thankful for the wonderful contributors to this product.

**Comment by BloodyIron** [comment]
So I did some additional testing that's relevant to my problem.

1. I'm using L2announce for a single IP via ARP
2. I have NGINX Ingress and librespeed pods as my test services, the LB IP is used by the Service for NGINX Ingress
3. I am using Cilium v1.15.1 which was installed on my behalf by RKE2 and I am using Rancher to help create/manage the k8s cluster
4. I timed each scenario and had the librespeed page up being refreshed every 5 minutes

First scenario:
1. NGINX Ingress and librespeed pods are on the same k8s node as the node holding the ARP IP
2. The ARP IP did notg change nodes at all so far as I can tell.
3. The librespeed page did not break even after 2h 15min, so I stopped and went to the Second scenario


Second scenario:
1. NGINX Ingress and librespeed pods are on a DIFFERENT k8s node from the node holding the ARP IP
2. The ARP IP did notg change nodes at all so far as I can tell.
3. The librespeed page broke in under 5 minutes (I did not measure precisely as I was running this test passively while doing other things.)

So I have a hunch this is related to whatever handles the traffic with kube-proxy disabled (which I have as true).

**Comment by PaulRitzkat0110** [comment]
For the second scenario, can you try setting
```
loadBalancer:
  bpfSocketLBHostnsOnly: true
socketLB:
  hostNamespaceOnly: true
```
I believe restricting the LB to the host namespace fixed this issue for me (also rke2 with ingress-nginx).

**Comment by BloodyIron** [comment]
> For the second scenario, can you try setting
> 
> ```
> loadBalancer:
>   bpfSocketLBHostnsOnly: true
> socketLB:
>   hostNamespaceOnly: true
> ```
> 
> I believe restricting the LB to the host namespace fixed this issue for me (also rke2 with ingress-nginx).

Oh I tried the hostNamespaceOnly thing, but I may have missed the bpfSocketLBHostnsOnly thing... I'll retry with those, thanks! :D Yay! Oh I'm excited this might work wheee :DDD let's find out...

**Comment by BloodyIron** [comment]
Okay so turned-on the test nodes (turned the cluster off when not testing). Cilium initially already was broken on initial init (shhh not redundant).

So about to start the test, and to set it up had to restart all cilium pods. Kinda dumb, hopefully I can find out why that is... preferably some way Cilium can fix itself in times like that... but may not necessarily be the test I'm about to do. Just wanted to add it to this topic for discussion if anyone has any ideas on that! I did not have this kind of init weirdness when using MetalLB btw (but also could not find a way to get SourceIP with that either).

About to test!

**Comment by BloodyIron** [comment]
> For the second scenario, can you try setting
> 
> ```
> loadBalancer:
>   bpfSocketLBHostnsOnly: true
> socketLB:
>   hostNamespaceOnly: true
> ```
> 
> I believe restricting the LB to the host namespace fixed this issue for me (also rke2 with ingress-nginx).

Yeah it broke again after about 1hr duration (not sure on exact timing measurement). So that did not seem to correct the matter :(

Any other ideas? Ugh probably going to switch away from Cilium at this point with how fragile it seems to be...

**Comment by BloodyIron** [comment]
@PaulRitzkat0110 I'm confused too there bud! :((((

**Comment by jstewart612** [comment]
If anyone else shows up here after a while... really pay attention to the prerequisites of the l2 documentation.  I missed the one sentence about externalTrafficPolicy having to be "Cluster" and it just cost me two hours of my life!

**Comment by eliottness** [comment]
FYI this is still not working on cilium 1.19.1 on k3s for me. No error log at all, no rate limit issue, the lease is held properly (hell I tried with a one node cluster). The only clue here is that `bpfSocketLBHostnsOnly` seems to be making things happen after an hour for me instead of after a few seconds.
