### ISSUE TITLE
CFP: Custom networking in AWS EKS

### ISSUE THREAD

**Issue by littlejo** [cilium/cilium#26649]
## Cilium Feature Proposal
        
**Is your feature request related to a problem?**

If your vpc cidr is small, it could be interesting to have this feature.

**Describe the feature you'd like**

You need to add cidr 100.64.0.0/16 from VPC + subnets relative to this cidr
Pods' eni use this cidr range instead of the small cidr.

It works with VPC CNI.

I tested to use cilium selecting the good subnets. I have this error when i create a pod:
`plugin type="cilium-cni" name="cilium" failed (add): unable to allocate IP via local cilium agent: [POST /ipam][502] postIpamFailure  No more IPs available`

From cilium-operator, i have:
`level=warning msg="Instance not found! Please delete corresponding ciliumnode if instance has already been deleted." instanceID=i-0108aa949140cae90 name=ip-10-0-102-168.ec2.internal subsys=ipam`

More info here:
https://aws.github.io/aws-eks-best-practices/networking/custom-networking/

**Comment by gandro** [comment]
Thanks for the report! If I understand the linked documentation correctly, this issue is about allocating IPs from a secondary VPC CIDR in case the initial one is exhausted? This is already supported by Cilium, if you use subnet tag filters that match a subnet in a secondary VPC CIDR, Cilium will allocate pod IPs from that secondary VPC CIDR instead.

It's not well documented at the moment, but there are some docs on how to use a different subnets here: https://docs.cilium.io/en/stable/network/concepts/ipam/eni/#configure-cilium-with-subnet-tags-filter

**Comment by littlejo** [comment]
> Thanks for the report! If I understand the linked documentation correctly, this issue is about allocating IPs from a secondary VPC CIDR in case the initial one is exhausted? 

Yes but the node IPs are always on the primary VPC CIDR and pods are always on the secondary CIDR which is in CG-NAT space (100.64.0.0/10 or 198.19.0.0/16).

![aws custom networking](https://aws.github.io/aws-eks-best-practices/networking/custom-networking/image.png)

In VPC CNI, you can do it like that:

https://www.eksworkshop.com/docs/networking/custom-networking/vpc

**Comment by gandro** [comment]
> Yes but the node IPs are always on the primary VPC CIDR and pods are always on the secondary CIDR which is in CG-NAT space (100.64.0.0/10 or 198.19.0.0/16).

Yes, this should be supported. The node IPs are managed by youself, but you can allocate pod CIDR IPs by setting a custom subnet tag filter

**Comment by christarazi** [comment]
Is this resolved?
