### ISSUE TITLE
Running the generate-k8s-api Target Results in Unexpected Deepcopy Funcs

### ISSUE THREAD

**Issue by danehans** [cilium/cilium#26877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

`pkg/maps/tunnel/zz_generated.deepcopy.go` was created from `$ make generate-k8s-api`. This is due to the `TunnelIP` struct containing a controller-runtime marker to generate the deepcopy funcs.

### Cilium Version

main branch

### Kernel Version

N/A

### Kubernetes Version

N/A

### Sysdump

N/A

### Relevant log output

```shell
N/A
```

### Anything else?

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ldelossa** [comment]
@danehans Why is this an issue?  And why now, looks like the commit which added deep copy was done 6 months ago?

**Comment by giorio94** [comment]
Hi @danehans,

The automatic generation of the deepcopy methods for that type has been overlooked for some time, as it was not checked by the CI. It should have been fixed by [this PR](https://github.com/cilium/cilium/pull/26790), though, and now running `make generate-k8s-api` should not lead to unexpected changes anymore. Could you please verify on a newly rebased branch if you still experience issues?

**Comment by danehans** [comment]
@giorio94 thanks for the review. Let me wrap-up the PR I'm working on and I'll retest.
