### ISSUE TITLE
a question about CIDR policies when `reserved:world` and cilium node CIDR ranges overlap

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium#26881]
hello 👋 

i have a 4-node setup in https://github.com/cilium/cilium-cli/pull/1749 where only 2 of the 4 nodes have cilium 1.13.4 installed:

- cilium is installed: `172.18.0.2` and `172.18.0.5`
- cilium is not installed: `172.18.0.3` and `172.18.0.4`

and then i run `cilium connectivity test` with the following flags:
```
            --external-cidr 172.18.0.0/16 \
            --external-ip  172.18.0.4 \
            --external-other-ip  172.18.0.3
```
which generates a policy rule like this:
```
  egress:
  - toCIDRSet:
    - cidr: 172.18.0.0/16
      except:
      - 172.18.0.3/32
```
all the CIDR tests pass, but then `cilium connectivity test` fails because cilium-agent logs these errors:
```
2023-07-17T23:12:17.287809793Z level=error msg="Unable to find identity of previously used CIDR 172.18.0.4/32" subsys=ipcache
2023-07-17T23:14:04.223730751Z level=error msg="Unable to find identity of previously used CIDR 172.18.0.3/32" subsys=ipcache
```

2 questions:

- are these error messages safe to ignore?
- more generally, does cilium support CIDR rules when the CIDR contains cilium node IPs?

another data point, i ran the same test using cilium v1.14.0-rc.0, and i didn't get these error messages.

**Comment by joestringer** [comment]
Currently Cilium does not support applying CIDR policies to nodes within the cluster.

Given that Cilium doesn't support this feature today, I believe that the "error" is really just a "warning" that there is a policy that is not being fully applied. Strictly speaking, it is actually the clean up of the policy that seems to be triggering the warning.

I would be okay with lowering this log to warning. In _some situation_ it could be possible for this log message to be signalling an inability to properly implement the policy. That could have high repercussions. However, so far it seems that the log message is signalling more of a false positive for that sort of error case.

I suspect that some of the ongoing work to better refactor ipcache in 1.14 and beyond is starting to address the root cause of these extraneous messages, hence why you report that it does not show up in v1.14.0-rc.0. I don't expect this to come up for this particular scenario, even though we still do not support applying CIDR policies to nodes in 1.14.x.

**Comment by joestringer** [comment]
Quick update for those interested: it is now possible to match nodes with CIDR policy by following this section of the documentation: https://docs.cilium.io/en/stable/security/policy/language/#selecting-nodes-with-cidr-ipblock
