### ISSUE TITLE
Test IPAM Multi-pool getting started guide with 1.14.0-rc.1

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#26932]
```[tasklist]
### Tasks
- [x] Install Cilium 1.14.0-rc.1
- [x] Test [IPAM Multi-pool getting started guide](https://docs.cilium.io/en/v1.14/network/kubernetes/ipam-multi-pool/#gsg-ipam-crd-multi-pool)
```

**Comment by danehans** [comment]
xref: https://github.com/cilium/cilium/issues/26966

**Comment by joestringer** [comment]
@danehans :+1: based on your PR, it looks like the testing was otherwise successful? Do you think we should check off the tasks and close out this item now? We can follow up on the PR separately and even in worst case ship the docs post-release given that we generate the 1.14 branch docs from the 1.14 branch.
