### ISSUE TITLE
CFP: How to run a program, it does not load connect4, it is used to test the connectivity of the ip of loadbalance. If let it not belong to /run/cilium/cgroupv2

### ISSUE THREAD

**Issue by llhhbc** [cilium/cilium#27027]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature request for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your feature request related to a problem?**
Because all programs share the kernel, all requests to access VIP will convert the destination address into the real destination IP in the connect stage, which is not conducive to checking the availability of VIP services. The programs mounted by cilium are unified under /run/cilium/cgroupv2, whether it is possible to create a separate cgroupv2, this rule does not apply

If so, please describe the problem

**Describe the feature you'd like**

Include any specific requirements you need

**(Optional) Describe your proposed solution**

Please complete this section if you have ideas / suggestions on how to implement the feature. We strongly recommend discussing your approach with Cilium committers before spending lots of time implementing a change. 

For longer proposals, you are welcome to link to an external doc (e.g. a Google doc). We have a [Cilium Feature Proposal template](https://docs.google.com/document/d/1vtE82JExQHw8_-pX2Uhq5acN1BMPxNlS6cMQUezRTWg/edit) to help you structure your proposal - if you would like to use it, please make a copy and ensure it's publicly visible, and then add the link here.

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

**Comment by youngnick** [comment]
Thanks for logging this issue @llhhbc. I'm finding it a bit hard to understand what the ask is, would you be able to make the following changes please:
- Remove template text from your issue so that the description only has relevant information
- Could you please rephrase your explanation?. It seems like you want something changed to do with external health checking of VIP services, but aside from that I can't quite make out what the problem you want to solve is.

**Comment by llhhbc** [comment]
Because all programs share the kernel, all requests to access VIP will convert the destination address into the real destination IP in the connect stage, which is not conducive to checking the availability of VIP services. The programs mounted by cilium are unified under /run/cilium/cgroupv2, whether it is possible to create a separate cgroupv2, this rule does not apply

Here is my example:
My three node is 1.2.3.1, 1.2.3.2, 1.2.3.3; and vip is 1.2.3.4; and I have install cilium with kube-proxy replace strict.

Think about that I have a loadbalance svc with external ip: 1.2.3.4, and the dest pod ip is  10.10.10.10, and my vip (1.2.3.4) is annoanced by metallb, that is vip up at node 1.2.3.3. 

I want to test vip 1.2.3.4 + 80 if work fine, but I can't test no any of the three node. Because cilium has register cgroup/connect4 in /run/cilium/cgroupv2,  every request of 1.2.3.4:80, will change dest ip to 10.10.10.10, even if the vip is annoanced at node 1.2.3.3

So, I want to known, If I don't need add a external node of ip 1.2.3.5, that without install cilium, for test vip 1.2.3.4:80 if work? Because client is out of cluster, and I can't deploy some check agent on it.

**Comment by youngnick** [comment]
Thanks for explaining more @llhhbc.

It sounds like you want to check the availability of a loadbalanced service, and you want the request that arrives at the backend pod to show the address of the _load balancer_ as the destination rather than the destination pod IP?

I'm sorry but I still don't understand what you're trying to test with that process. Isn't it usual that an external test is testing "Can external users see the app?", not "Can my backend service see details of the loadbalancer that's handling the traffic?".

If you're looking to test if the 1.2.3.4:80 VIP is working, then making external requests that get rerouted to a workload pod is implicitly testing that, because if the 1.2.3.4:80 VIP was _not_ working, then the requests would fail (because the pod is not routable outside the cluster).

Would you be able to explain more about what you are trying to achieve?

**Comment by llhhbc** [comment]
I want to check if vip is exposed with exception. Because the test in the cluster, the VIP will be converted into the real destination IP, and the path through which the traffic passes is different from the path through which the access to the VIP outside the cluster takes place.

**Comment by youngnick** [comment]
@llhhbc and I talked on Slack (https://cilium.slack.com/archives/C1MATJ5U5/p1690347863162229) about this, and determined that what they were looking for here was a way to remove the specific eBPF program that is rewriting traffic for the VIP.

I said that is not possible, so they're going to investigate other options.
