### ISSUE TITLE
bugtool: add `cilium status --all-controllers`

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2749]
Show status of all controllers in bugtool.

**Comment by joestringer** [comment]
This should be already handled through `cilium debuginfo`:

https://github.com/cilium/cilium/blob/afd1d5b9cddb074f1412bb226cbf8a82a74b0e08/bugtool/cmd/configuration.go#L207

https://github.com/cilium/cilium/blob/afd1d5b9cddb074f1412bb226cbf8a82a74b0e08/cilium/cmd/debuginfo.go#L72

https://github.com/cilium/cilium/blob/afd1d5b9cddb074f1412bb226cbf8a82a74b0e08/pkg/client/client.go#L146

However, this might not be that obvious since we also directly dump the cilium status via `cilium status`. I've got a local patch to add a `--verbose` option that should print everything known from the `cilium status` command, so I'll fold in a fix for this as well.
