### ISSUE TITLE
Optimize optiopay/kafka parser

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2770]
There is a lot of optimisation potential in the Kafka parser to enhance throughput and reduce latency
- [ ] Avoid multiple copies of the data
- [ ] Parse stream based instead of copying the entire request first
- [ ] Have a feedback mechanism to start parsing slower on write congestion

**Comment by jrfastab** [comment]
Related most likely, for BPF we need to do exact matches using a radix-tree instead of the for-loop over rules I saw in kafka logic. The idea is to do initial parse over packet into fields and then for exact match each 'letter' in a topic is node in the radix tree and if the topic string ends at a leaf node in the radix tree the topic is allowed otherwise it is a _not_ allowed. Same applies to other string matches that are exact match. The nice performance result is O(n) time where 'n' is length of strings vs O(mn) time where m is number of topics. But really the motivation is avoiding loops in BPF. Perhaps not noticeable unless we get many topics though.

Would be nice to port the same logic into kafka userland just for consolidation of code paths and perf benefit if we see many topics. 

I'll put together some design docs here shortly.
