### ISSUE TITLE
datapath: Extend METRICS_MAP to store prog ID / ifindex / LOC upon DROP_MISSED_TAIL_CALL

### ISSUE THREAD

**Issue by brb** [cilium/cilium#27748]
Currently, we get very little information when `DROP_MISSED_TAIL_CALL` happens - only the counter value is incremented (e.g., https://github.com/cilium/cilium/issues/26739).

To fix that, we could extend the `METRICS_MAP` to store prog ID, ifindex, LOC in the metrics counter which could drastically help with troubleshooting. The meta info could be rendered into prometheus metric label. `DROP_MISSED_TAIL_CALL` should be rare events, so the high cardinality of such a metric shouldn't be an issue.

**Comment by julianwiedmann** [comment]
In addition, we could also propagate it as `ext_err` in the drop notification. Not sure if that makes it all the way to hubble today.

**Comment by brb** [comment]
> ext_err in the drop notification

We do that today. However, in the case of `DROP_MISSED_TAIL_CALL`, the drop notification is not sent to the perf ringbuffer, as it's done in a separate tail call.

**Comment by julianwiedmann** [comment]
> > ext_err in the drop notification
> 
> We do that today.

I meant setting the `ext_err` to the actual missed tail-call index (ie returning with `DROP_MISSED_TAIL_CALL` and `ext_err := CILIUM_CALL_IPV4_NODEPORT_DSR`).

> However, in the case of `DROP_MISSED_TAIL_CALL`, the drop notification is not sent to the perf ringbuffer, as it's done in a separate tail call.

You mean in case there's a fundamental problem with tail-calls, then the drop-notification also wouldn't make it out? Yep, true. Is that the typical problem? I would have figured we can also have scenarios where some tail-call is just not wired up correctly, but `CILIUM_CALL_DROP_NOTIFY` still works.

**Comment by brb** [comment]
> then the drop-notification also wouldn't make it out

Yep, e.g., when there is a bug in our loader.

**Comment by brb** [comment]
> @brb wdyt?

SGTM

**Comment by ti-mo** [comment]
Some more data after investigating a few of these cases recently.

- Logging a missed tail call should not require a tail call. I suspect we spend as many insns preparing the context for tail calling into the program that outputs the perf event, so this feels a little pointless.
- Missing a tail call should emit a (rate limited) error-level log message addition to bumping the metric. Debugging missed tail calls using `cilium monitor` is almost impossible since this requires the local API to be up, by which point some programs might've already been replaced. Not sure if this will require a separate perf ring, I'm not familiar with `cilium monitor`'s internals, but the agent should open the ring immediately during startup (before replacing any progs) and log any missed tail calls. This is easier to spot during development.

**Comment by ti-mo** [comment]
Keeping this on the radar, but deferring until tail call misses pop up again at some point. (https://github.com/cilium/cilium/pull/30248)

There's room in the trailer of `struct metrics_key` to put a file and line number, but we need to be smart about allocating it. Do we go for an opaque 'extra' field? Or could more metrics benefit from file/lineno? Haven't given this much thought.
