### ISSUE TITLE
network problem caused by absent reverse entry in snat_v4_external map 

### ISSUE THREAD

**Issue by ghost** [cilium/cilium#27821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

One application in our prod environment encounters a network problem. When this application accesses one specific port of a remote host, the pod cannot get the response, the node get reponse but send RST. After restart the application, the problem still occur on another port. We find that in cilium_snat_v4_external map, there should be a pair of entries (tuples and states), but the reverse one is absent. After manually adding the lost entry, the network problem is fixed. The tuples in ct4 map exist.

`cilium monitor -t drop` shows no event. I think the eBPF program return NAT_PUNT_TO_STACK, which is ignored.

Cilium is configured as follows:
- ebpf masquerade enabled
- ebpf host routing enabled
- strict kube-proxy replacement
- native routing (tunnel: false)
- cluster-pool mode IPAM
- DSR is not used

eBPF program seems adding and deleting snat ingress and egress entries at same time, `deleteSwappedMapping4()` in conntrack GC seems delete one entry, but the comment says that this is used for DSR.

I don't know how to reproduce the problem, and am not sure this is a bug. Is there a situation that only one of the entries is deleted without DSR? Thanks.

### Cilium Version

1.11.17

### Kernel Version

5.10

### Kubernetes Version

1.24.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borkmann** [comment]
Hello @nijich, the 1.11.x OSS stable releases are EOL, did you consider upgrading as the issue might be fixed in newer Cilium, versions? https://github.com/cilium/cilium#stable-releases

**Comment by nijich** [comment]
Hello @borkmann, thanks for the information. I think it is hard for us to upgrade due to the potential operation risk and involving many people. It needs further discussion for our team to evaluate the problem. There are a lot of features in cilium, whereas we only use a small portion of them, and we want them stable. I am kind of worried abbout that the adding features will influence the features we used, which leading to frequent upgrading.

**Comment by youngnick** [comment]
Hi @nijich, thanks for your response. Unfortunately, because 1.11.x is EOL, we can't help much - there have been a _lot_ of fixes in this area.

If you do manage to upgrade to a supported version and can replicate the issue, please feel free to update or reopen here. I'll leave this open for now though.
