### ISSUE TITLE
External User Tunneled Through WireGuard Can't Connect to KubeDNS / any internal service

### ISSUE THREAD

**Issue by nadecancode** [cilium/cilium#27878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am currently using https://github.com/firezone/firezone to setup a wireguard server for users to access internal services. This has been working perfectly fine until today, after a restart to Cilium & operator the kube-dns service IP `10.96.0.10` is no longer accessible and it times out. I tried wg-easy and wireguard-operator and they yield exactly same result so I'm pretty sure it's not firezone's fault. I also exec'd into the actual wireguard pod and they're able to use kube-dns as usual, same as any other pods or nodes. The only one that can't connect to KubeDNS is the clients that have connected through wireguard.

I have also tried `hubble observe` the wireguard pods and it looks like there isn't even any traffic to kube-dns from the wireguard pod.

At this point, I suspect it has something to do with Cilium but I can't be too sure as I am out of ideas.

### Cilium Version

1.14.1

### Kernel Version

Ubuntu 22

### Kubernetes Version

Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NADESHIKON** [comment]
According to https://github.com/ivanmorenoj/k8s-wireguard/issues/3#issuecomment-1074687080, it seems like this sort of issue is indeed caused by CNI.

**Comment by youngnick** [comment]
Thanks for this report @NADESHIKON. Could you please upload a [sysdump](https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection) to this issue? That will help if someone can take a look.

**Comment by NADESHIKON** [comment]
> Thanks for this report @NADESHIKON. Could you please upload a [sysdump](https://docs.cilium.io/en/stable/operations/troubleshooting/#automatic-log-state-collection) to this issue? That will help if someone can take a look.

I no longer have access to the sysdump because but I know this issue only occurs with kube-proxy replacement = true, I could partially resolve this issue by turning on specific components eBPF but it looks like `bpf.masquerade` breaks the entire thing.

**Comment by youngnick** [comment]
Thanks for coming back to me @NADESHIKON.

Without a sysdump, it may take a bit longer for someone to investigate this, because they will need to try to replicate an environment. To help with that, here are a few questions:

- was this working with Cilium 1.14.1 before you restarted Cilium and the operator, or was that restart due to an upgrade?
- If it was an upgrade, what version were you on previously?
- If it wasn't due to an upgrade, did you change any config when you restarted?

At a minimum, for someone to investigate, they'll need:
- the command you used to install Cilium, or your current Cilium configuration (the `cilium config view` command would be okay)
- The details of your nodes (OS, kernel version, etc).
- What version of firebase you're using
- Some notes about how you installed firebase and the other Wireguard solutions

Thanks for anything you can give.

**Comment by NADESHIKON** [comment]
> was this working with Cilium 1.14.1 before you restarted Cilium and the operator, or was that restart due to an upgrade?
It was working before until two of my nodes crashed and I had to manually restart them, then this issue started occurring and kept occurring even after I went nuclear and reset my entire cluster network & reset the nodes. I tried both Cilium 1.14.1 and 1.15.0-pre0
If it was an upgrade, what version were you on previously?
> Always on 1.14.1
If it wasn't due to an upgrade, did you change any config when you restarted?
> Nope, nothing. Exactly same configuration and same system setting.

I used helm to install cilium and I used the basic command for kube-proxy replacement in the document.
All of my nodes are Ubuntu 20 LTS
I am using firezone 0.7.35 and I installed it by using its docker imagine to create a kubernetes deployment. On top of that, I also tried https://github.com/jodevsa/wireguard-operator and https://github.com/squat/kilo and they yield exactly same result. I followed the installation step indicated in their readme.

**Comment by youngnick** [comment]
Okay, thanks for that. I'm marking this for the datapath team's attention.

**Comment by RichardSufliarsky** [comment]
@NADESHIKON take a look at this comment: https://github.com/cilium/cilium/issues/27758#issuecomment-1718282433

**Comment by brb** [comment]
https://github.com/cilium/cilium/pull/33421 _might_ have fixed this issue.
