### ISSUE TITLE
cilium has wrong service list rules

### ISSUE THREAD

**Issue by llhhbc** [cilium/cilium#28084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/cilium/cilium/assets/6076617/29834f3d-990b-4d6b-9da6-b8b8232db8f7)

### Cilium Version

1.12.7

### Kernel Version

Linux 192-166-166-26 5.10.0-60.18.0.50.oe2203.x86_64 #1 SMP Wed Mar 30 03:12:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.18.17

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by julianwiedmann** [comment]
Hello @llhhbc ! Right now this issue has very little context / description. I take it the problem is that Cilium uses one set of backend IPs for the DNS ClusterIP service, while the coredns pods actually have different IPs?

Would you able to provide more information on how you ended up in this state? Are the stale backend IPs still known to the cluster? Could you upload a sysdump, as suggested in the issue template?

**Comment by llhhbc** [comment]
I don’t know how this happened. Currently, I found that only the bpf rules of some nodes are problematic, and coredns has not been restarted for a long time (the IP has not changed). I am not sure why cilium generates abnormal rules.

**Comment by lmb** [comment]
Please provide us with a sysdump. As Julian said, right now it's not possible to reproduce this issue.

**Comment by llhhbc** [comment]
This environment has been resolved by restarting, and you need to wait for the next occurrence to perform sysdump.
