### ISSUE TITLE
k8s: migrate CiliumNode and CiliumEndpoint watcher to Resource[T]

### ISSUE THREAD

**Issue by lmb** [cilium/cilium#28159]
Once https://github.com/cilium/cilium/pull/28091 goes in we'll be pulling CiliumNode and CiliumEndpoint twice: once via the old k8s watchers and once via the new Resource[T] framework. This has an obvious performance impact.

Migrate the watchers in `pkg/k8s/watchers/cilium_endpoint.go` and `pkg/k8s/watchers/cilium_node.go` to use Resource[T] internally. There is a simple example for this in `pkg/k8s/watchers/service.go`.

**Comment by pippolo84** [comment]
Regarding the CiliumEndpoint migration, it turned out not so straightforward.

The current CEP watcher sets up and exposes a store used [here](https://github.com/cilium/cilium/blob/58624f295ad971781f2b0cae3d66608bf2a48f9a/pkg/k8s/watchers/watcher.go#L1078), as part of a feature to let Hubble access k8s stores (see https://github.com/cilium/cilium/pull/12114). Luckily, that feature seems not to be relevant anymore, so my guess is that we can safely remove the CEP indexer usage there.
But the CEP watcher, together with the CES one, is also used for [cleaning up stale CEPs](https://github.com/cilium/cilium/blob/48a1c96cc78647d5d9b69aabc9fd651958588d54/daemon/cmd/daemon_main.go#L1806) at startup. To remove the old CEP informer, we need to modularize that GC, first. Doing so requires:

- expose an API to cells outside of package `daemon/cmd` to let the GC wait for endpoint restoration before running
- provide both Resource[CES] and Resource[CEP], since the GC needs to read CESs too.
- apply [this indexer](https://github.com/cilium/cilium/blob/48a1c96cc78647d5d9b69aabc9fd651958588d54/pkg/k8s/watchers/cilium_endpoint.go#L82) to the Resource[CEP]. This requires extra care:
  - that indexer references the LocalNodeStore to get the [IP of the local node](https://github.com/cilium/cilium/blob/48a1c96cc78647d5d9b69aabc9fd651958588d54/pkg/k8s/watchers/cilium_endpoint_slice.go#L29)
  - but the same resource constructor is used for [clustermesh-apiserver](https://github.com/cilium/cilium/blob/48a1c96cc78647d5d9b69aabc9fd651958588d54/clustermesh-apiserver/clustermesh/k8s/resources.go#L45) too, where we don't have a cell providing `LocalNodeStore`.
  - so, we need to use a separate resource constructor (one without the indexer) for clustermesh-apiserver, like we already do for the operator k8s resources.

After that, we can finally refactor the CES and CEP watcher like we did for the CiliumNode.
I'm gonna open the PRs to complete all of the above steps.

**Comment by pippolo84** [comment]
- [ ] https://github.com/cilium/cilium/pull/29222
- [ ] https://github.com/cilium/cilium/pull/29243
- [ ] https://github.com/cilium/cilium/pull/29244
- [ ] https://github.com/cilium/cilium/pull/29246
- [ ] https://github.com/cilium/cilium/pull/29249

**Comment by pippolo84** [comment]
All relevant PRs have been merged (see [this comment](https://github.com/cilium/cilium/issues/28159#issuecomment-1817469999)), closing.
