### ISSUE TITLE
CFP: BGP: Set R-bit in graceful restart

### ISSUE THREAD

**Issue by ArsenyBelorukov** [cilium/cilium#28168]
## Cilium Feature Proposal
       

**Describe the feature you'd like**

Currently, cilium doesn't set R-bit in a BGP OPEN message. It leads to a situation, where the Receiving Speaker withdraw routes when a cilium agent reconnects, and then adds routes again. There is a short disruption.

According to https://www.rfc-editor.org/rfc/rfc4724.html#section-4.1
```
To re-establish the session with its peer, the Restarting Speaker
MUST set the "Restart State" bit in the Graceful Restart Capability
of the OPEN message. 
```

**(Optional) Describe your proposed solution**
gobgp has the ability to set R-bit:

```
diff --git a/pkg/bgpv1/gobgp/server.go b/pkg/bgpv1/gobgp/server.go
index d5f099d604..a2c2844cab 100644
--- a/pkg/bgpv1/gobgp/server.go
+++ b/pkg/bgpv1/gobgp/server.go
@@ -283,6 +283,7 @@ func (g *GoBGPServer) getPeerConfig(ctx context.Context, n types.NeighborRequest
 		peer.GracefulRestart.Enabled = true
 		peer.GracefulRestart.RestartTime = uint32(*n.Neighbor.GracefulRestart.RestartTimeSeconds)
 		peer.GracefulRestart.NotificationEnabled = true
+		peer.GracefulRestart.LocalRestarting = true
 	}

 	for _, afiConf := range peer.AfiSafis {
```

**Comment by harsimran-pabla** [comment]
Hi @ArsenyBelorukov, thanks for this proposal. I'd like to understand the issue in more detail. Did you check if setting this bit was resolving your issue? 

The main reason why the LocalRestarting bit was not set, is because we do not have a way to know if this is first-time user config or peer config after a restart. We can definitely set it from startup ( you can send out a PR for it )

If setting this bit is still not resolving your issue, it could be a race between Cilium learning all the advertised prefixes from Kubernetes API and when Cilium sends out an EoR marker to the BGP peer. If Cilium sends EoR marker before it can learn all the routes, then the peer will remove extra routes which are installed in its RIB.

**Comment by ArsenyBelorukov** [comment]
I don't know exactly what could happen if restarting bit is set in case it is a first-time session. But according to [RFC](https://www.rfc-editor.org/rfc/rfc4724.html) it seems okay to set it if send EoR marker.
In my case, it helps:
restating agent without r-bit:
```
# session isn't established
abelorukov@sw> show bgp summary | match 10.65.235.19
10.65.235.19          65065          0          0       0       7           3 Active

# the route exists
abelorukov@sw> show route 10.64.7.0/24
10.64.7.0/24       *[BGP/170] 00:01:44, localpref 150
                      AS path: I, validation-state: unverified
                    >  to 10.65.235.19 via irb.235

# new session is established
abelorukov@sw> show bgp summary | match 10.65.235.19
10.65.235.19          65065          9          7       0       7           5 Establ

# the route was removed and added again
abelorukov@sw> show route 10.64.7.0/24
10.64.7.0/24       *[BGP/170] 00:00:07, localpref 150
                      AS path: I, validation-state: unverified
                    >  to 10.65.235.19 via irb.235
```
we can see that the route was re-added (it's time was reseted) 

restating agent with r-bit:
```
# session isn't established
abelorukov@sw> show bgp summary | match 10.65.235.19
10.65.235.19          65065          0          0       0       8          14 Active

# the route exists
abelorukov@sw> show route 10.64.7.0/24
10.64.7.0/24       *[BGP/170] 00:01:18, localpref 150
                      AS path: I, validation-state: unverified
                    >  to 10.65.235.19 via irb.235

# new session is established
abelorukov@sw> show bgp summary | match 10.65.235.19
10.65.235.19          65065         11         12       0       8           9 Establ

# the route wasn't removed
abelorukov@sw> show route 10.64.7.0/24
10.64.7.0/24       *[BGP/170] 00:01:29, localpref 150
                      AS path: I, validation-state: unverified
                    >  to 10.65.235.19 via irb.235
```
we can see that the route wasn't re-added (it's time wasn't reseted) 

What negative side effects do you know about setting r-bit in a first-time session?

**Comment by harsimran-pabla** [comment]
From the RFC, setting R bit is mostly to avoid deadlock. 

```
The most significant bit is defined as the Restart State (R)
         bit, which can be used to avoid possible deadlock caused by
         waiting for the End-of-RIB marker when multiple BGP speakers
         peering with each other restart.  When set (value 1), this bit
         indicates that the BGP speaker has restarted, and its peer MUST
         NOT wait for the End-of-RIB marker from the speaker before
         advertising routing information to the speaker.
```

Since Cilium is not supposed to act as a transit router, it was deemed unnecessary to set it. Based on the Juniper behaviour which you describe, I think we can go ahead and set it all the time ( at least at surface level I do not see any issue here ). 

Feel free to open a PR for the change.

**Comment by ArsenyBelorukov** [comment]
I will do
