### ISSUE TITLE
Eliminate Cilium Prefixing in CRDs

### ISSUE THREAD

**Issue by danehans** [cilium/cilium#28265]
https://github.com/cilium/cilium/pull/28175 intends to add 5 new CRDs that are prefixed with Cilium even though the APIs are in the `cilim.io` API group. The Cilium prefix is being included in each of the CRDs because the project has set a precedent of prefixing Cilium to CRDs. This kind of studdering is against Golang/API conventions and should be avoided.

**Comment by lmb** [comment]
If we stop prefixing now we'll end up in a world where some CRDs have the prefix, and others don't. Removing all of the prefixes seems like a lot of work for an unclear benefit, so the chances of that happening are low. In effect we'd be stuck in a world with both styles of CRD naming, which seems worse than what we have now.

In any case, this is not my call to make. I've triaged the issue so that it shows up in the appropriate places.
