### ISSUE TITLE
Gather cilium-envoy.log in bugtool

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#2829]
Doesn't look like the cilium-envoy log is gathered in bugtool output:

```
$ git grep "cilium-envoy.log"                                                                                                                                                                                      
pkg/envoy/envoy.go:     logPath := filepath.Join(logDir, "cilium-envoy.log")
```

**Comment by ianvernon** [comment]
I think this necessitates a change to the agent, where we can get all of the immutable configuration options provided to it at startup. Currently, we do not have access to all of these; otherwise, if users configure the agent to send cilium-envoy logs to a different location, we will not have access to them. This could be useful for debugging as well.

**Comment by ianvernon** [comment]
@jrajahalme @rlenglet is this needed given that we interleave `cilium-envoy` logs with Cilium logs now?

**Comment by rlenglet** [comment]
IMO, the Cilium logs are good enough now.
