### ISSUE TITLE
Improve agent resilience against apiserver problems

### ISSUE THREAD

**Issue by aojea** [cilium/cilium#28390]
We found an interesting behavior recently, if the agent does not have connectivity or permissions with the apiserver, it is not able to assign it an identity and new pods are not able to send or receive traffic, causing a considerable damage

My teammate @dlapcevic made a good analysis of the problem, quoting him

> What most likely happens is that during endpoint creation for the new pod, agent fails to get pod labels (fetchK8sLabelsAndAnnotations()) when using pod store (GetCachedPod()) because pod store doesn’t receive new pod events because of watch permissions.
> In this case, the Unable to fetch kubernetes labels log warning should be visible, but it won’t fail the endpoint creation. It will instead give init ID to the new endpoint.
> All traffic for the new endpoint is denied because it has init ID. https://docs.cilium.io/en/stable/security/policy/lifecycle/#init-identity
> 
> Code pointer: https://github.com/cilium/cilium/blob/v1.12/daemon/cmd/endpoint.go#L387

He is also working on improving this area, see related CFP https://github.com/cilium/cilium/issues/27752

Commenting this @squeed the other day, we thought about the possibility of removing this dependency on the apiserver to get the Pod labels, and be able to get it from the CNI ADD command directly, the [CRI API already sends down the labels and annotations to the Container Runtime](https://github.com/kubernetes/kubernetes/issues/69882#issuecomment-1228138339) and at least in [containerd there is way to send this metadata as part of the CNI ADD command](https://github.com/kubernetes/kubernetes/issues/69882#issuecomment-1509077177)

**Comment by aojea** [comment]
cc @squeed @joestringer @aanm

**Comment by joestringer** [comment]
I think we need to be a bit careful here around source of truth and potential local spoofing if assuming issues with kube-apiserver connectivity. In general I don't think we've ever assumed that it's possible to deploy new Pods while Cilium has a failure of connectivity to kube-apiserver.

**Comment by squeed** [comment]
Backstory: _we already support this_. Specifically, the PutEndpoint API call already accepts a Labels array and passes it directly to the endpoint. The only change would be plumbing it through CNI.

> potential local spoofing 

The labels can be passed in via the gRPC socket CreateEndpoint call as part of the CNI ADD. Access to that socket is already privileged (and can, indeed, disable policy entirely for a given node). In that case, I think it's safe to trust the labels, as they flow from kubelet -> containerd -> cni -> agent.

**Comment by aojea** [comment]
> In general I don't think we've ever assumed that it's possible to deploy new Pods while Cilium has a persistent failure of connectivity to kube-apiserver.

yeah, that is the other side of the problem, and @squeed , I and others are working on the CNI spec to support a STATUS verb that allows the kubelet to set the node unready , hence no new pods will be scheduled if the agent is unhealthy or with problems https://github.com/containernetworking/cni/issues/859

**Comment by christarazi** [comment]
> The only change would be plumbing it through CNI.

Recently, I looked into this a bit, and I recall that a more recent version of the spec supports passing metadata / labels in the CNI ADD. I can't seem to find where I posted my findings, but do you know which version of the spec supports this and when we could support it in Cilium? It could eliminate a whole hop to the apiserver on endpoint creation.

**Comment by joestringer** [comment]
> > potential local spoofing
> 
> The labels can be passed in via the gRPC socket CreateEndpoint call as part of the CNI ADD. Access to that socket is already privileged (and can, indeed, disable policy entirely for a given node). In that case, I think it's safe to trust the labels, as they flow from kubelet -> containerd -> cni -> agent.

Let me expand a little bit more: Access to the socket follows the [Root-equivalent Host Attacker](https://docs.cilium.io/en/stable/security/threat-model/#root-equivalent-host-attacker) threat actor in the Cilium threat model where the attacker compromises a particular node, but may not have compromised other nodes in the cluster. In general I think that we should be trying to move slowly towards a security posture where compromise of a particular node does not then impact the security properties of other nodes, or at least, that in cases where node compromise leads to limitations on the security posture on remote nodes, then that is an explicit user opt-in. There may be good reasons to trade off stricter security protocols in favour of better availability guarantees or other benefits.

I agree that currently the facility exists in the Cilium API, and it doesn't violate the security model as-is, and maybe there's even an answer for how to progress to a better security model while also adopting this proposal (such as better apiserver-side cross-checking of requests from individual agents/nodes).

Some other aspects this touches on is the longer term direction of whether agents can/should be able to locally allocate new identities which is under discussion in https://github.com/cilium/cilium/issues/27752 . While the CNI-provided label set may not be new, and hence won't require identity allocation, there is also the case where the CNI-provided label set *is* brand new. In the latter case of course Cilium's ability to allocate that Security Identity could also be impacted by the same apiserver resiliency issues brought up in this issue (depending on whether Identity allocation goes through kube-apiserver or directly through etcd).

The other aspect I can think of is that when Cilium creates an Endpoint, it also creates CEP objects in Kubernetes in order to inform remote nodes about the new Endpoint. If we're assuming kube-apiserver availability issues, then even this request is potentially problematic and we may not be able to bootstrap the Endpoint anyway.

**Comment by joestringer** [comment]
I'd also like to look a little bit closer at the motivation here.

I read that "permissions issues" is one of the primary motivators. Exactly which permissions are limited and is that a legitimate way to deploy Cilium, or a misconfiguration? Is that part of a security hardening effort and is it part of an attempt to adjust the Cilium Endpoint initialization workflow? 

The second motivation I see is connectivity issues with kube-apiserver. Can we define the pattern we are trying to handle here? In general today I think there are up to three touchpoints on k8s apiserver for Endpoint initialization, depending on the particulars of whether k8s is used as a backend for sharing information between agents:
- Pull labels (referred in issue description)
- Allocate security identity
- Propagate CEP

If all three of these operations require the kube-apiserver (first one definitely does, latter two depend on Cilium deployment model AFAIK), then a complete unavailability of kube-apiserver would prevent Endpoint creation regardless of how we handle the first step.

If we're talking about partial outage of kube-apiserver or the kube-apiserver being overloaded such that it's unable to propagate information in a timely manner, then removing the first step in favour of pulling the information via kube-apiserver->kubelet->CRI->CNI->Cilium would reduce the load at Pod initialization time. We also need the namespace labels to fully assign the correct identity. Assuming all of that, I think that eventually we probably *still* want Cilium to pull the full correct information directly from kube-apiserver just to double-check that Cilium is correctly implementing the policy wrt the latest versions of the resources. Is the idea that the "Get labels" step is duplicated with the k8s Pod watch anyway, so we could drop that step in favour of Pod watch update and still get confirmation directly from kube-apiserver in order to cross-check the labels are correct? That sounds like a nice optimization, I guess it's one request per Pod deployment. Depending on cluster Pod churn, maybe that's enough to tip over some limit. In the back of my mind I do wonder though whether the overall system is so tightly optimized that this sort of step makes a big difference at this point or whether there are lower hanging fruit.

At the same time, modulo the longer term security model implications above, I do like the idea of leveraging the labels via CNI ADD.

**Comment by dlapcevic** [comment]
>- Pull labels (referred in issue description)
>- Allocate security identity
>- Propagate CEP
>
>If all three of these operations require the kube-apiserver (first one definitely does, latter two depend on Cilium deployment model AFAIK), then a complete unavailability of kube-apiserver would prevent Endpoint creation regardless of how we handle the first step.

@joestringer, in the described case, if pod is not found in the Pod watcher's cache when fetching labels, then the CNI ADD will be completed, and pod will be running. The reason is that step 2 (Allocate security identity) will not interact with kube-apiserver when it allocates the init identity for a pod that has unknown labels (no labels). And step 3 (Propagate CEP) is not part of CNI ADD, if you mean that it needs to create CEP by sending a request to kube-apiserver. CNI ADD only creates local endpoint in cilium-agent's memory. The actual update is done by the endpoint synchronizer (10s interval), which fails to sync local endpoints to CEPs because the connection to kube-apiserver is down. Nonetheless, the new pod is running with init ID, denying all traffic.

**Comment by joestringer** [comment]
I stand corrected, thanks. That makes me wonder though, how does kube-apiserver successfully inform kubelet that the Pod must be deployed while not being available to Cilium? In general does it even make sense for Cilium to deploy Pods if it is disconnected / out of sync with the management plane? How long is OK for Cilium to drift along without access to kube-apiserver before it should just fail out to make the failure scenario obvious?

**Comment by skmatti** [comment]
Can we reopen the issue? @aojea
