### ISSUE TITLE
CFP: Response compression

### ISSUE THREAD

**Issue by artyom-p** [cilium/cilium#28499]
## Cilium Feature Proposal

**Describe the feature you'd like**

Probably its doable even now through some envoy filters, but the setup is not that straightforward, would be nice to have some simplified way to add response compression (global or per workload) in cilium itself.

**Comment by rauanmayemir** [comment]
@artyom-p It is not possible currently as all the compression filters in envoy build are commented out.

I've suggested them alongside other filters in #27008, but after re-evaluating I would say that compression is the most crucial and needed.

I'm already solving my other use cases by running a userspace level-two proxy with all the needed filters, but for 'regular' workloads (e.g related to infra) I would prefer to use cilium's envoy.

Example: I have a grafana deployment that is routed directly via cilium envoy and the performance is awful because browser's busy downloading uncompressed javascripts.

**Comment by artyom-p** [comment]
Riiight, https://github.com/cilium/proxy/blob/6b9ff340bc4058c9063b74aeeadd58fdc724c32e/envoy_build_config/extensions_build_config.bzl

**Comment by artyom-p** [comment]
Not stale

**Comment by artyom-p** [comment]
Still relevant

**Comment by artyom-p** [comment]
Can we reopen it again?
