### ISSUE TITLE
Kubernetes node loses connectivity after agent shutdown

### ISSUE THREAD

**Issue by jonkerj** [cilium/cilium#28755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I installed Cilium 1.14.x on Talos Linux (which mounts bpf automatically) with `bpf.autoMount.enabled=false`, and whenever the cilium agent shuts down (e.g. after a Talos drain or pod delete), the node gets and stays unreachable.

I've installed Cilium through Helm, with `--set bpf.autoMount.enabled=false`, and it's reproducable with only deleting the agent pod.

### Cilium Version

1.14.2 on Talos Linux 1.4.x and 1.5.x

### Kernel Version

6.1.30

### Kubernetes Version

1.27.3

### Sysdump

n/a

### Relevant log output

```shell
level=warning msg="================================= WARNING ==========================================" subsys=bpf
level=warning msg="BPF filesystem is not mounted. This will lead to network disruption when Cilium pods" subsys=bpf
level=warning msg="are restarted. Ensure that the BPF filesystem is mounted in the host." subsys=bpf
level=warning msg="https://docs.cilium.io/en/stable/operations/system_requirements/#mounted-ebpf-filesystem" subsys=bpf
level=warning msg="====================================================================================" subsys=bpf
level=info msg="Mounting BPF filesystem at /sys/fs/bpf" subsys=bpf
level=info msg="Mounted cgroupv2 filesystem at /sys/fs/cgroup" subsys=cgroups
level=info msg="Parsing base label prefixes from default label list" subsys=labels-filter
```
```


### Anything else?

The logs show that the agent is mounting the BPF FS, after having warned that this may have this effect. This suggests the agent thinks BPF is not already mounted (or the logic detecting that is faulty), and inspecting the pod this seems the case.

I think the `DaemonSet` template lacks the proper conditionals to (bi-dir) mount BPF FS for my use case. I've manually edited the `DaemonSet` to `hostPath` `/sys/fs/bpf` into the pod, and I can safely delete the Pod. Also, the logs show this:

```
level=info msg="Detected mounted BPF filesystem at /sys/fs/bpf" subsys=bpf
level=info msg="Mounted cgroupv2 filesystem at /sys/fs/cgroup" subsys=cgroups
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylandreimerink** [comment]
I think there is a misunderstanding of what the `bpf.autoMount.enabled` setting/helm value does. Cilium will always check for the existence of a BPFFS or mount one at the default BPFFS at `/sys/fs/bpf` or a custom location indicated by `bpf.root`.  The autoMount doesn't change that. 

> I think the `DaemonSet` template lacks the proper conditionals to (bi-dir) mount BPF FS for my use case.

This is exactly what the `bpf.autoMount.enabled` setting does, if set to `true` the template creates a bi-dir mount, if `false` like you have configured it, Cilium expects that this is not needed. That is because some environments always create this mount regardless of daemonset configuration. https://docs.cilium.io/en/stable/network/kubernetes/configuration/#crio

So I think you need `bpf.autoMount.enabled=true` in your setup.

**Comment by lennardk** [comment]
Hi, colleague of @jonkerj here.

I think the issue here is with the behavior of the `bpf.autoMount.enabled` and `.Values.containerRuntime.integration "crio"` values in the different scenarios.

Scenarios being:

- host may or may not have the BPFFS mount, container automaticly gets it (case 'CRI-O')
- host already has the BPFFS mount, container needs to explicitly host-mount it (case Talos)
- host does not have the BPFFS mount

For the CRI-O case, I'm saying 'may or may not have' because I don't have such an environment to check, I can only see in the helm chart that before `bpf.autoMount.enabled`, I can see there's also a privileged container (either cilium-agent or a init-container). If the host-mount is present in those cases or for some of those cases, the init container may have always been unneeded.

For the case Talos, the init-container is unnecessary but the cilium-agent host-mount is required (to not have issues during restart).

If I read [the helm chart](https://github.com/cilium/cilium/blob/v1.14.2/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml), there's currently no set of values that results in not running privileged, not having the init-container, but having the host-mount in cilium-agent: `bpf.autoMount.enabled` set to false is required to not get the init container, but also completely prevents the host-mount in the cilium-agent container.

cc @frezbo as the author of the `bpg.autoMount.enabled` patch, to hopefully weigh in with some insights.

**Comment by frezbo** [comment]
@lennardk you're right about the assumptions, it's my mistake and missed the host mount, would you mind fixing it? I can otherwise fix it later this week.

**Comment by lennardk** [comment]
> Bi-directional mounting requires the container to be privileged.
That's clear, thanks

> So you can have the host mount without making the container privileged, but in that case any pinned BPF programs will not persist on the hosts BPFFS and you will see these connection losses.
Is this truly the case even if the host mounts BPFFS on startup? In other words, during runtime are new submounts created that need to be propagated? Our (basic) testing seems to indicate that *only* having a `HostToContainer` mount for it in `cilium-agent` is sufficient.

For reference, in case of Talos, [this code](https://github.com/siderolabs/talos/blob/main/internal/pkg/mount/bpffs.go) runs as part of the boot process.

**Comment by lennardk** [comment]
> For reference, in case of Talos, [this code](https://github.com/siderolabs/talos/blob/main/internal/pkg/mount/bpffs.go) runs as part of the boot process.
While this is true that code doesn't tell much. I should be pointing [here](https://github.com/siderolabs/talos/blob/5dff164f1c8fc08b66f0ea509db36561eaef464c/internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go#L260C13-L260C13)

**Comment by frezbo** [comment]
> > For reference, in case of Talos, [this code](https://github.com/siderolabs/talos/blob/main/internal/pkg/mount/bpffs.go) runs as part of the boot process.
> 
> While this is true that code doesn't tell much. I should be pointing [here](https://github.com/siderolabs/talos/blob/5dff164f1c8fc08b66f0ea509db36561eaef464c/internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go#L260C13-L260C13)

i guess we need then privileged? not sure how it works on other distros

**Comment by jonkerj** [comment]
At the risk of increasing the confusion: when I create a (host-to-container propagated) hostpath volume in the agent's container, the agent is happy ("detected mounted BPF filesystem") and the node maintains connectivity after restart/shutdown of the agent. And my pod is un-privileged. In my case, Talos already mounted the BPFFS and to recap, I hostpath it into the pod (uni-directional).

Are we really sure we need privileged and/or bi-dir mount? It seems to work fine without both.

**Comment by dylandreimerink** [comment]
> when I create a (host-to-container propagated) hostpath volume in the agent's container, the agent is happy ("detected mounted BPF filesystem") and the node maintains connectivity after restart/shutdown of the agent.

It might depend on which features are in use and how programs are attached. Attaching TC programs via netlink increments the refcount so the agent can go away without issue, same goes for any map actively in use by any program that stays active. But for XDP we use BPF-links instread of netlink, and in that case the program will unload when the FS pin goes away.

> Are we really sure we need privileged and/or bi-dir mount? It seems to work fine without both.

The k8s docs say:

> Warning: Bidirectional mount propagation can be dangerous. It can damage the host operating system and therefore it is allowed only in privileged containers. Familiarity with Linux kernel behavior is strongly recommended. In addition, any volume mounts created by containers in pods must be destroyed (unmounted) by the containers on termination.

Not sure where this is enforced, but it seems we currently make the assumption this is for every container runtime. If this is not the case then that might be good to know.

**Comment by jonkerj** [comment]
> It might depend on which features are in use and how programs are attached. Attaching TC programs via netlink increments the refcount so the agent can go away without issue, same goes for any map actively in use by any program that stays active. But for XDP we use BPF-links instread of netlink, and in that case the program will unload when the FS pin goes away.

This actually explains why it works in our situation (we don't use XDP).

Having considered all this I don't think there is a bug, but I think the Helm values are bit confusing, as the semantics/logic behind `cgroup.autoMount.enabled` differs from  `bpf.autoMount.enabled`. We blindly assumed the latter being analogous to the former, causing the issue I reported. If you don't need XDP you could do with even less privileges than in 1.13, but the chart does not support that currently (ie: unidir hostpath-mount BPFFS).

**Comment by jonkerj** [comment]
> @lennardk you're right about the assumptions, it's my mistake and missed the host mount, would you mind fixing it? I can otherwise fix it later this week.

@frezbo, any news on this?

**Comment by jonkerj** [comment]
I'll try to make some time next week to look at the issue again
