### ISSUE TITLE
Cilium v1.14.3 failed to retrieve route for remote node IP

### ISSUE THREAD

**Issue by dghubble** [cilium/cilium#28858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A fresh cluster with Cilium v1.14.3 logs that the network is unreachable. Rolling back the Cilium daemonset to Cilium v1.14.2 the log messages go away.

### Cilium Version

v1.14.3

### Kernel Version

6.5.5

### Kubernetes Version

Kubernetes v1.28.3

### Sysdump

[bugtool.tgz](https://github.com/cilium/cilium/files/13199435/bugtool.tgz)

### Relevant log output

```shell
level=info msg="Unable to determine next hop address" error="failed to retrieve route for remote node IP: network is unreachable" interface=kube-ipvs0 ipAddr=10.168.0.2 subsys=node-neigh-debug
level=info msg="Unable to determine next hop address" error="failed to retrieve route for remote node IP: network is unreachable" interface=kube-ipvs0 ipAddr=10.168.0.4 subsys=node-neigh-debug
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by clcc2019** [comment]
I also encountered this problem.

**Comment by knowdee** [comment]
I also encountered this problem.
The version of my install for cilium is v1.14.4 .

**Comment by DirkTheDaring** [comment]
happened to me to with v1.14.4 -> revertedback to my previous v1.14.1 --> works again.

**Comment by dghubble** [comment]
I should mention, I haven't actually seen negative effects or rolled back, the log message just appears to be noise

**Comment by DirkTheDaring** [comment]
I have seen a major impact. Basically networking stopped working between certain pods which where on different machines.
Additionally also DNS lookup  for an external DNS Server stopped (could not connect anymore).   
The internal pods could sometime also not reach the internal coredns server.
Severall attempts to regenerate everything on a node did not lead to any success

reverting to 1.14.1 cured all of these issues.   So I consider this for 20 node cluster broken (1.14.4).   Currently I prepare an experiment if it runs on 1.14.2

**Comment by angapov** [comment]
Not sure if it's related, but we also had similar symptoms after upgrading to 1.14.x. We had intermittent errors when connecting to `ClusterIP` Services and CoreDNS. It turned out that our nodes are using cgroupv2, so I had to add this to Helm values:
```
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
  ```
Btw this is also mentioned in the documentation: https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#validate-bpf-cgroup-programs-attachment. Should've read it first.

**Comment by danielkza** [comment]
I see this specifically only for IPv6 addresses, and I can see the address is route-able and reachable from the host, which makes me puzzled.

**Comment by YutaroHayakawa** [comment]
I suspect [this commit](https://github.com/cilium/cilium/commit/f2dcc86ae86699ce5903c60328444393605adf0d) introduces the issue.

This is backported to `v1.14` branch and introduced in `v1.14.3`. Since this commit, when you enable Kube Proxy Replacement, Cilium does [L2 neighbor discovery](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#neighbor-discovery) for tunneling mode while it didn't on the older versions.

As a part of the neighbor discovery process, Cilium periodically checks whether other nodes in the cluster are in the same L2 domain. What it does essentially is `ip route get <nodeIP> oif <dev>` where <dev> is a device that attaches the BPF program (the device you specified with `devices` option or automatically detected).

https://github.com/cilium/cilium/blob/5fd020a2d764e7c9e9944d82e96b7051f8cbd4ff/pkg/datapath/linux/node.go#L616-L620

The issue is that it generates the `failed to retrieve route for remote node IP` for any error. `network unreachable` typically happens when the device is down. Probably, in the case of the case described in the issue description, `kube-ipvs0` is down, or somehow, the node IP `10.168.0.2` is unreachable from the device.

So, I guess the people who start to see the logs on upgrade meet the following conditions.

1. Using KPR
2. Using tunnel mode
3. One or more of the KPR-enabled devices are down

**Comment by Jean-Daniel** [comment]
I have this log but I'm not using tunnel mode and all my devices are up.

**Comment by diegocn** [comment]
> I suspect [this commit](https://github.com/cilium/cilium/commit/f2dcc86ae86699ce5903c60328444393605adf0d) introduces the issue.
> 
> This is backported to `v1.14` branch and introduced in `v1.14.3`. Since this commit, when you enable Kube Proxy Replacement, Cilium does [L2 neighbor discovery](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#neighbor-discovery) for tunneling mode while it didn't on the older versions.
> 
> As a part of the neighbor discovery process, Cilium periodically checks whether other nodes in the cluster are in the same L2 domain. What it does essentially is `ip route get <nodeIP> oif <dev>` where is a device that attaches the BPF program (the device you specified with `devices` option or automatically detected).
> 
> https://github.com/cilium/cilium/blob/5fd020a2d764e7c9e9944d82e96b7051f8cbd4ff/pkg/datapath/linux/node.go#L616-L620
> 
> The issue is that it generates the `failed to retrieve route for remote node IP` for any error. `network unreachable` typically happens when the device is down. Probably, in the case of the case described in the issue description, `kube-ipvs0` is down, or somehow, the node IP `10.168.0.2` is unreachable from the device.
> 
> So, I guess the people who start to see the logs on upgrade meet the following conditions.
> 
> 1. Using KPR
> 2. Using tunnel mode
> 3. One or more of the KPR-enabled devices are down

I can confirm the bug is happening for the first two conditions.
1. Using KPR
2. Using tunnel mode

Cilium version: 1.15.2

**Comment by ankitjain28may** [comment]
Any resolution regarding the `l2NeighDiscovery` since i am facing the same issue with Kube Proxy Replacement. My kernel version is 5.15.x

**Comment by dghubble** [comment]
This was solved for me by Cilium v1.15.3

**Comment by ankitjain28may** [comment]
Thanks, let me try that then.

**Comment by ankitjain28may** [comment]
Yeah, I am not getting this error after upgrading to v1.15.3, Thanks for the help.
