### ISSUE TITLE
FQDN: transition to asynchronous ipcache APIs

### ISSUE THREAD

**Issue by squeed** [cilium/cilium#28930]
We're almost done with the "legacy" IPCache APIs. The biggest remaining holdout is FQDN policy. For good reason: FQDN policy has the most complex lifecycle and many-to-many mappings _everywhere_.

This issue proposes a new architecture for the FQDN selector system. It aims for a simpler lifecycle on updates and some code removal.

# Background

The FQDN policy system has three main components:

* **DNSCache**: A forward and reverse mapping of name -> ips (along with some expiration information). This is the ultimate source of (name -> IP) mappings as well as the "owner" of IP lifecycle.
* **NameManager**: A list of currently active FQDN selectors
* **SelectorCache**: Generates a set of allowed identities for a given selector

# Proposal
Right now, identities for FQDN-policy CIDRs are generated directly by the NameManager and passed in to the SelectorCache.

My proposal would be to move identity management fully to the NameManager, and make FQDN selectors just a bag of `cidr:xxxx/32` selectors.

1. A FQDN selector is created. It calls `NameManager.RegisterForFQDNUpdates()` and preloads its cidr set from existing known names
2. A DNS response is intercepted, and - as before - the NameManager is notified:
    * The NameManager updates its internal datastructures, and determines if any changes are necessary. Assuming it is...
    * The NameManager calls `ipcache.UpsertMetadata(ip)`
    * All affected selectors have the method `AddLabels(`cidr:ip/32`)
    * If any of the newly selected cidr labels already have an identity, the selector is updated and an incremental update is pushed to the policy engine
    * When the ipcache allocates any new identities, it will directly update the SelectorCache, which now pushes these updates down to the FQDN selectors
3. The TTLs + conntrack run out, and some IPs are removed (this remains unchanged). Again, the NameManager is responsible for propagating this update. In the new flow, the NameManager calls `selector.RemoveLabels("cidr:stale_ip/32")` which causes the selector to update its set of cached identities.

### Blocking behavior on startup

One concern about migrating to the asynchronous APIs is that the ipcache's asynchronous apply loop is blocked until k8s caches are synced. The FQDN proxy right now starts listening quite early - in fact, in `newDaemon()`, not in `startDaemon()`. Any DNS responses received between proxy start and k8s cache population will not be able to allocate new identities. This could lead to policy drops if a new address is detected.

I can't immediately see a way around this; CIDRs will eventually have arbitrary labels, so we don't want to insert them before caches are synced or else numeric identities will flap. But delaying their insertion could lead to noticeable policy drops.

## An aside: synchronicity

There is an impedance mismatch between the asynchronous ipcache APIs and the DNS proxy. It attempts to ensure all identities are plumbed before returning the DNS response to the client. We need to build in a way to wait for identities to be made available. Additionally, we should not wait when desired identities are already fulfilled. This will require some API changes to the ipcache.

# The plan

I expect the sequence of commits to look like this:

1. Move identity management entirely to the NameManager
2. Convert FQDNSelector to a "bag of labels"
3. Refactor SelectorCache internal APIs
4. Return a channel that is closed when the ipcache has applied all pending prefixes
5. Convert the NameManager to the ipcache asynchronous APIs

**Comment by joestringer** [comment]
Thanks for putting together this proposal! I'd love to see this logic move over to the new async API, but yes I also agree that this is one of the trickier cases to handle.

> Right now, identities for FQDN-policy CIDRs are generated directly by the NameManager and passed in to the SelectorCache.

Hmm, this shouldn't be the case, though I think this is not critical for reasoning about the proposal. For some background, commit b10797c7d87b5b9e0c85e4a113fe302167b48933 (Nov 2021) aimed to move that over to the fqdn selectors. For some further background to that, a couple of years ago we had some identity leaks from FQDN paths that were causing issues, so we needed as minimal of a fix as we could make it while ultimately reworking the code sufficiently enough to allow us to balance the reference counting. Chris and I spent a bunch of time around this, and commit de10e82639cc50478d6d2bb1814c50bd559cd419 (Oct 2021) was one of the other key changes in that area. Even at that time I wasn't fully convinced exactly where the identity reference counts should belong.. that commentary may provide some additional context to think about this problem:

    Although I can see arguments for perhaps associating these references
    with the NameManager itself as it tracks the usage of each IP for FQDN
    policy and hence could tie the reference to the lifetime of the usage of
    the IP overall in the agent, so far the code has implicitly tied the
    allocation of each identity to its usage in each selector. As such, this
    commit attempts to simply acknowledge this reality and extend the
    update/release of the selectors in the NameManager to also release those
    same references that each selector holds

> A DNS response is intercepted.

I guess the missing (implied) step immediately after this is for the DNS proxy to inform the name manager, and that code already exists + wouldn't change?

> The NameManager calls selector.SetIPs(name, ips)

Is the full set of the ips? Maybe to add some complication, it's technically possible for different endpoints to use different DNS servers and get different results here.. actually come to think of it I'm not entirely sure whether we are fully consistent on this. I know we have per-endpoint name lists but I'm a little rough on the details of how those boil down into the selectors and apply to the policies across other endpoints. I have a niggling thought at the back of my head that a `SetIPs` API could discard good state, but on the other hand the NameManager should know everything there is to know about the names, so I can't express a specific issue with such an API.

One other aspect I didn't see mentioned is restore. We store & restore the Name<->IP mappnigs across restart, since that information cannot be reconstructed another way. That said, I think this integrates pretty easily into the proposal; part of the name manager recreation would involve associating the IPs. That said, if the name manager is longer lived and those restored prefixes need identities, then associating the ipcache metadata updates with the selectors is a little awkward.

> Any orphaned IPs have their metadata removed

Note that metadata is stored by prefix, so part of the `SetIPs` would need to identify the delta in ip set and apply the removal. Maybe this was implied by the proposal, just calling it out.

> The selector determines the set of relevant identities

Related to this, the ipcache does already have logic to inform the selectorcache when new identities are updated. It doesn't have the specific context about which particular selectors may be impacted by the identity allocation though, so I believe this means it just has to go through all the selectors and apply them to the new identity in order to update the selectorcache. On the other hand from the DNS proxy -> FQDN subsystem the selector is already known, so this proposal suggesting the selector should be responsible for this step feels like it should be efficient. Keeping this management in fqdn subsystem can make it much easier to manage the corresponding identities rather than relying on the ipcache, at the expense of splitting this logic across different parts of the codebase. On the other hand, with ipcache doing the async allocation, there needs to be a notification mechanism anyway, so we might consider just pushing this responsibility purely to the ipcache (?)

>  We need to build in a way to wait for identities to be made available. Additionally, we should not wait when desired identities are already fulfilled. 

Roughly speaking I figured we could leverage the `aux` parameter to pass in either some direct synchronization mechanism such as channel/waitgroup/etc, or maybe a pointer for an "ipcache revision" number and then the caller could call something like `ipcache.WaitForRevision(r)` which would return after revision `r` has been "reached", ie the set of requested ipcache changes have been fully plumbed (presumably both to the ipcache itself and also into the policymaps of the endpoints? TBD).

**Comment by bimmlerd** [comment]
Not sure how helpful it is, but during recent customer issues related to this, I've thrown together this diagram of the flow of control per DNS request: https://drive.google.com/file/d/1WSVnvWygoNltNZa-vLWM9KhVwHfyVxOm/view?usp=drive_link (it's a largeish svg, GH preview couldn't handle it).

One thing I didn't see mentioned in the proposal is the split of per-EP `DNSHistory` and the global `NameManager`. The explanation in https://github.com/cilium/cilium/blob/f911b128f3dfaa54165ba81d20136a7d6b2dfd61/pkg/fqdn/doc.go might not be fully up to date anymore, but the gist of it still holds. Specifically, the 

```
// === Caching, Long-Lived Connections & Garbage Collection ===
....
//   - Keep a per-Endpoint cache that can be stored to disk and restored on
//     startup. These caches apply TTL expiration and limit the IP count per domain.
//   - Keep a global cache to combine all this DNS information and send it to the
//     policy system. This cache applies TTL but not per-domain limits.
//     This causes a DNS lookup in one endpoint to leak to another!
//   - Track live connections allowed by DNS policy and delay expiring that data
//     while the connection is open. If the policy itself is removed, however, the
//     connection is interrupted.
```

part is relevant. Expiration of DNS TTL only expires the IP name mapping from the per-EP cache, IIRC. Actual expiration happens via Conntrack GC once it's certain that no live connections exist.

I'm not sure I understand

> The TTLs run out, and some IPs are removed. The NameManager calls selector.SetIPs(name, nil) which causes the metadata to be removed.

To me, this doesn't seem to work for S3. In the S3 case, you can expect all CoreDNS pods to have a different set of short-lived IPs for `s3.amazonaws.com`. Thus, it seems we'd need to at least keep track of which IPs for `name` expired, and remove those, not nil the whole selector. Also, this shouldn't happen as soon as TTLs of the DNS records run out, but only once the relevant DNSZombies are no longer alive.

**Comment by squeed** [comment]
Thanks all for the feedback. I realized there is potentially a better approach: to put identity management squarely on the shoulders of the NameManager. Then, a FQDN selector could just becomes a "bag" of `cidr:xxxx/32` labels.

This matches well with the existing flow, where the NameManager already manages all aspects of the DNS policy lifecycle.

Let me know what you think, and I'll start prototyping this.

**Comment by squeed** [comment]
I just realized there is a fundamental issue with using the asynchronous ipcache apis during startup: we will potentially block DNS responses for an arbitrarily long time while k8s caches are synchronized. I'm looking for a good potential solution to this.

**Comment by squeed** [comment]
@bimmlerd The plan is to change very little about the GC flow. Hopefully we can just centralize all identity management in the NameManager but keep the inputs (allocation, dns request, GC) the same.
