### ISSUE TITLE
CFP: move namespace watcher to cilium-operator

### ISSUE THREAD

**Issue by yingnanzhang666** [cilium/cilium#29127]
## Cilium Feature Proposal
        
Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

On the large scale cluster(several thousands of nodes), we have tens of thousands namespaces for customers. The raw data for one list all namespaces request is almost 200MB.
It's a huge stress for APIServer to suffer from the "listing" from cilium-agent.
Add the flowschema to ratelimit cilium-agent, it will cause cilium-agent taking a very long time to get ready.

To support the large scale clusters, we want to reduce the api loads from cilium-agent as much as possible.

**Describe the feature you'd like**

namespace watcher in cilium-agent is in charge of triggering the securitylabel changes of ciliumendpoint when namespace labels changed.
The idea is to move the namespace watcher from cilium-agent to cilium-operator.

cilium-operator watches all the namespaces, when it receives the update event, compare the namespace's labels and the securitylabels of the ciliumendpoints in this namespace, if there are changes, add an annotation such as "cilium.io/reconcile" to the ciliumendpoints.
cilium-agent watches the ciliumendpoints, when it receives the update event, and the new obj has the annotation "cilium.io/reconcile", cilium-agent will trigger the securitylabel changes of the ciliumendpoint. Then it get the namespace via GET api call instead of local cache to generate the new labels.

```mermaid
sequenceDiagram
    participant client
    participant apiserver
    participant cilium-operator
    participant cilium-agent
    cilium-operator->>apiserver: watch all namespaces
    cilium-agent->>apiserver: watch local ciliumendpoints
    client->>apiserver: update namespace labels
    apiserver-->>cilium-operator: namespace update event
    cilium-operator->>apiserver: patch ciliumendpoints in this namespace with reconcile annotation
    apiserver-->>cilium-agent: ciliumendpoint update event
    cilium-agent->>cilium-agent: trigger security labels reconcile
    cilium-agent->>apiserver: send GET ns request to fetch namespace meta labels
    cilium-agent->>cilium-agent: reconcile security labels of ciliumendpoint
    cilium-agent->>apiserver: remove reconcile annotation from ciliumendpoint
    cilium-agent->>apiserver: create new ciliumidentiy & update ciliumendpoint
```

**Comment by yingnanzhang666** [comment]
@julianwiedmann Do we have the community meeting next week, since it's near the Thanksgiving Day?
Can we initialize the discuss on slack or here first? Do you have any concern about this idea to move the namespace watcher to operator?

**Comment by yingnanzhang666** [comment]
Another consideration is that:
cilium-agent only watch each single namespaces for the pods on this node.
Such as there're only ns1/pod1, ns2/pod2 on node1, then cilium-agent on node1 will only register 2 watchers, to watch each ns with fieldSelector=metadata.name=<nsname>. Which is like the behavior of kubelet to watch confimaps and secrets mounted by the pods running on its node.
In this way, there will be a lot of watchers registered.

**Comment by marseel** [comment]
I have some clarifying questions to better understand your scale and the issues that you are facing, I just want to make sure that any of the proposed ideas would solve your case.

1. "The raw data for one list of all namespaces requests is almost 200MB." This seems super high, usually, namespaces are really light objects, like a few hundred bytes. Do you have some complex structure of your namespace objects/many labels etc?
2. You mentioned that you are running 1.23. What specific version? List call latency was significantly improved in version k8s v1.23.11
3. How many pods do you run in your cluster? Do you see a similar issue with CiliumEndpoint CRD lists? It seems to me counterintuitive that namespaces are the only issue, I would expect that you are running a lot of Pods and their corresponding CiliumEndpoints should also probably cause list-related issues :thinking:
4. 
> It's a huge stress for APIServer to suffer from the "listing" from cilium-agent.
Add the flowschema to ratelimit cilium-agent, it will cause cilium-agent taking a very long time to get ready. 

I understand that k8s control plane was suffering without flowschema and with flowschema agent was taking a lot of time to get ready. I am wondering, maybe giving more concurrency shares to the corresponding Priority Level would help? It's always a tradeoff between cpu/memory usage of k8s control plane and how long it takes Cilium to get ready.

5. During Cilium community meeting, you mentioned that this issue usually happens when doing a rolling upgrade of k8s control plane. If that's the case, I think it would be worth creating an issue for k8s itself. Efficient watch resumption [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1904-efficient-watch-resumption#summary) which is beta since 1.21 (so you probably have it enabled) and stable in 1.24, should prevent clients from doing list request when switching between k8s control plane nodes.

6. Do you mind sharing what setup do you have for your k8s control plane nodes? I would be interested in how many control planes you are running and what are the machine sizes and general numbers of objects within your cluster. 
7. Do you change namespace labels? I am asking, because if not, maybe it would make sense to drop informer altogether and just do a single get of namespace and do not react to namespace changes.


Going back to your proposals:
- Moving watcher to operator makes sense, but I would be worried about higher churn on CiliumEndpoint CRD - basically 2 events per CEP CRD whenever namespace label changes for all pods within namespaces - previously I've seen issues with it even on a smaller scale. Also, time to converge would be probably significant after changing the labels of the namespace that has many pods.
- Watching only single namespaces per pod running seems like a better solution. I'm not sure though how many pods you are running, but assuming it is in 100s of thousands, these additional watchers might also matter and cause issues for k8s control plane.
- Alternatively, If you are not changing namespace labels then the simplest solution would be to do a single get of the namespace when needed and never open watch, so while cilium would not react to namespaces label changes, it would definitely help with your k8s control plane. This wouldn't suffer from additional 100s of thousands of opened watches.

All these proposals assume though that namespace lists are the only issue, but my feeling is that we would see a similar issue with CiliumEndpoint CRDs lists for example.

**Comment by marseel** [comment]
> We are using 1.23.6. I believe the improvement you mentioned is "gzip compression switched from level 4 to level 1 to improve large list call latencies in exchange for higher network bandwidth usage (10-50% higher)". We can upgrade or cherry-pick this change to leverage the benefit.

Yes, that's the exact improvement I had in mind. It improves latency by x3 for list requests IIRC. There is also an option to disable compression, which gives additional x2 improvement, but it makes sense only if your network throughput allows it. 


> Add the label to indicate the nodeName or well-known on ciliumendpoint when creating the ciliumendpoint. And change the ciliumendpoint watcher to init with label selector.

This unfortunately won't bring much benefit - k8s control plane does not have indexes so with each list requests it will still be processing all objects to return a few. Definitely, it will be some improvement, but probably not major from k8s control plane point of view.   

> But client-go only treat ConnectionRefused case to re-watch, others will trigger relisting. Anyway, this is one thing I will take effort to fix in k8s side.

Yea, makes sense. If you want to feel free to join the k8s [sig-scalability meeting](https://github.com/kubernetes/community/blob/master/sig-scalability/README.md#meetings) to get some more attention to this issue. 


On a side note, you will definitely be interested in KEP-3157 as it will drastically reduce k8s control plane load with respect to list requests.

**Comment by yingnanzhang666** [comment]
>This unfortunately won't bring much benefit - k8s control plane does not have indexes so with each list requests it will still be processing all objects to return a few. Definitely, it will be some improvement, but probably not major from k8s control plane point of view.

From the observation of production env, the cost(cpu/memory/latency) of encoding is much larger than filter for large listing. I believe even there's no indexer for label of CRD, this way will improve the cep listing call. And I am thinking can we support to define label indexer for CRD?

**Comment by yingnanzhang666** [comment]
Back to the three proposals: I wonder whether upstream will accept any of them?

**Comment by linsun** [comment]
Hi there! I wanted to mention Rob proposed xDS adapter for Cilium which may be relevant here, PTAL: https://docs.google.com/document/d/1U4pO_dTaHERKOtrneNA8njW19HSVbq3sBM3x8an4878/edit#heading=h.y3v1ksm0ev6r
