### ISSUE TITLE
toFqdn policies suddenly fails to allow traffic

### ISSUE THREAD

**Issue by eegseth** [cilium/cilium#29322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Traffic destined for outside the cluster, allowed by toFqdn policies, experiences sudden failures on specific nodes. 
This problem occurs intermittently on one or more nodes, even though the traffic was forwarded correctly for extended periods (hours to days). 
Restarting the Cilium pod associated with the daemonset on affected nodes resolves the issue temporarily, and traffic resumes normal flow until the problem reoccurs.

### Cilium Version

1.14.1

### Kernel Version

5.15.0-1049-azure / AKSUbuntu-2204gen2containerd-202307.27.0

### Kubernetes Version

1.27.3 (AKS)

### Relevant log output

```shell
* When examining dropped flows, the ID of the destination FQDN is frequently set to 'WORLD.'
* Anomalies in ID tables:
	* Example: podX (ID 1300) is blocked when trying to reach google.com (ID 1672000) (should be allowed by toFqdn policy).
	* ID 1672000 is found in the output of cilium bpf ipcache list.
	* ID 1300 has an entry for google.com in the output of cilium fqdn cache list (Source 'lookup').
	* google.com (ID 1672000) has no entry in cilium identity list.
```

### Anything else?
Not sure if relevant, but we observe some dns timeouts:

DNS timeouts towards CoreDNS are observed:
'Nov  3 13:05:38.786: 10.0.5.101 (host) <> kube-system/coredns-6b8c654c-q67hr (ID:299) Unknown ICMPv4 code DROPPED (ICMPv4 DestinationUnreachable(Port))'

DNS timeouts towards the dnsproxy:
2023-11-03T13:05:34.783109052Z level=warning msg="Timeout waiting for response to forwarded proxied DNS lookup" DNSRequestID=39991 dnsName=google.com. endpointID=1319 error="read udp 10.0.5.101:43391->10.0.4.143:53: i/o timeout" identity=62324 ipAddr="10.0.5.73:60912" subsys=fqdn/dnsproxy

DNS timeouts from codeDns to upstream dns (azure-firewall)
[ERROR] plugin/errors: 2 google.com. SRV: read udp 10.0.4.143:53108->10.166.131.196:53: i/o timeout

**However, the timeouts from coreDns to upstream, does not correlate with the other timeouts described.**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmb** [comment]
Can you try updating to the latest v1.14 point release please?

**Comment by eegseth** [comment]
We tried, but rolled back due to #29175

**Comment by lmb** [comment]
Ah bummer, sorry to hear that. Can you try a pre-release so see whether the issue reproduces. AFAIK there's been quite a bit of bug fixing going on with the FQDN proxy.

In the meantime I'll see whether this rings a bell with the team.

**Comment by ebc92** [comment]
Hi, endre's team member checking in here. 

I'll see what we can do in terms of providing a sysdump, but it would likely have to be a scrubbed due to security concerns. Is there any parts of the sysdump that is of particular interest?

I will also see if i can find a suitable environment to test the 1.15 prerelease in, however it might take some time to validate as we are having a hard time reproducing the issue.

In terms of helm values, we're running the stock 1.14.1 chart with the following arguments:
```
    helm upgrade cilium cilium/cilium `
		--version $ciliumVersion `
		--namespace kube-system `
		--set aksbyocni.enabled=true `
		--set nodeinit.enabled=true `
		--set cluster.name=$EnvironmentAlias
		--set hubble.ui.enabled=true
		--set hubble.relay.enabled=true
		--set hubble.metrics.enabled="{dns,drop,tcp,flow,icmp,http}" `
		--set prometheus.enabled=true `
		--set operator.prometheus.enabled=true `
		--set kubeProxyReplacement=strict `
		--set k8sServiceHost=$clusterFqdn `
		--set k8sServicePort=443 `
		--set dnsProxy.minTtl=3600 `
		--install
```

As mentioned in the original post, when the issue occurs we have made an interesting observation where the destination/FQDN's  security ID (as reported by hubble) seems to be missing from the underlying cilium-agents local identity cache (when calling cilium identity list). 

Similarly, for normal outbound traffic this local identity always seems to be present. Are you able to comment on whether this is normal or potentially indicative of the underlying issue?

**Comment by eegseth** [comment]
Just confirming @ebc92's comment, so the need-more-info label is removed.

**Comment by eegseth** [comment]
The bug just occurred in one of our test clusters. We had debug-logging enabled and took a cilium sysdump. Will send it in a DM to @lmb

**Comment by ebc92** [comment]
@lmb we have been running 1.15.0-pre2 in one of our test environments but we are still seeing the same behavior here.
In regards to debugging the intermittent issues we are experiencing we are unfortunately unable to upload a sysdump at this time.

We can however provide some logs to back up our previously mentioned observations, as well as supply some additional details along with thoughts on possible root cause and angle for reproducing the issue.

_disclaimer: some information removed for brevity, some obscured for security_

## Policy and denied traffic
The policy itself is implemented as follows:
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
name: app001-np
namespace: jolly
spec:
  endpointSelector:
    matchLabels:
      app: app001
  egress:
  - toFQDNs:
    - matchName: config.com
    toPorts:
    - ports:
    - port: "443"
      protocol: TCP
```
However, using hubble, intermittent drops can be observed for traffic that is expected to be forwarded.
```
"flow": {
    "destination": {"identity": 16777304},
    "destination_names": ["config.com"],
    "drop_reason": 133,
    "drop_reason_desc": "POLICY_DENIED",
    "event_type": {"type": 5},
    "IP": {"destination": "13.128.128.76", "ipVersion": "IPv4", "source": "10.0.8.223"},
    "l4": {"TCP": {"destination_port": 443, "flags": {"SYN": true}, "source_port": 37576}},
    "node_name": "j/aks-systempool-12345678-vmss000006",
    "source":
        {
        "ID": 1892,
        "identity": 3967,
        "labels":
            [
            "k8s:app=app001",
            "k8s:io.cilium.k8s.namespace.labels.name=jolly",
            "k8s:io.kubernetes.pod.namespace=jolly"
            ],
        "namespace": "jolly",
        "pod_name": "app001-bc79cd79b-nxz48",
    }
    "Summary": "TCP Flags: SYN",
    "time": "2023-11-07T08:10:36.274233323Z",
    "traffic_direction": "EGRESS",
    "Type": "L3_L4",
    "uuid": "cf8f2d15-c3d5-4ec9-8285-4927941d0d0d",
    "verdict": "DROPPED" 
}
```
Simultaneously an almost identical flow entry can be found, where only the fields 'event_type' and 'uuid' differs.
```
"event_type": {"sub_type": 133, "type": 1}, "uuid": "5bf32889-835d-492b-8497-73205ef20bb7"
```

## Local identity cache and ipcache state
When inspecting the local identity cache (using cilium identity list), the security identity referenced in _flow.destination.identity_ **cannot be found.** Additionally, the following agent log messages from subsys=hubble can be observed:
```
"level=debug msg="failed to resolve identity" error="identity 16777304 not found"
```

However, the IP address referenced in _flow.ip.destination_ can be found using a different security identity:
```
ID         LABELS
16778513   cidr:13.128.128.76/32
           reserved:world
```

Additionally, the security identity referenced by the flow can be found in the ipcache:
```
IP PREFIX/ADDRESS    IDENTITY
13.128.128.76/32     identity=16777304 encryptkey=0 tunnelendpoint=0.0.0.0
```
Entries associated with security identity 16778513 _cannot_ be found in the ipcache.

## Policy map state
When inspecting the policy map for the referenced endpoint _flow.source.ID,_ an allow rule can be found for this identity:
```
Endpoint ID: 1892
Path: /sys/fs/bpf/tc/globals/cilium_policy_01892

POLICY   DIRECTION   IDENTITY   PORT/PROTO   PROXY PORT   AUTH TYPE   BYTES      PACKETS   PREFIX
Allow    Egress      16778513   443/TCP      NONE         disabled    0          0         24          
```


## Failed ipcache operations on agent
When these intermittent failures occurs, they can usually be observed on multiple, but not all nodes in the cluster.
The following chart shows cilium drops as observed by hubble over time, by node:
![drops](https://github.com/cilium/cilium/assets/7307236/49d7f744-c2ae-4e6f-b306-8ad25173fea3)


On the nodes experiencing failures, the following error messages can be found in the cilium cluster agent logs _practically simultaneously._
```
2023-11-06T20:25:40.438053830Z level=error msg="Failed to replace ipcache entry with new identity after label removal. Traffic may be disrupted." error="unable to overwrite source \"custom-resource\" with source \"k8s\"" identity=16777217 ipAddr=127.0.0.1/32 subsys=ipcache
2023-11-06T20:25:40.438085030Z level=error msg="Failed to replace ipcache entry with new identity after label removal. Traffic may be disrupted." error="unable to overwrite source \"custom-resource\" with source \"k8s\"" identity=16777219 ipAddr=10.0.0.1/32 subsys=ipcache
```
Cilium agent logs on nodes that are not experiencing failures are _not_ logging these error messages.

We can also see elevated values for metric cilium_ipcache_errors_total error="cannot_overwrite_by_source" **type="delete"** on affected nodes.

| Node | Count | Unexpected drops observed |
| --- | --- | --- |
| vmss00000j | 142 | Yes |
| vmss000006 | 146 | Yes |
| vmss000001 | 194 | Yes |
| vmss000007 | 1 | No | 
| vmss000000 | 1 | No |
| vmss00000i | 1 | No |
| vmss000004 | 1 | No | 
| vmss00000a | 1 | No |

Overlaying observed (unexpected) drops from hubble with metrics for ipcache error "cannot_overwrite_by_source" of type="delete" confirms that there is a strong correlation here.
![MicrosoftTeams-image (1)](https://github.com/cilium/cilium/assets/7307236/fc78a564-ac5f-427d-9305-f26b5b45adef)

Metric cilium_ipcache_errors_total error="cannot_overwrite_by_source" **type="upsert"** also seem somewhat high on certain nodes, but this does not correlate with nodes experiencing drops.
| Node | Count |
| --- | --- |
| vmss00000j | 2122 |
| vmss000006 | 549 |
| vmss000001 | 1958 |
| vmss000007 | 396 |
| vmss000000 | 76 |
| vmss00000i | 1309 |
| vmss000004 | 165 |
| vmss00000a | 173 |

## Closing thoughts
We suspect that failed ipcache operations on the agent is resulting in inconsistencies between ipcache map and policy/identity map, which in turn results in unexpectedly dropped traffic.
If our suspicions are correct, it should likely be possible to reproduce our issue by manipulating ipcache state or availability.

Additionally, more recently we have also observed the same behavior (drops, identity/ipcache inconsistency) on traffic that should have been allowed by a toCIDRSet rule (on replicaset X) and a toFQDN rule (on replicaset Y). In other terms, we are seeing some signs that indicate that this might not be isolated to toFQDN allowed traffic.

toFQDN rules being affected does seem predominant, though that could be because this is the type of policy we typically leverage.

**Comment by eegseth** [comment]
Sure, we will test it. Thanks for the feedback 👍

**Comment by eegseth** [comment]
@squeed 
We have been running 1.15.0-pre.3 since the beginning of December, and so far it looks good. No more drops in cilium 👍 
Thanks for the help.

Closing this bug now.
