### ISSUE TITLE
CI: ci-awscni & ci-eks - AlreadyExistsException: Stack [eksctl-cilium-cilium-<runid>-1-cluster] already exists

### ISSUE THREAD

**Issue by mhofstetter** [cilium/cilium#29426]
## CI failure

Creating the AWS EKS cluster during the tests `ci-awscni` & `ci-eks` fails with the following failiure:

```
2023-11-28 00:49:50 [ℹ]  building cluster stack "eksctl-cilium-cilium-7012612170-1-cluster"
Error: failed to create cluster "cilium-cilium-7012612170-1"
2023-11-28 00:49:51 [!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
2023-11-28 00:49:51 [ℹ]  to cleanup resources, run 'eksctl delete cluster --region=eu-central-1 --name=cilium-cilium-7012612170-1'
2023-11-28 00:49:51 [✖]  creating CloudFormation stack "eksctl-cilium-cilium-7012612170-1-cluster": operation error CloudFormation: CreateStack, https response error StatusCode: 400, RequestID: 02c84e8b-0c98-449a-8cd6-7c5dcdfadfe9, AlreadyExistsException: Stack [eksctl-cilium-cilium-7012612170-1-cluster] already exists
Error: Process completed with exit code 1.
```

e.g. https://github.com/cilium/cilium/actions/runs/7012612170/job/19077439535

The issue is that the name with the pattern `${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}-${{ github.run_attempt }}` isn't unique enough in cases where a testrun deploys a cluster in the same region twice. This is the case for `eu-central-1` since #29004 

https://github.com/cilium/cilium/blob/main/.github/workflows/conformance-aws-cni.yaml#L54

## Proposal

a) use a different region -> fixed with https://github.com/cilium/cilium/pull/29427
b) use a unique identifier for the name of the cluster to avoid name clashes

**Comment by mhofstetter** [comment]
Reopen, as #29427 only addressed the quick-fix

**Comment by nbusseneau** [comment]
Thanks for the quick fix, I don't think anything else is needed, this was indeed a copy/paste error in the region configuration but the name pattern should otherwise be unique thanks to `run_id` which is a unique identifier for each workflow run :)

**Comment by mhofstetter** [comment]
> Thanks for the quick fix, I don't think anything else is needed, this was indeed a copy/paste error in the region configuration but the name pattern should otherwise be unique thanks to `run_id` which is a unique identifier for each workflow run :)

you're welcome! yes it is unique as long as a workflow run only deploys each combination of the matrix into it's own region. Kind of a workaround :/

**Comment by nbusseneau** [comment]
Yes, that's why it's set up like this right now, it was split over multiple regions when we decided to implement testing over multiple regions in scheduled runs, while PR runs only test in the latest region. The nice thing with this naming scheme is that it's easy to track down, given a cluster name, from which workflow run it comes from, and while it does feel like a workaround the nice thing about splitting scheduled runs over multiple regions is that we also split "spot instances availability" risk, since we use specific machine types to reduce costs and it sometimes happens spot capacity in a region is tight. Overall I'm not perfectly satisfied with the setup but it works okay so I haven't bothered :D
