### ISSUE TITLE
Enable toK8sService for all services with external endpoints

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#2951]
Currently, `toK8sService` is limited to headless services, we can relax the selection and translate to toCIDR rules for all services with Endpoints that have an IP outside of the cluster range.

**Comment by nebril** [comment]
@tgraf is there a sensible way to create such service without specifying spec.ClusterIP as "none"?

What would be the use case for service with not-"none" ClusterIP (so endpoints are created by k8s automatically based on service selectors) with additional user-created endpoints pointing to external IP?

**Comment by tgraf** [comment]
Create a ClusterIP and have k8s allocate a service IP, omit the selector and create an Endpoints resource to define the backends.

**Comment by nebril** [comment]
Seems like current implementation can be switched to neglect whether the service is headless, since the only thing we are interested in is - does the service have a selector. If it has one, its endpoints will point to in-cluster addresses, which won't work with ToCIDR translation, if not - most probably user will add endpoints to external services.

Service being headless doesn't matter here AFAIU.
