### ISSUE TITLE
The CPU consumption of Cilium agent increases with the increase of business traffic

### ISSUE THREAD

**Issue by thfsir** [cilium/cilium#29526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The CPU of Cilium agent and Cilium envoy will increase as the business traffic of node nodes increases. When I pressure a flow rate of 30000+/min to a certain node, the CPU of the Cilium agent can reach 1100mCPU.

### Cilium Version

1.13.6

### Kernel Version

5.4 or 5.18

### Kubernetes Version

1.20.4

### Sysdump

[cilium-sysdump-20231201.zip](https://github.com/cilium/cilium/files/13521839/cilium-sysdump-20231201.zip)
![$_5%NB}TJYZ6R`32BOL{O90](https://github.com/cilium/cilium/assets/135086109/f816379e-0cd9-40d3-8461-f3b06cb86ec9)

### Relevant log output

```shell
no
```

### Anything else?

no

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aanm** [comment]
Thank you for opening the GH issue, try to run with the helm option `--set hubble.enabled=false` to see if the issue persists.

**Comment by tclxthf39645** [comment]
Thank you for your reply. Turn off the hub and return CPU consumption to relatively normal values. Is there a way to optimize the CPU consumption caused by the functions related to Hubble and L7 proxy?

**Comment by tclxthf39645** [comment]
Thank you for your reply. 
1、Turn off the hubble and return CPU consumption to relatively normal values. Is there a way to optimize the CPU consumption caused by the functions related to Hubble and L7 proxy?
2、Set -- set hub. enabled=true, collect  metrics, enable L7 proxy, and how much CPU does the cilium agent need to consume? Is there any reference data for this?




Thank you for opening the GH issue, try to run with the helm option --set hubble.enabled=false to see if the issue persists.
―

**Comment by ti-mo** [comment]
> Is there a way to optimize the CPU consumption caused by the functions related to Hubble and L7 proxy?

That depends on what you mean by 'optimize', but Hubble's design relies on packet metadata being plumbed to userspace, which is inherently expensive to handle. Currently, there's no rate limiting for these messages on the bpf side, so each packet will result in a message.
