### ISSUE TITLE
examples/getting_started not found

### ISSUE THREAD

**Issue by xcasas** [cilium/cilium#29559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm trying to build Cilium on docker using https://cilium-genbit.readthedocs.io/en/latest/gettingstarted/docker.html but the example script is not there anymore.
Is it possible to run Cilium directly in docker? Without Kubernettes.

### Cilium Version

pull from github

### Kernel Version

0

### Kubernetes Version

0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ti-mo** [comment]
@kasasxav This part of the documentation is indeed severely out of date. :slightly_smiling_face: Thanks for bringing that to our attention. You're mentioning 'building' Cilium on Docker, but I assume you're trying to run an existing Cilium release image on a standalone Docker node, correct?

I'm not aware of anyone running Cilium this way as it would be impractical to say the least. We definitely don't test Cilium in such a configuration. There's always https://netreap.io if you're looking to use Nomad instead of Kubernetes. I'll see if we can get that piece of documentation updated or removed in the meantime.

**Comment by kasasxav** [comment]
Hi @ti-mo,

Yes exactly, we have different dockers running on different sites and we would like to use Cilium for the networking between them and adding policies as well. But we don't use Kubernetes, I know before there use to be the cilium-net docker plugin but it seems it's not available anymore.

I will take a look at nomad and netreap.

Best,
Xavier.

**Comment by ti-mo** [comment]
Yep, running standalone on Docker hasn't been officially supported for a long time. Someone pointed me to the fact that you're linking to https://cilium-genbit.readthedocs.io, which is a really old fork of a contributor. This page is long gone in the main branch. :wink:

I'll close this out and ask them to take down the outdated copy of the docs. It's still ranking pretty highly when searching for `cilium docker getting started`, since the official docs no longer explicitly mention this topic. Thanks again for flagging this!
