### ISSUE TITLE
cilium do not gc local endpoint if pod was forced delete and CNI do not called

### ISSUE THREAD

**Issue by fzu-huang** [cilium/cilium#29647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This issue arises from a "special behavior" in containerd.

We know that cilium has two ways to clean up local endpoints:
1. By performing a CNI delete operation, calling the DeleteEndpoint API.
2. When the local pod's network interface (host veth) is forcibly deleted, such as during node restart. In this case, cilium itself performs a garbage collection (gc) check every 5 minutes to clean up.

However, I have encountered a specific leakage scenario. When using containerd as the container runtime, deleting a pod fails because a special log agent occupies the container's rootfs directory handle. Unlike Docker, containerd does not skip this failed umount operation. As a result, the pod remains stuck in the "terminating" state, and containerd does not even invoke the CNI delete operation, nor does it clean up the sandbox container.

This bypasses the two methods mentioned above for cilium to clean up endpoints:
1. The CNI delete operation is not triggered.
2. The pod's host veth interface remains, and cilium's gc check does not consider this endpoint for garbage collection.

You might think this is a containerd issue. However, when this problem occurs, users instinctively force delete the terminating pods. At this point, the bug in containerd and the leaked endpoints would be ignored, potentially leading to more severe issues in the future.

I suggest that when Cilium performs the gc check, it could attempt to retrieve the corresponding pod from the local k8sCache and validate it. This way, we can ensure that cilium keeps the data clean on the node after the pod is forcefully deleted, regardless of any issues with kubelet or containerd during that time.

### Cilium Version

1.12.3

### Kernel Version

 5.4.119-19.0009.37

### Kubernetes Version

1.22.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ti-mo** [comment]
@squeed MBOI?

**Comment by squeed** [comment]
We deviate from the kubernetes CRI + PodSandbox lifecycle at our peril.

Given that, as far as we know, this is still a valid PodSandbox with an online network namespace, we very much should not delete it. Especially since it is not immediately possible to tell the difference between a stale PodSandbox and one for which the Pod object merely hasn't yet appeared in our informer.

If you're using a custom container that breaks containerd deletion, that smells like a bug in your environment. Maybe containerd should be more willing to issue a CNI DEL in the scope of partial failures. But containerd's behavior, in this case, does not seem incorrect.

FYI, we have merged GC support in to CNI v1.1, and Cilium will likely support this. However, that still depends on containerd / cri-o being the source of truth for valid network namespaces.
