### ISSUE TITLE
Masquerade silently broken when BPF masquerade is enabled, but KPR is disabled

### ISSUE THREAD

**Issue by giorio94** [cilium/cilium#29663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

BPF masquerade requires KPR to be enabled, and Cilium currently [silently falls back to iptables masquerading](https://github.com/cilium/cilium/blob/d1128cf948979de7433385b2101a98404d99c64f/daemon/cmd/daemon.go#L776-L777) if it is enabled, but KPR is disabled (as well as in different other cases). 

> level=warning msg="Falling back to iptables-based masquerading." error="BPF
masquerade requires NodePort (--enable-node-port=\"true\")" subsys=daemon

Yet, recent changes broke this mechanism, leaving masquerade completely disabled in this case. Specifically, this occurred because the iptables cell got [modularized](https://github.com/cilium/cilium/pull/28746), directly retrieving the configuration through hive dependency injection. Which means that the `EnableBPFMasquerade` value change is never taken into account by that module, as it acts on a copy. From a quick look, it seems that egress gateway may be affected as well, as it also [accesses that field](https://github.com/cilium/cilium/blob/d1128cf948979de7433385b2101a98404d99c64f/pkg/egressgateway/manager.go#L193-L195) through the injected copy. 

This issue is strongly related to the approach to handle startup problems (https://github.com/cilium/cilium/issues/29169). The easy solution here would be to bail out loudly if the given combination is impossible (e.g., BPF masquerade + KPR disabled), instead of falling back silently. That would also match my personal expectation as user, given that I explicitly requested that feature to be enabled. OTOH, changing this behavior (if there's consensus) would possibly be a breaking change. 

Other configuration options which are modified at runtime may be affected as well.

### Cilium Version

Tip of main (d1128cf94897). Stable versions are not affected.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giorio94** [comment]
I've marked this issue as release blocker given that it is a regression from v1.14.

**Comment by pippolo84** [comment]
> The easy solution here would be to bail out loudly if the given combination is impossible (e.g., BPF masquerade + KPR disabled), instead of falling back silently. That would also match my personal expectation as user, given that I explicitly requested that feature to be enabled. OTOH, changing this behavior (if there's consensus) would possibly be a breaking change.

I'm in favor of this solution, as it seems the most natural to me.

Alternatively, it is possible to change the way we build the cell config to store a reference to the global option (or global option helper) so that runtime changes made elsewhere will be visible. For the iptables cell this is pretty straightforward, as it means returning to the previous model. But it might not be in many other cases.
Generally speaking, this sounds like adding the ability to reconcile the cell behavior following runtime config changes, and I think it'd be better to finalize the discussion in https://github.com/cilium/cilium/pull/28746 first and try to come up with some general policy (and maybe some guidelines to implement that).

So, again, I'd prefer to go with the "bail out loudly" solution, and avoid anything specific for the iptables cell only.

**Comment by giorio94** [comment]
> Alternatively, it is possible to change the way we build the cell config to store a reference to the global option (or global option helper) so that runtime changes made elsewhere will be visible.

This sounds pretty risky in terms of possible race conditions to me, as depending on when the option gets retrieved we may then get different values. IMO, one of the biggest advantages of hive is that removes the need of reasoning about all these possible ordering issues.

**Comment by pippolo84** [comment]
Let's open a PR to fix it, maybe with an additional upgrade note to highlight the change from v1.14. :+1:
