### ISSUE TITLE
Ambiguos command line options.

### ISSUE THREAD

**Issue by gaalw** [cilium/cilium#29764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello! 

I used many times the commands:

```
cilium install --set ipam.mode=kubernetes,k8sServiceHost=127.0.0.1
cilium install --set ipam.mode=kubernetes --set k8sServiceHost=127.0.0.1
```

and they worked fine for me.

Right now I found that when running them - no errors are displayed, but for some reason cilium CLI does not recognise k8sServiceHost substituting the host ip.

Now I need to use command:

```
cilium install --set ipam.mode=kubernetes --set-string k8sServiceHost=127.0.0.1
```

I want to emphasise that there is no good and understandable difference why we need to use for some values `--set` and for others `--set-string`. From my POV they are just "strings".

so...

1. As a DevOps engineer I want to get the error message directly stating that I am using and improper `--set` argument for the helm value
2. As a DevOps engineer I'd prefer to have one consistent way to set up all helm values on command line.

### Cilium Version

```
cilium version
cilium-cli: v0.15.14 compiled with go1.21.4 on linux/amd64
cilium image (default): v1.14.2
cilium image (stable): v1.14.4
cilium image (running): 1.14.2
```

### Kernel Version

```
Linux ubuntu-standard-4-8-60gb 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by squeed** [comment]
I agree the distinction between `--set` and `--set-string` is awkward. It is a detail of the underlying helm installer "leaking out".

This is because `helm install` **also** exposes both `--set` and `--set-string` flags. It does this because `--set key=5` will treat `key` as having an integer value. This may not be what you want, so you can override with `--set-string`.

I don't expect us to change this; `cilium install` is quite open in being a thin wrapper around Helm. If you are automating cluster creation, it may make sense to create a `values.yaml` containing the parameters you care about. `cilium install` will fill in sane defaults for unspecified parameters.
