### ISSUE TITLE
Add warning to /latest docs that they document main branch, not released versions

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#29969]
If you browse to https://docs.cilium.io/en/latest/, there is no indication that these are developer-focused docs to be able to validate how the tip of main looks. It's easy for users to confuse this with the documentation for stable releases (at https://docs.cilium.io/en/stable/).

Ideally there would be a clear warning on /latest docs pages that these docs apply only for development releases and may not work with older releases. Similar to how older stable release docs point out that there is a newer release.

**Comment by SD-13** [comment]
I would like to work on this!

**Comment by joestringer** [comment]
Awesome! Feel free to post a PR and include the text `Fixes: #29969` in the PR description.

**Comment by Darshan174** [comment]
Hey @joestringer, I'd like to work on this...

**Comment by qmonnet** [comment]
It looks like the banners for older branches have disappeared (again), I only see one for `v1.11`, none for `v1.12`, `v1.13`, `v1.14`.

We've been using an extension to handle the banners on older branches (`versionwarning.extension` in `conf.py`), I'm not sure why it's not working on 1.12-1.14. If we manage to fix it, then it probably becomes trivial to [customise the message for `latest`](https://sphinx-version-warning.readthedocs.io/en/latest/configuration.html#confval-versionwarning_messages).

I note that ReadTheDocs [claims to have the feature we want](https://docs.readthedocs.io/en/stable/versions.html#version-warning), both for older branches _and_ for `latest`. Apparently this can be enabled via the new dashboard (not sure there's an option for the `.readthedocs.yaml` yet. @joestringer, should we try using it?

Cc @shivam-Purohit

**Comment by qmonnet** [comment]
@aanm So you mean we're currently blocked for using the banner implemented by ReadTheDocs, because it's currently showing up on the `stable` version of the docs as well, and that the best way to contribute here would be for someone to push https://github.com/readthedocs/addons/issues/132 forward, am I understanding correctly?

**Comment by aanm** [comment]
> @aanm So you mean we're currently blocked for using the banner implemented by ReadTheDocs, because it's currently showing up on the `stable` version of the docs as well, and that the best way to contribute here would be for someone to push [readthedocs/addons#132](https://github.com/readthedocs/addons/issues/132) forward, am I understanding correctly?

:100: Correct!

**Comment by joestringer** [comment]
@humitos oh awesome, thanks for your work on that!

I've gone into https://app.readthedocs.org/dashboard/cilium/addons/edit/ and checked the box for "Enable addons". Should I expect the banner to appear after the next build or will we need to add some additional logic into our theme? It's not currently appearing at https://docs.cilium.io/en/latest/ .

**Comment by joestringer** [comment]
@humitos Hmm, actually after playing around with it, this seems to be breaking some other aspects of the rendering. It's a little hard to tell for sure which configurations we want since the settings seem to have some delay in applying. It may be that we need to do some additional customization of our theme to be compatible.

Right now, I'm seeing:

https://docs.cilium.io/en/latest/overview/intro/
- Good: Banner shows it's a development version
- Bad: Usually we have the flyout in the bottom left corner as part of the sidebar, but right now that's not displaying and instead there's a floating flyout for the version selector.
https://docs.cilium.io/en/stable/overview/intro/
- Good: No banner, as intended
- Bad: Same flyout issue
https://docs.cilium.io/en/v1.15/overview/intro/
- Bad: Flyout issue, also reports as a "maybe older" version. In practice stable and v1.15 are almost the same (stable is from the latest patch release, v1.15 is from the same branch).
https://docs.cilium.io/en/v1.14/overview/intro/
- Good: No flyout issue, but also no "maybe older" version banner. Maybe the new Addons aren't enabled for those builds yet?

**Comment by joestringer** [comment]
I think that probably we just want to have someone from Cilium side with some CSS fu to look into how the version flyout for the latest RTD Addons works and make sure it integrates with the theme. It's not a big issue to have v1.15 report that it "may" not be the newest version given that there's a stable version it can point to. After that it'll just be the question about whether the v1.14 version issue resolves itself or requires further action.

**Comment by joestringer** [comment]
I'll leave this as-is for a little while to give a chance for folks to see the current behaviour, but probably revert addons off afterwards until someone can look into the CSS.

**Comment by humitos** [comment]
Hi @joestringer 👋🏼 . I'm happy that you were able to give it a try to the new addons. If I'm understanding correctly, the main issue is that the flyout is now at the bottom right and it's _not as integrated with the theme as it was before_.

That integration is something we are deprecating[^1] because its implementation is too hacky and it has been causing us (but also users and theme maintainers) a lot of issues. So, we build the "the default" version for the flyout as a floating element at the bottom right. However, if theme authors or users want a more integrated feel with their documentation, they can do it themselves by using the data addons exposes via a Javascript event called `readthedocs-data-ready`.

We haven't written the documentation for this integration yet, but I've done it for our own Sphinx theme and you can take a look at the code in this pull request https://github.com/readthedocs/sphinx_rtd_theme/pull/1526/. In particular, the [`versions.js_t`](https://github.com/readthedocs/sphinx_rtd_theme/pull/1526/files#diff-9b3520a4bb4475f2476a6038f7c5c4b8fc66cc4aba38de59027a38dd05c52db6) file. Read the Docs documentation is already using that PR to build, and it's live at https://docs.readthedocs.io/en/stable/ in case you want see it in action.

Let me know if this information helps to move forward with addons or if you have any doubt.

[^1]: we plan to fully remove it in the following months and default all projects into the new addons.

**Comment by joestringer** [comment]
@humitos awesome, I appreciate the feedback. The information you've provided sounds like what we'd need to adjust for the new Addons. I don't personally work on the theme side of things but I'll reach out to folks in the community who have experience there and let them know about this thread so they can reach out if they have questions.
