### ISSUE TITLE
Nightly Tests: add test which tests scalability of policy updates

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3041]
When working in PR #2875 , I initially added code which upon receiving a new event from the key-value store (IP-identity mapping), a call to `daemon.TriggerPolicyUpdates` was made. This meant that whenever a new endpoint was launched or its identity changed, two events would be sent to the key-value store (one for IPv4 and one for IPv6). This added significantly more load upon the policy subsystem in Cilium. In the PR, I noticed some bizarre behavior, including deadlocks for the same endpoint trying to regenerate at the same time (which shouldn't happen), endpoints stuck in odd / incomplete states, etc. Add a test to the nightly test suite which tests the scalability of our policy subsystem from a goroutine to determine lurking issues.

**Comment by joestringer** [comment]
We've done some pretty deep work on the core policy engine since this was filed.

Concurrent regenerations should no longer be possible; endpoints in weird states hasn't been seen in a while AFAIK.

@aanm has had some thoughts recently on testing scalability, but I think it's already tracked outside this issue.

Not much value keeping this one open, closing.
