### ISSUE TITLE
Kubeadm - Cluster Mesh - Nodes not ready

### ISSUE THREAD

**Issue by SangeethKarunaratne** [cilium/cilium#30565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi All,
I would highly appreciate if someone can help me out
I have setup 2 clusters via kubeadm
```
kubeadm init --skip-phases=addon/kube-proxy --pod-network-cidr=10.41.0.0/16
kubeadm init --skip-phases=addon/kube-proxy --pod-network-cidr=10.42.0.0/16
```
Installed cilium CNI
```
helm install cilium cilium/cilium --version 1.14.5 \
 --namespace kube-system \
 --set l2announcements.enabled=true \
 --set k8sClientRateLimit.qps=5 \
 --set k8sClientRateLimit.burst=10 \
 --set kubeProxyReplacement=true \
 --set k8sServiceHost=10.120.84.50 \
 --set k8sServicePort=6443 \
 --set cluster.name=k8s-cluster-1 \
 --set cluster.id=1 \
 --set ipam.mode=kubernetes \
 --set ipv4NativeRoutingCIDR=10.41.0.0/16

helm install cilium cilium/cilium --version 1.14.5  \
  --namespace kube-system \
  --set l2announcements.enabled=true \
  --set k8sClientRateLimit.qps=5 \
  --set k8sClientRateLimit.burst=10 \
  --set kubeProxyReplacement=true \
  --set k8sServiceHost=10.130.84.50 \
  --set k8sServicePort=6443 \
  --set cluster.name=k8s-cluster-2 \
  --set cluster.id=2 \
  --set ipam.mode=kubernetes \
  --set ipv4NativeRoutingCIDR=10.42.0.0/16
```
Running cilium connectivity test got 45 tests passing and 18 tests skipped

I'm able to setup l2 advertisement, assign external ips and receive external traffic to each cluster
But when I mesh the clusters together via cilium clustermesh connect connection was successful in the command line response

```
Deployment clustermesh-apiserver is ready
 4/4 nodes are not connected to all clusters [min:0 / avg:0.0 / max:0]
```

And when checked for cilium clustermesh status
I keep getting the following msg and I do not have any leads on what the issue is, all pods are running without any errors or restart
```
Deployment clustermesh-apiserver is ready
 Waiting (0s) for clusters to be connected: 3 nodes are not ready
```
Can I know if I have missed anything? TIA

### Cilium Version

1.14.5

### Kernel Version

5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.6

### Sysdump
[cilium-sysdump-20240131-225924.zip](https://github.com/cilium/cilium/files/14179922/cilium-sysdump-20240131-225924.zip)

### Relevant log output

```shell
⚠️  Service type NodePort detected! Service may fail when nodes are removed from the cluster!
✅ Service "clustermesh-apiserver" of type "NodePort" found
✅ Cluster access information is available:
  - 10.130.84.50:32379
✅ Deployment clustermesh-apiserver is ready
⚠️  3/3 nodes are not connected to all clusters [min:0 / avg:0.0 / max:0]
🔌 Cluster Connections:
  - k8s-cluster-2: 3/3 configured, 0/3 connected
🔀 Global services: [ min:0 / avg:0.0 / max:0 ]
❌ 3 Errors:
  ❌ cilium-fsdc9 is not connected to cluster k8s-cluster-2: synchronization in progress for endpoints, identities, nodes
  ❌ cilium-fxmdr is not connected to cluster k8s-cluster-2: synchronization in progress for endpoints, identities, nodes
  ❌ cilium-wzt8l is not connected to cluster k8s-cluster-2: synchronization in progress for endpoints, identities, nodes
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lmb** [comment]
Can you provide a sysdump? Or even just grep for more error logs? The information you've provided so far is probably not enough to figure out what is going on.

**Comment by giorio94** [comment]
Thanks @SangeethKarunaratne for the detailed report.

I've checked the sysdump, and one possibility is that you hit the same bug mentioned in https://github.com/cilium/cilium/issues/24692. TL;DR; when KPR is enabled and a NodePort service configured with the same port exists in both meshed clusters, the traffic from a node towards that nodeport will always hit the local service, regardless of whether the target node is local or remote.

Specifically, this affects the clustermesh-apiserver service (which by default uses NodePort 32379), causing the agents (or kvstoremesh in this case) to mistakenly connect to the local one instead of the remote one (after a first successful connection), regardless of the configuration.

Could you please [configure a different NodePort](https://github.com/cilium/cilium/blob/d678428a8697545c03fa1da76d7833090671c058/install/kubernetes/cilium/values.yaml#L2615-L2622) on each cluster as a workaround and verify if the issue gets fixed? If not, could you provide the sysdump from both clusters for further investigation?
