### ISSUE TITLE
PATCH /endpoint/{id} does not return an error if regeneration is not possible

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3058]
If an endpoint is currently being built, the PATCH /endpoint/{id} will change the endpoint structure but will not queue a regeneration and will not return an error if that is possible. In most cases.

**Comment by ianvernon** [comment]
A few questions:

Is this supposed to be for `PATCH /endpoint/{id}/config`? That is what #3054 . `Patch/endpoint/{id}` is separate in `daemon/endpoint.go` under ```func (h *patchEndpointID) Handle(params PatchEndpointIDParams) middleware.Responder {```

From #3054, the following was mentioned by @tgraf :

```
I think the change that makes the CI fail is to return an error if regeneration was not possible. However, this actually shows a real bug that was present before. The config call would succeed even though a regeneration could not be scheduled.
```

Agreed; what is the expected behavior here, though? I.e., if an endpoint is not in a state where it is ready to receive configuration updates, we could do either of the following:

1. Quicker solution:  return an error to the client until the endpoint is ready to handle configuration updates. We can wait until the endpoint is in a 'ready' state after the call to `cilium endpoint config` in our CI fairly easily. In fact, we already have a function that does this; `test/helpers/cilium.go:EndpointSetConfig`. I recommend we do this for now and then focus on a non-state-dependent fix later, as I don't know how much work that will take to implement.

2. Handle such updates without being reliant upon endpoint state: Ideally, we'd be able to handle this behind the scenes and schedule a regeneration with these configuration updates if needed, regardless of the current state of the endpoint. I.e., I send the following configuration updates all in a row without checking the endpoint's state:

```
cilium endpoint config Debug=true
cilium endpoint config EgressPolicy=true
cilium endpoint config IngressPolicy=true
```

and all calls succeed; builds are queued up for the endpoint with these options changed (this could be optimized to avoid unnecessary regenerations).

@tgraf thoughts?

**Comment by tgraf** [comment]
I suggest we wait (with a timeout) in the API call until the endpoint is ready to have its state changed. It preserves the existing logic. Clients can stay as-is for the most part. As we later make config changes not depend on the state, clients do not have to change at all.

**Comment by ianvernon** [comment]
By 'in the API call' do you mean within `cilium/cmd/endpoint_config.go`? I think we should keep `pkg/endpoint/endpoint.go:Update` as I have done in PR #3264, because we are not privy to the timeout the client uses in the call to `PATCH/{id}/config` .

**Comment by ianvernon** [comment]
Hm, having the check in `cilium/cmd/endpoint_config.go` doesn't really seem viable unless we allow updating of endpoint state via the API, which I'm not sure we want. The problem though, is that adding the timeout within `pkg/endpoint/endpoint.go:Update` doesn't take into account the timeout on the client side of the API...

**Comment by tgraf** [comment]
I'm saying that we can keep on retrying in

``` go
func (d *Daemon) EndpointUpdate(id string, opts models.ConfigurationMap) error {
```

until it succeeds with a upper timeout/retry limit to eventually error out.

**Comment by ianvernon** [comment]
OK - but how will this take into account the timeout on the client side? The timeout is configurable and we aren't aware of it on the server side. If they set a timeout lower than our timeout for retrying internally, I believe they'll get an `EOF`; is this desirable?

See: 
```
// NewPatchEndpointIDConfigParams creates a new PatchEndpointIDConfigParams object
// with the default values initialized.
func NewPatchEndpointIDConfigParams() *PatchEndpointIDConfigParams {
	var ()
	return &PatchEndpointIDConfigParams{

		timeout: cr.DefaultTimeout,
	}
}
```

**Comment by tgraf** [comment]
How is the client timeout specific to this type of request? This is not about a long term solution. This is about deciding whether we build retry logic into the client or server short term. If we are going to make the config patching non-blocking in the future, why require all clients to build retry logic now?

**Comment by ianvernon** [comment]
@tgraf if we have timeout logic implemented on the server side, the error returned to the user will differ depending on if their client's timeout is configured to be higher or lower than the timeout on the server side. Given that this is a short-term solution, this doesn't really matter, though.
