### ISSUE TITLE
CI: Conformance E2E (ci-e2e) - ingress tests 

### ISSUE THREAD

**Issue by dylandreimerink** [cilium/cilium#30717]
## CI failure

https://github.com/cilium/cilium/actions/runs/7872408390/job/21479794145

The E2E (subtest 6) seem to flake on a fairly regular basis with the following error:
```
📋 Test Report
❌ 3/66 tests failed (3/928 actions), 4 tests skipped, 0 scenarios skipped:
Test [pod-to-ingress-service]:
  ❌ pod-to-ingress-service/pod-to-ingress-service/curl-0: cilium-test/client3-7557dd665c-fg64g (10.244.2.174) -> cilium-test/cilium-ingress-ingress-service (cilium-ingress-ingress-service.cilium-test:80)
Test [pod-to-ingress-service-allow-ingress-identity]:
  ❌ pod-to-ingress-service-allow-ingress-identity/pod-to-ingress-service/curl-2: cilium-test/client3-7557dd665c-fg64g (10.244.2.174) -> cilium-test/cilium-ingress-ingress-service (cilium-ingress-ingress-service.cilium-test:80)
Test [outside-to-ingress-service]:
  ❌ outside-to-ingress-service/outside-to-ingress-service/curl-ingress-service-0: cilium-test/host-netns-non-cilium-cwwp8 (172.18.0.2) -> cilium-test/cilium-ingress-ingress-service (cilium-ingress-ingress-service.cilium-test:80)
connectivity test failed: 3 tests failed
```

Full log archive: [logs_2049050.zip](https://github.com/cilium/cilium/files/14240348/logs_2049050.zip)
Sysdumps (minus hubble flows json so they are uploadable):
- [cilium-sysdump-6-20240212-145358-small.zip](https://github.com/cilium/cilium/files/14240520/cilium-sysdump-6-20240212-145358-small.zip)
- [cilium-sysdump-6-20240212-145950-small.zip](https://github.com/cilium/cilium/files/14240521/cilium-sysdump-6-20240212-145950-small.zip)
- [cilium-sysdump-6-20240212-150505-small.zip](https://github.com/cilium/cilium/files/14240522/cilium-sysdump-6-20240212-150505-small.zip)

List of other CI failure instances (that I was able to find):
- https://github.com/cilium/cilium/actions/runs/7871213294/job/21474028662
- https://github.com/cilium/cilium/actions/runs/7816728702/job/21322983350
- https://github.com/cilium/cilium/actions/runs/7802768439/job/21280989140
- https://github.com/cilium/cilium/actions/runs/7799535599/job/21270548738

**Comment by sayboras** [comment]
Should we close this issue as https://github.com/cilium/cilium/pull/30762 is merged? @dylandreimerink

**Comment by tommyp1ckles** [comment]
I'm still seeing issues that look like this, for ex: https://github.com/cilium/cilium/actions/runs/8374986872/job/22931393994

**Comment by giorio94** [comment]
https://github.com/cilium/cilium-cli/pull/2445 should remove some sources of flakiness by explicitly waiting for the creation of the ingress service, as well as providing a clearer error message in case it is not found. It should address almost all of the failures listed above.

**Comment by joestringer** [comment]
@sayboras No need to pin the item if it's assigned to you, assigned issues will stay open forever.

That said, do you plan to work on this? The intent with the stalebot is to let inactive issues be closed so that we can filter down issues more easily to problems that have affected the tree in the last 2-3 months. If there's no update on the issue and no-one's working on it, then it's often the case that the issue was already resolved and no-one came back to report it as fixed.

**Comment by joestringer** [comment]
Related:

This issue is referenced in `.github/workflows/tests-e2e-upgrade.yaml`, but the equivalent configuration is tested regularly as part of `.github/workflows/conformance-e2e.yaml`. Looking back through Marco seemed to hint that the issue should be resolved, so maybe this is actually ready to be closed out?
