### ISSUE TITLE
CFP: Allow to override on per-node basis which IP would be advertised as next-hop with BGP Control Plane

### ISSUE THREAD

**Issue by agrevtsev** [cilium/cilium#30878]
## Cilium Feature Proposal
        
Allow to override on per-node basis which IP would be advertised as next-hop with BGP Control Plane

**Is your proposed feature related to a problem?**

Currently, there is no way to override, which exactly IP address would be advertised as next-hop over the BGP-peering established by GoBGP and controlled by CiliumBGPPeeringPolicy. So, if k8s nodes is behind 1-to-1 NAT, their private IPs would be advertised to adjacent router as next-hops.

**Describe the feature you'd like**

Allow to override node external IP (IOW IP by which the node could be reached outside) by extending existing `cilium.io/bgp-virtual-router.{asn}=` annotation, e.g:

`kubectl annotate node <node-name> cilium.io/bgp-virtual-router.{asn}="external-ip=1.1.1.1"`

Br, Alexey

**Comment by YutaroHayakawa** [comment]
Note
- GoBGP allows to change the next-hop with Policy (https://github.com/osrg/gobgp/blob/master/docs/sources/policy.md)
- Annotation vs extending CRD, which is better?

**Comment by agrevtsev** [comment]
> Note
> 
> * GoBGP allows to change the next-hop with Policy (https://github.com/osrg/gobgp/blob/master/docs/sources/policy.md)
> * Annotation vs extending CRD, which is better?
I suppose the more elegant option is to extend existing k8s node annotation. It exist already, WDYT?

**Comment by YutaroHayakawa** [comment]
I want to avoid annotation as much as possible. I agree that `cilium.io/bgp-virtual-router.{asn}` is a quick win. However, I feel like this is a more generic problem and not specific to BGP advertisements. It is pretty common that Node has an external NAT and externally-reachable IP. In fact, Kubernetes provides an interface to export it to the `Node` object through [status. addresses](https://kubernetes.io/docs/reference/node/node-status/#addresses) as `ExternalIP` type. Instead of introducing a per-node annotation, we can instead implement a feature to override the next-hop with a node `ExternalIP`.

**Comment by agrevtsev** [comment]
Good point. But sometimes we need to strictly override the address, and annotation is a good place.
