### ISSUE TITLE
Restrict `toServices` policies to headless services

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3088]
According to the documentation:
http://docs.cilium.io/en/latest/policy/language/#services-based

"Services running in your cluster can be whitelisted in Egress rules. Currently headless Kubernetes services defined by their name and namespace or label selector are supported."

As far as I can tell, we don't reject policies which attempt to act upon non-headless services, we just silently fail to implement the policy. If this is true, we should consider rejecting policies acting upon unsupported service types.

**Comment by joestringer** [comment]
@nebril ^

**Comment by tgraf** [comment]
@joestringer The problem is that we can't really tell at import time. The service is referred to by name and can change its type after policy import. I hope that we print at least an error message. I've discussed with @nebril and he's working on enabling non headless but endpoints backed services and as soon as egress pod enforcement is merged, we can extend it to support all service types. Adding NodePort will be trivial as well.

**Comment by joestringer** [comment]
@nebril is this addressed by #2979?

**Comment by nebril** [comment]
@joestringer not really, #2979 changed the ToServices compatible policy types a bit. The issue is that ToServices can select services based on their labels, so new services can be created after the policy. Should we reject the policy if there are no matching services in the cluster? I think not, but maybe we should?

**Comment by joestringer** [comment]
@nebril Hmm, that seems restrictive. What if the service gets deleted later? Then we have a policy that doesn't apply to a service, but there would otherwise be no way to get in this state. We're still not really properly protecting against getting into this state.

**Comment by joestringer** [comment]
I'm going to close this, I don't think there's a good way to resolve it.
