### ISSUE TITLE
Cilium agent removes ciliumnode.spec.eni.subnet-ids when adding CiliumInternalIP and health IP

### ISSUE THREAD

**Issue by demikl** [cilium/cilium#30900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm using a Kyverno policy to add the field `.spec.eni.subnet-ids[]` on creation of a CiliumNode, with a single value sourced from 
`.spec.eni.node-subnet-id`, because I want to force this node to only use the same subnet as its primary ENI.

Unfortunately, soon after the CiliumNode resource has been created by cilium-agent and mutated by Kyverno, the cilium-agent makes an update that removes what Kyverno has added with its mutating webhook:

```diff
 ---
 apiVersion: cilium.io/v2
 kind: CiliumNode
 metadata:
   annotations:
     network.cilium.io/wg-pub-key: <REDACTED>
-    policies.kyverno.io/last-applied-patches: |
-      configure-pre-allocate.cilium-ipam-pre-allocate.kyverno.io: added /spec/ipam/pre-allocate
   creationTimestamp: "2024-02-21T17:36:14Z"
-  generation: 3
+  generation: 4
   labels:
     <REDACTED>
   name: ip-100-83-108-27.eu-west-3.compute.internal
   ownerReferences:
   - apiVersion: v1
     kind: Node
     name: ip-100-83-108-27.eu-west-3.compute.internal
     uid: b6ad92b7-ad5f-4d63-97b5-d29d2efcfdba
-  resourceVersion: "662319433"
+  resourceVersion: "662319456"
   uid: a48c27e7-0292-42ea-a380-6ba01a81f79e
 spec:
   addresses:
   - ip: 100.83.108.27
     type: InternalIP
+  - ip: 100.83.98.106
+    type: CiliumInternalIP
   alibaba-cloud: {}
   azure: {}
   encryption:
     key: 255
   eni:
     availability-zone: eu-west-3c
     disable-prefix-delegation: false
     first-interface-index: 0
     instance-type: t3a.medium
     node-subnet-id: subnet-0d9<REDACTED>
-    subnet-ids:
-    - subnet-0d9<REDACTED>
     use-primary-address: false
     vpc-id: <REDACTED>
-  health: {}
+  health:
+    ipv4: 100.83.105.39
   ingress: {}
   instance-id: i-0c284fc12ebc85fd3
   ipam:
     min-allocate: 6
     pool:
       100.83.98.106:
         resource: eni-0aa1a6fd523aeaf21
       100.83.101.196:
         resource: eni-03eafd0d0dabcab84
       100.83.105.39:
         resource: eni-03eafd0d0dabcab84
       100.83.109.141:
         resource: eni-03eafd0d0dabcab84
       100.83.109.212:
         resource: eni-03eafd0d0dabcab84
       100.83.110.124:
         resource: eni-03eafd0d0dabcab84
     pools: {}
     pre-allocate: 2
 status:
   alibaba-cloud: {}
   azure: {}
   eni:
     enis:
       eni-03eafd0d0dabcab84:
         addresses:
         - 100.83.105.39
         - 100.83.101.196
         - 100.83.109.212
         - 100.83.109.141
         - 100.83.110.124
         id: eni-03eafd0d0dabcab84
         ip: 100.83.108.27
         mac: 0e:31:b0:ef:5d:15
         security-groups:
         - sg-057<REDACTED>
         - sg-05a<REDACTED>
         subnet:
           cidr: 100.83.96.0/20
           id: subnet-0d9<REDACTED>
         tags:
           <REDACTED>
         vpc:
           cidrs:
           - 100.83.64.0/18
           - 100.89.0.0/16
           - 100.82.4.0/22
           - 100.80.64.0/18
           id: <REDACTED>
           primary-cidr: 10.200.136.0/21
       eni-0aa1a6fd523aeaf21:
         addresses:
         - 100.83.98.106
         description: Cilium-CNI (i-0c284fc12ebc85fd3)
         id: eni-0aa1a6fd523aeaf21
         ip: 100.83.110.38
         mac: 0e:6f:bd:65:bc:7d
         number: 1
         security-groups:
         - sg-057<REDACTED>
         - sg-05a<REDACTED>
         subnet:
           cidr: 100.83.96.0/20
           id: subnet-0d9<REDACTED>
         tags:
           io.cilium/cilium-managed: "true"
           io.cilium/cluster-name: <REDACTED>
         vpc:
           cidrs:
           - 100.83.64.0/18
           - 100.89.0.0/16
           - 100.82.4.0/22
           - 100.80.64.0/18
           id: <REDACTED>
           primary-cidr: 10.200.136.0/21
   ipam:
     operator-status: {}
```

### Cilium Version

Daemon: 1.15.0 2db45c46 2024-01-31T18:58:02+01:00 go version go1.21.6 linux/arm64

### Kernel Version

Linux ip-100-89-88-204.eu-west-3.compute.internal 5.10.209-198.812.amzn2.aarch64 #1 SMP Tue Jan 30 20:59:47 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.12-eks-5e0fdde", GitCommit:"95c835ee1111774fe5e8b327187034d8136720a0", GitTreeState:"clean", BuildDate:"2024-01-02T20:34:50Z", GoVersion:"go1.20.12", Compiler:"gc", Platform:"linux/amd64"}

### Anything else?

Here is the Kyverno policy I'm using to add fields when some specific CiliumNode resources are created:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cilium-ipam-pre-allocate
spec:
  background: false
  failurePolicy: Ignore
  rules:
  - name: configure-pre-allocate
    match:
      any:
      - resources:
          kinds:
          - CiliumNode
          operations:
          - CREATE
          selector:
            matchLabels:
              subnet: transverse
    mutate:
      patchStrategicMerge:
        spec:
          eni:
            subnet-ids:
            - "{{request.object.spec.eni.\"node-subnet-id\"}}"
          ipam:
            min-allocate: 6
            pre-allocate: 2
  validationFailureAction: Audit
```

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gandro** [comment]
Hi! Thanks for the report. Unfortunately I don't we support patching the IPAM section of the CiliumNode, and I don't think we ever will (at least with the current implementation), because changing the spec.ipam section after CiliumNode creation is not safe.

The reason why it is not safe is that it is racy: The operator might already have observed the CiliumNode object as created (i.e. without your patches) and will allocate IPs from the node subnet, which then will be used by pods and thus cannot be removed from the node anymore.

Instead, you can configure Cilium-Agent to populate the IPAM fields ([including the subnet-ids](https://github.com/cilium/cilium/blob/930d4427817dc2fedbcb53c18f20243721c36cc5/pkg/nodediscovery/nodediscovery.go#L500)) **from the CNI config file**. That one is read and respected by cilium-agent when it creates the node. This is documented here:

- https://docs.cilium.io/en/stable/network/concepts/ipam/eni/#custom-eni-configuration
- https://docs.cilium.io/en/stable/network/kubernetes/configuration/#adjusting-cni-configuration
 
This is also how we recommend you set min and pre-allocate.

If that solution works for you, then I propose we close this as "not planned".

**Comment by demikl** [comment]
As I understand the usage of the CNI config file, I would need as many separate cilium-agent daemonsets (each referencing its own configmap for the CNI file content) as I have "specialized" nodes templates. That's quite complicated to scale.

My first approach was to use a CiliumNodeConfig, but these IPAM and ENI parameters seems not to be overridable .

**Comment by gandro** [comment]
Yeah, I agree that it would be easier to have the option to inject a CNI config file or IPAM template via `CiliumNodeConfig`. PRs welcome in that regard.

For existing releases, my recommendation would be to inject a CNI config file onto the host when you provision the nodes, and then mount that file into the cilium-agent pod via  `extraHostPathMounts[0].name="host-custom-cni-conf"`, `extraHostPathMounts[0].mountPath="/host/custom-cni-conf/05-cilium.conf"` and `extraHostPathMounts[0].hostPath="/var/lib/cilium-custom-cni-conf/05-cilium.conf"`. Then you can Cilium-Agent to read that CNI config file with `cni.customConf=true` and `cni.readCniConf="/host/custom-cni-conf/05-cilium.conf"`. Every node can have it's own file on the host system.

But as mentioned above, I believe we would also accept a patch that allows one to inject a CNI config file as a string contained in the `CiliumNodeConfig`.

**Comment by demikl** [comment]
Thanks, I'll look into that. I was hoping that the mutation with Kyverno, that happens on the CREATE operation and not as an UPDATE after its creation, would comply to this race-condition requirement.

**Comment by gandro** [comment]
> Thanks, I'll look into that. I was hoping that the mutation with Kyverno, that happens on the CREATE operation and not as an UPDATE after its creation, would comply to this race-condition requirement.

Ah, I missed that. I'm not familiar with Kyverno - if it applies the patch in a way where no intermediate version of the CiliumNode object is observed, then that would actually be safe from an operator perspective. 

But I'm not sure if the cilium-agent code will cope with the fact that the object that it wrote is modified during creation. That would probably require an audit of the existing code to ensure the local node store can deal with the fact that what it writes to K8s is not what ends up in K8s. For certain fields, like the ENI IPAM parameters, that is safe because those are not read by the agent it self, but for other fields (like e.g. the the WireGuard encryption key) that will not work.

**Comment by demikl** [comment]
In my understanding, the `.spec.eni.subnet-ids[]` field is to be used only by the `cilium-operator`. So, the only requirement from the `cilium-agent` would be to retain fields that it does not manage. I will dive into the agent code to see what can be done to make it aware of "external" changes on this field.

Thanks again.

**Comment by demikl** [comment]
Before going into a PR that will allow overriding ENI parameters per node, I would like to share my thoughts about how to implement it.

Reading through the code, I can see two major ways of handling the override:

1. let `cilium-operator` read overrides from a `CiliumNodeConfig` on parameters it already knows about, such as `--subnet-ids-filter`

  - benefits:
    - only the cilium-operator needs modifications
  - drawbacks:
    - the `ciliumnode.spec.eni` fields won't reflect what is actually being enforced ; but that's already the case when a cilium-operator CLI flag and/or configmap key is set to change its behavior
    - many ENI parameters have no CLI flags or configmap keys on the cilium-operator, such as `pre-allocate` or `min-allocate`

2. the `cilium-agent` reads ENI configuration from a) the CNI configuration file, and b) a `CiliumNodeConfig` populated with each parameter than can be set on `ciliumnodes.spec.eni` and c) default values ; it then creates the `CiliumNode` resource with its `.spec.eni` fields populated from these cumulated sources, and the `cilium-operator` use these values

  - benefits:
    - no change is needed in the cilium-operator since it's already reading what it should do with each node from `ciliumnodes.spec.eni`
    - actual configuration for every node is clearly exposed in `ciliumnodes.spec.eni`, there's a single source of truth
  - drawbacks:
    - precedence is not clear: should the CNI configuration file read on each node have a higher priority than a CiliumNodeConfig? I think so, but that's debatable

There's also the option of having a default inline CNI configuration file for all nodes in the cilium configmap, and use a `CiliumNodeConfig` to have a different inline CNI configuration file for subsets of nodes, but I think it's quite a hack and less clear than the second propositiion.

**Comment by gandro** [comment]
Thanks for the write-up. I think you covered the different pros and cons very sufficiently. 

> There's also the option of having a default inline CNI configuration file for all nodes in the cilium configmap, and use a CiliumNodeConfig to have a different inline CNI configuration file for subsets of nodes, but I think it's quite a hack and less clear than the second proposition.

I personally actually prefer this solution. I also wouldn't call it a hack. The CNI config currently **is** the canonical way to configure ENI IPAM parameters, it has been documented for years. Users who have deployed custom ENI parameters will be familiar with it. All we would do is introduce yet another mechanism on how to inject a CNI config (besides reading it from file or reading it from configmap we would now also support reading from a string).

I like that solution (let's call it option 3), because it does also not have any precedence issues. There is a single canonical source of truth, the CNI config provided by the user. Plus it also helps users who are migrating CNIs (and e.g. want to have different CNI configurations on different nodes for other reasons than configuring IPAM), where as solutions 1 and 2 are very specific to IPAM (or perhaps even ENI IPAM).
