### ISSUE TITLE
CFP: Improve `auto-direct-node-routes` to not exit when node is outside of subnet

### ISSUE THREAD

**Issue by jleeh** [cilium/cilium#31124]
Improve `auto-direct-node-routes` so it doesn't exit when a node is outside of the current subnet.

**Is your proposed feature related to a problem?**

When running Cilium in native routing mode with the BGP Control Plane in a multi-zone setup, it is not possible to have same-zone traffic routed over L2 as each node is not aware of each others pod CIDR so it needs to use its default gateway, bottlenecking same-zone traffic.

Since we have multiple zones that have different subnets, it's not currently possible to enable `auto-direct-node-routes` as it will fatally exit when it detects the nodes which have different subnets.

**Describe the feature you'd like**

Improve `auto-direct-node-routes` so it ignores nodes that are outside of the current subnet, only adding routes for the nodes that are in the current subnet.

For example, if I have 8 nodes in zone A and 8 nodes in zone B, all zone A nodes will have direct node routes to all nodes in zone A and all zone B nodes will have direct node routes to all nodes in zone B.

More discussion here: https://github.com/cilium/cilium/issues/31091

**Comment by joestringer** [comment]
Hmm. This proposal seems like it will effectively divide the cluster into routable segments based on the underlying network topology, but then if a Pod in zone A attempts to connect to a Pod in zone B, it will fail to connect because Cilium cannot guarantee routability and the network is not guaranteeing routability. What do you think should happen in that scenario?

**Comment by jleeh** [comment]
In this scenario @joestringer, zone A <> zone B is still reachable as the routers have all of the advertised BGP routes broadcasted by Cilium. This is how it's working for us currently as we're running in native routing mode and relying on our core routers to route pod traffic.

The main problem this is solving is the lack of L2 routing for same-zone traffic. For inter-zone, the traffic would just leave the node and go to the gateway which would route the traffic as required. With the routes installed for same-zone traffic, the traffic would be routed directly to the nodes in the L2 rather than needing the default gateway solving the bottleneck and improving latency.

It's worth mentioning that Flannel does this if `DirectRouting` is enabled in the vxlan configuration, so it is already supported in other CNI's.

**Comment by joestringer** [comment]
OK, I see. So maybe we can tailor the specific error condition to only trigger if it doesn't look like routability is provided across subnets. If Cilium is advertising via BGP then it's probably fair to assume that routability is provided.

The only drawback I can see is if users naively configure the `auto-direct-node-routes` feature in this topology without configuring L3 routing. Currently those users would get a signal that they are doing something that will cause connectivity outages, and with this proposal they might not get any sign that something is wrong until traffic is dropped. But we can work around that by tailoring the error message to account for this case.

Some additional details that would help:
- Which configurations did you apply for BGP? The solution can check for those.
- What exactly is the error message that you observe in the Cilium logs when Cilium exits prematurely in this case? This can be used by a contributor to identify where to make the change.

**Comment by joestringer** [comment]
Thanks for the further details. I presume this also requires the (currently non-default) option `--enable-bgp-control-plane=true` (Helm: `bgpControlPlane.enabled=true`).

I agree that inherently if the cluster isn't configured correctly then the behaviour would be largely the same. On the other hand, currently Cilium has a "feature" here which will inform you about an incompatibility that it detects in your network: When configuring its own feature, it notices that certain nodes are unreachable on the L2 domain, and will very loudly fail out to let the user know that they may have misconfigured something. If we silently fail instead, this can make it harder for users to understand what is misconfigured.

The ideal situation to me in this scenario is if power users like yourself who know exactly what they're doing can override the failure with a signal that says "I know what I'm doing, just let me do it", while on the other hand we can still have detection mechanisms in place to inform the other users that have less understanding about what might be wrong.

Maybe there's a simple solution here, like just reducing the "fatal" message to an "error"/"warning", or by enhancing the detection so that Cilium can *know* that there are L3 devices in the network that provide routability. One signal for this is the `EnableBGPControlPlane` flag, since this _suggests_ that the user knows about the limitations of `--auto-direct-node-routes` and is augmenting the L2 functionality with L3 routing functionality.

**Comment by joestringer** [comment]
At a high level that seems reasonable to me. Unless others have a strong opinion otherwise, I think the next step would be to prepare a PR to implement the proposal.

**Comment by Sugaroverdose** [comment]
Was taken by surprise with current "auto-direct-node-routes" implementation and really struggle to understand why it want everything to be in a single L2 segment

The most voluminous description of autoDirectNodeRoutes is stated in [helm reference](https://docs.cilium.io/en/stable/helm-reference/#id1) and says this:

> Enable installation of PodCIDR routes between worker nodes if worker nodes share a common L2 network segment.

What, from my point of view, translates into:
> Creates direct routes between nodes which share the same L2 segment

Which is kind of logical(i would even say - it's the only right way to implement such feature) and i really struggle read it as:
> To enable this feature all of your worker nodes has to be in exact the same L2 segment or cilium agent will randomly fail of certain nodes

It's pretty easy to fix thou, this check is just has to stop initializing err
https://github.com/cilium/cilium/blob/aefd4ea3748cf6f82a3959461e2611c1573f4931/pkg/datapath/linux/node.go#L251-L255
something like this would do the trick
```
	if routes[0].Gw != nil && !routes[0].Gw.IsUnspecified() && !routes[0].Gw.Equal(nodeIP) {
		log.Warningf("route to destination %s contains gateway %s, skipping",
			nodeIP, routes[0].Gw.String())
		return
	}
```

Yet docs are also has to account that auto-direct-node-routes isn't only about worker nodes, but about masters as well

**Comment by jleeh** [comment]
> I agree that this could be useful, but would this proposal [inject received routes into the Linux kernel](https://github.com/cilium/cilium/issues/31091)?

It would do, but due to the complexity of the BGP proposal it was deemed this to be the better option (at least for my needs).

If you're looking to inject BGP routes into the linux kernel you could use kube-router:
https://docs.cilium.io/en/stable/network/kube-router/

**Comment by ldelossa** [comment]
@joestringer @Sugaroverdose 

For sake of discussion, since there is a "BGP" emphasis to this CFP, has the idea of distributing all PodCIDRs to each node via BGP been considered? 

With BGP employed already, it would be a common practice to also distribute same-zone PodCIDR into to nodes within the same zone. I'm under the current impression that Cilium's BGP control plane does not support this currently, but given 

I noticed that talk about such CFP in the previous few comments, but I'm also trying to gather whether distributing PodCIDR (full mesh) via BGP is a cleaner/better solution then modifying the way `auto-direct-node-routes` performs its feature detection. The docs for `auto-direct-node-routes` do mention that if you run into your use case, use BGP. 

Maybe we should pull in @YutaroHayakawa.

**Comment by jleeh** [comment]
I do personally agree that a BGP mesh would be a cleaner solution and it's already seen throughout other CNIs (Calico) and in kube-router for example.

Like said, editing node routes functionality feels like putting in a band-aid fix that is specifically for BGP use-cases.

**Comment by ldelossa** [comment]
@jleeh this is the overall sentiment I got from this CFP as well. To me it feels like we are adjusting a separate feature to handle a lack in a BGP feature. Before moving forward with that PR we should get a clean understanding if BGP-CP should actually learn this behavior or not. For that, we should defer to the sig-traffic-engineer team.

**Comment by harsimran-pabla** [comment]
Hi @jleeh, I would like to understand the scenario a bit better. Here is my current understanding ( please correct me if I am wrong )
- You have the cluster spread over multiple L2 domains. 
- BGP is advertising pod CIDRs to upstream routers.
- To have pod to pod reachability across nodes over L2 domains, node sends the traffic to upstream routers ( default route, I assume). 
- Upstream routes know pod CIDR -> node routing ( BGP learned prefixes ).
- Traffic goes to the destination node.

In all this, what I am curious about is why you need `auto-direct-node-routes` feature. Is it so that there is some traffic path optimization?

**Comment by jleeh** [comment]
Hey @harsimran-pabla, correct in terms of your understanding.

> Is it so that there is some traffic path optimization within L2 domain, i.e. traffic does not need to be hairpinned down from the router?

Exactly. Traffic is always being hairpinned down the router rather than being switched in the L2.
