### ISSUE TITLE
Commit displayed in GHA Workflow summary is not the commit which was tested.

### ISSUE THREAD

**Issue by learnitall** [cilium/cilium#31207]
During the Cilium community meeting today (March 6th, 2024), @tommyp1ckles pointed out that the commit that is displayed by GitHub on the workflow summary page is _not_ the commit that was actually tested in the workflow run.

For example, [this workflow](https://github.com/cilium/cilium/actions/runs/8159042299) shows that it was run on commit https://github.com/cilium/cilium/commit/08d898d8011c68a85851629e131900deef91bab3:

![summary](https://github.com/cilium/cilium/assets/13142290/008c49a0-21c1-443a-9949-19b4f41a4391)

However by looking at the step which checks out the untrusted branch for testing, the commit that was actually tested was https://github.com/cilium/cilium/commit/cb3839f899eef73a20aec4dca9c1d70635c62341:

![step](https://github.com/cilium/cilium/assets/13142290/0c93f5d0-7a3c-42f1-bdd8-cb67bb417af2)

This occurs based on the way that workflows are triggered. Ariane will schedule a workflow run through the `workflow_dispatch` trigger, using a trusted commit to grab the workflow files to run. The commit to be tested is passed as an input to the trigger, which the workflow then tests.

One option to address this is to modify each workflow to output the inputs that were used to trigger it, allowing for visibility into the PR, commit, etc. that is the target for testing. This might be the best option, as unfortunately, the GH API does not output the inputs to a `workflow_dispatch` trigger. See https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#get-a-workflow-run.

**Comment by joestringer** [comment]
When browsing to the workflow runs from an individual PR, I think the above is usually overlooked by most developers since the PR context is already fairly clear, though it may produce some confusion if a contributor pays close attention to the summary page.

For another different workflow, it can be even more confusing: Let's say I'd like to understand the stability of an individual branch. If I browse to the top-level page for the workflow, this will list *all* runs, from both PRs and from runs scheduled on a timer or triggered by push:

https://github.com/cilium/cilium/actions/workflows/conformance-runtime.yaml

In order to filter to workflow runs on a stable branch, it's useful to filter by either push event (triggered when the PR is merged, [example](https://github.com/cilium/cilium/actions/workflows/conformance-runtime.yaml?query=event%3Apush)) or schedule (triggered on a timer, depends on the workflow):

![image](https://github.com/cilium/cilium/assets/1243336/f5dc8655-7c78-487b-84f5-a7d60082add2)

**Comment by joestringer** [comment]
With https://github.com/cilium/cilium/pull/31424 , the set of input parameters for the workflow should now be clearly highlighted in a step in each relevant job called "Echo Workflow Dispatch Inputs":

![image](https://github.com/cilium/cilium/assets/1243336/764357da-ea50-4332-b0e0-0f71271b1360)
