### ISSUE TITLE
Make xDS network policies per-endpoint instead of per-identity

### ISSUE THREAD

**Issue by rlenglet** [cilium/cilium#3122]
The NetworkPolicy resources pushed to Envoy proxies are currently defined as per-identity, cf. https://github.com/cilium/cilium/blob/master/envoy/cilium/npds.proto. I.e. proxies query network policies per security identity.
However, that will prevent us from handling per-endpoint configuration, especially the endpoint-specific enforcement mode.
Therefore, the NetworkPolicy resources need to be changed to be query-able by endpoint IP address, which is the only endpoint metadata that never changes during the lifecycle of the endpoint. The signatures of the methods in Owner, etc. need to be changed to take an endpoint IP address instead of a security identity. And that implies that NetworkPolicy resources need now to be deleted when an endpoint is deleted, not when the identity becomes unused.

The currently implementation was done in https://github.com/cilium/cilium/pull/2902, https://github.com/cilium/cilium/pull/2993, and https://github.com/cilium/cilium/pull/3071. Look in particular at the new methods in the Owner interface.

**Comment by rlenglet** [comment]
@jrajahalme FYI, this will overlap with your change to npds.proto to replace the policy ID with IP address.

**Comment by joestringer** [comment]
@rlenglet the below comment suggests that this logic is just an optimization that could be removed and things will still be functional. If we're moving away from identity-based policies for xDS, then the below would either need to go away, or be replaced by something that can go through all of the endpoints rather than just the sets of labels. At the moment I'm thinking that if each endpoint is triggering this xDS networkpolicy update with its own addresses, then we can replace this with the list of endpoint IPs.

https://github.com/cilium/cilium/blob/40187c5c53d94c77a298af202f11fcb22b1898ea/pkg/envoy/server.go#L412-L429

**Comment by rlenglet** [comment]
We're not moving away from identity-based filtering. That part of the policy shouldn't change, and we should keep this optimization.
The only change we're making is what we use as resource name for NetworkPolicy. I.e. you should change or complement the `uint64 policy` field with a `string name` field that contains the IP address of the endpoint.
