### ISSUE TITLE
Adding `ingress.cilium.io/tls-passthrough` to any one ingress breaks all ingresses

### ISSUE THREAD

**Issue by nebula-it** [cilium/cilium#31242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. When using cilium ingress, adding `ingress.cilium.io/tls-passthrough` to any one ingress breaks it and all other ingresses in cluster. All ingresses fail with `curl: (56) Recv failure: Connection was reset`
2. The issue occurs, no matter if `ingressController.loadbalancerMode` is in `shared` or `dedicated` mode

### Cilium Version

v1.15.1

### Kernel Version

6.1.80-talos

### Kubernetes Version

v1.29.2

### Regression

This is a new addition in 1.15, the functionality was not present in previous versions

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chaunceyjiang** [comment]
Can you provide the sysdump file?

Could you provide some steps to reproduce the issue or installation parameters?

**Comment by dimidevops** [comment]
Hi,

I'm facing the same strange issue. I've tested it with v1.15.1 and v1.15.2 and the issue is present in both.

When you set the annotation "ingress.cilium.io/tls-passthrough: enabled" on an ingress, only that ingress is working. 
The rest of ingress routes, if they are plain text HTTP, they keep throwing error 502:

![image](https://github.com/cilium/cilium/assets/147745543/c0516f85-55fe-4eb5-82c2-842ef3164faf)

Attached is the cilium sysdump.
[cilium-sysdump-20240314-204252.zip](https://github.com/cilium/cilium/files/14605544/cilium-sysdump-20240314-204252.zip)

Cilium is installed via Helm without kube-proxy and the ingress service is set as 'NodePort:

helm install \
    cilium \
    cilium/cilium \
    --version 1.15.2 \
    --namespace kube-system \
    --set ipam.mode=kubernetes \
    --set kubeProxyReplacement=true \
    --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
    --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
    --set cgroup.autoMount.enabled=false \
    --set cgroup.hostRoot=/sys/fs/cgroup \
    --set k8sServiceHost=localhost \
    --set k8sServicePort=7445 \
    --set gatewayAPI.enabled=true \
    --set ingressController.enabled=true \
    --set ingressController.default=true \
    --set ingressController.loadbalancerMode=shared \
    --set nodePort.enabled=true \
    --set l7Proxy=true \
    --set envoy.enabled=true \
    --set hubble.relay.enabled=true \
    --set hubble.ui.enabled=true \
    --set prometheus.enabled=true \
    --set operator.prometheus.enabled=true \
    --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}"

**Comment by dimidevops** [comment]
Additionally, when I define Ingress A with TLS/SSL via cert-manager pointing to service A, and add the "ingress.cilium.io/tls-passthrough: enabled" annotation on ingress B with service B, the ingress A forwards requests to same service B that is defined under the ingress B.

I think this is a bug in the ingress-controller

**Comment by mhofstetter** [comment]
Thanks for opening the issue @nebula-it - and @dimidevops for providing the additional information via sysdump!

It looks like there are two issues with Ingress TLS Passthrough in combination with Shared Ingress. Both due to the fact that having different shared Ingresses (some with TLS Passthrough and some with HTTP(S)) leads to two separate Envoy Listeners - one that handles the TLS Passthrough case (implemented with Envoy [TCPProxy](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/tcp_proxy_filter) network filter) and the other one responsible for HTTP(S) (implemented with Envoy [HCM](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/http_conn_man#config-http-conn-man) network filter)

**Problem 1: Listener name clash**

The two listeners have the same name `listener` - hence only one of them ends up in the configuration (in most of the cases the TLS Passthrough one which appears later in the configuration).

Shared `CiliumEnvoyConfig` (after translating the Ingresses) contains the two listeners with the same name `listener` (file `ciliumenvoyconfigs-20240314-204252.yaml` from the sysdump) whereas the applied config on Envoy only contains one listener with the name `kube-system/cilium-ingress/listener` (after prefixing the name with the k8s namespace and name of the `CiliumEnvoyConfig`)(e.g. file `./cilium-bugtool-cilium-drs7r-20240314-204252/cmd/envoy-config.json`)

This is the cause for both mentioned issues by @dimidevops. In case the other non-TLS passthrough Ingress using HTTP (port 80) it fails because the filterchain of the existing listener doesn't handle non-TLS traffic- and in case the other non-TLS passthrough Ingress using HTTPS (port 443) - it uses the Passthrough (that even ends up on the _wrong_ service)

**Problem 2: TPROXY redirection to different listeners with same frontend service port**

After solving the name clash, i would still expect an issue with TLS Passthrough and HTTPS using the same "frontend" port 443 on the Ingress Service that is handled by different Envoy listeners. The current implementation (based on TPROXY) wouldn't be able to conditionally (HTTPS or TLS Passthrough) forward traffic to one of these two Listeners.

This is also part of the reason why problem 1 results in the applied listener retrieving all the requests for all the shared Ingresses (even though resulting in the 502 or TLS passthrough to the wrong service).

To solve this, the two use-cases should be combined into one Envoy listener.
---

> The issue occurs, no matter if ingressController.loadbalancerMode is in shared or dedicated mode

@nebula-it This should only occur in combination with Shared Ingress. Because a dedicated Ingress can either uses TLS passthrough or not. It would be nice to have a sysdump with dedicated mode. @dimidevops are you able to reproduce this one?

**Comment by dimidevops** [comment]
Hi, 

In the previous cluster, I forgot to mention that I manually edited the k8s 'cilium-ingress' service to be as 'NodePort' instead of 'LoadBalancer'. This is because I was running a demo cluster on metal and didn't have any automatic LB services. 

In this new cluster I've deployed metalLB to provide IP range pool for the default 'LoadBalancer' service that the cilium ingress creates.

To test everything I've deployed kubernetes-dashboard and created a simple ingress for it:

![image](https://github.com/cilium/cilium/assets/147745543/07f9d9ce-e183-42b4-af61-315f86bf06a1)

Service:
![image](https://github.com/cilium/cilium/assets/147745543/53e3b10e-b605-428a-be5c-5f314e2de7ac)

Ingress:
![image](https://github.com/cilium/cilium/assets/147745543/66832fd6-aa33-4de9-9113-16ed850b0458)

I can now access the dashboard and it works with the label 'ingress.cilium.io/tls-passthrough: enabled'
![image](https://github.com/cilium/cilium/assets/147745543/cc5a848f-6163-446e-a09b-1d58e0d62517)

Attached is the sysdump till this point.
[cilium-sysdump-20240318-182146.zip](https://github.com/cilium/cilium/files/14637840/cilium-sysdump-20240318-182146.zip)

Another application that I have deployed is the simple jmalloc/echo-server, with ingress defined as:
![image](https://github.com/cilium/cilium/assets/147745543/9db3a57b-2dbb-4c8b-a70f-a4629753f0af)

Service:
![image](https://github.com/cilium/cilium/assets/147745543/9b1aba42-c303-47ba-9d85-35f7c0252b7a)

Ingress:
![image](https://github.com/cilium/cilium/assets/147745543/52e98198-f4b7-43f6-957a-02d355b8d2e3)

On port 80 I get the redirection to https with the correct domain that is defined above:

![image](https://github.com/cilium/cilium/assets/147745543/4d449abc-e101-4af3-8ec5-e4a8ce85be73)

But on port 443 I get a connection reset:

![image](https://github.com/cilium/cilium/assets/147745543/7f766d3c-03d1-4889-a2c8-5dac8804c8a1)

Attached is the sysdump after this new ingress was deployed.

[cilium-sysdump-20240318-183229.zip](https://github.com/cilium/cilium/files/14637908/cilium-sysdump-20240318-183229.zip)

Also, idk if it is possible to define the service for the shared ingress-controller via annotations or during helm install as 'NodePort' instead of the default 'LoadBalancer', because 'NodePort' is the most common type of service for on-prem clusters running on metal.

Let me know if you need more info

**Comment by dimidevops** [comment]
Hi,

The 2nd Ingress for the echo apps now works, I had some typos in my curl command.

![image](https://github.com/cilium/cilium/assets/147745543/5aa23462-b121-4858-81bb-c990c680c61f)

It seems like when we use dedicated ingress per app, there is no mixing of traffic or errors inside the envoy proxy when using the 'tls-passthrough' annotation on the defined ingress. This is an okay case if we run on cloud and we can spin up LB automatically, but it's a nightmare if we use external LB and have to edit each ingress service and map the node ports.

Let me know if you need more info.

**Comment by dimidevops** [comment]
I've reverted to shared ingress using 'NodePort' and HAproxy as external LB in TCP mode.

The result is both ingresses serve the same service, which is the last defined service in the last defined ingress

Echo-a ingress:
![image](https://github.com/cilium/cilium/assets/147745543/9e776ed1-620c-4dac-b7b6-7fbb1fd55aac)

Dashboard ingress:
![image](https://github.com/cilium/cilium/assets/147745543/37e0f9f2-7ca2-493c-a8db-c842e8ef7730)

I'm 100% sure now that the shared ingress-controller and envoy config is mixing things up and breaking the shared feature.

Attached is the sysdump
[cilium-sysdump-20240318-191509.zip](https://github.com/cilium/cilium/files/14638404/cilium-sysdump-20240318-191509.zip)

**Comment by dimidevops** [comment]
Hi @mhofstetter will there be a release with fix soon or do you need more info from my end?

Thank you

**Comment by nebula-it** [comment]
Hey @dimidevops really appreciate you jumping in and providing the data. I had some things to take care at home and wasnt able to play with my k8s cluster.

I did try this from scratch last night with cilium `v1.15.2` and I can confirm your findings, the issue only appears when using shared ingress, with dedicated ingress it works as expected.

Happy to help if any more data is required but I think @dimidevops got it all :)

**Comment by mhofstetter** [comment]
Hey @dimidevops & @nebula-it 

Thanks for verifying that it's working as expected with dedicated Ingresses. No more info required.

I opened the following draft PR that tries to address this issue: https://github.com/cilium/cilium/pull/31646
