### ISSUE TITLE
Add options to derive node address without specifying snooping device

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#313]
It's impossible to have multiple cilium instances across multiple nodes (a.k.a. K8s DaemonSets) with the same cilium configuration on all nodes.

We currently have the flag `-d`/`--snoop-device` to derive the IP addresses for the cilium interfaces but since we don't (yet) support snooping + VxLAN, this doesn't work if the user wants to derive the IP addresses for the cilium interface without snooping mode and run in VxLAN mode.

I'm proposing to add a new option like `--derive-cilium-ip-from`. When this options is set, this will be the interface to select the IPs for the cilium `config.NodeAddress`

**Comment by tgraf** [comment]
I agree that we need to add a capability to derive this piece of configuration.

I think we want to provide multiple options here:
 - If possible, derive the node address from the Kubernetes context. Is this exposed somehow?
   - As a fallback I'm fine with what you propose although I would call the option `--derive-node-address`.
 - Since I ported configuration to cobra and viper, we can also easily add deriving configuration from a kvstore which could be a solution to this problem as well.

**Comment by aanm** [comment]
>If possible, derive the node address from the Kubernetes context. Is this exposed somehow?

Right now it's explained [here](https://github.com/cilium/cilium/blob/e51f94e3339a252f752a0940b5fba3bb5d46a750/contrib/packaging/k8s/daemon-set.yaml#L32), where should I also document this?

**Comment by tgraf** [comment]
> Right now it's explained here, where should I also document this?

That's fine, we'll add it to the documentation.
