### ISSUE TITLE
Memory usage regression on main branch

### ISSUE THREAD

**Issue by marseel** [cilium/cilium#31324]
This issue is meant for the investigation of the memory usage increase of the cilium-agent on the main branch.
The goal is to understand what caused an increase of memory usage and check if it's reasonable. 

Based on 100 node scale test, we can see that memory usage increased by ~20 MB
![image](https://github.com/cilium/cilium/assets/2011575/14e6ea7b-5f96-4f98-be29-1419981ac209)

Regression happened between commits (included):
- fe71a4aef3bdd2fdafa7a8cbdf3dc71d29f18cf7
- 5abe8a8cd5113ea737d1f4482ea73cbd5b83abc4

List of candidates:
- commit 5abe8a8cd5113ea737d1f4482ea73cbd5b83abc4 - https://github.com/cilium/cilium/pull/31074
- commit 8a131c2d197fe882c27408e8190ef04ba18d37c2 - https://github.com/cilium/cilium/pull/30866
- commit 6b63ea2f83fa3a471651c949e96b0a3ddccb9618 - https://github.com/cilium/cilium/pull/31026
- commit 21fa2df60abd0f3a5627aca3265347558d170f37 - https://github.com/cilium/cilium/pull/30034
- commit e1afa06774191d65714576d55f2eadcbe29fc2e6 - https://github.com/cilium/cilium/pull/30467
- commit 217426aae125fc3cc0257db611b7f8e9e519d3ab - same as above
- commit 16033b98b97573437df991efb2dd1da369a683ba - same as above
- commit c4cbb38a1819adb08bd9b479b37ab4a7ec1b4e7a - same as above
- commit 46db41390be3a17872f7274c0ded62ecf7a07bf8 - same as above
- commit ce25c55e4baffd05337a27d07b7a729035e35595 - https://github.com/cilium/cilium/pull/30649
- commit eb0030cdcedc84890331b1bf0efdc163d61fae48 - https://github.com/cilium/cilium/pull/30814
- commit b9098e6b25f97b4af51ebec3c24f5cf6ad48551f - https://github.com/cilium/cilium/pull/31053
- commit d7dba5e4628fcc15b237a157f5fefd49dceb0f88 - https://github.com/cilium/cilium/pull/31061
- commit cbca369611ae77d075c2197d86cbbe0851b408a7 - https://github.com/cilium/cilium/pull/29993
- commit 2063a21d984ebb3b11e296f245470aa711ffac8a - same as above
- commit ed04ccdc1e207fb3c34e1caa198ae89d597b6d1d - same as above
- commit 77053ae0b24e8ba61477cd42d88ba6e8468e09f4 - https://github.com/cilium/cilium/pull/30766
- commit cd53c4fd2b576646ed16ff0cbe24711a6e50fe8f - https://github.com/cilium/cilium/pull/31052
- commit 5d3c7c39641d04d16add92671ec3c090f174677f - https://github.com/cilium/cilium/pull/31039
- commit fe71a4aef3bdd2fdafa7a8cbdf3dc71d29f18cf7 - https://github.com/cilium/cilium/pull/31030

By eyeballing PRs, potential ones:
- https://github.com/cilium/cilium/pull/29993
- Maybe https://github.com/cilium/cilium/pull/30467
- I've already verified that disabling standalone envoy from PR https://github.com/cilium/cilium/pull/30034 doesn't help
- Maybe https://github.com/cilium/cilium/pull/31026
- Probably not https://github.com/cilium/cilium/pull/30866 as we don't have CEC in scale-test

**Comment by sayboras** [comment]
- commit https://github.com/cilium/cilium/commit/5abe8a8cd5113ea737d1f4482ea73cbd5b83abc4 - https://github.com/cilium/cilium/pull/31074 -> probably not as this change is related GHA only
- commit https://github.com/cilium/cilium/commit/cd53c4fd2b576646ed16ff0cbe24711a6e50fe8f - https://github.com/cilium/cilium/pull/31052 -> probably not as this is related to GRPCRoute only, and I don't think GRPRoute is used as part of the test based on your previous comment on CEC.

**Comment by marseel** [comment]
Commit https://github.com/cilium/cilium/commit/21fa2df60abd0f3a5627aca3265347558d170f37 has regression so now rerunning on e1afa06774191d65714576d55f2eadcbe29fc2e6 to double check that this commit introduced regression.

**Comment by dylandreimerink** [comment]
That is very unexpected. What https://github.com/cilium/cilium/pull/30467 does is it makes the compilation of certain tail calls unconditional in C and adds some logic in the loader to do static analysis to determine which tail calls are actually used or not, then removes the unused tail calls.

The only think I can think of in this change that could increase the memory usage would be that the collections (in Go representations of the ELF files) would have grown because there are more tail calls in the ELF files. But for that to show up, we would have to hold on to these collections which I believe we don't do after loading.

I got a pprof from before and after this change, but the loading code in which I would have expected an increase seems to use the exact same amount of memory. Not the 30 MiB we are looking for

![Screenshot from 2024-03-12 15-40-31](https://github.com/cilium/cilium/assets/1799415/bdbd10bd-f0cf-4b73-bf4e-460d274221a2)
![Screenshot from 2024-03-12 15-40-47](https://github.com/cilium/cilium/assets/1799415/87f9eac9-abc1-4a7b-804c-92a5b29a8e24)

**Comment by learnitall** [comment]
I think I found the root of this issue. TL;DR: the culprit PR increased the size of the compiled eBPF programs, resulting in extra memory usage when loading the programs into memory. Environments with high-endpoint churn are most impacted.

I added pprof gathering into the 100-node scale test workflow so we could see the behavior of the memory usage in the same environment as the regression was discovered. I ran the workflow for commit ce25c55e4baffd05337a27d07b7a729035e35595, before the regression, and commit e1afa06774191d65714576d55f2eadcbe29fc2e6, the regression. I used [pprof-merge](https://github.com/rakyll/pprof-merge) to create one merged pprof sample per commit, as the `-diff_base` argument for `go tool pprof` does not support multiple inputs. I then built a copy of the Cilium Agent binary for commit e1afa06774191d65714576d55f2eadcbe29fc2e to give `go tool pprof` the symbol information it needed. After this, I was able to load up the data into a browser with: `go tool pprof -http localhost:8080 -normalize -diff_base ./baseline-merged.data ./cilium-agent-e1afa06 ./regression-merged.data`.

The `alloc_space` index showed a high increase in the function  `endpoint.Endpoint.removeOldRedirects` that stood out:

![top](https://github.com/cilium/cilium/assets/13142290/431c079d-6736-4a28-950c-477ee3cf63b5)

Focusing on the function showed a flamegraph that drilled down into code responsible for loading eBPF programs:

![load](https://github.com/cilium/cilium/assets/13142290/cdf251c1-41b2-49d3-a983-7fd1875ab1de)

I used the sysdumps gathered from each test to find the size of each compiled eBPF program and saw a noticeable difference for `bpf_host.c` and `bpf_lxc.c`:

|Object File|Baseline Commit Size|Regression Commit Size|Diff|
|---|---|---|---|
|bpf_host.o|284 Kb|332 Kb|48 Kb|
|bpf_lxc.o|768 Kb|960 Kb|192 Kb|
|bpf_overlay.o|140 Kb|140 Kb|0 Kb|
|bpf_alignchecker.o|64 Kb|64 Kb|0 Kb|

The PR modifies `bpf_host.c` and `bpf_lxc.c` by removing macros used to cut-out functions not needed by the datapath for the given configuration. This change increases the program size on disk since functions are no longer removed from the compiled object file based on what is needed for the given configuration. The extra bits are loaded into memory and eventually removed by [removeUnreachableTailCalls](https://github.com/cilium/cilium/pull/30467/files#diff-d6f11688bc0f4227c8d78948312a1ca6e290c1c63dcf8c0db12a45d035fb9d5dR51), resulting in the same effective memory usage in the long term, but higher memory usage and churn at load time. The scale test introduces a high amount of pod churn into the cluster, meaning it's constantly loading new eBPF programs and requiring this extra memory to do so.

Overall, this PR would have a negative impact on memory usage in clusters that see a high amount of workload churn.

I'm not sure the best way forward here, since removing macro usage is a [long-term goal for the datapath](https://github.com/cilium/cilium/milestone/45), but the more macros that we remove the worse this problem will get. One very rough idea that comes to mind is caching using a similar pattern to [nix](https://nixos.org/):

1. All configuration inputs used to compile programs are hashed into a SHA256 hash, including some sort of value to indicate Cilium's version (commit, tag, etc).
2. After the static analysis of the tail calls, we dump the modified program to disk and associate it with the input hash.
3. When a program must be loaded again for a different endpoint, we check if the configuration input hash matches any existing hashes.
4. If a match is found, load the already analyzed program into memory. Otherwise, load the base program and perform the static analysis.

The tricky part here would be dealing with upgrade/downgrade scenarios, and with macros that are set per endpoint.

**Comment by dylandreimerink** [comment]
Thanks for confirming this is indeed the issue.

> All configuration inputs used to compile programs are hashed into a SHA256 hash, including some sort of value to indicate Cilium's version (commit, tag, etc).

We already do something to this extent with the ObjectCache in pkg/loader/cache.go. The way it works is that we check if there already is an object matching all inputs and skip re-compiling if no compile-time macros changed. But we always need to load the object again and modify it since every endpoint has unique load-time variables such as the LXC_ID. 

> I'm not sure the best way forward here, since removing macro usage is a [long-term goal for the datapath](https://github.com/cilium/cilium/milestone/45), but the more macros that we remove the worse this problem will get.

This is true, ELF sizes will only increase as Clang-freedom comes closer. But as long as we close the in-go representation, there should not be any memory penalty. The memory graph seems to indicate that we keep additional memory allocated. But I am uncertain if this is actually the case or just a matter of memory not yet being given back by the GC. If we are holding on to the in-go eBPF collection, then it seems to be in the endpoints, I will do a manual review. But if that is not the case, we might just have to accept the additional memory usage, at least for now.

**Comment by learnitall** [comment]
> But we always need to load the object again and modify it since every endpoint has unique load-time variables such as the LXC_ID.

These variables are currently set via macros correct? If so, are removing them part of the Clang-freedom project?

> But as long as we close the in-go representation, there should not be any memory penalty. 

This is true for the long-term life of a cluster, but we're still increasing the amount of memory usage *with each endpoint regeneration*. The more churn an endpoint has, the more of an impact this regression will have on a node's average memory utilization.

> The memory graph seems to indicate that we keep additional memory allocated.

The memory graph is based on metrics that are scraped from the [Node Metrics Summary API endpoint](https://kubernetes.io/docs/reference/instrumentation/node-metric) throughout the test. The graph summarizes the data by calculating percentiles on these in-use memory snapshots. This means that one additional case to consider is that some samples may have been pulled between the time when an ELF was loaded into memory and when the unreachable tail calls were deleted. Given the amount of endpoint churn the scale test creates, this isn't unexpected. During this period, the node will see higher memory usage, regardless of GC behavior or how we release the go objects backing unreachable tail calls.

**Comment by dylandreimerink** [comment]
>>But we always need to load the object again and modify it since every endpoint has unique load-time variables such as the LXC_ID.

> These variables are currently set via macros correct? If so, are removing them part of the Clang-freedom project?

Yes and no. The LXC_ID is defined as: 
```
DEFINE_U16(LXC_ID, 0x2A);
#define LXC_ID fetch_u16(LXC_ID)
```

So yes, its a macro. But the `fetch_u16` will translate into a "special" load instruction which emits a relocation entry. We use these to change its actual value at load time.

> The more churn an endpoint has, the more of an impact this regression will have on a node's average memory utilization.

Right, this makes sense. It also checks out with my investigation so far. We always close and discard the in-go representation once we are done loading. But if we are constantly loading programs then that could explain the jump in average in-use memory without memory leaks.

Like I mentioned we do have the object cache already which means we don't have to re-compile if the compile-time macros don't change. However, the way the load time variable replacement works is on the ELF level. This is a remnant from the days where we loaded using iproute2. So currently what happens is we have the compilation output we call 'templates' and then for every endpoint we do a file copy, then modify the ELF file at the binary level. Then parse the per-endpoint customized ELF into its go representation, load it, then discard.

If we start doing the rewriting in the in-go representation instead of the ELF (something we want to do anyway), we might be able to do something like a shallow copy where most of the memory of a collection can still be shared. But I don't know how feasible that is.

The only other way I can see to reduce active memory usage is to limit the amount of endpoints that can be loaded at the same time. In the end, if we load programs for 20 endpoints concurrently then we will have 20 collections in memory. But limiting concurrent endpoint creation might of course have other consequences

**Comment by learnitall** [comment]
> If we start doing the rewriting in the in-go representation instead of the ELF (something we want to do anyway), we might be able to do something like a shallow copy where most of the memory of a collection can still be shared.

Could there be a middle ground where we shift the process of removing unreachable tail calls to the ELF templates, rather than in per-endpoint customized ELFs? From my understanding, this would avoid having to touch the current load time variable replacement process.

1. On a cache-miss, compile an eBPF program into its ELF.
2. Load the ELF into its go representation and remove unreachable tail calls.
3. Save the ELF back to disk as a template.
4. On endpoint regen, file copy the template ELF with the unreachable tail calls removed and perform load time variable replacement.

> The only other way I can see to reduce active memory usage is to limit the amount of endpoints that can be loaded at the same time.

This would probably increase PodStartupLatency. I think we'd be putting the choice on users: do they care about memory or startup latency?

**Comment by dylandreimerink** [comment]
> 3. Save the ELF back to disk as a template.

We do not have the facilities to marshal collections back into ELF, but we should be able to keep the parsed and tail call eliminated templates in memory, then copy them as needed. But only once we have switched from binary variable replacement to in-go variable replacement.

I talked this issue over with the rest of the loader team. We will start looking into the above, which was on the roadmap for techdept reasons anyway, hopefully this will offset the memory usage a bit. 

On the other hand we are talking about a 5% memory usage increase in this specific load scenario. Its not a memory leak or a bug, so we have to weigh that against the cost of additional features or in this case the future prospect of clang freedom. I can't imagine we have a mandate to never increase average memory usage.

**Comment by joestringer** [comment]
Hi @marseel @dylandreimerink , I see this is marked as a release blocker but there does not appear to be recent activity on the issue. Is this still being investigated, and does it still have high impact? If yes, we may want to figure out how to draw more attention to the issue. If not, we should remove the release-blocker label.

**Comment by dylandreimerink** [comment]
To recap, there is increased memory consumption which bisecting pinpointed to changes in the loader as part of the move to clang-freedom. However, so far all our attempts to find out the exact root cause is unclear, at least to me. And the theories we have come up with to me don't seem easily solvable. I am personally out of ideas as to get better info at this moment and have no good action items.

The loader is undergoing quite a bit of work in a number of areas which hopefully offset some of the observed memory usage, but that is currently not a primary focus.

I think we can conclude that there is nothing specific to do at the moment and accept the additional percentages of memory usage and remove the release blocker label. I do support the effort in general to lower memory usage, but I would cast a wider net than just the changes flagged in this issue.

**Comment by marseel** [comment]
yup, agree. Thanks for taking a look. I was hoping there might some low-hanging fruit but apparently there is none.

**Comment by lmb** [comment]
I've done quite a bit of work in the loader which has the potential to reduce memory usage. As of https://github.com/cilium/cilium/commit/55a9d2ee4ae7da586c7693912c818437191772f7 we should be in a better place. Could you re-run the experiment to see whether anything changed?

**Comment by learnitall** [comment]
Hey @lmb! We had a major drop in memory usage around mid-May, but it looks like the commit you referenced was from about two weeks ago. From the time period where the referenced commit was made, there doesn't seem to be a clear noticeable change.

![mem](https://github.com/cilium/cilium/assets/13142290/ba8f2f18-11dd-436c-ac07-1b4fa11a6f10)
