### ISSUE TITLE
proposal: make daemon configuration a singleton object in its own package

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3160]
The daemon has a `Config` structure which contains configuration information passed through the CLI, and which is updatable during runtime by running commands like `cilium config`. Because this `Config` is part of the daemon package, other packages (e.g., `pkg/endpoint`) which need to access it have to do so through the `Owner` interface. This interface is cumbersome to use. I'd like to see if we can factor this `Config` for the agent out into a separate package as a singleton object (one object globally accessible per agent). This will allow other packages to access the daemon's configuration without having to access it through a callback, and instead access it by importing the package.

Thoughts?

**Comment by ianvernon** [comment]
What are other things we could extract as singletons into separate packages? For instance, I don't see a need for the daemon to have its own policy repository; this could also be a singleton that is part of the policy package.

**Comment by raybejjani** [comment]
I’m generally not keen on globally shared fields, in particular the package as an object pattern. This is mostly because it makes parallel testing harder but this can be solved by having a singleton object in the package instead (and passing that about or calling functions on it). More insidiously, global variables also hide relationships between parts of a program (over time as well as space) making it harder to reason about order of operations (for example: did we call init on this shared thing by the time I want to use it in the program). Essentially, when calling a function do you only need to know what it’s doing for you or do you also need to know how.
A good counterexample of this is often config, which doesn’t change. Except in our case it does. Is it possible to split this config to static fields the don’t change after program start (like the various BPF paths) and others that do? Naively I see 3 types of config here:
1- global non-changing config (like BPF paths, node identifiers): These can be global since they’re effectively constants.
2- global changing config (like debug toggle/log level, global/local CT table): These are more difficult to share. A simple lock fixes the race condition but it doesn’t fix time-dependency. A contrived example would be checking the global/local CT toggle multiple times during a CT cleanup. The GC functions (or others) would then behave differently depending on whether the toggle occurs while they run. In this scenario, it’s better to pass in the value of this config reasonably high in the stack to ensure consistency. We’ll encounter more of these situations as we add more long-lived controllers. Where it’s reasonable to pass these around by value is up for debate.
3- local changing config (like endpoint specific debug toggles): This is similar to (2) but the dependence direction is reversed (in that you’d expect a function on en Endpoint to use object fields if the function changes the Endpoint state). Owner has some functions that sort of do this (FlushCTEntries) but they might difficult to tease out. Generally, I would argue for setting things at constructor time. If they need to be changeable, then have getters and setters on that object. An example is Update/RemoveProxyRedirect. Whatever they call today could be given to the endpoint object constructor (we don’t have one of these today) and then we pass *Endpoint around. Alternatively, they are a global function (more similar to endpoint manager) and they can be called on a package or global singleton. 

Other things, like GetPolicyRepository, seem like a globally unchanging config, or one that can be set in constructors.

I think we also had some import loops that forced the creation of this intermediate interface. I think we can simplify this out in many cases, but perhaps not all, so we might need to retain something like Owner. I’d still prefer to split it appropriately in that case, even if it means longer parameter lists on functions.

**Comment by ianvernon** [comment]
This was done by #4086.
