### ISSUE TITLE
CFP: Hubble should use cache to enrich flows with Kubernetes metadata

### ISSUE THREAD

**Issue by anubhabMajumdar** [cilium/cilium#31666]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

Missing features and duplicate code. Details below.

**Describe the feature you'd like**

`cilium` contains a robust watcher and caching library that's quite generic in nature and can be useful for any Kubernetes project that needs watchers and caching mechanism. 

Some references:
- Start watchers: https://github.com/cilium/cilium/blob/464bbe4e4994f23c17abcfa8e63a9941fdbf3fbd/pkg/k8s/watchers/watcher.go#L463
-  Update cache (service cache for example): https://github.com/cilium/cilium/blob/464bbe4e4994f23c17abcfa8e63a9941fdbf3fbd/pkg/k8s/watchers/service.go#L66

The service cache is exactly what you would expect, a collection of [maps](https://github.com/cilium/cilium/blob/main/pkg/k8s/service_cache.go#L131-L138). However, the cache is severely limited by being keyed to the `ServiceID` object (name+namespace). For it to be really useful, I would also expect a map of `frontendIP` to the `ServiceID`, so that it can be used either way.

Another thing to note is despite having IP cache and Service cache, hubble need to implement a function specifically to get the service name and namespace information through the `service manager`, which has to maintain a map of ip->ID mapping in itself. This style of implementation is true for `endpoint` parsing as well.
Some references:
- https://github.com/cilium/cilium/blob/464bbe4e4994f23c17abcfa8e63a9941fdbf3fbd/daemon/cmd/hubble.go#L418
- Duplicate map: https://github.com/cilium/cilium/blob/464bbe4e4994f23c17abcfa8e63a9941fdbf3fbd/pkg/service/service.go#L2016
- Same for endpoints: https://github.com/cilium/cilium/blob/main/pkg/endpointmanager/manager.go#L53-L54

**(Optional) Describe your proposed solution**

1. Refactor the Service cache to be also keyed to Frontend IPs
2. Refactor Hubble Parsers to make use of the cache

**Comment by sayboras** [comment]
cc @cilium/sig-hubble

**Comment by joamaki** [comment]
Hey, thanks for the proposal. Interesting timing as I'm just looking into refactoring ServiceCache to be implemented using StateDB (the plan is actually to rewrite pkg/service as well eventually). I'm still in early stages with the CFP (the diagrams at https://github.com/joamaki/cilium-svc-cfp should give a rough idea) as I've been focusing on getting a proof-of-concept implementation far enough that I think I've covered most corners. I'm now at a point where most things work and benchmarks show that performance is similar, so I'm going to return to CFP writing and coming up with a plan to get this going. The proof-of-concept can be found at https://github.com/joamaki/cilium/tree/pr/joamaki/service-table.

In the new design the services and backends would be indexed primarily by the `L3n4Addr`: https://github.com/joamaki/cilium/blob/0425930652ea57032414bc61e17287e2f451a7a9/daemon/tables/services.go#L134, https://github.com/joamaki/cilium/blob/pr/joamaki/service-table/daemon/tables/backends.go#L80. This would allow looking up the service(s) by either just IP by doing a prefix query for the IP (since that's the first part of the key), or by the full `(IP, port, protocol, clusterID, scope) tuple. Would that solve what this CFP is trying to accomplish? 

It's likely that this won't yet land in v1.16 though, so if there's immediate use-cases that require this we could consider adding this additional indexing into the existing `ServiceCache`.

**Comment by anubhabMajumdar** [comment]
Sorry for late reply, I missed @chancez 's comment. Yes, I think the implementation can be made more efficient is we use the existing cache.

**Comment by rectified95** [comment]
@joamaki Did you ever finish refactoring `ServiceCache` to use `statedb`?

**Comment by joamaki** [comment]
> [@joamaki](https://github.com/joamaki) Did you ever finish refactoring `ServiceCache` to use `statedb`?

In a sense yes, but not as a drop-in replacement for it, but as a new control-plane implementation for load-balancing
(`pkg/loadbalancer/experimental`). This will eventually replace both `ServiceCache` and `ServiceManager` and provide
a single source of k8s-agnostic access to service and backend information. But this takes time to mature and it's going
to miss the v1.17 release as well (though the plan is to try to get it as feature complete as possible for v1.17 and behind the `loadBalancer.experimental` option).
