### ISSUE TITLE
L2 announcement seems not to work with path mtu discovery

### ISSUE THREAD

**Issue by pstefka** [cilium/cilium#32082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In our environment we access our Kubernetes cluster with L2 announcement VIP through OpenVPN. The traffic from the server doesn't reach the client behind VPN, if the reponse is bigger than ~MTU. The reason for this seems to be a problem with path MTU discovery. The VPN server sends back ICMP Fragmentation needed (with Next hop MTU = 1400) to the L2 announcement VIP, but it seems being ignored, as packets sizes are still bigger (>1400B, and sometimes even 2774B though MTU of all the interfaces in the path are set to 1500B). Find attached a pcap taken on a router in the path between client (192.168.9.45) and L2 announcement VIP (10.0.46.54) - [mtu.zip](https://github.com/cilium/cilium/files/15038232/mtu.zip)

### Cilium Version

v1.15.1

### Kernel Version

Linux worker-e961021e-8n4mg 5.15.0-92-generic #102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.28.8

### Sysdump

File size too big: 25 MB are allowed, 33 MB were attempted to upload.

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by robin-thoni** [comment]
I'm having the exact same issue. I couldn't understand why it was working for a while, then failing, and working again only after refreshing a certain page in a browser:
The server won't catch the ICMP message due to the above VIP issue. BUT! If the client sends a bigger packet than the MTU size _first_, it will catch the ICMP message and handle it. From this point, it will be in cache:
```
10.15.19.3 via 10.15.8.2 dev wlp4s0 src 10.15.15.127 uid 1000 
    cache expires 264sec mtu 1420
```
From there, all future TCP connections from that client will take it into account for the MSS, meaning the server will now fragment packets correctly, without even knowing the real PMTU. Of course, MSS only applies to TCP, so other protocols would still fail.

In summary:
- It would work for a while due to the client caching the ICMP-advertised MTU
- It would only start working again after refreshing a certain page in the browser because that particular request is heavier (cookies, etc)

My current WAR is to manually set `MTU=1420` in the Cilium Helm chart. I had to manually restart Cilium pods for it to apply:
```
$ ip link | grep --color -i mtu
3: cilium_net@cilium_host: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UP mode DEFAULT group default qlen 1000
4: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UP mode DEFAULT group default qlen 1000
7: cilium_vxlan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
11: lxc78cf62873065@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1420 qdisc noqueue state UP mode DEFAULT group default qlen 1000

```
