### ISSUE TITLE
helm: cilium kvstore clustermesh failing without `clustermesh-apiserver-remote-cert` in 1.15

### ISSUE THREAD

**Issue by taraspos** [cilium/cilium#32122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrade from 1.14.8 to 1.15.3 Cilium  is failing to connect to remote etcd with:

```
level=info msg="Waiting for all etcd configuration files to be available" error="open /var/lib/cilium/clustermesh/common-etcd-client-ca.crt: no such file or directory" subsys=kvstore
```

-----
Possible cause:

1. `common-etcd-client-ca.crt` is supposed to be included via `clustermesh-secrets` from `clustermesh-apiserver-remote-cert`:

  - https://github.com/cilium/cilium/blob/a758d21bbae09ab0c4a8cd671e05e043a8c1ea5a/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L863-L893
  
2. `clustermesh-apiserver-remote-cert` is created only when `clustermesh.useAPIServer` is set to `true`

  - https://github.com/cilium/cilium/blob/a758d21bbae09ab0c4a8cd671e05e043a8c1ea5a/install/kubernetes/cilium/templates/clustermesh-apiserver/tls-provided/remote-secret.yaml#L1-L5  

3. Since after the 1.15.x upgrade `kvstore` can't be used together with `clustermesh.useAPIServer`, otherwise helm chart is failing with:
    > Helm upgrade failed for release kube-system/cilium with chart cilium@1.15.3: execution error at (cilium/templates/validate.yaml:85:7): The clustermesh-apiserver cannot be enabled in combination with .Values.identityAllocationMode=kvstore. To establish a Cluster Mesh, directly configure the parameters to access the remote kvstore through .Values.clustermesh.config

  - This change seems to be introduced in: https://github.com/cilium/cilium/pull/28763

4. As result, Cilium agent can't join remote etcd because of missing tls certs

### Cilium Version

1.15.3

### Kernel Version

NA

### Kubernetes Version

N/A

### Regression

1.14.8

### Relevant log output

```shell
level=info msg="Creating etcd client" ConfigPath=/var/lib/cilium/clustermesh/cluster-2 KeepAliveHeartbeat=15s KeepAliveTimeout=25s ListLimit=256 MaxInflight=100 RateLimit=100 subsys=kvstore
level=info msg="Creating etcd client" ConfigPath=/var/lib/etcd-config/etcd.config KeepAliveHeartbeat=15s KeepAliveTimeout=25s ListLimit=256 MaxInflight=100 RateLimit=100 subsys=kvstore
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giorio94** [comment]
Hi @taraspos,

You need to manually specify through [the dedicated section](https://github.com/cilium/cilium/blob/cf9bde54bd6eb6dbebe6c5f3e44500019b33b524/install/kubernetes/cilium/values.yaml#L2860-L2865) the TLS key/certificate used to connect to the kvstore in remote clusters when running Cilium in kvstore mode, as those cannot be automatically managed by Cilium.

**Comment by ti-mo** [comment]
@giorio94 What's the takeaway? Does the upgrade documentation need to be improved? Sounds like this is a bit of a breaking change.

**Comment by taraspos** [comment]
Hey @giorio94, thanks for the reply!

Our configuration works in 1.14.8, but we had `useAPIServer` set to `true` with replicas scaled down, that was a workaround because some resources were not created otherwise.

After upgrading to 1.15 `useAPIServer=true` can't be used together with `kvstore`, so I had to disable it and to face current issue. I will take a look at the tls configuration section you provided when attempting 1.15 upgrade somewhere later.

**Comment by giorio94** [comment]
> What's the takeaway? Does the upgrade documentation need to be improved? Sounds like this is a bit of a breaking change.

Hmm, specifying the clustermesh configuration through helm in combination with Cilium running in kvstore mode had never been supported properly, and required using the trick of enabling the clustermesh-apiserver, but then scaling the replicas to 0. 

That was addressed by https://github.com/cilium/cilium/pull/28763, which also added an explicit validation to prevent running the clustermesh-apiserver when Cilium is running in kvstore mode. Indeed, this combination does not work correctly and is not supported by design, and allowing them to be enabled at the same time caused confusion to several users in the past.

@taraspos Could you please provide some more details about your clustermesh setup, and in particular about how the TLS certificates are configured for the external kvstores? The reason for not automatically creating the TLS certificates when the clustermesh-apiserver is disabled is that they wouldn't be trusted by the external kvstore, except in the very specific case in which the same CA is configured there as well (which I guess it could be the case for you).
