### ISSUE TITLE
CFP: Add optional labelsContext  to forward_count_total and forward_bytes_total metrics

### ISSUE THREAD

**Issue by andreev-io** [cilium/cilium#32193]
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

There have been requests to make it possible to measure flow bandwidth with Cilium/Hubble (https://github.com/cilium/cilium/issues/12913, https://github.com/cilium/cilium/issues/16188); however, this is still currently not possible.

**Describe the feature you'd like**

As far as I understand, Cilium already has information on packet counts and packet sizes, as indicated by the forward_count and forward_bytes metrics. Cilium also has information on Kubernetes metadata associated with a flow. Why not make it possible to annotate forward_bytes and forward_count metrics with this metadata (Kubernetes labels such as pod name at a minimum, L3 connection tuple parameters and Kubernetes labels as a goal)

**(Optional) Describe your proposed solution**

Please complete this section if you have ideas / suggestions on how to implement the feature. We strongly recommend discussing your approach with Cilium committers before spending lots of time implementing a change. 

For longer proposals, you are welcome to link to an external doc (e.g. a Google doc). We have a [Cilium Feature Proposal template](https://docs.google.com/document/d/1vtE82JExQHw8_-pX2Uhq5acN1BMPxNlS6cMQUezRTWg/edit) to help you structure your proposal - if you would like to use it, please make a copy and ensure it's publicly visible, and then add the link here.

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

**Comment by andreev-io** [comment]
I was told in [https://cilium.slack.com/archives/C1MATJ5U5/p1714051757203969](https://cilium.slack.com/archives/C1MATJ5U5/p1714051757203969) that the `foward_count` and `forward_bytes` metrics are not based on Hubble flow objects and are just based on device Tx/Rx counts.

Even if so, shouldn't it be relatively simple to create a new metric that allows measuring throughput based on Hubble flows? Flow objects themselves can be used as a measure of packet counts, and byte counts can be put into flow objects using the `Extensions` field.

**Comment by Nils98Ar** [comment]
We need this for traffic accounting / billing per pod as well. But we would need to get the external traffic only (between pod and world).

So there is actually no way to measure traffic per pod at the moment with cilium/hubble?

**Comment by andreev-io** [comment]
Hey @Nils98Ar! I believe there is not; we had a very similar feature need. Happy to share experiences regarding this on Slack – I'm available in the Cilium workspace (cilium.slack.com).

**Comment by chancez** [comment]
I'd like to add a bit of clarity to this issue since it's come up recently in discussion in relation to the issues linked in the description. Doing this in Hubble is difficult for reasons outlined in https://github.com/cilium/cilium/issues/16188 (primarily that the current event/flow based approach that Hubble uses isn't very compatible with bandwidth tracking as it would require frequently emitting events to get updated bandwidth utilization counts, which would introduce a non-negligible amount of processing overhead into Cilium/Hubble).

Implementing this in the cilium metrics sub-system is difficult for a different reason, that reason being that this metric is implemented is a BPF map `cilium_metrics`: https://github.com/cilium/cilium/blob/2387d597752132e1f2fc351f11bc04c2d76ea6e9/pkg/maps/metricsmap/metricsmap.go#L43C23-L50.

The way this metric is accounted for in the Datapath is by incrementing counters in a map where the key is defined from https://github.com/cilium/cilium/blob/2387d597752132e1f2fc351f11bc04c2d76ea6e9/pkg/maps/metricsmap/metricsmap.go#L85-L93 which basically means the map only knows the direction and reason a packet was forwarded (or dropped). When prometheus scrapes the agent for metrics, it pretty much just reads the value from the map and returns it. This makes it significantly more efficient than the event/flow based approach which Hubble uses.

However, with the design of the current cilium metrics map, this means there's no way to attach any pod, or even source/destination information to this metric today. Supporting it would require that cilium's metrics map is updated in a way that it tracks and associates the source and destination endpoints with the metrics being accumulated, and then in userspace, when the metrics collector runs, it would be possible for it to do a lookup to determine which endpoint the map values correspond to and then translate that into the pod(s) and associate that with the metric being exported. 

For what it's worth, we have many BPF maps in Cilium, and other sub-systems do track similar information already, so there's prior art for how this could be done, but it likely will require some fairly substantial changes to support this feature.

If you're interested, I would encourage you to write a design CFP covering how you would update the datapath to introduce this new functionality, including updating all existing usage of the existing cilium_metrics map. It's possible that it might be simpler to introduce a new map, and then move existing functionality to the new map incrementally, but that would require feedback and input from the datapath team for the path forward. In any case, writing a design CFP would be the necessary first step for implementing it.
