### ISSUE TITLE
Unable to connect to the server: i/o timeout after Cilium installation

### ISSUE THREAD

**Issue by alifiroozi80** [cilium/cilium#32208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello there.
I've initialized a bare-metal cluster with `kubeadm`. I want `kube-proxy`, and I deploy that as well, and everything is good.
I tried to install Cilium as my CNI only (not a replacement of `kube-proxy`), and after running the below command:

```shell
cilium install --version 1.15.4
```

After deployment of all Pods, now nothing works and `kubectl` commands return the below error:

```shell
$ kubectl get pod -A
Unable to connect to the server: dial tcp 10.0.7.122:6443: i/o timeout
```

Even the `cilium status` command not working.

### Cilium Version

```shell
$ cilium version --client
cilium-cli: v0.16.5 compiled with go1.22.2 on linux/amd64
cilium image (default): v1.15.4
cilium image (stable): v1.15.4
```

### Kernel Version

```shell
$ uname -a
Linux master-1 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
1.30.0
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by youngnick** [comment]
Thanks for this issue @alifiroozi80. Did you follow the steps in https://docs.cilium.io/en/stable/installation/k8s-install-kubeadm/ ? 

That looks like your kubectl is unable to connect to the apiserver, which could be caused by _many_ issues, not all of them related to Cilium. Without further info, I don't think we will be able to help you, sorry. (And obviously, if you can't connect to the cluster, I understand it will be difficult to collect further info).

I'd suggest starting over following the directions in the docs, and come back here if there are still problems.
