### ISSUE TITLE
BPF masquerading doesn't allow access to Ingress-created LoadBalancer internal or external IP

### ISSUE THREAD

**Issue by jorhett** [cilium/cilium#32783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This is a duplicate of #32525. This separate issue creation was requested by @sayboras at https://cilium.slack.com/archives/C1MATJ5U5/p1716533484257149?thread_ts=1715382762.010149&cid=C1MATJ5U5

Quote from the original report:
> I cannot seem to access ingress clusterIP addresses from a pod on the same node as the service backend pod if bpf masquerade is enabled in native router mode.

Note that this problem does not appear if I simply create a Service of type LoadBalancer. It only seems to impact ingress-created or Gateway-created LoadBalancer services.

### Cilium Version

1.15.5, 1.15.6, 1.16-pre.3

### Kernel Version

6.8.0-31-generic

### Kubernetes Version

v1.30.0

### Sysdump

[cilium-sysdump-20240530-051359.zip](https://github.com/cilium/cilium/files/15495007/cilium-sysdump-20240530-051359.zip)

### Relevant log output

Traffic from the node (and external IPs) works fine

```shell
$ kubectl get svc
NAME                            TYPE           CLUSTER-IP   EXTERNAL-IP      PORT(S)                      AGE
cilium-ingress-nonplus-apache   LoadBalancer   10.8.1.107   198.207.204.81   80:31940/TCP,443:30282/TCP   17m
nonplus-apache                  ClusterIP      10.8.1.186   <none>           80/TCP,443/TCP               17m

$ curl -sv --output /dev/null --resolve nonplus.us:80:10.8.1.186 http://nonplus.us
* Added nonplus.us:80:10.8.1.186 to DNS cache
* Hostname nonplus.us was found in DNS cache
*   Trying 10.8.1.186:80...
* Connected to nonplus.us (10.8.1.186) port 80
> GET / HTTP/1.1
> Host: nonplus.us
> User-Agent: curl/8.8.0
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 OK
...

$ curl -sv --output /dev/null --resolve nonplus.us:80:10.8.1.107 http://nonplus.us
* Added nonplus.us:80:10.8.1.107 to DNS cache
* Hostname nonplus.us was found in DNS cache
*   Trying 10.8.1.107:80...
* Connected to nonplus.us (10.8.1.107) port 80
> GET / HTTP/1.1
> Host: nonplus.us
> User-Agent: curl/8.8.0
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 301 Moved Permanently
< location: https://nonplus.us/
```

Traffic from other pods fails:

```shell
$ kubectl exec -it -n default ubuntu -- bash

root@ubuntu:/# nc -zv 10.8.1.186 80
Connection to 10.8.1.186 80 port [tcp/*] succeeded!

root@ubuntu:/# nc -zv 10.8.1.107 80
nc: connect to 10.8.1.107 port 80 (tcp) timed out

root@ubuntu:/# nc -zv 198.207.204.81 80
nc: connect to 198.207.204.81 port 80 (tcp) timed out
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @jorhett, thanks for the report. Quick question, the title of the issue here refers to BPF masquerading, but I don't see that referenced anywhere in the issue description. Is there some context that you have around how that setting is impacting the connectivity in this scenario, any output/examples you could show to demonstrate that?

**Comment by jorhett** [comment]
If I disable ebpf masquerade and using netfilter routing there's no such problem, as originally described in the linked thread. 

@jspaleta was only able to replicate the problem after enabling bpfmasquerade as well. https://cilium.slack.com/archives/C1MATJ5U5/p1715625810908169?thread_ts=1715382762.010149&cid=C1MATJ5U5

**Comment by joestringer** [comment]
@jorhett bear with me, I'm not up to speed with the discussion that went on in Slack, and I see there's over a hundred replies. I see in the description some examples of commands that pass or fail once Cilium is in this state, but it's not clear to me how someone would reproduce this issue. Exactly what commands could someone use to install Cilium with the right configurations, create relevant services and configure Ingress etc. so that they can observe the same behaviour? With that, I think there's a higher chance that someone in the community may find this issue and also dig into it to understand what's going on. If there's a particular guide(s) you're following from docs.cilium.io, then you could also share links to those.

Given that bpf masquerading is involved, then it's also possible that the configuration of the native routing CIDR may play a role in this.

@sayboras / @jspaleta of course if you also have some insights from the discussion that would help narrow this down or identify next steps, then I'd welcome your input as well.

**Comment by jorhett** [comment]
>  it's not clear to me how someone would reproduce this issue. Exactly what commands could someone use to install Cilium with the right configurations, create relevant services and configure Ingress etc. so that they can observe the same behaviour? With that, I think there's a higher chance that someone in the community may find this issue and also dig into it to understand what's going on. If there's a particular guide(s) you're following from docs.cilium.io, then you could also share links to those.

I've provided my configs and my sysdump twice now.  😕  It's 100% reproducible on any bare metal kubernetes install. I've got it exactly the same on 5 different nodes, each of which was built an entirely different way.  It's reproducible on internet connected nodes, and on private nodes. Any cilium ingress or gateway API loadbalancer can't be reached from a pod (non-host network) on the same node. It can be reached from the outside and from the host.

> Given that bpf masquerading is involved, then it's also possible that the configuration of the native routing CIDR may play a role in this.

Can you be specific? "May play a role" ... what should we be looking for here?
 
> @sayboras / @jspaleta of course if you also have some insights from the discussion that would help narrow this down or identify next steps, then I'd welcome your input as well.

I was previously thinking that I didn't know enough about eBPF to diagnose this... but if none of you have a clue how to diagnose this, then I think this speaks to a lack of observability. There should be an easy way to diagnose packet flow here. In any classic routing scenario, you can 1-2-3-4 any packet flow to figure it where it reaches and where it doesn't.

**Comment by jorhett** [comment]
FYI I've updated to `1.16.0-pre.3` without any change in behavior except that it lost the LB pool entries for my services 😖 No clear reason why but they weren't accepting connections. After deleting all the services they were re-established on creation.

**Comment by ti-mo** [comment]
@jorhett Your frustration is apparent, but please be mindful of your communication style. Try to maintain a positive attitude and things will work themselves out, I promise. :slightly_smiling_face: 

> I've provided my configs and my sysdump twice now. 😕 It's 100% reproducible on any bare metal kubernetes install.

I think what Joe's trying to say is you haven't provided a minimal reproducer. Sysdumps are great for figuring out specifics about system state after a high-level functional diagnosis has been done, but they don't really contribute towards conveying that high-level picture directly. Missing the forest for the trees, if you will.

It would help if you could provide the commands you used to deploy Cilium, some clear info about your desired outcome (e.g. address ranges of external networks you expect to be reachable) and maybe even the commands you used to provision the k8s cluster itself (in particular, if you're using k3s, the command invocation contains most all of the cluster configuration), ...

> I've got it exactly the same on 5 different nodes, each of which was built an entirely different way.

Then please, by all means, clue us in on how you deployed them, because bare metal deployments are bespoke by nature and vastly different from the environment Cilium is developed and deployed in (commercial clouds). Deploying Cilium on bare metal is slightly off the beaten path given the vast amount of differences between environments, so keep that in mind.

> > Given that bpf masquerading is involved, then it's also possible that the configuration of the native routing CIDR may play a role in this.
> 
> Can you be specific? "May play a role" ... what should we be looking for here?

This is exactly why we need to establish the higher-level picture (network topology) first. You're trying to push for a resolution without providing adequate (or clear) context.

Also, be aware that Slack links are highly ephemeral as Cilium OSS Slack only has a few weeks retention. Don't bother using them as a reference in issues, you're just putting up barriers to the issue reader.

> I was previously thinking that I didn't know enough about eBPF to diagnose this... but if none of you have a clue how to diagnose this, then I think this speaks to a lack of observability. There should be an easy way to diagnose packet flow here. In any classic routing scenario, you can 1-2-3-4 any packet flow to figure it where it reaches and where it doesn't.

Newer versions of Cilium have line/file references to the datapath source code in `cilium-dbg bpf metrics list` that could be useful in debugging where drops occur. Also Hubble or `cilium-dbg monitor` should at least provide some pointers to where the issue may lie. I hate to call RTFM, but since you're implying our incompetence..

@sayboras, any particular reason why this needs to be in a separate issue?

**Comment by jorhett** [comment]
> @jorhett Your frustration is apparent, but please be mindful of your communication style. Try to maintain a positive attitude and things will work themselves out, I promise. 🙂

I did have a positive attitude, and I did contribute everything and respond to every question. I was always positive. The silence I've gotten back--AFTER your own team members confirmed the issue--doesn't support that positivity. 

> > I've provided my configs and my sysdump twice now. 😕 It's 100% reproducible on any bare metal kubernetes install.
 
> I think what Joe's trying to say is you haven't provided a minimal reproducer. Sysdumps are great for figuring out specifics about system state after a high-level functional diagnosis has been done, but they don't really contribute towards conveying that high-level picture directly. Missing the forest for the trees, if you will.

Given that I've provided 3 reproducible setups so far, with every bit of the config included, I'm at a bit of a loss how you can claim I haven't provided this. When someone provides everything you ask for every time you ask for it, they are going to be confused when you keep claiming I haven't provided what you want.
 
If there is something you need that I haven't provided, please state it clearly and I will provide it--as I have done every time you've requested anything.
 
> It would help if you could provide the commands you used to deploy Cilium

Do you want links to all the places I've provided this? 😖  I've given you bare kubernetes setups, I went out and learned Kind and built a replication in Kind just because your staff seemed to like it. What exactly is missing here?

> some clear info about your desired outcome (e.g. address ranges of external networks you expect to be reachable)

This statement defies you having read my reports at all. This reinforces that I've provided the information over and over again, and you haven't read it.

The node I originally reported this on is a node on the public internet. It can reach everything on the Internet. Everything on the Internet can reach anything I've exposed with an Ingress. This isn't the problem. The problem is 100% around loopback access. Services in k8s cannot communicate with an Ingress or Gateway on the same node. 

> and maybe even the commands you used to provision the k8s cluster itself (in particular, if you're using k3s, the command invocation contains most all of the cluster configuration), ...

I'm not using k8s, or kind, or any other variant. I'm using source-origin Kubernetes installed via kubeadm. But I've built and demonstrated the same problem in Kind, as has @jspaleta. I've already provided my kind setup, which was based on Jef's kind setup...

> Then please, by all means, clue us in on how you deployed them

I have. As has Jef.  This speaks again to you not having read what is provided, given you didn't even understand the problem that is clearly stated/shown in the bug report description.

> This is exactly why we need to establish the higher-level picture (network topology) first. You're trying to push for a resolution without providing adequate (or clear) context.

You're not reading what is provided to you already in multiple places. If you need this provided in some special format, please be specific about what you need.

For example, in the kind cluster it's using the stock values from a bare bootstrap of a stock 24.04 Ubuntu node so

Public network: 172.18.0.0/16  (kind creates a new docker network, and 172.17 is used by docker0)
k8s service network: 10.96.0.0/12 
k8s host networks: 10.244.0.0/16 -- with the first /24 used by the sole host in the cluster

```bash
$ docker exec -it kind-control-plane ip -4 route
default via 172.18.0.1 dev eth0
10.244.0.0/24 via 10.244.0.85 dev cilium_host proto kernel src 10.244.0.85
10.244.0.85 dev cilium_host proto kernel scope link
172.18.0.0/16 dev eth0 proto kernel scope link src 172.18.0.2
```

Kind is deployed exactly as your documentation says:

```bash
$ cat kind.yaml
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true   # do not install kindnet
  kubeProxyMode: none       # do not run kube-proxy
nodes:
- role: control-plane
```
 
> Also, be aware that Slack links are highly ephemeral as Cilium OSS Slack only has a few weeks retention. Don't bother using them as a reference in issues, you're just putting up barriers to the issue reader.

My apologies. I've grown used to working in places where Slack is long-term and easier for discussion than trying to have conversations in git PR comments.

> > I was previously thinking that I didn't know enough about eBPF to diagnose this... but if none of you have a clue how to diagnose this, then I think this speaks to a lack of observability. There should be an easy way to diagnose packet flow here. In any classic routing scenario, you can 1-2-3-4 any packet flow to figure it where it reaches and where it doesn't.
> 
> Newer versions of Cilium have line/file references to the datapath source code in `cilium-dbg bpf metrics list` that could be useful in debugging where drops occur. Also Hubble or `cilium-dbg monitor` should at least provide some pointers to where the issue may lie. 

As I shown numerous times before, there are no drops. I can filter for drops and get zero lines. I've shown the monitor output, I've shown the PWRU output. I've asked repeatedly if I'm overlooking a better way to query for this, and SILENCE...

> I hate to call RTFM, but since you're implying our incompetence..

I have been RTFMing a lot, but when I show the output from the documented queries, and even queries I've figured out on my own, and ask questions about other ways to find out what's happening here I get silence. So you are literally (you wrote it!) calling RTFM on someone who has RTFM'd everything you've published, plus everything on Medium, Dev.to, and Youtube, and demonstrated conclusively that these packets aren't being dropped but are simply not being responded to.

It is beyond insulting to be told to RTFM after having posted repeated examples showing I did RTFM, questions about documentation, issues for improvements that could be made to the documentation, etc.

So let's recap:

1. I read your docs, posted queries specific to the docs, posted issues about inaccuracies in the docs
2. I have supplied everything you have requested, every time

And yet your summation here is that I'm not providing detail and didn't RTFM?  This is beyond insulting.

**Comment by jorhett** [comment]
> Try to maintain a positive attitude and things will work themselves out, I promise. 🙂

@ti-mo Do read up and show me exactly how things worked themselves out ? 👀 

You asked me to invest many hours providing you with numerous data dumps, minimal test cases, etc. And did absolutely nothing with them... The only thing that "worked itself out" is that I lost any belief that investing time and effort and money with Isovalent was a waste of time, so we diverted that money to projects which respond to bug reports.
