### ISSUE TITLE
CLI: check whether conntrack is enabled on per-endpoint basis 

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#3282]
If global conntrack is enabled (and thus local conntrack is not enabled per-endpoint), the output of `cilium bpf ct list <endpoint ID>` should communicate as such to the user. Currently, the output is the following if local conntrack table per endpoint is not enabled:

```sudo cilium bpf ct list 38940
Error: Unable to open /sys/fs/bpf/tc/globals/cilium_ct6_38940: Unable to get object /sys/fs/bpf/tc/globals/cilium_ct6_38940: no such file or directory
```

The CLI should be able to detect whether local conntrack is disabled per endpoint and output accordingly to the user.

**Comment by ianvernon** [comment]
Another possibility (not sure how feasible this is, so feel free to shoot it down), would be, if global conntrack is enabled (and thus local conntrack table per endpoint is disabled), we can get the conntrack flows that relate to the local endpoint from the global conntrack table. This could be quite useful for debugging.

**Comment by joestringer** [comment]
Perhaps if someone tries `cilium bpf ct list <epid>` and it fails due to "no such file or directory", we could print a line to suggest something like "Did you mean to run 'cilium bpf ct list global'?". This seems easy to achieve and keeps the tools dumb (which I think is desirable in this case).

A couple of concerns on other points mentioned above:
* Dependency on cilium daemon running in worst case could prevent introspection into these tables because Cilium daemon is down / not in a good state. Then you're stuck back using something like https://github.com/cilium/bpf-map to understand what's going on in maps.
* These `cilium bpf ...` tools are targeted at matching the datapath implementation to introspect that layer. Abstracting away the specific map in use so that it's unclear whether the developer is looking at the global table or endpoint-specific table makes it more difficult to trace and understand exactly which paths in the datapath are being hit.

**Comment by ianvernon** [comment]
@joestringer all valid points. Maybe we could put the logic that I suggested into another command? e.g., `cilium endpoint conntrack` or something like that?

**Comment by joestringer** [comment]
Perhaps, yes. This could streamline debugging issues with conntrack.

**Comment by joestringer** [comment]
FYI #6443 intends to make it much easier to detect when the CT map can't be opened because the filesystem path doesn't exist, which would make my earlier proposal easier to implement.
