### ISSUE TITLE
Cilium Gateway ignores Addresses

### ISSUE THREAD

**Issue by jorhett** [cilium/cilium#32865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium Gateway ignores Addresses provided by the Gateway API specification https://gateway-api.sigs.k8s.io/api-types/gateway/?h=addresses

```
$ k describe gateway
Name:         cilium-gateway
Namespace:    default
Labels:       <none>
API Version:  gateway.networking.k8s.io/v1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2024-06-04T07:14:01Z
  Generation:          1
  Resource Version:    10159066
  UID:                 00e4a3b0-3e73-4a9e-9e4e-efb50774b7c4
Spec:
  Addresses:
    Type:              IPAddress
    Value:             198.207.204.66
  Gateway Class Name:  cilium
  Listeners:
****snip****

Status:
  Addresses:
    Type:   IPAddress
    Value:  198.207.204.79
  Conditions:
    Last Transition Time:  2024-06-04T07:14:01Z
****snip****
```

Cilium should take the addresses and provide them to the service it creates.

### Cilium Version

1.15.5

### Kernel Version

6.5.0-28-generic

### Kubernetes Version

1.30.1

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chaunceyjiang** [comment]
I will try to reproduce this issue locally.

**Comment by BloodWorkXGaming** [comment]
I can confirm this issue. Cilium always takes the first IP of the pool regardless of the setting.

**Comment by chaunceyjiang** [comment]
是的，我本地也是能够问题复现这个问题。

``` shell
# kubectl get gateway my-gateway -oyaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  creationTimestamp: "2024-06-11T06:19:15Z"
  generation: 2
  name: my-gateway
  namespace: default
  resourceVersion: "3277558"
  uid: 41a0fb4c-4781-4e34-a1fd-462762fbc6f3
spec:
  addresses:
  - type: IPAddress
    value: 172.18.0.140
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: web-gw
    port: 80
    protocol: HTTP
status:
  addresses:
  - type: IPAddress
    value: 172.18.0.130
  conditions:
  - lastTransitionTime: "2024-06-11T06:29:19Z"
    message: Gateway successfully scheduled
    observedGeneration: 2
    reason: Accepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2024-06-11T06:29:19Z"
    message: Gateway successfully reconciled
    observedGeneration: 2
    reason: Programmed
    status: "True"
    type: Programmed
  listeners:
  - attachedRoutes: 1
    conditions:
    - lastTransitionTime: "2024-06-11T06:29:19Z"
      message: Listener Programmed
      observedGeneration: 2
      reason: Programmed
      status: "True"
      type: Programmed
    - lastTransitionTime: "2024-06-11T06:29:19Z"
      message: Listener Accepted
      observedGeneration: 2
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-06-11T06:29:19Z"
      message: Resolved Refs
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    name: web-gw
    supportedKinds:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
```

**Comment by youngnick** [comment]
Thanks for this issue @jorhett. @chaunceyjiang has opened #33042 to add support for doing this using Cilium's LBIPAM support, but I'm not sure if that will fit your use case. We've also documented this ask in #21926 if you'd like more background on the issue.

**Comment by jorhett** [comment]
> Thanks for this issue @jorhett. @chaunceyjiang has opened #33042 to add support for doing this using Cilium's LBIPAM support, but I'm not sure if that will fit your use case.

That would be fine. I assumed that it was "better" to ask for the proposed standard rather than something bespoke, but what I need is the functionality... don't quite care how it's implemented.

However, on the very same day that you told me that this PR might solve it, you told that PR provider that it wouldn't be acceptable because it didn't solve the problem for every cloud provider universe-wide 😕 For you to offer this as a suggested fix to me, and then tell that person it's unacceptable... 🤷🏽‍♀️  kindof hard to understand your motivations here.

I generally think that trying to solve every problem in every technology by every vendor is doomed to failure. Not that you shouldn't seek commonalities and groom together common patterns, but refusing to implement a necessary feature because it can't be deployed in every possibly scenario is doomed to failure.

**Comment by youngnick** [comment]
Ironically enough, I said that the proposed solution was not enough precisely because I expected feedback like this from AWS users who tried the feature out and found it didn't work, because people in general don't read the docs. 

My motivations are to ensure that we provide solutions to problems that people actually have, in a way that makes it clear who those solutions apply to, that is not confusing for people. As I said on the other issues, supporting the `address` feature across all platforms is very difficult, because of the wide variety of ways you can ask for a load balancer to have a specific address. In the above case, you're asking for the feature to be implemented without any guidance as to what platform you wanted it on, and so I have no option than to assume you meant on all supported platforms and clouds.

If you are saying that you would prefer that the feature would be available for LB-IPAM only, as that's what you require, that is a useful data point and I thank you for it. If you could confirm that is what you want, that would be very useful.

For more background, I was reluctant to accept a PR for a specific platform without more information about the number of users that having it available will impact, so having some evidence that specific address support for Gateway API and LB-IPAM is useful to people offsets the cost of adding it and the accompanying support costs forever.

However, this is, I believe, the third time I've interacted with you on an issue on Github, across Cilium and Gateway API, and the third time you've attacked me when I didn't answer in the way you wanted. Your attitude is unhelpful and unwelcome, and I would suggest that you will get better results if you refrained from attacking the people who are providing you with free software and features that you require.
