### ISSUE TITLE
Log endpoint's error message independently of debug option 

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#3305]
For example this message is never logged unless the endpoint is running with debug=true
```
				e.getLogger().WithFields(logrus.Fields{
					logfields.PolicyID: srcID,
					logfields.Port:     port,
					logfields.Protocol: proto}).WithError(err).Warn(
					"Update of l4 policy map failed")
```

**Comment by vadorovsky** [comment]
I see two separate issues there.

First of them is that we log endpoint failures with `Warn` - of course we should log them with `Error` method.

But the completely separate thing is that why we don't see messages logged with `Warn` method? Our default log level is `InfoLevel`[0] which is lower that `Warn`, so `Warn` messages should be printed.

[0] https://github.com/cilium/cilium/blob/master/pkg/logging/logging.go#L55

**Comment by ianvernon** [comment]
When one uses `e.getLogger()`, the logs are not sent to Cilium's log; they are only accessible via `cilium endpoint log` IIRC. See #3283 .

**Comment by ianvernon** [comment]
Expectation: this should show up in the cilium logs; `e.getLogger()` should log to the agent logs, not to `cilium endpoint log`.

**Comment by raybejjani** [comment]
I can't reproduce this directly. Endpoints are logging their debug logs when it is enabled on the endpoint or on the daemon in general. Looking at the original report I think there was some confusion between the agent logs and the `cilium endpoint logs` output.
In any case, I will make the messages that are going into the endpoint-specific logs also print as debugs in the agent log (as @ianvernon suggested). I won't address @mrostecki's point about warn vs error since I'm not sure what the reasoning was to begin with (I suspect it was related to complaints that errors seem very dangerous while warning are less so).

**Comment by tgraf** [comment]
> First of them is that we log endpoint failures with Warn - of course we should log them with Error method.

I see Error as something that has permanently failed or is immediately serious and the user typically has do to something about it. Warning is something that can be important but is potentially temporary or less important. Endpoints can always recover and get back into a healthy state.
