### ISSUE TITLE
Restart of cilium pods causes restart of hubble-relay pod and loss of metrics 

### ISSUE THREAD

**Issue by bdecoste** [cilium/cilium#33145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I restart the cilium pods the hubble-relay pod also restarts with the following log:

```
time="2024-06-13T23:33:19Z" level=warning msg="Error while receiving peer change notification; will try again after the timeout has expired" connection timeout=30s error="rpc error: code = Unavailable desc = error reading from server: EOF" subsys=hubble-relay
time="2024-06-13T23:33:48Z" level=info msg="Stopping server..." subsys=hubble-relay
time="2024-06-13T23:33:48Z" level=info msg="Server stopped" subsys=hubble-relay
```

The previously existing metrics (e.g. `hubble_drop_total`) are lost. 

Also tested with `rollout restart` and showed the same behavior with:
  `updateStrategy.rollingUpdate.maxUnavailable: 1` (with 2 nodes)
  `minReadySeconds: 10`

### Cilium Version

1.15.4, 1.15.6

1.13.4 and 1.14.12 do not exhibit this behavior 

### Kernel Version

5.15.0-1064-azure

### Kubernetes Version

Tested on AKS. K8s 1.28.9

### Relevant log output

```shell
time="2024-06-13T19:22:14Z" level=info msg="Stopping server..." subsys=hubble-relay
time="2024-06-13T19:22:14Z" level=info msg="Server stopped" subsys=hubble-relay
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylandreimerink** [comment]
It seems to me that the hubble-relay is killed because it becomes "unhealthy" during the agent upgrade. The health check asserts that the hubble relay is connected to an agent (any of then, it uses a service). We don't set a specific liveness probe interval, so the default 10s is used and the default `failureThreshold` value of 3. However, the default period before the relay attempts to reconnect is 30s as mentioned by the warning log. So the relay only tries to re-connect when its about to be killed for being unhealthy.

I would recommend decreasing `.Values.hubble.relay.retryTimeout` and perhaps `.Values.hubble.relay.dialTimeout` so that the relay re-connects faster after losing its original connection so it has more chance to become healthy before its restarted itself.

**Comment by bdecoste** [comment]
Great, thank you. Exactly the same recommendations as @soggiest

**Comment by bdecoste** [comment]
15s for `retryTimeout` and `dialTimeout` resolved the issue

**Comment by rolinh** [comment]
> 15s for `relay.retryTimeout` and `relay.dialTimeout` resolved the issue

Nice, would you mind opening a PR to fix this? Maybe pick 20s as the timeout values?

**Comment by bdecoste** [comment]
Will do

**Comment by chancez** [comment]
https://github.com/cilium/cilium/pull/33894 should resolve this. If it doesn't, then we can re-open this. If it doesn't work, I believe the best path forward is to simply not tie the relay health to the health of it's peers at all, meaning not relying on peer status for hubble relay health, and relying on rely to appropriately handle the case where it has no peers by responding with an gRPC error of "unavailable" or similar.
