### ISSUE TITLE
Test upgrade for new default cilium-envoy DS

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#33261]
During the community meeting 2024-06-19, we discussed about the change to enable cilium-envoy DS by default.

We should validate the upgrade for existing users to clarify whether this new configuration will apply in existing clusters during upgrade or not, and also we should check to ensure that there aren't any unexpected regressions as part of enabling this option during upgrade.

It's worth noting that for some arm64 users on raspberry PI OS, they will disable L7 proxying entirely due to an issue with tcmalloc in Envoy on that platform. As such, in particular we should avoid configuring the new Envoy DS when `l7Proxy.enabled=false` is configured in Helm.

Marking this as release blocker initially, but we can re-evaluate.

cc @jrajahalme @youngnick

**Comment by sayboras** [comment]
The below change is to make sure that we only enable the daemonset only for new installation, so the risk and impact will be significantly lower. Upgrade and Downgrade test should be already done as part of current CI setup.

While there are still some work to be done, this issue is no longer release blocker IMO. WDYT? 

https://github.com/cilium/cilium/pull/33384

**Comment by sayboras** [comment]
I think we can just close it out,  feel free to re-open if there is any thing pending. Thanks a lot.
