### ISSUE TITLE
CFP: Add options to use Node IPAM LB as default

### ISSUE THREAD

**Issue by ChickenIQ** [cilium/cilium#33282]
## Cilium Feature Proposal

**Describe the feature you'd like**

I've been testing out the pre-release of 1.16.0 and I've found the new Node IPAM LB to be quite perfect for my use case.
The annoying part is that I have to set the loadBalancerClass to "io.cilium/node" on every service.

I would like a way to change the default behavior to either:
**A:** Using this new feature if no other external IP is available
**B:** Prioritising it over existing IP Pools

**Describe your proposed solution**

Add the following helm chart values:
"nodeIPAM.fallback" that will change the behavior as described in point A
"nodeIPAM.default" that will satisfy point B

**Comment by MrFreezeex** [comment]
Hi, I'm unfortunately just seeing this now but thanks for the interest to node IPAM I'm glad it's useful to you :D. 

To me this is a fair request to be able to set node IPAM as a default lb class. I was not aware that Cilium LB IPAM was set by default without the lb class TBH. I think it would be indeed nice to integrate NodeIPAM into the mix as fallback by default if NodeIPAM is enabled and either respect `LBIPAM.requireLBClass=true` for NodeIPAM too or have some NodeIPAM specific setting (which could be named fallback or something like `requireLBClass` too).

**Comment by MrFreezeex** [comment]
So couple of proposals to actually implement this:

### Keep NodeIPAM and LB IPAM separated

This option would involve detecting this status in NodeIPAM: https://github.com/cilium/cilium/blob/d32ff87a6aa69b64f027fae40083d9148d283d1e/operator/pkg/lbipam/lbipam.go#L1042. If this condition is set and no lb class is set we could kick in the reconciliation on NodeIPAM side. We should either respect `LBIPAM.requireLBClass=true` or make a similar setting for NodeIPAM too to control that behavior though.

I believe this would be the easiest solution as it would be somewhat easy to implement. But this is concerning because it brings an indirect non obvious dependency between the two packages/controllers.

### Merge NodeIPAM into LB IPAM package/controller

In that mode under about the same condition as the previous we option we would fallback to NodeIPAM (if enabled ofc) and make lbipam aware of the node load balancer class. We would need to refactor a bit the NodeIPAM code to fit into the controller model of LB IPAM. For instance NodeIPAM uses controller-runtime style controller while LB IPAM does not and we would need to start watching EndpointSlice and Nodes if Node IPAM is enabled.

This would add complexity to LB IPAM but would mean that Cilium would handle all its Load balancer Service from one controller (which can be a good or a bad thing depending on how you look at it) and makes integration like that (falling back/defaulting to NodeIPAM if enabled) easier to do.


### Keep NodeIPAM and LB IPAM separated and get an option to set which one controls no lb class sets

We could just have a new option that sets who would own the load balancer if no lb class is set and would default to LB IPAM for backward compatibilities. This has not exactly the same behavior as the two options because if this new option is set to NodeIPAM it won't first try to use an existing `CiliumLoadBalancerIPPool` even if there is one matching and instead would directly try to use NodeIPAM.
