### ISSUE TITLE
Datapath related metrics export

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3337]
Add prometheus metrics to represent:
- [x] Packet drops
- [x] Forwarded packets
- [x] Rejected L7 (HTTP/Kafka) due to parse errors.
- [x] Forwarded L7 (HTTP/Kafka)
  - [ ] Latency
- [x] Denied L7 (HTTP/Kafka) due to policy
- [ ] Number of Envoy node proxy restarts
- [x] Service load balancing forwarded packets
  - [x] Backend selection statistics
- [ ] Number CT entries
- [ ] Proxymap entries

**Comment by eloycoto** [comment]
Linked with  https://github.com/cilium/cilium/issues/3284

**Comment by manalibhutiyani** [comment]
This is a duplicate of #3284. Spoke to @eloycoto offline, assigning to myself to not duplicate efforts.

**Comment by rlenglet** [comment]
I'd like to also export the number of Envoy node proxy restarts.

**Comment by manalibhutiyani** [comment]
@rlenglet added to the list of metrics. Thanks!

**Comment by manalibhutiyani** [comment]
L7 proxy stats done as part of #4010

**Comment by manalibhutiyani** [comment]
Also discussed this with @rlenglet 
@tgraf : 
Question:
Is collecting metrics per endpoint ID useful from Prometheus perspective because the endpoint ID is reused and the metrics will survive past the life of an endpoint. ?

How will this behave with endpoint ID reuse.  Also endpoint IDs can be same across cluster nodes,
in this way, Prometheus will aggregate metrics across 2 endpoints on different nodes with same endpoint ID. We were discussing how this will behave in Prometheus?

**Comment by tgraf** [comment]
> Is collecting metrics per endpoint ID useful from Prometheus perspective because the endpoint ID is reused and the metrics will survive past the life of an endpoint. ?

The endpointID does not make sense but we can translate it to something more meaningful such as labels. I've asked @mdlayher in Slack so we can get some more opinions.

**Comment by manalibhutiyani** [comment]
@tgraf @rlenglet I was thinking of simply having the key as

```
struct metrics_key {
    __u8      reason;     //0: forwarded, >0 dropped
    __u8      dir:1,      //0: Unknown 1: ingress 2: egress
              pad:7;
};

struct metrics_value {
	 __u64     lastUpdated; // timestamp for entry last updated.  bpf_ktime_get_sec()
         __u64		count;
};

```

Where reason: 
```
#define PACKET_FORWARDED       0
/* Cilium error codes, must NOT overlap with TC return codes */
#define DROP_INVALID_SMAC       -130
#define DROP_INVALID_DMAC       -131
#define DROP_INVALID_SIP        -132
#define DROP_POLICY             -133
#define DROP_INVALID            -134
#define DROP_CT_INVALID_HDR     -135
#define DROP_CT_MISSING_ACK     -136
#define DROP_CT_UNKNOWN_PROTO   -137
#define DROP_CT_CANT_CREATE     -138 /* unused */
#define DROP_UNKNOWN_L3         -139
#define DROP_MISSED_TAIL_CALL   -140
#define DROP_WRITE_ERROR        -141
#define DROP_UNKNOWN_L4         -142
#define DROP_UNKNOWN_ICMP_CODE  -143
#define DROP_UNKNOWN_ICMP_TYPE  -144
#define DROP_UNKNOWN_ICMP6_CODE -145
#define DROP_UNKNOWN_ICMP6_TYPE -146
#define DROP_NO_TUNNEL_KEY      -147
#define DROP_NO_TUNNEL_OPT      -148
#define DROP_INVALID_GENEVE     -149
#define DROP_UNKNOWN_TARGET     -150
#define DROP_NON_LOCAL          -151
#define DROP_NO_LXC             -152
#define DROP_CSUM_L3            -153
#define DROP_CSUM_L4            -154
#define DROP_CT_CREATE_FAILED   -155
#define DROP_INVALID_EXTHDR     -156
#define DROP_FRAG_NOSUPPORT     -157
#define DROP_NO_SERVICE         -158
#define DROP_POLICY_L4          -159
#define DROP_NO_TUNNEL_ENDPOINT -160
#define DROP_PROXYMAP_CREATE_FAILED     -161
#define DROP_POLICY_CIDR                -162
```


This makes things very simple because
1. We do not have to scan the whole map on every endpoint delete
2. For prometheus we will be aggregating all the counters in user space to display the "total_dropped/drop reason", in this scenario we can simply maintain this total counter / drop reason at the source itself instead of aggregating it in user space.
3. Endpoints can be shared across nodes as well as reused. From prometheus perspective I think we need more of a Global ID unique across cluster and hence counters per endpoint ID do not make sense IMHO, but counters per unique drop reason do.
4. This model can be easily extensible to include endpointID later if we feel the need to do so, but to begin with we can start with the simple well defined DROP_REASON counter table?
5. The DROP_REASON table will be well defined in terms of size and we do not need to cleanup or scan on every endpoint delete. The lifetime of the table will be same as the cilium agent

Also, this will also be easier/simpler to complete as a first step for 1.1
Thoughts?

**Comment by rlenglet** [comment]
@manalibhutiyani I like that. I think you can even remove the `lastUpdated` field from the value since you wouldn't need to GC/delete those entries.

**Comment by manalibhutiyani** [comment]
L3/L4 drop / forward Datapath bits are in this PR #4156
