### ISSUE TITLE
Kubernetes network policy for api-server

### ISSUE THREAD

**Issue by Umashankar-Philips** [cilium/cilium#33525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Any issue with the network policy for allowing Kubeapi access to my pod ..?

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-server-access
  namespace: default
spec:
  podSelector: { } # pod selector
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.43.0.1/32 # IP of kube Api Server Endpoints
      ports:
        - protocol: TCP
          port: 6443
    - to:
        - ipBlock:
            cidr: 161.84.211.134/32 # IP of K8s Api Server Endpoints
      ports:
        - protocol: TCP
          port: 6443

Traffic is still blocked ......

When I used cilium CRD it started working fine.

apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cilium-api-server-access
  namespace: default
spec:
  egress:
    - toEntities:
        - kube-apiserver
    - toPorts:
        - ports:
            - port: '443'
              protocol: TCP
Why we should use CRD to get access to kubeapi ..? it will to tightly coupled to the solution right 

### Cilium Version

1.15.5

### Kernel Version

5.14.21-150500.55.65-default  on SUSE Linux Enterprise Micro for Rancher 5.5

### Kubernetes Version

1.28.10rke2

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Cilium has a fairly opinionated approach to CIDR policy by default, which is that any policy rules that allow based on IPs should only apply to traffic which is going outside the cluster. The idea is that anything within the cluster should have richer metadata about _who_ that workload is rather than _where_ - for instance who is the kube-apiserver? It's the kube-apiserver control plane, not just this IP. So if the kube-apiserver IP address changes, then the example Cilium policy can track that and follow it to the new location. Similarly for contacting Pods, it is better to use label-based policy to express who can talk to who, rather than using IP addresses.

That said, as of Cilium v1.15 or later, there is a beta feature to enable such policies to match kube-apiserver and other nodes in the cluster, which should allow for your use case with kubernetes network policies: https://docs.cilium.io/en/stable/security/policy/language/#selecting-nodes-with-cidr-ipblock .
