### ISSUE TITLE
Pod created without the expected identity

### ISSUE THREAD

**Issue by joaoubaldo** [cilium/cilium#33581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Last week we've observed unexpected packet drops in our production EKS cluster. 
The drops as observed by hubble:
```
Jun 27 12:05:32.087: gog/foo-microservice-779664fb97-hc6sd:33820 (ID:246089) <> 10.212.125.185:3000 (ID:16777221) Policy denied DR
OPPED (TCP Flags: SYN)
Jun 27 12:05:32.087: gog/foo-microservice-779664fb97-hc6sd:33802 (ID:246089) <> 10.212.125.185:3000 (ID:16777221) Policy denied DR
OPPED (TCP Flags: SYN)
Jun 27 12:05:32.087: gog/foo-microservice-779664fb97-hc6sd:33814 (ID:246089) <> 10.212.125.185:3000 (ID:16777221) Policy denied DR
OPPED (TCP Flags: SYN)
Jun 27 12:05:32.091: gog/foo-microservice-779664fb97-rdztn:53686 (ID:246089) <> 10.212.125.185:3000 (ID:16777227) Policy denied DR
OPPED (TCP Flags: SYN)
Jun 27 12:05:32.109: gog/foo-microservice-779664fb97-56m9k:33926 (ID:246089) <> 10.212.125.185:3000 (ID:16777218) Policy denied DR
OPPED (TCP Flags: SYN)
```

For reference, the egress rule associated with `foo-microservice` for this flow is:
```
egress:
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/instance: eng-console
        io.kubernetes.pod.namespace: console
    toPorts:
    - ports:
      - port: "3000"
```

During this time, `10.212.125.185` was assigned to the pod `console/eng-console-microservice-78d67f5c94-2c8k5`, however there wasn't a label based identity associated to this pod/IP address as expected. In fact, multiple high number identities (world) for the same IP were logged for different flows, different clients.

Unfortunately we didn't took a sysdump before applying the mitigation, which was to delete the pod. After deletion, the new pod (via Deployment) had the correct identity assigned. 

The expected identity for the pod is:
```
$ cilium identity get 232239
ID       LABELS
232239   k8s:app.kubernetes.io/instance=eng-console
         k8s:app.kubernetes.io/managed-by=Helm
         k8s:app.kubernetes.io/name=eng-console-microservice
         k8s:app.kubernetes.io/version=1.0
         k8s:frontedBy=eng-console-microservice-svc
         k8s:helm.sh/chart=microservice-5.2.14
         k8s:io.cilium.k8s.namespace.labels.functional_area=engineering
         k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=console
         k8s:io.cilium.k8s.namespace.labels.team=console
         k8s:io.cilium.k8s.policy.cluster=production-eu-aug23
         k8s:io.cilium.k8s.policy.serviceaccount=default
         k8s:io.kubernetes.pod.namespace=console
         k8s:jumo.world/chart=microservice-5.2.14
         k8s:owner=console
         k8s:serviceSelector=eng-console-microservice-selector
```

The graph below demonstrates the volume of traffic dropped (policy deny) before, during and after the mitigation:
<img width="1396" alt="image" src="https://github.com/cilium/cilium/assets/3534309/a895f1f1-20e3-4d5f-94a5-bb3377896afe">

Looking at logs, the only evidence of an issue was a timeout during endpoint creation for the problematic pod:
```
time="2024-06-27T11:47:09Z" level=info msg="Successful endpoint creation" containerID=91ccbcdd57 datapathPolicyRevision=442 desiredPolicyRevision=442 endpointID=3978 identity=232239 ipv4=10.212.125.185 ipv6= k8sPodName=console/console-microservice-78d67f5c94-2c8k5 subsys=daemon
time="2024-06-27T11:46:29Z" level=warning msg="Creation of endpoint failed" containerID=a2734aad02 datapathPolicyRevision=0 desiredPolicyRevision=442 endpointID=403 error="timeout while waiting for initial endpoint generation to complete: context canceled" identity=232239 ipv4=10.212.99.186 ipv6= k8sPodName=console/console-microservice-78d67f5c94-2c8k5 subsys=daemon
```

An observation about this warning log is that the IP address (10.212.99.186) mismatches with the successful endpoint creation event that follows (10.212.125.185) for the same pod.

Also worth mentioning that while the affected pod was running, a latency increase for the Cilium API (endpoint-create and endpoint-delete calls) was observed for the host where the pod was running at:
<img width="1403" alt="image" src="https://github.com/cilium/cilium/assets/3534309/b8679dd2-0e12-4f71-abf6-10c1f7e64172">

Is this sequence of events observed in logs susceptible to lead to identity assignment issues?
Is there a way to reproduce the timeout scenario to check if there's any correlation with the identity issue?

We are happy to gather more data to help diagnosing the root cause.

### Cilium Version

Client: 1.14.12 f1de64c6 2024-06-08T22:34:32+00:00 go version go1.21.11 linux/amd64
Daemon: 1.14.12 f1de64c6 2024-06-08T22:34:32+00:00 go version go1.21.11 linux/amd64

### Kernel Version

Linux ip-10-212-145-103.eu-west-1.compute.internal 5.10.219-208.866.amzn2.x86_64 #1 SMP Tue Jun 18 14:00:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: v1.27.13-eks-3af4770

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joestringer** [comment]
Hi @joaoubaldo , nice writeup.

It looks to me like the source node is emitting the policy drop because it isn't aware of the identity of the affected Pod on the destination node. At the same time, the CNI ADD / Pod creation for the affected Pod on the destination node is experiencing some problems. In this specific scenario it looks like the destination has not successfully propagated information about the Pod back to the source node. It's a little hard to understand the status of the destination Pod unless we see a sysdump on the destination node while this event is occurring. That would be my first thought about how to get more information to dig deeper into this issue. Sysdump would collect not only all of the relevant logs, but also `endpoint list` state, agent status, and other clues that may hint to how the agent is operating at this time with respect to the affected Pod.

Based on the cilium-agent logs that you provided, it looks like Cilium first failed to create the network for the destination Pod, then at a later time it succeeded to create the network. Kubelet logs on the node with the affected Pod could also help during this time, for instance it's possible that there is some race condition with the creation and deletion that caused the destination node to stop propagating the information about the affected Pod back to the source node.

> Is there a way to reproduce the timeout scenario to check if there's any correlation with the identity issue?

This would be super helpful if we can identify this. For instance if we have a good sense for what the order of operations are that occured on the destination node that leads to this scenario. With a set of steps to reproduce, it makes this sort of issue drastically easier to understand, debug, and fix.
