### ISSUE TITLE
CFP: Fix cilium envoy implementation so that gateway api can be used with custom envoy configs

### ISSUE THREAD

**Issue by Havnevej** [cilium/cilium#33767]
## Cilium Feature Proposal - Optionally create ciliumenvoyconfig for gateway resource to allow for custom config. 
        
**Is your proposed feature related to a problem?**
Yes.

We right now have to go through the following fragile and tedious process to get cilium and envoy to do what we want as shown in the: [Nemlig.com Case study](https://www.cncf.io/case-studies/nemlig/)

1. Create gateway with gatewayclass `cilium`
2. wait for gateway to be programmed
3. *Delete* the gatewayclass resource for cilium
4. *Delete* the default generated CEC (CiliumEnvoyConfig) 
5. Install our custom CEC that handles JWT authentication using envoy on the platform level, so that backend services dont have to implement this logic.
6. Continiously make sure the secrets exist in the cilium-secrets namespace, as the TLS secrets will dissapear if envoy is restarted on all nodes.

**Notes: **
The reason we **Delete** the cilium gateway class is because cilium will not re-generate the CEC if the gateway class is not there, but it will still respect envoy configs, so we can "*hack*" it to use our custom envoy config (generated via. helm and deployed via argo).

**Describe the feature you'd like**

We would like to avoid having to delete the gateway class for cilium.
So ideally we would be able to specify that for this gateway, dont generate a CEC. I am imaging an annotation or label on the gateway, that would signal to cilium that it should not create a default CEC.

**(Optional) Describe your proposed solution**

A solution like annotating a gateway resource or a flag in the cilium helm chart perhpas an environment variable in the cilium agent, so that it wont generate a CEC if set.

Seems to be that the reconciler is set up to [always](https://github.com/cilium/cilium/blob/main/operator/pkg/ciliumenvoyconfig/ciliumenvoyconfig_reconcile.go#L43) create or update the default envoy config. As i presume, all services with a valid port will trigger the reconciliation because of this implementation.

Further, it seems that it would be possible to prevent the reconciliation if we specify the [EnableL7Proxy](https://github.com/cilium/cilium/blob/main/pkg/proxy/cell.go#L57-L60) as disabled. Because then the reconciler would be "disabled": https://github.com/cilium/cilium/blob/main/pkg/ciliumenvoyconfig/cell.go#L72. However, it seems that it would cause a bunch of other issues.

https://github.com/cilium/cilium/blob/main/pkg/proxy/cell.go#L110-L112
https://github.com/cilium/cilium/blob/main/pkg/envoy/cell.go#L154-L157

CFP: [github](https://github.com/cilium/design-cfps/pull/43)

**Comment by larssb** [comment]
Allow me to add some more context here.

I'm a colleague of @Havnevej and we worked together on our `token based auth. as a service` for our internal `Kubernetes` based `multi-cluster platform` ( as described in [CNCF case study - Nemlig](https://www.cncf.io/case-studies/nemlig/) ).

An alternative to the fix described above by @Havnevej would be to get the capability to control the `Envoy Listener` used for `Ingress network traffic` by capitalizing on the capabilities of `Cilium Network Policies`.

__Basically the reverse of what "we" already have for `egress network traffic` as described below__
---

- Controlling the `Envoy listener` on the `egress network traffic` path. Here's Roche describing that: https://www.youtube.com/watch?t=561&v=kC8efabCH6s ( timestamp to what's most relevant ). This is from this years `KubeCon EU` in **Paris**.

Furthermore, for more context: [Add policy listener support](https://github.com/cilium/cilium/pull/21600) which is the `PR` providing the described capability.

Getting this capability for the `ingress path` would make it unnecessary to:

* reconcile the `Cilium GatewayClass`
  * It's my impression and experience that doing so also gives packet loss for the amount of time that such change occurs
* Remove the need to remove the `Cilium` default `Cilium Envoy Config` created for `Gateway API instances`
  * When such def. `CEC` are re-generated. There's a time window wherein all traffic gets into the cluster - poking a security hole in the protection of our token based auth. as a service setup ( delivered through CEC, GW API and Cilium in general ). While this time window is small. E.g. because we've automated most of the remediation steps - it's still there.
* Establish secrets in the `cilium-secrets` namespace that `Cilium's Envoy setup` uses to decrypt TLS traffic on the path between `Envoy` and x `Cilium Gateway API` instance.

---

I read the code in [PR 21600]() and I don't see much needed work for getting this on the `ingress` path. I may certainly be wrong as I'm no expert in the field of `go programming` or `eBPF integration`. So here's to hoping that I'm correct 💯.

I see mentions of `Ingress` not allowed:

- https://github.com/cilium/cilium/pull/21600/files#diff-58bdd14f2b1b7c51d7976a95282df5b8cdb5d80836b652ae7e9a6bce337adfe9R419
- This commit: https://github.com/cilium/cilium/pull/21600/commits/e37d09f9299742181a62dfbc4102e86a3cc04421 ( from PR 21600 )

Wherein we find:

```text
proxy: use egress in test as CRD proxy ports only work for egress for…
… now

Specify proxy port as egress (or not-ingress) in test cases as the
datapath currently supports ProxyTypeCRD only for L7 LB which is always
on the egress path.

Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>
```

Might explain it some more.

Also in the latest released v1.15.7 we have:

```text
		// For now we have only tested custom listener support on the egress path.  TODO
		// (jrajahalme): Lift this limitation in follow-up work once proper testing has been
		// done on the ingress path.
		if ingress {
			return fmt.Errorf("Listener is not allowed on ingress (%s)", listener.Name)
```

Found at [pkg/policy/api/rule_validation.go](https://github.com/cilium/cilium/blob/v1.15.7/pkg/policy/api/rule_validation.go#L374-L378)

I don't know how much work it'll be to get the capability to control the `Envoy listener on the ingress path` and whether this is support at all ( `datapath currently supports ProxyTypeCRD only for L7 LB which is always on the egress path` ).

However, getting that - if possible - would drastically improve our `token based auth, as a service` offering.

---

## Sharing is caring

We're more than willing to share detailed guides and setup description so that other interested people/teams could potentially setup the same type of token based auth as a service as we do. Taking advantage of the best of Cilium as the swiss network army knife and Keycloak as the IDP/PAM provider.

Thank you so much

N.B. I've also had good talks on the above with the good ol' @nvibert and Mr. @hacktivist123

**Comment by Havnevej** [comment]
[Another CFP](https://github.com/cilium/cilium/issues/34582) would also be addressed, if this problem would be fixed to allow for custom envoy configs, among other really cool use cases with envoy for various traffic management solutions.

**Comment by ebc92** [comment]
Thanks for sharing the workaround, and +1 for the proposal.

Using this workaround I was able to inject the [coraza-proxy-wasm](https://github.com/corazawaf/coraza-proxy-wasm) waf filter to my cilium ingress.

**Comment by hmonsalv** [comment]
hey @larssb @Havnevej, really interesting topic, you are trying to get the reverse I demo'ed in this repo: https://github.com/hmonsalv/cilium-inject-mtls

AFAIK the `CNP` redirect feature is only available for egress traffic as you mentioned - @PhilipSchmid please correct me if I'm wrong.

I'm not quite familiar with `GatewayAPI`, but it might be an easier way than the one you use (which is very "hacky") to get your incoming traffic redirected to your `CEC` where you do the JWT verification.

The idea would be to "translate" this incoming traffic in egress traffic.

I think you could get that by configuring your `HTTPRoute` to route to a dummy service with a dummy endpoint like this:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: app1-jwt-verify-proxy
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: app1-jwt-verify-proxy
  namespace: default
subsets:
  - addresses:
      # Dummy IP, never used but required to redirect the traffic to Envoy
      - ip: 192.192.192.192
    ports:
      - port: 443
```

With this, you could then implement your `CNP` to redirect traffic with destination to ip `192.192.192.192` (egress) to your `CEC` where you do the JWT verification. And then in your `CEC` envoy's cluster endpoint address you set the real k8s app endpoint, e.g.: `app1.default.svc.cluster.local`.

The only problem with this approach, as discussed already with @PhilipSchmid, is that it doesn't scale well, because you would need a dedicated svc+endpoint and their corresponding `CNP`+`CEC` for each application. But still, probably better that the approach you currently have.

**Comment by larssb** [comment]
We found another way of completing what we needed. And a way that does not have the current limitation on the ingress side of controlling the Envoy Listener for certain traffic.

If people are interested in how we found a way to solve the needs we have that does not involve the, in this CFP described hurdles, feel free to reach out to me on the Cilium Slack community. I'm https://cilium.slack.com/team/U01AZV75T4K over there.

@Havnevej can you close this please.

**Comment by VGerris** [comment]
> Thanks for sharing the workaround, and +1 for the proposal.
> 
> Using this workaround I was able to inject the [coraza-proxy-wasm](https://github.com/corazawaf/coraza-proxy-wasm) waf filter to my cilium ingress.

can you elaborate on that ? A straight forward way to use OWASP CRS rules ( WAF ) is something many folks seem to be looking for.

**Comment by BartoszGiza** [comment]
> Thanks for sharing the workaround, and +1 for the proposal.
> 
> Using this workaround I was able to inject the [coraza-proxy-wasm](https://github.com/corazawaf/coraza-proxy-wasm) waf filter to my cilium ingress.

Would You mind to share Your solution that included Coraza into Cilium Envoy ? Thank You

**Comment by jbdalido** [comment]
@larssb same here, would love to know how you did it. Thanks

**Comment by YumeAyai** [comment]
> We found another way of completing what we needed. And a way that does not have the current limitation on the ingress side of controlling the Envoy Listener for certain traffic.
> 
> If people are interested in how we found a way to solve the needs we have that does not involve the, in this CFP described hurdles, feel free to reach out to me on the Cilium Slack community. I'm https://cilium.slack.com/team/U01AZV75T4K over there.
> 
> [@Havnevej](https://github.com/Havnevej) can you close this please.

hello, can you offer a solution?
