### ISSUE TITLE
[Question] How to use cilium API to check whether a policy is activated?

### ISSUE THREAD

**Issue by optimistyzy** [cilium/cilium#33807]
We use cilium API to create customized cilium policy before starting related pod. So the question is there any api to check a cilium policy has been activated? The purpose is to make sure that the created pod will be supervised by the policy . Thanks.

**Comment by joestringer** [comment]
Hi @optimistyzy , there is no stable API for this today. Cilium previously reported status for network policies into the kubernetes resource `.status` field, however this has scalability problems because every individual node in the cluster must report status, and they all attempt to write into the same object. I think that Cilium would need to be extended to properly support this use case.

**Comment by optimistyzy** [comment]
> Hi @optimistyzy , there is no stable API for this today. Cilium previously reported status for network policies into the kubernetes resource `.status` field, however this has scalability problems because every individual node in the cluster must report status, and they all attempt to write into the same object. I think that Cilium would need to be extended to properly support this use case.

Hi @joestringer，
Thanks for your detailed answer. Hoping that cilium can support this in the near future.
