### ISSUE TITLE
Ignore `Link not found` error during `cilium_host` IP restoration to avoid log spam

### ISSUE THREAD

**Issue by christarazi** [cilium/cilium#34039]
```
time="2024-07-22T12:51:26Z" level=warning msg="Failed to remove old router IPs from cilium_host." attempt=1 error="Link not found" subsys=daemon
time="2024-07-22T12:51:26Z" level=info msg="Waiting until local node addressing before starting watchers depending on it" subsys=k8s-watcher
time="2024-07-22T12:51:26Z" level=warning msg="Failed to remove old router IPs from cilium_host." attempt=2 error="Link not found" subsys=daemon
time="2024-07-22T12:51:26Z" level=warning msg="Failed to remove old router IPs from cilium_host." attempt=3 error="Link not found" subsys=daemon

time="2024-07-22T12:51:26Z" level=error msg="Restore of the cilium_host ips failed. Manual intervention is required to remove all other old IPs." error="timed out waiting for the condition" subsys=daemon
```

No need to retry if the device doesn't exist. This could lead to users being misled.

**Comment by shardulsrivastava** [comment]
@christarazi i would like to work on this issue, would appreciate any guidance on this.

**Comment by shardulsrivastava** [comment]
It took me some time to set the environment for cilium, ran into an issue, which turned out to be an actual issue, I have also raised it [here](https://github.com/cilium/cilium/issues/34156), finally managed to get the codespaces working with a workaround.

regarding this issue, I can see that the errors are being originated from the method `removeOldCiliumHostIPs` [here](https://github.com/cilium/cilium/blob/main/daemon/cmd/daemon.go#L273C6-L273C28)

Retry logic is [here](https://github.com/cilium/cilium/blob/main/daemon/cmd/daemon.go#L288-L290)

```go
if err := resiliency.Retry(ctx, 100*time.Millisecond, 3, gcHostIPsFn); err != nil {
	log.WithError(err).Error("Restore of the cilium_host ips failed. Manual intervention is required to remove all other old IPs.")
}
```

@christarazi As I understand, the DOD for this issue would be to remove this retry logic, is that correct, would appreciate your input, as I am very new to this.

**Comment by christarazi** [comment]
@shardulsrivastava Thanks for digging in. The idea is to just ignore the `Link not found` error, not to remove the entire retry logic.

**Comment by shardulsrivastava** [comment]
@christarazi I have raised a PR that adds a condition to only log error if it's not `link not found`, could you please take a alook.

**Comment by christarazi** [comment]
LGTM, thanks!
