### ISSUE TITLE
Can you use cilium egress gateway in gke autopilot?

### ISSUE THREAD

**Issue by kapunakap** [cilium/cilium#34163]
I'm asking because of the nodeSelector requirement for egw.

**Comment by NinoSkopac** [comment]
Another question: can you use egw in GKE Standard without GKE Enterprise? 

Asking because of `Enable multi-networking` in GKE Standard network configuration.

> The multi-networking feature is available only with Google Kubernetes Engine Enterprise (GKEE). To enable GKEE, see Enable GKE Enterprise. 

https://cloud.google.com/kubernetes-engine/docs/concepts/about-multinetwork-support-for-pods

![Screenshot 2024-08-04 at 7 56 11 PM](https://github.com/user-attachments/assets/804a5d0d-ce48-485d-9034-973176cbe556)

**Comment by NinoSkopac** [comment]
I believe you need multi-networking because the egw node needs 2 ENIs attached.
