### ISSUE TITLE
Enabling host firewall blocks arp

### ISSUE THREAD

**Issue by tahvane1** [cilium/cilium#34230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

After enabling host firewall arp stops working. After a while cluster loses external connectivity as it can't resolve mac address of default gateway. 

### How can we reproduce the issue?

Install cilium and enable host firewall

### Cilium Version

cilium-cli: v0.16.15 compiled with go1.22.5 on linux/amd64
cilium image (default): v1.16.0
cilium image (stable): unknown
cilium image (running): 1.16.0

### Kernel Version

Linux service-cluster-server-03 6.8.0-39-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.3+rke2r1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3+rke2r1

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tahvane1** [comment]
if datapathmode is netkit everything breaks (when enabling host firewall). With veth it works.

**Comment by julianwiedmann** [comment]
> if datapathmode is netkit everything breaks (when enabling host firewall). With veth it works.

Thank you! Excellent information that it only affects `netkit` mode.

**Comment by jfroy** [comment]
I don't have host firewall enabled and no network policies I still also all ARP being dropped via `cilium monitor --type drop`. I don't know if the root cause is different, but the symptoms is very similar.

**Comment by jrife** [comment]
I was able to reproduce this issue locally. When using `netkit` mode with host firewall I was no longer able to communicate with my nodes. This is not the case when using `veth`. `cilium monitor --type drop` shows dropped ARP packets in `cil_to_netdev`.

I investigated a little bit and this is what I found. When `netkit` mode is enabled it [causes](https://github.com/cilium/cilium/blob/main/pkg/datapath/linux/config/config.go#L1113) `ENABLE_ARP_PASSTHROUGH` and `ENABLE_ARP_RESPONDER` not to be set.

```golang
	if option.Config.DatapathMode != datapathOption.DatapathModeNetkit {
		if e.RequireARPPassthrough() {
			fmt.Fprint(fw, "#define ENABLE_ARP_PASSTHROUGH 1\n")
		} else {
			fmt.Fprint(fw, "#define ENABLE_ARP_RESPONDER 1\n")
		}
	}
```

When host firewall is enabled on top of that ARP packets are dropped in `cil_to_netdev` and `cil_to_host` since neither `ENABLE_ARP_PASSTHROUGH` nor `ENABLE_ARP_RESPONDER` is set.

```c
#ifdef ENABLE_HOST_FIREWALL
	/* This was initially added for Egress GW. There it's no longer needed,
	 * but it potentially also helps other paths (LB-to-remote-backend ?).
	 */
	if (ctx_snat_done(ctx))
		goto skip_host_firewall;

	if (!eth_is_supported_ethertype(proto)) {
		ret = DROP_UNSUPPORTED_L2;
		goto drop_err;
	}

	switch (proto) {
# if defined ENABLE_ARP_PASSTHROUGH || defined ENABLE_ARP_RESPONDER
	case bpf_htons(ETH_P_ARP):
		ret = CTX_ACT_OK;
		break;
# endif
# ifdef ENABLE_IPV6
	case bpf_htons(ETH_P_IPV6):
		ret = handle_to_netdev_ipv6(ctx, src_sec_identity,
					    &trace, &ext_err);
		break;
# endif
# ifdef ENABLE_IPV4
	case bpf_htons(ETH_P_IP): {
		ret = handle_to_netdev_ipv4(ctx, src_sec_identity,
					    &trace, &ext_err);
		break;
	}
# endif
	default:
		ret = DROP_UNKNOWN_L3;
		break;
	}
```

Changing the code locally to force `ENABLE_ARP_PASSTHROUGH` to be set resolves the node connectivity issues. We probably need to change the logic a bit here to allow ARP passthrough to the netdev even when disabling it for `netkit` endpoints.
