### ISSUE TITLE
CFP: add Volcengine cloud ENI IPAM support

### ISSUE THREAD

**Issue by ruicao93** [cilium/cilium#34604]
**Describe the feature you'd like**

Volcengine(Volcano Engine) is a cloud platform provided by ByteDance. In cloud environment, the form of placing Pods and hosts at the same network layer (VPC network) to get better performance and operability has been widely accepted. The Cilium users on Volcengine platform are calling for the ENI IPAM support just like the mode they are using on AWS and Alibaba Cloud:

- https://github.com/cilium/cilium/pull/8347
- https://github.com/cilium/cilium/pull/15160

So we would like to support the Volcengine cloud ENI IPAM in Cilium.

**(Optional) Describe your proposed solution**

Support for Volcengine cloud ENI IPAM will be split into several sub-tasks:

- [ ] Add Volcengine ENI IPAM fields into CiliumNode CRD. #34608

- [ ] Add Volcengine IPAM provider in Cilium Operator.

- [ ] Setup routing for Pod using Volcengine ENI in dataplane.

- [ ] Add Volcengine IPAM docs

**Comment by joestringer** [comment]
cc @cilium/sig-ipam

**Comment by ruicao93** [comment]
Hi @gandro , thanks for your reply.

As the support for customer requirements, we have resources to maintain the Volcengine IPAM mode, it's not a problem.

The primary reason customers require Volcengine IPAM is to have native support in Cilium to avoid extra OPEX and tests, especially considering the version compatibility.

When leveraging cloud network, Cilium-agent need cloud-specific interface info from CiliumNode CR(e.g. out iface mac/index) and setup cloud specific net configs(e.g. policy routing for Pods). Delegated IPAM mode has no ability to do cloud-specific logic. It might be feasible if we allow to add some common cloud logics after calling "Delegated IPAM plugin".

Besides, Cilium-operator provides an excellent framework which make it easy to implement a new and stable cloud provider.

**Comment by joestringer** [comment]
> Delegated IPAM mode has no ability to do cloud-specific logic.

I don't understand this statement. Delegated IPAM calls into another binary that the cloud provides. Any cloud-specific logic can be implemented in there. This is how Azure solves this problem with their own cloud-specific IPAM logic.

**Comment by gandro** [comment]
As for putting cloud-specific metadata into the CiliumNode resource  having a separate CRD (e.g. `VolcengineCiliumNode`) that is then read by the delegated CNI agent should work too. 

We actually have discussed moving the IPAM section for the existing IPAM modes into a seperate CRD. The problem with our current approach of putting IPAM information into the CiliumNode resource is that the CiliumNode is watched by all other agents in the cluster, even though most IPAM information is not relevant for them. This causes unnecessary overhead. 

Instead, it would be smarter to have a separate "IPAM" CRD that is only used for communication between the global component and the per-node component. The only IPAM-related information relevant to other nodes, such as pod CIDRs for auto-direct-node-routes or tunnel mode, would still have to be part of the CiliumNode CRD, but this does not apply to cloud fabrics such as ENI, Azure or AlibabaCloud (and presumably also Volcengine), since the intra-node routing is done by cloud fabric intead.

**Comment by ruicao93** [comment]
> I don't understand this statement. Delegated IPAM calls into another binary that the cloud provides. Any cloud-specific logic can be implemented in there. This is how Azure solves this problem with their own cloud-specific IPAM logic.

Hi @joestringer , do you mean Azure delegated IPAM also setup extra net configs for Pod such as install ingress/egress routes for Pods, in addition to allocating IP/ENIs.

**Comment by joestringer** [comment]
I see where you're coming from. As far as I understand, Azure doesn't have the same style of IP<->NetworkInterface association as ENI (or similar) modes. This means that for Azure IPAM is entirely separate from local-node routing. Local-node routing is a bit more complicated in the ENI cases. Unfortunately, it's also quite important for Cilium to be involved in configuring the local-node routing aspects, because in order to implement some of the Cilium features, Cilium must force some specific traffic to follow specific paths through the Linux routing stack. Therefore, it's not always good enough to just delegate the local node routing configuration to another plugin. The routing must take into account all possible traffic and ensure the traffic flows the correct way to implement the features requested by the user.

In an ideal world, I would probably have a setup something like:
- Cilium calls the delegated IPAM mode to get IP addresses
- Delegated IPAM can inform Cilium about the IP<->NetworkInterface mapping, whether directly through the CNI result, or indirectly through a centralized cluster component -> kvstore/CRD.
- Cilium does not have to extend its own CiliumNode CRD to have various cloud-specific pieces.
- Cilium agent learns about the IP<->NetworkInterface mapping and takes responsibility for ensuring that traffic for that IP is tightly associated with the specific network interface, whether by configuring the Linux routing stack or its own BPF implementation of intra-node routing.

The above is mostly thinking out loud at the moment, other contributors may have other ideas. I don't know how far away from reality it is to implement this architecture.

**Comment by ruicao93** [comment]
As @joestringer mentioned,  ENI mode can be abstraced as a scenario case where there are multiple interfaces on a Node, and each Pod use a designated network interface for ingress/egress traffic.

So @gandro @joestringer  shall we consider to extend the IPAM plugin returned struct, add <Pod, out interface> mapping info:

- IP/prefixLen
- (optional)direct access CIDRs
- out interface(ENI)
- mac
- ifindex

And then let Cilium-agent install the routes(BPF rules or Linux routes) for the Pod.

**Comment by joestringer** [comment]
I think it'd be worth exploring that option and see how the implementation turns out. The one thing I'm not sure about is whether the CNI spec allows for extra fields like that, but if you've written a plugin that works that way and write the Cilium code to trust that logic then we can at least validate that it works. We can deal with the CNI spec side of things afterwards, either by declaring this a clearly vendor-specific extension or by attempting to standardize with the folks in charge of the CNI spec.

**Comment by ruicao93** [comment]
Hi @joestringer, it looks like we could leverage the "interfaces" field in the delegation IPAM result to get the expected uplink interface info. And then install routes between Pod and uplink interface. Here's a draft PR for the proposal: https://github.com/cilium/cilium/pull/34779

**Comment by wedaly** [comment]
>  The one thing I'm not sure about is whether the CNI spec allows for extra fields like that, but if you've written a plugin that works that way and write the Cilium code to trust that logic then we can at least validate that it works. We can deal with the CNI spec side of things afterwards, either by declaring this a clearly vendor-specific extension or by attempting to standardize with the folks in charge of the CNI spec.

hmm, my reading of the CNI spec is that the delegated IPAM response *must* omit the `interfaces` field:
https://www.cni.dev/docs/spec/#delegated-plugins-ipam

> Delegated IPAM plugins must return an abbreviated Success object. Specifically, it is missing the interfaces array, as well as the interface entry in ips.

@squeed do you have context for why the CNI spec has this restriction?

**Comment by ruicao93** [comment]
@squeed In cloud enviroment, ENIs(virtual nic) are allocated by IPAM plugin on demand. So I think it make sense to include the host interface(ENI) info created for the Pod in IPAM result.

**Comment by dakehero** [comment]
> ENIs(virtual nic) are allocated by IPAM plugin on demand

If ENIs are created by IPAM plugin(may be asynchronously), it's natural to append it to the CNI result ,just like what other plugin("ptp" and “bridge”) did.
