### ISSUE TITLE
featuremanager: Lack of safety features

### ISSUE THREAD

**Issue by ovidiutirla** [cilium/cilium#34930]
WIP

**Comment by youngnick** [comment]
@ovidiutirla, would you be able to expand on this a bit? That would help others to understand what this issue is aiming at, and make it easier to collaborate with you.

If it's a subtask of a "featuremanager" feature, maybe opening an epic-style issue that can hold subtasks and also holds the larger context might also be useful.

**Comment by youngnick** [comment]
I'm going to add `kind/enhancement` to this because it seems like a featuremanager is an enhancement, but some more detail would be great, thanks!

**Comment by ovidiutirla** [comment]
Closing for now. yes, this was related to a draft PR I was working on. Had it with WIP as we were still discussing some parts.
