### ISSUE TITLE
error dumping ipcache BPF map: Unable to get object /sys/fs/bpf/tc/globals/cilium_ipcache: no such file or directory

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3519]
```
KVStore:                Ok   Etcd: http://127.0.0.1:32379 - 3.3.2; http://127.0.0.1:33379 - 3.3.2; http://127.0.0.1:34379 - (Leader) 3.3.2
ContainerRuntime:       Ok
Kubernetes:             Ok   OK
Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumNetworkPolicy", "networking.k8s.io/v1::NetworkPolicy", "core/v1::Service", "core/v1::Endpoint", "extensions/v1beta1::Ingress", "core/v1::Node"]
Cilium:                 Ok   OK
NodeMonitor:            Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok
IPv4 address pool:      4/65535 allocated
IPv6 address pool:      3/4294967295 allocated
Controller Status:      12/13 healthy
  Name                             Last success   Last error   Count   Message
  ipcache-bpf-garbage-collection   never          2s ago       11      error dumping ipcache BPF map: Unable to get object /sys/fs/bpf/tc/globals/cilium_ipcache: no such file or directory
Proxy Status:   OK, ip 10.15.28.238, port-range 10000-20000
Cluster health:   1/1 reachable   (2018-04-04T19:05:02Z)
```

**Comment by ianvernon** [comment]
I am able to reproduce this using the [minikube getting started guide](http://cilium.readthedocs.io/en/latest/gettingstarted/minikube/). The result of `OpenAfterMount` wasn't being logged in `pkg/maps/ipcache/ipcache.go:init()` so I am building a new Docker image which logs the result of trying to mount the map.

**Comment by ianvernon** [comment]
The map is only created on the datapath side based on certain `#define`s: 
```
#if defined POLICY_EGRESS && defined LXC_ID
/* Global IP -> Identity map for applying egress label-based policy */
struct bpf_elf_map __section_maps cilium_ipcache = {
	.type		= BPF_MAP_TYPE_HASH,
	.size_key	= sizeof(struct endpoint_key),
	.size_value	= sizeof(struct remote_endpoint_info),
	.pinning	= PIN_GLOBAL_NS,
	.max_elem	= IPCACHE_MAP_SIZE,
};
#endif
```

**Comment by ianvernon** [comment]
In Minikube, upon startup, these are not defined:
```
root@minikube:/var/run/cilium/state# grep -r "POLICY_EGRESS" *
29898/lxc_config.h:#undef POLICY_EGRESS
netdev_config.h:#undef POLICY_EGRESS
```

**Comment by ianvernon** [comment]
What I don't know is if this affects the userspace side, as the userspace side tries to open the map in `pkg/maps/ipcache/ipcache.go:init()`
```
func init() {
	err := bpf.OpenAfterMount(IPCache)
	if err != nil {
		log.Errorf("unable to open cilium_ipcache map: %s", err)
	}
}
```

**Comment by manalibhutiyani** [comment]
`POLICY_EGRESS` is only supposed to be defined on egress policy enforcement, i.e after endpoint regeneration. Why would be need this check on minikube startup?  Is this trying to do a  restore operation of endpoint states?

**Comment by joestringer** [comment]
In general, maps may be created from one of two places: It may be created when the `bpf/bpf_*.o` program includes the map, and we load that BPF program. Alternatively, it may be created when userspace does something like the `OpenOrCreate()` mentioned above.

Due to the `POLICY_EGRESS` #ifdef, the BPF programs don't refer to it and the map will not be created upon BPF prog load. We could consider removing that #ifdef, but leave the actual lookup of the map nested within the `#ifdef POLICY_EGRESS` so the first BPF program to be loaded will ensure that the map is created but it will only be enforced when policy is enabled.

The other background to this is that the regular userspace path to create the map is not working, most likely due to a race between performing `mount()` and `stat()` here:

https://github.com/cilium/cilium/blob/4a48a8ba143ec077da20447622ccd862463a29db/pkg/bpf/bpffs.go#L112

https://github.com/cilium/cilium/blob/4a48a8ba143ec077da20447622ccd862463a29db/pkg/bpf/bpffs.go#L148-L161

**Comment by ianvernon** [comment]
> POLICY_EGRESS is only supposed to be defined on egress policy enforcement, i.e after endpoint regeneration. Why would be need this check on minikube startup? Is this trying to do a restore operation of endpoint states?

@manalibhutiyani I was trying to deduce whether the ipcache BPF map was created / opened on the datapath side, but saw that it wasn't due to these `#undef` statements for `POLICY_EGRESS`. Restore is orthogonal here; this is an issue with opening / creating the maps the list of maps which are added to `delayedOpens` in `pkg/bpf`.

With the following commit : https://github.com/cilium/cilium/commit/789f9b2fa10fa6f677215b0c56d0214d7ee83b76

and running the Docker image of cilium containing said commit in Minikube the following is observed:
```
level=warning msg="BPF root is not a BPF filesystem (0x62656572 != 0xcafe4a11)" file-path=/sys/fs/bpf
level=error msg="error opening map after bpffs was mounted cilium_lxc"
level=error msg="error opening map after bpffs was mounted tunnel_endpoint_map"
level=error msg="error opening map after bpffs was mounted cilium_ipcache"
level=error msg="error opening map after bpffs was mounted cilium_proxy4"
level=error msg="error opening map after bpffs was mounted cilium_proxy6"
level=info msg="Mounted BPF filesystem /sys/fs/bpf"
```

As a result, the map is never opened or created on the userspace side because `POLICY_EGRESS` is undefined w.r.t. the datapath. Does that address your questions?

**Comment by ianvernon** [comment]
Added more logs to see what the error was when we tried to open the maps in `delayedOpens` in `pkg/bpf` and got the following output:

```
level=warning msg="BPF root is not a BPF filesystem (0x62656572 != 0xcafe4a11)" file-path=/sys/fs/bpf
level=error msg="error opening map after bpffs was mounted cilium_lxc: Unable create map base directory: mkdir /sys/fs/bpf/tc: no such file or directory"
level=error msg="error opening map after bpffs was mounted tunnel_endpoint_map: Unable create map base directory: mkdir /sys/fs/bpf/tc: no such file or directory"
level=error msg="error opening map after bpffs was mounted cilium_ipcache: Unable create map base directory: mkdir /sys/fs/bpf/tc: no such file or directory"
level=error msg="error opening map after bpffs was mounted cilium_proxy4: Unable create map base directory: mkdir /sys/fs/bpf/tc: no such file or directory"
level=error msg="error opening map after bpffs was mounted cilium_proxy6: Unable create map base directory: mkdir /sys/fs/bpf/tc: no such file or directory"
level=info msg="Mounted BPF filesystem /sys/fs/bpf"
```

This is more of a bug in the mounting of the bpffs. We can mitigate this with Joe's proposal above because the datapath itself will open / create the map, but this is not a bug with the ipcache code per-se. I suspect that the other BPF maps which show up in the logs get opened / created by other parts in the datapath and as such are immune from errors when Cilium tries to update them because they are already opened / created.

**Comment by ianvernon** [comment]
Added a sleep for ten seconds just to see if that gave enough time for mounting the `delayedOpens`; didn't work:

```
2018-04-05T20:54:12.722726671Z level=warning msg="BPF root is not a BPF filesystem (0x62656572 != 0xcafe4a11)" file-path=/sys/fs/bpf
2018-04-05T20:54:12.722748907Z level=warning msg="sleeping for 10 seconds to allow for handling of BPF filesystem issues"
2018-04-05T20:54:22.725734295Z level=error msg="error opening map after bpffs was mounted cilium_lxc: Unable create map base directory: mkdir /sys/fs/bpf/tc: no such file or directory"
2018-04-05T20:54:22.72576197Z level=error msg="error opening map after bpffs was mounted tunnel_endpoint_map: Unable create map base directory: mkdir /sys/fs/bpf/tc: no such file or directory"
2018-04-05T20:54:22.725766518Z level=error msg="error opening map after bpffs was mounted cilium_ipcache: Unable create map base directory: mkdir /sys/fs/bpf/tc: no such file or directory"
2018-04-05T20:54:22.725769897Z level=error msg="error opening map after bpffs was mounted cilium_proxy4: Unable create map base directory: mkdir /sys/fs/bpf/tc: no such file or directory"
2018-04-05T20:54:22.72577288Z level=error msg="error opening map after bpffs was mounted cilium_proxy6: Unable create map base directory: mkdir /sys/fs/bpf/tc: no such file or directory"
2018-04-05T20:54:22.72577596Z level=info msg="Mounted BPF filesystem /sys/fs/bpf"
```

**Comment by ianvernon** [comment]
Priority was reduced because this issue has only been seen in Minikube.

I followed @joestringer 's proposal https://github.com/cilium/cilium/issues/3519#issuecomment-378757566 and while the maps were unable to be opened:

```
2018-04-06T07:43:38.35921064Z level=warning msg="BPF root is not a BPF filesystem (0x62656572 != 0xcafe4a11)" file-path=/sys/fs/bpf
2018-04-06T07:43:48.366448139Z level=error msg="error opening map after bpffs was mounted cilium_lxc: Unable create map base directory: mkdir /sys/fs/bpf/tc: no such file or directory"
2018-04-06T07:43:48.367279718Z level=error msg="error opening map after bpffs was mounted tunnel_endpoint_map: Unable create map base directory: mkdir /sys/fs/bpf/tc: no such file or directory"
2018-04-06T07:43:48.367291342Z level=error msg="error opening map after bpffs was mounted cilium_ipcache: Unable create map base directory: mkdir /sys/fs/bpf/tc: no such file or directory"
2018-04-06T07:43:48.367294813Z level=error msg="error opening map after bpffs was mounted cilium_proxy4: Unable create map base directory: mkdir /sys/fs/bpf/tc: no such file or directory"
2018-04-06T07:43:48.367297607Z level=error msg="error opening map after bpffs was mounted cilium_proxy6: Unable create map base directory: mkdir /sys/fs/bpf/tc: no such file or directory"
2018-04-06T07:43:48.367339704Z level=info msg="Mounted BPF filesystem /sys/fs/bpf"
```

the BPF ipcache map is able to be accessed without any egress policy imported:

```
$ kubectl exec cilium-gff7m  -n kube-system -- cilium bpf ipcache list
IP ADDRESS           IDENTITY   
10.15.28.238         1          
192.168.99.100       1          
fc00::10ca:1         1          
f00d::a0f:0:0:74ca   38509      
10.15.242.54         38509      
f00d::a0f:0:0:8ad6   1 
```

will post a PR for this shortly.
