### ISSUE TITLE
Document the process to re-generate Vagrant boxes and Docker images

### ISSUE THREAD

**Issue by rlenglet** [cilium/cilium#3544]
Formally document how to re-generate Vagrant boxes and Docker images, esp. to udpate the Bazel caches when Cilium's Envoy codebase is rebased.

First rough checklist from @aanm:

- Push a branch to `cilium/cilium`.
- Prepare a commit like https://github.com/cilium/packer-ci-build/pull/40
- Once the `packer-ci-build` is merged, rebase the branch you have created in `cilium/cilium` with the new VM image.
- Run `make docker-image-builder` with the branch changes.

**Comment by eloycoto** [comment]
IMHO I think that it's better to merge in master first and update the VM after. The main reason is that if we need to build the VM a few days later, the branch will no longer exist and we'll have some trouble. 

If you want, to save time, we can create a parametrised build, where you can build a new VM based on a branch that you specified but default branch is master. 

Some doc related to the `packer-ci-build` here:
http://docs.cilium.io/en/latest/contributing/#packer-ci-build

**Comment by rlenglet** [comment]
cc @jrajahalme

**Comment by aanm** [comment]
>IMHO I think that it's better to merge in master first and update the VM after. The main reason is that if we need to build the VM a few days later, the branch will no longer exist and we'll have some trouble

@eloycoto this is supposed to be executed by the envoy maintainer in a couple ours, once the branch is merged, a new VM needs to be rebuild.

**Comment by eloycoto** [comment]
And what happens when you need to make a change in the VM that it's not related to Envoy? The git clone will fail because the branch no longer exists. 

I think that the best approach is to have a parametrized build in Jenkins, that when @jrajahalme  or @rlenglet need to update the VM, they can trigger the build with the branch that they want. For other developers and default branch will be master. IMHO.
