### ISSUE TITLE
Policy revision reported incorrectly

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3552]
When importing a policy, the policy is applied to the endpoint, correctly shown in the endpoint structure, the redirect is created (proxy stats show up) but the redirect in the datapath is not being put in place or not effective. The policy revision is still bumped which causes the policy to not be enforced even though it is reported to be enforcing.

Full log attached, a couple of suspicious errors:
```
level=error msg="error while receiving request from xDS stream" error="rpc error: code = 1 desc = context canceled" xdsStreamID=39
level=error msg="xDS stream context canceled" error="context canceled" xdsStreamID=37
level=error msg="error while receiving request from xDS stream" error="rpc error: code = 1 desc = context canceled" xdsStreamID=37
level=error msg="xDS stream context canceled" error="context canceled" xdsStreamID=38
level=error msg="error while receiving request from xDS stream" error="rpc error: code = 1 desc = context canceled" xdsStreamID=38
level=error msg="xDS stream context canceled" error="context canceled" xdsStreamID=39
level=warning msg="Envoy: Proxy crashed" error="signal: segmentation fault (core dumped)"
```

The following could be due to deletion of a k8s namespace
```
level=warning msg="Generating BPF for endpoint failed, keeping stale directory." containerID=4f39f8d734 endpointID=46367 file-path=/var/run/cilium/state/46367_next_fail policyRevision=192
level=warning msg="Regeneration of endpoint program failed" containerID=4f39f8d734 endpointID=46367 error="Skipping build due to invalid state: disconnected" policyRevision=192
```

[cilium-no-l7-redirect.log](https://github.com/cilium/cilium/files/1880763/cilium-no-l7-redirect.log)

**Comment by rlenglet** [comment]
We need to understand why Envoy is crashing sometimes. We are now logging the Envoy logs into the Cilium debug logs. When you see that happen, please collect the debug logs.
But Envoy is always restarted immediately by Cilium when it crashed, and usually such a crash has no effect on policy regeneration. Envoy restarts, picks up the latest configuration, applies it, and ACKs it.

Same with the "xDS stream context canceled" error messages. They just indicate that Envoy has closed its xDS connection to Cilium. That obviously happened in this case because it crashed.

**Comment by danwent** [comment]
[bad.log](https://github.com/cilium/cilium/files/1881949/bad.log)

**Comment by danwent** [comment]
[bad2.log](https://github.com/cilium/cilium/files/1881987/bad2.log)
[monitor.log](https://github.com/cilium/cilium/files/1881988/monitor.log)
