### ISSUE TITLE
L2 Neighbor Discovery: unable to determine next hop IPv4 address - remote node IP is non-routable

### ISSUE THREAD

**Issue by TechABC** [cilium/cilium#35926]
Hello,

We are using Cilium with the kube-proxy replacement feature, along with L2 neighbor discovery, as recommended in the documentation. This feature has been working well; however, we have noticed some errors appearing in the `cilium-cli status`.

Some of our nodes are connected to a dedicated IP storage network with no other routes outside of its own subnet. This network interface appears to be causing the following error messages on those specific nodes:
`controller node-neighbor-link-updater is failing since 4s (1x): unable to determine next hop IPv4 address for <storage_interface_name> (<any_other_node_ip_address>): remote node IP is non-routable`

We attempted to use the `exclude-local-address` agent configuration parameter to ignore the storage subnet, but this did not resolve the issue. We observed these errors using different kernel versions (5.15 or 6.1).

Is there a way to exclude certain network interfaces or subnets from the L2 neighbor discovery feature?

Thank you for your time and consideration.
Best regards

**Comment by squeed** [comment]
Hi there,
Would you be able to provide a sysdump of an affected node? Thanks!

**Comment by jrife** [comment]
Have you tried the `--devices` option in your Cilium config? Looking at the code, I think this will restrict L2 neighbor discovery only to the interfaces you specify. For example, if `eth1` is the interface with routes to your storage network and `eth0` has routes to cluster nodes you can do something like this. Maybe give it a try and see?

```
--devices=eth0
```

**Comment by BenoitKnecht** [comment]
I [commented here](https://github.com/cilium/cilium/issues/34093#issuecomment-2358054828) about this exact same problem, but I think it got mixed in with a wider issue that was being reported there.

So to recap, we observe this issue since Cilium 1.16, and it happens on nodes with multiple network interfaces. In my original comment, I mention that it only happens on clusters with BGP control plane enabled, but I'm not sure about that anymore; since the error doesn't _always_ show up in the output of `cilium status`, it's possible that I just didn't see the error by random chance, and then wrongly inferred this correlation.

Anyway, I'm attaching the sysdump for an affected node running Cilium 1.16.4: [cilium-sysdump-20241120-150513.zip](https://github.com/user-attachments/files/17832980/cilium-sysdump-20241120-150513.zip).
That node has two network interfaces: `eth0` with IP address `172.23.5.16`, and `eth1` with `10.6.2.17`. The routing table contains

```
default via 10.6.2.1 dev eth1
172.16.0.0/12 via 172.23.5.1 dev eth0
```

(truncated to only show relevant entries). The error messages state

```
Failed node neighbor link update: unable to determine next hop IPv4 address for eth0 (10.6.2.13): remote node IP is non-routable
Failed node neighbor link update: unable to determine next hop IPv4 address for eth0 (10.6.2.19): remote node IP is non-routable
```

which is correct, there's no route to `10.6.2.0/24` through `eth0`, but it _is_ reachable through `eth1`. The code seems to be doing the equivalent of

```console
$ ip route get 10.6.2.13 dev eth0 fib
```

to arrive at that conclusion, which indeed returns `RTNETLINK answers: No route to host` on that node.

**Comment by BenoitKnecht** [comment]
And I forgot to mention that so far, these errors don't seem to be causing any connectivity issues, at least not on the small test cluster we've been testing Cilium 1.16 on (which admittedly doesn't see a lot of traffic to begin with). But I wouldn't feel comfortable rolling 1.16 into production with these errors constantly popping up, so I'm really hoping to get to the bottom of this.

**Comment by BenoitKnecht** [comment]
I was looking through the code again and noticed that this was apparently fixed on `main` with #35144. It hasn't been backported yet though.

@pippolo84 Would you consider backporting this to 1.16? I just tried cherry-picking 7e6195b6057f75500c7cd8a9f65ae186a52c9358 and 658382aae711ec547979c33119dba6f393259690 on top of `v1.16`, and they were both applied without any conflict, so it should be pretty straightforward.

**Comment by pippolo84** [comment]
> [@pippolo84](https://github.com/pippolo84) Would you consider backporting this to 1.16?

[Here](https://github.com/cilium/cilium/pull/36093) the backport 👍

**Comment by TechABC** [comment]
Hello,

We would like to confirm that the error message has disappeared since we updated to version 1.16.5. Thank you very much for your prompt response and assistance.

Best regards.

**Comment by jgoelen** [comment]
@TechABC Was upgrading to version 1.16.5 sufficient to resolve the issue, or did you still need to use the `--devices=` option that was suggested?
