### ISSUE TITLE
connectivity impact after changing bpf filter priority

### ISSUE THREAD

**Issue by camrynl** [cilium/cilium#36172]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

Saw on cilium v1.14.15 and v1.16.2 in AKS cluster and with latest cilium in kind cluster

After changing the `bpf-filter-priority` in config from default value of `1`, the original tc egress and ingress filters and bpf programs attached to interface do not get cleaned up. Duplicates of these filters are added at the new priority and nodes fall into a notready state where connectivity is lost and kubelet stops reporting status. 

### How can we reproduce the issue?

1. Create cluster with cilium v1.14.15
3. After cilium is up and running, set `bpf-filter-priority: 2`
4. Restart cilium daemonset

Note: if repro is on a later cilium version the config must also have `enable-tcx: false` and `enable-node-port: true`

### Cilium Version

Cilium v1.14.15, v1.16.2

### Kernel Version

5.15.0-1074-azure

### Kubernetes Version

Kubernetes v1.29 (with cilium v1.14.15) and v1.31 (with cilium v1.16.2)

### Relevant log output

```shell

```

### Anything else?

@tamilmani1989 is working on the fix for this issue 

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by tamilmani1989** [comment]
![Image](https://github.com/user-attachments/assets/476793a5-6130-47fc-8bef-70142224718c)


After updating priority to 10, still old filter with priority 1 is not replaced. One option is to detect change in filter priority and then remove and create new filter with current priority

**Comment by joestringer** [comment]
Yeah I think this is one of these configuration options that we've never designed a safe upgrade for, it's intended to be configured correctly from the start and never modified. This is likely the reason that the option is marked hidden and we aren't trying to encourage users to use/modify it.

In general in Cilium when trying to properly support an upgrade / transition we aim for hitless transition, but in this case I'm not sure we have an option to atomically swap for this configuration.

If the choice is between (1) remove filter (2) time passes (3) add the new filter vs. (1) add the new filter (2) traffic impact (3) remove the old filter, I would lean towards the latter just because the first approach could cause network policy violations, whereas the latter option should only create temporary connectivity disruption.

**Comment by borkmann** [comment]
> Yeah I think this is one of these configuration options that we've never designed a safe upgrade for, it's intended to be configured correctly from the start and never modified. This is likely the reason that the option is marked hidden and we aren't trying to encourage users to use/modify it.

The other thing is that if we were to remove it, it could also be racy if some other 3rd party tool attached in the meantime.

Starting from Cilium 1.16 we use tcx (see https://isovalent.com/blog/post/cilium-netkit-a-new-container-networking-paradigm-for-the-ai-era/ ) which doesn't use priorities like the legacy tc datapath. I would suggest to migrate to that instead since its also faster (see KubeCon talk in the link).

> In general in Cilium when trying to properly support an upgrade / transition we aim for hitless transition, but in this case I'm not sure we have an option to atomically swap for this configuration.
> 
> If the choice is between (1) remove filter (2) time passes (3) add the new filter vs. (1) add the new filter (2) traffic impact (3) remove the old filter, I would lean towards the latter just because the first approach could cause network policy violations, whereas the latter option should only create temporary connectivity disruption.

**Comment by tamilmani1989** [comment]
Thanks @borkmann. Yes, certainly we move towards tcx in future version. AKS have been supporting cilium version < 1.16 and kernel with 5.15.x and need a fix for legacy TC until then.



> The other thing is that if we were to remove it, it could also be racy if some other 3rd party tool attached in the meantime.

can you elaborate a bit on how this could happen? Cilium will remove old TC filter only if it finds 2 filter (only cilium attached ebpf) with same name but different priority.
