### ISSUE TITLE
Document CI auto-scaling

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3633]
- [x] Process to manually remove nodes
- [x] Location of logfiles
- [ ] Process manually increase the number of nodes
- [ ] Process to change the limits

cc @ianvernon

**Comment by ianvernon** [comment]
Other recommendations:

- [ ] Log with timestamps in the autoscaling log
- [ ] Expose errors in the log in some way (using some log-level utility, for instance). It is extremely hard to figure out what went wrong.

Other concerns:
* It seems like we are silently failing and still provisioning instances even if required dependencies fail to download (git, go-bindata, etc.). I do not think this should happen, as it causes the user of the machines (those who post PRs) to suffer with cryptic-looking errors. We should detect errors and exit and clean up accordingly. We can suffer a longer build queue in this case because it's better to have a build that will succeed eventually and be stuck in a queue vs. having one run on a machine that is borked.
* We should add some precheck into the Jenkinsfile as a step that checks if required binaries are present. This can be done along with the above bulletpoint to ensure that both sides ensure that the instances are provisioned correctly.
