### ISSUE TITLE
Merge debug tools into a single tool

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#3655]
We currently have lots of tools to debug

- `cilium monitor`
- `cluster diagnosis`
- `cilium-health`
- `cilium-bugtool`
- `cilium debug info`
- `microscope`

We should either:

- merge all the command evocations in cilium client
- create a new tool that contains all debug tools?

I'm not against the tools per se I would only like to call all of them from a single place.

https://xkcd.com/927/

**Comment by ianvernon** [comment]
`cilium debuginfo` output is actually included within `bugtool` so that slightly addresses a subset of your concerns. I think having all output which can be gathered as the result of running a command (e.g., `cilium-bugtool`, `cilium debuginfo`, `cilium-health`, `cluster-diagnosis`), should be included as part of `cilium-bugtool`. `microscope` and `monitor` are special in that they require interaction to a degree from the user in terms of filtering, and killing the launched processes. Microscope also only works in Kubernetes AFAIK (@nebril correct me if I'm wrong), while `cilium monitor` works in any environment as it is built / packaged alongside Cilium. 

I don't see how we can merge things which achieve different aims (monitoring live packets vs. gathering debugging information) into one tool. However, I'm all for putting as much as we can outside of monitor / microscope into `cilium-bugtool`.

**Comment by vadorovsky** [comment]
`microscope` is written in Python, so it would be hard to integrate it without rewriting it from scratch.
