### ISSUE TITLE
Investigate tracepoints on kfree_skb for drop monitoring

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#3814]
We could build up a set of statistics on where `kfree_skb()` is being called to investigate issues where packets are being dropped unexpectedly.

**Comment by borkmann** [comment]
The way we could do it is to mark the skb on Cilium entry with some meta data that we don't use yet (tc_index?), and attach to kfree_skb a tracepoint triggering a BPF program that checks for these markings to filter. From BPF side we can reuse the same perf RB as for cilium monitor and intermix with custom data we collected about the kfree_skb. There's also the stackmap where we can automatically collect stack traces from the kernel side. The marking could also be fine-grained such that we can detect where it originated from, e.g. before TC_ACT_REDIRECT we could set the mark specifically such that we see that a drop happened due to MTU as an example. The mark can be read safely through bpf_probe_read(); skb->mark is unlikely to change ABI wise, so safe to use.
