### ISSUE TITLE
Invalid escape from CT GC

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#3867]
I found a lot of these errors in some logs:
```
```

They indicate that we break out of the following loop:
``` go
func doGC4(m *bpf.Map, filter *GCFilter) int {
[...]
        for {
                nextKeyValid := m.GetNextKey(&nextKey, &tmpKey)
                entryMap, err := m.Lookup(&nextKey)
                if err != nil {
                        log.WithError(err).Error("error during map Lookup")
                        break
                }
```

This is problematic from various perspectives:
 * We abort the GC run
 * This adds a lot of churn to the log for a non serious error

We need to handle this better

**Comment by jrajahalme** [comment]
Looking how bpf dumps work, if a lookup on an element fails, subsequent BPF_MAP_GET_NEXT_KEY will return the *first* key in the map, if it exists. Hence, if we do not stop iteration on lookup error we will loop forever.

If there are no concurrent operations on the map this style of iteration will traverse all elements of the map. In the presence of concurrent modifications the key returned by GET_NEXT_KEY may fail on a lookup, causing an early termination of the loop.

Specifically in the quoted code snippet if the lookup fails it is highly likely that `nextKeyValid` is `true`, but `tmpKey` will point to the first element of the map in that case. The pattern here is overall a bit weird, and IMO should be replaced with something like this:

```
// Initially tmpKey is all zeroes and should not be found from the map, and
// if no error is returned, nextKey is the key of the first element in the map.
for ; m.GetNextKey(&tmpKey, &nextKey) == nil ; tmpKey = nextKey {
	entryMap, err := m.Lookup(&nextKey)
	if err != nil {
		// element has been deleted by a concurrent map operation. GetNextKey would
		// start iteration over from the beginning so we have to stop.
		break
	}
	... deal with entryMap  ...
}
```

If desired we could count the number of restarts (lookup failures) and limit them to a small number. IMO we should log the number of restarts but on a less severe log level. We should probably also log a message if we fail to iterate to the end of the map as indicated by quitting due to excessive number of restarts.

**Comment by tgraf** [comment]
Discussed in person.
The original logic is because we can't delete an entry and then call `GetNextKey()` on it. On error handling, we decided to keep track of the previous two keys and fall back to the previous key if `GetNextKey()` on the current key fails.

Also discussed adding a metric to count the number of failed GC attempts.

**Comment by jrajahalme** [comment]
Discussed online, the snippet I proposed above does not work when current element is deleted.

**Comment by jrajahalme** [comment]
Solution proposal in #3946
