### ISSUE TITLE
[monitor] reliable related-to flag

### ISSUE THREAD

**Issue by nebril** [cilium/cilium#3888]
Monitor should derive all IPs of endpoint and be able to use (endpoint ID OR IP) as filter.

IP information needs to be taken out of the packets and be matched by endpoint information retrieved from ipcache.

**Comment by raybejjani** [comment]
https://github.com/cilium/cilium/issues/3889#issuecomment-384295973 might also apply here but, more generally, could monitor figure out the IPs from talking to the agent only? Alternatively, a given IP must be unique (at least within the pod IP ranges). We could look at all interfaces on the machine, match the one with the IP, and get the set of IPs bound to it. This is making some assumptions, though, since a host network setup might share IPs or have different IPs on different interfaces.

**Comment by nebril** [comment]
Closed by https://github.com/cilium/microscope/pull/69
