### ISSUE TITLE
CI: logged "STEPs" should indicate if the command is expected to succeed or fail and why

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium#3967]
It would be helpful for forming an initial understanding of a test failure if the logged test *STEP*s would indicate if the attempted command is expected to succeed or fail, and for what reason. This information can obviously be deciphered from the test sources, possibly by referencing the imported policy yaml, but that takes a lot of time for someone not already familiar with the test case in question.

For example, looking at test log below it is hard to say if the curl is expected to succeed or fail:
```
17:44:46 STEP: Client "app2" attempting to curl public URL on httpd2
17:44:46 time="2018-04-30T17:44:44Z" level=debug msg="running command: docker exec -i  app2 curl -s --fail --connect-timeout 5 --max-time 5 http://10.15.101.61:80/public"
```

Instead, it could say something like this (completely made up example, not relevant to the actual test output quoted):
```
17:44:46 STEP: Client "app2" attempting to curl public URL on httpd2, expected to FAIL due to label based egress policy on "app2"
17:44:46 time="2018-04-30T17:44:44Z" level=debug msg="running command: docker exec -i  app2 curl -s --fail --connect-timeout 5 --max-time 5 http://10.15.101.61:80/public"
```

Missing these helpful hints can be considered a regression from moving to Ginkgo framework, as many of the bash-tests had these. Fixing this should start at the intent level, so that whenever we work on new or existing test cases we add these.

**Comment by eloycoto** [comment]
@jrajahalme Yes,I'm agree on this, but that i's the test-output, and in the test itself we `expectFail` or `expectSucess` so if the test fails you will see the output and the assert message, and you will know the current output. (The idea is, if the test pass is the expected behaviour, if not pass you will see where,what, and why it fails) 

The issue is  when a new connectivity test, where you test 10 different connections and there is no step message that can not be written at all. 

https://github.com/cilium/cilium/blob/master/test/runtime/Policies.go#L295-L344

Yes, I know that it's a functionality that you had in the bash test, but for me Ginkgo is a different way to debug logs, and these BY messages can work few times, but not always can be applied. IMHO. 

On the other hand, the issue #3585 , is a task that it's to clean the noise of test, and looks like that we're going to add a bit more with this one.

**Comment by ianvernon** [comment]
@eloycoto we could explain it *before* the `connectivityTest` is ran, by replacing like 364 with `By` that explains which things should fail and why:
https://github.com/cilium/cilium/blob/73302155f7b2853b11499b93237e42491c4d51de/test/runtime/Policies.go#L364-L365

E.g.:

```
By("Expecting all connections to succeed from app1 to httpd1 because policy allows all connections from app1 to httpd1 on L3")
connectivityTest(...
```
It would at least give more context to the tests. It wouldn't be doable within the function itself, but it would make the tests easier to read for users if described in context of the test itself. I think this is a reasonable middle-ground. The key thing here is that the output to console currently does not say why the traffic should be allowed, just what we expect the result to be.

**Comment by eloycoto** [comment]
I think that this should be closed due to ResCMD.ExpectSuccess() functions.
