### ISSUE TITLE
Docs: Fix the GSG with the correct prometheus yaml link

### ISSUE THREAD

**Issue by manalibhutiyani** [cilium/cilium#4032]

**Comment by manalibhutiyani** [comment]
Related to  #4010 and #3337

**Comment by manalibhutiyani** [comment]
@joestringer Sorry but what needs to be added here in the spellchecker? The warning is a bit confusing.

22:25:27 /srv/Documentation/contributing.rst:1152: WARNING: 'any' reference target not found: Status("SUCCESS", "$JOB_BASE_NAME"
22:25:27 Spelling checker messages written to /srv/Documentation/_build/spelling/output.txt
22:25:27 WARNING: Found 2 misspelled words


`SUCCESS`, `JOB_BASE_NAME`  `Status`?   or something else?

**Comment by manalibhutiyani** [comment]
I don't see `any` in the line mentioned, so wanted to confirm once.

**Comment by ishantanu** [comment]
Stopped by here because I was facing same issue.
@manalibhutiyani Have a look at `line no: 1152` of `Documentation/contributing.rst`:

```
- **Status(String status, String context)**: set pull request check status on
  the given context, example `Status("SUCCESS", "$JOB_BASE_NAME"`
```
It should be:
```
- **Status(String status, String context)**: set pull request check status on
  the given context, example ``Status("SUCCESS", "$JOB_BASE_NAME")``
```
Note the double backticks `(``)`.

The error you're seeing is because of this setting which is being used.
https://github.com/cilium/cilium/blob/2657e862bbf9531108f137266d490e4968c3abdb/Documentation/conf.py#L177

Sphinx reference:
http://www.sphinx-doc.org/en/stable/markup/inline.html#cross-referencing-anything.

Since this issue was closed 7 days ago, let me know if there's a need to send a separate PR.

**Comment by manalibhutiyani** [comment]
@iamShantanu101 : That's great. Please raise a GH issue and go for it if you have cycles!
