### ISSUE TITLE
CRD backend for kvstore

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4057]
Use k8s CRD as kvstore backend to avoid requiring the deployment of a separate dedicated kvstore.

Considerations:
- [x] security identity allocation
- [x] ipcache
- [ ] service ID allocation for DSR
- [x] node discovery (already covered by k8s node resource)

Tasks:
- [ ] Research feasibility of a generic backend that implements the existing kvstore operations go interface

Relevant upstream issues:
- https://github.com/kubernetes/kubernetes/issues/57316
- https://github.com/kubernetes/kubernetes/pull/63518

cc @andrewsykim

**Comment by andrewsykim** [comment]
@tgraf according to your list, these are the data structs I have so far that needs to be converted to a versioned CRD: 
* IPIdentityPair (ipcache) - https://github.com/cilium/cilium/blob/master/pkg/identity/identity.go#L40-L53 
* identity allocator - https://github.com/cilium/cilium/blob/master/pkg/identity/allocator.go#L31-L34 
* node discovery - https://github.com/cilium/cilium/blob/master/pkg/node/node.go#L39-L76 (though likely won't be converted to CRD since covered by k8s node)
* service ID allocation - https://github.com/cilium/cilium/blob/master/pkg/loadbalancer/loadbalancer.go#L447-L452 

Can you confirm if this is correct and if there's anything else I'm missing here to build a working proof-of-concept for using CRDs to replace kvstore?

**Comment by tgraf** [comment]
Note that we have added etcd operator support in 1.2 to no longer require an external kvstore.

That said, the list looks good. Some notes on each:

> service ID allocation - https://github.com/cilium/cilium/blob/master/pkg/loadbalancer/loadbalancer.go#L447-L452

This has become optional and is only required when DSR is enabled. The DSR feature is currently not exposed as it is not documented. We have switched to 1.2

> node discovery

This is already possible via the k8s node resource.

> IPIdentityPair (ipcache)

This is likely straight forward

> identity allocator

This will likely be the tough piece.

**Comment by andrewsykim** [comment]
The etcd operator definitely helps! Do you still see value in replacing KV store entirely with CRDs or do you see KV store + etcd operator as the long-term/permanent solution? (Assuming we can support the same operations with CRDs as we can with etcd, it's not clear that we can yet).

**Comment by tgraf** [comment]
I think we will know in a couple of weeks. We already have several users on EKS running the etcd operator and so far it is looking good but the feedback will tell whether it is a good long-term solution. CRDs are still evolving as well. It might be worth have a conversation with API machinery to check if we can have some form of allocation logic.

**Comment by andrewsykim** [comment]
Sgtm! Please keep me updated, will hold off on any work til then :)

**Comment by mohag** [comment]
The 1.6 release notes mentions "[kvstore free operation](https://cilium.io/blog/2019/08/20/cilium-16/#kvstorefree)", which seems to fix this...

Some of the seemingly related PRs:
#8573
#8496
#8236
#8627

**Comment by tgraf** [comment]
@mohag Yes, thanks for pointing this out.

Fixed by #8573
