### ISSUE TITLE
1.x legacy removal tracker

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4082]
The following configuration options have been obsoleted but remain as hidden flags for compatibility. They are scheduled for removal in a future release.

- [ ] `--auto-ipv6-node-routes` (1.0)

**Comment by joestringer** [comment]
I was playing around with the idea that deprecated code could be wrapped in something like:

```
if versioncheck.DeprecateIn("1.3") {
   ...deprecated code...
}
```

Then, we either have a runtime check in `versioncheck.Deprecated()` that calls `Fatalf()` with a callstack if the version is beyond the specified version, or alternatively have a shell script invoked during postcheck that greps around for these lines and fails at buildtime.

We could set it up so that when the version gets bumped to `X.Y.90`, it considers the version to be `X.Y+1` and fails the compile, so the PR which bumps master to the new `X.Y.90` would also need to consider either removing deprecated code, or bumping the deprecation version further.
