### ISSUE TITLE
Errors observed updating CEP

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4099]
```
cilium-hwqvq-2018-05-14T17:18:56.171464.log:level=error msg="Cannot update CEP" containerID=cilium-loc controller="sync-to-k8s-ciliumendpoint (11004)" endpointID=11004 error="Operation cannot be fulfilled on ciliumendpoints.cilium.io \"cilium-health-ip-172-0-35-235.us-west-2.compute.internal\": StorageError: invalid object, Code: 4, Key: /registry/cilium.io/ciliumendpoints/kube-system/cilium-health-ip-172-0-35-235.us-west-2.compute.internal, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 77e9628f-5737-11e8-aab9-029cdb62bcae, UID in object meta: " ipv4=10.2.0.51 ipv6="f00d::a02:0:0:2afc" k8sPodName=":" policyRevision=0
```

@raybejjani Is this a serious error. What does it mean?

**Comment by joestringer** [comment]
Curiously, I also hit this in #3988 in a test case where I believe we ran out of memory and the KVstore got randomly killed by the kernel OOMkiller:

```
2018-05-02T23:32:23.862103365Z level=error msg="Cannot update CEP" containerID=cilium-loc controller="sync-to-k8s-ciliumendpoint (29898)" endpointID=29898 error="Operation cannot be fulfilled on ciliumendpoints.cilium.io \"cilium-health-k8s2\": StorageError: invalid object, Code: 4, Key: /registry/cilium.io/ciliumendpoints/kube-system/cilium-health-k8s2, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 68798083-4e60-11e8-a1ec-0800277280d1, UID in object meta: " ipv4=10.10.1.172 ipv6="f00d::a0a:100:0:74ca" k8sPodName=":" policyRevision=0
```

**Comment by raybejjani** [comment]
This one specifically will not break anything, because it's the health endpoint. The error happening at all is a little weird, because it's the health endpoint! (these are recreated on every cilium-agent start).
I think this came up in the past when we merged the json schema change. Was this an upgrade from a pre 1.0 version by any chance?

If @joestringer saw it on a current PR, however, then that's a little more troubling. I found this issue on the k8s side (https://github.com/kubernetes/kubernetes/issues/41760) but I doubt it was an old etcd thing (we need 3.1 anyway, right?)
Looking at this k8s code (https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/namespace/storage/storage.go#L141) could it be that the namespace changed? The thing is, the health-endpoint CEP is always in `kube-system` so unless the UID for that namespace changed (possible in @joestringer's scenario) this wouldn't trigger :/

**Comment by raybejjani** [comment]
Err, so, I'm not sure how likely it is to happen. In itself it isn't dangerous but annoying.

**Comment by tgraf** [comment]
> Was this an upgrade from a pre 1.0 version by any chance?

Yes

**Comment by joestringer** [comment]
> If @joestringer saw it on a current PR, however, then that's a little more troubling. I found this issue on the k8s side (kubernetes/kubernetes#41760) but I doubt it was an old etcd thing (we need 3.1 anyway, right?) Looking at this k8s code (https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/namespace/storage/storage.go#L141) could it be that the namespace changed? The thing is, the health-endpoint CEP is always in kube-system so unless the UID for that namespace changed (possible in @joestringer's scenario) this wouldn't trigger :/

FWIW in that build, lots of things got killed - docker, kubelet, etcd, cilium, etc.. Seems plausible that the UID for the namespace changed in that case.

**Comment by tgraf** [comment]
We are not seeing this anymore
