### ISSUE TITLE
"Cannot List CEPs" error in cilium logs 

### ISSUE THREAD

**Issue by danwent** [cilium/cilium#4160]
User had the following error (seen with both v1.0.2 and v1.0.3): 

```
cilium-pxbnf cilium-agent level=error msg="Cannot list CEPs" controller="sync-to-k8s-ciliumendpoint-gc (ip-172-20-99-69.eu-central-1.compute.internal)" error="v2.CiliumEndpointList: Items: []v2.CiliumEndpoint: v2.CiliumEndpoint: Status: v2.CiliumEndpointDetail: Status: readObjectStart: expect { or n, but found [, error found in #10 byte of ...|\"status\":[{\"code\":\"O|..., bigger context ...|ne\",\"policy-revision\":7,\"state\":\"ready\",\"status\":[{\"code\":\"OK\",\"message\":\"Successfully regenerated e|..."
```

@tgraf said it was harmless, but would be good to clean-up.

**Comment by raybejjani** [comment]
did the cluster ever run a pre-1.0 version, by any chance? I'll still hack in a workaround to the useless autogenerated code but it would be good to know if this is happening only to pre-1.0 installs or for another, unexpected, reason.

**Comment by raybejjani** [comment]
I'm going to close this. Another ticket I saw recently had a similar problem and it was due to a pre-1.0 CEP hanging about. This can still happen today with some of our quickstart guides.
The telltale sign is the `|\"status\":[{\"code\":\"O|` In older versions, `status` was an array of objects that contained a `code` field.
