### ISSUE TITLE
Make `ProxyWaitGroup` a local variable, don't cache it in `endpoint`.

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#4411]
The ProxyWaitGroup usage today for Endpoint `e` looks something like:

1. Lock BuildMutex
1. Initialize `e.ProxyWaitGroup`
1. Defer setting `e.ProxyWaitGroup` to `nil`
1. Make some call through the `Owner` interface, passing `e`.
1. `Owner` dereferences `e.ProxyWaitGroup`
1. Its context is passed through to XDS
1. This callstack finishes queuing some activity
1. The original function then runs `e.WaitForProxyCompletions`
1. Unlock `e.BuildMutex`.
1. Return, triggering the defer from step 3.

From discussion on #4395 , it seems like this might be a bit tidier if we avoid caching the `ProxyWaitGroup` inside the endpoint where it could be misused, and instead pass it around as a parameter to each relevant function.

**Comment by raybejjani** [comment]
I'll continue the discussion here, but this is a response to @rlenglet 

For some reason this didn't show up in my code analyzer but grep worked :/ We do seem to use `ProxyWaitGroup` outside of endpoint:
https://github.com/cilium/cilium/blob/master/daemon/daemon.go#L143
https://github.com/cilium/cilium/blob/master/daemon/daemon.go#L162
https://github.com/cilium/cilium/blob/master/daemon/daemon.go#L173-L174

I assumed that this was why we shared it in the endpoint class, since those functions would also wait on the same set of completions (adding their own, if needed) but might be called asynchronously to the functions in endpoint. The thing is, we don't seem to lock the I hope that I'm absolutely wrong about this, and we don't actually share `ProxyWaitGroup`. If so, we could make all uses local but perhaps also move these functions to the endpoint class, and simplifying `Owner`!

**Comment by joestringer** [comment]
@raybejjani If you trace up to the callers of the three daemon functions you pointed to here, they grab the `BuildMutex` before calling down into these interfaces. 

I'm fairly convinced that the code is strictly correct today, but yeah I feel like there should be a more obvious way to structure this code so it's clearer that it's correct.

**Comment by jrajahalme** [comment]
> On Jun 8, 2018, at 10:22 AM, Joe Stringer <notifications@github.com> wrote:
> 
> @raybejjani <https://github.com/raybejjani> If you trace up to the callers of the three daemon functions you pointed to here, they grab the BuildMutex before calling down into these interfaces.
> 
> I'm fairly convinced that the code is strictly correct today, but yeah I feel like there should be a more obvious way to structure this code so it's clearer that it's correct.
> 

Fully agree, placing ProxyWaitGroup into endpoint was done for convenience, pushing back the need to refactor the code that seems now necessary..

**Comment by ianvernon** [comment]
Taken care of by https://github.com/cilium/cilium/pull/4697
