### ISSUE TITLE
deploying Cilium with Kubernetes + Prometheus creates large amount of global conntrack entries

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#4496]
It's easy to cause a standard k8s + prometheus setup to generate a large number of DNS requests, each of which results in an entry in the conntrack table. Worst case if the table becomes completely full, the datapath may begin to drop new connections. Furthermore if there are many entries in the table, then conntrack garbage collection could use a lot of CPU. Recent changes such as #4389 alleviate this issue by expiring UDP entries after about 60 seconds, but more improvements can be made.

* [ ] Investigate whether the large number of CT entries is due to the garbage collection being interrupted by datapath deletes (#4507)
  * If so, perhaps we can track a slice of entries and reset back only a few elements rather than back to the beginning.
* [ ] Consider adding some form of LRU / pseudo-random eviction of conntrack entries when the table is almost full
* Your suggestions here

**Comment by joestringer** [comment]
Some of this is natural k8s behaviour in some configurations where DNS needs to iterate through different search domains, causing potentially several DNS "connections" for each lookup. This can be mitigated by configuring the containers with better search domain parameters, or by configuring clients such as prometheus to use FQDNs rather than basic DNS names that require expanding.

We already use LRU where available which mitigates this issue on newer kernels (4.11 or later).

Bugs such as the one recently fixed by https://github.com/cilium/cilium/pull/6318 may have also exacerbated this kind of issue, which should no longer occur. I think this is the biggest potential problem when LRU is not in use.

Furthermore, https://github.com/cilium/cilium/pull/5501 mitigates the issue by splitting TCP and non-TCP connection tracking.

@ianvernon due to the above, I will close this now. If you feel otherwise, please feel free to reopen.
