### ISSUE TITLE
CLI: "unable to parse sysfs to get CPU count"

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#4559]
It seems for any CLI command executed, the message "unable to parse sysfs to get CPU count" is printed.

```
$ cilium endpoint list
level=error msg="unable to parse sysfs to get CPU count" error="input does not match format"
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                 IPv4            STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                     
20928      Disabled           Disabled          59281      mesos:id=web-server           f00d::a0f:0:0:51c0   10.15.137.206   ready   
23520      Disabled           Disabled          4          reserved:health               f00d::a0f:0:0:5be0   10.15.162.64    ready
```

```
$ cilium status
level=error msg="unable to parse sysfs to get CPU count" error="input does not match format"
KVStore:                Ok         Consul: 172.18.0.2:8300
ContainerRuntime:       Ok         docker daemon: OK
Kubernetes:             Disabled   
Cilium:                 Ok         OK
NodeMonitor:            Disabled
Cilium health daemon:   Ok   
IPv4 address pool:      4/65535 allocated
IPv6 address pool:      3/65535 allocated
Controller Status:      15/15 healthy
Proxy Status:           OK, ip 10.15.0.1, port-range 10000-20000
Cluster health:   1/1 reachable   (2018-06-19T15:14:28Z)
```

This happens with current master in the mesos guide. (a new mesos guide version is available in https://github.com/cilium/cilium/pull/4558)

The bug is probably caused by 
https://github.com/cilium/cilium/blob/a5910535291914762cd80d6b596d4cd40f115362/pkg/maps/metricsmap/metricsmap.go#L243-L267

**Comment by manalibhutiyani** [comment]
@aanm Is this only specific to mesos setup or does this happen on k8s,docker also?

**Comment by manalibhutiyani** [comment]
might be a root cause: https://github.com/golang/go/issues/13565
need to investigate.

**Comment by aanm** [comment]
@manalibhutiyani can't the `init()` be replaced with a `Init()` that is invoked when the daemon starts? There are parts of the code where we use a sort of `Init` function.

This will allow to use the CLI without the need to open a bpf map, which is what the `init` does AFAIK.

**Comment by manalibhutiyani** [comment]
@aanm I am not sure I follow. None of the `pkg/maps` use `Init`.
```
Manalis-MBP:maps manalibhutiyani$ pwd
/Users/manalibhutiyani/go/src/github.com/cilium/cilium/pkg/maps
Manalis-MBP:maps manalibhutiyani$ grep -i -r "init" .
./ipcache/ipcache.go:func init() {
./tunnel/tunnel.go:func init() {
./ctmap/ctmap.go:	// prevKey is initially invalid, causing GetNextKey to return the first key in the map as currentKey.
./ctmap/ctmap.go:	// prevKey is initially invalid, causing GetNextKey to return the first key in the map as currentKey.
./cidrmap/cidrmap.go:func (cm *CIDRMap) cidrKeyInit(cidr net.IPNet) (key cidrKey) {
./cidrmap/cidrmap.go:func (cm *CIDRMap) keyCidrInit(key cidrKey) (cidr net.IPNet) {
./cidrmap/cidrmap.go:	key := cm.cidrKeyInit(cidr)
./cidrmap/cidrmap.go:	key := cm.cidrKeyInit(cidr)
./cidrmap/cidrmap.go:	key := cm.cidrKeyInit(cidr)
./cidrmap/cidrmap.go:		key = cm.cidrKeyInit(*cidr)
./cidrmap/cidrmap.go:	out := cm.keyCidrInit(keyNext)
./proxymap/ipv4.go:func init() {
./proxymap/ipv6.go:func init() {
./lxcmap/lxcmap.go:func init() {
./metricsmap/metricsmap.go:func init() {
```
Can you give me an example when you say :  `that is invoked when the daemon starts? There are parts of the code where we use a sort of Init function.`

**Comment by aanm** [comment]
@manalibhutiyani 

IPAM, k8s, workloads
```
$ grep 'Init(' * -R
daemon/policy.go:               if e.IsInit() {
daemon/daemon.go:       workloads.Init(&d)
daemon/daemon.go:               if err := k8s.Init(); err != nil {
daemon/daemon.go:       // IPv6AllocPrefix were already allocated before the k8s.Init().
daemon/daemon.go:       // If the device hasn't been specified, k8s.Init() allocated the
daemon/daemon.go:       // If k8s.Init() failed to retrieve the IPv4AllocPrefix we can try to derive
daemon/daemon.go:       ipam.Init()
daemon/daemon.go:       if err := node.ValidatePostInit(); err != nil {
```

**Comment by manalibhutiyani** [comment]
I guess I was simply following the same method all other maps are using. Let me check if this can be changed.

**Comment by joestringer** [comment]
I'm not seeing this on the latest master version, doesn't seem like a major issue. If anyone observes this, please comment/reopen.

**Comment by aanm** [comment]
Still not fixed. At least in `v1.2.0`

**Comment by brb** [comment]
I've tested v1.2.5 with the mesos guide from the master:

```
$ cilium version
level=error msg="unable to parse sysfs to get CPU count" error="input does not match format" subsys=map-metrics
Client: 1.2.5 f094f0a 2018-10-22T15:04:52-07:00 go version go1.10.3 linux/amd64
Daemon: 1.2.5 f094f0a 2018-10-22T15:04:52-07:00 go version go1.10.3 linux/amd64
```

We should probably avoid abusing `init()`. Hopefully https://github.com/cilium/cilium/pull/6286 will fix this.

Anyway, the problem is that on the provisioned VM there is only one CPU, so `/sys/devices/system/cpu/possible` contains `0` which makes https://github.com/cilium/cilium/blob/v1.3/pkg/maps/metricsmap/metricsmap.go#L226 to log the error, but to return the correct number of CPUs (1 in this case).

`/sys/devices/system/cpu/possible` is handled by https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/base/cpu.c#n224. If I'm not mistaken, the output can be a comma separated list of either a CPU number or CPU number ranges. See how perf parses max CPU number: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/perf/util/cpumap.c#n410.

I think there is a bug in https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/testing/selftests/bpf/bpf_util.h#n25 from which `calculateNumCpus` was derived, as it does not handle the commas (e.g. `0-8,10-15`).

We need to fix parsing in `calculateNumCpus` in a way that it returns ~just max CPU num~ a correct number of possible CPUs, as there can be gaps in available CPU ranges, ~and change the function name to reflect the change~.
