### ISSUE TITLE
Proposal: Separate identity for remote cluster nodes

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4779]
We currently have an identity `reserved:host` which represents both the local node but also all other nodes in the cluster. The collapsing of both local and remote nodes into a single identity is not ideal. With the introduction of the ipcache, we can split the local and remote nodes and assign individual identities.

**Use case walkthroughs**

1. Ingress from another node via tunnel, e.g. host networking PID on node A sends traffic to pod on node B.
   - Traffic encapsulated to other nodes with source identity reserved:host is mapped to reserved:remote-host

2. Ingress from another node via direct routing
   - No identity information is carried as PID on node A talks straight to node B

3. Egress from pod to another node, e.g. pod on Node A sends traffic to node B
   - ipcache is populated with all node IPs which map to identity of reserved:remote-host
   - ipcache is populated with local node IP with identity of reserved:host

**Comment by joestringer** [comment]
I assume this proposal supersedes https://github.com/cilium/cilium/issues/3536 .

Case 1 could be achieved on transmit from node A (see that it's from host and rewrite to from remote-node) or on receive at node B (there's no legitimate reason with this model to receive from:host so from:host can be rewritten to from reserved:remote-host).

Case 2 depending on how it's received we could treat as from:world by default but if the source IP is known and can be matched against another node, it could be considered from reserved:remote-host.

There's just one tricky part here, which is how we handle upgrade. If anyone has written any policy depending on the current classification behaviour for other nodes in the cluster, then we change the way the traffic is classified, then it will break their policies. We may need to consider another thing similar to 
the `host-allows-world` option. For case 1, it's more likely to break because the traffic is currently considered as host, which is more restrictive. If someone allowed traffic from:host and the traffic is now considered from:remote-host then the old policy would no longer allow traffic based on the new behaviour. Case 3 should be unaffected as currently the destination would map to cluster / world, and policies that select reserved:world should probably apply to remote-host as well - ie, if you are allowed to talk to the world, then you are also allowed to talk to remote-host.

**Comment by tgraf** [comment]
> I assume this proposal supersedes #3536 .

Yes, I was looking for this but didn't find it.

> We may need to consider another thing similar to
> the host-allows-world option.

Agreed. There is no way around it. It's invisible for new users so I'm not worried.
