### ISSUE TITLE
the network not working if add --disable-conntrack

### ISSUE THREAD

**Issue by swimablefish** [cilium/cilium#4781]
**Important:** Join our [slack channel](http://cilium.io/slack) for immediate
support and an opportunity to ask questions. Please also have a look at our
[FAQ](https://goo.gl/qG2YmU) for frequently asked questions first.

If you open a GitHub issue, please follow these guidelines:

1. It must be a bug or a feature request.
2. The form below must be filled out.

--------------

### Title

the network not working if add --disable-conntrack

### General Information

- Cilium version (run `cilium version`): 1.1.0
- Kernel version (run `uname -a`): Linux ip-10-0-6-225 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): k8s 1.10.2
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

### How to reproduce the issue

1. edit ds cilium, add parameter --disable-conntrack

**Comment by swimablefish** [comment]
[cilium-sysdump-20180709-024056.zip](https://github.com/cilium/cilium/files/2174499/cilium-sysdump-20180709-024056.zip)

**Comment by raybejjani** [comment]
@swimablefish I'm able to reproduce this and I tracked it down to the load balancing not working when conntrack is disabled. This applies to the dns server and it's connection to kube-apiserver. In my testing, using pod IPs directly did work. Can you test that to ensure that I'm seeing the same problem?

In the meantime, I've created a bug https://github.com/cilium/cilium/issues/4814 to avoid overwriting your issue (in case what you're seeing is still different).

**Comment by swimablefish** [comment]
@raybejjani , yes, pod IPs work

**Comment by raybejjani** [comment]
@swimablefish Unfortunately, what you're seeing is expected when `--disable-conntrack`. I'm sorry :( I don't see a straight forward workaround because DNS is always a service in kubernetes.

The problem is specific to load-balancing and conntrack. Load-balancing doesn't work without conntrack and this affects kubedns, itself a kubernetes service that cilium will load-balance. By disabling conntrack, load-balancing no longer works. When load-balancing no longer works, all DNS requests to kubedns are dropped. For most pods, this will seem like the network is down because no DNS lookup succeeds.
