### ISSUE TITLE
Replace k8s client usage with native http client

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#498]
Should dramatically reduce binary size and build time.

**Comment by aanm** [comment]
I check the whole code and we use plenty of features and structures the k8s client offers:
1) *k8s.io/client-go/1.5/pkg/apis/extensions/v1beta1.NetworkPolicy
2) k8s.io/client-go/1.5/pkg/kubelet/types.KubernetesContainerNameLabel
3) k8s.io/client-go/1.5/pkg/kubelet/types.GetPodNamespace
4) k8s.io/client-go/1.5/pkg/kubelet/types.GetPodName
5) *k8s.io/client-go/1.5/tools/cache.NewInformer
6) *k8s.io/client-go/1.5/pkg/api/v1

.
1) contains the k8s NetworkPolicy structure. 
2) contains the label const that is used in the container runtime to identify the container.
3) Is a function that returns the podnamespace from a list of labels.
4) Is a function that returns the podname from a list of labels.
5) Is used to retrieve events from the kube-apiserver whenever a new Network Policy, Service, Endpoints or Ingress is Added, Updated, or Deleted from the kube-apiserver.
6) Contains all the structures' spec that we list for changes in 5)

The ones marked with * can't be replaced as the work to maintain the code will be higher than just use the go-client libraries.

I've check a kubecon talk about the go-client, and there is 3 ways to listen for object changes:
1) With your own client
2) With `cache.NewInformer`
3) With k8s go-client and do an infinite for loop for each time you receive a new object change

The 3) was the on used presented in the talk but unfortunately that code had a concurrency  problem since you could lose object changes events between for loops. I talked with the presenter at the end of the talk and he agreed that `cache.NewInformer` solves that issue.

I'll see if a recent client-go library helps with this issue but I strongly discourage replacing the client-go client with native http client since it could create bugs that bite us in the future.

**Comment by tgraf** [comment]
It may not be required to replace all uses of go-client packages but the current derived dependencies is not acceptable. What are your actual concerns in terms of bugs? The current binding to head of go-client is definitely not a long term solution.

**Comment by aanm** [comment]
>but the current derived dependencies

Which derived dependencies are you talking?

**Comment by aanm** [comment]
We can try this although it might need to change some of code as the client methods aren't the same.
Although we could do a wrapper so we can easily replace between clients. https://github.com/ericchiang/k8s
