### ISSUE TITLE
Feature: Transparent end to end encryption and authentication

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#504]
- [x] Automatically encrypt all packets between cluster nodes
- [ ] Authenticate nodes prior to communication
- [x] Ability to specify keys
- [x] Integration with various secrets stores
- [ ] Possibility to specify ability to receive untrusted traffic in the policy
- [ ] Integration with service identity spec such as SPIFFE

**Comment by danwent** [comment]
Is it intentional to call out just encryption here, as opposed to encryption, authentication, and integrity?   I'm assuming we'd use something like IPsec and/or SSL/TLS, which should be able to provide all three, and the main use case would seem to be protecting against an untrusted "physical" network, in which case, I assume you would want all three.

**Comment by tgraf** [comment]
> Is it intentional to call out just encryption here, as opposed to encryption, authentication, and integrity? I'm assuming we'd use something like IPsec and/or SSL/TLS, which should be able to provide all three, and the main use case would seem to be protecting against an untrusted "physical" network, in which case, I assume you would want all three.

Absolutely, this includes auth and integrity as well. I've updated the section. It's still fairly high level until we work out individual details.

**Comment by wallies** [comment]
I dont know whether this issue has been completed or how the implementation was going to be implemented but something that would be nice is using wireguard (https://github.com/linuxkit/linuxkit/blob/master/docs/wireguard.md) which is something linuxkit was looking to use for similiar use case. Also great project by the way.

**Comment by ghost** [comment]
@tgraf can we get a status update on this issue?

**Comment by G3ph4z** [comment]
I guess it isn't implemented yet, right?

**Comment by tgraf** [comment]
@ericstoekl @G3ph4z We are actively implementing this right now.

**Comment by justincormack** [comment]
Great news! Is there a design doc for this?

**Comment by redbaron** [comment]
Can't wait for it to happen.

**Comment by tgraf** [comment]
Initial support merged via #6693

**Comment by nustiueudinastea** [comment]
Hi folks! Someone mentioned WireGuard higher in the comments and I would like to re-ask the question. Did you consider WireGuard as an alternative for IPsec? Perhaps at the moment it’s more difficult to implement since you can’t use a preshared key and wg is not merged in the kernel yet but it would be a very interesting alternative since it’s supposed to have better performance than IPsec. At 10gbit or higher it might make a big difference.

**Comment by brb** [comment]
@nustiueudinastea Yes, we have an issue for this: https://github.com/cilium/cilium/issues/7519.

**Comment by aanm** [comment]
Cilium has mutual authentication. Closing as this is already done https://docs.cilium.io/en/v1.15/network/servicemesh/mutual-authentication/mutual-authentication/#gs-mutual-authentication
