### ISSUE TITLE
CI: Check for warning/error logs misses errors or warnings in log

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#5136]
On this PR failure:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5504/testReport/junit/k8s-1/7/K8sChaosTest_Endpoint_can_still_connect_while_Cilium_is_not_running/

Output on jenkins:
```
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
```

However, downloading the zip and looking inside:

```
$ grep "level=error" *agent.log | wc -l
105
$ grep "level=warning" *agent.log | wc -l
226
```

[0a9ca6ca_K8sChaosTest_Endpoint_can_still_connect_while_Cilium_is_not_running.zip](https://github.com/cilium/cilium/files/2271372/0a9ca6ca_K8sChaosTest_Endpoint_can_still_connect_while_Cilium_is_not_running.zip)

**Comment by eloycoto** [comment]
that it's normal, the warning is only checked for the logs that happens during the test: 
https://github.com/cilium/cilium/blob/4a7d484af44b6e68f4e16dd9587704e449d9648c/test/helpers/kubectl.go#L1102-L1105

So, if you see the cilium-logs you will see the that there are no warning or error.  If we test for all logs, some test will fail because it has a invalid panic/NACK from the past. (That already happened)

Regards
