### ISSUE TITLE
update test/k8sT/manifests/cilium_ds.template

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#5281]
It looks the cilium_ds.template is out of date with the file from `examples/kubernetes/1.8/cilium-ds.yaml`

Can we make the process automatic so we make sure this won't happen again?

**Comment by eloycoto** [comment]
I though about this in the past, but It's near impossible to have that with the current `sed` setup for templates:-( 

The only way that I can think is the use of `jsonnet` and `kubecfg`, can do that effort, but not sure if we want to change to jsonnet the templates files.

Regards.

**Comment by ianvernon** [comment]
As part of the `sed` scripts we could generate YAMLs that are used for tests that will point to the name of the image used during the tests. This image is hardcoded to be `k8s1:5000/cilium/cilium-dev:latest` in the `cilium_ds.jsonnet` file. 

We could then store different `ConfigMaps` for testing certain configurations of Cilium in the repo if we want to test certain configuration features. We would then add these `ConfigMaps` via `kubectl`, and they wouldn't take effect until we restart Cilium.

**Comment by eloycoto** [comment]
The problem with sed is that more changes need to be done, like livenessProbe, readinessProbe, some labels for cilium-agent and  geneve, vxlan, in my opinion, add an array of things in sed is hard, or at least for me. 

Using kubecfg the yaml can be created with the tool `kubecfg show cilium_ds.jsonnet`, jsonnet is like a template engine and we can use the same for testing and examples.

**Comment by ianvernon** [comment]
Are we actively changing the `livenessProbe` and `readinessProbe` for Cilium in the CI? Ideally we should be using the default values that we are shipping out in the YAMLs we provide to the public. 

It does look like that `kubecfg` allows us to provide a template for the entire YAML vs. just a `ConfigMap`, which appears to not let one programmatically specify the image, etc. 

OK, you are saying that we should instead be using `jsonnet` for our templates in `examples/kubernetes` instead of `sed`, and then we can consume those templates in the CI? I think this makes sense, and gives a lot of flexibility with generating different YAMLs in different scenarios vs. using `sed`. Sounds good to me!

**Comment by eloycoto** [comment]
> OK, you are saying that we should instead be using jsonnet for our templates in examples/kubernetes instead of sed, and then we can consume those templates in the CI? I think this makes sense, and gives a lot of flexibility with generating different YAMLs in different scenarios vs. using sed. Sounds good to me!

yes!

>Are we actively changing the livenessProbe and readinessProbe for Cilium in the CI? Ideally we should be using the default values that we are shipping out in the YAMLs we provide to the public.

yes, to have lower values to avoid waiting times, something that a user shouldn't use at all.

**Comment by eloycoto** [comment]
Andre addressed that with a PR https://github.com/cilium/cilium/pull/5297
