### ISSUE TITLE
Discussion: Backport criteria for 1.2

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5383]
We have seen some fantastic work around endpoint regeneration in terms of:
- Reduction of resource usage
- Visibility into how resources are spent

It is tempting to aggressively backport this to have the tooling available in the 1.2.x series in user clusters.

**Option 1:**

Backport almost all of the endpoint regeneration changes.

Pros:
 * Simple, conflict-free  backports
 * Ability to identify performance problems based on user logs

Cons:
 * Potential to introduce regressions

**Option 2:**

Very selective backport (Identify candidates in testing cluster in master, backport low risk commits

Pros:
 * Less potential of regressions

Cons:
 * More merge conflict
 * Increased need for testing

**Option 3:**

Extremely selective backports. Only backport what is 100% reviewable.

Pros:
 * Less testing needed

Cons:
 * We give up on performance gains in 1.2.x

**Comment by ianvernon** [comment]
I'm for the third option. I'm of the belief that release branches need to converge upon stability - this implies that bugs, not inefficiencies, that are discovered should only be the things fixed in the branch. Thus, unless there was a huge regression with performance from say 1.1 to 1.2, we should not backport performance improvements. Performance improvements make great "features" for 1.3 as well ;)

**Comment by tgraf** [comment]
I think enough time has passed for people to raise concerns and comment.

*Summary of discussion in development meeting:*
* We will be conservative with backports.
* The endpoint generation improvements will be made available in 1.3 unless the fix has a major impact on 1.2.
* Visibility into endpoint regeneration durations may be nominated for backport if the need arises.
