### ISSUE TITLE
Run all test framework if a PR has the "kind/release" label

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#5600]
If a PR has the `kind/release` label, all tests should be executed when triggered by `test-me-please`

**Comment by ianvernon** [comment]
Alternatively, we can edit the build settings for each current protected branch and require specific builds to be ran instead of just the default CI tests (i.e., documentation tests, all K8s versions, etc.). This would be much easier than backporting a fix. I agree that this would be useful for the future.

**Comment by ianvernon** [comment]
Removing backport labels here. We can edit the branch settings directly in GitHub if we want this. We can move to doing this in the future via labels for future branches.

**Comment by aanm** [comment]
Not relevant anymore
