### ISSUE TITLE
cilium status doesn't report IPAM pools in k8s mode

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#5630]
A user reported in Cilium slack the output of cilium status:

```
$ kubectl -n kube-system exec -it cilium-4q4j8 -- cilium status
KVStore:                Ok   etcd: 1/1 connected: https://cilium-etcd-client.kube-system.svc.cluster.local:2379 - 3.2.22
ContainerRuntime:       Ok   docker daemon: OK
Kubernetes:             Ok   1.11 (v1.11.3) [linux/amd64]
Kubernetes APIs:        ["core/v1::Node", "core/v1::Namespace", "CustomResourceDefinition", "cilium/v2::CiliumNetworkPolicy", "networking.k8s.io/v1::NetworkPolicy", "core/v1::Service
", "core/v1::Endpoint", "core/v1::Pods"]
Cilium:                 Ok   OK
NodeMonitor:            Disabled
Cilium health daemon:   Ok
Controller Status:      20/20 healthy
Proxy Status:           OK, ip 10.2.0.1, port-range 10000-20000
Cluster health:   4/4 reachable   (2018-09-19T18:07:55Z)
```

Compare with output from a non-k8s setup in dev VM:

```
$ cilium status
KVStore:                Ok         Consul: 172.17.0.3:8300
ContainerRuntime:       Ok         docker daemon: OK
Kubernetes:             Disabled
Cilium:                 Ok         OK
NodeMonitor:            Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok
IPv4 address pool:      3/65535 allocated
IPv6 address pool:      2/65535 allocated
Controller Status:      12/12 healthy
Proxy Status:           OK, ip 10.11.0.1, port-range 10000-20000
Cluster health:   1/1 reachable   (2018-09-19T18:20:49Z)
```

**Comment by ianvernon** [comment]
This is because the user most likely had debug-mode disabled:

https://github.com/cilium/cilium/blob/5dc61ed8d21bf62ce53917c622f2c36639cf7309/daemon/status.go#L160-L162

This is an easy fix as we can unconditionally dump the IPAM in the status. However, we do lock the `ipamConf.allocatorMutex` when dumping:

https://github.com/cilium/cilium/blob/5dc61ed8d21bf62ce53917c622f2c36639cf7309/pkg/ipam/allocator.go#L137-L165

 is that perhaps the reason we we only want IPAM information in the status output when debug is enabled? cc: @raybejjani , @tgraf

**Comment by tgraf** [comment]
> is that perhaps the reason we we only want IPAM information in the status output when debug is enabled?

That lock should practically never be contented so it's absolutely fine to hold it.
