### ISSUE TITLE
cilium-node-monitor is consuming excessive CPU

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5650]
```
 7205 root      20   0 1688216  50712   9700 S 123.0  0.2  58:44.61 cilium-node-mon
```

```
Build ID: 8a088597bc32aeb46b4f8957f042d6c8d4b65c3f
Type: cpu
Time: Sep 21, 2018 at 12:55pm (UTC)
Duration: 30.14s, Total samples = 12.70s (42.13%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 6870ms, 54.09% of 12700ms total
Dropped 124 nodes (cum <= 63.50ms)
Showing top 10 nodes out of 99
      flat  flat%   sum%        cum   cum%
    1350ms 10.63% 10.63%     2140ms 16.85%  runtime.scanobject
    1310ms 10.31% 20.94%     2540ms 20.00%  runtime.mallocgc
     930ms  7.32% 28.27%     1530ms 12.05%  runtime.cgocall
     730ms  5.75% 34.02%      730ms  5.75%  runtime.heapBitsForObject
     710ms  5.59% 39.61%      720ms  5.67%  syscall.Syscall
     470ms  3.70% 43.31%      470ms  3.70%  runtime.greyobject
     370ms  2.91% 46.22%      500ms  3.94%  runtime.mapiternext
     350ms  2.76% 48.98%      570ms  4.49%  runtime.cgoCheckUnknownPointer
     340ms  2.68% 51.65%      340ms  2.68%  runtime.memclrNoHeapPointers
     310ms  2.44% 54.09%      310ms  2.44%  runtime.cgoIsGoPointer
```

[profile001.svg.txt](https://github.com/cilium/cilium/files/2405415/profile001.svg.txt)

**Comment by tgraf** [comment]
CPU utilization went down when old `cilium monitor` instances were closed. It is possible that the problem is related to handling of broken pipes.

**Comment by nebril** [comment]
Killing `kubectl exec` leaves the command running in the pod container, which in case of multiple `cilium monitor` instances contributes to high CPU usage.

AFAIK there is no way to discern whether monitor is actually connected to the other end of pipe from within the container.

Monitor itself is not to blame here (although possibly it could be improved with implementing concurrent MultiWriter and calling gob.Encode on each payload just once - but this gets even harder now due to differences between versions and how payloads are being represented).

We may clear monitors periodically inside container, but I am not sure if this is something our users might want - someone can have a use case for running `cilium monitor` long term.

This may be an agent option on by default, so that users that want to have long-running monitors don't suffer from this.

**Comment by tgraf** [comment]
No bottleneck justifying a 1.3 release blocker has been found. There is optimization potential that can be done as part of the 1.4 development cycle. Adjusting milestones accordingly.

**Comment by tgraf** [comment]
We are no longer seeing this
