### ISSUE TITLE
Optimize policy calculation function regeneratePolicy()

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#5876]
Use case 1: 5k unique identities
- [x] go test benchmark
- [x] Optimization

Use case 2: 1k policy rules
- [x] go test benchmark
- [x] Optimization

**Comment by ianvernon** [comment]
Update on this: did some work locally on case 2, and have found that we should avoid doing matching on rules as much as possible; the majority of time spent in the code is determining whether a rule selects a given endpoint or not. We could optimize this out by doing a single pass over the rules initially, and only grab the rules which select the endpoint. This would reduce the iterations over all the rules in the repository significantly.

We also suffer a lot when requirements are added in, especially when L4 Policy is calculated.

**Comment by ianvernon** [comment]
We should also consider removing the `ResolveCIDRPolicy` subsystem if possible. @joestringer can we do this without affecting the plumbed policy for an Endpoint since we now handle CIDRs with identities now? I recall there being work done to handle the CIDR ingress side as well with labels. We would lose the API visibility into CIDR policy for an endpoint, though, so we'd have to figure out a way of caching information about CIDR-based policy for an endpoint without doing more iterations over the rules.

**Comment by ianvernon** [comment]
A variety of PRs did the initial work surrounding this for the v1.4 release:

Benchmark (with configurable number of rules and identities in the test): https://github.com/cilium/cilium/pull/6374

Optimizations around policy calculation and associated refactoring:
* https://github.com/cilium/cilium/pull/6432
* https://github.com/cilium/cilium/pull/6404
* https://github.com/cilium/cilium/pull/6400
* https://github.com/cilium/cilium/pull/6375

**Comment by ianvernon** [comment]
There is a GitHub project tracking more work in optimizing policy calculation in v1.5: https://github.com/cilium/cilium/projects/23

**Comment by ianvernon** [comment]
Closing this accordingly ; work has been completed for v1.4 surrounding this.
