### ISSUE TITLE
DNS entry expiration and look by time

### ISSUE THREAD

**Issue by almariah** [cilium/cilium#6796]
The method `updateIPsForName` will not return true in case of expired DNS entry. The logic in this function as follow:
* Lookup for `dnsname`
* update `newIPs`
* Another lookup
* Finally compare
The `Lookup` will exclude always the expired entries. The impact is no update for rules in case of some expired entries. Is that intended?

https://github.com/cilium/cilium/blob/master/pkg/fqdn/rulegen.go#L525

**Comment by raybejjani** [comment]
Thanks for the report @almariah! In cilium 1.3 it was accidentally intended. DNS data wasn't expired from the policy until new data replaced it and in the case you describe that would be "correct". The intent was to avoid breaking long-lived connections with `toFQDNs` rules. Obviously, that isn't the most expected behaviour but sorting that out is non-trivial. See https://github.com/cilium/cilium/pull/6740 for how we're doing that.

I only see one way that the scenario you describe can happen: `updateIPsForName` is called with a lookupTime so far in the past that the data has already expired. This is because of a few things:
- `updateIPsForName` is only called when new DNS data is seen (via `RuleGen.UpdateGenerateDNS`)
- `DNSCache.Lookup` excludes already-expired entries, as you pointed out.
- `sortedIPsAreEqual` would treat the two empty slices as equal, as you pointed out

If the new IP data is not expired (i.e. still within TTL, the usual, expected, case) then `sortedNewIPs` would include the new IPs (this new set may be the same as `cacheIPs` and that is intended as a no-op). If the new IP data is expired, but the old data is still fully valid the intended no-op happens. If the old data is partially valid, `cacheIPs` == `sortedNewIPs` and we will return `updated=false`. This would also happen when the new data is already expired and the old data is fully expired.

For this case we'll add a check in the PR I linked above (since we are already updating expiration handling etc.) but am I missing another scenario that you had in mind?
