### ISSUE TITLE
Cilium integration with OpenStack Kuryr

### ISSUE THREAD

**Issue by vadorovsky** [cilium/cilium#6826]
## Proposal / RFE

**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Provide a possibility to run Cilium on top of OpenStack Kuryr (https://github.com/openstack/kuryr-kubernetes), in the similar way as it's possible to run Cilium on top of Flannel.

Action items:

Initial:
- [ ] Provide dev environment with devstack (as a patch to Vagrant configuration, similar to https://github.com/cilium/cilium/blob/master/contrib/flannel/run-flannel.diff)
- [ ] Add .conflist configuration file which will refer to Kuryr and 
- [ ] Add handler for Kuryr's CNI configuration in `plugins/cilium-cni/cilium-cni.go`

Things to research
- [ ] How to handle load balancing - shall we integrate with OpenStack Octavia?

**Comment by IKermani** [comment]
I respectfully submit that this issue should not be closed as stale. In lieu of closure, I would appreciate a clear communication if implementation is not currently planned.

**Comment by joestringer** [comment]
This issue was first filed in 2019 and there are zero reactions to the issue until last month. I doubt that anyone is planning something. That said, if someone wants to make a feature proposal that will improve integration with OpenStack Kuryr then I would encourage posting such a proposal in this issue.

That said, without clear signal about interest in this proposal it will go stale over time regardless, so I don't see a strong reason to keep it open. We can reopen it again as and when there is community interest in contributing changes to improve integration with OpenStack Kuryr.
