### ISSUE TITLE
Test minikube guide

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#6877]
Guide: https://docs.cilium.io/en/latest/gettingstarted/minikube/

- [ ] Write down unclear steps in the documentation
- [ ] Report failures

**Comment by borkmann** [comment]
I've been testing latest kubectl/minikube for k8s 1.13 and works fine, all straight forward. Been using https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/minikube/http-sw-app.yaml as sample app and all pods are in running state. Tried testing the older k8s configs, but minikube failed to bootstrap so far. Filed issue 3629 at kubernetes/minikube.

**Comment by tgraf** [comment]
1.13 is fine. I'll close this issue regarding 1.4.0

**Comment by borkmann** [comment]
Ok, so after some more debugging turns out a `minikube delete` was missing. I've checked now with the following `--kubernetes-version` params:

v1.13.2, v1.12.5, v1.11.7, v1.10.12 is all good till here.

For v1.9.11, I've filed the following bug #6940.

v1.8.15 I still need to downgrade my kubectl version, will report back my findings.

**Comment by borkmann** [comment]
Ok, after kubectl downgrade, found the same error for v1.8.15. I've updated #6940 accordingly. As far as the GSG goes, I think it's super straight forward, I can add a small note into the doc for testing older versions via `--kubernetes-version`, fwiw.
