### ISSUE TITLE
CI: ToFQDNs testing in upgrade test (?)

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#6924]

**Comment by joestringer** [comment]
Sounds good, with DNS proxy this seems like it should be doable.

For poller this could be a bit more painful. We'd want to minimize the amount of time waiting for the poller to run, and understand when the poller has run to be able to correctly test that Cilium thinks it has plumbed the right stuff and that everything should work, without having to wait for a bunch of timeouts.

Note: Maybe this should be a nightly upgrade test rather than part of the regular set.
