### ISSUE TITLE
CIDR-based deny security policies

### ISSUE THREAD

**Issue by jimmyjones2** [cilium/cilium#7111]
## Proposal / RFE

**Is your feature request related to a problem?**
I'd like to restrict all pods in my Kubernetes cluster from accessing sensitive parts of the corporate network (CIDR ranges) without resorting to a hardware firewall.

**Describe the solution you'd like**
A cluster admin can define a set of rules that apply to all pod egress. NetworkPolicy/CiliumNetworkPolicy objects controlled by users could further restrict this.

**Comment by tgraf** [comment]
@jimmyjones2 If I understand you correctly, you want to install a rule like the following but mark it as impossible to overwrite with another whitelist rule.

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "block-corp-network"
spec:
  endpointSelector:
    matchLabels:
      {}
  egress:
  - toCIDR:
    - 20.1.1.1/32
  - toCIDRSet:
    - cidr: 0/0
      except:
      - corpNetwork/16
```

**Comment by jimmyjones2** [comment]
@tgraf Yes, that would do it. A user could then only further restrict egress, eg. removing access to 20.1.1.1 or something else outside the corporate network.

A little bit like [OpenShift egress firewalls](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_networking.html#admin-guide-limit-pod-access-egress)

**Comment by jimmyjones2** [comment]
Still an issue. In public cloud environments you'd want to block all containers from accessing the metadata service

**Comment by olemarkus** [comment]
This is something we are interested in as well. Perhaps something that works similar to calico's global network policies.

**Comment by olemarkus** [comment]
We do consider network policies trusted so it is more about having default egress rules for every namespace. They actually should be overrideable by regular namespace-local policies

**Comment by joestringer** [comment]
Related: https://github.com/cilium/cilium/issues/9200

**Comment by aanm** [comment]
@jimmyjones2 Isn't the proposal made in https://github.com/cilium/cilium/issues/7111#issuecomment-469009377 enough? There's also the cluster wide network policies proposal in #9200 which will be added in 1.7.0

**Comment by jimmyjones2** [comment]
@aanm If I understand the docs of #9200 properly it would still allow a project admin to override/loosen the rules set by the cluster admin with a CiliumClusterwideNetworkPolicy?

**Comment by aanm** [comment]
@jimmyjones2 correct. So what you want is some sort of RBAC for the policy creation in the cluster?

**Comment by joestringer** [comment]
Another perspective, would it be sufficient to have an overriding blacklist of egress destinations that should never be allowed?

**Comment by jimmyjones2** [comment]
@joestringer Yes, either a blacklist of disallowed addresses, or a whilelist of allowed addresses that can't be expanded

**Comment by awprice** [comment]
+1 I'm interested in something similar to Calico's GlobalNetworkPolicy that allows us to have cluster-wide egress deny policies.

**Comment by tgraf** [comment]
> One of our key requirements however is to have Cilium run in an "allow all" mode, and only denying traffic if there is a deny egress policy in place. I'm aware that this isn't the most secure, but we are looking for an easy path to transition to Cilium without having to rethink all of our network policies and structure in plate at the moment.

Yes, this seems to be a very common use case and ask. I think it makes sense to focus on this next.

We want to be careful not to introduce any sequential processing as it would harm performance. Reading through all of the comments above, the use case seems to be:

* Ability to define a set of IP blocks (CIDR + exceptions) that can't be reached under no circumstances.
* Ability to specify these new rules at both namespace and cluster level. Either way, they can't be overwritten by any allow rules.

The biggest question is on how it should affect the default deny behavior. The current definition is:
Any CNP or NP select a pod with at least an ingress or egress section will put the pod into default deny at the specified direction. We have a couple of options:

1) We keep the behavior and a deny rule will put the pod into default deny as well. This will require you to also have a global allow-all together with the deny rule in order to achieve, allow-all except for listed exceptions.

2) We assume that the presence of only a deny means allow all except listed exceptions. This seems a bit unnatural as the behavior of the rule will change when another rule is imported which selects the pod and puts that pod into default deny.

Thoughts?

**Comment by awprice** [comment]
@tgraf Thanks for the detailed explanation!

> We keep the behavior and a deny rule will put the pod into default deny as well. This will require you to also have a global allow-all together with the deny rule in order to achieve, allow-all except for listed exceptions.

From my point of view, this option makes the most sense. Requiring a global allow-all rule to be configured makes this configuration more explicit and removes any doubt around the default behaviour. 

Very much looking to this functionality!

**Comment by joestringer** [comment]
One idea I have which is kind of a mix of (1) and (2) above would be for the new blacklist policy to be a different "tier", enabled via a separate CRD. This `CiliumBlackholePolicies` structure would always deny traffic to the specified peers, and would have its own selection logic which does not interact with existing policies. As a separate CRD, I would imagine that RBAC could be handled independently.

Logically:
* If a blacklist policy is in place, then any pods selected by such a policy will deny traffic to peers that matches the contents of the policy. This would not put the pod into default deny; it simply puts an additional blacklist in place.
* If there is a blacklist policy but no NP/CNP, then it acts as a blacklist/allow all with no access to the denied endpoints.
* If there is a blacklist policy with an NP/CNP, then it acts as a whitelist policy that will never allow access to the denied endpoints per the blackhole policy, regardless of the NP/CNP.

Benefits:
* Computation and policy handling can be easily performed as a separate stage from whitelist / allow policies. Structurally it would be easier to ensure the integrity of blacklist policy; avoid merging with the whitelist policy until a later point in computation with a simpler representation.

Downsides:
* We already have CNP, CCNP for namespaced / clusterwide network policies. This would presumably add another pair, CBP / CCBP which is more cognitive effort to deal with. We could easily get into a place where users are not aware that they should be checking an additional couple of CRDs.

Implementation possibilities:
* Blacklists could be separately computed and used at the lower layers of policy plumbing in the userspace. Before creating policymap entries, cilium-agent would compare potential allows against the blacklist policy and skip installing policymap entries if the corresponding identity would not be allowed in the blacklist.
* Alternatively we could have a blacklist policy stage as part of the policy check in the BPF. A separate map with a set of blacklisted peers which cause the packet handling to jump into the deny logic. Benefit here is that we could even use a different drop reason to highlight that it was a blacklist policy that caused the drop, rather than simply the lack of an allow.

**Comment by jimmyjones2** [comment]
Can it be possible to define a blacklist with exceptions? An example usecase would be a cluster not allowed to access the internet for eg. regulatory reasons - blacklist 0/0, except corp network

**Comment by joestringer** [comment]
@jimmyjones2 I think that a "blacklist with exceptions" is the same as a "whitelist", isn't it? You can achieve this today with a whitelist that only allows the corp network CIDR.

**Comment by tgraf** [comment]
> Can it be possible to define a blacklist with exceptions? An example usecase would be a cluster not allowed to access the internet for eg. regulatory reasons - blacklist 0/0, except corp network

Are you referring to being able to list blacklists in the form of `10.0.0.0/8` except for `[10.0.0.1, 10.1.1.2]`?

**Comment by jimmyjones2** [comment]
> @jimmyjones2 I think that a "blacklist with exceptions" is the same as a "whitelist", isn't it? You can achieve this today with a whitelist that only allows the corp network CIDR.

@joestringer Yes, but some use cases need the whitelist applied globally, rather than trusting project admins, which I don't think it possible today?

**Comment by jimmyjones2** [comment]
> > Can it be possible to define a blacklist with exceptions? An example usecase would be a cluster not allowed to access the internet for eg. regulatory reasons - blacklist 0/0, except corp network
> 
> Are you referring to being able to list blacklists in the form of `10.0.0.0/8` except for `[10.0.0.1, 10.1.1.2]`?

@tgraf Yes

**Comment by aanm** [comment]
@jimmyjones2 What kind of policy deny spec would make more sense for you to use? A "per direction traffic" 1) or a "per field" deny 2).

1) 
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "policy-deny"
spec:
  endpointSelector:
    matchLabels:
      k8s-app: web
  egressDeny:
  - toCIDR:
    - 1.1.1.1/32
  - toEndpoints:
      matchLabels:
        foo: bar
```
2) 
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "policy-deny"
spec:
  endpointSelector:
    matchLabels:
      k8s-app: web
  egress:
  - toCIDRDeny:
    - 1.1.1.1/32
  - toEndpointsDeny:
      matchLabels:
        foo: bar
```

**Comment by aanm** [comment]
Also FYI @awprice and @olemarkus ^^^

**Comment by olemarkus** [comment]
The feature we were looking for was actually #9200 
We are not really _that_ interested in deny rules, but there may be cases where we'd like pods to be able to talk to anything on the internet, but nothing inside the cluster.

In this case, my preference is alternative 1.

**Comment by awprice** [comment]
+1  to option 1.

**Comment by jimmyjones2** [comment]
Happy with option 1. I presume both the following would work?

Block cloud metadata service:

```yaml
  egressDeny:
  - toCIDR:
    - 169.254.169.254/32
```

Block direct internet access:

```yaml
  egressDeny:
  - toCIDRSet:
    - cidr: 0/0
      except:
      - corpNetwork/16
```
