### ISSUE TITLE
Detect kvstore inconsistency and trigger re-creation of state

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#7224]
Instead of relying on periodic re-creation of keys, find way to detect kvstore inconsistency to trigger re-creation of all local state in the kvstore.

Possible ways to trigger the recreation is to create a special key in the kvstore which all agents watch for that then triggers recreation.

Once this is established, the periodic re-creation interval can be increased to a much larger value and potentially disabled entirely for better scale.

**Comment by raybejjani** [comment]
I think have a basic sketch of what this might look like. I'm not sure if I've missed anything (I just dumped a running kvstore). In general, the scheme would be to move overall detection to cilium-operator but each cilium-agent would resync data when triggered. It is likely also good to rate-limit how many nodes are triggered and how often each one is.

**cilium-operator**
Everything here could be done periodically but it is likely less overheard to watch all resources and handle kvstore events. A challenge will be allowing enough time for two different data streams (k8s and the cilium kvstore) to be in sync. 
1. For all labels -> identities seen in CEPs in k8s ensure that a key exists for that identity `cilium/state/identities/v1/id/<SecID>` and that the SecID master key also matches in `cilium/state/identities/v1/value/<labels>/<NodeIP>`. CEPs are updated less often and might be more stable than the kvstore key. When a mismatch is found, trigger a node resync on nodes that own the CEPs.

2. Ensure that `cilium/state/identities/v1/id/<SecID>` and `cilium/state/identities/v1/value/<labels>` are consistent (the value of one is the key of the other). A master key must exist if a node key exists but a master key may exist without node keys (when it is left to expire). When an orphaned node key is seen without a master key, trigger a node resync for the node in the node key.
Note that this  should be handled by the bad-delete handling in cilium-agent so it isn't expected to happen. A long delay to trigger resync may be safest to avoid overloading etcd with full resyncs when it is slow.

3. Ensure that kvstore node entries at `cilium/state/nodes/v1/default/<node>` match k8s Node objects with
```
      io.cilium.network.ipv4-cilium-host: 10.15.0.1
      io.cilium.network.ipv4-health-ip: 10.15.141.22
      io.cilium.network.ipv4-pod-cidr: 10.15.0.0/16
```
annotations. Nodes without the annotations may not be managed by cilium. When a mismatch occurs trigger a resync for that node.

3.1. [this may be a bad idea] Check that all pods on a node are within the `pod-cidr` reported by cilium. I'm not sure what to do if something is mismatched, but this may relate to discussions 
around restarting unmanaged pods.

**cilium-agent**
1. Ensure Delete protections is working correctly (https://github.com/cilium/cilium/issues/7239 and https://github.com/cilium/cilium/issues/7240). We may need tests that simulate etcd being under load.

2. [this may be a bad idea] On every startup and after restoring, cilium-agent will fully resync. This is a bad idea for large clusters as cilium upgrades will clobber etcd. A solution would be to jitter the resync on the nodes. The only use I see for this is to remove a forced resync step during operation, but if cilium-operator does its job this shouldn't matter. It would only be needed if we keep missing mismatches and need to make sure it happens.

3. Triggerable kvstore resync

**3.1** Via an API call: This would then be a CLI command and can be triggered the same way other cilium commands are (via exec). Using this method exclusively means cilium-operator may need exec access within k8s :/

**3.2** Via a specific kvstore key: `cilium/state/rsync/v1/value/<nodeIP> -> {"requested": ""2019-03-26T17:11:51Z", "completed": "2019-03-26T17:11:55Z"}`. The IPs here match the ones advertised in the SecID node keys. The trigger only includes the "requested" JSON field and the node updates it with the "completed" field at the end of a rsync.  
One issue with this approach is that, in cases where cilium-agent is out-of-sync because the kvstore connection is undetectably broken, this key creation will also be missed.

**3.3.** Annotate the k8s Node object: This would work like (3.2) but rely on k8s to move the data around. It avoids the failure mode (3.2) has but I think we were trying to avoid having a node watch itself in k8s.

**Triggering resyncs**
However we trigger a resync, the cilium-agent will have to upsert all keys it owns and delete remote keys that incorrectly belong to it.

- Begin a resync on seeing a resync key `cilium/state/rsync/v1/value/<nodeIP>` create/update for this node where "requested" is further in the future than "completed", or "completed" is missing.

- Upsert and delete Identity node keys `cilium/state/identities/v1/value/<labels>`

- Upsert node discovery key `cilium/state/nodes/v1/default/<node>`

- Update node resync key `cilium/state/rsync/v1/value/<nodeIP>` with completed field

**Comment by tgraf** [comment]
We seem to have gotten kvstore inconsistency under control except when combined with the etcd operator which we are phasing out in favor of CRD mode. Closing this for now.
