### ISSUE TITLE
Cilium 1.4.1 fails because of removed `disable-ipv4` option

### ISSUE THREAD

**Issue by secustor** [cilium/cilium#7266]
## Bug report

**General Information**

- Cilium version (docker image: `1.4.1`)
- Kernel version (`4.15.0-45-generic`)
- Orchestration system version in use ( K8 `v1.13.3` )
- Link to relevant artifacts (policies, deployments scripts, ...)
   - Pod Events https://gist.github.com/secustor/3fb1e248cbe028d1d2f086569e635974
   - Config Map https://gist.github.com/secustor/6891b05759433a3672a7e7d36640618a

**How to reproduce the issue**
1. Create a configuration without `disable-ipv4`
2. run it in a K8 cluster. 
3. Monitor state of pod
4. To fix: add the `disable-ipv4` variable

**Comment by joestringer** [comment]
@secustor Thanks for the report.

Did you observe this while following a particular page in the docs? If so, please link the documentation page where the YAMLs were fetched - in particular for the `DaemonSet` YAML.

The latest v1.4.1 DaemonSet YAML files should no longer rely on the `disable-ipv4` variable as it has been deprecated:

http://docs.cilium.io/en/v1.4/install/upgrade/#deprecated-configmap-options
http://docs.cilium.io/en/v1.4/install/upgrade/#step-3-apply-new-rbac-and-daemonset-definitions

**Comment by joestringer** [comment]
As far as I can tell, assuming that you upgrade to a particular version of Cilium by installing the `DaemonSet` YAMLs for that version (per links above), then this issue should not occur. If you otherwise hit this issue, please reopen/comment or open a new issue reporting the issue and linking to the specific YAMLs being used.

Closing, thanks.
