### ISSUE TITLE
Probe support for perf event maps

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#7830]
We should be able to probe the presence of `CONFIG_BPF_EVENTS` by loading a program which attempts to write into a perf ring buffer. If it fails with `-EOPNOTSUPP` then `cilium monitor` will not work.

**Comment by vadorovsky** [comment]
~As far as I understand, such a probe needs to have a program in userspace which creates a perf ring buffer, then write its file descriptor to BPF map. Then the BPF program should use it. And that BPF program would need to be loaded by the userspace program. Or is there some way to use tc for that?~

~If not, It would be non-trivial to do it with run_probes.sh script, because we would need to somehow use libbpf.~

~I will try to play with gobpf which already handles ring buffers and just add a checker directly in daemon code, if you are OK with that.~

~Sorry if I, as a complete BPF newbie, wrote something stupid.~

Nevermind, I found the `test/bpf/` and looked at `pkg/bpf/perf_linux.go`, I don't need gobpf.

**Comment by joestringer** [comment]
I don't expect this to be entirely trivial, though it shouldn't need to be overly complex either. From the BPF side, all you really need is a simple program that has a perf event channel buffer, then attempt to make the `skb_event_output()` call and observe whether it succeeds or not (and which error code). I suspect that the probes under `bpf/probes` are slightly too simplistic just because we need the ability to somehow fetch out the return result of the `skb_event_output()` call, which is known in the BPF program and will need to be somehow propagated into the userspace program which is launching the probe.

One direction to look at, is that recent versions of `libbpf` / `bpftool` provide some amount of probing, maybe we can just extend those to probe for this support as well, then maybe do something like `bpftool feature probe ...` (https://twitter.com/qeole/status/1118526783790436355)

**Comment by vadorovsky** [comment]
I like the idea of extending `bpftool feature probe ...`, I will try to do that.

**Comment by pchaigno** [comment]
Now that we have the probe manager (see e.g. [`daemon/cmd/kube_proxy_replacement.go`](https://github.com/cilium/cilium/blob/e567f8bfa7e8cc4d71566f224f60d7222d3d874b/daemon/cmd/kube_proxy_replacement.go#L200-L201)), this should be trivial to probe for.

What do we want to do with that information once we have it though? Fatal in the agent? Issue an error log? Disable the collection of events from the datapath?

**Comment by joestringer** [comment]
I think that it makes sense to log a Warning level log that states that Hubble and Cilium monitor output will not work because of the missing configuration. This is not too serious to the operation of the datapath, but it would be nice to detect this and warn users that this may cause subsequent problems for them.

**Comment by ti-mo** [comment]
A lot has changed since this was created, but this particular check still relies on parsing /proc/config.gz. We have an higher-level work item for this: https://github.com/cilium/cilium/issues/22514). Closing this one in favor of the broader one.
