### ISSUE TITLE
Cilium metrics: always show there is a `restoring` state endpoint

### ISSUE THREAD

**Issue by ArthurChiao** [cilium/cilium#8088]
### Phenomenon

On start/restart, Cilium **monitoring metrics always show that there is an endpoint in `restoring` state**, but **in reality, there is no such an endpoint**. Something like this:

### How to reproduce the issue

1. Install Cilium `1.5.1` or `1.5` with docker images
2. On K8S nodes: `curl localhost:9090/metrics 2>/dev/null | grep 'endpoint_state="restoring"'` always return `cilium_endpoint_state{endpoint_state="restoring"} 1`

### General Information

- Cilium version: `v1.5`
- Kernel version: `4.14`
- Orchestration system version in use: `K8S 1.13`

### Trouble Shooting

Digging into the code, i got this call flow:

```shell
runDaemon                                       // daemon/daemon_main.go
  |-NewDaemon                                   // daemon/daemon.go
    |-restoreOldEndpoints                       // daemon/state.go
    | |-readEPsFromDirNames                     // daemon/state.go
    |    for ep in endpints
    |      ParseEndpoint                        // pkg/endpoint/endpoint.go
    |       |-SetStateLocked(StateRestoring)    // pkg/endpoint/endpoint.go
    |-for ep in endpoints                       // daemon/state.go
        if ep is cilium-health:
            continue
        else:
            restore ep, StateRestoring -> StateReady or other states
```

1. On restart, cilium agent will read all endpoints' info from local files with `readEPsFromDirNames`
1. then it loops over all endpoints and calls `ParseEndpoint` for each endpoint, the latter further calls `SetStateLocked` with `StateRestoring` parameter to set the endpoint into `restoring` state,  [code here](https://github.com/cilium/cilium/blob/v1.5/pkg/endpoint/endpoint.go#L1077). `SetStateLocked` will update the monitoring metrics.
1. Later, another for loop actually does the restoration jobs, and sets the endpoint to `StateReady` if everything goes well.
1. But, there is a special endpoint called `cilium-health`, it is cleaned unconditionally and the loop `continue`d, [code here](https://github.com/cilium/cilium/blob/v1.5/daemon/state.go#L110), thus no code will decrease the counter of `restoring` metrics, which **permanently leaves a `restoring` state endpoint in the monitoring metrics**.

**Comment by ArthurChiao** [comment]
I made a quick try by set the state to `ready` before the `continue`, the problem solved:

https://github.com/ArthurChiao/cilium/commit/090841a6ddb51c1c445ae2339e1178ebe75b1306

However, this seems to breaks your deliberately designed FSM, and leaves one additional `ready` state endpoint in the metrics, which doesn't exist either.

Any ideas?

**Comment by ArthurChiao** [comment]
Another way may be skip `inc` the `restoring` state counter if detected it is `cilium-health` endpoint, in `ParseEndpoint()` method.

**Comment by aanm** [comment]
@joestringer Can you take a look, I thought the PR https://github.com/cilium/cilium/pull/7895 would have fixed this.

**Comment by joestringer** [comment]
Hi @ArthurChiao , thanks for the report, and my apologies for the delay as I was out on PTO.

I think that your proposal in the patch above is close, but a bit too specific to the cilium-health endpoint. It's plausible for endpoint restore to fail for a variety of reasons, so a similar bug could be caused in later code that also invokes `continue` lower in the code. 

On master, the `validateEndpoint()` function is responsible for detecting all of these reasons. So, I think the logic you're looking for should be placed directly into `restoreOldEndpoints()` in the `!restore` case here:

https://github.com/cilium/cilium/blob/064c57b9b18eaa420e061255b79161ad31f62d6d/daemon/state.go#L167-L172

Also, rather than changing the state into `endpoint.StateReady`, which would then push the same type of metric leak into the 'ready' label rather than 'restoring' label, instead the endpoint should be placed into `endpoint.StateDisconnected`. I believe that the FSM can be safely extended to add the `StateDisconnected` case in the same switch statement that you used in your patch above.

Would you be willing to make these changes and submit them as a PR against master? We will handle backporting the patch to fix the bug on all affected releases.

**Comment by ArthurChiao** [comment]
Hi @joestringer , thanks for your reply!

Looking at 6f01080, I think it had (unintentionaly? :) ) done the right thing, I will test the latest image and come back.

**Comment by ArthurChiao** [comment]
Upgraded to latest version, problem disappeared. Thanks for your help @joestringer @aanm .
