### ISSUE TITLE
remove string usage as key of SelectorCache.selectors

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#8093]
https://github.com/cilium/cilium/blob/a657ad010af94ea90a4e2b16de201797818c42a3/pkg/policy/selectorcache.go#L171-L172

Using `.String()` to generate a string to store in the map will have implications in the heap usage as well as CPU usage to generate those strings. For example when making a large amount of calls to`FindCachedIdentitySelector` for example.

https://github.com/cilium/cilium/blob/a657ad010af94ea90a4e2b16de201797818c42a3/pkg/policy/selectorcache.go#L473-L481

Follow up of https://github.com/cilium/cilium/pull/7879#discussion_r285592269

**Comment by ianvernon** [comment]
I think keeping a string representation of any `api.*Selector` (`api.EndpointSelector`, `api.FQDNSelector` ) cached within the selector itself is fine. 


The SelectorCache uses the string representation of the selectors because they are the keys in the map, so we can't use the selector itself directly as a key. Using the selectors themselves is a no-go because even if the contents of an `api.EndpointSelector` are the same, it only contains pointers, which will be different for each re-creation of the same selector from JSON, etc.

What about caching the contents of String() within a selector once we use it in the SelectorCache? This would make calls to String() only have an upfront cost of an initial computation, and since selectors are immutable, their string representation would always be the same.

This was the conclusion that @jrajahalme and I came to in [this discussion](https://github.com/cilium/cilium/pull/7879#discussion_r279678355). 

Are you concerned about the usage of strings in general and the effect on heap size? I agree that this will increase memory consumption, but the added benefit in terms of speed of policy calculation / reduction of CPU during policy calculation far outweighs this.
