### ISSUE TITLE
policy identities are not garbage collected in bpf maps

### ISSUE THREAD

**Issue by joulaud** [cilium/cilium#8191]
## Bug report

**General Information**

- Cilium version `1.5.1 6db814405 2019-05-16T12:54:32-07:00 go version go1.12.5 linux/amd64`
- Kernel version `Linux ip-10-X-X-X 4.19.0-0.bpo.2-amd64 #1 SMP Debian 4.19.16-1~bpo9+1 (2019-02-07) x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use : kubernetes `version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.8", GitCommit:"4e209c9383fa00631d124c8adcc011d617339b3c", GitTreeState:"clean", BuildDate:"2019-02-28T18:40:05Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`

**How to reproduce the issue**

1. Cilium cluster with no policies, and kubernetes pods with different labels or annotations per pod.
2. Do a lot of pod creation and destruction with new annotations for each pod each time.
3. Check size of *cilium_policy* bpf maps and see that it only increases even when identities are deleted

For example `bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_policy_00163` give 23360 elements found in the map whereas there is only 11678 identities listed by `cilium identity list`.

This problem cumulated with [bad initial annotation filtering](https://github.com/cilium/cilium/pull/8152) leads to saturation of bpf policy map with really bad side effects.

**Comment by ianvernon** [comment]
In the current releases of Cilium (including v1.5), this is the expected behavior for the policy map. We are aware of this behavior, and have optimized the datapath to account for this in v1.6.

To elaborate further, in Cilium, the PolicyMap is a tuple of the following information:

* Traffic Direction
* Identity
* Port
* Protocol

We synthesize 'allow-all' traffic (e.g., all ingress / egress from all destinations) as allowing all identities at all ports from both traffic directions (ingress and egress).

While allow-all at a certain port is represented by putting the port as '0', and the protocol as 'ANY' (0 as well), sort of like a wildcard, in current versions of Cilium, we do not wildcard for identities. So, to allow all identities in both directions (ingress, egress), we have to insert policymap entries for ingress and egress for each identity, e.g.

* <Ingress,12345,0,0>
* <Egress,12345,0,0>

This means that the map has 2x entries as the number of identities, which 23360/11678 approximates to (2). 

In v1.6, we will have added wildcarding at L3 (i.e., all identities represented by identity '0') for allowing all at L3 and L4, so that allowing all traffic at ingress / egress will be represented by:

* <Ingress,0,0,0>
* <Egress,0,0,0>

**Comment by joulaud** [comment]
@ianvernon thanks for the complete explanation. It is useful.

So my problem is not with the bpf map per se but just with the volume of identities.
At the moment I have 12187 identities in my cluster vs. only 1178 pods.

My hunch is that cilium only creates new identities but never delete them even if there is no pod left matching this identity.

**Comment by joulaud** [comment]
For those interested our current workaround was to increase the size of bpf maps with the `--bpf-policy-map-max` option from https://github.com/cilium/cilium/pull/8071

**Comment by joestringer** [comment]
@joulaud are you running `cilium-operator`? That component is necessary for garbage-collecting unused identities periodically.

**Comment by joulaud** [comment]
We don't have cilium-operator indeed. We used kops default way of installing Cilium.

We will migrate to cilium-operator as soon as we find a way to do it properly.

Closing this ticket as all is clear on my side now.
