### ISSUE TITLE
Allow waiting-to-regenerate from waiting-to-regenerate

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#8493]
This seems to be an unnecessary warning 
```
    - code: Warning
      message: 'Skipped invalid state transition to waiting-to-regenerate due to: Skipped duplicate endpoint regeneration trigger due to one or more identities created or deleted'
      state: waiting-to-regenerate
      timestamp: "2019-06-10T19:00:24Z"
```

https://github.com/cilium/cilium/blob/a4c7f1e55fef91449a4d5ee56e4a6b68bf3dc7b5/pkg/endpoint/policy.go#L424-L428

**Comment by ianvernon** [comment]
We use the return value from `SetStateLocked` to determine whether we need to regenerate in various cases. But, if we are 'waiting-to-regenerate', we do not need to enqueue another regeneration, since the regeneration that is already enqueued will realize whatever state that the current regeneration that is being triggered, needs. 

If we allow this state transition, we would then have several call sites calling `endpoint.Regenerate`, which would enqueue another needless regeneration for this endpoint, since one is already enqueued. We can silence the log in this case, but still return 'false'. Is this an OK compromise?

I'm quite wary about touching the endpoint state machine in something that is going to be backported, and would like to keep the change as minimal as possible.
