### ISSUE TITLE
Unable to upgrade cilium with --install-iptables-rules="false"

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#8910]
cilium options set in `/etc/sysconfig/cilium`
```
CILIUM_OPTS='--k8s-kubeconfig-path /var/lib/cilium/cilium.kubeconfig --kvstore etcd --kvstore-opt etcd.config=/var/lib/cilium/etcd-config.yml --single-cluster-route="false" --masquerade="false" --enable-ipv4="true" --k8s-require-ipv4-pod-cidr="true" --enable-ipv6="false" --k8s-require-ipv6-pod-cidr="false" --enable-legacy-services="false" --ipv4-cluster-cidr-mask-size="16" --ipv4-service-range="192.168.0.0/24" --bpf-ct-global-tcp-max="524288" --bpf-ct-global-any-max="262144" --preallocate-bpf-maps="true" --tofqdns-enable-poller="false" --disable-endpoint-crd="false" --disable-k8s-services="false" --allow-localhost="always" --install-iptables-rules="false" --prepend-iptables-chains="false" --enable-ipsec="false" --debug="false" --log-system-load="true" --monitor-aggregation=none --tunnel=disabled'
```

with these options cilium 1.5.5 runs fine, with current master it fails to start:

```
Aug 14 19:55:15 k8s1 cilium-agent[19644]: level=error msg="Command execution failed" cmd="[iptables -w 5 -t mangle -A CILIUM_PRE_mangle -p tcp -m mark --mark 0x3f8d0200 -m comment --comment cilium: TPROXY to host cilium-dns-egress proxy -j TPROXY --tproxy-mark 0x00000200 --on-port 36159]" error="exit status 1" subsys=iptables
Aug 14 19:55:15 k8s1 cilium-agent[19644]: level=warning msg="iptables: No chain/target/match by that name." subsys=iptables
Aug 14 19:55:15 k8s1 cilium-agent[19644]: level=fatal msg="Error while creating daemon" error="Can't install proxy rules for cilium-dns-egress: exit status 1" subsys=daemon
```

**Comment by jrajahalme** [comment]
I think `--install-iptables-rules="false"` is at fault here. Generally, in a newer version of Cilium we can use a different set of iptables chains than before. If `--install-iptables-rules="false"` indeed prevents installation of those chains and the rules in them, then I would not expect this to work. 1.6 installs the TPROXY rules on demand, and if not installed, L7 proxying is not going to work at all.

One possible fix is to document that `--install-iptables-rules="false"` should not be used on an upgrade. Another would be to make the iptables code to note the missing tables in this case and either complain or ignore the option and install the chains/rules anyway.

Finally, it seems to me that we should deprecate this option altogether and change the iptables handling so that we would first check if the chains/rules exist in the expected configuration and only re-install them if not.

**Comment by joestringer** [comment]
Shouldn't the tproxy rule installation be also gated upon `--install-iptables-rules` and we just document that this breaks L7 policy?

**Comment by brb** [comment]
Keep in mind, that the ipvlan mode is dependent on this flag value: https://docs.cilium.io/en/latest/gettingstarted/ipvlan/. So it's expected that sometimes users will pass `false`.

**Comment by tgraf** [comment]
IPVLAN is already documented to not support L7 right now

**Comment by tgraf** [comment]
> Shouldn't the tproxy rule installation be also gated upon `--install-iptables-rules` and we just document that this breaks L7 policy?

Any objections to this proposal?

**Comment by jrajahalme** [comment]
#8928 only starts the L7 proxy support in the daemon if installing iptables rules is allowed.
