### ISSUE TITLE
Cilium health endpoint should not be created in managed k8s

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#9260]
Having a cilium-health endpoint created in managed k8s will make cilium-health to have an IP allocated from a pod CIDR created by Cilium. This causes 2 issues:

1) `cilium status` will always report that the reachability of endpoints is not possible, which is true since `cilium-health` endpoint does not belong to the CIDR allocated by the cloud provider.

2) Cilium will create node annotations with podCIDRs for which I believe the ipsec configuration depends on.

3) Cilium creates `/16` routes that might overlap with the cloud provider's CIDR. e.g.:
```
10.66.0.0/16 via 10.66.76.52 dev cilium_host  src 10.66.76.52  mtu 1500
10.66.76.52 dev cilium_host  scope link
```

As a solution for 1) we should disable the health endpoint, has already performed by the flannel CNI integration but not done by the remaining CNI chaining integrations.

**Comment by joestringer** [comment]
We have a community user running with Cilium EKS integration who would like to see the EKS mode actually allocate cilium-health endpoint IPs from the EKS IPAM module.

I think this raises two separate cases:
* For chaining modes we should likely just disable health endpoint per the logic above
* Otherwise if Cilium has IPAM logic enabled (via standard or CRD or ENI mode), it should allocate an IP using the IPAM module.

**Comment by jraby** [comment]
I'm still testing cilium in a deployment with kube-router. Starting the health endpoint broke replaced the route for the node's podCIDR, rendering all pods unreachable (`Time to live exceeded`):

before:
```
10.205.3.0/24 dev cni0 proto kernel scope link src 10.205.3.1 
```

after startup:
```
10.205.3.0/24 via 10.205.3.60 dev cilium_host src 10.205.3.60 mtu 1500 
10.205.3.60 dev cilium_host scope link
```
