### ISSUE TITLE
Kubernetes Service CI tests for IPv6

### ISSUE THREAD

**Issue by brb** [cilium/cilium#9362]
Currently, we don't have any Kubernetes Service tests for IPv6.

Adding such tests is relatively straightforward. However, we do not provision k8s with IPv6 enabled in any of the CI jobs. Perhaps we could dedicate one job to run with [k8s IPv4/IPv6 dual-stack](https://kubernetes.io/docs/concepts/services-networking/dual-stack/).

The tests should cover the existing IPv4 cases (ClusterIP, NodePort, ExternalIP, etc).

**Comment by aanm** [comment]
@brb @borkmann long story short it's not possible to configure k8s IPv4/IPv6 dual-stack with k8s 1.16 in our CI. There was a bug in k8s, fixed for 1.17, that makes kubelet panicking when using dual-stack with a CNI plugin. Also, because we have a constrain for the ipv6 CIDR range (`/112`) that is also a problem to run the k8s dual stack since there's a maximum limit that can be set in k8s controller-manager. The only way to run this:

- Setup the CI and kubernetes to use cri-o. If we use cri-o the panic won't occur in kubelet since the CNI setup will be made through cri-o.
- Remove the ipv6 cidr range constrain in cilium. Since we have removed DSR support this constrain can now be removed without any problems.

**Comment by borkmann** [comment]
As discussed deferred to k8s 1.17 release where this would then cover all CI.

**Comment by borkmann** [comment]
Fixed by #10115.
