### ISSUE TITLE
Add slimmer Cilium image

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#9411]
Now that we have bpf templates available in Cilium we could introduce a slimmer version of Cilium image which would only contain the cilium binaries.

- [ ] Templatize the base BPF programs (#9515)
- [ ] Create a new Dockerfile to make this available
- [ ] Add documentation describing the limitations for cilium slimmer image. For example, the inability to use all options available with `cilium endpoint config`.
- [ ] CI? Do we have a small test suite to test if the image could start and perform some basic connectivity tests?

This would solve issue https://github.com/cilium/cilium/issues/8761, https://github.com/cilium/cilium/issues/9361 and https://github.com/cilium/cilium/issues/8760

**Comment by aanm** [comment]
Joe will be looking if having the minimal requirement of kernel 4.19 + having endpoint with and without debug would be enough for an initial release of this image.

**Comment by joestringer** [comment]
I run a 5.0 kernel here and these are the datapath options that I have for endpoints with a pretty standard set of install options:

```
# uname -a
Linux allosaurus 5.0.0-29-generic #31-Ubuntu SMP Thu Sep 12 13:05:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
# cilium bpf sha get 0f2f2d05e7149e1aa55d25e7fe49ca2b8d6fa0fa | sed -e '/IP/d' -e '/MAC/d' -e '/SECLABEL/d' -e '/LXC_ID/d' -e '/_MAP/d'
#include "lib/utils.h"

#define FORCE_LOCAL_POLICY_EVAL_AT_SOURCE 1
#define ENABLE_ROUTING 1
#define ENABLE_ARP_RESPONDER 1
#define ENABLE_HOST_REDIRECT 1
#define LB_L3 1
#define LB_L4 1
#define LOCAL_DELIVERY_METRICS 1
#define CONNTRACK 1
#define CONNTRACK_ACCOUNTING 1
#undef CONNTRACK_LOCAL
#define DEBUG 1
#define LB_DEBUG 1
#define DROP_NOTIFY 1
#define MONITOR_AGGREGATION 3
#undef ENABLE_NAT46
#define TRACE_NOTIFY 1
```

The above looks pretty standard and easy to precompile against. Unfortunately it's a bit more nuanced than this because we also mix in the node configuration:

```
# grep "^#" /var/run/cilium/state/globals/node_config.h | sed -e '/_MAP/d' -e '/LIFETIME/d' -e '/TIMEOUT/d'
#include "lib/utils.h"
#define NAT46_PREFIX { .addr = { 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0x0, 0x0, 0x0, 0x0 } }
#define ENABLE_IPV4 1
#define HEALTH_ID 4
#define HOST_ID 1
#define INIT_ID 5
#define IPV4_GATEWAY 0x6d7f40a
#define IPV4_LOOPBACK 0x12afea9
#define IPV4_MASK 0xffff
#define LB_RR_MAX_SEQ 31
#define MTU 1500
#define TRACE_PAYLOAD_LEN 128ULL
#define UNMANAGED_ID 3
#define WORLD_ID 2
#ifndef CILIUM_NET_MAC
#define CILIUM_NET_MAC { .addr = {0x96,0x11,0x75,0xb3,0x03,0xfe}}
#endif /* CILIUM_NET_MAC */
#define HOST_IFINDEX 9
#define HOST_IFINDEX_MAC { .addr = {0x42,0x38,0x7b,0xdf,0xaa,0x12}}
#define CILIUM_IFINDEX 10
#define EPHERMERAL_MIN 32768
#define ENCAP_VXLAN 1
#define ENCAP_IFINDEX 931
```

Here we have IP addresses, MAC addresses, MTU, device ifindexes. We would basically need to templatize these fields as well so that the base programs and endpoint programs could substitute these in the ELFs that are provided as part of the slimmer image.

Feature-wise we would need to consider which combinations of the following we need:
* IPv4-only vs IPv6-only vs both
* VXLAN vs direct-routing (, chaining)
* Trace aggregation level

I believe that for sockmap and host LB we should be able to just compile with these features and distribute the corresponding BPF ELF objects, then if a user disables these options, simply don't load them. I haven't audited whether these options affect the regular LXC BPF endpoint program compilation.

**Comment by joestringer** [comment]
Relevant, LLVM CPU version selection: https://github.com/cilium/cilium/pull/10804#pullrequestreview-396769678
