### ISSUE TITLE
Create backends for k8s LoadBalancer services

### ISSUE THREAD

**Issue by aanm** [cilium/cilium#9508]
Create Cluster and NodePort backends for Loadbalancer services

**Comment by borkmann** [comment]
(Reported from Brau in Cilium slack.)

**Comment by braudel** [comment]
When running k8s integrated with openstack and creating a service of the type LoadBalancer k8s talks to the openstack API to create a loadbalancer at the openstack level. This LB is set up to   loadbalance traffic into the NodePort ports associated to the service in k8s. Ie:

I) I have deployed k8s 1.15.3 using ubuntu bionic vms (kernel 5.3.0) , cillium 1.6.3 and deleted the kube-proxy daemonset.
2) Then I created a service of type LoadBalancer for the nginx ingress:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  name: ingress-nginx-controller
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
```

This triggers the process and the service ends up looking like this:
```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-10-28T14:24:20Z"
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  name: ingress-nginx-controller
  namespace: ingress-nginx
  resourceVersion: "492320"
  selfLink: /api/v1/namespaces/ingress-nginx/services/ingress-nginx-controller
  uid: 0791dfd9-a027-4dda-80db-b30fb47b10d4
spec:
  clusterIP: 192.200.26.158
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31923
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 31111
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.58.244.96
```

So the service is populated with the clusterip, assigned Nodeports and the openstack loadbalancer's floating ip as expected.

But unfortunately these particular NodePorts do not seem to be created:

```bash
$ curl -w "%{http_code}\n"  -v --header 'Host: kuard.k8s.pipeworks.arm.com' http://192.193.0.9:31923
* Rebuilt URL to: http://192.193.0.9:31923/
*   Trying 192.193.0.9...
* TCP_NODELAY set
* connect to 192.193.0.9 port 31923 failed: Connection refused
* Failed to connect to 192.193.0.9 port 31923: Connection refused
* Closing connection 0
000
curl: (7) Failed to connect to 192.193.0.9 port 31923: Connection refused
```
Which leads to the openstack loadbalancer tcp checks to fail as there is no port to send traffic to.

Using a NodePort service instead of a loadbalancer works, showing that it is not a particular issue of the setup. However using NodePort losses the nice automation setting up the ingress route all the way up to the floaing ip.

**Comment by brb** [comment]
It might not be enough just to provision NodePort BPF services. We might need to create a BPF service for LoadBalancer (external) IP, so this depends on the ExternalIP feature.

**Comment by braudel** [comment]
Hi brb,

Not sure if I am missing something, but if requesting an svc of the type LoadBalancer creates the NodePort all should fall into place as at the openstack-level the loadbalancer is just trying to send traffic to the Nodes on the nodeport:

 
![image](https://user-images.githubusercontent.com/492997/67698344-18f15c80-f9a2-11e9-8d27-d9caa3bd25f5.png)

**Comment by brb** [comment]
Hi @braudel ,

Some loadbalancers (e.g. MetalLB in L2 mode, https://github.com/cilium/cilium/issues/9116) expect a node to handle requests with the destination IP addr = the LoadBalancer SVC external IP addr. So, to fix for all we need to fix https://github.com/cilium/cilium/pull/9092 first.

Anyway, your case should be fixed by https://github.com/cilium/cilium/pull/9510.
