### ISSUE TITLE
Stale etcd kvstore lock deadlock

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#9855]
A situation was observed where no nodes where able to schedule pods due to the kvstore lock acquisition operation timing out. This subsequently caused CNI ADD to timeout.

How to reproduce:
* k8s apiserver was unavailable for 20-30 minutes
* etcd observed peer communication errors in the logs due to the DNS ClusterIP not being routable. This has likely been caused by kube-proxy giving up on providing the ClusterIP iptables rule although this has not been fully confirmed.
* The etcd cluster eventually recovered.
* For a yet unknown reason, kvstore locks have been leaked.
* Incident was noticed
* Kvstore write ability was validated using `cilium kvstore set` command
* The kvstore lock for at least one security identity could no longer be acquired from any node.
* Manual removal of the entire kvstore lock key prefix resolved the situation immediately.

**Comment by aanm** [comment]
One way trigger the kvstore bug.
1) connect to a etcd member (https://node-A:2379) to create a lock with a 25 second lease (the default for cilium)
2) drop all peer packets, not client packets, to and from that etcd member (https://node-A:2380).
3) try releasing that lock immediately. The unlock will fail with the error level=error msg="Unable to unlock kvstore lock" error="etcdserver: request timed out".
4) As soon the unlock fails, resume connectivity dropped in 2), this re-connectivity needs to happen before the lease expires, which means the Unlock on step 3) needs to fail in less than 25 seconds, this is what happen for my case.
5) since the client resumed connectivity with the server in less than 25 seconds, the lease didn't expire which means the server still thinks the client is still holding the lock but the client assumes the lock was unlocked.
